<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Luokka',
		'Categories' => 'Kategoriat',
		'Rubrique' => 'Luokka',
		'Rubriques' => 'Kategoriat',
		'categories' => 'luokat',
		'TheCategorie' => 'Luokka',
		'NoCategoryYet' => 'Luokkaa ei tällaisen luonut',
		'In' => 'Sisällä',
		'AddIn' => 'Lisää',
		'modify' => 'muuttaa',
		'Classify' => 'Luokittele',
		'CategoriesArea' => 'Kategoriat alueella',
		'ProductsCategoriesArea' => 'Tuotteet / Palvelut "luokkiin alue',
		'SuppliersCategoriesArea' => 'Toimittajien luokkiin alue',
		'CustomersCategoriesArea' => 'Asiakkaiden kategoriat alueella',
		'ThirdPartyCategoriesArea' => 'Kolmansien osapuolten luokkiin alue',
		'MembersCategoriesArea' => 'Jäsenet luokat alue',
		'MainCats' => 'Pääryhmään',
		'SubCats' => 'Alaluokat',
		'CatStatistics' => 'Tilastot',
		'CatList' => 'Luettelo catgories',
		'AllCats' => 'Kaikki kategoriat',
		'ViewCat' => 'Näytä luokkien',
		'NewCat' => 'Lisää luokka',
		'NewCategory' => 'Uusi luokka',
		'ModifCat' => 'Muokkaa luokka',
		'CatCreated' => 'Luokka luonut',
		'CreateCat' => 'Luo luokka',
		'CreateThisCat' => 'Luo tähän luokkaan',
		'ValidateFields' => 'Validate aloilla',
		'NoSubCat' => 'N: o alaluokka.',
		'SubCatOf' => 'Alaluokat',
		'FoundCats' => 'Löytyi tuoteryhmät',
		'FoundCatsForName' => 'Kategoriat löydetty nimi:',
		'FoundSubCatsIn' => 'Alaluokat löytyy luokkaan',
		'ErrSameCatSelected' => 'Valittaessa samaan kategoriaan useita kertoja',
		'ErrForgotCat' => 'Unohditte valita luokka',
		'ErrForgotField' => 'Unohditte ilmoitettava kentät',
		'ErrCatAlreadyExists' => 'Tämä nimi on jo käytössä',
		'AddProductToCat' => 'Lisää tämä tuote luokka?',
		'ImpossibleAddCat' => 'Mahdotonta lisätä luokkaan',
		'ImpossibleAssociateCategory' => 'Mahdotonta yhdistää luokka',
		'WasAddedSuccessfully' => '<b> %s</b> on lisätty onnistuneesti.',
		'ObjectAlreadyLinkedToCategory' => 'Osa on jo liitetty tähän luokkaan.',
		'CategorySuccessfullyCreated' => 'Tähän luokkaan %s on lisätty menestys.',
		'ProductIsInCategories' => 'Tuotteen / palvelun omistaa seuraavien luokkien',
		'SupplierIsInCategories' => 'Kolmas osapuoli omistaa seuraavien toimittajien tuoteryhmät',
		'CompanyIsInCustomersCategories' => 'Tämä kolmas osapuoli omistaa seuraavien asiakkaat / näkymät tuoteryhmät',
		'CompanyIsInSuppliersCategories' => 'Tämä kolmas osapuoli omistaa seuraavien toimittajien tuoteryhmät',
		'MemberIsInCategories' => 'Tämä jäsen omistaa seuraaville jäsenille ryhmiin',
		'ProductHasNoCategory' => 'Tämä tuote / palvelu ei ole mitään luokkia',
		'SupplierHasNoCategory' => 'Tämä toimittaja ei ole mitään luokkia',
		'CompanyHasNoCategory' => 'Tämä yritys ei ole mitään luokkia',
		'MemberHasNoCategory' => 'Tämä jäsen ei ole mitään luokkiin',
		'ClassifyInCategory' => 'Luokitella luokkaan',
		'NoneCategory' => 'Ei mitään',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Tämä luokka on jo olemassa samassa paikassa',
		'ReturnInProduct' => 'Takaisin tuotteen / palvelun kortti',
		'ReturnInSupplier' => 'Palaa toimittaja-kortti',
		'ReturnInCompany' => 'Palaa asiakas / näköpiirissä kortti',
		'ContentsVisibleByAll' => 'Sisältö näkyy kaikkien',
		'ContentsVisibleByAllShort' => 'Sisällys näkyviin kaikki',
		'ContentsNotVisibleByAllShort' => 'Sisältö ei näy kaikissa',
		'CategoriesTree' => 'Kategoriat puu',
		'DeleteCategory' => 'Poista luokka',
		'ConfirmDeleteCategory' => 'Oletko varma, että haluat poistaa tämän luokan?',
		'RemoveFromCategory' => 'Poista yhteys Categorie',
		'RemoveFromCategoryConfirm' => 'Oletko varma, että haluat poistaa välinen kauppa-ja luokka?',
		'NoCategoriesDefined' => 'N: o luokkaan',
		'SuppliersCategoryShort' => 'Tavarantoimittajat luokka',
		'CustomersCategoryShort' => 'Asiakkaat luokka',
		'ProductsCategoryShort' => 'Tuotteet luokka',
		'MembersCategoryShort' => 'Jäsenet luokka',
		'SuppliersCategoriesShort' => 'Tavarantoimittajat tuoteryhmät',
		'CustomersCategoriesShort' => 'Asiakkaat tuoteryhmät',
		'CustomersProspectsCategoriesShort' => 'Custo. / prosp. luokat',
		'ProductsCategoriesShort' => 'Tuotteet Tuoteryhmät',
		'MembersCategoriesShort' => 'Jäsenet luokat',
		'ThisCategoryHasNoProduct' => 'Tämä kategoria ei sisällä mitään tuotetta.',
		'ThisCategoryHasNoSupplier' => 'Tämä kategoria ei sisällä mitään toimittaja.',
		'ThisCategoryHasNoCustomer' => 'Tämä kategoria ei sisällä asiakkaalle.',
		'ThisCategoryHasNoMember' => 'Tämä kategoria ei sisällä mitään jäsen.',
		'AssignedToCustomer' => 'Annetaan asiakkaalle',
		'AssignedToTheCustomer' => 'Annetaan asiakkaan',
		'InternalCategory' => 'Inernal luokka',
		'CategoryContents' => 'Luokka sisältö',
		'CategId' => 'Luokka id',
		'CatSupList' => 'Luettelo toimittaja tuoteryhmät',
		'CatCusList' => 'Luettelo asiakas / näköpiirissä tuoteryhmät',
		'CatProdList' => 'Luettelo tuotteista tuoteryhmät',
		'CatMemberList' => 'Jäsenlista luokkien',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>