<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Luokka',
		'Categories' => 'Kategoriat',
		'Rubrique' => 'Luokka',
		'Rubriques' => 'Kategoriat',
		'categories' => 'luokat',
		'TheCategorie' => 'Luokka',
		'NoCategoryYet' => 'Luokkaa ei tällaisen luonut',
		'In' => 'Sisällä',
		'AddIn' => 'Lisää',
		'modify' => 'muuttaa',
		'Classify' => 'Luokittele',
		'CategoriesArea' => 'Kategoriat alueella',
		'ProductsCategoriesArea' => 'Tuotteet / Palvelut "luokkiin alue',
		'SuppliersCategoriesArea' => 'Toimittajien luokkiin alue',
		'CustomersCategoriesArea' => 'Asiakkaiden kategoriat alueella',
		'ThirdPartyCategoriesArea' => 'Kolmansien osapuolten luokkiin alue',
		'MembersCategoriesArea' => 'Jäsenet luokat alue',
		'MainCats' => 'Pääryhmään',
		'SubCats' => 'Alaluokat',
		'CatStatistics' => 'Tilastot',
		'CatList' => 'Luettelo catgories',
		'AllCats' => 'Kaikki kategoriat',
		'ViewCat' => 'Näytä luokkien',
		'NewCat' => 'Lisää luokka',
		'NewCategory' => 'Uusi luokka',
		'ModifCat' => 'Muokkaa luokka',
		'CatCreated' => 'Luokka luonut',
		'CreateCat' => 'Luo luokka',
		'CreateThisCat' => 'Luo tähän luokkaan',
		'ValidateFields' => 'Validate aloilla',
		'NoSubCat' => 'N: o alaluokka.',
		'SubCatOf' => 'Alaluokat',
		'FoundCats' => 'Löytyi tuoteryhmät',
		'FoundCatsForName' => 'Kategoriat löydetty nimi:',
		'FoundSubCatsIn' => 'Alaluokat löytyy luokkaan',
		'ErrSameCatSelected' => 'Valittaessa samaan kategoriaan useita kertoja',
		'ErrForgotCat' => 'Unohditte valita luokka',
		'ErrForgotField' => 'Unohditte ilmoitettava kentät',
		'ErrCatAlreadyExists' => 'Tämä nimi on jo käytössä',
		'AddProductToCat' => 'Lisää tämä tuote luokka?',
		'ImpossibleAddCat' => 'Mahdotonta lisätä luokkaan',
		'ImpossibleAssociateCategory' => 'Mahdotonta yhdistää luokka',
		'WasAddedSuccessfully' => '<b> %s</b> on lisätty onnistuneesti.',
		'ObjectAlreadyLinkedToCategory' => 'Osa on jo liitetty tähän luokkaan.',
		'CategorySuccessfullyCreated' => 'Tähän luokkaan %s on lisätty menestys.',
		'ProductIsInCategories' => 'Tuotteen / palvelun omistaa seuraavien luokkien',
		'SupplierIsInCategories' => 'Kolmas osapuoli omistaa seuraavien toimittajien tuoteryhmät',
		'CompanyIsInCustomersCategories' => 'Tämä kolmas osapuoli omistaa seuraavien asiakkaat / näkymät tuoteryhmät',
		'CompanyIsInSuppliersCategories' => 'Tämä kolmas osapuoli omistaa seuraavien toimittajien tuoteryhmät',
		'MemberIsInCategories' => 'Tämä jäsen omistaa seuraaville jäsenille ryhmiin',
		'ProductHasNoCategory' => 'Tämä tuote / palvelu ei ole mitään luokkia',
		'SupplierHasNoCategory' => 'Tämä toimittaja ei ole mitään luokkia',
		'CompanyHasNoCategory' => 'Tämä yritys ei ole mitään luokkia',
		'MemberHasNoCategory' => 'Tämä jäsen ei ole mitään luokkiin',
		'ClassifyInCategory' => 'Luokitella luokkaan',
		'NoneCategory' => 'Ei mitään',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Tämä luokka on jo olemassa samassa paikassa',
		'ReturnInProduct' => 'Takaisin tuotteen / palvelun kortti',
		'ReturnInSupplier' => 'Palaa toimittaja-kortti',
		'ReturnInCompany' => 'Palaa asiakas / näköpiirissä kortti',
		'ContentsVisibleByAll' => 'Sisältö näkyy kaikkien',
		'ContentsVisibleByAllShort' => 'Sisällys näkyviin kaikki',
		'ContentsNotVisibleByAllShort' => 'Sisältö ei näy kaikissa',
		'CategoriesTree' => 'Kategoriat puu',
		'DeleteCategory' => 'Poista luokka',
		'ConfirmDeleteCategory' => 'Oletko varma, että haluat poistaa tämän luokan?',
		'RemoveFromCategory' => 'Poista yhteys Categorie',
		'RemoveFromCategoryConfirm' => 'Oletko varma, että haluat poistaa välinen kauppa-ja luokka?',
		'NoCategoriesDefined' => 'N: o luokkaan',
		'SuppliersCategoryShort' => 'Tavarantoimittajat luokka',
		'CustomersCategoryShort' => 'Asiakkaat luokka',
		'ProductsCategoryShort' => 'Tuotteet luokka',
		'MembersCategoryShort' => 'Jäsenet luokka',
		'SuppliersCategoriesShort' => 'Tavarantoimittajat tuoteryhmät',
		'CustomersCategoriesShort' => 'Asiakkaat tuoteryhmät',
		'CustomersProspectsCategoriesShort' => 'Custo. / prosp. luokat',
		'ProductsCategoriesShort' => 'Tuotteet Tuoteryhmät',
		'MembersCategoriesShort' => 'Jäsenet luokat',
		'ThisCategoryHasNoProduct' => 'Tämä kategoria ei sisällä mitään tuotetta.',
		'ThisCategoryHasNoSupplier' => 'Tämä kategoria ei sisällä mitään toimittaja.',
		'ThisCategoryHasNoCustomer' => 'Tämä kategoria ei sisällä asiakkaalle.',
		'ThisCategoryHasNoMember' => 'Tämä kategoria ei sisällä mitään jäsen.',
		'AssignedToCustomer' => 'Annetaan asiakkaalle',
		'AssignedToTheCustomer' => 'Annetaan asiakkaan',
		'InternalCategory' => 'Inernal luokka',
		'CategoryContents' => 'Luokka sisältö',
		'CategId' => 'Luokka id',
		'CatSupList' => 'Luettelo toimittaja tuoteryhmät',
		'CatCusList' => 'Luettelo asiakas / näköpiirissä tuoteryhmät',
		'CatProdList' => 'Luettelo tuotteista tuoteryhmät',
		'CatMemberList' => 'Jäsenlista luokkien',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>