<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Kaupalliset',
		'CommercialArea' => 'Kaupallinen ala',
		'CommercialCard' => 'Kaupalliset kortti',
		'CustomerArea' => 'Asiakkaat alueella',
		'Customer' => 'Asiakas',
		'Customers' => 'Asiakkaat',
		'Prospect' => 'Esitetilaus',
		'Prospects' => 'Näkymät',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Poista toiminto / tehtävä',
		'NewAction' => 'Uusi toimi / tehtävä',
		'AddAction' => 'Lisää toiminta / tehtävä',
		'AddAnAction' => 'Lisää toiminta / tehtävä',
		'AddActionRendezVous' => 'Lisää Rendezvous tehtävä',
		'Rendez-Vous' => 'Rendezvous',
		'ConfirmDeleteAction' => 'Oletko varma, että haluat poistaa tämän tehtävän?',
		'CardAction' => 'Toimi-kortti',
		'PercentDone' => 'Prosenttiosuus tehnyt',
		'ActionOnCompany' => 'Task noin yritys',
		'ActionOnContact' => 'Task noin yhteyttä',
		'TaskRDV' => 'Kokoukset',
		'TaskRDVWith' => 'Tapaaminen %s',
		'ShowTask' => 'Näytä tehtävä',
		'ShowAction' => 'Näytä toiminta',
		'ActionsReport' => 'Toimet raportti',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Myyntiedustaja',
		'SalesRepresentatives' => 'Myyntiedustajat',
		'SalesRepresentativeFollowUp' => 'Myyntiedustajaasi (follow-up)',
		'SalesRepresentativeSignature' => 'Myyntiedustajaasi (allekirjoitus)',
		'CommercialInterlocutor' => 'Kaupalliset keskustelukumppani',
		'ErrorWrongCode' => 'Väärä koodi',
		'NoSalesRepresentativeAffected' => 'Mitään erityistä myyntiedustajaasi vaikuttaa',
		'ShowCustomer' => 'Näytä asiakas',
		'ShowProspect' => 'Näytä näköpiirissä',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Luettelo näkymät',
		'ListOfCustomers' => 'Luettelo asiakkaille',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'Viimeisin %s tehnyt tehtävänsä',
		'LastRecordedTasks' => 'Viimeisin kirjataan tehtävät',
		'LastActionsToDo' => 'Viimeisin %s vanhin toimia ei ole saatu',
		'DoneAndToDoActionsFor' => 'Tehty ja tehdä tehtäviä %s',
		'DoneAndToDoActions' => 'Tehty ja tehdä tehtäviä',
		'DoneActions' => 'Tehty toimia',
		'DoneActionsFor' => 'Tehty toimia %s',
		'ToDoActions' => 'Puutteellinen toimet',
		'ToDoActionsFor' => 'Puutteellinen toimia %s',
		'SendPropalRef' => 'Lähetä kaupallinen ehdotus %s',
		'SendOrderRef' => 'Lähetä jotta %s',
		'StatusNotApplicable' => 'Ei sovelleta',
		'StatusActionToDo' => 'Voit tehdä',
		'StatusActionDone' => 'Tehty',
		'StatusActionInProcess' => 'In process',
		'MyActionsAsked' => 'Toimet olen kirjataan',
		'MyActionsToDo' => 'Toimet Olen tehdä',
		'MyActionsDone' => 'Toimet vaikuttaa minusta',
		'TasksHistoryForThisContact' => 'Toimet tähän yhteyttä',
		'LastProspectDoNotContact' => 'Älä yhteyttä',
		'LastProspectNeverContacted' => 'Älä koskaan yhteyttä',
		'LastProspectToContact' => 'Voit ottaa yhteyttä',
		'LastProspectContactInProcess' => 'Yhteystiedot prosessi',
		'LastProspectContactDone' => 'Yhteystiedot tehnyt',
		'DateActionPlanned' => 'Päiväys toimia varten',
		'DateActionDone' => 'Päiväys toiminta tapahtuu',
		'ActionAskedBy' => 'Toimi pyytänyt',
		'ActionAffectedTo' => 'Toiminta vaikuttaa',
		'ActionDoneBy' => 'Toiminta tapahtuu',
		'ActionUserAsk' => 'Tallennettu',
		'ErrorStatusCantBeZeroIfStarted' => 'Jos kenttä <b>"Päiväys tehtävä</b> on täytetty, toiminta on alkanut (tai valmis), joten alalla" <b>Tila</b> "ei voi olla 0%%.',
		'ActionAC_TEL' => 'Puhelinsoitto',
		'ActionAC_FAX' => 'Lähetä faksi',
		'ActionAC_PROP' => 'Lähetä ehdotus',
		'ActionAC_EMAIL' => 'Lähetä sähköpostiviesti',
		'ActionAC_RDV' => 'Kokoukset',
		'ActionAC_FAC' => 'Lähetä laskutustietosi',
		'ActionAC_REL' => 'Lähetä laskutustilanteesi (muistutus)',
		'ActionAC_CLO' => 'Sulje',
		'ActionAC_EMAILING' => 'Lähetä massa sähköpostia',
		'ActionAC_COM' => 'Lähetä tilata postitse',
		'ActionAC_SHIP' => 'Lähetä toimitus postitse',
		'ActionAC_SUP_ORD' => 'Lähetä toimittaja tilaa postitse',
		'ActionAC_SUP_INV' => 'Lähetä toimittaja lasku postitse',
		'ActionAC_OTH' => 'Muut',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Prospect tila',
		'DraftPropals' => 'Suunnitelmiin liiketoimintaehdotukset',
		'SearchPropal' => 'Etsi kaupallinen ehdotuksen'
);
?>