<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$orders = array(
		'CHARSET' => 'UTF-8',
		'OrdersArea' => 'Asiakkaiden tilausten alueella',
		'SuppliersOrdersArea' => 'Toimittajien tilaukset alueella',
		'OrderCard' => 'Tilaa kortti',
		'Order' => 'Tilata',
		'Orders' => 'Tilaukset',
		'OrderFollow' => 'Seuranta',
		'OrderDate' => 'Tilaa päivämäärä',
		'NewOrder' => 'Uusi järjestys',
		'ToOrder' => 'Tee jotta',
		'MakeOrder' => 'Tee jotta',
		'SupplierOrder' => 'Toimittaja jotta',
		'SuppliersOrders' => 'Toimittajien tilaukset',
		'SuppliersOrdersRunning' => 'Nykyinen toimittajien tilaukset',
		'CustomerOrder' => 'Asiakas jotta',
		'CustomersOrders' => 'Asiakkaiden tilausten',
		'CustomersOrdersRunning' => 'Nykyisten asiakkaiden tilausten',
		'CustomersOrdersAndOrdersLines' => 'Asiakkaan tilaukset ja tilaukset "linjat',
		'OrdersToValid' => 'Tilauksia voimassa',
		'OrdersToBill' => 'Tilaukset laskuttaa',
		'OrdersInProcess' => 'Tilaukset prosessi',
		'OrdersToProcess' => 'Tilausten käsittely',
		'StatusOrderCanceledShort' => 'Peruutettu',
		'StatusOrderDraftShort' => 'Vedos',
		'StatusOrderValidatedShort' => 'Validoidut',
		'StatusOrderOnProcessShort' => 'Prosessissa',
		'StatusOrderProcessedShort' => 'Jalostettu',
		'StatusOrderToBillShort' => 'Bill',
		'StatusOrderApprovedShort' => 'Hyväksyttiin',
		'StatusOrderRefusedShort' => 'Kieltäydytty',
		'StatusOrderToProcessShort' => 'Käsitellä',
		'StatusOrderReceivedPartiallyShort' => 'Osittain saanut',
		'StatusOrderReceivedAllShort' => 'Kaikki saivat',
		'StatusOrderCanceled' => 'Peruutettu',
		'StatusOrderDraft' => 'Luonnos (on vahvistettu)',
		'StatusOrderValidated' => 'Validoidut',
		'StatusOrderOnProcess' => 'Prosessissa',
		'StatusOrderProcessed' => 'Jalostettu',
		'StatusOrderToBill' => 'Bill',
		'StatusOrderApproved' => 'Hyväksyttiin',
		'StatusOrderRefused' => 'Kieltäydytty',
		'StatusOrderReceivedPartially' => 'Osittain saanut',
		'StatusOrderReceivedAll' => 'Kaikki saivat',
		'DraftOrWaitingApproved' => 'Esitys tai hyväksytty ei vielä määrännyt',
		'DraftOrWaitingShipped' => 'Esitys tai validoitua ole vielä lähetetty',
		'MenuOrdersToBill' => 'Tilaukset laskuttaa',
		'SearchOrder' => 'Haku jotta',
		'Sending' => 'Lähettävä',
		'Sendings' => 'Sendings',
		'ShipProduct' => 'Laiva tuote',
		'Discount' => 'Discount',
		'CreateOrder' => 'Luo Tilaa',
		'RefuseOrder' => 'Jätteiden jotta',
		'ApproveOrder' => 'Hyväksy jotta',
		'ValidateOrder' => 'Validate jotta',
		'DeleteOrder' => 'Poista jotta',
		'CancelOrder' => 'Peruuta tilaus',
		'AddOrder' => 'Lisää jotta',
		'AddToMyOrders' => 'Add to my tilaukset',
		'AddToOtherOrders' => 'Lisää muut tilaukset',
		'ShowOrder' => 'Näytä jotta',
		'NoOpenedOrders' => 'N: o avataan tilaukset',
		'NoOtherOpenedOrders' => 'Mikään muu avataan tilaukset',
		'OtherOrders' => 'Muut tilaukset',
		'LastOrders' => 'Viimeisin %s tilaukset',
		'LastModifiedOrders' => 'Viimeisin %s muunnettu tilaukset',
		'LastClosedOrders' => 'Viimeisin %s suljettu tilaukset',
		'AllOrders' => 'Kaikki tilaukset',
		'NbOfOrders' => 'Määrä tilauksia',
		'OrdersStatistics' => 'Tilaukset tilastot',
		'OrdersStatisticsSuppliers' => 'Toimittaja tilaukset tilastot',
		'NumberOfOrdersByMonth' => 'Määrä tilauksia kuukausittain',
		'AmountOfOrdersByMonthHT' => 'määrä tilauksia kuukausittain (ilman veroja)',
		'ListOfOrders' => 'Luettelo tilaukset',
		'CloseOrder' => 'Sulje jotta',
		'ConfirmCloseOrder' => 'Oletko varma, että haluat sulkea tämän tilauksen? Kun tilaus on päättynyt, se voidaan laskuttaa.',
		'ConfirmCloseOrderIfSending' => 'Oletko varma, että haluat sulkea tämän tilauksen? Sinun on lähellä tilauksen vasta, kun kaikki merenkulku on valmis.',
		'ConfirmDeleteOrder' => 'Oletko varma, että haluat poistaa tämän tilauksen?',
		'ConfirmValidateOrder' => 'Oletko varma, että haluamme vahvistaa tämän määräyksen nojalla <b>nimi %s?</b>',
		'ConfirmCancelOrder' => 'Oletko varma, että haluat peruuttaa tämän tilauksen?',
		'ConfirmMakeOrder' => 'Oletko varma, että haluat vahvistaa olet tehnyt tämän <b>tilauksen %s?</b>',
		'GenerateBill' => 'Luo lasku',
		'ClassifyBilled' => 'Luokittele "Laskutetun"',
		'ComptaCard' => 'Kirjanpito-kortti',
		'DraftOrders' => 'Luonnos tilaukset',
		'RelatedOrders' => 'Aiheeseen liittyvät tilaukset',
		'OnProcessOrders' => 'Prosessissa tilaukset',
		'RefOrder' => 'Ref. tilata',
		'RefCustomerOrder' => 'Ref. asiakas jotta',
		'CustomerOrder' => 'Asiakas jotta',
		'RefCustomerOrderShort' => 'Ref. asiakasnumero. tilata',
		'SendOrderByMail' => 'Lähetä tilata postitse',
		'ActionsOnOrder' => 'Toimia, jotta',
		'NoArticleOfTypeProduct' => 'N: o artikkeli tyypin "tuote" niin ei shippable artikkeli tässä tilauksessa',
		'OrderMode' => 'Jotta menetelmä',
		'AuthorRequest' => 'Pyydä tekijä',
		'UseCustomerContactAsOrderRecipientIfExist' => 'Käytä asiakkaan yhteystiedot, jos se on määritetty sijaan kolmannen osapuolen osoite jotta vastaanottajan osoite',
		'RunningOrders' => 'Toimitussuhteet prosessi',
		'UserWithApproveOrderGrant' => 'Useres myönnetään "hyväksyä tilauksia" lupaa.',
		'Error_COMMANDE_SUPPLIER_ADDON_NotDefined' => 'Constant COMMANDE_SUPPLIER_ADDON ole määritelty',
		'Error_COMMANDE_ADDON_NotDefined' => 'Constant COMMANDE_ADDON ole määritelty',
		'Error_FailedToLoad_COMMANDE_SUPPLIER_ADDON_File' => 'Failed to load module file \' %s\'',
		'Error_FailedToLoad_COMMANDE_ADDON_File' => 'Failed to load module file \' %s\'',
		'OrderSource0' => 'Kaupalliset ehdotus',
		'OrderSource1' => 'Internet',
		'OrderSource2' => 'Mail kampanja',
		'OrderSource3' => 'Puhelin compain',
		'OrderSource4' => 'Faksi kampanja',
		'OrderSource5' => 'Kaupalliset',
		'OrderSource6' => 'Varastoida',
		'QtyOrdered' => 'Kpl velvoitti',
		'AddDeliveryCostLine' => 'Lisää toimitus kustannukset linja ilmoitetaan paino, jotta',
		'PDFEinsteinDescription' => 'Täydellinen jotta malli (logo. ..)',
		'OrderLine' => 'Tilaa linja',
		'PaymentOrderRef' => 'Maksutoimisto jotta %s',
		'CloneOrder' => 'Klooni jotta',
		'ConfirmCloneOrder' => 'Oletko varma, että haluat klooni tässä <b>järjestyksessä %s?</b>',
		'OrderToProcess' => 'Jotta prosessi',
		'TypeContact_commande_internal_SALESREPFOLL' => 'Edustaja seurantaan asiakkaan tilauksen',
		'TypeContact_commande_internal_SHIPPING' => 'Edustaja seurantaan merenkulku',
		'TypeContact_commande_external_BILLING' => 'Asiakkaan lasku yhteystiedot',
		'TypeContact_commande_external_SHIPPING' => 'Asiakas merenkulku yhteystiedot',
		'TypeContact_commande_external_CUSTOMER' => 'Asiakas ottaa yhteyttä seurantaan, jotta',
		'TypeContact_order_supplier_internal_SALESREPFOLL' => 'Edustaja seurantaan toimittaja järjestys',
		'TypeContact_order_supplier_internal_SHIPPING' => 'Edustaja seurantaan merenkulku',
		'TypeContact_order_supplier_external_BILLING' => 'Toimittajan lasku yhteystiedot',
		'TypeContact_order_supplier_external_SHIPPING' => 'Toimittajan merenkulku yhteystiedot',
		'TypeContact_order_supplier_external_CUSTOMER' => 'Toimittajan yhteystiedot seurantaan, jotta',
		'PDFEdisonDescription' => 'Yksinkertainen, jotta malli',
		'PDFQuevedoDescription' => 'Täydellinen, jotta malli Espanjan RE ja IRPF',
		'DispatchSupplierOrder' => 'Vastaanottaminen toimittaja järjestys %s',
		'SuppliersOrdersToProcess' => 'Toimittajan tilauksia käsitellä',
		'StatusOrderSentShort' => 'Meneillään',
		'ShippingExist' => 'Lähetys olemassa',
		'UnvalidateOrder' => 'Unvalidate järjestys',
		'ConfirmUnvalidateOrder' => 'Oletko varma että haluat palauttaa järjestyksen <b>%s</b> Luonnos-tilaan?',
		'OrderByMail' => 'Posti',
		'OrderByFax' => 'Faksin',
		'OrderByEMail' => 'Sähköposti',
		'OrderByWWW' => 'Online',
		'OrderByPhone' => 'Puhelin',
);
?>