<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$propal = array(
		'CHARSET' => 'UTF-8',
		'Proposals' => 'Kaupalliset ehdotuksia',
		'Proposal' => 'Kaupalliset ehdotus',
		'ProposalShort' => 'Ehdotus',
		'ProposalsDraft' => 'Luonnos kaupallinen ehdotuksia',
		'ProposalDraft' => 'Luonnos kaupallinen ehdotus',
		'ProposalsOpened' => 'Avoinna kaupallinen ehdotuksia',
		'Prop' => 'Kaupalliset ehdotuksia',
		'CommercialProposal' => 'Kaupalliset ehdotus',
		'CommercialProposals' => 'Kaupalliset ehdotuksia',
		'ProposalCard' => 'Ehdotus kortti',
		'NewProp' => 'Uusia kaupallisia ehdotus',
		'NewProposal' => 'Uusia kaupallisia ehdotus',
		'NewPropal' => 'Uusi ehdotus',
		'Prospect' => 'Esitetilaus',
		'ProspectList' => 'Esitetilaus luettelo',
		'DeleteProp' => 'Poista kaupallinen ehdotus',
		'ValidateProp' => 'Validate kaupallinen ehdotus',
		'AddProp' => 'Lisää ehdotus',
		'ConfirmDeleteProp' => 'Oletko varma, että haluat poistaa tämän kaupallisen ehdotusta?',
		'ConfirmValidateProp' => 'Oletko varma, että haluat vahvistaa kaupallista ehdotusta?',
		'LastPropals' => 'Viimeisin %s ehdotuksia',
		'LastClosedProposals' => 'Viimeisin %s suljettu ehdotuksia',
		'LastModifiedProposals' => 'Viimeisin %s muutetut ehdotukset',
		'AllPropals' => 'Kaikki ehdotukset',
		'LastProposals' => 'Viimeisin ehdotuksia',
		'SearchAProposal' => 'Haku ehdotuksen',
		'ProposalsStatistics' => 'Kaupalliset ehdotuksia tilastot',
		'NumberOfProposalsByMonth' => 'Lukumäärä kuukausittain',
		'AmountOfProposalsByMonthHT' => 'Määrä kuukausittain (ilman veroja)',
		'NbOfProposals' => 'Numero kaupallisten ehdotuksia',
		'ShowPropal' => 'Näytä ehdotus',
		'PropalsDraft' => 'Drafts',
		'PropalsOpened' => 'Avoinna',
		'PropalsNotBilled' => 'Suljettu ei laskuteta',
		'PropalStatusDraft' => 'Luonnos (on vahvistettu)',
		'PropalStatusValidated' => 'Validoidut (ehdotus on avattu)',
		'PropalStatusOpened' => 'Validoidut (ehdotus on avattu)',
		'PropalStatusClosed' => 'Suljettu',
		'PropalStatusSigned' => 'Allekirjoitettu (laskuttaa)',
		'PropalStatusNotSigned' => 'Ei ole kirjautunut (suljettu)',
		'PropalStatusBilled' => 'Laskutetun',
		'PropalStatusDraftShort' => 'Vedos',
		'PropalStatusValidatedShort' => 'Validoidut',
		'PropalStatusOpenedShort' => 'Avoinna',
		'PropalStatusClosedShort' => 'Suljettu',
		'PropalStatusSignedShort' => 'Allekirjoitettu',
		'PropalStatusNotSignedShort' => 'Ei ole kirjautunut',
		'PropalStatusBilledShort' => 'Laskutetun',
		'PropalsToClose' => 'Kaupalliset ehdotuksia lähellä',
		'PropalsToBill' => 'Allekirjoitettu kaupallinen ehdotuksia bill',
		'ListOfProposals' => 'Luettelo kaupallisista ehdotuksia',
		'ActionsOnPropal' => 'Toimia, ehdotus',
		'NoOpenedPropals' => 'N: o avataan kaupalliseen ehdotuksia',
		'NoOtherOpenedPropals' => 'Mikään muu avataan kaupalliseen ehdotuksia',
		'RefProposal' => 'Kaupalliset ehdotus ref',
		'SendPropalByMail' => 'Lähetä kaupallinen ehdotus postitse',
		'FileNotUploaded' => 'Tiedosto ei ole ladattu',
		'FileUploaded' => 'Tiedosto on siirretty onnistuneesti',
		'AssociatedDocuments' => 'Asiakirjat kanssa assosioituneet ehdotus:',
		'ErrorCantOpenDir' => 'Ei voi avata hakemistoon',
		'DatePropal' => 'Päiväys Ehdotuksen',
		'DateEndPropal' => 'Päiväys loppuun voimassaoloaika',
		'DateEndPropalShort' => 'Voimassaolo päättyy',
		'ValidityDuration' => 'Voimassaolo kesto',
		'CloseAs' => 'Sulje joiden tila',
		'ClassifyBilled' => 'Luokittele laskutetaan',
		'BuildBill' => 'Rakenna lasku',
		'ErrorPropalNotFound' => 'Propal %s ei löydy',
		'Estimate' => 'Arvio:',
		'EstimateShort' => 'Arvio',
		'OtherPropals' => 'Muut ehdotukset',
		'CopyPropalFrom' => 'Luo kaupallinen ehdotus kopioimalla olemassa olevan ehdotuksen',
		'CreateEmptyPropal' => 'Luo tyhjä kaupallinen ehdotuksia vierge tai luettelo tuotteet / palvelut',
		'DefaultProposalDurationValidity' => 'Oletus kaupallinen ehdotus voim. kesto (päivinä)',
		'UseCustomerContactAsPropalRecipientIfExist' => 'Käytä asiakkaan yhteystiedot, jos se on määritetty sijaan kolmannen osapuolen osoite ehdotus vastaanottajan osoite',
		'ClonePropal' => 'Klooni kaupallinen ehdotus',
		'ConfirmClonePropal' => 'Oletko varma, että haluat klooni kaupallista <b>ehdotus %s?</b>',
		'ConfirmReOpenProp' => 'Oletko varma että haluat avata takaisin kaupallisen ehdotuksen <b>%s?</b>',
		'ProposalsAndProposalsLines' => 'Kaupalliset ehdotusta ja linjat',
		'ProposalLine' => 'Ehdotus linja',
		'ProposalLines' => 'Proposal lines',
		'AvailabilityPeriod' => 'Saatavuus viive',
		'SetAvailability' => 'Aseta saatavuus viive',
		'AfterOrder' => 'tilauksesta',
		////////// Availability //////////
		'AvailabilityTypeAV_NOW' => 'Välitön',
		'AvailabilityTypeAV_1W' => '1 viikko',
		'AvailabilityTypeAV_2W' => '2 viikkoa',
		'AvailabilityTypeAV_3W' => '3 viikkoa',
		'AvailabilityTypeAV_1M' => '1 kuukausi',
		////////// Types de contacts //////////
		'TypeContact_propal_internal_SALESREPFOLL' => 'Edustaja seurantaan ehdotus',
		'TypeContact_propal_external_BILLING' => 'Asiakkaan lasku yhteystiedot',
		'TypeContact_propal_external_CUSTOMER' => 'Asiakas ottaa yhteyttä seurantaan ehdotus',
		// Document models
		'DocModelAzurDescription' => 'Täydellinen ehdotus malli (logo. ..)',
		'DocModelJauneDescription' => 'Jaune ehdotus malli',
		'Numbershort' => 'N°',
		'LinkdedOrders' => 'Linked orders'
);
?>