<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Warehouse-kortti',
		'Warehouse' => 'Warehouse',
		'NewWarehouse' => 'Uusi varasto / Kanta-alue',
		'MenuNewWarehouse' => 'Uusi varasto',
		'WarehouseOpened' => 'Warehouse avattu',
		'WarehouseClosed' => 'Warehouse suljettu',
		'WarehouseSource' => 'Lähde varasto',
		'WarehouseTarget' => 'Kohdekieli varasto',
		'ValidateSending' => 'Poista lähettäminen',
		'CancelSending' => 'Peruuta lähettäminen',
		'DeleteSending' => 'Poista lähettäminen',
		'Stock' => 'Kanta',
		'Stocks' => 'Varastot',
		'Movement' => 'Movement',
		'Movements' => 'Liikkeet',
		'ErrorWarehouseRefRequired' => 'Warehouse viite nimi tarvitaan',
		'ErrorWarehouseLabelRequired' => 'Warehouse etiketissä on',
		'CorrectStock' => 'Oikea varastossa',
		'ListOfWarehouses' => 'Luettelo varastoissa',
		'ListOfStockMovements' => 'Luettelo varastojen muutokset',
		'StocksArea' => 'Varastot alueella',
		'Location' => 'Lieu',
		'LocationSummary' => 'Lyhyt nimi sijainti',
		'NumberOfProducts' => 'Kokonaismäärä tuotteet',
		'LastMovement' => 'Viimeisin liikkuvuus',
		'LastMovements' => 'Viimeisin liikkeet',
		'Units' => 'Yksiköt',
		'Unit' => 'Yksikkö',
		'StockCorrection' => 'Oikea varastossa',
		'StockMovement' => 'Siirto',
		'StockMovements' => 'Kanta siirrot',
		'NumberOfUnit' => 'Kappalemäärä',
		'TotalStock' => 'Yhteensä varastossa',
		'StockTooLow' => 'Kanta liian alhainen',
		'EnhancedValue' => 'Value',
		'PMPValue' => 'Value',
		'EnhancedValueOfWarehouses' => 'Varastot arvo',
		'UserWarehouseAutoCreate' => 'Luo varastossa automaattisesti luoda käyttäjä',
		'QtyDispatched' => 'Määrä lähetysolosuhteita',
		'OrderDispatch' => 'Tilaa lähetyskeskukset',
		'RuleForStockManagementDecrease' => 'Sääntö varaston hallintaan lasku',
		'RuleForStockManagementIncrease' => 'Sääntö varaston hallintaan lisätä',
		'DeStockOnBill' => 'Decrease todellinen varastot laskuista / hyvityslaskuja',
		'DeStockOnValidateOrder' => 'Decrease todellinen varastot tilaukset toteaa',
		'ReStockOnBill' => 'Lisäys todellinen varastot laskuista / hyvityslaskuja',
		'ReStockOnValidateOrder' => 'Lisäys todellinen varastot tilaukset toteaa',
		'StockLimitShort' => 'Limit',
		'StockLimit' => 'Kanta raja hälytykset',
		'PhysicalStock' => 'Varasto',
		'RealStock' => 'Real Stock',
		'TheoreticalStock' => 'Therocial varastossa',
		'VirtualStock' => 'Virtual varastossa',
		'MininumStock' => 'Vähimmäisvarasto',
		'StockUp' => 'Kanta ylös',
		'MininumStockShort' => 'Kanta min',
		'StockUpShort' => 'Kanta ylös',
		'IdWarehouse' => 'Id-varasto',
		'DescWareHouse' => 'Kuvaus varasto',
		'LieuWareHouse' => 'Lokalisointi varasto',
		'WarehousesAndProducts' => 'Varastot ja tuotteet',
		'PMPValueShort' => 'WAP',
		'AverageUnitPricePMPShort' => 'Keskimääräiset tulohintajärjestelmää',
		'AverageUnitPricePMP' => 'Keskimääräiset tulohintajärjestelmää',
		'EstimatedStockValueShort' => 'Arvioitu arvo varastossa',
		'EstimatedStockValue' => 'Arvioitu arvo varastossa',
		'WarehouseEdit' => 'Muokkaa varasto',
		'DeStockOnShipment' => 'Otto real varastojen siirtoa validointi',
		'ReStockOnDispatchOrder' => 'Lisäys real varastot käsikirja lähettämistä osaksi varastot, kun toimittaja voidaan vastaanottaa',
		'OrderStatusNotReadyToDispatch' => 'Tilaa ei ole vielä tai enää asema, joka mahdollistaa lähettäminen varastossa olevista tuotteista varastoissa.',
		'StockDiffPhysicTeoric' => 'Syy ero kannan fyysinen ja teoreettinen',
		'NoPredefinedProductToDispatch' => 'Ei ennalta tuotteet tämän objektin. Joten ei lähettämistä varastossa on.',
		'DispatchVerb' => 'Lähettäminen',
		'DeleteAWarehouse' => 'Poista varasto',
		'ConfirmDeleteWarehouse' => 'Oletko varma että haluat poistaa varastoon <b>%s?</b>',
		'PersonalStock' => 'Henkilökohtainen varastossa %s',
		'ThisWarehouseIsPersonalStock' => 'Tämä varasto edustaa henkilökohtainen kanta %s %s',
		'SellPriceMin' => 'Myynnin Yksikköhinta',
		'EstimatedStockValueSellShort' => 'Arvo myydä',
		'EstimatedStockValueSell' => 'Arvo Myy',
		'SelectWarehouseForStockDecrease' => 'Valitse varasto käyttää varastossa laskua',
		'SelectWarehouseForStockIncrease' => 'Valitse varasto käyttää varastossa lisätä',
);
?>