<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'Käyttäjän kortti',
		'ContactCard' => 'Osoitekortin',
		'GroupCard' => 'Ryhmän kortti',
		'NoContactCard' => 'N: o kortin joukossa yhteystiedot',
		'Permission' => 'Lupa',
		'Permissions' => 'Oikeudet',
		'EditPassword' => 'Muokkaa salasanaa',
		'SendNewPassword' => 'Lähetä uusi salasana',
		'ReinitPassword' => 'Luo uusi salasana',
		'PasswordChangedTo' => 'Salasana muutettu: %s',
		'SubjectNewPassword' => 'Uusi salasana Dolibarr',
		'AvailableRights' => 'Saatavilla olevat luvat',
		'OwnedRights' => 'Omisti käyttöoikeudet',
		'GroupRights' => 'Ryhmän käyttöoikeudet',
		'UserRights' => 'Käyttöluvat',
		'UserGUISetup' => 'Käyttäjän näytön asetukset',
		'DisableUser' => 'Poistaa käytöstä',
		'DisableAUser' => 'Poista käyttäjä',
		'DeleteUser' => 'Poistaa',
		'DeleteAUser' => 'Poista käyttäjä',
		'DisableGroup' => 'Poistaa käytöstä',
		'DisableAGroup' => 'Poista ryhmä',
		'EnableAUser' => 'Ota käyttäjä',
		'EnableAGroup' => 'Ota ryhmä',
		'DeleteGroup' => 'Poistaa',
		'DeleteAGroup' => 'Poista ryhmä',
		'ConfirmDisableUser' => 'Oletko varma, että haluat poistaa <b>käyttäjän %s?</b>',
		'ConfirmDisableGroup' => 'Oletko varma, että haluat poistaa <b>ryhmän %s?</b>',
		'ConfirmDeleteUser' => 'Oletko varma, että haluat <b>poistaa %s?</b>',
		'ConfirmDeleteGroup' => 'Oletko varma, että haluat poistaa <b>ryhmän %s?</b>',
		'ConfirmEnableUser' => 'Oletko varma, että haluat antaa <b>käyttäjän %s?</b>',
		'ConfirmEnableGroup' => 'Oletko varma, että haluat antaa <b>ryhmän %s?</b>',
		'ConfirmReinitPassword' => 'Oletko varma, että haluat luoda uuden käyttäjän <b>salasana %s?</b>',
		'ConfirmSendNewPassword' => 'Oletko varma, että haluat luoda ja lähettää uuden salasanan <b>käyttäjän %s?</b>',
		'NewUser' => 'Uusi käyttäjä',
		'CreateUser' => 'Luo käyttäjä',
		'SearchAGroup' => 'Etsi ryhmää',
		'SearchAUser' => 'Etsi käyttäjä',
		'LoginNotDefined' => 'Kirjaudu ei ole määritelty.',
		'NameNotDefined' => 'Nimi ei ole määritelty.',
		'ListOfUsers' => 'Luettelo käyttäjistä',
		'Administrator' => 'Administrator',
		'SuperAdministrator' => 'Super Administrator',
		'SuperAdministratorDesc' => 'Administrator kaikki oikeudet',
		'AdministratorDesc' => 'Järjestelmänvalvojan kokonaisuus',
		'DefaultRights' => 'Oletus käyttöoikeudet',
		'DefaultRightsDesc' => 'Määritä tässä default käyttöoikeudet automaattisesti joka myönnetään uusille käyttäjille.',
		'SpeedealingUsers' => 'Speedealing users',
		'LastName' => 'Nimi',
		'FirstName' => 'Etunimi',
		'ListOfGroups' => 'Luettelo ryhmien',
		'NewGroup' => 'Uusi ryhmä',
		'CreateGroup' => 'Luo ryhmä',
		'RemoveFromGroup' => 'Poista ryhmästä',
		'PasswordChangedAndSentTo' => 'Salasana muutettu ja <b>lähetetään %s.</b>',
		'PasswordChangeRequestSent' => 'Pyynnön vaihtaa <b>salasana %s lähetetään %s.</b>',
		'MenuUsersAndGroups' => 'Käyttäjät & ryhmät',
		'LastGroupsCreated' => 'Viimeisin %s luonut ryhmiä',
		'LastUsersCreated' => 'Viimeisin %s käyttäjät luotu',
		'ShowGroup' => 'Näytä ryhmä',
		'ShowUser' => 'Näytä käyttäjän',
		'NonAffectedUsers' => 'Ei vaikuttaa käyttäjien',
		'UserModified' => 'Käyttäjä muutettu onnistuneesti',
		'GroupModified' => 'Ryhmän muunnettu onnistuneesti',
		'PhotoFile' => 'Photo tiedosto',
		'UserWithSpeedealingAccess' => 'User with Speedealing access',
		'ListOfUsersInGroup' => 'Luettelo käyttäjien tässä ryhmässä',
		'ListOfGroupsForUser' => 'Luettelo ryhmien tälle käyttäjälle',
		'UsersToAdd' => 'Käyttäjät lisätä tähän ryhmään',
		'GroupsToAdd' => 'Ryhmät, jos haluat lisätä tämän käyttäjän',
		'NoLogin' => 'Ei tunnus',
		'LinkToCompanyContact' => 'Linkki kolmannen osapuolen / contact',
		'LinkedToSpeedealingMember' => 'Link to member',
		'LinkedToSpeedealingUser' => 'Link to Speedealing user',
		'LinkedToSpeedealingThirdParty' => 'Link to Speedealing third party',
		'CreateSpeedealingLogin' => 'Create a user',
		'CreateSpeedealingThirdParty' => 'Create a third party',
		'LoginAccountDisable' => 'Tili poistettu, aseta uusi kirjautumistunnuksesi sen käyttöön.',
		'LoginAccountDisableInSpeedealing' => 'Account disabled in Speedealing.',
		'LoginAccountDisableInLdap' => 'Tili poistettu alalla.',
		'UsePersonalValue' => 'Käytä henkilökohtaista arvo',
		'GuiLanguage' => 'Kieli -',
		'InternalUser' => 'Sisäinen käyttäjä',
		'MyInformations' => 'Omat tiedot',
		'ExportDataset_user_1' => 'Dolibarr käyttäjille ja ominaisuudet',
		'DomainUser' => 'Domain käyttäjän %s',
		'Reactivate' => 'Uudelleenaktivoi',
		'CreateInternalUserDesc' => 'Tämän lomakkeen avulla voit luotu käyttäjän sisäinen yrityksenne / perusta. Voit luotu ulkopuolinen käyttäjä (asiakas, toimittaja, ...), käytä painiketta Luo Dolibarr käyttäjä "kolmannen osapuolen yhteystiedot kortin.',
		'InternalExternalDesc' => '<b>Sisäinen</b> käyttäjä on käyttäjä, joka on osa yrityksen / perusta. <br> <b>Ulkoinen</b> käyttäjä on asiakas, toimittaja tai muu. <br><br> Molemmissa tapauksissa, oikeudet määritellään oikeuksia Dolibarr myös ulkoinen käyttäjä voi olla eri valikosta johtaja kuin sisäinen käyttäjä (Katso etusivu - Asetukset - Display)',
		'PermissionInheritedFromAGroup' => 'Lupa myönnettiin, koska periytyy yhden käyttäjän ryhmä.',
		'Inherited' => 'Peritty',
		'UserWillBeInternalUser' => 'Luotu käyttäjä on sisäinen käyttäjä (koska ei liity erityistä kolmannelle osapuolelle)',
		'UserWillBeExternalUser' => 'Luotu käyttäjä tulee ulkopuolinen käyttäjä (koska liittyy erityistä kolmannelle osapuolelle)',
		'IdPhoneCaller' => 'Id puhelimeen soittajan',
		'UserLogged' => 'Käyttäjän %s kytketty',
		'UserLogoff' => 'Käyttäjä %s logout',
		'NewUserCreated' => 'Käyttäjä %s on luotu',
		'NewUserPassword' => 'Salasana muutos %s',
		'EventUserModified' => 'Käyttäjän %s muuntamattomat',
		'UserDisabled' => 'Käyttäjän %s pois päältä',
		'UserEnabled' => 'Käyttäjän %s aktivoitu',
		'UserDeleted' => 'Käyttäjän %s poistettu',
		'NewGroupCreated' => 'Ryhmän %s on luotu',
		'GroupModified' => 'Ryhmän muunnettu onnistuneesti',
		'GroupDeleted' => 'Ryhmän %s poistettu',
		'ConfirmCreateContact' => 'Oletko varma yu haluamme luoda Dolibarr huomioon tässä yhteydessä?',
		'ConfirmCreateLogin' => 'Oletko varma, että haluat luoda Dolibarr huomioon tämän jäsen?',
		'ConfirmCreateThirdParty' => 'Oletko varma, että haluat luoda kolmannelle osapuolelle tämä jäsen?',
		'LoginToCreate' => 'Kirjaudu luoda',
		'NameToCreate' => 'Nimi kolmannen osapuolen luoda',
		'YourRole' => 'Omat roolit',
		'YourQuotaOfUsersIsReached' => 'Tilakiintiösi aktiivisia käyttäjiä on saavutettu!',
		'NbOfUsers' => 'Nb käyttäjien',
		'DontDowngradeSuperAdmin' => 'Vain superadmin voi downgrade superadmin',
		'NewDatabase' => 'Nouvelle base de données',
		'CreateDatabase' => 'Créer la base de données',
		'ListOfDatabases' => 'Liste des bases de données',
		'ListOfUsersInDatabase' => 'Liste des utilisateurs liés à la base de données',
		'ListOfRolesInDatabase' => 'Liste des groupes liés à la base de données',
		'DeleteADatabase' => 'Suppression d\'une database',
		'ConfirmDatabase' => 'Êtes-vous sûr de vouloir supprimer la base de données <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Groupes non affectés à la base de données',
		'NonAffectedUsersDatabase' => 'Utilisateurs non affectés à la base de données',
		'Collaborators' => 'Collaborateurs',
		'Profiles' => 'Profils collaborateurs'
);
?>