<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$withdrawals = array(
		'CHARSET' => 'UTF-8',
		'StandingOrdersArea' => 'Pysyvän tilaukset alueella',
		'CustomersStandingOrdersArea' => 'Asiakkaat pysyvän tilaukset alueella',
		'StandingOrders' => 'Pysyvän tilaukset',
		'StandingOrder' => 'Pysyvän tilaukset',
		'NewStandingOrder' => 'Uusi kestotilaus',
		'Withdrawals' => 'Nostot',
		'Withdrawal' => 'Peruuttaminen',
		'WithdrawalsReceipts' => 'Nostot kuitit',
		'WithdrawalReceipt' => 'Peruuttaminen vastaanottamisesta',
		'WithdrawalReceiptShort' => 'Kuitti',
		'LastWithdrawalReceipts' => 'Viimeisin %s vetäytymis kuitit',
		'WithdrawedBills' => 'Withdrawed laskut',
		'WithdrawalsLines' => 'Nostot linjat',
		'RequestStandingOrderToTreat' => 'Pyyntö seisoville tilausten hoitoon',
		'RequestStandingOrderTreated' => 'Pyyntö seisoville tilaukset käsitellään',
		'CustomersStandingOrders' => 'Asiakas pysyvän tilaukset',
		'CustomerStandingOrder' => 'Asiakas kestotilaus',
		'NbOfInvoiceToWithdraw' => 'Nb laskun kanssa peruuttaa pyynnön',
		'InvoiceWaitingWithdraw' => 'Laskun odottaa peruuttaa',
		'AmountToWithdraw' => 'Määrä peruuttaa',
		'WithdrawsRefused' => 'Peruuttaa evätty',
		'NoInvoiceToWithdraw' => 'Ei asiakasta laskun maksu mode "vetää" odottaa. Mene "Peruuta" välilehdessä laskun kortin pyytää.',
		'ResponsibleUser' => 'Vastaava käyttäjä',
		'WithdrawalsSetup' => 'Peruuttaminen setup',
		'WithdrawStatistics' => 'Peruuttaa tilastot',
		'WithdrawRejectStatistics' => 'Peruuta hylkää tilastot',
		'LastWithdrawalReceipt' => 'Viimeisin %s poistamista kuitit',
		'MakeWithdrawRequest' => 'Tee peruuttaa pyynnön',
		'ThirdPartyBankCode' => 'Kolmannen osapuolen pankin koodi',
		'ThirdPartyDeskCode' => 'Kolmannen osapuolen desk-koodi',
		'NoInvoiceCouldBeWithdrawed' => 'N: o laskun withdrawed menestyksekkäästi. Tarkista, että laskussa yrityksiin, joilla on voimassa oleva kielto.',
		'ClassCredited' => 'Luokittele hyvitetään',
		'ClassCreditedConfirm' => 'Oletko varma, että haluat luokitella tämän vetäytymisen vastaanottamisesta kuin hyvitetty pankkitilisi?',
		'StandingOrderToProcess' => 'Jotta prosessi',
		'StandingOrderProcessed' => 'Jalostettu',
		'TransData' => 'Päivämäärä Lähetetty',
		'TransMetod' => 'Menetelmä Lähetetty',
		'Send' => 'Lähettää',
		'Lines' => 'Linjat',
		'StandingOrderReject' => 'Issue hylätä',
		'WithdrawalRefused' => 'Nostot Refuseds',
		'WithdrawalRefusedConfirm' => 'Oletko varma että haluat kirjoittaa peruuttamisesta hylkäämisen yhteiskunnan',
		'RefusedData' => 'Päivä hylkäämisestä',
		'RefusedReason' => 'Hylkäämisen syy',
		'RefusedInvoicing' => 'Laskutus hylkääminen',
		'NoInvoiceRefused' => 'Älä lataa hylkäämisestä',
		'InvoiceRefused' => 'Lataa hylkäämisen asiakkaan',
		'Status' => 'Tila',
		'StatusUnknown' => 'Tuntematon',
		'StatusWaiting' => 'Odotus',
		'StatusCredited' => 'Hyvitetään',
		'StatusRefused' => 'Refused',
		'StatusMotif0' => 'Määrittelemätön',
		'StatusMotif1' => 'Säännös insuffisante',
		'StatusMotif2' => 'Tirage conteste',
		'StatusMotif3' => 'Ei vetäytyminen järjestys',
		'StatusMotif4' => 'Asiakkaan tilauksen',
		'StatusMotif5' => 'RIB inexploitable',
		'StatusMotif6' => 'Huomioon ilman tasapaino',
		'StatusMotif7' => 'Ratkaisusta',
		'StatusMotif8' => 'Muu syy',
		'CreateAll' => 'Nosta kaikki',
		'CreateGuichet' => 'Vain toimisto',
		'CreateBanque' => 'Vain pankki',
		'OrderWaiting' => 'Odottelen hoito',
		'NotifyTransmision' => 'Irtisanominen Lähetetty',
		'NotifyEmision' => 'Irtisanominen päästöjen',
		'NotifyCredit' => 'Irtisanominen Credit',
		'NumeroNationalEmetter' => 'Kansallinen lähetin määrä',
		'NbOfInvoiceToWithdrawWithInfo' => 'Nb laskun kanssa peruuttaa pyynnön asiakkaille, joilla määritellään tilitietoja',
		'StatusTrans' => 'Toimitettu',
		'PleaseSelectCustomerBankBANToWithdraw' => 'Valitse tiedot asiakkaan pankkitilille peruuttaa',
		'WithBankUsingRIB' => 'Jos pankkitilit käyttäen RIB',
		'WithBankUsingBANBIC' => 'Jos pankkitilit käyttäen IBAN / BIC / SWIFT',
		'BankToReceiveWithdraw' => 'Pankkitili saada vetäytyy',
		'CreditDate' => 'Luottoa',
		'WithdrawalFileNotCapable' => 'Ei voitu luoda peruuttamiseen kuitti tiedosto maasi',
		'ShowWithdraw' => 'Näytä Nosta',
		'IfInvoiceNeedOnWithdrawPaymentWontBeClosed' => 'Kuitenkin, jos lasku on ainakin yksi poistamista määrä ei kuitenkaan ole vielä käsitelty, sitä ei voida määrittää koska maksoivat sallimaan hallita poistettaviksi.',
		'DoStandingOrdersBeforePayments' => 'Tällä välilehtien avulla voit pyytää ja kestotilauksena. Kun se on valmis, voit kirjoittaa maksun sulkea laskun.',
		'InfoCreditSubject' => 'Maksaminen kestotilaus %s pankin',
		'InfoCreditMessage' => 'Kestotilaus %s on maksanut pankille <br> Tiedot maksu: %s',
		'InfoTransSubject' => 'Toimittaminen kestotilaus %s pankkiin',
		'InfoTransMessage' => 'Kestotilaus %s on transmited sen pankkiin %s %s. <br><br>',
		'InfoTransData' => 'Määrä: %s <br> Metode: %s <br> Date: %s',
		'InfoFoot' => 'Tämä on automaattinen viesti lähetetään Dolibarr',
		'InfoRejectSubject' => 'Pysyvä järjestyksessä kieltäytyi',
		'InfoRejectMessage' => 'Hei, <br><br> standig järjestys laskun %s liittyviä yrityksen %s, joiden määrä %s on evätty pankin. <br><br> - <br> % $',
		'ModeWarning' => 'Vaihtoehto todellista tilaa ei ole asetettu, pysähdymme jälkeen simulointi',
);
?>