<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$install = array(
		'CHARSET' => 'UTF-8',
		'InstallEasy' => '只需按照分步说明。',
		'MiscellanousChecks' => '先决条件检查',
		'SpeedealingWelcome' => 'Welcome to Speedealing',
		'ConfFileExists' => '配置文件<b>％s</b>存在。',
		'ConfFileDoesNotExists' => '配置文件<b>％s</b>不存在！',
		'ConfFileDoesNotExistsAndCouldNotBeCreated' => '配置文件<b>％s</b>不存在，无法创建！',
		'ConfFileCouldBeCreated' => '<b>％s的</b>配置文件可以被创建。',
		'ConfFileIsNotWritable' => '配置文件<b>％s</b>不是写。检查权限。对于第一次安装，您的Web服务器必须被授予能够进入这个文件写在配置过程中（“文件模式，例如666”在一个像Unix的操作系统）。',
		'ConfFileIsWritable' => '配置文件<b>％s</b>是可写的。',
		'ConfFileReload' => '重新载入配置文件的所有信息。',
		'PHPSupportSessions' => '这个PHP支持会议。',
		'PHPSupportPOSTGETOk' => '这个PHP支持的变量的POST和GET。',
		'PHPSupportPOSTGETKo' => '有可能你的PHP安装程序不支持变量POST和/或GET。检查你的php.ini中参数<b>的变数</b> 。',
		'PHPSupportGD' => '这个PHP支持广东的图形功能。',
		'PHPSupportUTF8' => '这个PHP支持UTF8的功能。',
		'PHPMemoryOK' => '您的PHP最大会话内存设置为<b>％s。</b>这应该是足够的。',
		'PHPMemoryTooLow' => '您的PHP最大会话内存设置为<b>％s</b>字节。这应该是太低了。改变你的<b>php.ini中</b>设置<b>memory_limit的</b>参数至少<b>％s</b>字节。',
		'Recheck' => '点击这里，更多的有意义的测试',
		'ErrorPHPDoesNotSupportSessions' => '您的PHP安装不支持会话。此功能必须作出Speedealing工作。检查你的PHP安装程序。',
		'ErrorPHPDoesNotSupportGD' => '您的PHP安装不支持图形功能的广东。不图将可用。',
		'ErrorPHPDoesNotSupportUTF8' => '您的PHP安装不支持UTF8的功能。 Speedealing不能正常工作。解决这个安装之前Speedealing。',
		'ErrorDirDoesNotExists' => '目录％s不存在。',
		'ErrorGoBackAndCorrectParameters' => '后退和纠正错误的参数。',
		'ErrorWrongValueForParameter' => '您可能输入一个参数的错误值％s\'的。',
		'ErrorFailedToCreateDatabase' => '无法创建数据库\'％s\'的。',
		'ErrorFailedToConnectToDatabase' => '无法连接到数据库\'％s\'的。',
		'ErrorDatabaseVersionTooLow' => 'Database version (%s) too old. Version %s or higher is required.',
		'ErrorPHPVersionTooLow' => 'PHP的版本太旧。版本％s是必需的。',
		'WarningPHPVersionTooLow' => 'PHP版本太旧。预计或以上版本%s。这个版本应该允许安装，但不支持。',
		'ErrorConnectedButDatabaseNotFound' => '连接到数据库服务器的成功，但\'％s\'不存在。',
		'ErrorDatabaseAlreadyExists' => '数据库\'％s\'已经存在。',
		'IfDatabaseNotExistsGoBackAndUncheckCreate' => '如果数据库不存在，请返回并检查选择“创建数据库”。',
		'IfDatabaseExistsGoBackAndCheckCreate' => '如果数据库已经存在，请返回并取消选中“创建数据库”选项。',
		'WarningBrowserTooOld' => 'Too old version of browser. Upgrading your browser to a recent version of Firefox, Chrome or Opera is highly recommanded.',
		'PHPVersion' => 'PHP版本',
		'YouCanContinue' => '您可以继续...',
		'PleaseBePatient' => '请耐心等待...',
		'License' => '使用许可',
		'ConfigurationFile' => '配置文件',
		'WebPagesDirectory' => '目录下的网页存储',
		'DocumentsDirectory' => '目录来存储和生成的文件上传',
		'URLRoot' => '网址根',
		'ForceHttps' => '部队的安全连接（HTTPS）的',
		'CheckToForceHttps' => '选中此选项，迫使安全连接（HTTPS）的。 <br>这就要求网络服务器是一个SSL证书配置。',
		'SpeedealingDatabase' => 'Speedealing Database',
		'DatabaseChoice' => '数据库的选择',
		'DatabaseType' => '数据库类型',
		'DriverType' => '驱动类型',
		'Server' => '服务器',
		'ServerAddressDescription' => '名称或IP数据库服务器，通常填入\'localhost\'当数据库服务器的地址存放在Web服务器相同的服务器比',
		'ServerPortDescription' => '数据库服务器端口。保持空如果不明。',
		'DatabaseServer' => '数据库服务器',
		'DatabaseName' => '数据库名称',
		'DatabasePrefix' => '数据库前缀表',
		'Login' => '注册',
		'AdminLogin' => '登录为Speedealing数据库所有者。',
		'Password' => '密码',
		'PasswordAgain' => '第二次再次输入密码',
		'AdminPassword' => '密码Speedealing数据库所有者。',
		'CreateDatabase' => '创建数据库',
		'CreateUser' => '创建所有者',
		'DatabaseSuperUserAccess' => '数据库服务器 - 超级用户',
		'CheckToCreateDatabase' => '检查中，如果数据库不存在，必须创建。 <br>在这种情况下，必须填写登录/密码为超级用户帐户在本页面底部。',
		'CheckToCreateUser' => '如果数据库所有者复选框不存在，必须创建。 <br>在这种情况下，必须选择自己的登录名和密码，并填写在本页面底部的登录/为超级用户帐户的密码。如果此框未被选中，业主数据库及其密码必须存在。',
		'Experimental' => '（实验）',
		'DatabaseRootLoginDescription' => '允许创建新的数据库或新用户，无用的，如果你的数据库和数据库登录已经存在就像当你在一个网站举办的托管服务提供商是（用户登录）。',
		'KeepEmptyIfNoPassword' => '给空如果用户没有密码（避免这种情况）',
		'SaveConfigurationFile' => '保存价值',
		'ConfigurationSaving' => '储蓄配置文件',
		'ServerConnection' => '服务器连接',
		'DatabaseConnection' => '数据库连接',
		'DatabaseCreation' => '数据库的创建',
		'UserCreation' => '用户创建',
		'CreateDatabaseObjects' => '数据库对象的创建',
		'ReferenceDataLoading' => '数据加载参考',
		'TablesAndPrimaryKeysCreation' => '创建表和主键',
		'CreateTableAndPrimaryKey' => '创建表％s的',
		'CreateOtherKeysForTable' => '创建外键和索引的表％s',
		'OtherKeysCreation' => '外键和索引创建',
		'FunctionsCreation' => '创造功能',
		'AdminAccountCreation' => '管理员登录创作',
		'PleaseTypePassword' => '请键入一个密码，空密码不得！',
		'PleaseTypeALogin' => '请输入登录！',
		'PasswordsMismatch' => '密码不同，请再试一次！',
		'SetupEnd' => '安装完',
		'SystemIsInstalled' => '此安装已完成。',
		'SystemIsUpgraded' => 'Speedealing已经升级成功。',
		'YouNeedToPersonalizeSetup' => '您需要配置Speedealing以满足您的需求（外观，功能，...).要做到这一点，请按照以下链接：',
		'AdminLoginCreatedSuccessfuly' => 'Speedealing管理员登录<b>\'％s\'</b>的创建successfuly。',
		'GoToSpeedealing' => 'Go to Speedealing',
		'GoToSetupArea' => '前往Speedealing（安装面积）',
		'MigrationNotFinished' => '您的数据库的版本是不完全最新的，所以你必须再次运行升级过程。',
		'GoToUpgradePage' => '转到页再次升级',
		'Examples' => '范例',
		'WithNoSlashAtTheEnd' => '没有斜杠“/”在年底',
		'DirectoryRecommendation' => '这是推荐使用的目录以外的你对你的网页目录。',
		'LoginAlreadyExists' => '已存在',
		'SpeedealingAdminLogin' => 'Speedealing admin login',
		'AdminLoginAlreadyExists' => 'Speedealing管理员帐户<b>\'％s\'</b>已经存在。',
		'WarningRemoveInstallDir' => '警告，出于安全原因，一旦安装或升级完成后，你应该删除<b>安装目录或重命名为install.lock，以避免其恶意使用。</b>',
		'ThisPHPDoesNotSupportTypeBase' => '这个PHP系统不支持任何接口来访问数据库类型％s',
		'FunctionNotAvailableInThisPHP' => '不是可以用这个PHP',
		'MigrateScript' => '迁移脚本',
		'ChoosedMigrateScript' => '选择迁移脚本',
		'DataMigration' => '数据迁移',
		'DatabaseMigration' => '结构数据库迁移',
		'ProcessMigrateScript' => '脚本处理',
		'ChooseYourSetupMode' => '选择你的安装模式，然后点击“开始”...',
		'FreshInstall' => '全新安装',
		'FreshInstallDesc' => '使用此模式，如果这是你第一次安装。如果没有，这个模式可以不完全修复前安装，但是如果你想升级你的版本，选择“升级”模式。',
		'Upgrade' => '升级',
		'UpgradeDesc' => '如果你使用这种模式已经取代了从一个较新版本的文件旧Speedealing文件。这将提升您的数据库和数据。',
		'Start' => '开始',
		'InstallNotAllowed' => '安装程序不容许<b>conf.php</b>权限',
		'NotAvailable' => '不适用',
		'YouMustCreateWithPermission' => '您必须创建文件％s，并为网络服务器在安装过程中写上它的权限。',
		'CorrectProblemAndReloadPage' => '请修正这个问题，请按F5重新载入页面。',
		'AlreadyDone' => '已迁移',
		'DatabaseVersion' => '数据库版本',
		'ServerVersion' => '数据库服务器版本',
		'YouMustCreateItAndAllowServerToWrite' => '您必须创建此目录和Web服务器允许写进去。',
		'CharsetChoice' => '字符集的选择',
		'CharacterSetClient' => '字符集生成的HTML网页使用',
		'CharacterSetClientComment' => '选择字符集的网页显示。 <br/>默认建议的字符集是您的数据库之一。',
		'CollationConnection' => '字符排序',
		'CollationConnectionComment' => '选择页面的代码定义字符的排序顺序由数据库使用。此参数也被称为\'整理一些数据库的。 <br/>此参数不能被定义，如果数据库已经存在。',
		'CharacterSetDatabase' => '数据库字符集',
		'CharacterSetDatabaseComment' => '选择想要的字符集的数据库创建。 <br/>此参数不能被定义，如果数据库已经存在。',
		'YouAskDatabaseCreationSoSpeedealingNeedToConnect' => 'You ask to create database <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'YouAskLoginCreationSoSpeedealingNeedToConnect' => 'You ask to create database login <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'BecauseConnectionFailedParametersMayBeWrong' => '作为连接失败，主机或超级用户参数一定是错误的。',
		'OrphelinsPaymentsDetectedByMethod' => '孤儿付款检测方法％s',
		'RemoveItManuallyAndPressF5ToContinue' => '手动删除它，然后按F5键继续。',
		'KeepDefaultValuesWamp' => '您使用从DoliWamp Speedealing安装向导，所以这里建议值已经进行了优化。他们唯一的变化，如果你知道你做什么。',
		'KeepDefaultValuesDeb' => '您使用从Ubuntu或者Debian软件包的Speedealing安装向导，所以这里建议值已经进行了优化。只有数据库的所有者创建的密码必须完成。其他参数的变化，如果你只知道你做什么。',
		'KeepDefaultValuesMamp' => '您使用从DoliMamp Speedealing安装向导，所以这里建议值已经进行了优化。他们唯一的变化，如果你知道你做什么。',
		'KeepDefaultValuesProxmox' => '您使用Proxmox的虚拟设备的Speedealing安装向导，因此，这里提出的价值已经优化。改变他们，只有当你知道你做什么。',
		'FieldRenamed' => '场更名',
		'IfLoginDoesNotExistsCheckCreateUser' => '如果登录不存在，但你必须检查选项“创建用户”',
		'ErrorConnection' => '服务器<b>“％s”，</b>数据库名称<b>“％s”，</b>并登录<b>“％的</b> ”，或数据库密码可能是错误或PHP的客户端版本可能太旧版本相比，数据库。',
		'InstallChoiceRecommanded' => '推荐选择<b>你</b>的安装版本<b>％％s</b>从当前版本',
		'InstallChoiceSuggested' => '<b>选择安装所建议的安装程序</b> 。',
		'MigrateIsDoneStepByStep' => '目标版本（%s）有好几个版本的差距，因此，安装向导会回来一次将完成这一个建议未来的迁移。',
		'CheckThatDatabasenameIsCorrect' => '检查数据库名称<b>“％s”</b>是正确的。',
		'IfAlreadyExistsCheckOption' => '如果此名称是正确的，该数据库尚不存在，你必须检查选项“创建数据库”。',
		'OpenBaseDir' => 'PHP的openbasedir参数',
		'YouAskToCreateDatabaseSoRootRequired' => '你选中的方块“创建数据库”。为此，您需要提供登录/密码的超级用户（形式的底部）。',
		'YouAskToCreateDatabaseUserSoRootRequired' => '你选中的方块“创建数据库所有者”。为此，您需要提供登录/密码的超级用户（形式的底部）。',
		'NextStepMightLastALongTime' => '当前步骤可能会持续几分钟。请等待下一个屏幕显示完全，然后再继续。',
		'LastStepDesc' => '<strong>最后一步</strong> ：此处定义的登录名和密码，您打算使用连接到软件。不松，因为它是帐户管理所有其他。',
		'ActivateModule' => '激活模块%s',
		'ShowEditTechnicalParameters' => 'Click here to show/edit advanced parameters (expert mode)',
		'ServerPortCouchdbDescription' => 'Port du serveur. Défaut 5984.',
		'ServerAddressCouchdbDescription' => 'Nom FQDN du serveur de base de données, \'localhost.localdomain\' quand le serveur est installé sur la même machine que le serveur web',
		'DatabaseCouchdbUserDescription' => 'Login du super administrateur ayant tous les droits sur le serveur CouchDB ou l\'administrateur propriétaire de la base si la base et son compte d\'accès existent déjà (comme lorsque vous êtes chez un hébergeur).<br><br><div class="alert-box info">Cet utilisateur/mot de passe sera l\'administrateur pour se connecter à Speedealing.</div>',
		'CheckToCreateCouchdbDatabase' => 'Cochez cette option si la base de données n\'existe pas et doit être créée.',
		'CreateAdminUser' => 'Créer le super administrateur (Première installation de couchDB)',
		'MemcachedDescription' => 'Activer Memcached necessite l\'installation d\'un serveur Memcached et des lib php-memcached ou php-memcache. Il peut être activer après l\'installation.',
		'ServerAddressMemcachedDesc' => 'Nom ou adresse ip du serveur memcached, généralement \'localhost\' quand le serveur est installé sur la même machine que le serveur web',
		'ServerPortMemcachedDesc' => 'Port du serveur memcached. Défaut : 11211',
		'EnabledMemcached' => 'Activer Memcached',
		'DatabaseNoSQL' => 'Base de données CouchDB',
		'FailedToCreateAdminLogin' => 'Echec de la création du compte administrateur Speedealing.',
		'LinkedElementsInvalidDeleted' => '<b>%s</b> liaisons invalides ont été supprimées',
		'NothingToDelete' => 'Aucune liaison invalide trouvée',
		'SourceType' => 'Source',
		'TargetType' => 'Cible',
                // Upgrade
                'UpgradeOk' => 'Upgrade is ok !',
                'NewInstalledVersion' => 'Your new version is %s',
                'NeedUpgrade' => 'New Speedealing version !',
                'WarningUpgrade' => 'Installed version is %s, you must upgrade to %s. <br>Please contact your administrator.'
);
?>