<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Categoria',
		'Categories' => 'Categorias',
		'Rubrique' => 'Rubrica',
		'Rubriques' => 'Rubricas',
		'categories' => 'Categorias',
		'TheCategorie' => 'A Categoria',
		'NoCategoryYet' => 'Nenhuma Categoria Deste Tipo Criada',
		'In' => 'Em',
		'AddIn' => 'Adicionar em',
		'modify' => 'Modificar',
		'Classify' => 'Classificar',
		'CategoriesArea' => 'Área Categorias',
		'ProductsCategoriesArea' => 'Área Categorias de Produtos e Serviços',
		'SuppliersCategoriesArea' => 'Área Categorias Fornecedores',
		'CustomersCategoriesArea' => 'Área Categorias Clientes',
		'ThirdPartyCategoriesArea' => 'Área Categorias de Fornecedores',
		'MembersCategoriesArea' => 'Members categories area',
		'MainCats' => 'Categorias Principais',
		'SubCats' => 'Sub-Categorias',
		'CatStatistics' => 'Estatísticas',
		'CatList' => 'Lista de Categorias',
		'AllCats' => 'Todas as Categorias',
		'ViewCat' => 'Ver Categoria',
		'NewCat' => 'Nova Categoria',
		'NewCategory' => 'Nova Categoria',
		'ModifCat' => 'Modificar uma Categoria',
		'CatCreated' => 'Categoria Criada',
		'CreateCat' => 'Adicionar uma Categoria',
		'CreateThisCat' => 'Adicionar esta Categoria',
		'ValidateFields' => 'Confirmar os campos',
		'NoSubCat' => 'Esta categoria não contém Nenhuma subcategoria.',
		'SubCatOf' => 'Subcategoria',
		'FoundCats' => 'Categorias Encontradas',
		'FoundCatsForName' => 'Categorias Encontradas com o Nome:',
		'FoundSubCatsIn' => 'Subcategorias Encontradas na Categoria',
		'ErrSameCatSelected' => 'Selecionou a mesma categoria varias vezes',
		'ErrForgotCat' => 'Esqueceu de escolher a categoria',
		'ErrForgotField' => 'Esqueceu de atribuir um campo',
		'ErrCatAlreadyExists' => 'Este nome esta sendo utilizado',
		'AddProductToCat' => 'Adicionar este produto a uma categoria?',
		'ImpossibleAddCat' => 'Impossível Adicionar a categoria',
		'ImpossibleAssociateCategory' => 'Impossível associar a categoria',
		'WasAddedSuccessfully' => 'Foi adicionado com êxito.',
		'ObjectAlreadyLinkedToCategory' => 'O elemento já está associado a esta categoria',
		'CategorySuccessfullyCreated' => 'A Categoria %s foi inserida com sucesso',
		'ProductIsInCategories' => 'Este produto/serviço encontra-se nas seguintes categorias',
		'SupplierIsInCategories' => 'Este fornecedor encontra-se nas seguintes categorias',
		'CompanyIsInCustomersCategories' => 'Esta empresa encontra-se nas seguintes categorias',
		'CompanyIsInSuppliersCategories' => 'Esta empresa encontra-se nas seguintes categorias de Fornecedores',
		'MemberIsInCategories' => 'This member owns to following members categories',
		'ProductHasNoCategory' => 'Este produto/serviço não se encontra em nenhuma categoria em particular',
		'SupplierHasNoCategory' => 'Este fornecedor não se encontra em Nenhuma categoria em particular',
		'CompanyHasNoCategory' => 'Esta empresa não se encontra em Nenhuma categoria em particular',
		'MemberHasNoCategory' => 'This member is not in any categories',
		'ClassifyInCategory' => 'Esta categoria não contém clientes',
		'NoneCategory' => 'Nenhuma',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Esta categoria já existe na mesma localização',
		'ReturnInProduct' => 'Voltar à ficha produto/serviço',
		'ReturnInSupplier' => 'Voltar à ficha fornecedor',
		'ReturnInCompany' => 'Voltar à ficha cliente/cliente potencial',
		'ContentsVisibleByAll' => 'O Conteúdo Será Visivel por Todos?',
		'ContentsVisibleByAllShort' => 'Conteúdo visivel por todos',
		'ContentsNotVisibleByAllShort' => 'Conteúdo não visivel por todos',
		'CategoriesTree' => 'Árvore de Categorias',
		'DeleteCategory' => 'Eliminar Categoria',
		'ConfirmDeleteCategory' => 'Tem certeza que quer eliminar esta categoria?',
		'RemoveFromCategory' => 'Eliminar link com categoria',
		'RemoveFromCategoryConfirm' => 'Tem certeza que quer eliminar o link entre a transação e a categoria?',
		'NoCategoriesDefined' => 'Nenhuma Categoria Definida',
		'SuppliersCategoryShort' => 'Categoria Fornecedores',
		'CustomersCategoryShort' => 'Categoria Clientes',
		'ProductsCategoryShort' => 'Categoria Produtos',
		'MembersCategoryShort' => 'Members category',
		'SuppliersCategoriesShort' => 'Categorias Fornecedores',
		'CustomersCategoriesShort' => 'Categorias Clientes',
		'CustomersProspectsCategoriesShort' => 'Cat. Clientes/Potenciais',
		'ProductsCategoriesShort' => 'Categorias Produtos',
		'MembersCategoriesShort' => 'Members categories',
		'ThisCategoryHasNoProduct' => 'Esta categoria não contém nenhum produto.',
		'ThisCategoryHasNoSupplier' => 'Esta categoria não contém a nenhum fornecedor.',
		'ThisCategoryHasNoCustomer' => 'Esta categoria não contém a nenhum cliente.',
		'ThisCategoryHasNoMember' => 'This category does not contain any member.',
		'AssignedToCustomer' => 'Atribuir a um cliente',
		'AssignedToTheCustomer' => 'Atribuido a um cliente',
		'InternalCategory' => 'Categoria Interna',
		'CategoryContents' => 'Conteúdo da Categoria',
		'CategId' => 'Id Categoria',
		'CatSupList' => 'Lista de categorias de fornecedores',
		'CatCusList' => 'Lista de Categorias de Clientes/Perspectivas',
		'CatProdList' => 'Lista de Categorias de Produtos',
		'CatMemberList' => 'List of members categories',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>