<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Comercial',
		'CommercialArea' => 'Área Comercial',
		'CommercialCard' => 'Ficha Comercial',
		'CustomerArea' => 'Área de Clientes',
		'Customer' => 'Cliente',
		'Customers' => 'Clientes',
		'Prospect' => 'Cliente Potencial',
		'Prospects' => 'Clientes Potenciais',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Eliminar uma Ação',
		'NewAction' => 'Nova Ação',
		'AddAction' => 'Criar Ação',
		'AddAnAction' => 'Criar uma Ação',
		'AddActionRendezVous' => 'Criar uma Reunião',
		'Rendez-Vous' => 'Reunião',
		'ConfirmDeleteAction' => 'Tem certeza que quer eliminar esta ação?',
		'CardAction' => 'Ficha da Ação',
		'PercentDone' => 'Percentagem Realizada',
		'ActionOnCompany' => 'Ação Relativa à Empresa',
		'ActionOnContact' => 'Ação Relativa ao Contato',
		'TaskRDV' => 'Reunião',
		'TaskRDVWith' => 'Reunião com %s',
		'ShowTask' => 'Ver Tarefa',
		'ShowAction' => 'Ver Ação',
		'ActionsReport' => 'Relatório de Ações',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Commercial',
		'SalesRepresentatives' => 'Comerciais',
		'SalesRepresentativeFollowUp' => 'Comercial (Seguimento)',
		'SalesRepresentativeSignature' => 'Comercial (Assinatura)',
		'CommercialInterlocutor' => 'Interlocutor Comercial',
		'ErrorWrongCode' => 'Código Incorreto',
		'NoSalesRepresentativeAffected' => 'Nenhum Comercial Afetado',
		'ShowCustomer' => 'Ver Cliente',
		'ShowProspect' => 'Ver Clientes Potenciais',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Lista de Clientes Potenciais',
		'ListOfCustomers' => 'Lista de Clientes',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'As %s últimas Ações Efetuadas',
		'LastRecordedTasks' => 'últimas Ações Registradas',
		'LastActionsToDo' => 'As %s últimas Ações não Completadas',
		'DoneAndToDoActionsFor' => 'Lista de ações realizadas ou a realizar por %s',
		'DoneAndToDoActions' => 'Lista de ações realizadas ou a realizar',
		'DoneActions' => 'Lista de Ações Realizadas',
		'DoneActionsFor' => 'Lista de Ações Realizadas por %s',
		'ToDoActions' => 'Lista de Ações Incompletas',
		'ToDoActionsFor' => 'Lista de Ações Incompletas de %s',
		'SendPropalRef' => 'Enviar Orçamento %s',
		'SendOrderRef' => 'Enviar Pedido %s',
		'StatusNotApplicable' => 'Not applicable',
		'StatusActionToDo' => 'A Realizar',
		'StatusActionDone' => 'Realizado',
		'StatusActionInProcess' => 'Em Curso',
		'MyActionsAsked' => 'Ações que Registei',
		'MyActionsToDo' => 'Ações que tenho que fazer',
		'MyActionsDone' => 'Ações que me afetam',
		'TasksHistoryForThisContact' => 'Ações respeito ao contato',
		'LastProspectDoNotContact' => 'Não Contactar',
		'LastProspectNeverContacted' => 'Não Contactado',
		'LastProspectToContact' => 'A Contactar',
		'LastProspectContactInProcess' => 'Contato em Curso',
		'LastProspectContactDone' => 'Clientes Potenciais Contactados',
		'DateActionPlanned' => 'Data Planificação',
		'DateActionDone' => 'Data realização',
		'ActionAskedBy' => 'Ação Questionada por',
		'ActionAffectedTo' => 'Ação associada a',
		'ActionDoneBy' => 'Ação Realizada por',
		'ActionUserAsk' => 'Registrada por',
		'ErrorStatusCantBeZeroIfStarted' => 'Se o campo \'<b>Ficha de Realização</b>\' tiver dados a ação está em curso, por isso o campo \'Estado\' não pode ser 0%%.',
		'ActionAC_TEL' => 'Chamada Telefônica',
		'ActionAC_FAX' => 'Envio Fax',
		'ActionAC_PROP' => 'Envio Orçamento por Correio',
		'ActionAC_EMAIL' => 'Envio E-Mail',
		'ActionAC_RDV' => 'Reunião',
		'ActionAC_FAC' => 'Envio Fatura por Correio',
		'ActionAC_REL' => 'Lembrete fatura por correio',
		'ActionAC_CLO' => 'Fechar',
		'ActionAC_EMAILING' => 'Envio mailing massivo',
		'ActionAC_COM' => 'Envio Pedido por Correio',
		'ActionAC_SHIP' => 'Enviar Por E-Mail',
		'ActionAC_SUP_ORD' => 'Send supplier order by mail',
		'ActionAC_SUP_INV' => 'Send supplier invoice by mail',
		'ActionAC_OTH' => 'Outro',
		'Stats' => 'Estatisticas de Venda',
		'CAOrder' => 'Ordem CA',
		'FromTo' => 'A partir de %s até %s',
		'MargeOrder' => 'Ordem da Margem',
		'RecapAnnee' => 'Recapitular um',
		'NoData' => 'Sem Dados',
		'StatusProsp' => 'Prospect status',
		'DraftPropals' => 'Draft commercial proposals',
		'SearchPropal' => 'Search a commercial proposal'
);
?>