<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$contracts = array(
		'CHARSET' => 'UTF-8',
		'ContractsArea' => 'Área Contratos',
		'ListOfContracts' => 'Lista de Contratos',
		'LastContracts' => 'Os últimos %s contratos modificados',
		'AllContracts' => 'Todos os Contratos',
		'ContractCard' => 'Ficha Contrato',
		'ContractStatus' => 'Estado do Contrato',
		'ContractStatusNotRunning' => 'Fora de Serviço',
		'ContractStatusRunning' => 'Em Serviço',
		'ContractStatusDraft' => 'Rascunho',
		'ContractStatusValidated' => 'Validado',
		'ContractStatusClosed' => 'Encerrado',
		'ServiceStatusInitial' => 'Inativo',
		'ServiceStatusRunning' => 'Em Serviço',
		'ServiceStatusNotLate' => 'Running, not expired',
		'ServiceStatusNotLateShort' => 'Not expired',
		'ServiceStatusLate' => 'Em Serviço, Expirado',
		'ServiceStatusLateShort' => 'Expirado',
		'ServiceStatusClosed' => 'Encerrado',
		'ServicesLegend' => 'Legenda para os Serviços',
		'Contracts' => 'Contratos',
		'Contract' => 'Contrato',
		'NoContracts' => 'Sem Contratos',
		'MenuServices' => 'Serviços',
		'MenuInactiveServices' => 'Serviços Inativos',
		'MenuRunningServices' => 'Serviços Ativos',
		'MenuExpiredServices' => 'Serviços Expirados',
		'MenuClosedServices' => 'Serviços Fechados',
		'NewContract' => 'Novo Contrato',
		'AddContract' => 'Criar Contrato',
		'SearchAContract' => 'Procurar um Contrato',
		'DeleteAContract' => 'Eliminar um Contrato',
		'CloseAContract' => 'Fechar um Contrato',
		'ConfirmDeleteAContract' => 'Tem certeza que quer eliminar este contrato?',
		'ConfirmValidateContract' => 'Tem certeza que quer Confirmar este contrato?',
		'ConfirmCloseContract' => 'Tem certeza que quer Fechar este contrato?',
		'ConfirmCloseService' => 'Tem certeza que quer Fechar este serviço?',
		'ValidateAContract' => 'Confirmar um contrato',
		'ActivateService' => 'Ativar o serviço',
		'ConfirmActivateService' => 'Tem certeza que quer ativar este serviço em data %s?',
		'RefContract' => 'Contract reference',
		'DateContract' => 'Data Contrato',
		'DateServiceActivate' => 'Data Ativação do Serviço',
		'DateServiceUnactivate' => 'Data Desativação do Serviço',
		'DateServiceStart' => 'Data Inicio do Serviço',
		'DateServiceEnd' => 'Data Finalização do Serviço',
		'ShowContract' => 'Mostrar Contrato',
		'ListOfServices' => 'Lista de Serviços',
		'ListOfInactiveServices' => 'List of not active services',
		'ListOfExpiredServices' => 'List of expired active services',
		'ListOfClosedServices' => 'List of closed services',
		'ListOfRunningContractsLines' => 'Lista de Linhas de Contratos em Serviço',
		'ListOfRunningServices' => 'Lista de Serviços Ativos',
		'NotActivatedServices' => 'Serviços Desativados (Com os Contratos Validados)',
		'BoardNotActivatedServices' => 'Serviços a Ativar (Com os Contratos Validados)',
		'LastContracts' => 'Os últimos %s contratos modificados',
		'LastActivatedServices' => 'Os %s últimos Serviços Ativados',
		'LastModifiedServices' => 'Os %s últimos Serviços Modificados',
		'EditServiceLine' => 'Edição Linha do Serviço',
		'ContractStartDate' => 'Data Inicio',
		'ContractEndDate' => 'Data Finalização',
		'DateStartPlanned' => 'Data Prevista de Colocação em Serviço',
		'DateStartPlannedShort' => 'Data Inicio Prevista',
		'DateEndPlanned' => 'Data Prevista Fim do Serviço',
		'DateEndPlannedShort' => 'Data Fim Prevista',
		'DateStartReal' => 'Data Real Colocação em Serviço',
		'DateStartRealShort' => 'Data Inicio',
		'DateEndReal' => 'Data Real Fim do Serviço',
		'DateEndRealShort' => 'Data Real Finalização',
		'NbOfServices' => 'No de Serviços',
		'CloseService' => 'Finalizar Serviço',
		'ServicesNomberShort' => '%s Serviço(s)',
		'RunningServices' => 'Serviços Ativos',
		'BoardRunningServices' => 'Serviços Ativos Expirados',
		'ServiceStatus' => 'Estado do Serviço',
		'DraftContracts' => 'Contratos Rascunho',
		'CloseRefusedBecauseOneServiceActive' => 'O contrato não pode ser encerrado já que contém ao menos um serviço aberto.',
		'CloseAllContracts' => 'Fechar Todos os Contratos',
		'DeleteContractLine' => 'Delete a contract line',
		'ConfirmDeleteContractLine' => 'Are you sure you want to delete this contract line ?',
		'MoveToAnotherContract' => 'Mover o serviço a outro contrato deste Fornecedor.',
		'ConfirmMoveToAnotherContract' => 'Escolhi o contrato e confirmo o alterar de serviço ao presente contrato.',
		'ConfirmMoveToAnotherContractQuestion' => 'Escolha qualquer outro contrato do mesmo Fornecedor, deseja mover este serviço?',
		'PaymentRenewContractId' => 'Renovação do Serviço (Numero %s)',
		'ExpiredSince' => 'Expirado desde',
		'RelatedContracts' => 'Related contracts',
		'NoExpiredServices' => 'No expired active services',
		////////// Types de contacts //////////
		'TypeContact_contrat_internal_SALESREPSIGN' => 'Comercial assinante do contrato',
		'TypeContact_contrat_internal_SALESREPFOLL' => 'Comercial seguimento do contrato',
		'TypeContact_contrat_external_BILLING' => 'Contato cliente de faturação do contrato',
		'TypeContact_contrat_external_CUSTOMER' => 'Contato cliente seguimento do contrato',
		'TypeContact_contrat_external_SALESREPSIGN' => 'Contato cliente assinante do contrato',
		'Error_CONTRACT_ADDON_NotDefined' => 'Constant CONTRACT_ADDON not defined'
);
?>