<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$install = array(
		'CHARSET' => 'UTF-8',
		'InstallEasy' => 'Tentámos tornar a instalação do Speedealing o mais fácil possível. É favor seguir as instruções passo-a-passo.',
		'MiscellanousChecks' => 'Pré-requisitos check',
		'SpeedealingWelcome' => 'Welcome to Speedealing',
		'ConfFileExists' => 'O arquivo de configuração <b>conf.php</b> existe.',
		'ConfFileDoesNotExists' => 'Arquivo de <b>configuração %s</b> não existe!',
		'ConfFileDoesNotExistsAndCouldNotBeCreated' => 'Arquivo de <b>configuração %s</b> não existe e não poderia ser criado!',
		'ConfFileCouldBeCreated' => 'O arquivo de configuração <b>conf.php</b> pôde ser criado.',
		'ConfFileIsNotWritable' => 'O arquivo de configuração <b>conf.php</b> não é passível de escrita, verifique as permissões sff, o seu servidor web tem de ter permissões de escrita neste arquivo cem Linux, chmod 666).',
		'ConfFileIsWritable' => 'O arquivo de configuração <b>conf.php</b> tem as permissões corretas.',
		'ConfFileReload' => 'Reload all information from configuration file.',
		'PHPSupportSessions' => 'Esta PHP suporta sessões.',
		'PHPSupportPOSTGETOk' => 'Esta PHP suporta variáveis GET e POST.',
		'PHPSupportPOSTGETKo' => 'É possível configurar o PHP não suporta variáveis POST e / ou GET. Verifique se o seu parâmetro <b>variables_order</b> em php.ini.',
		'PHPSupportGD' => 'Este suporte PHP GD gráfica funções.',
		'PHPSupportUTF8' => 'Este suporte PHP UTF8 funções.',
		'PHPMemoryOK' => 'Seu PHP max sessão memória está definido <b>para %s.</b> Isto deve ser suficiente.',
		'PHPMemoryTooLow' => 'Seu PHP max sessão memória está definido <b>para %s</b> bytes. Isto deve ser muito baixo. Alterar o seu <b>php.inem memory_limit</b> para definir parâmetro para pelo <b>menos %s</b> bytes.',
		'Recheck' => 'Clique aqui para um teste mais significativo',
		'ErrorPHPDoesNotSupportSessions' => 'Sua instalação não suporta PHP sessões. Esta característica é necessária para tornar Speedealing trabalho. Verifique a sua configuração do PHP.',
		'ErrorPHPDoesNotSupportGD' => 'Sua instalação PHP não suporta gráficos função GD. Não gráfico estarão disponíveis.',
		'ErrorPHPDoesNotSupportUTF8' => 'Sua instalação PHP não suporta UTF8 funções. Speedealing pode não funcionar corretamente. Resolva este antes de instalar Speedealing.',
		'ErrorDirDoesNotExists' => 'Diretório %s não existe.',
		'ErrorGoBackAndCorrectParameters' => 'Ir para trás e corrigir errado parâmetros.',
		'ErrorWrongValueForParameter' => 'Você pode ter digitado um valor incorreto para o parâmetro \' %s\'.',
		'ErrorFailedToCreateDatabase' => 'Erro ao criar a base de dados\' %s\'.',
		'ErrorFailedToConnectToDatabase' => 'Falha ao conectar com o banco de dados\' %s\'.',
		'ErrorDatabaseVersionTooLow' => 'Database version (%s) too old. Version %s or higher is required.',
		'ErrorPHPVersionTooLow' => 'PHP versão muito antiga. Versão %s é requerida.',
		'WarningPHPVersionTooLow' => 'PHP version too old. Version %s or more is expected. This version should allow install but is not supported.',
		'ErrorConnectedButDatabaseNotFound' => 'Login ao servidor com êxito, mas database \' %s\' não foi encontrado.',
		'ErrorDatabaseAlreadyExists' => 'Base de dados\' %s\' já existe.',
		'IfDatabaseNotExistsGoBackAndUncheckCreate' => 'Se não existe base de dados, volte e verifique a opção "Criar uma base de dados".',
		'IfDatabaseExistsGoBackAndCheckCreate' => 'Caso dados já existe, volte e desmarque "Criar uma base de dados" opção.',
		'WarningBrowserTooOld' => 'Too old version of browser. Upgrading your browser to a recent version of Firefox, Chrome or Opera is highly recommanded.',
		'PHPVersion' => 'Versão PHP',
		'YouCanContinue' => 'Pode continuar...',
		'PleaseBePatient' => 'Por favor, seja paciente ...',
		'License' => 'A usar licença',
		'ConfigurationFile' => 'Arquivo de configuração',
		'WebPagesDirectory' => 'Directoria onde armazenar as páginas web',
		'DocumentsDirectory' => 'Directoria onde armazenar documentos enviados e/ou gerados',
		'URLRoot' => 'URL de raiz',
		'ForceHttps' => 'Force secure connections (https)',
		'CheckToForceHttps' => 'Check this option to force secure connections (https).<br>This requires that the web server is configured with an SSL certificate.',
		'SpeedealingDatabase' => 'Speedealing Database',
		'DatabaseChoice' => 'Escolha de base de dados',
		'DatabaseType' => 'Tipo de base de dados',
		'DriverType' => 'Driver tipo',
		'Server' => 'Servidor',
		'ServerAddressDescription' => 'Nome ou endereço IP para o servidor de dados, normalmente \'localhost\' ao banco de dados está hospedado no mesmo servidor que servidor web',
		'ServerPortDescription' => 'Database server port. Mantenha vazio se desconhecido.',
		'DatabaseServer' => 'Database server',
		'DatabaseName' => 'Nome da base de dados',
		'DatabasePrefix' => 'Database prefix table',
		'Login' => 'Login',
		'AdminLogin' => 'Login para o administrador da base de dados Speedealing. Deixar em branco se a conexão é feita com anônimo',
		'Password' => 'Password',
		'PasswordAgain' => 'Introduza a password uma segunda vez',
		'AdminPassword' => 'Password para o administrador da base de dados Speedealing. Deixar em branco se a conexão é feita com anônimo',
		'CreateDatabase' => 'Criar uma base de dados',
		'CreateUser' => 'Criar usuário',
		'DatabaseSuperUserAccess' => 'Base de dados - Acesso Superuser',
		'CheckToCreateDatabase' => 'Verifique se caixa de dados não existe e deve ser criado. <br> Neste caso, você deve preencher o login / senha para o superusuário em conta, na parte inferior desta página.',
		'CheckToCreateUser' => 'Caixa de login, se não existe e deve ser criado. <br> Neste caso, você deve preencher o login / senha para o superusuário em conta, na parte inferior desta página.',
		'Experimental' => '(experimental, não operacional)',
		'DatabaseRootLoginDescription' => 'Login do usuário permissão para criar novas bases de dados ou de novos usuários, inútil se o seu banco de dados e seu banco de dados já existe login (como quando você está hospedado por um provedor de hospedagem da web).',
		'KeepEmptyIfNoPassword' => 'Deixar em branco se o usuário não tiver password',
		'SaveConfigurationFile' => 'Gravar configuração',
		'ConfigurationSaving' => 'A gravar...',
		'ServerConnection' => 'Conexão ao servidor',
		'DatabaseConnection' => 'Conexão à base de dados',
		'DatabaseCreation' => 'Database criação',
		'UserCreation' => 'Usuário criação',
		'CreateDatabaseObjects' => 'Criação dos objetos na base de dados...',
		'ReferenceDataLoading' => 'Dados de base a carregar...',
		'TablesAndPrimaryKeysCreation' => 'Tabelas e chaves primárias criação',
		'CreateTableAndPrimaryKey' => 'Criar tabela %s',
		'CreateOtherKeysForTable' => 'Crie chaves estrangeiras e índices para a tabela %s',
		'OtherKeysCreation' => 'Chaves estrangeiras e índices criação',
		'FunctionsCreation' => 'Funções criação',
		'AdminAccountCreation' => 'A criar login do Administradore',
		'PleaseTypePassword' => 'Por favor escreva uma password, passwords vazias não são permitidas !',
		'PleaseTypeALogin' => 'Por favor escreva um login !',
		'PasswordsMismatch' => 'As passwords diferem, tente novamente sff !',
		'SetupEnd' => 'Fim da Configuração',
		'SystemIsInstalled' => 'Instalação completa.',
		'SystemIsUpgraded' => 'Speedealing foi atualizado com êxito.',
		'YouNeedToPersonalizeSetup' => 'Agora necessita de configurar o Speedealing por forma a corresponder às suas necessidades (aspecto, funcionalidades, ...). Para tal clique no seguinte link:',
		'AdminLoginCreatedSuccessfuly' => 'Login de Administrador criado com sucesso.',
		'GoToSpeedealing' => 'Go to Speedealing',
		'GoToSetupArea' => 'Prosseguir para a área de configuração',
		'MigrationNotFinished' => 'Version of your database is not completely up to date, so you\'ll have to run the upgrade process again.',
		'GoToUpgradePage' => 'Go to upgrade page again',
		'Examples' => 'Exemplos',
		'WithNoSlashAtTheEnd' => 'Sem a barra "/" no final',
		'DirectoryRecommendation' => 'É recomendado que você ponha esta directry das páginas da web diretório.',
		'LoginAlreadyExists' => 'Já existe',
		'SpeedealingAdminLogin' => 'Speedealing admin login',
		'AdminLoginAlreadyExists' => 'Speedealing conta administrador <b>\' %s\'</b> já existe.',
		'WarningRemoveInstallDir' => 'Atenção, por razões de segurança, uma vez que a instalação ou atualização estiver completa, você deve remover o <b>diretório</b> de <b>instalação ou renomeá-lo para install.lock a fim de evitar o seu uso malicioso.</b>',
		'ThisPHPDoesNotSupportTypeBase' => 'PHP Este sistema não suporta qualquer tipo de interface para acesso de dados %s',
		'FunctionNotAvailableInThisPHP' => 'Não disponível neste PHP',
		'MigrateScript' => 'Migrar script',
		'ChoosedMigrateScript' => 'Escolhido migrar script',
		'DataMigration' => 'Migração de dados',
		'DatabaseMigration' => 'Estrutura migração de dados',
		'ProcessMigrateScript' => 'Script transformação',
		'ChooseYourSetupMode' => 'Escolha o seu modo de configuração e clique em "Iniciar" ...',
		'FreshInstall' => 'Fresh instalar',
		'FreshInstallDesc' => 'Utilize este modo, se esta for a primeira instalação. Se não, este modo pode reparar uma instalação anterior incompleto, mas se você deseja atualizar sua versão, selecione "Atualizar" modo.',
		'Upgrade' => 'Upgrade',
		'UpgradeDesc' => 'Use este modo se você tiver substituído Speedealing antigos arquivos com arquivos de uma versão mais recente. Isto irá atualizar o seu banco de dados e dados.',
		'Start' => 'Iniciar',
		'InstallNotAllowed' => 'Instalação não permitidas pela <b>conf.php</b> permissões',
		'NotAvailable' => 'Não disponível',
		'YouMustCreateWithPermission' => 'Você deve criar o arquivo %s e definir permissões escrever sobre ele para instalar o servidor web durante o processo.',
		'CorrectProblemAndReloadPage' => 'Corrija o problema e pressione a tecla F5 para recarregar página.',
		'AlreadyDone' => 'Já migrou',
		'DatabaseVersion' => 'Database versão',
		'ServerVersion' => 'Database server version',
		'YouMustCreateItAndAllowServerToWrite' => 'Você deve criar este diretório e para permitir que o servidor da web para escrever nela.',
		'CharsetChoice' => 'Conjunto de caracteres escolha',
		'CharacterSetClient' => 'Conjunto de caracteres utilizados para páginas HTML geradas',
		'CharacterSetClientComment' => 'Escolher conjunto de caracteres para exibir na web. <br/> Padrão proposto um conjunto de caracteres é o do seu banco de dados.',
		'CollationConnection' => 'Caracteres triagem fim',
		'CollationConnectionComment' => 'Escolha página código que define o caráter triagem fim utilizado por base de dados. Este parâmetro é também chamado de "recolha" por alguns bancos de dados. <br/> Esse parâmetro não pode ser definido se de dados já existe.',
		'CharacterSetDatabase' => 'Conjunto de caracteres para o banco de dados',
		'CharacterSetDatabaseComment' => 'Escolher conjunto de caracteres queria para o banco de dados criação. <br/> Esse parâmetro não pode ser definido se de dados já existe.',
		'YouAskDatabaseCreationSoSpeedealingNeedToConnect' => 'You ask to create database <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'YouAskLoginCreationSoSpeedealingNeedToConnect' => 'You ask to create database login <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'BecauseConnectionFailedParametersMayBeWrong' => 'Como conexão falhou, de acolhimento ou super usuário parâmetros devem ser errado.',
		'OrphelinsPaymentsDetectedByMethod' => 'Orphelins pagamento detectado pelo método %s',
		'RemoveItManuallyAndPressF5ToContinue' => 'Removê-lo manualmente e pressione F5 para continuar.',
		'KeepDefaultValuesWamp' => 'Você usa o DoliWamp Setup Wizard, para valores propostos aqui já estão otimizados. Alterá-los apenas se souber o que você faz.',
		'KeepDefaultValuesDeb' => 'You use the Speedealing setup wizard from a Linux package (Ubuntu, Debian, Fedora...), so values proposed here are already optimized. Only the password of the database owner to create must be completed. Change other parameters only if you know what you do.',
		'KeepDefaultValuesMamp' => 'Você usa o DoliMamp Setup Wizard, para valores propostos aqui já estão otimizados. Alterá-los apenas se souber o que você faz.',
		'KeepDefaultValuesProxmox' => 'You use the Speedealing setup wizard from a Proxmox virtual appliance, so values proposed here are already optimized. Change them only if you know what you do.',
		'FieldRenamed' => 'Campo renomeado',
		'IfLoginDoesNotExistsCheckCreateUser' => 'Se login não existe ainda, você deve verificar a opção "Criar usuário"',
		'ErrorConnection' => 'Servidor <b>" %s",</b> nome do banco de dados <b>" %s",</b> login <b>" %s",</b> ou banco de dados senha pode estar errado ou PHP versão cliente pode ser muito velho para comparação de dados versão.',
		'InstallChoiceRecommanded' => 'Recommended choice to install version <b>%s</b> from your current version <b>%s</b>',
		'InstallChoiceSuggested' => '<b>Install choice suggested by installer</b>.',
		'MigrateIsDoneStepByStep' => 'The targeted version (%s) has a gap of several versions, so install wizard will come back to suggest next migration once this one will be finished.',
		'CheckThatDatabasenameIsCorrect' => 'Check that database name "<b>%s</b>" is correct.',
		'IfAlreadyExistsCheckOption' => 'If this name is correct and that database does not exist yet, you must check option "Create database".',
		'OpenBaseDir' => 'PHP openbasedir parameter',
		'YouAskToCreateDatabaseSoRootRequired' => 'You checked the box "Create database". For this, you need to provide login/password of superuser (bottom of form).',
		'YouAskToCreateDatabaseUserSoRootRequired' => 'You checked the box "Create database owner". For this, you need to provide login/password of superuser (bottom of form).',
		'NextStepMightLastALongTime' => 'Current step may last several minutes. Please wait until the next screen is shown completely before continuing.',
		'LastStepDesc' => '<strong>Last step</strong>: Define here login and password you plan to use to connect to software. Do not loose this as it is the account to administer all others.',
		'ActivateModule' => 'Activate module %s',
		'ShowEditTechnicalParameters' => 'Click here to show/edit advanced parameters (expert mode)',
		'ServerPortCouchdbDescription' => 'Port du serveur. Défaut 5984.',
		'ServerAddressCouchdbDescription' => 'Nom FQDN du serveur de base de données, \'localhost.localdomain\' quand le serveur est installé sur la même machine que le serveur web',
		'DatabaseCouchdbUserDescription' => 'Login du super administrateur ayant tous les droits sur le serveur CouchDB ou l\'administrateur propriétaire de la base si la base et son compte d\'accès existent déjà (comme lorsque vous êtes chez un hébergeur).<br><br><div class="alert-box info">Cet utilisateur/mot de passe sera l\'administrateur pour se connecter à Speedealing.</div>',
		'CheckToCreateCouchdbDatabase' => 'Cochez cette option si la base de données n\'existe pas et doit être créée.',
		'CreateAdminUser' => 'Créer le super administrateur (Première installation de couchDB)',
		'MemcachedDescription' => 'Activer Memcached necessite l\'installation d\'un serveur Memcached et des lib php-memcached ou php-memcache. Il peut être activer après l\'installation.',
		'ServerAddressMemcachedDesc' => 'Nom ou adresse ip du serveur memcached, généralement \'localhost\' quand le serveur est installé sur la même machine que le serveur web',
		'ServerPortMemcachedDesc' => 'Port du serveur memcached. Défaut : 11211',
		'EnabledMemcached' => 'Activer Memcached',
		'DatabaseNoSQL' => 'Base de données CouchDB',
		'FailedToCreateAdminLogin' => 'Echec de la création du compte administrateur Speedealing.',
		'LinkedElementsInvalidDeleted' => '<b>%s</b> liaisons invalides ont été supprimées',
		'NothingToDelete' => 'Aucune liaison invalide trouvée',
		'SourceType' => 'Source',
		'TargetType' => 'Cible',
                // Upgrade
                'UpgradeOk' => 'Upgrade is ok !',
                'NewInstalledVersion' => 'Your new version is %s',
                'NeedUpgrade' => 'New Speedealing version !',
                'WarningUpgrade' => 'Installed version is %s, you must upgrade to %s. <br>Please contact your administrator.'
);
?>