<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$orders = array(
		'CHARSET' => 'UTF-8',
		'OrdersArea' => 'Área de Pedidos de Clientes',
		'SuppliersOrdersArea' => 'Área de Pedidos a Fornecedores',
		'OrderCard' => 'Ficha Pedido',
		'OrderId' => 'Order Id',
		'Order' => 'Pedido',
		'Orders' => 'Pedidos',
		'OrderLine' => 'Linha de Comando',
		'OrderLines' => 'Order lines',
		'OrderFollow' => 'Seguimento',
		'OrderDate' => 'Data Pedido',
		'OrderToProcess' => 'Order to process',
		'NewOrder' => 'Novo Pedido',
		'ToOrder' => 'Realizar Pedido',
		'MakeOrder' => 'Realizar Pedido',
		'SupplierOrder' => 'Pedido a Fornecedor',
		'SuppliersOrders' => 'Pedidos a Fornecedores',
		'SuppliersOrdersRunning' => 'Pedidos a Fornecedores em Curso',
		'CustomerOrder' => 'Pedido de Cliente',
		'CustomersOrders' => 'Pedidos de Clientes',
		'CustomersOrdersRunning' => 'Pedidos de Clientes em Curso',
		'CustomersOrdersAndOrdersLines' => 'Pedidos de Clientes e Linhas de Pedido',
		'OrdersToValid' => 'Pedidos a Confirmar',
		'OrdersToBill' => 'Pedidos por Faturar',
		'OrdersInProcess' => 'Pedidos em Processo',
		'OrdersToProcess' => 'Pedidos a Processar',
		'SuppliersOrdersToProcess' => 'Supplier\'s orders to process',
		'StatusOrderCanceledShort' => 'Anulado',
		'StatusOrderDraftShort' => 'Rascunho',
		'StatusOrderValidatedShort' => 'Validado',
		'StatusOrderSentShort' => 'In process',
		'StatusOrderSent' => 'Shipment in process',
		'StatusOrderOnProcessShort' => 'Em curso',
		'StatusOrderProcessedShort' => 'Processado',
		'StatusOrderToBillShort' => 'A Faturar',
		'StatusOrderToBill2Short' => 'To bill',
		'StatusOrderApprovedShort' => 'Aprovado',
		'StatusOrderRefusedShort' => 'Reprovado',
		'StatusOrderToProcessShort' => 'A Processar',
		'StatusOrderReceivedPartiallyShort' => 'Recebido Parcialmente',
		'StatusOrderReceivedAllShort' => 'Recebido',
		'StatusOrderCanceled' => 'Anulado',
		'StatusOrderDraft' => 'Rascunho (a Confirmar)',
		'StatusOrderValidated' => 'Validado',
		'StatusOrderOnProcess' => 'Em processo',
		'StatusOrderProcessed' => 'Processado',
		'StatusOrderToBill' => 'A Faturar',
		'StatusOrderToBill2' => 'To bill',
		'StatusOrderApproved' => 'Aprovado',
		'StatusOrderRefused' => 'Reprovado',
		'StatusOrderReceivedPartially' => 'Recebido Parcialmente',
		'StatusOrderReceivedAll' => 'Recebido',
		'ShippingExist' => 'A shipment exists',
		'DraftOrWaitingApproved' => 'Rascunho aprovado mas ainda não controlado',
		'DraftOrWaitingShipped' => 'Rascunho o validado mas ainda não expedido',
		'MenuOrdersToBill' => 'Pedidos por Faturar',
		'MenuOrdersToBill2' => 'Orders to bill',
		'SearchOrder' => 'Procurar um Pedido',
		'Sending' => 'Envio',
		'Sendings' => 'Envíos',
		'ShipProduct' => 'Enviar Produto',
		'Discount' => 'Desconto',
		'CreateOrder' => 'Criar Pedido',
		'RefuseOrder' => 'Rejeitar o Pedido',
		'ApproveOrder' => 'Aceitar o Pedido',
		'ValidateOrder' => 'Confirmar o Pedido',
		'UnvalidateOrder' => 'Unvalidate order',
		'DeleteOrder' => 'Eliminar o pedido',
		'CancelOrder' => 'Anular o Pedido',
		'AddOrder' => 'Criar Pedido',
		'AddToMyOrders' => 'Adicionar os meus Pedidos',
		'AddToOtherOrders' => 'Adicionar a outros pedidos',
		'ShowOrder' => 'Mostrar Pedido',
		'NoOpenedOrders' => 'Nenhum pedido em aberto',
		'NoOtherOpenedOrders' => 'Nenhum outro pedido aberto',
		'OtherOrders' => 'Outros Pedidos',
		'LastOrders' => 'Os %s últimos pedidos',
		'LastModifiedOrders' => 'Os %s últimos pedidos modificados',
		'LastClosedOrders' => 'Os últimos %s Pedidos',
		'AllOrders' => 'Todos os Pedidos',
		'NbOfOrders' => 'Número de Pedidos',
		'OrdersStatistics' => 'Estatísticas de pedidos',
		'OrdersStatisticsSuppliers' => 'Estatísticas de Pedidos a Fornecedores',
		'NumberOfOrdersByMonth' => 'Número de Pedidos por Mês',
		'AmountOfOrdersByMonthHT' => 'Valor total de pedidos por mês (sem ICMS)',
		'ListOfOrders' => 'Lista de Pedidos',
		'CloseOrder' => 'Fechar Pedido',
		'ConfirmCloseOrder' => 'Tem certeza de que deseja fechar este pedido? Quando um pedido é fechado, ele só pode ser cobrado.',
		'ConfirmCloseOrderIfSending' => 'Tem certeza de que deseja fechar este pedido? Veve fechar no somente quando todos os transfretes marítimos são feitos.',
		'ConfirmDeleteOrder' => 'Tem certeza que quer eliminar este pedido?',
		'ConfirmValidateOrder' => 'Tem certeza que quer Confirmar este pedido sobre a referencia <b>%s</b> ?',
		'ConfirmUnvalidateOrder' => 'Are you sure you want to restore order <b>%s</b> to draft status ?',
		'ConfirmCancelOrder' => 'Tem certeza que quer anular este pedido?',
		'ConfirmMakeOrder' => 'Tem certeza que quer confirmar este pedido em data de<b>%s</b> ?',
		'GenerateBill' => 'Faturar',
		'ClassifyShipped' => 'Classify delivered',
		'ClassifyBilled' => 'Classificar "Faturado"',
		'ComptaCard' => 'Ficha Contabilidade',
		'DraftOrders' => 'Rascunhos de Pedidos',
		'RelatedOrders' => 'Pedidos Anexos',
		'OnProcessOrders' => 'Pedidos em Processo',
		'RefOrder' => 'Ref. Pedido',
		'RefCustomerOrder' => 'Ref. Pedido Cliente',
		'CustomerOrder' => 'Pedido de Cliente',
		'RefCustomerOrderShort' => 'Ref. Ped. Cliente',
		'SendOrderByMail' => 'Enviar pedido por e-mail',
		'ActionsOnOrder' => 'Ações sobre o pedido',
		'NoArticleOfTypeProduct' => 'Não existe artigos de tipo \'produto\' e por tanto expedidos neste pedido',
		'OrderMode' => 'Método de pedido',
		'AuthorRequest' => 'Autor/Solicitante',
		'UseCustomerContactAsOrderRecipientIfExist' => 'Utilizar endereço do contato do cliente de seguimento cliente se está definido em vez do Fornecedor como destinatário dos pedidos',
		'RunningOrders' => 'Pedidos em Curso',
		'UserWithApproveOrderGrant' => 'Usuários autorizados a aprovar os pedidos.',
		'PaymentOrderRef' => 'Pagamento de Pedido %s',
		'CloneOrder' => 'Copiar o Pedido',
		'ConfirmCloneOrder' => 'Tem certeza de que deseja clonar este<b>%s</b> ?',
		'DispatchSupplierOrder' => 'Receiving supplier order %s',
		'DateDeliveryPlanned' => 'Date de livraison prévue',
		'SetDemandReason' => 'Définir l\'origine de la commande',
		////////// Types de contacts //////////
		'TypeContact_commande_internal_SALESREPFOLL' => 'Representative following-up customer order',
		'TypeContact_commande_internal_SHIPPING' => 'Representative following-up shipping',
		'TypeContact_commande_external_BILLING' => 'Customer invoice contact',
		'TypeContact_commande_external_SHIPPING' => 'Customer shipping contact',
		'TypeContact_commande_external_CUSTOMER' => 'Customer contact following-up order',
		'TypeContact_order_supplier_internal_SALESREPFOLL' => 'Representative following-up supplier order',
		'TypeContact_order_supplier_internal_SHIPPING' => 'Representative following-up shipping',
		'TypeContact_order_supplier_external_BILLING' => 'Supplier invoice contact',
		'TypeContact_order_supplier_external_SHIPPING' => 'Supplier shipping contact',
		'TypeContact_order_supplier_external_CUSTOMER' => 'Supplier contact following-up order',
		'Error_COMMANDE_SUPPLIER_ADDON_NotDefined' => 'Constante COMMANDE_SUPPLIER_ADDON não definida',
		'Error_COMMANDE_ADDON_NotDefined' => 'Constante COMMANDE_ADDON não definida',
		'Error_FailedToLoad_COMMANDE_SUPPLIER_ADDON_File' => 'Erro na carga do Arquivo módulo \'%s\'',
		'Error_FailedToLoad_COMMANDE_ADDON_File' => 'Erro na carga de arquivo módulo \'%s\'',
		'Error_OrderNotChecked' => 'No orders to invoice selected',
		// Sources
		'OrderSource0' => 'Orçamento Proposto',
		'OrderSource1' => 'Internet',
		'OrderSource2' => 'Campanha por correio',
		'OrderSource3' => 'Campanha telefônica',
		'OrderSource4' => 'Campanha por fax',
		'OrderSource5' => 'Comercial',
		'OrderSource6' => 'Revistas',
		'QtyOrdered' => 'Quant. Pedida',
		'AddDeliveryCostLine' => 'Adicionar uma linha de despesas de fretes indicando o peso do pedido',
		// Documents models
		'PDFEinsteinDescription' => 'Modelo de orçamento completo (logo...)',
		'PDFEdisonDescription' => 'A simple order model',
		// Orders modes
		'OrderByMail' => 'Mail',
		'OrderByFax' => 'Fax',
		'OrderByEMail' => 'EMail',
		'OrderByWWW' => 'Online',
		'OrderByPhone' => 'Phone',
		'CreateInvoiceForThisCustomer' => 'Bill orders',
		'NoOrdersToInvoice' => 'No orders billable',
		'CloseProcessedOrdersAutomatically' => 'Classify "Processed" all selected orders.',
		'MenuOrdersToBill2' => 'Orders to bill',
		'LinkedInvoices' => 'Linked invoices',
		'LinkedProposals' => 'Linked proposals'
);
?>