<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$projects = array(
		'CHARSET' => 'UTF-8',
		'Project' => 'Projeto',
		'Projects' => 'Projetos',
		'SharedProject' => 'Projeto Compartilhado',
		'PrivateProject' => 'Contatos do Projeto',
		'MyProjectsDesc' => 'This view is limited to projects you are a contact for (whatever is the type).',
		'ProjectsPublicDesc' => 'This view presents all projects you are allowed to read.',
		'ProjectsDesc' => 'This view presents all projects (your user permissions grant you permission to view everything).',
		'MyTasksDesc' => 'This view is limited to projects or tasks you are a contact for (whatever is the type).',
		'TasksPublicDesc' => 'This view presents all projects and tasks you are allowed to read.',
		'TasksDesc' => 'This view presents all projects and tasks (your user permissions grant you permission to view everything).',
		'Myprojects' => 'Os Meus Projetos',
		'ProjectsArea' => 'Área de Projetos',
		'NewProject' => 'Novo Projeto',
		'AddProject' => 'Criar Projeto',
		'DeleteAProject' => 'Eliminar um Projeto',
		'DeleteATask' => 'Eliminar uma Tarefa',
		'ConfirmDeleteAProject' => 'Tem certeza que quer eliminar este projeto?',
		'ConfirmDeleteATask' => 'Tem certeza que quer eliminar esta tarefa?',
		'OfficerProject' => 'Responsável do Projeto',
		'LastProjects' => 'Os %s últimos Projetos',
		'AllProjects' => 'Todos os Projetos',
		'ProjectsList' => 'Lista de Projetos',
		'ShowProject' => 'Adicionar Projeto',
		'SetProject' => 'Definir Projeto',
		'NoProject' => 'Nenhum Projeto Definido',
		'NbOpenTasks' => 'No Tarefas Abertas',
		'NbOfProjects' => 'No de Projetos',
		'TimeSpent' => 'Tempo Dedicado',
		'TimesSpent' => 'Time spent',
		'RefTask' => 'Ref. Tarefa',
		'LabelTask' => 'Etiqueta de Tarefa',
		'NewTimeSpent' => 'Novo Tempo Dedicado',
		'MyTimeSpent' => 'O Meu Tempo Dedicado',
		'MyTasks' => 'As minhas Tarefas',
		'Tasks' => 'Tarefas',
		'Task' => 'Tarefa',
		'NewTask' => 'Nova Tarefa',
		'AddTask' => 'Adicionar Tarefa',
		'AddDuration' => 'Indicar Duração',
		'Activity' => 'Atividade',
		'Activities' => 'Tarefas/Atividades',
		'MyActivity' => 'A Minha Atividade',
		'MyActivities' => 'Minhas Tarefas/Atividades',
		'MyProjects' => 'Os Meus Projetos',
		'DurationEffective' => 'Duração Efetiva',
		'Progress' => 'Progress',
		'Time' => 'Tempo',
		'ListProposalsAssociatedProject' => 'Lista de Orçamentos Associados ao Projeto',
		'ListOrdersAssociatedProject' => 'Lista de Pedidos Associados ao Projeto',
		'ListInvoicesAssociatedProject' => 'Lista de Faturas Associadas ao Projeto',
		'ListPredefinedInvoicesAssociatedProject' => 'Lista de Faturas a Clientes Predefinidas Associadas ao Projeto',
		'ListSupplierOrdersAssociatedProject' => 'Lista de Pedidos a Fornecedores Associados ao Projeto',
		'ListSupplierInvoicesAssociatedProject' => 'Lista de Faturas de Fornecedor Associados ao Projeto',
		'ListContractAssociatedProject' => 'Lista de Contratos Associados ao Projeto',
		'ListFichinterAssociatedProject' => 'List of interventions associated with the project',
		'ListTripAssociatedProject' => 'List of trips and expenses associated with the project',
		'ListActionsAssociatedProject' => 'List of events associated with the project',
		'ActivityOnProjectThisWeek' => 'Atividade ao Projeto esta Semana',
		'ActivityOnProjectThisMonth' => 'Atividade ao Projeto este Mês',
		'ActivityOnProjectThisYear' => 'Atividade ao Projeto este Ano',
		'ChildOfTask' => 'Link da Tarefa',
		'NotOwnerOfProject' => 'Não é responsável deste projeto privado',
		'AffectedTo' => 'Atribuido a',
		'CantRemoveProject' => 'Este projeto não pode ser eliminado porque está referenciado por muito objetos (facturas, pedidos e outros). ver a lista no separador referencias.',
		'ValidateProject' => 'Validate projet',
		'ConfirmValidateProject' => 'Are you sure you want to validate this project ?',
		'CloseAProject' => 'Close project',
		'ConfirmCloseAProject' => 'Are you sure you want to close this project ?',
		'ReOpenAProject' => 'Open project',
		'ConfirmReOpenAProject' => 'Are you sure you want to re-open this project ?',
		'ProjectContact' => 'Project contacts',
		'ActionsOnProject' => 'Events on project',
		'YouAreNotContactOfProject' => 'You are not a contact of this private project',
		'DeleteATimeSpent' => 'Delete time spent',
		'ConfirmDeleteATimeSpent' => 'Are you sure you want to delete this time spent ?',
		'DoNotShowMyTasksOnly' => 'See also tasks not allocated to me',
		'ShowMyTasksOnly' => 'View only tasks allocated to me',
		'TaskRessourceLinks' => 'Ressources',
		'ProjectsDedicatedToThisThirdParty' => 'Projects dedicated to this third party',
		'NoTasks' => 'No tasks for this project',
		'LinkedToAnotherCompany' => 'Linked to other third party',
		'TaskIsNotAffectedToYou' => 'Task not allocated to you',
		'ErrorTimeSpentIsEmpty' => 'Time spent is empty',
		'ThisWillAlsoRemoveTasks' => 'This action will also delete all tasks of project (<b>%s</b> tasks at the moment) and all inputs of time spent.',
		'IfNeedToUseOhterObjectKeepEmpty' => 'If some objects (invoice, order, ...), belonging to another third party, must be linked to the project to create, keep this empty to have the project being multi third parties.',
		'CloneProject' => 'Clone project',
		'CloneTasks' => 'Clone tasks',
		'CloneContacts' => 'Clone contacts',
		'CloneNotes' => 'Clone notes',
		'CloneFiles' => 'Clone joined files',
		'ConfirmCloneProject' => 'Are you sure to clone this project ?',
		'ProjectReportDate' => 'Change task date according project start date',
		'ErrorShiftTaskDate' => 'Impossible to shift task date according to new project start date',
		////////// Types de contacts //////////
		'TypeContact_project_internal_PROJECTLEADER' => 'Project leader',
		'TypeContact_project_external_PROJECTLEADER' => 'Project leader',
		'TypeContact_project_internal_CONTRIBUTOR' => 'Contributor',
		'TypeContact_project_external_CONTRIBUTOR' => 'Contributor',
		'TypeContact_project_task_internal_TASKEXECUTIVE' => 'Task executive',
		'TypeContact_project_task_external_TASKEXECUTIVE' => 'Task executive',
		'TypeContact_project_task_internal_CONTRIBUTOR' => 'Contributor',
		'TypeContact_project_task_external_CONTRIBUTOR' => 'Contributor',
		// Documents models
		'DocumentModelBaleine' => 'A complete project\'s report model (logo...)'
);
?>