<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$propal = array(
		'CHARSET' => 'UTF-8',
		'Proposals' => 'Orçamentos',
		'Proposal' => 'Orçamento',
		'ProposalShort' => 'Proposal',
		'ProposalsDraft' => 'Orçamentos Rascunho',
		'ProposalDraft' => 'Orçamento Rascunho',
		'ProposalsOpened' => 'Orçamentos Abertos',
		'Prop' => 'Orçamentos',
		'CommercialProposal' => 'Orçamento',
		'CommercialProposals' => 'Orçamentos',
		'ProposalCard' => 'Proposal card',
		'NewProp' => 'Novo Orçamento',
		'NewProposal' => 'Novo Orçamento',
		'NewPropal' => 'Novo Orçamento',
		'Prospect' => 'Cliente Potencial',
		'ProspectList' => 'Lista de Clientes Potenciais',
		'DeleteProp' => 'Eliminar Orçamento',
		'ValidateProp' => 'Confirmar Orçamento',
		'AddProp' => 'Criar Orçamento',
		'ConfirmDeleteProp' => 'Tem certeza que quer eliminar este orçamento?',
		'ConfirmValidateProp' => 'Tem certeza que quer Confirmar este orçamento?',
		'LastPropals' => 'Os %s últimos Orçamentos',
		'LastClosedProposals' => 'Os últimos Orçamentos Encerrados',
		'LastModifiedProposals' => 'As últimas %s propostas modificadas',
		'AllPropals' => 'Todos Os Orçamentos',
		'LastProposals' => 'últimos Orçamentos',
		'SearchAProposal' => 'Procurar um Orçamento',
		'ProposalsStatistics' => 'Estatísticas de Orçamentos',
		'NumberOfProposalsByMonth' => 'Número por Mês',
		'AmountOfProposalsByMonthHT' => 'Valor por Mês (sem ICMS)',
		'NbOfProposals' => 'Número Orçamentos',
		'ShowPropal' => 'Ver Orçamento',
		'PropalsDraft' => 'Rascunho',
		'PropalsOpened' => 'Abertos',
		'PropalsNotBilled' => 'Não Faturados',
		'PropalStatusDraft' => 'Rascunho (A Confirmar)',
		'PropalStatusValidated' => 'Validado (Orçamento Aberto)',
		'PropalStatusOpened' => 'Validado (Orçamento Aberto)',
		'PropalStatusClosed' => 'Encerrado',
		'PropalStatusSigned' => 'Assinado (A Faturar)',
		'PropalStatusNotSigned' => 'Sem Assinar (Encerrado)',
		'PropalStatusBilled' => 'Faturado',
		'PropalStatusDraftShort' => 'Rascunho',
		'PropalStatusValidatedShort' => 'Validado',
		'PropalStatusOpenedShort' => 'Aberto',
		'PropalStatusClosedShort' => 'Encerrado',
		'PropalStatusSignedShort' => 'Assinado',
		'PropalStatusNotSignedShort' => 'Sem Assinar',
		'PropalStatusBilledShort' => 'Faturado',
		'PropalsToClose' => 'Orçamentos a Fechar',
		'PropalsToBill' => 'Orçamentos Assinados a Faturar',
		'ListOfProposals' => 'Lista de Orçamentos',
		'ActionsOnPropal' => 'Ações sobre o Orçamento',
		'NoOpenedPropals' => 'Sem Orçamentos Abertos',
		'NoOtherOpenedPropals' => 'Nenhum outro orçamento aberto',
		'RefProposal' => 'Ref. Orçamento',
		'SendPropalByMail' => 'Enviar Orçamento por E-mail',
		'FileNotUploaded' => 'Não foi Carregado o Arquivo',
		'FileUploaded' => 'O Arquivo foi carregado corretamente',
		'AssociatedDocuments' => 'Documentos Associados ao Orçamento :',
		'ErrorCantOpenDir' => 'Impossível Abrir a Pasta',
		'DatePropal' => 'Data da Proposta',
		'DateEndPropal' => 'Válido até',
		'DateEndPropalShort' => 'Data Fim',
		'ValidityDuration' => 'Duração da Validade',
		'CloseAs' => 'Fechado como',
		'ClassifyBilled' => 'Classificar Faturado',
		'BuildBill' => 'Criar Fatura',
		'ErrorPropalNotFound' => 'Orçamento %s Inexistente',
		'Estimate' => 'Orçamento:',
		'EstimateShort' => 'Orç.',
		'OtherPropals' => 'Outros Orçamentos',
		'CopyPropalFrom' => 'Criar orçamento por Cópia de um existente',
		'CreateEmptyPropal' => 'Criar orçamento a partir da Lista de produtos predefinidos',
		'DefaultProposalDurationValidity' => 'Prazo de validez por default (em dias)',
		'UseCustomerContactAsPropalRecipientIfExist' => 'Utilizar endereço contato de seguimento de cliente definido em vez do endereço do Fornecedor como destinatário dos Orçamentos',
		'ClonePropal' => 'Colonar Proposta Comercial',
		'ConfirmClonePropal' => 'Tem a certeza que deseja colonar a proposta comercial <b>%s</b>?',
		'ConfirmReOpenProp' => 'Are you sure you want to open back the commercial proposal <b>%s</b> ?',
		'ProposalsAndProposalsLines' => 'Propostas para clientes e diretrizes para apresentação de propostas',
		'ProposalLine' => 'Linha da Proposta',
		'ProposalLines' => 'Proposal lines',
		'AvailabilityPeriod' => 'Availability delay',
		'SetAvailability' => 'Set availability delay',
		'AfterOrder' => 'after order',
		////////// Availability //////////
		'AvailabilityTypeAV_NOW' => 'Immediate',
		'AvailabilityTypeAV_1W' => '1 week',
		'AvailabilityTypeAV_2W' => '2 weeks',
		'AvailabilityTypeAV_3W' => '3 weeks',
		'AvailabilityTypeAV_1M' => '1 month',
		////////// Types de contacts //////////
		'TypeContact_propal_internal_SALESREPFOLL' => 'Representative following-up proposal',
		'TypeContact_propal_external_BILLING' => 'Customer invoice contact',
		'TypeContact_propal_external_CUSTOMER' => 'Customer contact following-up proposal',
		// Document models
		'DocModelAzurDescription' => 'Modelo de orçamento completo (logo...)',
		'DocModelJauneDescription' => 'Modelo de Orçamento Jaune',
		'Numbershort' => 'N°',
		'LinkdedOrders' => 'Linked orders'
);
?>