<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Ficha Armazém',
		'Warehouse' => 'Armazém',
		'Warehouses' => 'Warehouses',
		'NewWarehouse' => 'Novo Armazém ou Zona de Armazenagem',
		'WarehouseEdit' => 'Modify warehouse',
		'MenuNewWarehouse' => 'Novo Armazém',
		'WarehouseOpened' => 'Armazém Aberto',
		'WarehouseClosed' => 'Armazém Encerrado',
		'WarehouseSource' => 'Armazém Origem',
		'WarehouseSourceNotDefined' => 'No warehouse defined,',
		'AddOne' => 'Add one',
		'WarehouseTarget' => 'Armazém Destino',
		'ValidateSending' => 'Confirmar Envio',
		'CancelSending' => 'Cancelar Envio',
		'DeleteSending' => 'Eliminar Envio',
		'Stock' => 'Estoque',
		'Stocks' => 'Estoques',
		'Movement' => 'Movimento',
		'Movements' => 'Movimentos',
		'ErrorWarehouseRefRequired' => 'O nome de referencia do armazém é obrigatório',
		'ErrorWarehouseLabelRequired' => 'A etiqueta do armazém é obrigatória',
		'CorrectStock' => 'Corrigir Estoque',
		'ListOfWarehouses' => 'Lista de Armazens',
		'ListOfStockMovements' => 'Lista de movimentos de estoque',
		'StocksArea' => 'Área estoques',
		'Location' => 'Localização',
		'LocationSummary' => 'Nome abreviado da localização',
		'NumberOfProducts' => 'Numero total de produtos',
		'LastMovement' => 'Último movimento',
		'LastMovements' => 'Últimos movimentos',
		'Units' => 'Unidades',
		'Unit' => 'Unidade',
		'StockCorrection' => 'Correção estoque',
		'StockMovement' => 'Transferencia',
		'StockMovements' => 'Movimentos de estoque',
		'NumberOfUnit' => 'Número de peças',
		'UnitPurchaseValue' => 'Unit purchase price',
		'TotalStock' => 'Total em estoque',
		'StockTooLow' => 'Estoque insuficiente',
		'StockLowerThanLimit' => 'Stock lower than alert limit',
		'EnhancedValue' => 'Valor',
		'PMPValue' => 'Valor (PMP)',
		'PMPValueShort' => 'PMP',
		'EnhancedValueOfWarehouses' => 'Valor de estoques',
		'UserWarehouseAutoCreate' => 'Criar existencias automaticamente na criação de um usuário',
		'QtyDispatched' => 'Quantidade desagregada',
		'OrderDispatch' => 'Recepção de estoques',
		'RuleForStockManagementDecrease' => 'Regra de Administração de decrementos de estoque',
		'RuleForStockManagementIncrease' => 'Regra de Administração de incrementos de estoque',
		'DeStockOnBill' => 'Decrementar os estoques físicos sobre as faturas/recibos',
		'DeStockOnValidateOrder' => 'Decrementar os estoques físicos sobre os pedidos',
		'DeStockOnShipment' => 'Decrementar os estoques físicos sobre os envios (recomendado)',
		'ReStockOnBill' => 'Incrementar os estoques físicos sobre as faturas/recibos',
		'ReStockOnValidateOrder' => 'Incrementar os estoques físicos sobre os pedidos',
		'ReStockOnDispatchOrder' => 'Increase real stocks on manual dispatching into warehouses, after supplier order receiving',
		'OrderStatusNotReadyToDispatch' => 'Order has not yet or no more a status that allows dispatching of products in stock warehouses.',
		'StockDiffPhysicTeoric' => 'Motivo da diferença entre valores físicos e teóricos',
		'NoPredefinedProductToDispatch' => 'No predefined products for this object. So no dispatching in stock is required.',
		'DispatchVerb' => 'Dispatch',
		'StockLimitShort' => 'Límite máximo',
		'StockLimit' => 'Límite máximo existencias',
		'PhysicalStock' => 'Estoque físico',
		'RealStock' => 'Estoque real',
		'TheoreticalStock' => 'Estoque teórico',
		'VirtualStock' => 'Estoque virtual',
		'MininumStock' => 'Estoque mínimo',
		'StockUp' => 'Estoque máximo',
		'MininumStockShort' => 'Estoque min.',
		'StockUpShort' => 'Estoque max.',
		'IdWarehouse' => 'Id. armazém',
		'DescWareHouse' => 'Descrição armazém',
		'LieuWareHouse' => 'Localização armazém',
		'WarehousesAndProducts' => 'Armazens e produtos',
		'AverageUnitPricePMPShort' => 'Weighted average input price',
		'AverageUnitPricePMP' => 'Weighted average input price',
		'SellPriceMin' => 'Selling Unit Price',
		'EstimatedStockValueSellShort' => 'Value to sell',
		'EstimatedStockValueSell' => 'Value to Sell',
		'EstimatedStockValueShort' => 'Input stock value',
		'EstimatedStockValue' => 'Input stock value',
		'DeleteAWarehouse' => 'Delete a warehouse',
		'ConfirmDeleteWarehouse' => 'Are you sure you want to delete the warehouse <b>%s</b> ?',
		'PersonalStock' => 'Personal stock %s',
		'ThisWarehouseIsPersonalStock' => 'This warehouse represents personal stock of %s %s',
		'SelectWarehouseForStockDecrease' => 'Choose warehouse to use for stock decrease',
		'SelectWarehouseForStockIncrease' => 'Choose warehouse to use for stock increase',
		'LastWaitingSupplierOrders' => 'Orders waiting for receptions'
);
?>