<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$withdrawals = array(
		'CHARSET' => 'UTF-8',
		'StandingOrdersArea' => 'Área de Débitos Diretos',
		'CustomersStandingOrdersArea' => 'Área de Débitos Diretos de Clientes',
		'StandingOrders' => 'Débitos Diretos',
		'StandingOrder' => 'Débitos Diretos',
		'NewStandingOrder' => 'Novo Débito Direto',
		'StandingOrderToProcess' => 'To process',
		'StandingOrderProcessed' => 'Processed',
		'Withdrawals' => 'Levantamentos',
		'Withdrawal' => 'Levantamento',
		'WithdrawalsReceipts' => 'Ordens de Levantamento',
		'WithdrawalReceipt' => 'Ordem de Levantamento',
		'WithdrawalReceiptShort' => 'Ordem',
		'LastWithdrawalReceipts' => 'As %s últimas ordens de levantamento',
		'WithdrawedBills' => 'Faturas de Levantamentos',
		'WithdrawalsLines' => 'Linhas de Levantamento',
		'RequestStandingOrderToTreat' => 'Pedidos de Débitos Diretos a Tratar',
		'RequestStandingOrderTreated' => 'Pedidos de Débitos Diretos Processados',
		'CustomersStandingOrders' => 'Débitos Diretos de Clientes',
		'CustomerStandingOrder' => 'Débito Direto de Cliente',
		'NbOfInvoiceToWithdraw' => 'No de Faturas Pendentes de Levantamento',
		'NbOfInvoiceToWithdrawWithInfo' => 'Nb of invoice with withdraw request for customers having defined bank account information',
		'InvoiceWaitingWithdraw' => 'Faturas em Espera de Levantamento',
		'AmountToWithdraw' => 'Quantidade a Levantar',
		'WithdrawsRefused' => 'Débitos Diretos Rejeitados',
		'NoInvoiceToWithdraw' => 'Nenhuma fatura a cliente com modo de pagamento \'Débito Directo\' em espera. Ir ao separador \'Débito Directo\' na ficha da fatura para fazer um pedido.',
		'ResponsibleUser' => 'Usuário Responsável dos Débitos Diretos',
		'WithdrawalsSetup' => 'Configuração dos Débitos Diretos',
		'WithdrawStatistics' => 'Estatísticas de Débitos Diretos',
		'WithdrawRejectStatistics' => 'Estatísticas de Débitos Diretos Rejeitados',
		'LastWithdrawalReceipt' => 'Os %s últimos Débitos Diretos Recebidos',
		'MakeWithdrawRequest' => 'Realizar um Pedido de Débito Direto',
		'ThirdPartyBankCode' => 'Código Banco do Fornecedor',
		'ThirdPartyDeskCode' => 'Código da Escritório do Fornecedor',
		'NoInvoiceCouldBeWithdrawed' => 'Não há fatura de débito direto com sucesso. Verifique se a fatura da empresa tem um válido IBAN.',
		'ClassCredited' => 'Classificar Acreditados',
		'ClassCreditedConfirm' => 'Tem certeza que quer classificar este débito direto como realizado sobre a sua conta bancaria?',
		'TransData' => 'Date Transmission',
		'TransMetod' => 'Method Transmission',
		'Send' => 'Send',
		'Lines' => 'Lines',
		'StandingOrderReject' => 'Issue a reject',
		'InvoiceRefused' => 'Invoice refused',
		'WithdrawalRefused' => 'Withdrawal Refused',
		'WithdrawalRefusedConfirm' => 'Are you sure you want to enter a withdrawal rejection for society',
		'RefusedData' => 'Date of rejection',
		'RefusedReason' => 'Reason for rejection',
		'RefusedInvoicing' => 'Billing the rejection',
		'NoInvoiceRefused' => 'Do not charge the rejection',
		'InvoiceRefused' => 'Invoice refused',
		'Status' => 'Status',
		'StatusUnknown' => 'Unknown',
		'StatusWaiting' => 'Waiting',
		'StatusTrans' => 'Transmitted',
		'StatusCredited' => 'Credited',
		'StatusRefused' => 'Refused',
		'StatusMotif0' => 'Unspecified',
		'StatusMotif1' => 'Provision insuffisante',
		'StatusMotif2' => 'Tirage conteste',
		'StatusMotif3' => 'No Withdrawal order',
		'StatusMotif4' => 'Customer Order',
		'StatusMotif5' => 'RIB inexploitable',
		'StatusMotif6' => 'Account without balance',
		'StatusMotif7' => 'Judicial Decision',
		'StatusMotif8' => 'Other reason',
		'CreateAll' => 'Withdraw all',
		'CreateGuichet' => 'Only office',
		'CreateBanque' => 'Only bank',
		'OrderWaiting' => 'Waiting for treatment',
		'NotifyTransmision' => 'Withdrawal Transmission',
		'NotifyEmision' => 'Withdrawal Emission',
		'NotifyCredit' => 'Withdrawal Credit',
		'NumeroNationalEmetter' => 'National Transmitter Number',
		'PleaseSelectCustomerBankBANToWithdraw' => 'Select information about customer bank account to withdraw',
		'WithBankUsingRIB' => 'For bank accounts using RIB',
		'WithBankUsingBANBIC' => 'For bank accounts using IBAN/BIC/SWIFT',
		'BankToReceiveWithdraw' => 'Bank account to receive withdraws',
		'CreditDate' => 'Credit on',
		'WithdrawalFileNotCapable' => 'Unable to generate withdrawal receipt file for your country',
		'ShowWithdraw' => 'Show Withdraw',
		'IfInvoiceNeedOnWithdrawPaymentWontBeClosed' => 'However, if invoice has at least one withdrawal payment not yet processed, it won\'t be set as payed to allow to manage withdrawal before.',
		'DoStandingOrdersBeforePayments' => 'This tabs allows you to request for a standing order. Once it will be finished, you can type the payment to close the invoice.',
		////// Notifications
		'InfoCreditSubject' => 'Payment of standing order %s by the bank',
		'InfoCreditMessage' => 'The standing order %s has been paid by the bank<br>Data of payment: %s',
		'InfoTransSubject' => 'Transmission of standing order %s to bank',
		'InfoTransMessage' => 'The standing order %s has been transmited to bank by %s %s.<br><br>',
		'InfoTransData' => 'Amount: %s<br>Metode: %s<br>Date: %s',
		'InfoFoot' => 'This is an automated message sent by Dolibarr',
		'InfoRejectSubject' => 'Standing order refused',
		'InfoRejectMessage' => 'Hello,<br><br>the standig order of invoice %s related to the company %s, with an amount of %s has been refused by the bank.<br><br>--<br>%$',
		'ModeWarning' => 'Option for real mode was not set, we stop after this simulation'
);
?>