<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'TasksHistoryForThisContact' => 'Aktiviteter för denna kontakt',
		'LastProspectDoNotContact' => 'Kontakta inte',
		'LastProspectNeverContacted' => 'Aldrig kontaktat',
		'LastProspectToContact' => 'För att kontakta',
		'LastProspectContactInProcess' => 'Kontakta i processen',
		'LastProspectContactDone' => 'Kontakta gjort',
		'DateActionPlanned' => 'Datum planerade åtgärder för',
		'DateActionDone' => 'Datum insatser görs',
		'ActionAskedBy' => 'Åtgärd bad',
		'ActionAffectedTo' => 'Åtgärd påverkas',
		'ActionDoneBy' => 'Åtgärder som utförs av',
		'ActionUserAsk' => 'Registrerats av',
		'ErrorStatusCantBeZeroIfStarted' => 'Om fältet <b>&quot;Datum gjort&quot;</b> är fylld, är arbetet igång (eller färdiga), så fältet <b>&quot;Status&quot;</b> kan inte 0%%.',
		'ActionAC_TEL' => 'Telefonsamtal',
		'ActionAC_FAX' => 'Skicka fax',
		'ActionAC_PROP' => 'Skicka förslag via e-post',
		'ActionAC_EMAIL' => 'Skicka e-post',
		'ActionAC_RDV' => 'Möten',
		'ActionAC_FAC' => 'Skicka kundfaktura med post',
		'ActionAC_REL' => 'Skicka kundfaktura via post (påminnelse)',
		'ActionAC_CLO' => 'Stäng',
		'ActionAC_EMAILING' => 'Skicka massa e-post',
		'ActionAC_COM' => 'Skicka kundorder per post',
		'ActionAC_SUP_ORD' => 'Skicka leverantör beställning av e-post',
		'ActionAC_SUP_INV' => 'Skicka leverantörsfaktura med post',
		'Commercial' => 'Kommersiella',
		'CommercialArea' => 'Kommersiella område',
		'CommercialCard' => 'Kommersiella kort',
		'CustomerArea' => 'Kundarea',
		'Customer' => 'Kunden',
		'Customers' => 'Kunder',
		'Prospect' => 'Prospect',
		'Prospects' => 'Framtidsutsikter',
		'DeleteAction' => 'Ta bort en handling / uppgift',
		'NewAction' => 'Ny åtgärd / uppgift',
		'AddAction' => 'Lägg till åtgärd / uppgift',
		'AddAnAction' => 'Lägg till en handling / uppgift',
		'AddActionRendezVous' => 'Lägg till en Rendezvous uppgift',
		'Rendez-Vous' => 'Rendezvous',
		'ConfirmDeleteAction' => 'Är du säker på att du vill ta bort denna uppgift?',
		'CardAction' => 'Action-kort',
		'PercentDone' => 'Andel komplett',
		'ActionOnCompany' => 'Uppgift om företaget',
		'ActionOnContact' => 'Uppgift om kontakt',
		'TaskRDV' => 'Möten',
		'TaskRDVWith' => 'Möte med %s',
		'ShowTask' => 'Visa uppgift',
		'ShowAction' => 'Visa åtgärder',
		'ActionsReport' => 'Åtgärder rapport',
		'SalesRepresentative' => 'Säljare',
		'SalesRepresentatives' => 'Säljare',
		'SalesRepresentativeFollowUp' => 'Försäljare (uppföljning)',
		'SalesRepresentativeSignature' => 'Försäljare (underskrift)',
		'CommercialInterlocutor' => 'Kommersiella samtalspartner',
		'ErrorWrongCode' => 'Fel kod',
		'NoSalesRepresentativeAffected' => 'Ingen särskild säljare påverkas',
		'ShowCustomer' => 'Visa kund',
		'ShowProspect' => 'Visa utsikter',
		'ListOfProspects' => 'Lista över framtidsutsikter',
		'ListOfCustomers' => 'Lista över kunder',
		'LastDoneTasks' => 'Senaste %s slutförda uppgifter',
		'LastRecordedTasks' => 'Senaste registrerade uppgifter',
		'LastActionsToDo' => 'Senaste %s äldsta åtgärder som genomförts inte',
		'DoneAndToDoActionsFor' => 'Slutföras och att göra uppgifter för %s',
		'DoneAndToDoActions' => 'Slutföras och att göra uppgifter',
		'DoneActions' => 'Genomförda åtgärder',
		'DoneActionsFor' => 'Genomförda åtgärder för %s',
		'ToDoActions' => 'Ofullständig åtgärder',
		'ToDoActionsFor' => 'Ofullständiga åtgärder för %s',
		'SendPropalRef' => 'Skicka kommersiella förslag %s',
		'SendOrderRef' => 'Skicka beställningen %s',
		'StatusActionToDo' => 'För att göra',
		'StatusActionDone' => 'Komplett',
		'MyActionsAsked' => 'Åtgärderna jag har spelat in',
		'MyActionsToDo' => 'Åtgärder skall jag göra',
		'MyActionsDone' => 'Handlande påverkade mig',
		'StatusActionInProcess' => 'I processen',
		'StatusNotApplicable' => 'Ej tillämpligt',
		'ActionAC_SHIP' => 'Skicka Leverans med e-post',
		'ActionAC_OTH' => 'Andra',
		'StatusProsp' => 'Prospect status',
		'DraftPropals' => 'Utforma kommersiella förslag',
		'SearchPropal' => 'Sök en kommersiell förslag',
);
?>