<?php
/* Copyright (C) 2012-2013	Regis Houssin	<regis.houssin@capnetworks.com>
 * Copyright (C) 2012-2013	Herve Prot		<herve.prot@symeos.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$orders = array(
		'CHARSET' => 'UTF-8',
		'OrdersArea' => 'Kunder order område',
		'SuppliersOrdersArea' => 'Leverantörer order område',
		'OrderCard' => 'Beställ kort',
		'OrderId' => 'Order Id',
		'Order' => 'Beställ',
		'Orders' => 'Beställningar',
		'OrderLine' => 'Orderrad',
		'OrderLines' => 'Order lines',
		'OrderFollow' => 'Uppföljning',
		'OrderDate' => 'Beställ datum',
		'OrderToProcess' => 'Att kunna bearbeta',
		'NewOrder' => 'Ny ordning',
		'ToOrder' => 'Gör så',
		'MakeOrder' => 'Gör så',
		'SupplierOrder' => 'Leverantör för',
		'SuppliersOrders' => 'Leverantörens order',
		'SuppliersOrdersRunning' => 'Nuvarande leverantörens order',
		'CustomerOrder' => 'Kundorder',
		'CustomersOrders' => 'Kundens order',
		'CustomersOrdersRunning' => 'Nuvarande kundens order',
		'CustomersOrdersAndOrdersLines' => 'Kundorder och ordning: s linjer',
		'OrdersToValid' => 'Beställningar att validera',
		'OrdersToBill' => 'Order till faktura',
		'OrdersInProcess' => 'Orderingången i processen',
		'OrdersToProcess' => 'Order att behandla',
		'SuppliersOrdersToProcess' => 'Leverantörens order att behandla',
		'StatusOrderCanceledShort' => 'Annullerad',
		'StatusOrderDraftShort' => 'Förslag',
		'StatusOrderValidatedShort' => 'Validerad',
		'StatusOrderSentShort' => 'I processen',
		'StatusOrderSent' => 'Shipment in process',
		'StatusOrderOnProcessShort' => 'Den process',
		'StatusOrderProcessedShort' => 'Bearbetade',
		'StatusOrderToBillShort' => 'Till Bill',
		'StatusOrderToBill2Short' => 'To bill',
		'StatusOrderApprovedShort' => 'Godkänd',
		'StatusOrderRefusedShort' => 'Refused',
		'StatusOrderToProcessShort' => 'För att kunna behandla',
		'StatusOrderReceivedPartiallyShort' => 'Delvis fått',
		'StatusOrderReceivedAllShort' => 'Allt fick',
		'StatusOrderCanceled' => 'Annullerad',
		'StatusOrderDraft' => 'Utkast (måste valideras)',
		'StatusOrderNeedQuotes' => 'Draft (needs manual quotes)',
		'StatusOrderNew' => 'New order (needs to be validated)',
		'StatusOrderProcessing' => 'Processing',
		'StatusOrderValidated' => 'Validerad',
		'StatusOrderOnProcess' => 'Den process',
		'StatusOrderSending' => 'Sending',
		'StatusOrderClosed' => 'Closed (Shipped)',
		'StatusOrderToBill' => 'Till Bill',
		'StatusOrderToBill2' => 'To bill',
		'StatusOrderApproved' => 'Godkänd',
		'StatusOrderRefused' => 'Refused',
		'StatusOrderError' => 'Error',
		'StatusOrderReceivedPartially' => 'Delvis fått',
		'StatusOrderReceivedAll' => 'Allt fick',
		'ShippingExist' => 'En sändning föreligger',
		'DraftOrWaitingApproved' => 'Förslag eller godkänts ännu ej beställas',
		'DraftOrWaitingShipped' => 'Förslag eller godkännas ännu inte sändas',
		'MenuOrdersToBill' => 'Order till faktura',
		'MenuOrdersToBill2' => 'Orders to bill',
		'SearchOrder' => 'Sök ordning',
		'Sending' => 'Sända',
		'Sendings' => 'Sendings',
		'ShipProduct' => 'Ship produkt',
		'Discount' => 'Rabatt',
		'CreateOrder' => 'Skapa ordning',
		'RefuseOrder' => 'Vägra att',
		'ApproveOrder' => 'Acceptera att',
		'ValidateOrder' => 'Verifiera att',
		'UnvalidateOrder' => 'Unvalidate För',
		'DeleteOrder' => 'Radera ordning',
		'CancelOrder' => 'Avbryt för',
		'AddOrder' => 'Lägg ordning',
		'AddToMyOrders' => 'Lägg till i mitt order',
		'AddToOtherOrders' => 'Lägg till övriga beställningar',
		'ShowOrder' => 'Visa att',
		'NoOpenedOrders' => 'Ingen öppnade order',
		'NoOtherOpenedOrders' => 'Ingen annan öppnas order',
		'OtherOrders' => 'Övriga beställningar',
		'LastOrders' => 'Senaste %s order',
		'LastModifiedOrders' => 'Senast %s uppdaterad order',
		'LastClosedOrders' => 'Senaste %s stängd order',
		'AllOrders' => 'Alla order',
		'NbOfOrders' => 'Antal order',
		'OrdersStatistics' => 'Beställ statistik',
		'OrdersStatisticsSuppliers' => 'Leverantören för statistik',
		'NumberOfOrdersByMonth' => 'Antal beställningar per månad',
		'AmountOfOrdersByMonthHT' => 'orderingången per månad (efter skatt)',
		'ListOfOrders' => 'Lista över beställningar',
		'CloseOrder' => 'Stäng ordning',
		'ConfirmCloseOrder' => 'Är du säker på att du vill stänga denna beställning? När en order är stängd, kan den bara faktureras.',
		'ConfirmCloseOrderIfSending' => 'Är du säker på att du vill stänga denna beställning? Du måste stänga ett beslut först när alla sjöfarten är klar.',
		'ConfirmDeleteOrder' => 'Är du säker på att du vill ta bort denna order?',
		'ConfirmValidateOrder' => 'Är du säker på att du vill godkänna denna ordning under namnet <b>%s?</b>',
		'ConfirmUnvalidateOrder' => 'Är du säker på att du vill återställa ordningen <b>%s</b> att utarbeta status?',
		'ConfirmCancelOrder' => 'Är du säker på att du vill avbryta denna order?',
		'ConfirmMakeOrder' => 'Är du säker på att du vill bekräfta att du gjort detta beställning på <b>%s?</b>',
		'GenerateBill' => 'Skapa faktura',
		'ClassifyShipped' => 'Classify delivered',
		'ClassifyBilled' => 'Klassificera &quot;Fakturerade&quot;',
		'ComptaCard' => 'Bokföring kort',
		'DraftOrders' => 'Förslag till beslut',
		'RelatedOrders' => 'Relaterade order',
		'OnProcessOrders' => 'I processen order',
		'RefOrder' => 'Ref. För',
		'RefCustomerOrder' => 'Ref. kundorder',
		'CustomerOrder' => 'Kundorder',
		'RefCustomerOrderShort' => 'Ref. cust. För',
		'SendOrderByMail' => 'Skicka beställningen per post',
		'ActionsOnOrder' => 'Åtgärder för att',
		'NoArticleOfTypeProduct' => 'Ingen artikel av typen &quot;produkt&quot; så ingen shippable artikel för denna beställning',
		'OrderMode' => 'Beställ metod',
		'AuthorRequest' => 'Begär författare',
		'UseCustomerContactAsOrderRecipientIfExist' => 'Använd kundkontakt adress om definieras i stället för tredje parts adress för mottagarens adress',
		'RunningOrders' => 'Beställningar på processen',
		'UserWithApproveOrderGrant' => 'Användare som beviljats med &quot;godkänna order&quot;-behörighet.',
		'PaymentOrderRef' => 'Betalning av att %s',
		'CloneOrder' => 'Klon för',
		'ConfirmCloneOrder' => 'Är du säker på att du vill klona denna beställning <b>%s?</b>',
		'DispatchSupplierOrder' => 'Ta emot leverantör för %s',
		'DateDeliveryPlanned' => 'Date de livraison prévue',
		'SetDemandReason' => 'Définir l\'origine de la commande',
		////////// Types de contacts //////////
		'TypeContact_commande_internal_SALESREPFOLL' => 'Representanten följa upp kundorder',
		'TypeContact_commande_internal_SHIPPING' => 'Representanten uppföljning sjöfart',
		'TypeContact_commande_external_BILLING' => 'Kundfaktura kontakt',
		'TypeContact_commande_external_SHIPPING' => 'Kunden Frakt Kontakta',
		'TypeContact_commande_external_CUSTOMER' => 'Kundkontakt uppföljning för',
		'TypeContact_order_supplier_internal_SALESREPFOLL' => 'Representanten uppföljning leverantör för',
		'TypeContact_order_supplier_internal_SHIPPING' => 'Representanten uppföljning sjöfart',
		'TypeContact_order_supplier_external_BILLING' => 'Leverantörsfaktura kontakt',
		'TypeContact_order_supplier_external_SHIPPING' => 'Leverantör Frakt Kontakta',
		'TypeContact_order_supplier_external_CUSTOMER' => 'Leverantör kontakt uppföljning för',
		'Error_COMMANDE_SUPPLIER_ADDON_NotDefined' => 'Konstant COMMANDE_SUPPLIER_ADDON inte definierat',
		'Error_COMMANDE_ADDON_NotDefined' => 'Konstant COMMANDE_ADDON inte definierat',
		'Error_FailedToLoad_COMMANDE_SUPPLIER_ADDON_File' => 'Kunde inte ladda modulen fil %s',
		'Error_FailedToLoad_COMMANDE_ADDON_File' => 'Kunde inte ladda modulen fil %s',
		'Error_OrderNotChecked' => 'No orders to invoice selected',
		// Sources
		'OrderSource0' => 'Kommersiella förslag',
		'OrderSource1' => 'Internet',
		'OrderSource2' => 'Mail kampanj',
		'OrderSource3' => 'Telefon compaign',
		'OrderSource4' => 'Fax kampanj',
		'OrderSource5' => 'Kommersiella',
		'OrderSource6' => 'Store',
		'QtyOrdered' => 'Antal beställda',
		'AddDeliveryCostLine' => 'Lägg till en line-kostnad som visar vikten av beslutet',
		// Documents models
		'PDFEinsteinDescription' => 'En fullständig för-modellen (logo. ..)',
		'PDFEdisonDescription' => 'En enkel ordning modell',
		// Orders modes
		'OrderByMail' => 'Post',
		'OrderByFax' => 'Faxa',
		'OrderByEMail' => 'EMail',
		'OrderByWWW' => 'Nätet',
		'OrderByPhone' => 'Telefonen',
		'CreateInvoiceForThisCustomer' => 'Bill orders',
		'NoOrdersToInvoice' => 'No orders billable',
		'CloseProcessedOrdersAutomatically' => 'Classify "Processed" all selected orders.',
		'MenuOrdersToBill2' => 'Orders to bill',
		'LinkedInvoices' => 'Linked invoices',
		'LinkedProposals' => 'Linked proposals',
		'ShippingHT' => 'Shipping cost'
);
?>