<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$compta = array(
		'CHARSET' => 'UTF-8',
		'Accountancy' => 'Счетоводство',
		'AccountancyCard' => 'Счетоводството карта',
		'Treasury' => 'Съкровищница',
		'MenuFinancial' => 'Финансов',
		'TaxModuleSetupToModifyRules' => 'Отиди на <a href="%s">модул за настройка</a> да променя правилата за изчисляване',
		'OptionMode' => 'Възможност за счетоводството',
		'OptionModeTrue' => 'Вариант доходите, Разходи',
		'OptionModeVirtual' => 'Вариант Вземания Дълговете',
		'OptionModeTrueDesc' => 'В този контекст, на оборота се изчислява плащания (дата на плащанията). Валидността на цифрите е гарантирана само ако счетоводството се разглежда през входа / изхода на сметките чрез фактури.',
		'OptionModeVirtualDesc' => 'В този контекст, на оборота се изчислява върху фактури (датата на утвърждаване). Когато тези фактури се дължи, независимо дали са платени или не, те са изброени в оборота изход.',
		'FeatureIsSupportedInInOutModeOnly' => 'Функцията е достъпна само в счетоводството режим кредити ЗАЕМИ (Виж модулна конфигурация за счетоводството)',
		'VATReportBuildWithOptionDefinedInModule' => 'Сумите, показани тук, са изчислени въз основа на правилата, определени от данъчните модул за настройка.',
		'Param' => 'Структура',
		'RemainingAmountPayment' => 'Сума за плащане остава:',
		'AmountToBeCharged' => 'Общо сумата за плащане:',
		'AccountsGeneral' => 'Сметки',
		'Account' => 'Сметка',
		'Accounts' => 'Сметки',
		'Accountparent' => 'Сметка Родител',
		'Accountsparent' => 'Сметки майка',
		'BillsForSuppliers' => 'Законопроекти за доставчиците',
		'Income' => 'Доход',
		'Outcome' => 'Разход',
		'ReportInOut' => 'Приходи / разходи',
		'ReportTurnover' => 'Оборот',
		'PaymentsNotLinkedToInvoice' => 'Плащания, които не са свързани с всяка фактура, така че не свързани с която и да е трета страна',
		'PaymentsNotLinkedToUser' => 'Плащанията, които не са свързани с който и да е потребител',
		'Profit' => 'Печалба',
		'Balance' => 'Баланс',
		'Debit' => 'Дебит',
		'Credit' => 'Кредит',
		'Withdrawal' => 'Оттегляне',
		'Withdrawals' => 'Тегления',
		'AmountHTVATRealReceived' => 'Net събраните',
		'AmountHTVATRealPaid' => 'Net плаща',
		'VATToPay' => 'ДДС продава',
		'VATReceived' => 'ДДС, получавани',
		'VATToCollect' => 'ДДС покупки',
		'VATSummary' => 'ДДС баланс',
		'LT2SummaryES' => 'IRPF баланс',
		'VATPaid' => 'ДДС, платен',
		'LT2PaidES' => 'IRPF платен',
		'LT2CustomerES' => 'IRPF продажби',
		'LT2SupplierES' => 'IRPF покупки',
		'VATCollected' => 'Събраният ДДС',
		'ToPay' => 'За да платите',
		'ToGet' => 'За да се върнете',
		'TaxAndDividendsArea' => 'Данъци, вноски за социално и дивиденти площ',
		'SocialContribution' => 'Социален принос',
		'SocialContributions' => 'Социалноосигурителни вноски',
		'MenuTaxAndDividends' => 'Данъци и дивиденти',
		'MenuSocialContributions' => 'Социалноосигурителни вноски',
		'MenuNewSocialContribution' => 'Нов принос',
		'NewSocialContribution' => 'Нова социална принос',
		'ContributionsToPay' => 'Вноски за плащане',
		'AccountancyTreasuryArea' => 'Счетоводство / Министерството на финансите',
		'AccountancySetup' => 'Счетоводството настройка',
		'NewPayment' => 'Нов плащане',
		'Payments' => 'Плащания',
		'PaymentCustomerInvoice' => 'Плащане на клиенти фактура',
		'PaymentSupplierInvoice' => 'Плащане доставчик фактура',
		'PaymentSocialContribution' => 'Осигурителната вноска за плащане',
		'PaymentVat' => 'Плащането на ДДС',
		'ListPayment' => 'Списък на плащанията',
		'ListOfPayments' => 'Списък на плащанията',
		'ListOfCustomerPayments' => 'Списък на клиентски плащания',
		'ListOfSupplierPayments' => 'Списък на доставчика плащания',
		'DatePayment' => 'Дата на плащане',
		'NewVATPayment' => 'Нова плащането на ДДС',
		'newLT2PaymentES' => 'Нова IRPF плащане',
		'LT2PaymentES' => 'IRPF плащане',
		'LT2PaymentsES' => 'IRPF Плащания',
		'VATPayment' => 'Плащането на ДДС',
		'VATPayments' => 'Плащанията по ДДС',
		'SocialContributionsPayments' => 'Социални плащания вноски',
		'ShowVatPayment' => 'Покажи плащане на ДДС',
		'TotalToPay' => 'Всичко за плащане',
		'TotalVATReceived' => 'Общо ДДС',
		'CustomerAccountancyCode' => 'Код на клиенти счетоводство',
		'SupplierAccountancyCode' => 'Код доставчик счетоводство',
		'AlreadyPaid' => 'Вече е платена',
		'AccountNumberShort' => 'Номер на сметка',
		'AccountNumber' => 'Номер на сметка',
		'NewAccount' => 'Нов акаунт',
		'SalesTurnover' => 'Продажби оборот',
		'ByThirdParties' => 'Bu трети страни',
		'ByUserAuthorOfInvoice' => 'С фактура автор',
		'AccountancyExport' => 'Счетоводството износ',
		'ErrorWrongAccountancyCodeForCompany' => 'Bad код отчетност за клиента %s',
		'SuppliersProductsSellSalesTurnover' => 'Генерираният оборот от продажбите на продуктите на доставчика.',
		'CheckReceipt' => 'Проверете депозит',
		'CheckReceiptShort' => 'Проверете депозит',
		'NewCheckReceipt' => 'Нов отстъпка',
		'NewCheckDeposit' => 'Нова проверка депозит',
		'NewCheckDepositOn' => 'Създаване на разписка за депозит по сметка: %s',
		'NoWaitingChecks' => 'Няма проверки за депозит.',
		'DateChequeReceived' => 'Проверете датата рецепция',
		'NbOfCheques' => 'Nb на проверките',
		'PaySocialContribution' => 'Заплащане на осигурителната вноска',
		'ConfirmPaySocialContribution' => 'Сигурен ли сте, че искате да класифицира този осигурителната вноска като платен?',
		'DeleteSocialContribution' => 'Изтриване на осигурителната вноска',
		'ConfirmDeleteSocialContribution' => 'Сигурен ли сте, че искате да изтриете тази осигурителната вноска?',
		'ExportDataset_tax_1' => 'Социални вноски и плащания',
		'AnnualSummaryDueDebtMode' => 'Баланс на приходи и разходи, годишно обобщение, каза режим <b>%sClaims Debt%sS ангажимент счетоводство.</b>',
		'AnnualSummaryInputOutputMode' => 'Баланс на приходи и разходи, годишно обобщение, каза режим <b>%sIncomes Expense%sS отчитане на касова основа.</b>',
		'AnnualByCompaniesDueDebtMode' => 'Баланс на приходи и разходи, подробно от трети страни, каза режим <b>%sClaims Debt%sS ангажимент счетоводство.</b>',
		'AnnualByCompaniesInputOutputMode' => 'Баланс на приходи и разходи, подробно от трети страни, каза режим <b>%sIncomes Expense%sS отчитане на касова основа.</b>',
		'SeeReportInInputOutputMode' => 'Виж доклада <b>%sIncomes-Expense%sS</b> каза <b>за отчитане на касова основа</b> за изчисляване на действителните плащания',
		'SeeReportInDueDebtMode' => 'Виж доклада <b>%sClaims-Debt%sS ангажимент счетоводство</b> за изчисляване на издадените фактури',
		'RulesResultDue' => '- Показани Сумите са с включени всички такси <br> - Тя включва неплатените фактури, разходи и ДДС, независимо дали са платени или не. <br> - Тя се основава на датата на утвърждаване на фактури и ДДС и на датата на падежа за разходи.',
		'RulesResultInOut' => '- Показани Сумите са с включени всички такси <br> - Тя включва реалните плащания по фактури, разходи и ДДС. <br> - Тя се основава на датите на изплащане на фактури, разходи за ДДС ANF. <br>',
		'RulesCADue' => '- Тя включва дължимите на клиента фактури, независимо дали са платени или не. <br> - Тя се основава на датата на валидиране тези фактури. <br>',
		'RulesCAIn' => '- То включва всички ефективни плащания на фактурите, получени от клиенти. <br> - Тя се основава на датата на плащане на тези фактури <br>',
		'DepositsAreNotIncluded' => '- Депозит фактури не са включени',
		'DepositsAreIncluded' => '- Депозит фактури са включени',
		'LT2ReportByCustomersInInputOutputModeES' => 'Доклад от трета страна IRPF',
		'VATReportByCustomersInInputOutputMode' => 'Доклад от клиента ДДС, събрани и изплатени (ДДС получаване)',
		'VATReportByCustomersInDueDebtMode' => 'Доклад от клиента ДДС, събрани и изплатени (ставка на ДДС)',
		'VATReportByQuartersInInputOutputMode' => 'Доклад по ставки на ДДС, събрани и изплатени (ДДС получаване)',
		'VATReportByQuartersInDueDebtMode' => 'Доклад по ставки на ДДС, събрани и изплатени (ставка на ДДС)',
		'SeeVATReportInInputOutputMode' => 'Виж да докладва <b>%sVAT encasement%s</b> за изчислението на стандартната',
		'SeeVATReportInDueDebtMode' => 'Виж доклада <b>%sVAT за flow%s</b> за изчисление, с опция върху потока',
		'RulesVATInServices' => '- По отношение на услугите, докладът включва разпоредби действително са получили или издават въз основа на датата на плащане на ДДС. <br> - Материални активи, включва ДДС фактури въз основа на датата на фактурата.',
		'RulesVATInProducts' => '- Материални активи, включва ДДС фактури въз основа на датата на фактурата.',
		'RulesVATDueServices' => '- Услуги, в доклада се включва ДДС фактури дължи платена или не, въз основа на датата на фактурата.',
		'RulesVATDueProducts' => '- Материални активи, включва ДДС фактури, въз основа на датата на фактурата.',
		'OptionVatInfoModuleComptabilite' => 'Забележка: За материални активи, трябва да използват датата на доставка, за да бъде по-справедлива.',
		'PercentOfInvoice' => '% / Фактура',
		'NotUsedForGoods' => 'Не се използва върху стоки',
		'ProposalStats' => 'Статистика за представяне на предложения',
		'OrderStats' => 'Статистика за поръчки',
		'InvoiceStats' => 'Статистически данни за сметки',
		'Dispatch' => 'Диспечерско',
		'Dispatched' => 'Изпратени',
		'ToDispatch' => 'За изпращане',
		'ThirdPartyMustBeEditAsCustomer' => 'От трета страна трябва да бъдат определени като клиент',
		'SellsJournal' => 'Продажби вестник',
		'PurchasesJournal' => 'Покупките вестник',
		'DescSellsJournal' => 'Продажби вестник',
		'DescPurchasesJournal' => 'Покупките вестник',
		'InvoiceRef' => 'Фактура с реф.',
		'CodeNotDef' => 'Не е определена',
		'AddRemind' => 'Изпращането наличната сума',
		'RemainToDivide' => 'Останете изпращането:',
		'WarningDepositsNotIncluded' => 'Депозити фактури не са включени в тази версия с този модул за счетоводството.',
		'DatePaymentTermCantBeLowerThanObjectDate' => 'Payment term date can\'t be lower than object date.',
		'Pcg_version' => 'PCG версия',
		'Pcg_type' => 'PCG тип',
		'Pcg_subtype' => 'PCG подтип',
		'Withdrawl' => 'Prélèvement',
		'Withdrawls' => 'Prélèvements',
		'ToGetBack' => 'A récupérer',
		'Journaux' => 'Journaux',
		'Piece' => 'Piece compta',
		'JournalNum' => 'Journal',
		'COMPTA_JOURNAL_SELL' => 'Numéro comptable du Journal des Achats',
		'COMPTA_JOURNAL_BUY' => 'Numéro comptable du Journal des Ventes',
		'COMPTA_PRODUCT_BUY_ACCOUNT' => 'Compte comptable par défaut pour produits achetés (si non défini sur fiche produit)',
		'COMPTA_PRODUCT_SOLD_ACCOUNT' => 'Compte comptable par défaut pour produits vendus (si non défini sur fiche produit)',
		'COMPTA_SERVICE_BUY_ACCOUNT' => 'Compte comptable par défaut pour services achetés (si non défini sur fiche service)',
		'COMPTA_SERVICE_SOLD_ACCOUNT' => 'Compte comptable par défaut pour services vendus (si non défini sur fiche service)',
		'COMPTA_VAT_ACCOUNT' => 'Compte comptable par défaut pour TVA (si non défini dans dictionnaire "Taux de TVA")',
		'COMPTA_ACCOUNT_CUSTOMER' => 'Compte comptable client par défaut (si non défini sur fiche tiers)',
		'COMPTA_ACCOUNT_SUPPLIER' => 'Compte comptable fournisseur par défaut (si non défini sur fiche tiers)',
);
?>