<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'Потребителска карта',
		'ContactCard' => 'Свържи се карта',
		'GroupCard' => 'Група карта',
		'NoContactCard' => 'Няма карта сред контакти',
		'Permission' => 'Разрешение',
		'Permissions' => 'Разрешения',
		'EditPassword' => 'Edit парола',
		'SendNewPassword' => 'Регенерира и изпращане на парола',
		'ReinitPassword' => 'Повторно генериране на парола',
		'PasswordChangedTo' => 'Парола изменя така: %s',
		'SubjectNewPassword' => 'Вашата нова парола за Speedealing',
		'AvailableRights' => 'Наличните разрешения',
		'OwnedRights' => 'Собствени разрешения',
		'GroupRights' => 'Група разрешения',
		'UserRights' => 'Потребителските права',
		'UserGUISetup' => 'Настройка Потребителят дисплей',
		'DisableUser' => 'Правя неспособен',
		'DisableAUser' => 'Изключване на потребителя',
		'DeleteUser' => 'Изтриване',
		'DeleteAUser' => 'Изтриване на потребител',
		'DisableGroup' => 'Правя неспособен',
		'DisableAGroup' => 'Изключване група',
		'EnableAUser' => 'Разрешаване на потребителя',
		'EnableAGroup' => 'Разрешаване на група',
		'DeleteGroup' => 'Изтриване',
		'DeleteAGroup' => 'Изтриване на група',
		'ConfirmDisableUser' => 'Сигурен ли сте, че искате да изключите потребителски <b>%s?</b>',
		'ConfirmDisableGroup' => 'Сигурен ли сте, че искате да деактивирате група <b>%s?</b>',
		'ConfirmDeleteUser' => 'Сигурен ли сте, че искате да изтриете потребителски <b>%s?</b>',
		'ConfirmDeleteGroup' => 'Сигурен ли сте, че искате да изтриете група <b>%s?</b>',
		'ConfirmEnableUser' => 'Сигурен ли сте, че искате да разрешите потребителски <b>%s?</b>',
		'ConfirmEnableGroup' => 'Сигурен ли сте, че искате да разрешите група <b>%s?</b>',
		'ConfirmReinitPassword' => 'Сигурен ли сте, че искате да създадете нова парола за потребителски <b>%s?</b>',
		'ConfirmSendNewPassword' => 'Сигурен ли сте, че искате да генерираме и изпратим нова парола за потребителски <b>%s?</b>',
		'NewUser' => 'Нов потребител',
		'CreateUser' => 'Създаване на потребител',
		'SearchAGroup' => 'Търсене на група',
		'SearchAUser' => 'Търсене на потребителя',
		'LoginNotDefined' => 'Вход не е дефинирано.',
		'NameNotDefined' => 'Името не е дефинирана.',
		'ListOfUsers' => 'Списък на потребителите',
		'Administrator' => 'Администратор',
		'SuperAdministrator' => 'Супер Администратор',
		'SuperAdministratorDesc' => 'Глобално администратор',
		'AdministratorDesc' => 'Администратор лице',
		'DefaultRights' => 'Разрешенията по подразбиране',
		'DefaultRightsDesc' => 'Определете тук разрешенията по <u>подразбиране,</u> които автоматично са предоставени на <u>новосъздадения</u> потребител (на потребителското карта, за да се промени разрешение на съществуващ потребител).',
		'SpeedealingUsers' => 'Speedealing users',
		'LastName' => 'Име',
		'FirstName' => 'Собствено име',
		'ListOfGroups' => 'Списък на групите',
		'NewGroup' => 'Нова група',
		'CreateGroup' => 'Създай група',
		'RemoveFromGroup' => 'Премахване от групата',
		'PasswordChangedAndSentTo' => 'Парола променили и изпраща <b>%s.</b>',
		'PasswordChangeRequestSent' => 'Заявка за промяна на парола за <b>%s,</b> изпратени до <b>%s.</b>',
		'MenuUsersAndGroups' => 'Потребители и групи',
		'LastGroupsCreated' => 'Последно %s създават групи',
		'LastUsersCreated' => 'Последно потребители %s създаден',
		'ShowGroup' => 'Показване на групата',
		'ShowUser' => 'Покажи потребителя',
		'NonAffectedUsers' => 'За засегнатите потребители',
		'UserModified' => 'Потребителят е променена успешно',
		'GroupModified' => 'Група променена успешно',
		'PhotoFile' => 'Снимка файл',
		'UserWithSpeedealingAccess' => 'User with Speedealing access',
		'ListOfUsersInGroup' => 'Списък на потребителите в тази група',
		'ListOfGroupsForUser' => 'Списък на групи за този потребител',
		'UsersToAdd' => 'На потребителите да добавят към тази група',
		'GroupsToAdd' => 'Групи, за да добавите този потребител',
		'NoLogin' => 'Без данни за вход',
		'LinkToCompanyContact' => 'Линк към трета страна / контакт',
		'LinkedToSpeedealingMember' => 'Link to member',
		'LinkedToSpeedealingUser' => 'Link to Speedealing user',
		'LinkedToSpeedealingThirdParty' => 'Link to Speedealing third party',
		'CreateSpeedealingLogin' => 'Create a user',
		'CreateSpeedealingThirdParty' => 'Create a third party',
		'LoginAccountDisable' => 'Профилът е деактивиран, поставете нов, влезте с потребителско име и парола, за да я активирате.',
		'LoginAccountDisableInSpeedealing' => 'Account disabled in Speedealing.',
		'LoginAccountDisableInLdap' => 'Профилът е деактивиран в домейна.',
		'UsePersonalValue' => 'Използвайте лична стойност',
		'GuiLanguage' => 'Език на интерфейса',
		'InternalUser' => 'Вътрешна потребителска',
		'MyInformations' => 'Моите данни',
		'ExportDataset_user_1' => 'Speedealing потребителите и свойства',
		'DomainUser' => '%s потребителски домейн',
		'Reactivate' => 'Възстановете',
		'CreateInternalUserDesc' => 'Тази форма ви позволява да създавам потребител на вътрешни за вашата компания / фондация. Да създавам външен потребител (клиент, доставчик, ...), използвайте бутона &quot;Създаване на Speedealing потребителя от трета страна картата за контакт.',
		'InternalExternalDesc' => '<b>Вътрешен</b> потребител е потребител, който е част от вашата компания / фондация. <br> <b>Външен</b> потребител е клиент, доставчик или друга. <br><br> И в двата случая, разрешения определя права върху Speedealing, външен потребител може да има друг мениджър меню от вътрешния потребител (Виж Начало - Setup - Display)',
		'PermissionInheritedFromAGroup' => 'Регулация, защото е наследен от един от групата на потребителя.',
		'Inherited' => 'Наследен',
		'UserWillBeInternalUser' => 'Създаден потребителят ще бъде вътрешен потребител (тъй като не са свързани с определена трета страна)',
		'UserWillBeExternalUser' => 'Създаден потребителят ще бъде външен потребител (защото свързани с дадена трета страна)',
		'IdPhoneCaller' => 'Caller ID телефон',
		'UserLogged' => 'Потребителят %s вход',
		'UserLogoff' => 'Потребителски %s изход',
		'NewUserCreated' => 'Потребителски %s създаден',
		'NewUserPassword' => 'Промяна на паролата за %s',
		'EventUserModified' => 'Потребителски %s промяна',
		'UserDisabled' => 'Потребителски %s инвалиди',
		'UserEnabled' => 'Потребителски %s активира',
		'UserDeleted' => 'Потребителски %s отстранени',
		'NewGroupCreated' => 'Група %s създаден',
		'GroupModified' => 'Група променена успешно',
		'GroupDeleted' => 'Група %s отстранени',
		'ConfirmCreateContact' => 'Сигурен ли сте, че искате да създадете акаунт Speedealing за този контакт?',
		'ConfirmCreateLogin' => 'Сигурен ли сте, че искате да създадете акаунт Speedealing за този потребител?',
		'ConfirmCreateThirdParty' => 'Сигурен ли сте, че искате да създадете трета страна за този потребител?',
		'LoginToCreate' => 'Влез за да създаде',
		'NameToCreate' => 'Име на трета страна, за да създадете',
		'YourRole' => 'Вашите роли',
		'YourQuotaOfUsersIsReached' => 'Квотата на активните потребители е достигнато!',
		'NbOfUsers' => 'Nb на потребителите',
		'DontDowngradeSuperAdmin' => 'Само superadmin да понижи категорията на superadmin',
		'NewDatabase' => 'Nouvelle base de données',
		'CreateDatabase' => 'Créer la base de données',
		'ListOfDatabases' => 'Liste des bases de données',
		'ListOfUsersInDatabase' => 'Liste des utilisateurs liés à la base de données',
		'ListOfRolesInDatabase' => 'Liste des groupes liés à la base de données',
		'DeleteADatabase' => 'Suppression d\'une database',
		'ConfirmDatabase' => 'Êtes-vous sûr de vouloir supprimer la base de données <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Groupes non affectés à la base de données',
		'NonAffectedUsersDatabase' => 'Utilisateurs non affectés à la base de données',
		'Collaborators' => 'Collaborateurs',
		'Profiles' => 'Profils collaborateurs'
);
?>