<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Kategorija',
		'Categories' => 'Kategorije',
		'Rubrique' => 'Rubrika',
		'Rubriques' => 'Rubrike',
		'categories' => 'kategorije',
		'TheCategorie' => 'Kategorija',
		'NoCategoryYet' => 'Ni kreirana nobena kategorija te vrste',
		'In' => 'V',
		'AddIn' => 'Dodaj v',
		'modify' => 'spremeni',
		'Classify' => 'Razvrsti',
		'CategoriesArea' => 'Področje kategorij',
		'ProductsCategoriesArea' => 'Področje kategorij proizvodov/storitev',
		'SuppliersCategoriesArea' => 'Področje kategorij dobaviteljev',
		'CustomersCategoriesArea' => 'Področje kategorij kupcev',
		'ThirdPartyCategoriesArea' => 'Področje kategorij partnerjev',
		'MembersCategoriesArea' => 'Področje kategorij članov',
		'MainCats' => 'Glavne kategorije',
		'SubCats' => 'Podkategorije',
		'CatStatistics' => 'Statistika',
		'CatList' => 'Seznam kategorij',
		'AllCats' => 'Vse kategorije',
		'ViewCat' => 'Glej kategorijo',
		'NewCat' => 'Dodaj kategorijo',
		'NewCategory' => 'Nova kategorija',
		'ModifCat' => 'Spremeni kategorijo',
		'CatCreated' => 'Kreirana kategorija',
		'CreateCat' => 'Kreiraj kategorijo',
		'CreateThisCat' => 'Kreiraj to kategorijo',
		'ValidateFields' => 'Potrdi polja',
		'NoSubCat' => 'Ni podkategorije.',
		'SubCatOf' => 'Podkategorija',
		'FoundCats' => 'Najdi kategorije',
		'FoundCatsForName' => 'Najdena kategorija za ime :',
		'FoundSubCatsIn' => 'Najdena podkategorija v kategoriji',
		'ErrSameCatSelected' => 'Večkrat ste izbrali enako kategorijo',
		'ErrForgotCat' => 'Pozabili ste izbrati kategorijo',
		'ErrForgotField' => 'Pozabili ste izbrati polje',
		'ErrCatAlreadyExists' => 'To ime je že uporabljeno',
		'AddProductToCat' => 'Želite dodati ta proizvod v kategorijo?',
		'ImpossibleAddCat' => 'Ni možno dodati kategorije',
		'ImpossibleAssociateCategory' => 'Ni možno vezati kategorije na',
		'WasAddedSuccessfully' => '<b>%s</b> je bil uspešno dodan.',
		'ObjectAlreadyLinkedToCategory' => 'Element je že povezan na to kategorijo.',
		'CategorySuccessfullyCreated' => 'Ta kategorija %s je bila uspešno dodana.',
		'ProductIsInCategories' => 'Proizvod/storitev pripada naslednji kategoriji',
		'SupplierIsInCategories' => 'Partner pripada naslednjim kategorijam dobaviteljev',
		'CompanyIsInCustomersCategories' => 'Ta partner pripada naslednjim kategorijam kupcev/možnih strank',
		'CompanyIsInSuppliersCategories' => 'Ta partner pripada naslednjim kategorijam dobaviteljev',
		'MemberIsInCategories' => 'Ta član pripada naslednjim kategorijam',
		'ProductHasNoCategory' => 'Ta proizvod/storitev ni vključen v nobeno kategorijo',
		'SupplierHasNoCategory' => 'Ta dobavitelj ni vključen v nobeno kategorijo',
		'CompanyHasNoCategory' => 'To podjetje ni vključeno v nobeno kategorijo',
		'MemberHasNoCategory' => 'Ta član ni v nobeni kategoriji',
		'ClassifyInCategory' => 'Razvrsti v kategorijo',
		'NoneCategory' => 'Nobena',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Kategorija s to referenco že obstaja',
		'ReturnInProduct' => 'Nazaj na kartico proizvodov/storitev',
		'ReturnInSupplier' => 'Nazaj na kartico dobaviteljev',
		'ReturnInCompany' => 'Nazaj na kartico kupcev/možnih strank',
		'ContentsVisibleByAll' => 'Vsebina bo vidna vsem',
		'ContentsVisibleByAllShort' => 'Vsebina vidna vsem',
		'ContentsNotVisibleByAllShort' => 'Vsebina ni vidna vsem',
		'CategoriesTree' => 'Drevesna struktura kategorij',
		'DeleteCategory' => 'Izbriši kategorijo',
		'ConfirmDeleteCategory' => 'Ali zares želite izbrisati to kategorijo?',
		'RemoveFromCategory' => 'Odstranite povezavo s kategorijo',
		'RemoveFromCategoryConfirm' => 'Ali zares želite odstraniti povezavo med transakcijo in kategorijo?',
		'NoCategoriesDefined' => 'Ni izbrana kategorija',
		'SuppliersCategoryShort' => 'Kategorija dobaviteljev',
		'CustomersCategoryShort' => 'Kategorija kupcev',
		'ProductsCategoryShort' => 'Kategorija proizvodov',
		'MembersCategoryShort' => 'Kategorija članov',
		'SuppliersCategoriesShort' => 'Kategorije dobaviteljev',
		'CustomersCategoriesShort' => 'Kategorije kupcev',
		'CustomersProspectsCategoriesShort' => 'Kategorije kupcev/možnih strank',
		'ProductsCategoriesShort' => 'Kategorije proizvodov',
		'MembersCategoriesShort' => 'Kategorije članov',
		'ThisCategoryHasNoProduct' => 'Ta kategorija ne vsebuje nobenega proizvoda.',
		'ThisCategoryHasNoSupplier' => 'Ta kategorija ne vsebuje nobenega proizvoda.',
		'ThisCategoryHasNoCustomer' => 'Ta kategorija ne vsebuje nobenega kupca.',
		'ThisCategoryHasNoMember' => 'Ta kategorija ne vsebuje nobenega člana.',
		'AssignedToCustomer' => 'Dodeljeno kupcu',
		'AssignedToTheCustomer' => 'Dodeljeno kupcu',
		'InternalCategory' => 'Interna kategorija',
		'CategoryContents' => 'Vsebina kategorije',
		'CategId' => 'ID kategorije',
		'CatSupList' => 'Seznam kategorij dobaviteljev',
		'CatCusList' => 'Seznam kategorij kupcev/možnih strank',
		'CatProdList' => 'Seznam kategorij proizvodov',
		'CatMemberList' => 'Seznam kategorij članov',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>