<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Komerciala',
		'CommercialArea' => 'Komercialno področje',
		'CommercialCard' => 'Komercialna kartica',
		'CustomerArea' => 'Področje kupcev',
		'Customer' => 'Kupec',
		'Customers' => 'Kupci',
		'Prospect' => 'Možna stranka',
		'Prospects' => 'Možne stranke',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Brisanje aktivnosti/naloge',
		'NewAction' => 'Nova aktivnost/naloga',
		'AddAction' => 'Dodaj aktivnost/nalogo',
		'AddAnAction' => 'Dodajanje aktivnosti/naloge',
		'AddActionRendezVous' => 'Dodaj nalogo/srečanje',
		'Rendez-Vous' => 'Srečanje',
		'ConfirmDeleteAction' => 'Ali zares želite izbrisati to nalogo?',
		'CardAction' => 'Kartica aktivnosti',
		'PercentDone' => 'Procent dokončanosti',
		'ActionOnCompany' => 'Naloga o podjetju',
		'ActionOnContact' => 'Naloga o kontaktu',
		'TaskRDV' => 'Sestanki',
		'TaskRDVWith' => 'Sestanek z %s',
		'ShowTask' => 'Prikaži naloge',
		'ShowAction' => 'Prikaži aktivnosti',
		'ActionsReport' => 'Poročilo o aktivnostih',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Prodajni predstavnik',
		'SalesRepresentatives' => 'Prodajni predstavniki',
		'SalesRepresentativeFollowUp' => 'Prodajni predstavnik (nadaljevanje)',
		'SalesRepresentativeSignature' => 'Prodajni predstavnik (podpisi)',
		'CommercialInterlocutor' => 'Komercialni zastopnik',
		'ErrorWrongCode' => 'Napačna koda',
		'NoSalesRepresentativeAffected' => 'Se ne tiče določenega prodajnega predstavnika',
		'ShowCustomer' => 'Prikaži kupca',
		'ShowProspect' => 'Prikaži možno stranko',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Seznam možnih strank',
		'ListOfCustomers' => 'Seznam kupcev',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'Zadnjih %s zaključenih nalog',
		'LastRecordedTasks' => 'Zadnja zabeležena naloga',
		'LastActionsToDo' => 'Zadnjih %s najstarejših nedokončanih aktivnosti',
		'DoneAndToDoActionsFor' => 'Dokončane in odprte naloge za %s',
		'DoneAndToDoActions' => 'Dokončane in odprte naloge',
		'DoneActions' => 'Dokončane aktivnosti',
		'DoneActionsFor' => 'Dokončane aktivnosti za %s',
		'ToDoActions' => 'Nedokončane aktivnosti',
		'ToDoActionsFor' => 'Nedokončane aktivnosti za %s',
		'SendPropalRef' => 'Poslana komercialna ponudba %s',
		'SendOrderRef' => 'Poslano naročilo %s',
		'StatusNotApplicable' => 'Ni veljaven',
		'StatusActionToDo' => 'Odprto',
		'StatusActionDone' => 'Dokončano',
		'StatusActionInProcess' => 'V teku',
		'MyActionsAsked' => 'Aktivnosti, ki sem jih zabeležil',
		'MyActionsToDo' => 'Aktivnosti, ki jih moram narediti',
		'MyActionsDone' => 'Aktivnosti, ki se me tičejo',
		'TasksHistoryForThisContact' => 'Aktivnosti v zvezi s tem kontaktom',
		'LastProspectDoNotContact' => 'Ne kontaktirati',
		'LastProspectNeverContacted' => 'Nikoli kontaktiran',
		'LastProspectToContact' => 'Kontaktirati',
		'LastProspectContactInProcess' => 'Kontakt v teku',
		'LastProspectContactDone' => 'Kontakt izveden',
		'DateActionPlanned' => 'Datum planirane aktivnosti za',
		'DateActionDone' => 'Datum izvedene aktivnosti',
		'ActionAskedBy' => 'Aktivnost zahteval',
		'ActionAffectedTo' => 'Aktivnost, ki se tiče',
		'ActionDoneBy' => 'Aktivnost izvedel',
		'ActionUserAsk' => 'Zabeležil',
		'ErrorStatusCantBeZeroIfStarted' => 'Če je polje \'<b>Date done</b>\' izpolnjeno, je aktivnost začeta (ali končana), zato polje \'<b>Status</b>\' ne more biti 0%%.',
		'ActionAC_TEL' => 'Telefonski klic',
		'ActionAC_FAX' => 'Poslati faks',
		'ActionAC_PROP' => 'Poslati ponudbo',
		'ActionAC_EMAIL' => 'Poslati e-mail',
		'ActionAC_RDV' => 'Sestanek',
		'ActionAC_FAC' => 'Poslati račun kupcu po pošti',
		'ActionAC_REL' => 'Poslati račun kupcu po pošti (opomin)',
		'ActionAC_CLO' => 'Zapreti',
		'ActionAC_EMAILING' => 'Poslati skupinski e-mail',
		'ActionAC_COM' => 'Poslati naročilo kupca po pošti',
		'ActionAC_SHIP' => 'Pošlji pošiljko po pošti',
		'ActionAC_SUP_ORD' => 'Poslati naročilo dobavitelju po pošti',
		'ActionAC_SUP_INV' => 'Poslati račun dobavitelja po pošti',
		'ActionAC_OTH' => 'Ostalo',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Status možne stranke',
		'DraftPropals' => 'Osnutek komercialne ponudbe',
		'SearchPropal' => 'Iskanje komercialne ponudbe'
);
?>