<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$propal = array(
		'CHARSET' => 'UTF-8',
		'Proposals' => 'Komercialne ponudbe',
		'Proposal' => 'Komercialna ponudba',
		'ProposalShort' => 'Ponudba',
		'ProposalsDraft' => 'Osnutek komercialnih ponudb',
		'ProposalDraft' => 'Osnutek komercialne ponudbe',
		'ProposalsOpened' => 'Odprte komercialne ponudbe',
		'Prop' => 'Komercialne ponudbe',
		'CommercialProposal' => 'Komercialna ponudba',
		'CommercialProposals' => 'Komercialne ponudbe',
		'ProposalCard' => 'Kartica ponudbe',
		'NewProp' => 'Nova komercialna ponudba',
		'NewProposal' => 'Nova komercialna ponudba',
		'NewPropal' => 'Nova ponudba',
		'Prospect' => 'Možna stranka',
		'ProspectList' => 'Seznam možnih strank',
		'DeleteProp' => 'Izbriši komercialno ponudbo',
		'ValidateProp' => 'Potrdi komercialno ponudbo',
		'AddProp' => 'Dodaj ponudbo',
		'ConfirmDeleteProp' => 'Ali zares želite izbrisati to komercialno ponudbo ?',
		'ConfirmValidateProp' => 'Ali zares želite potrditi to komercialno ponudbo?',
		'LastPropals' => 'Zadnjih %s ponudb',
		'LastClosedProposals' => 'Zadnjih %s zaključenih ponudb',
		'LastModifiedProposals' => 'Zadnjih %s spremenjenih ponudb',
		'AllPropals' => 'Vse ponudbe',
		'LastProposals' => 'Zadnje ponudbe',
		'SearchAProposal' => 'Išči ponudbo',
		'ProposalsStatistics' => 'Statistika komercialnih ponudb',
		'NumberOfProposalsByMonth' => 'Število po mesecih',
		'AmountOfProposalsByMonthHT' => 'Znesek po mesecih(brez DDV)',
		'NbOfProposals' => 'Število komercialnih ponudb',
		'ShowPropal' => 'Prikaži ponudbo',
		'PropalsDraft' => 'Osnutki',
		'PropalsOpened' => 'Odprte',
		'PropalsNotBilled' => 'Zaključene, ne fakturirane',
		'PropalStatusDraft' => 'Osnutek (potrebno potrditi)',
		'PropalStatusValidated' => 'Potrjena (ponudba je odprta)',
		'PropalStatusOpened' => 'Odprta (ponudba je odprta)',
		'PropalStatusClosed' => 'Zaprta',
		'PropalStatusSigned' => 'Podpisana (potrebno fakturirati)',
		'PropalStatusNotSigned' => 'Nepodpisana (zaprta)',
		'PropalStatusBilled' => 'Fakturirana',
		'PropalStatusDraftShort' => 'Osnutek',
		'PropalStatusValidatedShort' => 'Potrjena',
		'PropalStatusOpenedShort' => 'Odprta',
		'PropalStatusClosedShort' => 'Zaprta',
		'PropalStatusSignedShort' => 'Podpisana',
		'PropalStatusNotSignedShort' => 'Nepodpisana',
		'PropalStatusBilledShort' => 'Fakturirana',
		'PropalsToClose' => 'Komercialne ponudbe, ki jih je potrebno zapreti',
		'PropalsToBill' => 'Podpisane komercialne ponudbe, ki jih je potrebno fakturirati',
		'ListOfProposals' => 'Seznam komercialnih ponudb',
		'ActionsOnPropal' => 'Aktivnosti v zvezi s ponudbo',
		'NoOpenedPropals' => 'Komercialne ponudbe, ki niso odprte',
		'NoOtherOpenedPropals' => 'Ni drugih odprtih komercialnih ponudb',
		'RefProposal' => 'Referenca komercialne ponudbe',
		'SendPropalByMail' => 'Pošlji komercialno ponudbo po pošti',
		'FileNotUploaded' => 'Datoteka ni bila prenesena',
		'FileUploaded' => 'Datoteka je bila uspešno prenesena',
		'AssociatedDocuments' => 'Dokumenti, povezani s ponudbo:',
		'ErrorCantOpenDir' => 'Ne morem odpreti mape',
		'DatePropal' => 'Datum ponudbe',
		'DateEndPropal' => 'Datum veljavnosti ponudbe',
		'DateEndPropalShort' => 'Datum veljavnosti',
		'ValidityDuration' => 'Trajanje veljavnosti',
		'CloseAs' => 'Zaključi s statusom',
		'ClassifyBilled' => 'Klasificiraj kot fakturirano',
		'BuildBill' => 'Izdelaj fakturo',
		'ErrorPropalNotFound' => 'Ponudbe %s ne najdem',
		'Estimate' => 'Ocena:',
		'EstimateShort' => 'Ocena',
		'OtherPropals' => 'Ostale ponudbe',
		'CopyPropalFrom' => 'Kreiraj komercialno ponudbo s kopiranjem obstoječe ponudbe',
		'CreateEmptyPropal' => 'Kreiraj prazno komercialno ponudbo ali izberi s seznama prizvodov/storitev',
		'DefaultProposalDurationValidity' => 'Privzeto trajanje veljavnosti komercialne ponudbe (v dneh)',
		'UseCustomerContactAsPropalRecipientIfExist' => 'Kot naslov prejemnika ponudbe uporabi naslov kontakta pri kupcu, če je na voljo, namesto naslova partnerja',
		'ClonePropal' => 'Kloniraj komercialno ponudbo',
		'ConfirmClonePropal' => 'Ali zares želite klonirati to komercialno ponudbo <b>%s</b> ?',
		'ConfirmReOpenProp' => 'Ali ste prepričani, da želite odpreti nazaj poslovne <b>%s</b> predlog?',
		'ProposalsAndProposalsLines' => 'Komercialna ponudba in vrstice',
		'ProposalLine' => 'Vrstica ponudbe',
		'ProposalLines' => 'Proposal lines',
		'AvailabilityPeriod' => 'Dobavni rok',
		'SetAvailability' => 'Nastavi dobavni rok',
		'AfterOrder' => 'od naročila',
		////////// Availability //////////
		'AvailabilityTypeAV_NOW' => 'Takoj',
		'AvailabilityTypeAV_1W' => '1 teden',
		'AvailabilityTypeAV_2W' => '2 tedna',
		'AvailabilityTypeAV_3W' => '3 tedne',
		'AvailabilityTypeAV_1M' => '1 mesec',
		////////// Types de contacts //////////
		'TypeContact_propal_internal_SALESREPFOLL' => 'Predstavnik za sledenje ponudbe',
		'TypeContact_propal_external_BILLING' => 'Kontakt za račun pri kupcu',
		'TypeContact_propal_external_CUSTOMER' => 'Kontakt pri kupcu za sledenje ponudbe',
		// Document models
		'DocModelAzurDescription' => 'Vzorec kompletne ponudbe (logo...)',
		'DocModelJauneDescription' => 'Vzorec ponudbe Jaune',
		'Numbershort' => 'N°',
		'LinkdedOrders' => 'Linked orders'
);
?>