<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'Kartica uporabnika',
		'ContactCard' => 'Kartica kontakta',
		'GroupCard' => 'Kartica skupine',
		'NoContactCard' => 'Ni kartice med kontakti',
		'Permission' => 'Dovoljenje',
		'Permissions' => 'Dovoljenja',
		'EditPassword' => 'Spremeni geslo',
		'SendNewPassword' => 'Regeneriraj in pošlji geslo',
		'ReinitPassword' => 'Regeneriraj geslo',
		'PasswordChangedTo' => 'Geslo spremenjeno v: %s',
		'SubjectNewPassword' => 'Vaše novo geslo za Speedealing',
		'AvailableRights' => 'Dovoljenja, ki so na voljo',
		'OwnedRights' => 'Lastna dovoljenja',
		'GroupRights' => 'Dovoljenja skupine',
		'UserRights' => 'Dovoljenja uporabnika',
		'UserGUISetup' => 'Nastavitev zaslona uporabnika',
		'DisableUser' => 'Onemogoči',
		'DisableAUser' => 'Onemogoči',
		'DeleteUser' => 'Izbriši',
		'DeleteAUser' => 'Izbriši uporabnika',
		'DisableGroup' => 'Onemogoči',
		'DisableAGroup' => 'Onemogoči skupino',
		'EnableAUser' => 'Omogoči uporabnika',
		'EnableAGroup' => 'Omogoči skupino',
		'DeleteGroup' => 'Izbriši',
		'DeleteAGroup' => 'Izbriši skupino',
		'ConfirmDisableUser' => 'Ali zares želite onemogočiti uporabnika <b>%s</b> ?',
		'ConfirmDisableGroup' => 'Ali zares želite onemogočiti skupino <b>%s</b> ?',
		'ConfirmDeleteUser' => 'Ali zares želite izbrisati uporabnika <b>%s</b> ?',
		'ConfirmDeleteGroup' => 'Ali zares želite izbrisati skupino <b>%s</b> ?',
		'ConfirmEnableUser' => 'Ali zares želite omogočiti uporabnika <b>%s</b> ?',
		'ConfirmEnableGroup' => 'Ali zares želite omogočiti skupino <b>%s</b> ?',
		'ConfirmReinitPassword' => 'Ali zares želite generirati novo geslo za uporabnika <b>%s</b> ?',
		'ConfirmSendNewPassword' => 'Ali zares želite generirati in poslati novo geslo za uporabnika <b>%s</b> ?',
		'NewUser' => 'Nov uporabnik',
		'CreateUser' => 'Kreiraj uporabnika',
		'SearchAGroup' => 'Išči skupino',
		'SearchAUser' => 'Išči uporabnika',
		'LoginNotDefined' => 'Uporabniško ime ni določeno.',
		'NameNotDefined' => 'Ime ni določeno.',
		'ListOfUsers' => 'Seznam uporabnikov',
		'Administrator' => 'Administrator',
		'SuperAdministrator' => 'Super Administrator',
		'SuperAdministratorDesc' => 'Administrator z vsemi pravicami',
		'AdministratorDesc' => 'Entiteta administratorja',
		'DefaultRights' => 'Privzeta dovoljenja',
		'DefaultRightsDesc' => 'Tukaj določite <u>privzeta</u> dovoljenja, ki se avtomatsko dodelijo <u>novo kreiranemu</u> uporabniku (Dovoljenja obstoječega uporabnika spremenite preko kartice uporabnika).',
		'SpeedealingUsers' => 'Speedealing users',
		'LastName' => 'Priimek',
		'FirstName' => 'Ime',
		'ListOfGroups' => 'Seznam skupin',
		'NewGroup' => 'Nova skupina',
		'CreateGroup' => 'Kreiraj skupino',
		'RemoveFromGroup' => 'Odstrani iz skupine',
		'PasswordChangedAndSentTo' => 'Geslo spremenjeno in poslano <b>%s</b>.',
		'PasswordChangeRequestSent' => 'Zahtevek za spremembo gesla <b>%s</b> poslan <b>%s</b>.',
		'MenuUsersAndGroups' => 'Uporabniki & Skupine',
		'LastGroupsCreated' => 'Zadnjih %s kreiranih skupin',
		'LastUsersCreated' => 'Zadnjih %s kreiranih uporabnikov',
		'ShowGroup' => 'Prikaži skupino',
		'ShowUser' => 'Prikaži uporabnika',
		'NonAffectedUsers' => 'Nevključeni uporabniki',
		'UserModified' => 'Uporabnik uspešno spremenjen',
		'GroupModified' => 'Skupina %s je spremenjena',
		'PhotoFile' => 'Datoteka s fotografijo',
		'UserWithSpeedealingAccess' => 'User with Speedealing access',
		'ListOfUsersInGroup' => 'Seznam uporabnikov v tej skupini',
		'ListOfGroupsForUser' => 'Seznam skupin tega uporabnika',
		'UsersToAdd' => 'Uporabniki, ki jih je potrebno dodati v to skupino',
		'GroupsToAdd' => 'Skupine, v katere je potrebno dodati tega uporabnika',
		'NoLogin' => 'Ni uporabniškega imena',
		'LinkToCompanyContact' => 'Povezava na partnerja / kontakt',
		'LinkedToSpeedealingMember' => 'Link to member',
		'LinkedToSpeedealingUser' => 'Link to Speedealing user',
		'LinkedToSpeedealingThirdParty' => 'Link to Speedealing third party',
		'CreateSpeedealingLogin' => 'Create a user',
		'CreateSpeedealingThirdParty' => 'Create a third party',
		'LoginAccountDisable' => 'Račun onemogočen, vnesi novo ime uporabnika za aktivacijo.',
		'LoginAccountDisableInSpeedealing' => 'Account disabled in Speedealing.',
		'LoginAccountDisableInLdap' => 'Račun onemogočen v domeni.',
		'UsePersonalValue' => 'Uporabi osebne podatke',
		'GuiLanguage' => 'Jezik vmesnika',
		'InternalUser' => 'Interni uporabnik',
		'MyInformations' => 'Moji podatki',
		'ExportDataset_user_1' => 'Uporabniki Speedealingja in značilnosti',
		'DomainUser' => 'Uporabnik domene %s',
		'Reactivate' => 'Ponovno aktiviraj',
		'CreateInternalUserDesc' => 'Ta obrazec omogoča kreiranje internega uporabnika v vašem podjetju/ustanovi. Za kreiranje zunanjega uporabnika (kupec, dobavitelj, ...), uporabite gumb \'Kreiraj Speedealing uporabnika\' na kartici kontakta pri partnerju.',
		'InternalExternalDesc' => '<b>Interni</b> uporabnik je uporabnik, ki je zaposlen v vašem podjetju/ustanovi.<br> <b>Zunanji</b> uporabnik je kupec, dobavitelj, ali kdo drug.<br><br>V obeh primerih se lahko definirajo pravice za uporabo Speedealingja, zunanji uporabnik ima lahko drugačno menijsko strukturo, kot interni uporabnik (Glejte Domov - Nastavitev - Prikaz)',
		'PermissionInheritedFromAGroup' => 'Dovoljenje dodeljeno zaradi podedovanja od druge uporabniške skupine.',
		'Inherited' => 'Podedovan',
		'UserWillBeInternalUser' => 'Kreiran uporabnik bo interni uporabnik (ker ni povezan z določenim partnerjem)',
		'UserWillBeExternalUser' => 'Kreiran uporabnik bo zunanji uporabnik (ker je povezan z določenim partnerjem)',
		'IdPhoneCaller' => 'ID klicatelja po telefonu',
		'UserLogged' => 'Uporabnik %s je prijavljen',
		'UserLogoff' => 'Uporabnik %s je odjavljen',
		'NewUserCreated' => 'Uporabik %s je kreiran',
		'NewUserPassword' => 'Sprememba gesla za %s',
		'EventUserModified' => 'Uporabnik %s je spremenjen',
		'UserDisabled' => 'Uporabnik %s je onemogočen',
		'UserEnabled' => 'Uporabnik %s je aktiviran',
		'UserDeleted' => 'Uporabnik %s je odstranjen',
		'NewGroupCreated' => 'Skupina %s je kreirana',
		'GroupModified' => 'Skupina %s je spremenjena',
		'GroupDeleted' => 'Skupina %s je odstranjena',
		'ConfirmCreateContact' => 'Ali zares želite kreirati Speedealing dostop za ta kontakt ?',
		'ConfirmCreateLogin' => 'Ali zares želite kreirati Speedealing dostop za tega člana ?',
		'ConfirmCreateThirdParty' => 'Ali zares želite kreirati partnerja za tega člana ?',
		'LoginToCreate' => 'Kreiranje uporabniškega imena',
		'NameToCreate' => 'Kreiranje imena partnerja',
		'YourRole' => 'Vaše vloge',
		'YourQuotaOfUsersIsReached' => 'Dosežena je vaša kvota aktivnih uporabnikov !',
		'NbOfUsers' => 'Število uporabnikov',
		'DontDowngradeSuperAdmin' => 'Samo superadmin lahko degradira samo superadmin',
		'NewDatabase' => 'Nouvelle base de données',
		'CreateDatabase' => 'Créer la base de données',
		'ListOfDatabases' => 'Liste des bases de données',
		'ListOfUsersInDatabase' => 'Liste des utilisateurs liés à la base de données',
		'ListOfRolesInDatabase' => 'Liste des groupes liés à la base de données',
		'DeleteADatabase' => 'Suppression d\'une database',
		'ConfirmDatabase' => 'Êtes-vous sûr de vouloir supprimer la base de données <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Groupes non affectés à la base de données',
		'NonAffectedUsersDatabase' => 'Utilisateurs non affectés à la base de données',
		'Collaborators' => 'Collaborateurs',
		'Profiles' => 'Profils collaborateurs'
);
?>