<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$banks = array(
		'CHARSET' => 'UTF-8',
		'Bank' => 'Banca',
		'Banks' => 'Banci',
		'MenuBankCash' => 'Banca / Casa',
		'MenuSetupBank' => 'Configurare Banca / Cash ',
		'BankName' => 'Nume bancă',
		'FinancialAccount' => 'Cont',
		'FinancialAccounts' => 'Conturi',
		'BankAccount' => 'Cont bancar',
		'BankAccounts' => 'Conturi bancare',
		'AccountRef' => 'Contul financiare ref',
		'AccountLabel' => 'Contul financiare etichetă',
		'CashAccount' => 'Cont numerar',
		'CashAccounts' => 'Conturi numerar',
		'MainAccount' => 'Cont principal',
		'CurrentAccount' => 'Cont curent',
		'CurrentAccounts' => 'Conturi curente',
		'SavingAccount' => 'Cont  depozite',
		'SavingAccounts' => 'Conturi depozite',
		'ErrorBankLabelAlreadyExists' => 'Eticheta  contului financiar există deja',
		'BankBalance' => 'Soldul',
		'BalanceMinimalAllowed' => 'Sold minim autorizat',
		'BalanceMinimalDesired' => 'Sold minim dorit',
		'InitialBankBalance' => 'Sold iniţial',
		'EndBankBalance' => 'Sold final',
		'CurrentBalance' => 'Sold curent',
		'FutureBalance' => 'Sold viitor',
		'ShowAllTimeBalance' => 'Arată soldul  de la început',
		'Reconciliation' => 'Reconciliere',
		'RIB' => 'Număr de cont',
		'IBAN' => 'Cod IBAN ',
		'BIC' => 'Cod BIC / SWIFT ',
		'StandingOrders' => 'Ordine de plată',
		'StandingOrder' => 'Odin de plată',
		'Withdrawals' => 'Retrageri',
		'Withdrawal' => 'Retragerea',
		'AccountStatement' => 'Extras de cont',
		'AccountStatementShort' => 'Extras',
		'AccountStatements' => 'Extrase',
		'LastAccountStatements' => 'Ultimele extrase bancare',
		'Rapprochement' => 'Reconciliate',
		'IOMonthlyReporting' => 'Raport lunar',
		'BankAccountDomiciliation' => 'Adresă Cont',
		'BankAccountCountry' => 'Ţara Cont',
		'BankAccountOwner' => 'Titular Cont',
		'BankAccountOwnerAddress' => 'Adresă titular Cont',
		'RIBControlError' => 'Verificarea integritătii a eşuat. Acest lucru înseamnă pentru acest  cont nu sunt  sau sunt greşit  completate (verifică ţară, număr cont şi IBAN).',
		'CreateAccount' => 'Crearea cont',
		'NewAccount' => 'Cont nou',
		'NewBankAccount' => 'Nou cont bancar',
		'NewFinancialAccount' => 'Cont nou financiar',
		'MenuNewFinancialAccount' => 'Cont nou financiar',
		'NewCurrentAccount' => 'Cont  nou curent',
		'NewSavingAccount' => 'Cont nou depozit',
		'NewCashAccount' => 'Cont nou numerar',
		'EditFinancialAccount' => 'Editare cont',
		'AccountSetup' => 'Configurare conturi financiare',
		'SearchBankMovement' => 'Căutare inregistrări extrase bancare',
		'Debts' => 'Datorii',
		'LabelBankCashAccount' => 'Eticheta Banca sau Casa',
		'AccountType' => 'Tip de cont',
		'BankType0' => 'Cont depozit / plasament',
		'BankType1' => 'Cont curent sau card',
		'BankType2' => 'Cont Casa / numerar',
		'IfBankAccount' => 'Dacă contul bancar',
		'AccountsArea' => 'Zona Conturi ',
		'AccountCard' => 'Fişa Cont',
		'DeleteAccount' => 'Ştergere cont',
		'ConfirmDeleteAccount' => 'Sunteţi sigur că doriţi să ştergeţi acest cont?',
		'Account' => 'Cont',
		'ByCategories' => 'Pe categorii',
		'ByRubriques' => 'Pe rubrici',
		'BankTransactionByCategories' => 'Tranzacţii bancare pe rubrici',
		'BankTransactionForCategory' => 'Tranzacţii bancare pentru rubrica <b> %s</b>',
		'RemoveFromRubrique' => 'Eliminaţi link-ul cu rubrica',
		'RemoveFromRubriqueConfirm' => 'Sunteţi sigur că doriţi să ştergeţi legătura dintre tranzacţie şi rubrică ?',
		'ListBankTransactions' => 'Listă tranzacţii bancare',
		'IdTransaction' => 'ID-ul tranzacţiei',
		'BankTransactions' => 'Tranzacţii bancare',
		'SearchTransaction' => 'Caută  tranzacţie',
		'ListTransactions' => 'Lista tranzacţiilor',
		'ListTransactionsByCategory' => 'Lista tranzacţiilor/ rubrică',
		'TransactionsToConciliate' => 'Tranzacţii de conciliat',
		'Conciliable' => 'Conciliabile',
		'Conciliate' => 'Conciliază',
		'Conciliation' => 'Conciliere',
		'ConciliationForAccount' => 'Conciliază pe acest cont',
		'IncludeClosedAccount' => 'Includeţi închis conturile',
		'OnlyOpenedAccount' => 'Numai conturile deschise ',
		'AccountToCredit' => 'Cont de creditat',
		'AccountToDebit' => 'Cont de debitat',
		'DisableConciliation' => 'Dezactivaţi funcţia  conciliere  pentru acest cont',
		'ConciliationDisabled' => 'Funcţia conciliere dezactivată',
		'StatusAccountOpened' => 'Deschis',
		'StatusAccountClosed' => 'Închis',
		'AccountIdShort' => 'Număr',
		'EditBankRecord' => 'Editare tranzacţie',
		'LineRecord' => 'Tranzacţie',
		'AddBankRecord' => 'Adaugă tranzacţie',
		'AddBankRecordLong' => 'Adaugă tranzacţie manual fără factură',
		'ConciliatedBy' => 'Conciliat de',
		'DateConciliating' => 'Data Conciliere',
		'BankLineConciliated' => 'Tranzacţie conciliată',
		'CustomerInvoicePayment' => 'Plată Clienţi',
		'SupplierInvoicePayment' => 'Plată furnizori',
		'WithdrawalPayment' => 'Retragerea numerar',
		'SocialContributionPayment' => 'Plată contribuţie socială',
		'FinancialAccountJournal' => 'Jurnal cont de trezorerie',
		'BankTransfer' => 'Virament bancar',
		'BankTransfers' => 'Viramente bancare',
		'TransferDesc' => 'Transferul de la un cont la altul, Speedealing va scrie două înregistrări (un debit în cont sursă şi o ţintă de credit în cont, de la aceeaşi sumă. Aceeaşi etichetă şi data vor fi utilizate pentru această tranzacţie)',
		'TransferFrom' => 'De la',
		'TransferTo' => 'La',
		'TransferFromToDone' => 'Un transfer din <b> %s </b>către<b> %s</b>  de <b>%s</b> %s  a fost inregistrat.',
		'CheckTransmitter' => 'Emitent',
		'ValidateCheckReceipt' => 'Validaţi acest bordeou de cecuri remise?',
		'ConfirmValidateCheckReceipt' => 'Sunteţi sigur că doriţi să valideze această verificare la primire, nici o schimbare va fi posibilă o dată acest lucru este făcut?',
		'DeleteCheckReceipt' => 'Ştergeţi acest borderou de cecuri?',
		'ConfirmDeleteCheckReceipt' => 'Sunteţi sigur că doriţi să ştergeţi acest verifica primirea?',
		'BankChecks' => 'Cecuri',
		'BankChecksToReceipt' => 'Cecuri de depus',
		'ShowCheckReceipt' => 'Arată borderou de cecuri remise',
		'NumberOfCheques' => 'Nr cecuri',
		'DeleteTransaction' => 'Şterge tranzacţia',
		'ConfirmDeleteTransaction' => 'Sunteţi sigur că doriţi să ştergeţi această tranzacţie?',
		'ThisWillAlsoDeleteBankRecord' => 'Aceasta va şterge, de asemenea, tranyactiile bancare generate ',
		'BankMovements' => 'Transferuri',
		'CashBudget' => 'Buget trezorerie',
		'PlannedTransactions' => 'Tranzacţii planificate ',
		'Graph' => 'Grafice',
		'ExportDataset_banque_1' => 'Tranzacţii bancare şi extrase de cont',
		'TransactionOnTheOtherAccount' => 'Tranzacţie pe alt cont',
		'TransactionWithOtherAccount' => 'Cont  transfer',
		'PaymentNumberUpdateSucceeded' => 'Număr plată actualizat cu succes',
		'PaymentNumberUpdateFailed' => 'Numărul de plată nu a putut fi actualizat',
		'PaymentDateUpdateSucceeded' => 'Dată plată actualizată cu succes',
		'PaymentDateUpdateFailed' => 'Dată plată nu a putut fi actualizată',
		'Transactions' => 'Tranzacţii',
		'BankTransactionLine' => 'Tranzacţie bancară',
		'AllAccounts' => 'Toate conturile  banca / casa',
		'BackToAccount' => 'Inapoi la cont',
		'ShowAllAccounts' => 'Arata pentru toate conturile',
		'FutureTransaction' => 'Tranzacţie în  viitor. In nici un caz de conciliat.',
		'SelectChequeTransactionAndGenerate' => 'Selectaţi / filtraţi cecurile pentru a le include în borderourile cecurilor  remise  şi faceţi clic "Creare".',
		'InputReceiptNumber' => 'Alegeţi extrasul de cont referitor la conciliere. Utilizati o  valoare numerică sortabilă (de ex, YYYYMM)',
		'EventualyAddCategory' => 'Eventual, specificaţi o categorie înn care clasaţi inregistrarea.',
		'ToConciliate' => 'De  conciliat?',
		'ThenCheckLinesAndConciliate' => 'Apoi, bifaţi liniile prezente pe extras si click '
);
?>