<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$boxes = array(
		'CHARSET' => 'UTF-8',
		'BoxLastRssInfos' => 'Rss informaţii',
		'BoxLastProducts' => 'Ultimele produse / servicii',
		'BoxLastProductsInContract' => 'Ultima contractate de produse / servicii',
		'BoxLastSupplierBills' => 'Ultima furnizorului facturi',
		'BoxLastCustomerBills' => 'Ultimul client a facturilor',
		'BoxLastProposals' => 'Ultima comerciale propuneri',
		'BoxLastProspects' => 'Ultima perspectivele',
		'BoxLastCustomers' => 'Ultima clienţi',
		'BoxLastCustomerOrders' => 'Ultima client ordinelor',
		'BoxLastSuppliers' => 'Ultima furnizori',
		'BoxLastBooks' => 'Ultimele cărţi',
		'BoxLastActions' => 'Ultima acţiuni',
		'BoxCurrentAccounts' => 'Conturile curente echilibru',
		'BoxSalesTurnover' => 'Vanzari cifra de afaceri',
		'BoxTitleLastBooks' => 'Ultima %s înregistrate cărţi',
		'BoxTitleNbOfCustomers' => 'Nombre de client',
		'BoxTitleLastRssInfos' => 'Ultimele noutăţi de la %s %s',
		'BoxTitleLastProducts' => 'Ultima %s modificate produse / servicii',
		'BoxTitleLastCustomerOrders' => 'Ultima modificare %s client ordinelor',
		'BoxTitleLastSuppliers' => 'Ultima %s înregistrate de furnizori',
		'BoxTitleLastCustomers' => 'Ultima %s înregistrate de clienţi',
		'BoxTitleLastCustomersOrProspects' => 'Ultima %s înregistrate de clienţi sau de perspectivele',
		'BoxTitleLastPropals' => 'Ultima %s înregistrate propuneri',
		'BoxTitleLastCustomerBills' => 'Ultima %s clientului facturi',
		'BoxTitleLastSupplierBills' => 'Ultima %s furnizorului facturi',
		'BoxTitleLastProspects' => 'Ultima %s înregistrate perspectivele',
		'BoxTitleCurrentAccounts' => 'Contul curent al soldurilor',
		'BoxTitleSalesTurnover' => 'Vanzari cifra de afaceri',
		'BoxMyLastBookmarks' => 'Ultima mea %s marcaje',
		'FailedToRefreshDataInfoNotUpToDate' => 'Nu a reuşit să reîmprospătaţi flux RSS. Ultima reuşită a reîmprospăta data: %s',
		'NoRecordedBookmarks' => 'No bookmarks defined. Click <a href=Nu marcaje definite. Faceţi clic <a href="%s">aici</a> pentru a adăuga marcaje.',
		'NoRecordedCustomers' => 'Nu înregistrate de clienţi',
		'BoxTitleLastActionsToDo' => 'Ultima %s acţiunile de a face',
		'NoActionsToDo' => 'Nr actiuni pentru a face',
		'NoRecordedOrders' => 'Nu înregistrate clientului ordinelor',
		'NoRecordedProposals' => 'Nu înregistrate propuneri',
		'NoRecordedInvoices' => 'Nu înregistrate clientului facturi',
		'NoRecordedSupplierInvoices' => 'Nu înregistrate furnizorului facturi',
		'LastRefreshDate' => 'Ultima data de reîmprospătare',
		'NoRecordedProducts' => 'Nu înregistrate produse / servicii',
		'NoRecordedProspects' => 'Nu înregistrate perspectivele',
		'NoContractedProducts' => 'Nu produse / servicii contractate',
		'BoxOldestUnpaidCustomerBills' => 'Primele facturi neachitate clientului',
		'BoxOldestUnpaidSupplierBills' => 'Primele facturi neachitate furnizorului',
		'BoxTotalUnpaidCustomerBills' => 'Total facturi neachitate clientului',
		'BoxTotalUnpaidSuppliersBills' => 'Total facturi neachitate furnizorului',
		'BoxTitleOldestUnpaidCustomerBills' => 'Cele mai vechi %s neachitate clientului facturi',
		'BoxTitleOldestUnpaidSupplierBills' => 'Cele mai vechi %s neachitate furnizorului, facturi',
		'BoxTitleTotalUnpaidCustomerBills' => 'Neachitate clientului facturi',
		'BoxTitleTotalUnpaidSuppliersBills' => 'Furnizorului, facturi neachitate',
		'NoUnpaidCustomerBills' => 'Nu neachitate clientului facturi',
		'NoUnpaidSupplierBills' => 'Nu facturi neachitate furnizorului',
		'BoxLastContracts' => 'Ultimele contracte',
		'BoxTitleLastProductsInContract' => 'Ultima %s produse / servicii intr-un contract',
		'BoxTitleLastContracts' => 'Ultimele contracte %s',
		'NoModifiedSupplierBills' => 'Nici un furnizor nu a înregistrat facturile',
		'NoRecordedContracts' => 'Nr contracte înregistrate',
		'BoxLastContracts' => 'Siste kontrakter',
		'LastRefreshDate' => 'Siste oppdatering dato',
		'BoxTitleLastContracts' => 'Siste %s kontrakter',
		'NoModifiedSupplierBills' => 'Ingen registrert leverandørens faktura',
		'NoRecordedProducts' => 'Ingen registrert produkter / tjenester',
		'NoRecordedProspects' => 'Ingen registrert utsikter',
		'NoContractedProducts' => 'Ingen produkter / tjenester innleide',
		'NoRecordedContracts' => 'Ingen registrert kontrakter',
		'BoxLastContracts' => 'Laatste contracten',
		'BoxTitleLastContracts' => 'Laatste %s contracten',
		'NoModifiedSupplierBills' => 'Geen geregistreerd leverancier facturen',
		'NoRecordedContracts' => 'Geen geregistreerde overeenkomsten',
		'BoxOldestUnpaidCustomerBills' => 'Oudste onbetaalde facturen klant',
		'BoxOldestUnpaidSupplierBills' => 'Oudste onbetaalde facturen van de leverancier',
		'BoxLastContracts' => 'Laatste contracten',
		'BoxTotalUnpaidCustomerBills' => 'Totaal aantal onbetaalde facturen klant',
		'BoxTotalUnpaidSuppliersBills' => 'Totaal aantal onbetaalde facturen van de leverancier',
		'BoxTitleOldestUnpaidCustomerBills' => 'Oudste %s onbetaalde facturen klant',
		'BoxTitleOldestUnpaidSupplierBills' => 'Oudste %s onbetaalde facturen van de leverancier',
		'BoxTitleTotalUnpaidCustomerBills' => 'Onbetaalde facturen klant',
		'BoxTitleTotalUnpaidSuppliersBills' => 'Onbetaalde facturen van de leverancier',
		'BoxTitleLastContracts' => 'Laatste %s contracten',
		'NoModifiedSupplierBills' => 'Geen geregistreerd leverancier facturen',
		'NoRecordedContracts' => 'Geen geregistreerde overeenkomsten',
		'BoxLastContracts' => 'Ostatnie zamówienia',
		'BoxTitleLastProductsInContract' => 'Ostatnie %s produktów / usług w umowie',
		'BoxTitleLastContracts' => 'Ostatnie %s umów',
		'NoModifiedSupplierBills' => 'Nie zarejestrowane faktury dostawcy',
		'NoRecordedContracts' => 'Umów nie zarejestrowanych',
		'BoxLastContracts' => 'Última contratos',
		'BoxTitleLastContracts' => 'Última contratos %s',
		'NoModifiedSupplierBills' => 'Nenhum fornecedor facturas registadas na',
		'NoRecordedContracts' => 'Sem contratos registrados',
		'BoxTitleLastModifiedSuppliers' => '%s Ultima modificare furnizori',
		'BoxTitleLastModifiedCustomers' => '%s Ultima modificare clienţii',
		'BoxTitleLastModifiedProspects' => '%s Ultima modificare perspective',
		'BoxLastContacts' => 'Ultimele date de contact / adresele',
		'BoxLastMembers' => 'Ultimele membri',
		'BoxTitleLastModifiedMembers' => '%s Ultimele membri modificate',
		'BoxTitleLastModifiedContacts' => '%s Ultima modificare contacte / adrese',
		'BoxOldestExpiredServices' => 'Cele mai vechi active de servicii a expirat',
		'BoxLastExpiredServices' => 'Ultimele %s mai vechi contacte cu serviciile de active expirate',
		'BoxTitleLastModifiedDonations' => '%s Ultima modificare donaţii',
		'BoxTitleLastModifiedExpenses' => '%s Ultima modificare cheltuieli',
		'ClickToAdd' => 'Click aici pentru a adăuga.',
		'NoRecordedContacts' => 'Nu sunt înregistrate date de contact',
);
?>