<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Categorie',
		'Categories' => 'Categorii',
		'Rubrique' => 'Rubrică',
		'Rubriques' => 'Rubrici',
		'categories' => 'categorii',
		'TheCategorie' => 'Categoria',
		'NoCategoryYet' => 'Nicio categorie de acest tip creată',
		'In' => 'În',
		'AddIn' => 'Adăugaţi în',
		'modify' => 'modifică',
		'Classify' => 'Clasifică',
		'CategoriesArea' => 'Zona Categorii',
		'ProductsCategoriesArea' => 'Zona Categorii Produse / Servicii ',
		'SuppliersCategoriesArea' => 'Zona categorii furnizori ',
		'CustomersCategoriesArea' => 'Zona categorii clienţi ',
		'ThirdPartyCategoriesArea' => 'Zona categorii terţi',
		'MembersCategoriesArea' => 'Zona categorii membrii',
		'MainCats' => 'Categorii principale',
		'SubCats' => 'Subcategorii',
		'CatStatistics' => 'Statistici',
		'CatList' => 'Listă  categorii',
		'AllCats' => 'Toate categoriile',
		'ViewCat' => 'Vezi categoria',
		'NewCat' => 'Adaugă categorie',
		'NewCategory' => 'Categorie nouă',
		'ModifCat' => 'Modificare categorie',
		'CatCreated' => 'Categorie creată',
		'CreateCat' => 'Creaţi categorie',
		'CreateThisCat' => 'Creaţi această categorie',
		'ValidateFields' => 'Validare câmpuri',
		'NoSubCat' => 'Fără  subcategorii.',
		'SubCatOf' => 'Subcategorie',
		'FoundCats' => 'Categorii găsite',
		'FoundCatsForName' => 'Categorii găsite pentru  numele:',
		'FoundSubCatsIn' => 'Subcategorii găsit în categoria',
		'ErrSameCatSelected' => 'Le-aţi selectat în aceeaşi categorie de mai multe ori',
		'ErrForgotCat' => 'Ai uitat de să alegeţi  categoria',
		'ErrForgotField' => 'Ai uitat să îl informeze pe domenii',
		'ErrCatAlreadyExists' => 'Acest nume este folosit deja',
		'AddProductToCat' => 'Adauga acest produs la o categorie?',
		'ImpossibleAddCat' => 'Imposibil de a adăuga la categoria',
		'ImpossibleAssociateCategory' => 'Imposibil de a se asocia în categoria a',
		'WasAddedSuccessfully' => '<b> %s</b> a fost adaugat cu succes.',
		'ObjectAlreadyLinkedToCategory' => 'Elementul este deja legate de această categorie.',
		'CategorySuccessfullyCreated' => 'Această categorie %s a fost adaugata cu succes.',
		'ProductIsInCategories' => 'Produse / servicii pentru a deţine următoarele categorii',
		'SupplierIsInCategories' => 'Terţă parte de a deţine următoarele categorii de furnizori',
		'CompanyIsInCustomersCategories' => 'Acest terţ deţine la următoarele clienţi / perspectivele categorii',
		'CompanyIsInSuppliersCategories' => 'Acest terţ deţine la următoarele categorii de furnizori',
		'MemberIsInCategories' => 'Acest membru detine la următoarele categorii de membri',
		'ProductHasNoCategory' => 'Acest produs / serviciu nu este în nici un categorii',
		'SupplierHasNoCategory' => 'Acest furnizor nu este în nici un categorii',
		'CompanyHasNoCategory' => 'Aceasta companie nu este în nici un categorii',
		'MemberHasNoCategory' => 'Acest membru nu este în nicio categorie',
		'ClassifyInCategory' => 'Clasifica în categoria',
		'NoneCategory' => 'Niciunul',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Această categorie nu există deja în acelaşi loc',
		'ReturnInProduct' => 'Inapoi la produs / serviciu de carte',
		'ReturnInSupplier' => 'Inapoi la furnizor carte',
		'ReturnInCompany' => 'Inapoi la client / perspectiva carte',
		'ContentsVisibleByAll' => 'Conţinutul vor fi vizibile de către toate',
		'ContentsVisibleByAllShort' => 'Cuprins vizibil de către toate',
		'ContentsNotVisibleByAllShort' => 'Cuprins nu sunt vizibile de către toate',
		'CategoriesTree' => 'Categorii de copac',
		'DeleteCategory' => 'Ştergere categorie',
		'ConfirmDeleteCategory' => 'Sunteţi sigur că doriţi să ştergeţi această categorie?',
		'RemoveFromCategory' => 'Eliminaţi link-ul cu Categorie',
		'RemoveFromCategoryConfirm' => 'Sunteţi sigur că doriţi să ştergeţi legătura dintre tranzacţie şi de categorie?',
		'NoCategoriesDefined' => 'Nu categorie definită',
		'SuppliersCategoryShort' => 'Furnizori categorie',
		'CustomersCategoryShort' => 'Clienţii categorie',
		'ProductsCategoryShort' => 'Produse categorie',
		'MembersCategoryShort' => 'Membrii categorie',
		'SuppliersCategoriesShort' => 'Furnizori categorii',
		'CustomersCategoriesShort' => 'Clienţii categorii',
		'CustomersProspectsCategoriesShort' => 'Custo. / Prosp. categorii',
		'ProductsCategoriesShort' => 'Produse Categorii',
		'MembersCategoriesShort' => 'Membrii categorii',
		'ThisCategoryHasNoProduct' => 'Această categorie nu conţine nici un produs.',
		'ThisCategoryHasNoSupplier' => 'Această categorie nu conţine nici un furnizor.',
		'ThisCategoryHasNoCustomer' => 'Această categorie nu conţine nici un client.',
		'ThisCategoryHasNoMember' => 'Această categorie nu conţine nici un membru.',
		'AssignedToCustomer' => 'Angajat într-un client',
		'AssignedToTheCustomer' => 'Atribuite de client',
		'InternalCategory' => 'Inernal categorie',
		'CategoryContents' => 'Categorie conţinutul',
		'CategId' => 'Id-ul categoriei',
		'CatSupList' => 'Lista de furnizor categorii',
		'CatCusList' => 'Lista de client / categorii de perspectivă',
		'CatProdList' => 'Lista de categorii de produse',
		'CatMemberList' => 'Lista membrilor categorii',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>