<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Comercial',
		'CommercialArea' => 'Zona Comercial',
		'CommercialCard' => 'Fişă Comercială',
		'CustomerArea' => 'Zona Clienţii ',
		'Customer' => 'Client',
		'Customers' => 'Clienţi',
		'Prospect' => 'Prospect',
		'Prospects' => 'Prospecţi',
		'Suspects' => 'Suspecţi',
		'DeleteAction' => 'Ştergeţi o acţiune / sarcină',
		'NewAction' => 'Acţiune / sarcină nouă',
		'AddAction' => 'Adăugare acţiune / sarcină nouă',
		'AddAnAction' => 'Adăugaţi o acţiune / sarcină',
		'AddActionRendezVous' => 'Adaugă întâlnire',
		'Rendez-Vous' => 'Întâlnire',
		'ConfirmDeleteAction' => 'Sunteţi sigur că doriţi să ştergeţi această acţiune / sarcină?',
		'CardAction' => 'Fişă acţiune',
		'PercentDone' => 'Procentajul realizat',
		'ActionOnCompany' => 'Acţiune privitoare la societatea',
		'ActionOnContact' => 'Acţiune privitoare la contactul',
		'TaskRDV' => 'Întâlniri',
		'TaskRDVWith' => 'Întâlnire cu %s',
		'ShowTask' => 'Afişează sarcină',
		'ShowAction' => 'Afişează acţiunea',
		'ActionsReport' => 'Raport acţiuni ',
		'ThirdPartiesOfSaleRepresentative' => 'Terţ cu reprezentant vânzări',
		'SalesRepresentative' => 'Reprezentant vânzări',
		'SalesRepresentatives' => 'Reprezentanţi vânzări',
		'SalesRepresentativeFollowUp' => 'Reprezentant vânzări(follow-up)',
		'SalesRepresentativeSignature' => 'Reprezentant vânzări (semnătura)',
		'CommercialInterlocutor' => 'Interlocutor comercial',
		'ErrorWrongCode' => 'Cod greşit ',
		'NoSalesRepresentativeAffected' => 'Niciun reprezentant vânzări particular afectat',
		'ShowCustomer' => 'Afişează client',
		'ShowProspect' => 'Afişează prospect',
		'ShowSuspect' => 'Afişează suspect',
		'ListOfProspects' => 'Listă  prospecte',
		'ListOfCustomers' => 'Listă  clienţi',
		'ListOfSuspects' => 'Listă suspecţi',
		'ListOfAll' => 'Listă toate conturile',
		'ListSuspectsShort' => 'Listă suspecţi',
		'ListAllShort' => 'Listă toate conturile',
		'LastDoneTasks' => 'Ultimele %s acţiuni efectuate',
		'LastRecordedTasks' => 'Ultimele acţiuni  înregistrate',
		'LastActionsToDo' => 'Cele mai vechi  %s acţiuni nefinalizate',
		'DoneAndToDoActionsFor' => 'Lista acţiunilor realizate sau de realizat pentru %s',
		'DoneAndToDoActions' => 'Lista acţiunilor realizate sau de realizat ',
		'DoneActions' => 'Lista acţiunilor realizate',
		'DoneActionsFor' => 'Lista acţiunilor realizate pentru %s',
		'ToDoActions' => 'Acţiuni incomplete',
		'ToDoActionsFor' => 'Acţiuni incomplete pentru %s',
		'SendPropalRef' => 'Trimite propunerea comercială %s',
		'SendOrderRef' => 'Trimite comanda  %s',
		'StatusNotApplicable' => 'Nu se aplică',
		'StatusActionToDo' => 'De realizat',
		'StatusActionDone' => 'Realizat',
		'StatusActionInProcess' => 'În curs',
		'MyActionsAsked' => 'Acţiuni ce le-am inregistrat',
		'MyActionsToDo' => 'Acţiuni ce mi-au fost atribuite',
		'MyActionsDone' => 'Acţiuni atribuite  mie realizate',
		'TasksHistoryForThisContact' => 'Acţiuni pentru acest contact',
		'LastProspectDoNotContact' => 'Nu  contacta',
		'LastProspectNeverContacted' => 'Necontactat',
		'LastProspectToContact' => 'De contactat',
		'LastProspectContactInProcess' => 'Contact în curs',
		'LastProspectContactDone' => 'Prospecte contactate',
		'DateActionPlanned' => 'Dată realizare planificată',
		'DateActionDone' => 'Dată realizare efectivă',
		'ActionAskedBy' => 'Acţiune înregistrată de către',
		'ActionAffectedTo' => 'Acţiune  atribuită pentru ',
		'ActionDoneBy' => 'Acţiune realizată de către',
		'ActionUserAsk' => 'Înregistrată de către',
		'ErrorStatusCantBeZeroIfStarted' => 'Dacă câmpul "<b>Data inceput reală</b> "este completat,acţiunea  este începută  (sau terminată),  astfel câmpul " <b>Status</b> " nu poate fi 0%%.',
		'ActionAC_TEL' => 'Apel telefonic',
		'ActionAC_FAX' => 'Trimite fax',
		'ActionAC_PROP' => 'Trimite ofertă pe mail',
		'ActionAC_EMAIL' => 'Trimite email',
		'ActionAC_RDV' => 'Întâlniri',
		'ActionAC_FAC' => 'Trimite factura client pe email',
		'ActionAC_REL' => 'Trimite factura client pe email (relansare)',
		'ActionAC_CLO' => 'Închide',
		'ActionAC_EMAILING' => 'Trimite email-uri în masă',
		'ActionAC_COM' => 'Trimite comanda client prin email',
		'ActionAC_SHIP' => 'Trimite   aviz de expediţie prin email',
		'ActionAC_SUP_ORD' => 'Trimite comanda  furnizor prin email ',
		'ActionAC_SUP_INV' => 'Trimite factura furnizor prin email ',
		'ActionAC_OTH' => 'Altele',
		'Stats' => 'Statistici vânzări',
		'CAOrder' => 'Volum vânzări (comenzi validate)',
		'FromTo' => 'de la %s la %s',
		'MargeOrder' => 'Marje (comenzi validate)',
		'RecapAnnee' => 'Recapitulativ an',
		'NoData' => 'Nicio dată',
		'StatusProsp' => 'Status prospect ',
		'DraftPropals' => 'Draft propunere comercială',
		'SearchPropal' => 'Căutaţi o propunere comercială'
);
?>