<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Comerciale',
		'CommercialArea' => 'Zona comerciala',
		'CommercialCard' => 'Comerciale carte',
		'CustomerArea' => 'Clienţii zona',
		'Customer' => 'Client',
		'Customers' => 'Clienti',
		'Prospect' => 'Prospect',
		'Prospects' => 'Perspectivele',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Ştergeţi o acţiune / sarcina',
		'NewAction' => 'New acţiune / sarcina',
		'AddAction' => 'Adăugare acţiune / sarcina',
		'AddAnAction' => 'Adăugaţi o acţiune / sarcina',
		'AddActionRendezVous' => 'Adauga un loc de întâlnire sarcină',
		'Rendez-Vous' => 'Loc de întâlnire',
		'ConfirmDeleteAction' => 'Sunteţi sigur că doriţi să ştergeţi această sarcină?',
		'CardAction' => 'Acţiunea carte',
		'PercentDone' => 'Procentajul făcut',
		'ActionOnCompany' => 'Task despre companie',
		'ActionOnContact' => 'Task despre contact',
		'TaskRDV' => 'Întâlniri',
		'TaskRDVWith' => 'Întâlnire cu %s',
		'ShowTask' => 'Arata sarcină',
		'ShowAction' => 'Arata acţiune',
		'ActionsReport' => 'Acţiuni de raport',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Reprezentant vanzari',
		'SalesRepresentatives' => 'Reprezentanţii de vânzări',
		'SalesRepresentativeFollowUp' => 'Reprezentant vanzari (follow-up)',
		'SalesRepresentativeSignature' => 'Reprezentant vanzari (semnătura)',
		'CommercialInterlocutor' => 'Comerciale interlocutor',
		'ErrorWrongCode' => 'Greşit codul',
		'NoSalesRepresentativeAffected' => 'Nu special afectate reprezentant vânzări',
		'ShowCustomer' => 'Arata client',
		'ShowProspect' => 'Arata perspectiva',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Lista de perspectivele',
		'ListOfCustomers' => 'Lista de clienţi',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'Ultima %s făcut sarcini',
		'LastRecordedTasks' => 'Ultima înregistrate sarcini',
		'LastActionsToDo' => 'Ultima %s acţiunile cele mai vechi nu sa finalizat cu',
		'DoneAndToDoActionsFor' => 'Pentru a face Adoptată şi sarcinile pentru %s',
		'DoneAndToDoActions' => 'Pentru a face Adoptată şi sarcinile',
		'DoneActions' => 'Adoptat acţiuni',
		'DoneActionsFor' => 'Adoptat acţiuni pentru %s',
		'ToDoActions' => 'acţiuni incomplete',
		'ToDoActionsFor' => 'acţiuni incomplete pentru %s',
		'SendPropalRef' => 'Trimite comerciale propunerea %s',
		'SendOrderRef' => 'Trimite pentru %s',
		'StatusNotApplicable' => 'Nu se aplică',
		'StatusActionToDo' => 'Pentru a face',
		'StatusActionDone' => 'Făcut',
		'StatusActionInProcess' => 'În procesul de',
		'MyActionsAsked' => 'Acţiuni am inregistrat',
		'MyActionsToDo' => 'Acţiuni ce am de făcut',
		'MyActionsDone' => 'Acţiuni afectate pentru a-mi',
		'TasksHistoryForThisContact' => 'Acţiuni pentru acest contact',
		'LastProspectDoNotContact' => 'Nu de contact',
		'LastProspectNeverContacted' => 'N-am contactat',
		'LastProspectToContact' => 'Pentru a contacta',
		'LastProspectContactInProcess' => 'De contact în procesul de',
		'LastProspectContactDone' => 'Contact făcut',
		'DateActionPlanned' => 'Data planificată pentru acţiune',
		'DateActionDone' => 'Data de acţiune făcut',
		'ActionAskedBy' => 'Acţiunea a cerut de către',
		'ActionAffectedTo' => 'Afectate de acţiune pentru a',
		'ActionDoneBy' => 'Acţiunea efectuată de către',
		'ActionUserAsk' => 'Înregistrate de către',
		'ErrorStatusCantBeZeroIfStarted' => 'Dacă câmpul <b>"Data făcut"</b> este completat, este început de acţiune (sau finite), astfel încât câmpul <b>"Status"</b> nu poate fi 0%%.',
		'ActionAC_TEL' => 'Telefon',
		'ActionAC_FAX' => 'Trimite fax',
		'ActionAC_PROP' => 'Trimiteţi propunere',
		'ActionAC_EMAIL' => 'Trimite un email',
		'ActionAC_RDV' => 'Întâlniri',
		'ActionAC_FAC' => 'Trimite facturare',
		'ActionAC_REL' => 'Trimite facturare (memento)',
		'ActionAC_CLO' => 'Închide',
		'ActionAC_EMAILING' => 'Trimite email-uri în masă',
		'ActionAC_COM' => 'Pentru a trimite prin e-mail',
		'ActionAC_SHIP' => 'Trimite prin e-mail de transport maritim',
		'ActionAC_SUP_ORD' => 'Trimite comanda prin e-mail cu furnizorul',
		'ActionAC_SUP_INV' => 'Trimite factura prin e-mail cu furnizorul',
		'ActionAC_OTH' => 'Alte',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Prospect statutul',
		'DraftPropals' => 'Proiectul de propuneri comerciale',
		'SearchPropal' => 'Căutaţi o propunere comercială'
);
?>