<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$contracts = array(
		'CHARSET' => 'UTF-8',
		'ContractsArea' => 'Zona Contracte',
		'ListOfContracts' => 'Lista  contracte',
		'LastContracts' => 'Ultimele %s  contracte modificate',
		'AllContracts' => 'Toate contractele',
		'ContractCard' => 'Fişă Contract ',
		'ContractStatus' => 'Stare Contract',
		'ContractStatusNotRunning' => 'Fără service',
		'ContractStatusRunning' => 'În service',
		'ContractStatusDraft' => 'Draft',
		'ContractStatusValidated' => 'Validat',
		'ContractStatusClosed' => 'Închis',
		'ServiceStatusInitial' => 'Inactiv',
		'ServiceStatusRunning' => 'In service',
		'ServiceStatusNotLate' => 'În service, nexpirat',
		'ServiceStatusNotLateShort' => 'Nexpirat',
		'ServiceStatusLate' => 'În service expirat',
		'ServiceStatusLateShort' => 'Expirat',
		'ServiceStatusClosed' => 'Închis',
		'ServicesLegend' => 'Legenda Service',
		'Contracts' => 'Contracte',
		'Contract' => 'Contract',
		'NoContracts' => 'Fără contracte',
		'MenuServices' => 'Servicii',
		'MenuInactiveServices' => 'Servicii neactive',
		'MenuRunningServices' => 'Servicii active',
		'MenuExpiredServices' => 'Servicii expirate',
		'MenuClosedServices' => 'Servicii închise',
		'NewContract' => 'Contract nou',
		'AddContract' => 'Adaugă contract',
		'SearchAContract' => 'Căutare contract',
		'DeleteAContract' => 'Ştergere contract',
		'CloseAContract' => 'Închidere contract',
		'ConfirmDeleteAContract' => 'Sunteţi sigur că doriţi să ştergeţi acest contract şi toate serviciile sale?',
		'ConfirmValidateContract' => 'Sunteţi sigur că doriţi să validaţi acest contract?',
		'ConfirmCloseContract' => 'Acest lucru  va închide toate serviciile (active sau nu). Sunteţi sigur că vreţi să închideţi acest contract ?',
		'ConfirmCloseService' => 'Sunteţi sigur că vreţi să închideţi acest serviciu cu data  de <b> %s?</b>',
		'ValidateAContract' => 'Validare  contract',
		'ActivateService' => 'Activare serviciu',
		'ConfirmActivateService' => 'Sunteţi sigur că doriţi să activaţi acest serviciu cu data de <b> %s</b> _',
		'RefContract' => 'Referinţă Contract ',
		'DateContract' => 'Data Contract ',
		'DateServiceActivate' => 'Data  activare a serviciu',
		'DateServiceUnactivate' => 'Data dezactivare serviciu',
		'DateServiceStart' => 'Data de început serviciu',
		'DateServiceEnd' => 'Data de sfârşit  serviciu',
		'ShowContract' => 'Afişare contract',
		'ListOfServices' => 'Listă  servicii',
		'ListOfInactiveServices' => 'Listă servicii neactive',
		'ListOfExpiredServices' => 'Listă servicii active expirate',
		'ListOfClosedServices' => 'Listă  servicii închise',
		'ListOfRunningContractsLines' => 'Listă linii contract în service',
		'ListOfRunningServices' => 'Listă servicii active',
		'NotActivatedServices' => 'Servicii  inactive (din contracte validate )',
		'BoardNotActivatedServices' => 'Servicii de activat în  contracte valide',
		'LastContracts' => 'Ultimele %s  contracte modificate',
		'LastActivatedServices' => 'Ultimele %s servicii activate',
		'LastModifiedServices' => 'Ultimele  %s  servicii  modificate',
		'EditServiceLine' => 'Editare linie de serviciu ',
		'ContractStartDate' => 'Dată început',
		'ContractEndDate' => 'Dată sfârşit',
		'DateStartPlanned' => 'Data  planificată  început ',
		'DateStartPlannedShort' => 'Dată inceput planificată',
		'DateEndPlanned' => 'Dată planificată  sfârşit ',
		'DateEndPlannedShort' => 'Dată sfărşit planificată',
		'DateStartReal' => 'Data reală început',
		'DateStartRealShort' => 'Data de început ',
		'DateEndReal' => 'Data reală de sfârşit',
		'DateEndRealShort' => 'Data de sfârşit reală',
		'NbOfServices' => 'Nr de servicii',
		'CloseService' => 'Inchidere serviciu',
		'ServicesNomberShort' => '%s serviciu (i)',
		'RunningServices' => ' Servicii active',
		'BoardRunningServices' => 'Servicii active şi expirate în contract',
		'ServiceStatus' => 'Statut serviciu',
		'DraftContracts' => 'Drafturi de contracte',
		'CloseRefusedBecauseOneServiceActive' => 'Contractul nu poate fi închis deoarece există cel puţin un serviciu deschis pe el.',
		'CloseAllContracts' => 'Închideţi toate serviciile',
		'DeleteContractLine' => 'Ştergeţi o linie de contract',
		'ConfirmDeleteContractLine' => 'Sunteţi sigur că doriţi să ştergeţi aceasăt linie de contract ?',
		'MoveToAnotherContract' => 'Mutare serviciu într-un alt contract.',
		'ConfirmMoveToAnotherContract' => 'Am ales contractul  ţintă şi  confirm  că vreau să mutaţi acest serviciu în acest contract.',
		'ConfirmMoveToAnotherContractQuestion' => 'Alegeţi, în care contract existent (al acelaşi terţ) doriţi să mutaţi acest serviciu ?',
		'PaymentRenewContractId' => 'Reînnoiţi  linie  contract( numărul %s)',
		'ExpiredSince' => 'Data expirării',
		'RelatedContracts' => 'Contracte asociate',
		'NoExpiredServices' => 'Niciun Serviciu activ expirat',
		////////// Types de contacts //////////
		'TypeContact_contrat_internal_SALESREPSIGN' => 'Semnatura Reprezentant vanzari  a contractului',
		'TypeContact_contrat_internal_SALESREPFOLL' => 'Reprezentant vanzări responsabil contract',
		'TypeContact_contrat_external_BILLING' => 'Contact client factură  contract',
		'TypeContact_contrat_external_CUSTOMER' => 'Contact  Follow-up  client',
		'TypeContact_contrat_external_SALESREPSIGN' => 'Contact client semnatura  contract',
		'Error_CONTRACT_ADDON_NotDefined' => 'Constantă CONTRACT_ADDON nedefinită'
);
?>