<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$holiday = array(
		'CHARSET' => 'UTF-8',
		'CPTitreMenu' => 'Concedii',
		'MenuReportMonth' => 'Situatia lunara',
		'MenuAddCP' => 'Cerere noua',
		'NotActiveModCP' => 'Trebuie sa activati modulul Concedii pentru afisarea acestei pagini',
		'NotConfigModCP' => 'Trebuie sa configurati modulul Concedii pentru afisarea acestei pagini.Pentru aceasta, <a href="./admin/holiday.php?leftmenu=setup&mainmenu=home" style="font-weight: normal; color: red; text-decoration: underline;"> click aici </ a>.',
		'NoCPforUser' => 'Dvs nu aveti inca cerere de concediu.',
		'AddCP' => 'Creare cerere de concediu',
		'CPErrorSQL' => 'O eroare SQL a survenit:',
		'Employe' => 'Salariat',
		'DateDebCP' => 'Data de inceput',
		'DateFinCP' => 'Data de final',
		'DateCreateCP' => 'Data creare',
		'DraftCP' => 'Ciorna',
		'ToValidateCP' => 'In asteptarea vaidarii',
		'ValidateCP' => 'Validata',
		'CancelCP' => 'Anulata',
		'RefuseCP' => 'Refuzata',
		'ValidatorCP' => 'Validator',
		'ListeCP' => 'Lista concedii',
		'ValidateByCP' => 'Va fi validata de',
		'DescCP' => 'Descriere',
		'SendRequestCP' => 'Trimite cererea de concediu',
		'DelayToRequestCP' => 'Cererile de concediu trebuiesc fi facute cu  cel putin<b>%s zi(le)</b> inainte de data.',
		'MenuConfCP' => 'Actualizeaza soldul',
		'UpdateAllCP' => 'Actualizeaza concediile',
		'SoldeCPUser' => 'Soldul dvs de concediu este de <b>%s zile</b>.',
		'ErrorEndDateCP' => 'Trebuie sa alegeti o data de sfarsit superioara celei de inceput',
		'ErrorSQLCreateCP' => 'O eroare SQL a  intervenit in timpul crearii :',
		'ErrorIDFicheCP' => 'O eroare a intervenit, cererea de concediu nu exista',
		'ReturnCP' => 'Inapoi la pagina precedenta',
		'ErrorUserViewCP' => 'Dvs nu aveti dreptul de a citi aceata cerere de concediu.',
		'InfosCP' => 'Informatii cerere de concediu',
		'InfosWorkflowCP' => 'Flux Informatii',
		'DateCreateCP' => 'Data creare',
		'RequestByCP' => 'Cerut de',
		'TitreRequestCP' => 'Fisa Concedii',
		'NbUseDaysCP' => 'Nunar de zile de concediu consumate',
		'EditCP' => 'Modifica',
		'DeleteCP' => 'Sterge',
		'ActionValidCP' => 'Valideaza',
		'ActionRefuseCP' => 'Refuza',
		'ActionCancelCP' => 'Anuleaza',
		'StatutCP' => 'Statut',
		'SendToValidationCP' => 'Trimite la validare',
		'TitleDeleteCP' => 'Sterge cererea de concediu',
		'ConfirmDeleteCP' => 'Confirmati stergerea acestei cereri de concediu ?',
		'ErrorCantDeleteCP' => 'Eroare, dvs nu aveti drepturi de stergere acestei cereri de concediu.',
		'CantCreateCP' => 'Dvs nu aveti drepturi de face cereri de concediu.',
		'InvalidValidatorCP' => 'Dvs trebuie sa alegeti un validator pentru cererea dvs de concediu.',
		'UpdateButtonCP' => 'Actualizare',
		'CantUpdate' => 'Dvs nu puteti actualiza aceasta cerere de concediu.',
		'NoDateDebut' => 'Dvs trebuie sa alegeti o data de  inceput.',
		'NoDateFin' => 'Dvs trebuie sa alegeti o data de final.',
		'ErrorDureeCP' => 'Cererea dvs de concediu platit nu contine nicio zi lucratoare.',
		'TitleValidCP' => 'Valideaza cererea de concediu platit',
		'ConfirmValidCP' => 'Sunteti sigur ca doriti validarea cererii de concediu ?',
		'DateValidCP' => 'Data validarii ',
		'TitleToValidCP' => 'Trimite cererea de concediu platit',
		'ConfirmToValidCP' => 'Sunteti sigur ca doriti trimiterea cererii de concediu ?',
		'TitleRefuseCP' => 'Refuzare cerere concediu platit',
		'ConfirmRefuseCP' => 'Sunteti sigur ca doritirefuzarea cererii de concediu ?',
		'NoMotifRefuseCP' => 'Dvs trebuie sa alegeti un motiv pentru refuzarea acestei cereri.',
		'TitleCancelCP' => 'Anuleaza cererea de concediu platit',
		'ConfirmCancelCP' => 'Sunteti sigur ca doriti anularea cererii de concediu ?',
		'DetailRefusCP' => 'Motiv de refuz',
		'DateRefusCP' => 'Data refuzului',
		'DateCancelCP' => 'Data anularii',
		'DefineEventUserCP' => 'Atribuie un concediu exceptional la un utilizator',
		'addEventToUserCP' => 'Atribuie acest concediu',
		'MotifCP' => 'Motiv',
		'UserCP' => 'Utilizator',
		'ErrorAddEventToUserCP' => 'O eroare a survenit in timpul adaugarii de concediu exceptional.',
		'AddEventToUserOkCP' => 'Adaugarea de concediu exceptional a fost efectuat',
		'MenuLogCP' => 'Vezi logurile concediilor',
		'LogCP' => 'Loguri de actualizari concedii',
		'ActionByCP' => 'Realizat de',
		'UserUpdateCP' => 'Pentru utilizatorul',
		'ActionTypeCP' => 'Tip',
		'PrevSoldeCP' => 'Sold precedent',
		'NewSoldeCP' => 'Sold nou',
		'alreadyCPexist' => 'O cerere de concediu a fost deja efectuata pe aceasta perioada',
		'UserName' => 'Nume Prenume',
		'Employee' => 'Salariat',
		'FirstDayOfHoliday' => 'Prima zi de concediu',
		'LastDayOfHoliday' => 'Ultima zi de concediu',
		//// Configuration du Module ////
		'ConfCP' => 'Configurare modul concedii',
		'DescOptionCP' => 'Descriere optiune',
		'ValueOptionCP' => 'Valoare
',
		'GroupToValidateCP' => 'Grup cu drepturi de validare a concediilor',
		'ConfirmConfigCP' => 'Validati configuratia',
		'LastUpdateCP' => 'Ultima actualizare automata  a concediilor',
		'UpdateConfCPOK' => 'Actualizare reusita',
		'ErrorUpdateConfCP' => 'O eroare a intervenit in timpul actualizarii, va rugam mai incercati .',
		'AddCPforUsers' => 'Puteti adauga soldul concediilor pentru utilizatori <a href="../define_holiday.php" style="font-weight: normal; color: red; text-decoration: underline;">click aici</a>.',
		'DelayForSubmitCP' => 'Perioada de timp  in avans pentru a face o cerere de concediu ',
		'AlertValidatorDelayCP' => 'Prevenire validarea daca cererea de concediu nu repecta  perioada de anuntare prevazuta',
		'AlertValidorSoldeCP' => 'Prevenire validarea daca utilizatorul cere zile sw concediu ce depaseste soldul',
		'nbUserCP' => 'Numarul de utilizatori suportat de modulul concedii',
		'nbHolidayDeductedCP' => 'Numar de concedii platite de dedus pe zile ce concediu luat',
		'nbHolidayEveryMonthCP' => 'Numar de concedii platite adaugate in fiecare luna',
		'Module27130Name' => 'Managementul concediilor',
		'Module27130Desc' => 'Managementul concediilor',
		'TitleOptionMainCP' => 'Configurari principale a concediilor',
		'TitleOptionEventCP' => 'Configurari legate de evenimente a concediilor',
		'ValidEventCP' => 'Validare',
		'UpdateEventCP' => 'Actualizare evenimente',
		'CreateEventCP' => 'Creare',
		'NameEventCP' => 'Nume eveniment',
		'OkCreateEventCP' => 'Adaugarea evenimentului s-a derulat cu succes.',
		'ErrorCreateEventCP' => 'Eroare la crearea evenimentului',
		'UpdateEventOkCP' => 'Actualizarea evenomentului s-a derulat cu succes',
		'ErrorUpdateEventCP' => 'Eroare la actualizarea unui eveniment.',
		'DeleteEventCP' => 'Stergere eveniment',
		'DeleteEventOkCP' => 'Evenimentul a fost sters cu succes',
		'ErrorDeleteEventCP' => 'Eroare la stergerea evenimentului.',
		'TitleDeleteEventCP' => 'Sterge un concediu exceptional',
		'TitleCreateEventCP' => 'Creaza un concediu exceptional',
		'TitleUpdateEventCP' => 'Modifica sau sterge un concediu exceptional',
		'DeleteEventOptionCP' => 'Stegere',
		'UpdateEventOptionCP' => 'Actualizare',
		'ErrorMailNotSend' => 'O eroare a intervenit la trimiterea mailului :',
		'NoCPforMonth' => 'Niciun concediu in luna aceasta',
		'Jours' => 'zile',
		'nbJours' => 'Numar zile',
		'TitleAdminCP' => 'Configurare Concedii',
		'Permission20001' => 'Citeste / Creare / modificare toate cererile de concediu'
);
?>