<?php
/* Copyright (C) 2012-2013	Regis Houssin	<regis.houssin@capnetworks.com>
 * Copyright (C) 2012-2013	Herve Prot		<herve.prot@symeos.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$orders = array(
		'CHARSET' => 'UTF-8',
		'OrdersArea' => 'Zona Comenzi Clienţi',
		'SuppliersOrdersArea' => ' Zona Comenzi Furnizori ',
		'OrderCard' => 'Fişă Comandă',
		'OrderId' => 'ID Comandă',
		'Order' => 'Comandă',
		'Orders' => 'Comenzi',
		'OrderLine' => 'Linie Comandă',
		'OrderLines' => 'Linii comandă',
		'OrderFollow' => 'Urmăreşte',
		'OrderDate' => 'Data comandă',
		'OrderToProcess' => 'Comandă de procesat',
		'NewOrder' => 'Comandă nouă',
		'ToOrder' => 'Faceţi comanda',
		'MakeOrder' => 'Faceţi comanda',
		'SupplierOrder' => 'Comandă Furnizor ',
		'SuppliersOrders' => 'Comenzi Furnizori ',
		'SuppliersOrdersRunning' => 'Comenzi furnizori în curs',
		'CustomerOrder' => 'Comandă clienţi',
		'CustomersOrders' => 'Comenzi clienţi',
		'CustomersOrdersRunning' => 'Comenzi clienţi în curs',
		'CustomersOrdersAndOrdersLines' => 'Comenzi Clienţi  şi linii comenzi',
		'OrdersToValid' => 'Comenzi clienţi de validat',
		'OrdersToBill' => 'Comenzi clienţi livrate',
		'OrdersInProcess' => 'Comenzi clienţi în procesare',
		'OrdersToProcess' => 'Comenzi clienti de procesat',
		'SuppliersOrdersToProcess' => 'Comenzi furnizor de procesat',
		'StatusOrderCanceledShort' => 'Anulată',
		'StatusOrderDraftShort' => 'Draft',
		'StatusOrderValidatedShort' => 'Validată',
		'StatusOrderSentShort' => 'În procesare',
		'StatusOrderSent' => ' Livrare în procesare',
		'StatusOrderOnProcessShort' => 'În curs',
		'StatusOrderProcessedShort' => 'Procesată',
		'StatusOrderToBillShort' => 'Livrată',
		'StatusOrderToBill2Short' => 'De facturat',
		'StatusOrderApprovedShort' => 'Aprobată',
		'StatusOrderRefusedShort' => 'Refuzată',
		'StatusOrderToProcessShort' => 'De procesat',
		'StatusOrderReceivedPartiallyShort' => 'Parţial recepţionată',
		'StatusOrderReceivedAllShort' => 'Complet recepţionată',
		'StatusOrderCanceled' => 'Anulată',
		'StatusOrderDraft' => 'Draft (trebuie să fie validată)',
		'StatusOrderNeedQuotes' => 'Draft (needs manual quotes)',
		'StatusOrderNew' => 'Ordin nou (trebuie să fie validat)',
		'StatusOrderProcessing' => 'Procesare',
		'StatusOrderValidated' => 'Validată',
		'StatusOrderOnProcess' => 'Aşteaptă recepţia',
		'StatusOrderSending' => 'Sending',
		'StatusOrderClosed' => 'Closed (Shipped)',
		'StatusOrderToBill' => 'Livrată',
		'StatusOrderToBill2' => 'De facturat',
		'StatusOrderApproved' => 'Aprobată',
		'StatusOrderRefused' => 'Refuzată',
		'StatusOrderError' => 'Eroare',
		'StatusOrderReceivedPartially' => 'Parţial recepţionată',
		'StatusOrderReceivedAll' => 'Recepţionată complet',
		'ShippingExist' => 'O expediţie există',
		'DraftOrWaitingApproved' => 'Draft sau aprobarea nu a fost încă comandată',
		'DraftOrWaitingShipped' => 'Draft sau validarea nu a fost încă expediată',
		'MenuOrdersToBill' => 'Comenzi livrate ',
		'MenuOrdersToBill2' => 'Comenzi de facturat',
		'SearchOrder' => 'Căutare comandă',
		'Sending' => 'Expediţie',
		'Sendings' => 'Expediţii',
		'ShipProduct' => 'Expediere produs',
		'Discount' => 'Discount',
		'CreateOrder' => 'Creare comandă',
		'RefuseOrder' => 'Refuzare comandă',
		'ApproveOrder' => 'Acceptare comandă',
		'ValidateOrder' => 'Validate comandă',
		'UnvalidateOrder' => 'Devalidare comandă',
		'DeleteOrder' => 'Ştergere comandă',
		'CancelOrder' => 'Anulare comandă',
		'AddOrder' => 'Creare comandă',
		'AddToMyOrders' => 'Adaugare la comenzile mele',
		'AddToOtherOrders' => 'Adaugare la alte comenzi',
		'ShowOrder' => 'Afişare comandă',
		'NoOpenedOrders' => 'Nicio comandă draft',
		'NoOtherOpenedOrders' => 'Nici o altă comandă draft',
		'OtherOrders' => 'Alte comenzi',
		'LastOrders' => 'Ultimele %s comenzi',
		'LastModifiedOrders' => 'Ultimele %s comenzi modificate',
		'LastClosedOrders' => 'Ultimele %s comenzi închise',
		'AllOrders' => 'Toate comenzile',
		'NbOfOrders' => 'Numar de comenzi',
		'OrdersStatistics' => 'Statistici comenzi',
		'OrdersStatisticsSuppliers' => 'Statistici  Comenzi Furnizori',
		'NumberOfOrdersByMonth' => 'Numar comenzi pe lună',
		'AmountOfOrdersByMonthHT' => 'Valoarea  totală a comenzilor pe  luna (fără taxe)',
		'ListOfOrders' => 'Lista comenzi',
		'CloseOrder' => 'Inchidere comanda',
		'ConfirmCloseOrder' => 'Sunteţi sigur că vreţi să închideţi acestă comandă ?  Odată ce un comanda este închisă, ea poate fi doar facturată.',
		'ConfirmCloseOrderIfSending' => 'Sunteţi sigur că vreţi să închideţi aceae facut.',
		'ConfirmDeleteOrder' => 'Sunteţi sigur că doriţi să ştergeţi această comandă ?',
		'ConfirmValidateOrder' => 'Sunteţi sigur că doriţi să validaţi această comandă sub numele <b>%s</b>  ?',
		'ConfirmUnvalidateOrder' => 'Sunteţi sigur că doriţi să restauraţi comanda  <b>%s</b> la statutul de draft ?',
		'ConfirmCancelOrder' => 'Sunteţi sigur că doriţi să anulaţi această comandă?',
		'ConfirmMakeOrder' => 'Sunteţi sigur că doriţi să confirmaţi această comandă, pentru in data de<b> %s</b> ?',
		'GenerateBill' => 'Generare factură',
		'ClassifyShipped' => 'Clasează livrate',
		'ClassifyBilled' => 'Clasează facturate',
		'ComptaCard' => 'Fişă Contabilitate ',
		'DraftOrders' => 'Comenzi draft',
		'RelatedOrders' => 'Comenzi reataşate',
		'OnProcessOrders' => 'Comenzi în curs de procesare',
		'RefOrder' => 'Ref. comanda',
		'RefCustomerOrder' => 'Ref. comandă client',
		'CustomerOrder' => 'Comandă clienţi',
		'RefCustomerOrderShort' => 'Ref. cmd. client',
		'SendOrderByMail' => 'Trimite  comanda prin e-mail',
		'ActionsOnOrder' => 'Acţiuni de pe comandă',
		'NoArticleOfTypeProduct' => 'Nici un articol de tip "produs" şi deci expediabil în această comandă  ',
		'OrderMode' => 'Metodă comandă',
		'AuthorRequest' => 'Autor cerere',
		'UseCustomerContactAsOrderRecipientIfExist' => 'Utilizaţi  adresa de contact client, dacă este definită la terţi ca adresa destinatarului comenzii',
		'RunningOrders' => 'Comenzi în curs',
		'UserWithApproveOrderGrant' => 'Utilizatori  responsabili cu  "aprobarea comenzilor" .',
		'PaymentOrderRef' => 'Plata comandă  %s',
		'CloneOrder' => 'Clonează comandă',
		'ConfirmCloneOrder' => 'Sunteţi sigur că doriţi să clonaţi această comandă <b> %s</b>  ?',
		'DispatchSupplierOrder' => 'Recepţia comenzii furnizorului %s',
		'DateDeliveryPlanned' => 'Date de livrare prevăzute',
		'SetDemandReason' => 'Definiţi originea comenzii',
		////////// Types de contacts //////////
		'TypeContact_commande_internal_SALESREPFOLL' => 'Responsabil urmărire comandă client ',
		'TypeContact_commande_internal_SHIPPING' => 'Responsabil trimitere comandă client',
		'TypeContact_commande_external_BILLING' => 'Clientul factura de contact',
		'TypeContact_commande_external_SHIPPING' => 'Contact client livrare comandă',
		'TypeContact_commande_external_CUSTOMER' => 'Contact client urmărire comandă',
		'TypeContact_order_supplier_internal_SALESREPFOLL' => 'Responsabil urmărire comandă  furnizor',
		'TypeContact_order_supplier_internal_SHIPPING' => 'Responsabil recepţie livrare  furnizor',
		'TypeContact_order_supplier_external_BILLING' => 'Contact comandă  factură furnizor',
		'TypeContact_order_supplier_external_SHIPPING' => 'Contact comandă  livrare furnizor',
		'TypeContact_order_supplier_external_CUSTOMER' => 'Contact responsabil comandă furnizor',
		'Error_COMMANDE_SUPPLIER_ADDON_NotDefined' => 'Constanta COMMANDE_SUPPLIER_ADDON nedefinită',
		'Error_COMMANDE_ADDON_NotDefined' => 'Constanta  COMMANDE_ADDON nedefinită',
		'Error_FailedToLoad_COMMANDE_SUPPLIER_ADDON_File' => 'Eşec la incărcarea modulului " %s"',
		'Error_FailedToLoad_COMMANDE_ADDON_File' => 'Eşec la incărcarea modulului " %s"',
		'Error_OrderNotChecked' => 'Nicio comandă pentru factura selectată',
		// Sources
		'OrderSource0' => 'Propunere  comercială',
		'OrderSource1' => 'Internet',
		'OrderSource2' => 'Campanie Mail ',
		'OrderSource3' => 'Campanie Telefonică',
		'OrderSource4' => 'Campanie Fax ',
		'OrderSource5' => 'Comercial',
		'OrderSource6' => 'Magazin',
		'QtyOrdered' => 'Cant comandată',
		'AddDeliveryCostLine' => 'Add a delivery cost line indicating the weight of the order',
		// Documents models
		'PDFEinsteinDescription' => 'Model  comandă complet (logo. ..)',
		'PDFEdisonDescription' => 'Model comandă simplu',
		// Orders modes
		'OrderByMail' => 'Corespondenţă',
		'OrderByFax' => 'Fax',
		'OrderByEMail' => 'EMail',
		'OrderByWWW' => 'Online',
		'OrderByPhone' => 'Telefon',
		'CreateInvoiceForThisCustomer' => 'Comeni facturate',
		'NoOrdersToInvoice' => 'Nicio comandă facturabilă',
		'CloseProcessedOrdersAutomatically' => 'Clasare automată  "Procesate" toate comenzile selectate.',
		'MenuOrdersToBill2' => 'Comenzi de facturat',
		'LinkedInvoices' => 'Facturi ataşate',
		'LinkedProposals' => 'Propuneri comerciale ataşate',
		'ShippingHT' => 'Shipping cost'
);
?>