<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Depozit carte',
		'Warehouse' => 'Warehouse',
		'Warehouses' => 'Warehouses',
		'NewWarehouse' => 'Nou depozit / zona de stoc',
		'WarehouseEdit' => 'Modificare depozit',
		'MenuNewWarehouse' => 'Nou depozit',
		'WarehouseOpened' => 'Warehouse deschis',
		'WarehouseClosed' => 'Depozit închis',
		'WarehouseSource' => 'Sursa de depozit',
		'WarehouseSourceNotDefined' => 'No warehouse defined,',
		'AddOne' => 'Add one',
		'WarehouseTarget' => 'Target antrepozit',
		'ValidateSending' => 'Ştergere trimiterea',
		'CancelSending' => 'Anulare expediere',
		'DeleteSending' => 'Ştergere trimiterea',
		'Stock' => 'Stoc',
		'Stocks' => 'Stocuri',
		'Movement' => 'Mişcarea',
		'Movements' => 'Mişcările',
		'ErrorWarehouseRefRequired' => 'Warehouse nume de referinţă este necesară',
		'ErrorWarehouseLabelRequired' => 'Warehouse etichetei este necesară',
		'CorrectStock' => 'Corect stoc',
		'ListOfWarehouses' => 'Lista de depozite',
		'ListOfStockMovements' => 'Lista de stoc mişcările',
		'StocksArea' => 'Stocuri zona',
		'Location' => 'Lieu',
		'LocationSummary' => 'Nume scurt locaţie',
		'NumberOfProducts' => 'Numărul total de produse',
		'LastMovement' => 'Ultima circulaţie',
		'LastMovements' => 'Ultima mişcările',
		'Units' => 'Unităţi',
		'Unit' => 'Unitatea de',
		'StockCorrection' => 'Corect stoc',
		'StockMovement' => 'Transfer',
		'StockMovements' => 'Transferuri de stoc',
		'NumberOfUnit' => 'Numărul de unităţi',
		'UnitPurchaseValue' => 'Unit purchase price',
		'TotalStock' => 'Total în stoc',
		'StockTooLow' => 'Stoc prea mică',
		'StockLowerThanLimit' => 'Stock lower than alert limit',
		'EnhancedValue' => 'Valoare',
		'PMPValue' => 'Valoare',
		'PMPValueShort' => 'WAP',
		'EnhancedValueOfWarehouses' => 'Depozite valoare',
		'UserWarehouseAutoCreate' => 'Creaţi un stoc în mod automat atunci când se creează un utilizator',
		'QtyDispatched' => 'Cantitate expediate',
		'OrderDispatch' => 'Ordinul de expediţie',
		'RuleForStockManagementDecrease' => 'Norma de management al stocurilor scădere',
		'RuleForStockManagementIncrease' => 'Norma de management al stocurilor creştere',
		'DeStockOnBill' => 'Reducerea real stocurile de pe facturi / note de credit',
		'DeStockOnValidateOrder' => 'Reducerea real stocurile de pe ordinele de note',
		'DeStockOnShipment' => 'Scăderea stocurilor reale privind transferurile de validare',
		'ReStockOnBill' => 'Creşterea reală stocurile de pe facturi / note de credit',
		'ReStockOnValidateOrder' => 'Creşterea reală stocurile de pe ordinele de note',
		'ReStockOnDispatchOrder' => 'Creşterea stocurilor real pe manualul de expediere în depozite, după ce furnizorul pentru primirea',
		'OrderStatusNotReadyToDispatch' => 'Ordinul nu a fost încă sau nu mai mult de un statut care permite trimiterea produselor în depozite stoc.',
		'StockDiffPhysicTeoric' => 'Motivul pentru stocul diferenţa fizice şi teoretice',
		'NoPredefinedProductToDispatch' => 'Nu exista produse predefinite pentru acest obiect. Deci, nu de expediere în stoc este necesară.',
		'DispatchVerb' => 'Expediere',
		'StockLimitShort' => 'Limita de',
		'StockLimit' => 'Stoc limită pentru alerte',
		'PhysicalStock' => 'Stocul fizic',
		'RealStock' => 'Real de stoc',
		'TheoreticalStock' => 'Therocial stoc',
		'VirtualStock' => 'Virtual stoc',
		'MininumStock' => 'Minim stoc',
		'StockUp' => 'Stoc sus',
		'MininumStockShort' => 'Stoc min',
		'StockUpShort' => 'Stoc sus',
		'IdWarehouse' => 'Id-ul antrepozit',
		'DescWareHouse' => 'Descriere antrepozit',
		'LieuWareHouse' => 'Localizare depozit',
		'WarehousesAndProducts' => 'Depozite şi produse',
		'AverageUnitPricePMPShort' => 'Preţul mediu de intrare',
		'AverageUnitPricePMP' => 'Preţul mediu de intrare',
		'SellPriceMin' => 'Preţul de vânzare unitatii',
		'EstimatedStockValueSellShort' => 'Valoarea de a vinde',
		'EstimatedStockValueSell' => 'Valoarea de a vinde',
		'EstimatedStockValueShort' => 'Valoare estimată de stoc',
		'EstimatedStockValue' => 'Valoare estimată de stoc',
		'DeleteAWarehouse' => 'Ştergeţi-un antrepozit',
		'ConfirmDeleteWarehouse' => 'Sunteţi sigur că doriţi să ştergeţi <b>%s</b> depozit?',
		'PersonalStock' => '%s personale stoc',
		'ThisWarehouseIsPersonalStock' => 'Acest depozit reprezinta stocul personale ale %s %s',
		'SelectWarehouseForStockDecrease' => 'Alege depozit utilizat pentru scăderea stocului',
		'SelectWarehouseForStockIncrease' => 'Alege depozit utilizat pentru creşterea stocului',
		'LastWaitingSupplierOrders' => 'Orders waiting for receptions'
);
?>