<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Fişă Depozit',
		'Warehouse' => 'Depozit',
		'Warehouses' => 'Depozite',
		'NewWarehouse' => 'Depozit / zona depozit nouă',
		'WarehouseEdit' => 'Modificare depozit',
		'MenuNewWarehouse' => 'Depozit nou',
		'WarehouseOpened' => 'Depozit deschis',
		'WarehouseClosed' => 'Depozit închis',
		'WarehouseSource' => 'Sursă depozit',
		'WarehouseSourceNotDefined' => 'Niciun depozit definit',
		'AddOne' => 'Adaugă unul',
		'WarehouseTarget' => 'Depozit ţintă',
		'ValidateSending' => 'Validaţi expediţia',
		'CancelSending' => 'Anulaţi expediţia',
		'DeleteSending' => 'Şterge expediţia',
		'Stock' => 'Stoc',
		'Stocks' => 'Stocuri',
		'Movement' => 'Transfer',
		'Movements' => 'Transferuri',
		'ErrorWarehouseRefRequired' => 'Referinţă  nume depozit este obligatoriu',
		'ErrorWarehouseLabelRequired' => 'Eticheta depozitului este obligatorie',
		'CorrectStock' => 'Corectare  stoc',
		'ListOfWarehouses' => 'Listă depozite',
		'ListOfStockMovements' => 'Lista transferuri',
		'StocksArea' => 'Zona Stocuri',
		'Location' => 'Locaţie',
		'LocationSummary' => 'Nume scurt locaţie',
		'NumberOfProducts' => 'Număr total de produse',
		'LastMovement' => 'Ultimul transfer',
		'LastMovements' => 'Ultimele transferuri',
		'Units' => 'Unităţi',
		'Unit' => 'Unitate',
		'StockCorrection' => 'Corecţie stoc',
		'StockMovement' => 'Transfer',
		'StockMovements' => 'Transferuri de stoc',
		'NumberOfUnit' => 'Număr  unităţi',
		'UnitPurchaseValue' => 'Preţ unitar cumpărare',
		'TotalStock' => 'Total în stoc',
		'StockTooLow' => 'Stoc insuficient',
		'StockLowerThanLimit' => 'Stoc inferior limitei de alertă',
		'EnhancedValue' => 'Valoare',
		'PMPValue' => 'Valoare PMP',
		'PMPValueShort' => 'PMP',
		'EnhancedValueOfWarehouses' => 'Valoare depozit',
		'UserWarehouseAutoCreate' => 'Creaţi un stoc în mod automat atunci când se creează un utilizator',
		'QtyDispatched' => 'Cantitate expediate',
		'OrderDispatch' => 'Ordinul de expediţie',
		'RuleForStockManagementDecrease' => 'Norma de management al stocurilor scădere',
		'RuleForStockManagementIncrease' => 'Norma de management al stocurilor creştere',
		'DeStockOnBill' => 'Reducerea real stocurile de pe facturi / note de credit',
		'DeStockOnValidateOrder' => 'Reducerea real stocurile de pe ordinele de note',
		'DeStockOnShipment' => 'Scăderea stocurilor reale privind transferurile de validare',
		'ReStockOnBill' => 'Creşterea reală stocurile de pe facturi / note de credit',
		'ReStockOnValidateOrder' => 'Creşterea reală stocurile de pe ordinele de note',
		'ReStockOnDispatchOrder' => 'Creşterea stocurilor real pe manualul de expediere în depozite, după ce furnizorul pentru primirea',
		'OrderStatusNotReadyToDispatch' => 'Ordinul nu a fost încă sau nu mai mult de un statut care permite trimiterea produselor în depozite stoc.',
		'StockDiffPhysicTeoric' => 'Motivul pentru stocul diferenţa fizice şi teoretice',
		'NoPredefinedProductToDispatch' => 'Nu exista produse predefinite pentru acest obiect. Deci, nu de expediere în stoc este necesară.',
		'DispatchVerb' => 'Expediere',
		'StockLimitShort' => 'Limita de',
		'StockLimit' => 'Stoc limită pentru alerte',
		'PhysicalStock' => 'Stocul fizic',
		'RealStock' => 'Stocul real',
		'TheoreticalStock' => 'Stocul teoretic',
		'VirtualStock' => 'Stocul virtual ',
		'MininumStock' => 'Stocul  minim',
		'StockUp' => 'Stocul maxim',
		'MininumStockShort' => 'Stoc min',
		'StockUpShort' => 'Stoc max',
		'IdWarehouse' => 'Id depozit',
		'DescWareHouse' => 'Descriere depozit',
		'LieuWareHouse' => 'Localizare depozit',
		'WarehousesAndProducts' => 'Depozite şi produse',
		'AverageUnitPricePMPShort' => 'Preţul mediu ponderat',
		'AverageUnitPricePMP' => 'Preţul mediu de achiziţie',
		'SellPriceMin' => 'Preţ  vânzare unitar',
		'EstimatedStockValueSellShort' => 'Valoare  vânzare',
		'EstimatedStockValueSell' => 'Valoare vănzare',
		'EstimatedStockValueShort' => 'Valoare  intrare stoc',
		'EstimatedStockValue' => 'Valoare  intrare stoc',
		'DeleteAWarehouse' => 'Ştergeţi depozit',
		'ConfirmDeleteWarehouse' => 'Sunteţi sigur că doriţi să ştergeţi depozitul <b>%s</b> ?',
		'PersonalStock' => 'Personal stoc %s',
		'ThisWarehouseIsPersonalStock' => 'Acest depozit reprezintă stocul personal al %s %s',
		'SelectWarehouseForStockDecrease' => 'Alege depozitul utilizat pentru scăderea stocului',
		'SelectWarehouseForStockIncrease' => 'Alege depozitul  utilizat pentru creşterea stocului',
		'LastWaitingSupplierOrders' => 'Comenzi în aşteptarea recepţiei'
);
?>