<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Depozit carte',
		'Warehouse' => 'Warehouse',
		'NewWarehouse' => 'Nou depozit / zona de stoc',
		'MenuNewWarehouse' => 'Nou depozit',
		'WarehouseOpened' => 'Warehouse deschis',
		'WarehouseClosed' => 'Depozit închis',
		'WarehouseSource' => 'Sursa de depozit',
		'WarehouseTarget' => 'Target antrepozit',
		'ValidateSending' => 'Ştergere trimiterea',
		'CancelSending' => 'Anulare expediere',
		'DeleteSending' => 'Ştergere trimiterea',
		'Stock' => 'Stoc',
		'Stocks' => 'Stocuri',
		'Movement' => 'Mişcarea',
		'Movements' => 'Mişcările',
		'ErrorWarehouseRefRequired' => 'Warehouse nume de referinţă este necesară',
		'ErrorWarehouseLabelRequired' => 'Warehouse etichetei este necesară',
		'CorrectStock' => 'Corect stoc',
		'ListOfWarehouses' => 'Lista de depozite',
		'ListOfStockMovements' => 'Lista de stoc mişcările',
		'StocksArea' => 'Stocuri zona',
		'Location' => 'Lieu',
		'LocationSummary' => 'Nume scurt locaţie',
		'NumberOfProducts' => 'Numărul total de produse',
		'LastMovement' => 'Ultima circulaţie',
		'LastMovements' => 'Ultima mişcările',
		'Units' => 'Unităţi',
		'Unit' => 'Unitatea de',
		'StockCorrection' => 'Corect stoc',
		'StockMovement' => 'Transfer',
		'StockMovements' => 'Transferuri de stoc',
		'NumberOfUnit' => 'Numărul de unităţi',
		'TotalStock' => 'Total în stoc',
		'StockTooLow' => 'Stoc prea mică',
		'EnhancedValue' => 'Valoare',
		'PMPValue' => 'Valoare',
		'EnhancedValueOfWarehouses' => 'Depozite valoare',
		'UserWarehouseAutoCreate' => 'Creaţi un stoc în mod automat atunci când se creează un utilizator',
		'QtyDispatched' => 'Cantitate expediate',
		'OrderDispatch' => 'Ordinul de expediţie',
		'RuleForStockManagementDecrease' => 'Norma de management al stocurilor scădere',
		'RuleForStockManagementIncrease' => 'Norma de management al stocurilor creştere',
		'DeStockOnBill' => 'Reducerea real stocurile de pe facturi / note de credit',
		'DeStockOnValidateOrder' => 'Reducerea real stocurile de pe ordinele de note',
		'ReStockOnBill' => 'Creşterea reală stocurile de pe facturi / note de credit',
		'ReStockOnValidateOrder' => 'Creşterea reală stocurile de pe ordinele de note',
		'StockLimitShort' => 'Limita de',
		'StockLimit' => 'Stoc limită pentru alerte',
		'PhysicalStock' => 'Stocul fizic',
		'RealStock' => 'Real de stoc',
		'TheoreticalStock' => 'Therocial stoc',
		'VirtualStock' => 'Virtual stoc',
		'MininumStock' => 'Minim stoc',
		'StockUp' => 'Stoc sus',
		'MininumStockShort' => 'Stoc min',
		'StockUpShort' => 'Stoc sus',
		'IdWarehouse' => 'Id-ul antrepozit',
		'DescWareHouse' => 'Descriere antrepozit',
		'LieuWareHouse' => 'Localizare depozit',
		'WarehousesAndProducts' => 'Depozite şi produse',
		'PMPValueShort' => 'WAP',
		'AverageUnitPricePMPShort' => 'Preţul mediu de intrare',
		'AverageUnitPricePMP' => 'Preţul mediu de intrare',
		'EstimatedStockValueShort' => 'Valoare estimată de stoc',
		'EstimatedStockValue' => 'Valoare estimată de stoc',
		'WarehouseEdit' => 'Modificare depozit',
		'DeStockOnShipment' => 'Scăderea stocurilor reale privind transferurile de validare',
		'ReStockOnDispatchOrder' => 'Creşterea stocurilor real pe manualul de expediere în depozite, după ce furnizorul pentru primirea',
		'OrderStatusNotReadyToDispatch' => 'Ordinul nu a fost încă sau nu mai mult de un statut care permite trimiterea produselor în depozite stoc.',
		'StockDiffPhysicTeoric' => 'Motivul pentru stocul diferenţa fizice şi teoretice',
		'NoPredefinedProductToDispatch' => 'Nu exista produse predefinite pentru acest obiect. Deci, nu de expediere în stoc este necesară.',
		'DispatchVerb' => 'Expediere',
		'DeleteAWarehouse' => 'Ştergeţi-un antrepozit',
		'ConfirmDeleteWarehouse' => 'Sunteţi sigur că doriţi să ştergeţi <b>%s</b> depozit?',
		'PersonalStock' => '%s personale stoc',
		'ThisWarehouseIsPersonalStock' => 'Acest depozit reprezinta stocul personale ale %s %s',
		'SellPriceMin' => 'Preţul de vânzare unitatii',
		'EstimatedStockValueSellShort' => 'Valoarea de a vinde',
		'EstimatedStockValueSell' => 'Valoarea de a vinde',
		'SelectWarehouseForStockDecrease' => 'Alege depozit utilizat pentru scăderea stocului',
		'SelectWarehouseForStockIncrease' => 'Alege depozit utilizat pentru creşterea stocului',
);
?>