<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'Fişă Utilizator ',
		'ContactCard' => 'Fişă Contact ',
		'GroupCard' => 'Fişă Grup',
		'NoContactCard' => 'Fără fişă printre contacte',
		'Permission' => 'Permisiune',
		'Permissions' => 'Permisiuni',
		'EditPassword' => 'Modificare parolă',
		'SendNewPassword' => 'Regenerare şi trimite parolă ',
		'ReinitPassword' => 'Regenerare parolă ',
		'PasswordChangedTo' => 'Parolă  schimbată la: %s',
		'SubjectNewPassword' => 'Noua  dvs parolă pentru Speedealing',
		'AvailableRights' => 'Permisiuni disponibile',
		'OwnedRights' => 'Permisiuni deţinute',
		'GroupRights' => 'Permisiuni grup',
		'UserRights' => 'Permisiuni utilizator',
		'UserGUISetup' => 'Configurare Intefaţă utilizator',
		'DisableUser' => 'Dezactivare',
		'DisableAUser' => 'Dezactivare utilizator',
		'DeleteUser' => 'Şterge',
		'DeleteAUser' => 'Şterge  utilizator',
		'DisableGroup' => 'Dezactivare',
		'DisableAGroup' => 'Dezactivare grup',
		'EnableAUser' => 'Activare utilizator',
		'EnableAGroup' => 'Activare grup',
		'DeleteGroup' => 'Şterge',
		'DeleteAGroup' => 'Şterge  grup',
		'ConfirmDisableUser' => 'Sunteţi sigur că doriţi să dezactivaţi utilizatorul  <b>%s</b> ?',
		'ConfirmDisableGroup' => 'Sunteţi sigur că doriţi să dezactivaţi grupul <b>%s</b> ?',
		'ConfirmDeleteUser' => 'Sunteţi sigur că doriţi să ştergeţi utilizatorul <b>%s?</b> ?',
		'ConfirmDeleteGroup' => 'Sunteţi sigur că doriţi să ştergeţi grupul <b> %s</b> ?',
		'ConfirmEnableUser' => 'Sunteţi sigur că doriţi să activaţi utilizatorul<b>%s</b>?',
		'ConfirmEnableGroup' => 'Sunteţi sigur că doriţi să activaţi grupul <b>%s</b>?',
		'ConfirmReinitPassword' => 'Sunteţi sigur că doriţi să generaţi o nouă parolă pentru utilizatorul <b>%s</b> ?',
		'ConfirmSendNewPassword' => 'Sunteţi sigur că doriţi să genereraţi  şi trimiteţi o noua parolă pentru utilizatorul <b> %s</b>?',
		'NewUser' => 'Utilizator nou',
		'CreateUser' => 'Creare utilizator',
		'SearchAGroup' => 'Căutare grup',
		'SearchAUser' => 'Căutare utilizator',
		'LoginNotDefined' => 'Login nu este definit.',
		'NameNotDefined' => 'Numele nu este definit.',
		'ListOfUsers' => 'Listă utilizatori',
		'Administrator' => 'Administrator',
		'SuperAdministrator' => 'Super Administrator',
		'SuperAdministratorDesc' => 'Administrator global',
		'AdministratorDesc' => 'Administrator  entitate',
		'DefaultRights' => 'Permisiuni implicite',
		'DefaultRightsDesc' => 'Definiţi aici  permisiunile <u>implicite</u> care sunt acordate în mod automat la crearea de <u>utilizator nou</u>. ( Vezi fişa utilizatorului pentru a schimba permisiile unui utilizator existent).',
		'SpeedealingUsers' => 'Utilizatori Speedealing ',
		'LastName' => 'Nume',
		'FirstName' => 'Prenume',
		'ListOfGroups' => 'Listă grupuri',
		'NewGroup' => 'Grup nou',
		'CreateGroup' => 'Creare grup',
		'RemoveFromGroup' => 'Şterge  grup',
		'PasswordChangedAndSentTo' => 'Parola schimbată şi trimisă la <b> %s</b>.',
		'PasswordChangeRequestSent' => 'Cerere pentru a schimba parola  pentru <b>%s</b> la trimisă la <b>%s</b>.',
		'MenuUsersAndGroups' => 'Utilizatori & Grupuri',
		'LastGroupsCreated' => 'Ultimele %s grupuri create',
		'LastUsersCreated' => 'Ultimii %s utilizatorii creţi',
		'ShowGroup' => 'Afişează grup',
		'ShowUser' => 'Afişează  utilizator',
		'NonAffectedUsers' => 'Utilizatori neafectaţi la grupuri',
		'UserModified' => 'Utilizator modificat cu succes',
		'GroupModified' => 'Grup modificat cu succes',
		'PhotoFile' => 'Fişier Foto ',
		'UserWithSpeedealingAccess' => 'Utilizatori cu acces Speedealing ',
		'ListOfUsersInGroup' => 'Listă utilizatori din acest grup',
		'ListOfGroupsForUser' => 'Listă de grupuri pentru acest utilizator',
		'UsersToAdd' => 'Utilizatorii de adăugat la acest grup',
		'GroupsToAdd' => 'Grupuri de adăugat la acest utilizator',
		'NoLogin' => 'Nu login',
		'LinkToCompanyContact' => 'Link  terţi  / contact',
		'LinkedToSpeedealingMember' => 'Link către membru',
		'LinkedToSpeedealingUser' => 'Link către utilizator Speedealing',
		'LinkedToSpeedealingThirdParty' => 'Link către terţ Speedealing ',
		'CreateSpeedealingLogin' => 'Creare utilizator',
		'CreateSpeedealingThirdParty' => 'Creare terţ',
		'LoginAccountDisable' => 'Cont dezactivat, pune un nou login pentru a activa.',
		'LoginAccountDisableInSpeedealing' => 'Cont dezactivat in Speedealing.',
		'LoginAccountDisableInLdap' => 'Cont dezactivat în domeniu.',
		'UsePersonalValue' => 'Utilizaţi valoari personale',
		'GuiLanguage' => 'Limbă Interfaţă ',
		'InternalUser' => 'Utilizator intern',
		'MyInformations' => 'Informaţiile mele',
		'ExportDataset_user_1' => 'Utilizatori  şi atribute Speedealing',
		'DomainUser' => 'Domeniu utilizatorului %s',
		'Reactivate' => 'Reactivaţi',
		'CreateInternalUserDesc' => 'Acest formular va permite sa creaţi un utilizator intern al companiei / fundaţiei dumneavoastră . Pentru a creat un utilizator extern (client, furnizor, ...), folosi butonul "Creaţi utilizator Speedealing " din fişa de contact a terţei părţi .',
		'InternalExternalDesc' => 'Un utilizator <b>intern</b> este un utilizator care este parte a firmei /fundaţiei dvs.  <br> Un utilizator <b>extern</b> este un client, furnizor sau de alt terţ. <br><br> În ambele cazuri, permisiunile definesc drepturile pe Speedealing, dar utilizatorii externi, poat avea un alt  meniu decât utilizatorii interni (a se vedea Acasă - Configurare - Afişare)',
		'PermissionInheritedFromAGroup' => 'Permisiune acordată deoarece moşteneşte de laun  grup al utilizatorului.',
		'Inherited' => 'Moştenit',
		'UserWillBeInternalUser' => 'Utilizatorul creat va fi un utilizator intern (pentru că nu e legat de o  terţă parte)',
		'UserWillBeExternalUser' => 'Utilizatorul creat va fi un utilizator extern (deoarece e  legat de o terţ special)',
		'IdPhoneCaller' => 'Id-ul apelului telefonic',
		'UserLogged' => 'Conectare utilizator %s ',
		'UserLogoff' => 'Deconectare utilizator %s',
		'NewUserCreated' => 'Creare utilizator %s',
		'NewUserPassword' => 'Schimbare parolă pentru %s',
		'EventUserModified' => 'Modificare utilizator %s ',
		'UserDisabled' => 'Dezactivare utilizator  %s ',
		'UserEnabled' => 'Activare utilizator %s ',
		'UserDeleted' => 'Eliminare utilizator  %s ',
		'NewGroupCreated' => 'Creare grup %s',
		'GroupModified' => 'Grup modificat cu succes',
		'GroupDeleted' => 'Eliminare grup %s',
		'ConfirmCreateContact' => 'Sunteţi sigur că doriţi să creaţi un cont Speedealing pentru acest contact?',
		'ConfirmCreateLogin' => 'Sunteţi sigur că doriţi să creaţi un cont  Speedealing  pentru acest membru?',
		'ConfirmCreateThirdParty' => 'Sunteţi sigur că doriţi să creaţi un terţ pentru acest membru?',
		'LoginToCreate' => 'Login de creat',
		'NameToCreate' => 'Nume terţ de creat',
		'YourRole' => 'Rolurile dvs.',
		'YourQuotaOfUsersIsReached' => 'Cota dvs. de utilizatori activi este atinsă!',
		'NbOfUsers' => 'Nr utilizatori',
		'DontDowngradeSuperAdmin' => 'Numai un superadmin poate degrada un superadmin',
		'NewDatabase' => 'Baza de date nouă',
		'CreateDatabase' => 'Creare bază de date',
		'ListOfDatabases' => 'Listă baze de date',
		'ListOfUsersInDatabase' => 'Listă utilizatori legaţi la baza de date',
		'ListOfRolesInDatabase' => 'Listă  groupuri legate la baza de date',
		'DeleteADatabase' => 'Ştergere baza de date',
		'ConfirmDatabase' => 'Sunteţi sigur că doriţi ştergerea bazei de date <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Grupuri  neafectate la baza de date',
		'NonAffectedUsersDatabase' => 'Utilizatori neaffectaţi la baza de date',
		'Collaborators' => 'Colaboratori',
		'Profiles' => 'Profile colaboratori'
);
?>