<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'Utilizator carte',
		'ContactCard' => 'Contact carte',
		'GroupCard' => 'Grupul de carte',
		'NoContactCard' => 'Nu carte între persoane de contact',
		'Permission' => 'Permission',
		'Permissions' => 'Permisiuni',
		'EditPassword' => 'Modificarea parolei',
		'SendNewPassword' => 'Trimite o parolă nouă',
		'ReinitPassword' => 'Genera o parolă nouă',
		'PasswordChangedTo' => 'Parola schimbat la: %s',
		'SubjectNewPassword' => 'Parola nouă pentru Speedealing',
		'AvailableRights' => 'Disponibil permisiunile',
		'OwnedRights' => 'Owned permisiunile',
		'GroupRights' => 'Grupul de permisiuni',
		'UserRights' => 'Permisiunile de utilizator',
		'UserGUISetup' => 'Afişa utilizatorului setup',
		'DisableUser' => 'Dezactiva',
		'DisableAUser' => 'Dezactivaţi un utilizator',
		'DeleteUser' => 'Şterge',
		'DeleteAUser' => 'A şterge un utilizator',
		'DisableGroup' => 'Dezactiva',
		'DisableAGroup' => 'Dezactivaţi un grup',
		'EnableAUser' => 'Permite unui utilizator',
		'EnableAGroup' => 'Activaţi un grup',
		'DeleteGroup' => 'Şterge',
		'DeleteAGroup' => 'Ştergeţi un grup',
		'ConfirmDisableUser' => 'Sunteţi sigur că doriţi să dezactivaţi <b>utilizator %s?</b>',
		'ConfirmDisableGroup' => 'Sunteţi sigur că doriţi să dezactivaţi <b>grup %s?</b>',
		'ConfirmDeleteUser' => 'Sunteţi sigur că doriţi să ştergeţi <b>utilizatorul %s?</b>',
		'ConfirmDeleteGroup' => 'Sunteţi sigur că doriţi să ştergeţi <b>grup %s?</b>',
		'ConfirmEnableUser' => 'Sunteţi sigur că doriţi, pentru a permite <b>utilizatorului %s?</b>',
		'ConfirmEnableGroup' => 'Sunteţi sigur că doriţi să activaţi <b>grup %s?</b>',
		'ConfirmReinitPassword' => 'Sunteţi sigur că doriţi pentru a genera o nouă parolă pentru <b>utilizatorul %s?</b>',
		'ConfirmSendNewPassword' => 'Sunteţi sigur că doriţi să genereze şi trimite noua parolă pentru <b>utilizatorul %s?</b>',
		'NewUser' => 'Utilizator nou',
		'CreateUser' => 'Creaţi utilizator',
		'SearchAGroup' => 'Cauta un grup',
		'SearchAUser' => 'Caută un utilizator',
		'LoginNotDefined' => 'Login nu este definit.',
		'NameNotDefined' => 'Numele nu este definit.',
		'ListOfUsers' => 'Lista de utilizatori',
		'Administrator' => 'Administrator',
		'SuperAdministrator' => 'Super Administrator',
		'SuperAdministratorDesc' => 'Administrator, cu toate drepturile',
		'AdministratorDesc' => 'Administrator de entitate',
		'DefaultRights' => 'Implicit permisiunile',
		'DefaultRightsDesc' => 'Definiţi aici implicit permisiuni care sunt acordate în mod automat la un nou create de utilizator.',
		'SpeedealingUsers' => 'Speedealing users',
		'LastName' => 'Nume',
		'FirstName' => 'Prenume',
		'ListOfGroups' => 'Lista de grupuri',
		'NewGroup' => 'Grup nou',
		'CreateGroup' => 'Creaţi grup',
		'RemoveFromGroup' => 'Înlăturaţi din grup',
		'PasswordChangedAndSentTo' => 'Parola schimbat şi a trimis <b>la %s.</b>',
		'PasswordChangeRequestSent' => 'Cerere pentru a schimba parola <b>pentru %s %s</b> la trimis.',
		'MenuUsersAndGroups' => 'Utilizatorii & Grupuri',
		'LastGroupsCreated' => 'Ultima %s creat grupuri',
		'LastUsersCreated' => 'Ultima %s utilizatorii creat',
		'ShowGroup' => 'Arata grup',
		'ShowUser' => 'Arata utilizator',
		'NonAffectedUsers' => 'Non afectate utilizatori',
		'UserModified' => 'Utilizator modificate cu succes',
		'GroupModified' => 'Grupul modificate cu succes',
		'PhotoFile' => 'Foto fişier',
		'UserWithSpeedealingAccess' => 'User with Speedealing access',
		'ListOfUsersInGroup' => 'Lista de utilizatori în acest grup',
		'ListOfGroupsForUser' => 'Lista de grupuri pentru acest utilizator',
		'UsersToAdd' => 'Utilizatorii de adăugat la acest grup',
		'GroupsToAdd' => 'Grupuri pentru a adăuga la acest utilizator',
		'NoLogin' => 'Nu login',
		'LinkToCompanyContact' => 'Link către o terţă parte / de contact',
		'LinkedToSpeedealingMember' => 'Link to member',
		'LinkedToSpeedealingUser' => 'Link to Speedealing user',
		'LinkedToSpeedealingThirdParty' => 'Link to Speedealing third party',
		'CreateSpeedealingLogin' => 'Create a user',
		'CreateSpeedealingThirdParty' => 'Create a third party',
		'LoginAccountDisable' => 'Cont dezactivat, pune un nou login pentru a activa.',
		'LoginAccountDisableInSpeedealing' => 'Account disabled in Speedealing.',
		'LoginAccountDisableInLdap' => 'Cont dezactivat în domeniu.',
		'UsePersonalValue' => 'Utilizaţi valoarea personale',
		'GuiLanguage' => 'Interfaţă limba',
		'InternalUser' => 'Interne de utilizator',
		'MyInformations' => 'Mea de date',
		'ExportDataset_user_1' => 'Speedealing utilizatorii şi proprietăţi',
		'DomainUser' => 'Domeniu utilizatorul %s',
		'Reactivate' => 'Reactivaţi',
		'CreateInternalUserDesc' => 'Acest formular va permite sa creat un utilizator internă a companiei dumneavoastră / Fundaţia. Pentru a creat un utilizator extern (client, furnizor, ...), folosi butonul "Creaţi Speedealing utilizator" de la o terţă parte de contact ale carte.',
		'InternalExternalDesc' => 'Un utilizator <b>intern</b> este un utilizator care este parte a firmei dvs. / Fundaţia. <br> Un utilizator <b>extern</b> este un client, furnizor sau de altă parte. <br><br> În ambele cazuri, permissions defineşte drepturile pe Speedealing, externe, de asemenea, utilizatorul poate avea un alt administrator de meniu decât utilizator intern (a se vedea Home - Setup - Display)',
		'PermissionInheritedFromAGroup' => 'Permisiunea acordată deoarece moştenită de la un utilizator al unui grup.',
		'Inherited' => 'Moştenit',
		'UserWillBeInternalUser' => 'De utilizator creat va fi un utilizator intern (pentru că nu este legată de o parte terţă)',
		'UserWillBeExternalUser' => 'De utilizator creat va fi un utilizator extern (deoarece legat de un terţ special)',
		'IdPhoneCaller' => 'Id-ul telefonului apelantului',
		'UserLogged' => 'User %s conectat',
		'UserLogoff' => '%s utilizator logout',
		'NewUserCreated' => 'User %s create',
		'NewUserPassword' => 'Schimba parola pentru %s',
		'EventUserModified' => 'User %s modificate',
		'UserDisabled' => 'User %s cu handicap',
		'UserEnabled' => 'User %s activat',
		'UserDeleted' => 'User %s eliminat',
		'NewGroupCreated' => 'Grupul creat %s',
		'GroupModified' => 'Grupul modificate cu succes',
		'GroupDeleted' => 'Grupul %s eliminat',
		'ConfirmCreateContact' => 'Yu Sunteţi sigur că doriţi să creaţi un cont pentru acest Speedealing de contact?',
		'ConfirmCreateLogin' => 'Sunteţi sigur că doriţi să creaţi un cont pentru acest Speedealing membru?',
		'ConfirmCreateThirdParty' => 'Sunteţi sigur că doriţi să creaţi o terţă parte pentru acest stat?',
		'LoginToCreate' => 'Login pentru a crea',
		'NameToCreate' => 'Nume de terţă parte pentru a crea',
		'YourRole' => 'Dvs. de roluri',
		'YourQuotaOfUsersIsReached' => 'Cota dvs. de utilizatori activi este atins!',
		'NbOfUsers' => 'NB de utilizatori',
		'DontDowngradeSuperAdmin' => 'Numai un superadmin poate declasa un superadmin',
		'NewDatabase' => 'Nouvelle base de données',
		'CreateDatabase' => 'Créer la base de données',
		'ListOfDatabases' => 'Liste des bases de données',
		'ListOfUsersInDatabase' => 'Liste des utilisateurs liés à la base de données',
		'ListOfRolesInDatabase' => 'Liste des groupes liés à la base de données',
		'DeleteADatabase' => 'Suppression d\'une database',
		'ConfirmDatabase' => 'Êtes-vous sûr de vouloir supprimer la base de données <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Groupes non affectés à la base de données',
		'NonAffectedUsersDatabase' => 'Utilisateurs non affectés à la base de données',
		'Collaborators' => 'Collaborateurs',
		'Profiles' => 'Profils collaborateurs'
);
?>