<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Categoria',
		'Categories' => 'categories',
		'Rubrique' => 'Carpeta',
		'Rubriques' => 'Carpetes',
		'categories' => 'Categoria(es)',
		'TheCategorie' => 'La categoria',
		'NoCategoryYet' => 'Cap categoria d\'aquest tipus creada',
		'In' => 'En',
		'AddIn' => 'Afegir en',
		'modify' => 'Modificar',
		'Classify' => 'Classificar',
		'CategoriesArea' => 'Àrea categories',
		'ProductsCategoriesArea' => 'Àrea categories de productes i serveis',
		'SuppliersCategoriesArea' => 'Àrea categories de proveïdors',
		'CustomersCategoriesArea' => 'Àrea categories de clients',
		'ThirdPartyCategoriesArea' => 'Àrea categories de tercers',
		'MembersCategoriesArea' => 'Àrea categories de membres',
		'MainCats' => 'Categories principals',
		'SubCats' => 'Subcategories',
		'CatStatistics' => 'Estadístiques',
		'CatList' => 'Llista de categories',
		'AllCats' => 'Totes les categories',
		'ViewCat' => 'Veure la categoria',
		'NewCat' => 'Nova categoria',
		'NewCategory' => 'Nova categoria',
		'ModifCat' => 'Modificar una categoria',
		'CatCreated' => 'Categoria creada',
		'CreateCat' => 'Afegir una categoria',
		'CreateThisCat' => 'Afegir aquesta categoria',
		'ValidateFields' => 'Validar els camps',
		'NoSubCat' => 'Aquesta categoria no  conté cap subcategoria',
		'SubCatOf' => 'Subcategories',
		'FoundCats' => 'Categories trobades',
		'FoundCatsForName' => 'Categories trobades amb el nom:',
		'FoundSubCatsIn' => 'Subcategories trobades en  la categoria',
		'ErrSameCatSelected' => 'Heu seleccionat la mateixa categoria diverses vegades',
		'ErrForgotCat' => 'Ha oblidat escollir la categoria',
		'ErrForgotField' => 'Ha oblidat reassignar un camp',
		'ErrCatAlreadyExists' => 'Aquest nom està sent utilitzat',
		'AddProductToCat' => 'Afegir aquest producte a una categoria?',
		'ImpossibleAddCat' => 'Impossible afegir la categoria',
		'ImpossibleAssociateCategory' => 'Impossible associar la categoria',
		'WasAddedSuccessfully' => 's\'ha afegit amb èxit.',
		'ObjectAlreadyLinkedToCategory' => 'L\'element ja està enllaçat a aquesta categoria',
		'CategorySuccessfullyCreated' => 'La categoria %s s\'ha inserit correctament.',
		'ProductIsInCategories' => 'Aquest producte/servei es troba en les següents categories',
		'SupplierIsInCategories' => 'Aquest proveïdor es troba en les següents categories',
		'CompanyIsInCustomersCategories' => 'Aquesta empresa es troba en les següents categories',
		'CompanyIsInSuppliersCategories' => 'Aquesta empresa es troba en les següents categories de proveïdors',
		'MemberIsInCategories' => 'Aquest membre es troba en les següents categories de membres',
		'ProductHasNoCategory' => 'Aquest producte/servei no es troba en cap categoria en particular',
		'SupplierHasNoCategory' => 'Aquest proveïdor no es troba en cap categoria en particular',
		'CompanyHasNoCategory' => 'Aquesta empresa no es troba en cap categoria en particular',
		'MemberHasNoCategory' => 'Aquest membre no es troba en cap categoria en particular',
		'ClassifyInCategory' => 'Classificar en la categoria',
		'NoneCategory' => 'Cap',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Aquesta categoria ja existeix per aquesta referència',
		'ReturnInProduct' => 'Tornar a la fitxa producte/servei',
		'ReturnInSupplier' => 'Tornar a la fitxa proveïdor',
		'ReturnInCompany' => 'Tornar a la fitxa client/client potencial',
		'ContentsVisibleByAll' => 'El contingut serà visible per tots',
		'ContentsVisibleByAllShort' => 'Contingut visible per tots',
		'ContentsNotVisibleByAllShort' => 'Contingut no visible per tots',
		'CategoriesTree' => 'Arbre de categories',
		'DeleteCategory' => 'Eliminar categoria',
		'ConfirmDeleteCategory' => 'Esteu segur de voler eliminar aquesta categoria?',
		'RemoveFromCategory' => 'Suprimir l\'enllaç amb categoria',
		'RemoveFromCategoryConfirm' => 'Esteu segur de voler eliminar el vincle entre la transacció i la categoria?',
		'NoCategoriesDefined' => 'Cap categoria definida',
		'SuppliersCategoryShort' => 'Categoria proveïdors',
		'CustomersCategoryShort' => 'Categoria clients',
		'ProductsCategoryShort' => 'Categoria productes',
		'MembersCategoryShort' => 'Categoria membre',
		'SuppliersCategoriesShort' => 'Categories proveïdors',
		'CustomersCategoriesShort' => 'Categories clients',
		'CustomersProspectsCategoriesShort' => 'Categories clients/potencials',
		'ProductsCategoriesShort' => 'Categories productes',
		'MembersCategoriesShort' => 'Categories membres',
		'ThisCategoryHasNoProduct' => 'Aquesta categoria no conté cap producte.',
		'ThisCategoryHasNoSupplier' => 'Aquesta categoria no conté cap proveïdor.',
		'ThisCategoryHasNoCustomer' => 'Aquesta categoria no conté cap client.',
		'ThisCategoryHasNoMember' => 'Aquesta categoria no té cap membre.',
		'AssignedToCustomer' => 'Assignar a un client',
		'AssignedToTheCustomer' => 'Assignat a un client',
		'InternalCategory' => 'Categoria interna',
		'CategoryContents' => 'Contingut de la categoria',
		'CategId' => 'Id categoria',
		'CatSupList' => 'Llista de categories de proveïdors',
		'CatCusList' => 'Llista de categories de clients/potencials',
		'CatProdList' => 'Llista de categories de productes',
		'CatMemberList' => 'Llista de categories de membres',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>