<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Comercial',
		'CommercialArea' => 'Àrea comercial',
		'CommercialCard' => 'Fitxa comercial',
		'CustomerArea' => 'Àrea clients',
		'Customer' => 'Client',
		'Customers' => 'Clients',
		'Prospect' => 'Client potencial',
		'Prospects' => 'Clients potencials',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Eliminar un esdeveniment',
		'NewAction' => 'Nou esdeveniment',
		'AddAction' => 'Crear esdeveniment',
		'AddAnAction' => 'Crear un esdeveniment',
		'AddActionRendezVous' => 'Crear una cita',
		'Rendez-Vous' => 'Cita',
		'ConfirmDeleteAction' => 'Esteu segur de voler eliminar aquest esdeveniment?',
		'CardAction' => 'Fitxa esdeveniment',
		'PercentDone' => 'Percentatge realitzat',
		'ActionOnCompany' => 'Esdeveniment concernent a l\'empresa',
		'ActionOnContact' => 'Esdeveniment concernent al contacte',
		'TaskRDV' => 'Cita',
		'TaskRDVWith' => 'Cita amb %s',
		'ShowTask' => 'Veure tasca',
		'ShowAction' => 'Veure esdeveniment',
		'ActionsReport' => 'Informe d\'esdeveniments',
		'ThirdPartiesOfSaleRepresentative' => 'Tercers on el representant de vendes és',
		'SalesRepresentative' => 'Comercial',
		'SalesRepresentatives' => 'Comercials',
		'SalesRepresentativeFollowUp' => 'Comercial (seguiment)',
		'SalesRepresentativeSignature' => 'Comercial (firma)',
		'CommercialInterlocutor' => 'Interlocutor comercial',
		'ErrorWrongCode' => 'Codi incorrecte',
		'NoSalesRepresentativeAffected' => 'Cap comercial afectat',
		'ShowCustomer' => 'Veure client',
		'ShowProspect' => 'Veure clients potencials',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Llista de clients potencials',
		'ListOfCustomers' => 'Llista de clients',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'Les %s últimes accions efectuades',
		'LastRecordedTasks' => 'Darrers esdeveniments registrats',
		'LastActionsToDo' => 'Les %s últimes accions no acabades',
		'DoneAndToDoActionsFor' => 'Llista d\'esdeveniments realitzats o a realitzar per %s',
		'DoneAndToDoActions' => 'Llista d\'esdeveniments realitzats o a realitzar',
		'DoneActions' => 'Llista d\'esdeveniments realitzats',
		'DoneActionsFor' => 'Llista d\'esdeveniments realitzats per %s',
		'ToDoActions' => 'Llista d\'esdevenimentss incomplets',
		'ToDoActionsFor' => 'Llista d\'esdeveniments incomplets %s',
		'SendPropalRef' => 'Enviament del pressupost %s',
		'SendOrderRef' => 'Enviament de la comanda %s',
		'StatusNotApplicable' => 'No aplicable',
		'StatusActionToDo' => 'A realitzar',
		'StatusActionDone' => 'Realitzat',
		'StatusActionInProcess' => 'En curs',
		'MyActionsAsked' => 'Esdeveniments que he registrat',
		'MyActionsToDo' => 'Esdeveniments que he de fer',
		'MyActionsDone' => 'Esdeveniments que m\'afecten',
		'TasksHistoryForThisContact' => 'Esdeveniments respecte al contacte',
		'LastProspectDoNotContact' => 'No contactar',
		'LastProspectNeverContacted' => 'No contactat',
		'LastProspectToContact' => 'A contactar',
		'LastProspectContactInProcess' => 'Contacte en curs',
		'LastProspectContactDone' => 'Clients potencials contactats',
		'DateActionPlanned' => 'Data planificació',
		'DateActionDone' => 'Data realització',
		'ActionAskedBy' => 'Acció registrada per',
		'ActionAffectedTo' => 'Acció assignada a',
		'ActionDoneBy' => 'Acció realitzada per',
		'ActionUserAsk' => 'Registrada per',
		'ErrorStatusCantBeZeroIfStarted' => 'Si el camp \'<b>Data de realització</b>\' conté dades l\'acció està en curs, per la qual cosa el camp \'Estat\' no pot ser 0%%.',
		'ActionAC_TEL' => 'Trucada telefònica',
		'ActionAC_FAX' => 'Enviament Fax',
		'ActionAC_PROP' => 'Enviament pressupost per correu',
		'ActionAC_EMAIL' => 'Enviament E-Mail',
		'ActionAC_RDV' => 'Cita',
		'ActionAC_FAC' => 'Enviament factura a client per correu',
		'ActionAC_REL' => 'Recordatori factura a client per correu',
		'ActionAC_CLO' => 'Tancament',
		'ActionAC_EMAILING' => 'Enviament mailing massiu',
		'ActionAC_COM' => 'Enviament comanda de client per correu',
		'ActionAC_SHIP' => 'Enviament expedició per correu',
		'ActionAC_SUP_ORD' => 'Enviament comanda a proveïdor per correu',
		'ActionAC_SUP_INV' => 'Enviament factura de proveïdor per correu',
		'ActionAC_OTH' => 'Altra',
		'Stats' => 'Estadístiques de venda',
		'CAOrder' => 'Volum de vendes (Comandes validades)',
		'FromTo' => 'de %s a %s',
		'MargeOrder' => 'Marges (Comandes validades)',
		'RecapAnnee' => 'Recapitulació de l\'any',
		'NoData' => 'No hi ha dades',
		'StatusProsp' => 'Estat prospecció',
		'DraftPropals' => 'Pressupostos esborrany',
		'SearchPropal' => 'Cercar un pressupost'
);
?>