<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$orders = array(
		'CHARSET' => 'UTF-8',
		'OrdersArea' => 'Àrea comandes de clients',
		'SuppliersOrdersArea' => 'Àrea comandes a proveïdors',
		'OrderCard' => 'Fitxa comanda',
		'OrderId' => 'Id comanda',
		'Order' => 'Comanda',
		'Orders' => 'Comandes',
		'OrderLine' => 'Línia de comanda',
		'OrderLines' => 'Order lines',
		'OrderFollow' => 'Seguiment',
		'OrderDate' => 'Data comanda',
		'OrderToProcess' => 'Comanda a processar',
		'NewOrder' => 'Nova comanda',
		'ToOrder' => 'Realitzar comanda',
		'MakeOrder' => 'Realitzar comanda',
		'SupplierOrder' => 'Comanda a proveïdor',
		'SuppliersOrders' => 'Comandes a proveïdors',
		'SuppliersOrdersRunning' => 'Comandes a proveïdors en curs',
		'CustomerOrder' => 'Comada de client',
		'CustomersOrders' => 'Comandes de clients',
		'CustomersOrdersRunning' => 'Comandes de clients en curs',
		'CustomersOrdersAndOrdersLines' => 'Comandes de clients i línies de comanda',
		'OrdersToValid' => 'Comandes de clients a validar',
		'OrdersToBill' => 'Comandes de clients a facturar',
		'OrdersInProcess' => 'Comandes de clients en procés',
		'OrdersToProcess' => 'Comandes de clients a processar',
		'SuppliersOrdersToProcess' => 'Comandes a proveïdors a processar',
		'StatusOrderCanceledShort' => 'Anul·lada',
		'StatusOrderDraftShort' => 'Esborrany',
		'StatusOrderValidatedShort' => 'Validada',
		'StatusOrderSentShort' => 'Expedició en curs',
		'StatusOrderSent' => 'Enviament en curs',
		'StatusOrderOnProcessShort' => 'Per rebre',
		'StatusOrderProcessedShort' => 'Processada',
		'StatusOrderToBillShort' => 'A facturar',
		'StatusOrderToBill2Short' => 'To bill',
		'StatusOrderApprovedShort' => 'Aprovada',
		'StatusOrderRefusedShort' => 'Rebutjada',
		'StatusOrderToProcessShort' => 'A processar',
		'StatusOrderReceivedPartiallyShort' => 'Rebuda parcialment',
		'StatusOrderReceivedAllShort' => 'Rebuda',
		'StatusOrderCanceled' => 'Anul-lada',
		'StatusOrderDraft' => 'Esborrany (a validar)',
		'StatusOrderValidated' => 'Validada',
		'StatusOrderOnProcess' => 'Pendent de rebre',
		'StatusOrderProcessed' => 'Processada',
		'StatusOrderToBill' => 'A facturar',
		'StatusOrderToBill2' => 'To bill',
		'StatusOrderApproved' => 'Aprovada',
		'StatusOrderRefused' => 'Rebutjada',
		'StatusOrderReceivedPartially' => 'Rebuda parcialment',
		'StatusOrderReceivedAll' => 'Rebuda',
		'ShippingExist' => 'Existeix una expedició',
		'DraftOrWaitingApproved' => 'Esborrany o aprovat encara no controlat',
		'DraftOrWaitingShipped' => 'Esborrany o validada encara no expedida',
		'MenuOrdersToBill' => 'Comandes a facturar',
		'MenuOrdersToBill2' => 'Comandes facturables',
		'SearchOrder' => 'Cercar una comanda',
		'Sending' => 'Enviament',
		'Sendings' => 'Enviaments',
		'ShipProduct' => 'Enviar producte',
		'Discount' => 'Descompte',
		'CreateOrder' => 'Crear comanda',
		'RefuseOrder' => 'Rebutjar la comanda',
		'ApproveOrder' => 'Acceptar la comanda',
		'ValidateOrder' => 'Validar la comanda',
		'UnvalidateOrder' => 'Desvalidar la comanda',
		'DeleteOrder' => 'Eliminar la comanda',
		'CancelOrder' => 'Anul·lar la comanda',
		'AddOrder' => 'Crear comanda',
		'AddToMyOrders' => 'afegir a les meves comandes',
		'AddToOtherOrders' => 'Afegir a altres comandes',
		'ShowOrder' => 'Mostrar comanda',
		'NoOpenedOrders' => 'Cap comanda esborrany',
		'NoOtherOpenedOrders' => 'Cap altra comanda esborrany',
		'OtherOrders' => 'Altres comandes',
		'LastOrders' => 'Les %s darreres comandes',
		'LastModifiedOrders' => 'Les %s darreres comandes modificades',
		'LastClosedOrders' => 'Les %s darreres comandes tancades',
		'AllOrders' => 'Totes les comandes',
		'NbOfOrders' => 'Nombre de comandes',
		'OrdersStatistics' => 'Estadístiques de comandes',
		'OrdersStatisticsSuppliers' => 'Estadístiques de comandes a proveïdors',
		'NumberOfOrdersByMonth' => 'Nombre de comandes per mes',
		'AmountOfOrdersByMonthHT' => 'Import total de comandes per mes (Sense IVA)',
		'ListOfOrders' => 'Llistat de comandes',
		'CloseOrder' => 'Tancar comanda',
		'ConfirmCloseOrder' => 'Esteu segur de voler tancar aquesta comanda? Un cop tancat, haurà de facturar-se',
		'ConfirmCloseOrderIfSending' => 'Esteu segur de voler tancar aquesta comanda? No ha de tancar una comanda que encara no té els seus productes enviats',
		'ConfirmDeleteOrder' => 'Esteu segur de voler eliminar aquest comanda?',
		'ConfirmValidateOrder' => 'Esteu segur de voler validar aquesta comanda sota la referència <b>%s</b> ?',
		'ConfirmUnvalidateOrder' => 'Esteu segur de voler restaurar la comanda <b>%s</b> a l\'estat esborrany?',
		'ConfirmCancelOrder' => 'Esteu segur de voler anul lar aquesta comanda?',
		'ConfirmMakeOrder' => 'Esteu segur de voler confirmar aquest comanda a data de <b>%s</b> ?',
		'GenerateBill' => 'Facturar',
		'ClassifyShipped' => 'Classificar enviat',
		'ClassifyBilled' => 'Classificar facturat',
		'ComptaCard' => 'Fitxa comptable',
		'DraftOrders' => 'Comandes esborrany',
		'RelatedOrders' => 'Comandes adjuntes',
		'OnProcessOrders' => 'Comandes en procés',
		'RefOrder' => 'Ref. comanda',
		'RefCustomerOrder' => 'Ref. comanda client',
		'CustomerOrder' => 'Comada de client',
		'RefCustomerOrderShort' => 'Ref. com. client',
		'SendOrderByMail' => 'Enviar comanda per e-mail',
		'ActionsOnOrder' => 'Esdeveniments sobre la comanda',
		'NoArticleOfTypeProduct' => 'No hi ha articles de tipus \'producte\' i per tant enviables en aquesta comanda',
		'OrderMode' => 'Mètode de comanda',
		'AuthorRequest' => 'Autor/Sol·licitant',
		'UseCustomerContactAsOrderRecipientIfExist' => 'Utilitzar adreça del contacte del client de seguiment client si està definit en comptes del tercer com a destinatari de les comandes',
		'RunningOrders' => 'Comandes en curs',
		'UserWithApproveOrderGrant' => 'Usuaris habilitats per aprovar les comandes',
		'PaymentOrderRef' => 'Pagament comanda %s',
		'CloneOrder' => 'Clonar comanda',
		'ConfirmCloneOrder' => 'Esteu segur de voler clonar aquesta comanda <b>%s</b>?',
		'DispatchSupplierOrder' => 'Recepció de la comanda a proveïdor %s',
		'DateDeliveryPlanned' => 'Date de livraison prévue',
		'SetDemandReason' => 'Définir l\'origine de la commande',
		////////// Types de contacts //////////
		'TypeContact_commande_internal_SALESREPFOLL' => 'Responsable seguiment comanda client',
		'TypeContact_commande_internal_SHIPPING' => 'Responsable enviament comanda client',
		'TypeContact_commande_external_BILLING' => 'Contacte client facturació comanda',
		'TypeContact_commande_external_SHIPPING' => 'Contacte client lliurament comanda',
		'TypeContact_commande_external_CUSTOMER' => 'Contacte client seguiment comanda',
		'TypeContact_order_supplier_internal_SALESREPFOLL' => 'Responsable seguiment comanda a proveïdor',
		'TypeContact_order_supplier_internal_SHIPPING' => 'Responsable recepció comanda a proveïdor',
		'TypeContact_order_supplier_external_BILLING' => 'Contacte proveïdor facturació comanda',
		'TypeContact_order_supplier_external_SHIPPING' => 'Contacte proveïdor lliurament comanda',
		'TypeContact_order_supplier_external_CUSTOMER' => 'Contacte proveïdor seguiment comanda',
		'Error_COMMANDE_SUPPLIER_ADDON_NotDefined' => 'Constant COMMANDE_SUPPLIER_ADDON no definida',
		'Error_COMMANDE_ADDON_NotDefined' => 'Constant COMMANDE_ADDON no definida',
		'Error_FailedToLoad_COMMANDE_SUPPLIER_ADDON_File' => 'Error en la càrrega de l\'arxiu mòdul \'%s\'',
		'Error_FailedToLoad_COMMANDE_ADDON_File' => 'Error en la càrrega de l\'arxiu mòdul \'%s\'',
		'Error_OrderNotChecked' => 'No s\'han seleccionat comandes a facturar',
		// Sources
		'OrderSource0' => 'Pressupost',
		'OrderSource1' => 'Internet',
		'OrderSource2' => 'Campanya per correu',
		'OrderSource3' => 'Campanya telefònica',
		'OrderSource4' => 'Campanya per fax',
		'OrderSource5' => 'Comercial',
		'OrderSource6' => 'Revistes',
		'QtyOrdered' => 'Qt. demanda',
		'AddDeliveryCostLine' => 'Afegir una línia de despeses de ports indicant el pes de la comanda',
		// Documents models
		'PDFEinsteinDescription' => 'Model de comanda complet (logo...)',
		'PDFEdisonDescription' => 'Model de comanda simple',
		// Orders modes
		'OrderByMail' => 'Correu',
		'OrderByFax' => 'Fax',
		'OrderByEMail' => 'E-Mail',
		'OrderByWWW' => 'En línia',
		'OrderByPhone' => 'Telèfon',
		'CreateInvoiceForThisCustomer' => 'Facturar comandes',
		'NoOrdersToInvoice' => 'Sense comandes facturables',
		'CloseProcessedOrdersAutomatically' => 'Classificar automàticament com "Processades" les comandes seleccionades.',
		'MenuOrdersToBill2' => 'Comandes facturables',
		'LinkedInvoices' => 'Linked invoices',
		'LinkedProposals' => 'Linked proposals'
);
?>