<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$install = array(
		'CHARSET' => 'UTF-8',
		'InstallEasy' => 'ちょうどステップごとの手順のステップに従ってください。',
		'MiscellanousChecks' => '前提条件チェック',
		'SpeedealingWelcome' => 'Welcome to Speedealing',
		'ConfFileExists' => 'コンフィギュレーションファイル<b>%sが</b>存在し<b>ています</b> 。',
		'ConfFileDoesNotExists' => 'コンフィギュレーションファイル<b>%sは</b>存在しません！',
		'ConfFileDoesNotExistsAndCouldNotBeCreated' => 'コンフィギュレーションファイル<b>%sが</b>存在しないと作成できませんでした！',
		'ConfFileCouldBeCreated' => '設定ファイルの<b>%sを</b>作成することができます。',
		'ConfFileIsNotWritable' => '設定ファイルの<b>%sが</b>書き込み可能<b>では</b>ありません。権限を確認してください。最初のインストールについては、Webサーバーは、（OSのようなUnix上の例のために&quot;chmod 666&quot;）のコンフィギュレーションプロセス中にこのファイルに書き込むことができるように付与する必要があります。',
		'ConfFileIsWritable' => 'コンフィギュレーションファイルの<b>%sは</b>書き込み可能です。',
		'ConfFileReload' => 'コンフィギュレーションファイルからすべての情報をリロードします。',
		'PHPSupportSessions' => 'このPHPは、セッションをサポートしています。',
		'PHPSupportPOSTGETOk' => 'このPHPは、変数はPOSTとGETをサポートしています。',
		'PHPSupportPOSTGETKo' => 'それはあなたのPHPの設定は変数のPOSTおよび/をサポートしたり、取得していない可能性があります。 php.iniのパラメータ<b>に、variables_orderを</b>確認<b>して</b>ください。',
		'PHPSupportGD' => 'このPHPのサポートGDグラフィック機能。',
		'PHPSupportUTF8' => 'このPHPは、UTF8の機能をサポートしています。',
		'PHPMemoryOK' => 'あなたのPHPの最大のセッションメモリは<b>%s</b>に設定されています。これは十分なはずです。',
		'PHPMemoryTooLow' => 'あなたのPHPの最大セッション·メモリーが<b>%s</b>バイトに設定されています。これはあまりにも低くする必要があります。少なくとも<b>%s</b>バイト<b>にmemory_limit</b>パラメータを設定するには、php.ini <b>を</b>変更してください。',
		'Recheck' => 'もっと意味のあるテストはここをクリック',
		'ErrorPHPDoesNotSupportSessions' => 'PHPのインストールでは、セッションをサポートしていません。この機能はSpeedealingの作業を行う必要があります。 PHPの設定を確認してください。',
		'ErrorPHPDoesNotSupportGD' => 'PHPのインストールはグラフィカル関数GDをサポートしていません。ないグラフは利用できません。',
		'ErrorPHPDoesNotSupportUTF8' => 'PHPのインストールは、UTF8の機能をサポートしていません。 Speedealingが正しく動作することはできません。 Speedealingをインストールする前にこの問題を解決する。',
		'ErrorDirDoesNotExists' => 'ディレクトリの%sが存在しません。',
		'ErrorGoBackAndCorrectParameters' => '後方に移動して、不正なパラメータを修正してください。',
		'ErrorWrongValueForParameter' => 'あなたは、パラメータ  %s 間違った値を入力した可能性があります。',
		'ErrorFailedToCreateDatabase' => 'データベース %s を作成できませんでした。',
		'ErrorFailedToConnectToDatabase' => 'データベース %s への接続に失敗しました。',
		'ErrorDatabaseVersionTooLow' => 'Database version (%s) too old. Version %s or higher is required.',
		'ErrorPHPVersionTooLow' => 'あまりにも古いPHPバージョン。バージョン%sが必要です。',
		'WarningPHPVersionTooLow' => 'あまりにも古いPHPバージョン。バージョンの%s以上が期待されている。このバージョンは、インストール許可する必要がありますが、サポートされていません。',
		'ErrorConnectedButDatabaseNotFound' => 'しかしデータベース %s 成功したサーバーへの接続を見つけていない。',
		'ErrorDatabaseAlreadyExists' => 'データベース %s は既に存在します。',
		'IfDatabaseNotExistsGoBackAndUncheckCreate' => 'データベースが存在しない場合は、戻ってオプション&quot;データベースを作成します&quot;をチェック。',
		'IfDatabaseExistsGoBackAndCheckCreate' => 'データベースが既に存在する場合は、戻ってチェックを外してオプションの &quot;データベースの作成&quot;を参照してください。',
		'WarningBrowserTooOld' => 'Too old version of browser. Upgrading your browser to a recent version of Firefox, Chrome or Opera is highly recommanded.',
		'PHPVersion' => 'PHPのバージョン',
		'YouCanContinue' => '作業を続行することができます...',
		'PleaseBePatient' => 'しばらくお待ちください...',
		'License' => 'ライセンスを使用して',
		'ConfigurationFile' => '設定ファイル',
		'WebPagesDirectory' => 'ウェブページが保存されているディレクトリ',
		'DocumentsDirectory' => 'アップロードし、生成されたドキュメントを格納するディレクトリ',
		'URLRoot' => 'URLのルート',
		'ForceHttps' => '力安全な接続（HTTPS）',
		'CheckToForceHttps' => 'セキュアな接続（https）を強制的にこのオプションをチェックしてください。 <br>これは、WebサーバがSSL証明書を使用して構成されている必要があります。',
		'SpeedealingDatabase' => 'Speedealing Database',
		'DatabaseChoice' => 'データベースの選択',
		'DatabaseType' => 'データベースの種類',
		'DriverType' => 'ドライバのタイプ',
		'Server' => 'サーバーの',
		'ServerAddressDescription' => '通常、データベースサーバー、データベースサーバーがWebサーバーよりも、同じサーバー上でホストされている \'localhost\'のための名前またはIPアドレス',
		'ServerPortDescription' => 'データベース·サーバーのポート。不明の場合は、空の保管してください。',
		'DatabaseServer' => 'データベース·サーバー',
		'DatabaseName' => 'データベース名',
		'DatabasePrefix' => 'データベースの接頭辞テーブル',
		'Login' => 'ログイン',
		'AdminLogin' => 'Speedealingデータベース所有者のログイン。',
		'Password' => 'パスワード',
		'PasswordAgain' => 'もう一度パスワードを再入力',
		'AdminPassword' => 'Speedealingデータベースの所有者のパスワード。',
		'CreateDatabase' => 'データベースを作成します。',
		'CreateUser' => '所有者を作成します。',
		'DatabaseSuperUserAccess' => 'データベースサーバ - スーパーユーザーのアクセス',
		'CheckToCreateDatabase' => 'データベースが存在しない場合はチェックボックスをオンにして作成する必要があります。 <br>このケースでは、このページの下部にスーパーユーザアカウントのログイン/パスワードを入力する必要があります。',
		'CheckToCreateUser' => 'データベースの所有者が存在しない場合はチェックボックスをオンにして作成する必要があります。 <br>このケースでは、そのログイン名とパスワードを選択しても、ログイン/このページの下部にスーパーユーザーアカウント用のパスワードを入力する必要があります。このボックスがチェックされていない場合、所有者のデータベースとそのパスワードが存在する必要があります。',
		'Experimental' => '（実験的）',
		'DatabaseRootLoginDescription' => 'あなたのデータベースおよびデータベースのログインが既に存在する場合（あなたがウェブホスティングプロバイダによってホストされているときのように）役に立たない、新しいデータベースまたは新しいユーザを作成することを禁止するユーザのログイン。',
		'KeepEmptyIfNoPassword' => 'ユーザーがパスワードを持っていない場合（これを避けるため）を空のままに',
		'SaveConfigurationFile' => '値を保存',
		'ConfigurationSaving' => '保存する設定ファイル',
		'ServerConnection' => 'サーバーへの接続',
		'DatabaseConnection' => 'データベース接続',
		'DatabaseCreation' => 'データベースの作成',
		'UserCreation' => 'ユーザーの作成',
		'CreateDatabaseObjects' => 'データベースオブジェクトの作成',
		'ReferenceDataLoading' => '参照データのロード',
		'TablesAndPrimaryKeysCreation' => 'テーブルと主キーの作成',
		'CreateTableAndPrimaryKey' => 'テーブルの%sを作成する',
		'CreateOtherKeysForTable' => 'テーブルの%sの外部キーとインデックスを作成する',
		'OtherKeysCreation' => '外部キーとインデックスの作成',
		'FunctionsCreation' => '関数の作成',
		'AdminAccountCreation' => '管理者ログインの作成',
		'PleaseTypePassword' => 'パスワードを入力してください、空のパスワードが許可されていません！',
		'PleaseTypeALogin' => 'ログイン情報を入力してください！',
		'PasswordsMismatch' => 'パスワードは異なりますが、もう一度試してください！',
		'SetupEnd' => 'セットアップの終了',
		'SystemIsInstalled' => 'このインストールは完了です。',
		'SystemIsUpgraded' => 'Speedealingが正常にアップグレードされています。',
		'YouNeedToPersonalizeSetup' => 'あなたのニーズに合わせてSpeedealingを設定する必要があります（外観、機能、...).これを行うには、下記のリンクをクリックしてください。',
		'AdminLoginCreatedSuccessfuly' => '成功したの作成​​Speedealing管理者ログイン<b>&quot;%s&quot;。</b>',
		'GoToSpeedealing' => 'Go to Speedealing',
		'GoToSetupArea' => 'Speedealing（セットアップの領域）に移動します',
		'MigrationNotFinished' => 'データベースのバージョンが完全に最新ではありませんので、再度アップグレードプロセスを実行する必要があります。',
		'GoToUpgradePage' => 'ページを再度アップグレードする行く',
		'Examples' => '例',
		'WithNoSlashAtTheEnd' => '末尾のスラッシュ&quot;/&quot;なし',
		'DirectoryRecommendation' => 'それは、あなたのWeb​​ページのディレクトリの外にディレクトリを使用することを勧めます。',
		'LoginAlreadyExists' => 'すでに存在しています',
		'SpeedealingAdminLogin' => 'Speedealing admin login',
		'AdminLoginAlreadyExists' => 'Speedealing管理者アカウント<b>&quot;%s</b> \' <b>は</b>既に存在します。あなたが別のパーティションを作成する場合は、戻ってください。',
		'WarningRemoveInstallDir' => '警告、セキュリティ上の理由から、一度インストールまたはアップグレードが完了すると、あなた<b>は</b>それ<b>の悪意のある使用を避けるために、インストールディレクトリを</b>削除<b>するか、Speedealingのドキュメントディレクトリにinstall.lockと呼ばれるファイルを追加</b>する必要があります<b>。</b>',
		'ThisPHPDoesNotSupportTypeBase' => 'このPHPシステムは、データベースの種類%sにアクセスする任意のインターフェイスをサポートしていません。',
		'FunctionNotAvailableInThisPHP' => 'このPHPは利用できません',
		'MigrateScript' => '移行スクリプト',
		'ChoosedMigrateScript' => '移行スクリプトを選択します。',
		'DataMigration' => 'データの移行',
		'DatabaseMigration' => '構造データベースの移行',
		'ProcessMigrateScript' => 'スクリプト処理',
		'ChooseYourSetupMode' => 'セットアップモードを選択し、&quot;スタート&quot;をクリック...',
		'FreshInstall' => '新規インストール',
		'FreshInstallDesc' => 'これはあなたの最初のインストールの場合、このモードを使用してください。そうでない場合、このモードでは不完全な以前のインストールを修復することができますが、バージョンをアップグレードする場合、&quot;アップグレード&quot;モードを選択してください。',
		'Upgrade' => 'アップグレード',
		'UpgradeDesc' => 'あなたが新しいバージョンのファイルが古いSpeedealingファイルを交換した場合、このモードを使用します。これにより、データベースとデータをアップグレードします。',
		'Start' => '開始',
		'InstallNotAllowed' => 'セットアップでは<b>、conf.php</b>の権限で許可されていない',
		'NotAvailable' => '利用できない',
		'YouMustCreateWithPermission' => 'あなたは、ファイル%sを作成し、インストールプロセス中にWebサーバのためにそれへの書き込み権限を設定する必要があります。',
		'CorrectProblemAndReloadPage' => '問題を修正し、ページをリロードするには、F5キーを押してください。',
		'AlreadyDone' => '既に移行',
		'DatabaseVersion' => 'データベースのバージョン',
		'ServerVersion' => 'データベースサーバのバージョン',
		'YouMustCreateItAndAllowServerToWrite' => 'このディレクトリを作成し、そこに書き込むようにWebサーバを許可する必要があります。',
		'CharsetChoice' => '文字セットの選択',
		'CharacterSetClient' => '生成されたHTML Webページに使用される文字セット',
		'CharacterSetClientComment' => 'Web表示用の文字セットを選択します。 <br/>デフォルト提案された文字セットは、データベースの一つです。',
		'CollationConnection' => '文字のソート順',
		'CollationConnectionComment' => 'データベースで使用される文字のソート順序を定義するページのコードを選択してください。このパラメータは、いくつかのデータベースで&quot;照合順序&quot;と呼ばれています。 <br/>データベースがすでに存在している場合、このパラメータは定義することはできません。',
		'CharacterSetDatabase' => 'データベースの文字セット',
		'CharacterSetDatabaseComment' => 'データベース作成のためにしたい文字セットを選択します。 <br/>データベースがすでに存在している場合、このパラメータは定義することはできません。',
		'YouAskDatabaseCreationSoSpeedealingNeedToConnect' => 'You ask to create database <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'YouAskLoginCreationSoSpeedealingNeedToConnect' => 'You ask to create database login <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'BecauseConnectionFailedParametersMayBeWrong' => '接続が失敗したように、ホストまたはスーパーユーザパラメータが間違っていなければなりません。',
		'OrphelinsPaymentsDetectedByMethod' => 'メソッド%sによって検出された孤児の支払い',
		'RemoveItManuallyAndPressF5ToContinue' => '手動で削除して続行するF5キーを押します。',
		'KeepDefaultValuesWamp' => 'あなたがDoliWampからSpeedealingセットアップ·ウィザードを使用するので、ここで提案する値は、既に最適化されています。あなたは何をすべきか分かっている場合にのみ、それらを変更します。',
		'KeepDefaultValuesDeb' => 'あなたは、Linuxパッケージ（Ubuntuのは、Debian、Fedoraの...）からSpeedealingセットアップ·ウィザードを使用するので、ここで提案値がすでに最適化されています。作成するデータベースの所有者のパスワードのみを完了する必要があります。あなたは何をすべきか分かっている場合にのみ、他のパラメータを変更します。',
		'KeepDefaultValuesMamp' => 'あなたがDoliMampからSpeedealingのセットアップウィザードを使用して、ここで提案するので、値がすでに最適化されています。あなたは何をすべきか分かっている場合にのみ、それらを変更してください。',
		'KeepDefaultValuesProxmox' => 'あなたがProxmox仮想アプライアンスからSpeedealingのセットアップウィザードを使用して、ここで提案するので、値がすでに最適化されています。あなたは何をすべきか分かっている場合にのみ、それらを変更してください。',
		'FieldRenamed' => 'フィールドの名前変更',
		'IfLoginDoesNotExistsCheckCreateUser' => 'ログインがまだ存在しない場合は、オプション&quot;ユーザーの作成&quot;をチェックする必要があります',
		'ErrorConnection' => 'サーバ<b>&quot;%s&quot;、</b>データベース名<b>&quot;%s&quot;、</b>ログイン<b>&quot;%s&quot;、</b>またはデータベースのパスワードは、クライアントのバージョンがデータベースのバージョンに比べて古すぎる可能性があります間違っていたり、PHP可能性があります。',
		'InstallChoiceRecommanded' => 'あなたの現在のバージョンの<b>%s</b>からバージョン<b>%sを</b>インストールすることをお勧め選択肢',
		'InstallChoiceSuggested' => '<b>インストーラによって提案された選択肢をインストールします</b> 。',
		'MigrateIsDoneStepByStep' => '対象となるバージョン（%s）は、いくつかのバージョンのギャップがあるため、インストールウィザードは、この1つが終了されますしたら、次の移行を示唆して戻ってくるだろう。',
		'CheckThatDatabasenameIsCorrect' => 'そのデータベース名<b>&quot;%s&quot;が</b>正しいか確認してください。',
		'IfAlreadyExistsCheckOption' => 'この名前が正しいこと、およびそのデータベースがまだ存在しない場合は、オプションの&quot;データベースの作成&quot;をチェックする必要があります。',
		'OpenBaseDir' => 'PHP openbasedirパラメータ',
		'YouAskToCreateDatabaseSoRootRequired' => 'あなたは &quot;データベースの作成&quot;ボックスをチェックしました。このためには、スーパーユーザー（フォームの下部）のログイン名/パスワードを提供する必要があります。',
		'YouAskToCreateDatabaseUserSoRootRequired' => 'あなたは &quot;データベース所有者の作成&quot;ボックスをチェックしました。このためには、スーパーユーザー（フォームの下部）のログイン名/パスワードを提供する必要があります。',
		'NextStepMightLastALongTime' => '現在のステップには数分かかる場合があります。次の画面が続行する前に完全に表示されるまでしばらくお待ちください。',
		'LastStepDesc' => '<strong>最後のステップ</strong> ：ここにあなたがソフトウェアへの接続に使用する予定のログインとパスワードを定義します。それは他のすべてを管理するアカウントであるとしてこれを紛失しないでください。',
		'ActivateModule' => 'モジュール%sをアクティブにする',
		'ShowEditTechnicalParameters' => 'Click here to show/edit advanced parameters (expert mode)',
		'ServerPortCouchdbDescription' => 'Port du serveur. Défaut 5984.',
		'ServerAddressCouchdbDescription' => 'Nom FQDN du serveur de base de données, \'localhost.localdomain\' quand le serveur est installé sur la même machine que le serveur web',
		'DatabaseCouchdbUserDescription' => 'Login du super administrateur ayant tous les droits sur le serveur CouchDB ou l\'administrateur propriétaire de la base si la base et son compte d\'accès existent déjà (comme lorsque vous êtes chez un hébergeur).<br><br><div class="alert-box info">Cet utilisateur/mot de passe sera l\'administrateur pour se connecter à Speedealing.</div>',
		'CheckToCreateCouchdbDatabase' => 'Cochez cette option si la base de données n\'existe pas et doit être créée.',
		'CreateAdminUser' => 'Créer le super administrateur (Première installation de couchDB)',
		'MemcachedDescription' => 'Activer Memcached necessite l\'installation d\'un serveur Memcached et des lib php-memcached ou php-memcache. Il peut être activer après l\'installation.',
		'ServerAddressMemcachedDesc' => 'Nom ou adresse ip du serveur memcached, généralement \'localhost\' quand le serveur est installé sur la même machine que le serveur web',
		'ServerPortMemcachedDesc' => 'Port du serveur memcached. Défaut : 11211',
		'EnabledMemcached' => 'Activer Memcached',
		'DatabaseNoSQL' => 'Base de données CouchDB',
		'FailedToCreateAdminLogin' => 'Echec de la création du compte administrateur Speedealing.',
		'LinkedElementsInvalidDeleted' => '<b>%s</b> liaisons invalides ont été supprimées',
		'NothingToDelete' => 'Aucune liaison invalide trouvée',
		'SourceType' => 'Source',
		'TargetType' => 'Cible',
                // Upgrade
                'UpgradeOk' => 'Upgrade is ok !',
                'NewInstalledVersion' => 'Your new version is %s',
                'NeedUpgrade' => 'New Speedealing version !',
                'WarningUpgrade' => 'Installed version is %s, you must upgrade to %s. <br>Please contact your administrator.'
);
?>