<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'ユーザーカード',
		'ContactCard' => 'カードにお問い合わせください',
		'GroupCard' => 'グループカード',
		'NoContactCard' => '接点間にカードが入っていません',
		'Permission' => 'アクセス権',
		'Permissions' => 'パーミッション',
		'EditPassword' => 'パスワードを編集します。',
		'SendNewPassword' => 'パスワードを再生成して送信する',
		'ReinitPassword' => 'パスワードを再生成する',
		'PasswordChangedTo' => '%s：パスワードに変更',
		'SubjectNewPassword' => 'Speedealingための新しいパスワード',
		'AvailableRights' => '使用可能なアクセス許可',
		'OwnedRights' => '所有する権限',
		'GroupRights' => 'グループのパーミッション',
		'UserRights' => 'ユーザー権限',
		'UserGUISetup' => 'ユーザーのディスプレイのセットアップ',
		'DisableUser' => '無効にする',
		'DisableAUser' => 'ユーザーを無効にする',
		'DeleteUser' => '削除',
		'DeleteAUser' => 'ユーザーを削除する',
		'DisableGroup' => '無効',
		'DisableAGroup' => 'グループを無効にする',
		'EnableAUser' => 'ユーザーを有効にします。',
		'EnableAGroup' => 'グループを有効にする',
		'DeleteGroup' => '削除する',
		'DeleteAGroup' => 'グループを削除する',
		'ConfirmDisableUser' => 'あなたは、ユーザ<b>%sを</b>無効<b>に</b>してもよろしいですか？',
		'ConfirmDisableGroup' => 'あなたは、グループ<b>%sを</b>無効<b>に</b>してもよろしいですか？',
		'ConfirmDeleteUser' => 'あなたは、ユーザ<b>%sを</b>削除し<b>てもよろしい</b>ですか？',
		'ConfirmDeleteGroup' => 'あなたは、グループ<b>%sを</b>削除し<b>てもよろしい</b>ですか？',
		'ConfirmEnableUser' => 'あなたは、ユーザ<b>%sを</b>有効<b>に</b>してもよろしいですか？',
		'ConfirmEnableGroup' => 'あなたは、グループ<b>%sを</b>有効<b>に</b>してもよろしいですか？',
		'ConfirmReinitPassword' => 'あなたは、ユーザ<b>%s</b>の新しいパスワードを生成してもよろしいですか？',
		'ConfirmSendNewPassword' => 'あなたはユーザー<b>%s</b>のための新しいパスワードを生成して送信してもよろしいですか？',
		'NewUser' => '新しいユーザ',
		'CreateUser' => 'ユーザを作成する',
		'SearchAGroup' => 'グループを検索',
		'SearchAUser' => 'ユーザーを検索',
		'LoginNotDefined' => 'ログインが定義されていません。',
		'NameNotDefined' => '名前が定義されていません。',
		'ListOfUsers' => 'ユーザーのリスト',
		'Administrator' => '管理者',
		'SuperAdministrator' => 'スーパー管理者',
		'SuperAdministratorDesc' => 'グローバル管理者',
		'AdministratorDesc' => '管理者の実体',
		'DefaultRights' => '既定のアクセス許可',
		'DefaultRightsDesc' => 'ここで自動的に<u>新規作成した</u>ユーザー（既存のユーザーのアクセス許可を変更するには、ユーザカードに移動）に付与されている<u>既定の</u>アクセス許可を定義します。',
		'SpeedealingUsers' => 'Speedealing users',
		'LastName' => 'の名前',
		'FirstName' => '最初の名前',
		'ListOfGroups' => 'グループのリスト',
		'NewGroup' => '新グループ',
		'CreateGroup' => 'グループを作成します。',
		'RemoveFromGroup' => 'グループから削除',
		'PasswordChangedAndSentTo' => 'パスワードが変更され<b>、%s</b>に送信されます。',
		'PasswordChangeRequestSent' => '<b>%s %s</b>に送信するためのパスワードを変更するには、要求します。',
		'MenuUsersAndGroups' => 'ユーザーとグループ',
		'LastGroupsCreated' => '最後%sグループを作成',
		'LastUsersCreated' => '最後に作成した%sユーザー',
		'ShowGroup' => 'グループを表示',
		'ShowUser' => 'ユーザーを表示する',
		'NonAffectedUsers' => '非影響を受けるユーザー',
		'UserModified' => 'ユーザーが正常に変更',
		'GroupModified' => 'グループが正常に変更',
		'PhotoFile' => '写真ファイル',
		'UserWithSpeedealingAccess' => 'User with Speedealing access',
		'ListOfUsersInGroup' => 'このグループのユーザのリスト',
		'ListOfGroupsForUser' => 'このユーザのグループのリスト',
		'UsersToAdd' => 'ユーザーはこのグループに追加する',
		'GroupsToAdd' => 'このユーザーに追加するグループ',
		'NoLogin' => '全くログインしない',
		'LinkToCompanyContact' => 'サードパーティ/お問い合わせへのリンク',
		'LinkedToSpeedealingMember' => 'Link to member',
		'LinkedToSpeedealingUser' => 'Link to Speedealing user',
		'LinkedToSpeedealingThirdParty' => 'Link to Speedealing third party',
		'CreateSpeedealingLogin' => 'Create a user',
		'CreateSpeedealingThirdParty' => 'Create a third party',
		'LoginAccountDisable' => 'アカウントが無効になって、それをアクティブにするには、新しいログインを入れた。',
		'LoginAccountDisableInSpeedealing' => 'Account disabled in Speedealing.',
		'LoginAccountDisableInLdap' => 'アカウントがドメインで無効に。',
		'UsePersonalValue' => '個人的な値を使用',
		'GuiLanguage' => 'インターフェースの言語',
		'InternalUser' => '内部ユーザ',
		'MyInformations' => '私のデータ',
		'ExportDataset_user_1' => 'Speedealingのユーザーとプロパティ',
		'DomainUser' => 'ドメインユーザー%s',
		'Reactivate' => '再アクティブ化',
		'CreateInternalUserDesc' => 'このフォームは、あなたの会社/財団への内部ユーザを設けることができます。外部ユーザー（顧客、サプラ​​イヤ、...）creatを、サードパーティの連絡先カードからボタンの作成Speedealingユーザー \'を使用します。',
		'InternalExternalDesc' => '<b>内部</b>ユーザは、あなたの会社/基礎の一部であるユーザーです。 <br> <b>外部</b>ユーザーは顧客、サプライヤーまたは他のです。 <br><br>両方のケースでは、権限も、Speedealingの権限を定義する外部ユーザー（ホームを参照してください - セットアップ - ディスプレイ）は、内部ユーザーとは異なるメニューマネージャを持つことができます',
		'PermissionInheritedFromAGroup' => 'ユーザーのグループのいずれかから継承されたので、許可が付与されます。',
		'Inherited' => '継承された',
		'UserWillBeInternalUser' => '（特定の第三者にリンクされていないため）作成したユーザーは、内部ユーザーになります',
		'UserWillBeExternalUser' => '作成したユーザ（特にサードパーティにリンクされているため）、外部のユーザーになります',
		'IdPhoneCaller' => 'イドの電話発信',
		'UserLogged' => 'ユーザー%sログイン',
		'UserLogoff' => 'ユーザーの%sログアウト',
		'NewUserCreated' => 'ユーザーの%s作成',
		'NewUserPassword' => '%s用パスワードの変更',
		'EventUserModified' => 'ユーザーの%sは変更',
		'UserDisabled' => 'ユーザーの%sが無効になって',
		'UserEnabled' => 'ユーザー%sは、アクティブ',
		'UserDeleted' => 'ユーザー%sは削除され',
		'NewGroupCreated' => 'グループ%sが作成',
		'GroupModified' => 'グループが正常に変更',
		'GroupDeleted' => 'グループ%sは削除され',
		'ConfirmCreateContact' => 'あなたは、この連絡先のSpeedealingアカウントを作成してもよろしいですか？',
		'ConfirmCreateLogin' => 'このメンバーのSpeedealingアカウントを作成してもよろしいですか？',
		'ConfirmCreateThirdParty' => 'このメンバーのサードパーティを作成してもよろしいですか？',
		'LoginToCreate' => '作成するには、ログインしてください',
		'NameToCreate' => '作成するには、サードパーティの名前',
		'YourRole' => 'あなたの役割',
		'YourQuotaOfUsersIsReached' => 'アクティブなユーザーのあなたのクォータに達している！',
		'NbOfUsers' => 'ユーザーのNb',
		'DontDowngradeSuperAdmin' => '唯一superadminはダウングレードは、superAdminできます',
		'NewDatabase' => 'Nouvelle base de données',
		'CreateDatabase' => 'Créer la base de données',
		'ListOfDatabases' => 'Liste des bases de données',
		'ListOfUsersInDatabase' => 'Liste des utilisateurs liés à la base de données',
		'ListOfRolesInDatabase' => 'Liste des groupes liés à la base de données',
		'DeleteADatabase' => 'Suppression d\'une database',
		'ConfirmDatabase' => 'Êtes-vous sûr de vouloir supprimer la base de données <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Groupes non affectés à la base de données',
		'NonAffectedUsersDatabase' => 'Utilisateurs non affectés à la base de données',
		'Collaborators' => 'Collaborateurs',
		'Profiles' => 'Profils collaborateurs'
);
?>