<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Commercial',
		'CommercialArea' => 'Commercial area',
		'CommercialCard' => 'Commercial card',
		'CustomerArea' => 'Customers area',
		'Customer' => 'Customer',
		'Customers' => 'Customers',
		'Prospect' => 'Prospect',
		'Prospects' => 'Prospects',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Delete an event/task',
		'NewAction' => 'New event/task',
		'AddAction' => 'Add event/task',
		'AddAnAction' => 'Add an event/task',
		'AddActionRendezVous' => 'Add a Rendez-vous event',
		'Rendez-Vous' => 'Rendezvous',
		'ConfirmDeleteAction' => 'Are you sure you want to delete this event/task ?',
		'CardAction' => 'Event card',
		'PercentDone' => 'Percentage complete',
		'ActionOnCompany' => 'Task about company',
		'ActionOnContact' => 'Task about contact',
		'TaskRDV' => 'Meetings',
		'TaskRDVWith' => 'Meeting with %s',
		'ShowTask' => 'Show task',
		'ShowAction' => 'Show event',
		'ActionsReport' => 'Events report',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Sales representative',
		'SalesRepresentatives' => 'Sales representatives',
		'SalesRepresentativeFollowUp' => 'Sales representative (follow-up)',
		'SalesRepresentativeSignature' => 'Sales representative (signature)',
		'CommercialInterlocutor' => 'Commercial interlocutor',
		'ErrorWrongCode' => 'Wrong code',
		'NoSalesRepresentativeAffected' => 'No particular sales representative affected',
		'ShowCustomer' => 'Show customer',
		'ShowProspect' => 'Show prospect',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'List of prospects',
		'ListOfCustomers' => 'List of customers',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'Last %s completed tasks',
		'LastRecordedTasks' => 'Last recorded tasks',
		'LastActionsToDo' => 'Last %s oldest actions not completed',
		'DoneAndToDoActionsFor' => 'Completed and To do events for %s',
		'DoneAndToDoActions' => 'Completed and To do events',
		'DoneActions' => 'Completed events',
		'DoneActionsFor' => 'Completed events for %s',
		'ToDoActions' => 'Incomplete events',
		'ToDoActionsFor' => 'Incomplete events for %s',
		'SendPropalRef' => 'Send commercial proposal %s',
		'SendOrderRef' => 'Send order %s',
		'StatusNotApplicable' => 'Not applicable',
		'StatusActionToDo' => 'To do',
		'StatusActionDone' => 'Complete',
		'StatusActionInProcess' => 'In process',
		'MyActionsAsked' => 'Events I have recorded',
		'MyActionsToDo' => 'Events I have to do',
		'MyActionsDone' => 'Events affected to me',
		'TasksHistoryForThisContact' => 'Events for this contact',
		'LastProspectDoNotContact' => 'Do not contact',
		'LastProspectNeverContacted' => 'Never contacted',
		'LastProspectToContact' => 'To contact',
		'LastProspectContactInProcess' => 'Contact in process',
		'LastProspectContactDone' => 'Contact done',
		'DateActionPlanned' => 'Date event planned for',
		'DateActionDone' => 'Date event done',
		'ActionAskedBy' => 'Event reported by',
		'ActionAffectedTo' => 'Event affected to',
		'ActionDoneBy' => 'Event done by',
		'ActionUserAsk' => 'Reported by',
		'ErrorStatusCantBeZeroIfStarted' => 'If field \'<b>Date done</b>\' is filled, action is started (or finished), so field \'<b>Status</b>\' can\'t be 0%%.',
		'ActionAC_TEL' => 'Phone call',
		'ActionAC_FAX' => 'Send fax',
		'ActionAC_PROP' => 'Send proposal by mail',
		'ActionAC_EMAIL' => 'Send Email',
		'ActionAC_RDV' => 'Meetings',
		'ActionAC_FAC' => 'Send customer invoice by mail',
		'ActionAC_REL' => 'Send customer invoice by mail (reminder)',
		'ActionAC_CLO' => 'Close',
		'ActionAC_EMAILING' => 'Send mass email',
		'ActionAC_COM' => 'Send customer order by mail',
		'ActionAC_SHIP' => 'Send shipping by mail',
		'ActionAC_SUP_ORD' => 'Send supplier order by mail',
		'ActionAC_SUP_INV' => 'Send supplier invoice by mail',
		'ActionAC_OTH' => 'Other',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Prospect status',
		'DraftPropals' => 'Draft commercial proposals',
		'SearchPropal' => 'Search a commercial proposal'
);
?>