<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$install = array(
		'CHARSET' => 'UTF-8',
		'InstallEasy' => 'Just follow the instructions step by step.',
		'MiscellanousChecks' => 'Prerequisites check',
		'SpeedealingWelcome' => 'Welcome to Speedealing',
		'ConfFileExists' => 'Configuration file <b>%s</b> exists.',
		'ConfFileDoesNotExists' => 'Configuration file <b>%s</b> does not exist !',
		'ConfFileDoesNotExistsAndCouldNotBeCreated' => 'Configuration file <b>%s</b> does not exist and could not be created !',
		'ConfFileCouldBeCreated' => 'Configuration file <b>%s</b> could be created.',
		'ConfFileIsNotWritable' => 'Configuration file <b>%s</b> is not writable. Check permissions. For first install, your web server must be granted to be able to write into this file during configuration process ("chmod 666" for example on a Unix like OS).',
		'ConfFileIsWritable' => 'Configuration file <b>%s</b> is writable.',
		'ConfFileReload' => 'Reload all information from configuration file.',
		'PHPSupportSessions' => 'This PHP supports sessions.',
		'PHPSupportPOSTGETOk' => 'This PHP supports variables POST and GET.',
		'PHPSupportPOSTGETKo' => 'It\'s possible your PHP setup does not support variables POST and/or GET. Check your parameter <b>variables_order</b> in php.ini.',
		'PHPSupportGD' => 'This PHP support GD graphical functions.',
		'PHPSupportUTF8' => 'This PHP support UTF8 functions.',
		'PHPMemoryOK' => 'Your PHP max session memory is set to <b>%s</b>. This should be enough.',
		'PHPMemoryTooLow' => 'Your PHP max session memory is set to <b>%s</b> bytes. This should be too low. Change your <b>php.ini</b> to set <b>memory_limit</b> parameter to at least <b>%s</b> bytes.',
		'Recheck' => 'Click here for a more significative test',
		'ErrorPHPDoesNotSupportSessions' => 'Your PHP installation does not support sessions. This feature is required to make Speedealing working. Check your PHP setup.',
		'ErrorPHPDoesNotSupportGD' => 'Your PHP installation does not support graphical function GD. No graph will be available.',
		'ErrorPHPDoesNotSupportUTF8' => 'Your PHP installation does not support UTF8 functions. Speedealing can\'t work correctly. Solve this before installing Speedealing.',
		'ErrorDirDoesNotExists' => 'Directory %s does not exist.',
		'ErrorGoBackAndCorrectParameters' => 'Go backward and correct wrong parameters.',
		'ErrorWrongValueForParameter' => 'You may have typed a wrong value for parameter \'%s\'.',
		'ErrorFailedToCreateDatabase' => 'Failed to create database \'%s\'.',
		'ErrorFailedToConnectToDatabase' => 'Failed to connect to database \'%s\'.',
		'ErrorDatabaseVersionTooLow' => 'Database version (%s) too old. Version %s or higher is required.',
		'ErrorPHPVersionTooLow' => 'PHP version too old. Version %s is required.',
		'WarningPHPVersionTooLow' => 'PHP version too old. Version %s or more is expected. This version should allow install but is not supported.',
		'ErrorConnectedButDatabaseNotFound' => 'Connection to server successfull but database \'%s\' not found.',
		'ErrorDatabaseAlreadyExists' => 'Database \'%s\' already exists.',
		'IfDatabaseNotExistsGoBackAndUncheckCreate' => 'If database does not exists, go back and check option "Create database".',
		'IfDatabaseExistsGoBackAndCheckCreate' => 'If database already exists, go back and uncheck "Create database" option.',
		'WarningBrowserTooOld' => 'Too old version of browser. Upgrading your browser to a recent version of Firefox, Chrome or Opera is highly recommanded.',
		'PHPVersion' => 'PHP Version',
		'YouCanContinue' => 'You can continue...',
		'PleaseBePatient' => 'Please be patient...',
		'License' => 'Using license',
		'ConfigurationFile' => 'Configuration file',
		'WebPagesDirectory' => 'Web pages directory',
		'DocumentsDirectory' => 'Documents directory',
		'URLRoot' => 'URL Root',
		'ForceHttps' => 'Force secure connections (https)',
		'CheckToForceHttps' => 'Check this option to force secure connections (https).<br>This requires that the web server is configured with an SSL certificate.',
		'SpeedealingDatabase' => 'Speedealing Database',
		'DatabaseChoice' => 'Database choice',
		'DatabaseType' => 'Database type',
		'DriverType' => 'Driver type',
		'Server' => 'Server',
		'ServerAddressDescription' => 'Name or ip address for database server, usually \'localhost\' when database server is hosted on same server than web server',
		'ServerPortDescription' => 'Database server port. Keep empty if unknown.',
		'DatabaseServer' => 'Database server',
		'DatabaseName' => 'Database name',
		'DatabasePrefix' => 'Database prefix table',
		'Login' => 'Login',
		'AdminLogin' => 'Login for Speedealing database owner.',
		'Password' => 'Password',
		'PasswordAgain' => 'Retype password a second time',
		'AdminPassword' => 'Password for Speedealing database owner.',
		'CreateDatabase' => 'Create database',
		'CreateUser' => 'Create owner',
		'DatabaseSuperUserAccess' => 'Database server - Superuser access',
		'CheckToCreateDatabase' => 'Check box if database does not exist and must be created.<br>In this case, you must fill the login/password for superuser account at the bottom of this page.',
		'CheckToCreateUser' => 'Check box if database owner does not exist and must be created.<br>In this case, you must choose its login and password and also fill the login/password for the superuser account at the bottom of this page. If this box is unchecked, owner database and its passwords must exists.',
		'Experimental' => '(experimental)',
		'DatabaseRootLoginDescription' => 'Login of the user allowed to create new databases or new users, useless if your database and your database login already exists (like when you\'re hosted by a web hosting provider).',
		'KeepEmptyIfNoPassword' => 'Leave empty if user has no password (avoid this)',
		'SaveConfigurationFile' => 'Save values',
		'ConfigurationSaving' => 'Saving configuration file',
		'ServerConnection' => 'Server connection',
		'DatabaseConnection' => 'Database connection',
		'DatabaseCreation' => 'Database creation',
		'UserCreation' => 'User creation',
		'CreateDatabaseObjects' => 'Database objects creation',
		'ReferenceDataLoading' => 'Reference data loading',
		'TablesAndPrimaryKeysCreation' => 'Tables and Primary keys creation',
		'CreateTableAndPrimaryKey' => 'Create table %s',
		'CreateOtherKeysForTable' => 'Create foreign keys and indexes for table %s',
		'OtherKeysCreation' => 'Foreign keys and indexes creation',
		'FunctionsCreation' => 'Functions creation',
		'AdminAccountCreation' => 'Administrator login creation',
		'PleaseTypePassword' => 'Please type a password, empty passwords are not allowed !',
		'PleaseTypeALogin' => 'Please type a login !',
		'PasswordsMismatch' => 'Passwords differs, please try again !',
		'SetupEnd' => 'End of setup',
		'SystemIsInstalled' => 'This installation is complete.',
		'SystemIsUpgraded' => 'Speedealing has been upgraded successfully.',
		'YouNeedToPersonalizeSetup' => 'You need to configure Speedealing to suit your needs (appearance, features, ...). To do this, please follow the link below:',
		'AdminLoginCreatedSuccessfuly' => 'Speedealing administrator login \'<b>%s</b>\' created successfuly.',
		'GoToSpeedealing' => 'Go to Speedealing',
		'GoToSetupArea' => 'Go to Speedealing (setup area)',
		'MigrationNotFinished' => 'Version of your database is not completely up to date, so you\'ll have to run the upgrade process again.',
		'GoToUpgradePage' => 'Go to upgrade page again',
		'Examples' => 'Examples',
		'WithNoSlashAtTheEnd' => 'Without the slash "/" at the end',
		'DirectoryRecommendation' => 'It is recommanded to use a directory outside of your directory of your web pages.',
		'LoginAlreadyExists' => 'Already exists',
		'SpeedealingAdminLogin' => 'Speedealing admin login',
		'AdminLoginAlreadyExists' => 'Speedealing administrator account \'<b>%s</b>\' already exists. Go back, if you want to create another one.',
		'WarningRemoveInstallDir' => 'Warning, for security reasons, once the install or upgrade is complete, to avoid using install tools again, you should add a file called <b>install.lock</b> into Speedealing document directory, in order to avoid malicious use of it.',
		'ThisPHPDoesNotSupportTypeBase' => 'This PHP system does not support any interface to access database type %s',
		'FunctionNotAvailableInThisPHP' => 'Not available on this PHP',
		'MigrateScript' => 'Migration script',
		'ChoosedMigrateScript' => 'Choose migration script',
		'DataMigration' => 'Data migration',
		'DatabaseMigration' => 'Structure database migration',
		'ProcessMigrateScript' => 'Script processing',
		'ChooseYourSetupMode' => 'Choose your setup mode and click "Start"...',
		'FreshInstall' => 'Fresh install',
		'FreshInstallDesc' => 'Use this mode if this is your first install. If not, this mode can repair a incomplete previous install, but if you want to upgrade your version, choose "Upgrade" mode.',
		'Upgrade' => 'Upgrade',
		'UpgradeDesc' => 'Use this mode if you have replaced old Speedealing files with files from a newer version. This will upgrade your database and data.',
		'Start' => 'Start',
		'InstallNotAllowed' => 'Setup not allowed by <b>conf.php</b> permissions',
		'NotAvailable' => 'Not available',
		'YouMustCreateWithPermission' => 'You must create file %s and set write permissions on it for the web server during install process.',
		'CorrectProblemAndReloadPage' => 'Please fix the problem and press F5 to reload page.',
		'AlreadyDone' => 'Already migrated',
		'DatabaseVersion' => 'Database version',
		'ServerVersion' => 'Database server version',
		'YouMustCreateItAndAllowServerToWrite' => 'You must create this directory and allow for the web server to write into it.',
		'CharsetChoice' => 'Character set choice',
		'CharacterSetClient' => 'Character set used for generated HTML web pages',
		'CharacterSetClientComment' => 'Choose character set for web display.<br/> Default proposed character set is the one of your database.',
		'CollationConnection' => 'Character sorting order',
		'CollationConnectionComment' => 'Choose page code that defines character\'s sorting order used by database. This parameter is also called \'collation\' by some databases.<br/>This parameter can\'t be defined if database already exists.',
		'CharacterSetDatabase' => 'Character set for database',
		'CharacterSetDatabaseComment' => 'Choose character set wanted for database creation.<br/>This parameter can\'t be defined if database already exists.',
		'YouAskDatabaseCreationSoSpeedealingNeedToConnect' => 'You ask to create database <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'YouAskLoginCreationSoSpeedealingNeedToConnect' => 'You ask to create database login <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'BecauseConnectionFailedParametersMayBeWrong' => 'As connection failed, host or super user parameters must be wrong.',
		'OrphelinsPaymentsDetectedByMethod' => 'Orphans payment detected by method %s',
		'RemoveItManuallyAndPressF5ToContinue' => 'Remove it manually and press F5 to continue.',
		'KeepDefaultValuesWamp' => 'You use the Speedealing setup wizard from DoliWamp, so values proposed here are already optimized. Change them only if you know what you do.',
		'KeepDefaultValuesDeb' => 'You use the Speedealing setup wizard from a Linux package (Ubuntu, Debian, Fedora...), so values proposed here are already optimized. Only the password of the database owner to create must be completed. Change other parameters only if you know what you do.',
		'KeepDefaultValuesMamp' => 'You use the Speedealing setup wizard from DoliMamp, so values proposed here are already optimized. Change them only if you know what you do.',
		'KeepDefaultValuesProxmox' => 'You use the Speedealing setup wizard from a Proxmox virtual appliance, so values proposed here are already optimized. Change them only if you know what you do.',
		'FieldRenamed' => 'Field renamed',
		'IfLoginDoesNotExistsCheckCreateUser' => 'If login does not exists yet, you must check option "Create user"',
		'ErrorConnection' => 'Server "<b>%s</b>", database name "<b>%s</b>", login "<b>%s</b>", or database password may be wrong or PHP client version may be too old compared to database version.',
		'InstallChoiceRecommanded' => 'Recommended choice to install version <b>%s</b> from your current version <b>%s</b>',
		'InstallChoiceSuggested' => '<b>Install choice suggested by installer</b>.',
		'MigrateIsDoneStepByStep' => 'The targeted version (%s) has a gap of several versions, so install wizard will come back to suggest next migration once this one will be finished.',
		'CheckThatDatabasenameIsCorrect' => 'Check that database name "<b>%s</b>" is correct.',
		'IfAlreadyExistsCheckOption' => 'If this name is correct and that database does not exist yet, you must check option "Create database".',
		'OpenBaseDir' => 'PHP openbasedir parameter',
		'YouAskToCreateDatabaseSoRootRequired' => 'You checked the box "Create database". For this, you need to provide login/password of superuser (bottom of form).',
		'YouAskToCreateDatabaseUserSoRootRequired' => 'You checked the box "Create database owner". For this, you need to provide login/password of superuser (bottom of form).',
		'NextStepMightLastALongTime' => 'Current step may last several minutes. Please wait until the next screen is shown completely before continuing.',
		'LastStepDesc' => '<strong>Last step</strong>: Define here login and password you plan to use to connect to software. Do not loose this as it is the account to administer all others.',
		'ActivateModule' => 'Activate module %s',
		'ShowEditTechnicalParameters' => 'Click here to show/edit advanced parameters (expert mode)',
		'ServerPortCouchdbDescription' => 'Port du serveur. Défaut 5984.',
		'ServerAddressCouchdbDescription' => 'Nom FQDN du serveur de base de données, \'localhost.localdomain\' quand le serveur est installé sur la même machine que le serveur web',
		'DatabaseCouchdbUserDescription' => 'Login du super administrateur ayant tous les droits sur le serveur CouchDB ou l\'administrateur propriétaire de la base si la base et son compte d\'accès existent déjà (comme lorsque vous êtes chez un hébergeur).<br><br><div class="alert-box info">Cet utilisateur/mot de passe sera l\'administrateur pour se connecter à Speedealing.</div>',
		'CheckToCreateCouchdbDatabase' => 'Cochez cette option si la base de données n\'existe pas et doit être créée.',
		'CreateAdminUser' => 'Créer le super administrateur (Première installation de couchDB)',
		'MemcachedDescription' => 'Activer Memcached necessite l\'installation d\'un serveur Memcached et des lib php-memcached ou php-memcache. Il peut être activer après l\'installation.',
		'ServerAddressMemcachedDesc' => 'Nom ou adresse ip du serveur memcached, généralement \'localhost\' quand le serveur est installé sur la même machine que le serveur web',
		'ServerPortMemcachedDesc' => 'Port du serveur memcached. Défaut : 11211',
		'EnabledMemcached' => 'Activer Memcached',
		'DatabaseNoSQL' => 'Base de données CouchDB',
		'FailedToCreateAdminLogin' => 'Echec de la création du compte administrateur Speedealing.',
		'LinkedElementsInvalidDeleted' => '<b>%s</b> liaisons invalides ont été supprimées',
		'NothingToDelete' => 'Aucune liaison invalide trouvée',
		'SourceType' => 'Source',
		'TargetType' => 'Cible',
                // Upgrade
                'UpgradeOk' => 'Upgrade is ok !',
                'NewInstalledVersion' => 'Your new version is %s',
                'NeedUpgrade' => 'New Speedealing version !',
                'WarningUpgrade' => 'Installed version is %s, you must upgrade to %s. <br>Please contact your administrator.'
);
?>