<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$boxes = array(
		'CHARSET' => 'UTF-8',
		'BoxLastRssInfos' => 'Rss informacji',
		'BoxLastProducts' => 'Ostatnie produkty / usługi',
		'BoxLastProductsInContract' => 'Ostatnia zakontraktowanych produktów / usług',
		'BoxLastSupplierBills' => 'Ostatnia dostawcy faktur',
		'BoxLastCustomerBills' => 'Ostatnia klienta faktury',
		'BoxLastProposals' => 'Ostatnia propozycji',
		'BoxLastProspects' => 'Ostatnia perspektywy',
		'BoxLastCustomers' => 'Ostatnia klientów',
		'BoxLastCustomerOrders' => 'Ostatnia zamówień',
		'BoxLastSuppliers' => 'Ostatnia dostawców',
		'BoxLastBooks' => 'Ostatnie książki',
		'BoxLastActions' => 'Ostatnie działania',
		'BoxCurrentAccounts' => 'Rachunki bieżące saldo',
		'BoxSalesTurnover' => 'Obrót',
		'BoxTitleLastBooks' => 'Ostatnia %s rejestrowane książek',
		'BoxTitleNbOfCustomers' => 'Nombre de klienta',
		'BoxTitleLastRssInfos' => 'Ostatnie wieści z %s %s',
		'BoxTitleLastProducts' => 'Ostatnia %s zmodyfikowane produkty / usługi',
		'BoxTitleLastCustomerOrders' => 'Ostatnia %s zmodyfikowane zamówień',
		'BoxTitleLastSuppliers' => 'Ostatnia %s zarejestrowanych dostawców',
		'BoxTitleLastCustomers' => 'Ostatnia %s zarejestrowanych klientów',
		'BoxTitleLastCustomersOrProspects' => 'Ostatnia %s zarejestrowanych klientów lub potencjalnych klientów',
		'BoxTitleLastPropals' => 'Ostatnia %s rejestrowane propozycje',
		'BoxTitleLastCustomerBills' => 'Ostatnia %s klienta faktury',
		'BoxTitleLastSupplierBills' => 'Ostatnia %s dostawcy faktur',
		'BoxTitleLastProspects' => 'Ostatnia %s rejestrowane perspektywy',
		'BoxTitleCurrentAccounts' => 'Salda na rachunku obrotów bieżących',
		'BoxTitleSalesTurnover' => 'Obrót',
		'BoxMyLastBookmarks' => 'Moje ostatnie %s zakładek',
		'FailedToRefreshDataInfoNotUpToDate' => 'Nie można odświeżyć RSS topnika. Ostatnie udane odświeżenie data: %s',
		'NoRecordedBookmarks' => 'No bookmarks defined. Click <a href=Nie zdefiniowano zakładki. Kliknij <a href="%s">tutaj,</a> aby dodać zakładki.',
		'NoRecordedCustomers' => 'Nr zarejestrowanych klientów',
		'BoxTitleLastActionsToDo' => 'Ostatnia %s do działania',
		'NoActionsToDo' => 'Brak działań do',
		'NoRecordedOrders' => 'Nr rejestrowane klienta zamówienia',
		'NoRecordedProposals' => 'Nr zarejestrowanych wniosków',
		'NoRecordedInvoices' => 'Nr rejestrowane klienta faktury',
		'NoRecordedSupplierInvoices' => 'Nr rejestrowane dostawcy faktur',
		'LastRefreshDate' => 'Ostatnia odświeżyć daty',
		'NoRecordedProducts' => 'Nr zarejestrowane produkty / usługi',
		'NoRecordedProspects' => 'Nr rejestrowane perspektywy',
		'NoContractedProducts' => 'Brak produktów / usług zakontraktowanych',
		'BoxOldestUnpaidCustomerBills' => 'Najstarszego klienta niezapłaconych faktur',
		'BoxOldestUnpaidSupplierBills' => 'Najstarszy dostawcy niezapłaconych faktur',
		'BoxTotalUnpaidCustomerBills' => 'Suma niezapłaconych faktur klienta',
		'BoxTotalUnpaidSuppliersBills' => 'Suma niezapłaconych faktur dostawcy',
		'BoxTitleOldestUnpaidCustomerBills' => 'Najstarszy %s klienta niezapłaconych faktur',
		'BoxTitleOldestUnpaidSupplierBills' => 'Najstarszy %s dostawcy niezapłaconych faktur',
		'BoxTitleTotalUnpaidCustomerBills' => 'Należne wpłaty klienta faktury',
		'BoxTitleTotalUnpaidSuppliersBills' => 'Zaległej płatności za faktury dostawcy',
		'NoUnpaidCustomerBills' => 'Nr klienta niezapłaconych faktur',
		'NoUnpaidSupplierBills' => 'Nr dostawcy niezapłaconych faktur',
		'BoxLastContracts' => 'Siste kontrakter',
		'LastRefreshDate' => 'Siste oppdatering dato',
		'BoxTitleLastContracts' => 'Siste %s kontrakter',
		'NoModifiedSupplierBills' => 'Ingen registrert leverandørens faktura',
		'NoRecordedProducts' => 'Ingen registrert produkter / tjenester',
		'NoRecordedProspects' => 'Ingen registrert utsikter',
		'NoContractedProducts' => 'Ingen produkter / tjenester innleide',
		'NoRecordedContracts' => 'Ingen registrert kontrakter',
		'BoxLastContracts' => 'Laatste contracten',
		'BoxTitleLastContracts' => 'Laatste %s contracten',
		'NoModifiedSupplierBills' => 'Geen geregistreerd leverancier facturen',
		'NoRecordedContracts' => 'Geen geregistreerde overeenkomsten',
		'BoxOldestUnpaidCustomerBills' => 'Oudste onbetaalde facturen klant',
		'BoxOldestUnpaidSupplierBills' => 'Oudste onbetaalde facturen van de leverancier',
		'BoxLastContracts' => 'Laatste contracten',
		'BoxTotalUnpaidCustomerBills' => 'Totaal aantal onbetaalde facturen klant',
		'BoxTotalUnpaidSuppliersBills' => 'Totaal aantal onbetaalde facturen van de leverancier',
		'BoxTitleOldestUnpaidCustomerBills' => 'Oudste %s onbetaalde facturen klant',
		'BoxTitleOldestUnpaidSupplierBills' => 'Oudste %s onbetaalde facturen van de leverancier',
		'BoxTitleTotalUnpaidCustomerBills' => 'Onbetaalde facturen klant',
		'BoxTitleTotalUnpaidSuppliersBills' => 'Onbetaalde facturen van de leverancier',
		'BoxTitleLastContracts' => 'Laatste %s contracten',
		'NoModifiedSupplierBills' => 'Geen geregistreerd leverancier facturen',
		'NoRecordedContracts' => 'Geen geregistreerde overeenkomsten',
		'BoxLastContracts' => 'Ostatnie zamówienia',
		'BoxTitleLastProductsInContract' => 'Ostatnie %s produktów / usług w umowie',
		'BoxTitleLastContracts' => 'Ostatnie %s umów',
		'NoModifiedSupplierBills' => 'Nie zarejestrowane faktury dostawcy',
		'NoRecordedContracts' => 'Umów nie zarejestrowanych',
		'BoxTitleLastModifiedSuppliers' => '%s ostatnio zmodyfikowano dostawców',
		'BoxTitleLastModifiedCustomers' => '%s ostatnio zmodyfikowano klientów',
		'BoxTitleLastModifiedProspects' => 'Ostatnio zmodyfikowano perspektywy %s',
		'BoxLastContacts' => 'Ostatnie kontakty / adresy',
		'BoxLastMembers' => 'Ostatnie użytkowników',
		'BoxTitleLastModifiedMembers' => 'Ostatnie %s zmodyfikowane użytkowników',
		'BoxTitleLastModifiedContacts' => 'Ostatnie %s zmodyfikowane kontakty / adresy',
		'BoxOldestExpiredServices' => 'Najstarszy aktywny minął usługi',
		'BoxLastExpiredServices' => 'Ostatnie %s Najstarsze kontakty z aktywnymi przeterminowanych usług',
		'BoxTitleLastModifiedDonations' => 'Ostatnie %s modyfikowane darowizn',
		'BoxTitleLastModifiedExpenses' => 'Ostatnie %s modyfikowane wydatki',
		'ClickToAdd' => 'Kliknij tutaj, aby dodać.',
		'NoRecordedContacts' => 'Brak zapisanych kontaktów',
);
?>