<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Kategoria',
		'Categories' => 'Kategorie',
		'Rubrique' => 'Kategoria',
		'Rubriques' => 'Kategorie',
		'categories' => 'kategorie',
		'TheCategorie' => 'Kategoria',
		'NoCategoryYet' => 'Nr kategorii tego typu tworzone',
		'In' => 'W',
		'AddIn' => 'Dodaj w',
		'modify' => 'modyfikować',
		'Classify' => 'Klasyfikacja',
		'CategoriesArea' => 'Kategorie obszarze',
		'ProductsCategoriesArea' => 'Produkty / Usługi kategorii powierzchni',
		'SuppliersCategoriesArea' => 'Dostawcy kategorii powierzchni',
		'CustomersCategoriesArea' => 'Klienci kategorii powierzchni',
		'ThirdPartyCategoriesArea' => 'Stron trzecich kategorii powierzchni',
		'MembersCategoriesArea' => 'Członków kategorii obszaru',
		'MainCats' => 'Główne kategorie',
		'SubCats' => 'Podkategorie',
		'CatStatistics' => 'Statystyki',
		'CatList' => 'Lista catgories',
		'AllCats' => 'Wszystkie kategorie',
		'ViewCat' => 'Wyświetl kategorii',
		'NewCat' => 'Dodaj kategorię',
		'NewCategory' => 'Nowa kategoria',
		'ModifCat' => 'Modyfikacja kategorii',
		'CatCreated' => 'Kategoria utworzonych',
		'CreateCat' => 'Tworzenie kategorii',
		'CreateThisCat' => 'Tworzenie tej kategorii',
		'ValidateFields' => 'Validate pola',
		'NoSubCat' => 'Brak podkategorii.',
		'SubCatOf' => 'Podkategoria',
		'FoundCats' => 'Znaleziono kategorii',
		'FoundCatsForName' => 'Kategorie znaleźć na imię i nazwisko:',
		'FoundSubCatsIn' => 'Podkategorie w kategorii',
		'ErrSameCatSelected' => 'Wybrano tej samej kategorii, kilka razy',
		'ErrForgotCat' => 'You forgot wybrać kategorię',
		'ErrForgotField' => 'Zapomniałeś o zakresie',
		'ErrCatAlreadyExists' => 'Ta nazwa jest już używany',
		'AddProductToCat' => 'Dodaj produkt do kategorii?',
		'ImpossibleAddCat' => 'Niemożliwe, aby dodać kategorię',
		'ImpossibleAssociateCategory' => 'Niemożliwe włączają do kategorii',
		'WasAddedSuccessfully' => '<b> %s</b> został dodany pomyślnie.',
		'ObjectAlreadyLinkedToCategory' => 'Element jest już powiązana z tej kategorii.',
		'CategorySuccessfullyCreated' => 'Ta kategoria %s został dodany pomyślnie.',
		'ProductIsInCategories' => 'Produktu / usługi posiada do następujących kategorii',
		'SupplierIsInCategories' => 'Trzeciej posiada do następujących kategorii dostawców',
		'CompanyIsInCustomersCategories' => 'Wspomniana strona trzecia posiada do następujących klientów / perspektywy kategorii',
		'CompanyIsInSuppliersCategories' => 'Wspomniana strona trzecia posiada do następujących kategorii dostawców',
		'MemberIsInCategories' => 'Ten użytkownik posiada do następujących kategorii użytkowników',
		'ProductHasNoCategory' => 'Ten produkt / usługa nie jest w żaden kategorii',
		'SupplierHasNoCategory' => 'To dostawca nie jest w żaden kategorii',
		'CompanyHasNoCategory' => 'Ta firma nie jest w żaden kategorii',
		'MemberHasNoCategory' => 'Członek ten nie jest w żadnym kategorii',
		'ClassifyInCategory' => 'Klasyfikacja w kategorii',
		'NoneCategory' => 'Żaden',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Ta kategoria już istnieje w tym samym miejscu',
		'ReturnInProduct' => 'Powrót do produktów / usług karty',
		'ReturnInSupplier' => 'Powrót do dostawcy kart',
		'ReturnInCompany' => 'Powrót do klienta / perspektywa karty',
		'ContentsVisibleByAll' => 'Zawartość będzie widoczny przez wszystkich',
		'ContentsVisibleByAllShort' => 'Zawartość widoczna przez wszystkie',
		'ContentsNotVisibleByAllShort' => 'Treść nie jest widoczna dla wszystkich',
		'CategoriesTree' => 'Kategorie drzewa',
		'DeleteCategory' => 'Usuwanie kategorii',
		'ConfirmDeleteCategory' => 'Czy na pewno chcesz usunąć tę kategorię?',
		'RemoveFromCategory' => 'Usuń powiązanie z kategorii',
		'RemoveFromCategoryConfirm' => 'Czy na pewno chcesz usunąć związek między transakcją i kategorii?',
		'NoCategoriesDefined' => 'Nr kategorii zdefiniowanych',
		'SuppliersCategoryShort' => 'Dostawcy kategorii',
		'CustomersCategoryShort' => 'Klienci kategorii',
		'ProductsCategoryShort' => 'Produkty kategorii',
		'MembersCategoryShort' => 'Członków kategorii',
		'SuppliersCategoriesShort' => 'Dostawcy kategorii',
		'CustomersCategoriesShort' => 'Klienci kategorii',
		'CustomersProspectsCategoriesShort' => 'Custo. / prosp. kategorie',
		'ProductsCategoriesShort' => 'Produkty kategorii',
		'MembersCategoriesShort' => 'Członków kategorii',
		'ThisCategoryHasNoProduct' => 'Ta kategoria nie zawiera żadnych produktów.',
		'ThisCategoryHasNoSupplier' => 'Ta kategoria nie zawiera żadnego dostawcy.',
		'ThisCategoryHasNoCustomer' => 'Ta kategoria nie zawiera żadnych klientów.',
		'ThisCategoryHasNoMember' => 'Ta kategoria nie zawiera żadnych członków.',
		'AssignedToCustomer' => 'Przypisany do klienta',
		'AssignedToTheCustomer' => 'Przypisany do klienta',
		'InternalCategory' => 'Inernal kategorii',
		'CategoryContents' => 'Kategoria treści',
		'CategId' => 'Kategoria id',
		'CatSupList' => 'Lista kategorii dostawcy',
		'CatCusList' => 'Lista klientów / perspektywa kategorii',
		'CatProdList' => 'Lista produktów kategorii',
		'CatMemberList' => 'Lista członków kategorii',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>