<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Komercyjne',
		'CommercialArea' => 'Powierzchnia handlowa',
		'CommercialCard' => 'Commercial karty',
		'CustomerArea' => 'Klienci obszaru',
		'Customer' => 'Klient',
		'Customers' => 'Klienci',
		'Prospect' => 'Prospect',
		'Prospects' => 'Perspektywy',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Usuń działania / zadania',
		'NewAction' => 'Nowe działania / zadania',
		'AddAction' => 'Dodaj działania / zadania',
		'AddAnAction' => 'Dodaj działania / zadania',
		'AddActionRendezVous' => 'Dodać zadanie Rendezvous',
		'Rendez-Vous' => 'Rendezvous',
		'ConfirmDeleteAction' => 'Czy na pewno chcesz usunąć to zadanie?',
		'CardAction' => 'Działanie karty',
		'PercentDone' => 'Procent zrobić',
		'ActionOnCompany' => 'Zadanie o firmie',
		'ActionOnContact' => 'Zadanie o kontakt',
		'TaskRDV' => 'Spotkania',
		'TaskRDVWith' => 'Spotkanie z %s',
		'ShowTask' => 'Pokaż zadanie',
		'ShowAction' => 'Pokaż działania',
		'ActionsReport' => 'Działania raport',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Przedstawiciel handlowy',
		'SalesRepresentatives' => 'Przedstawiciele handlowi',
		'SalesRepresentativeFollowUp' => 'Przedstawiciel handlowy (kontynuacja)',
		'SalesRepresentativeSignature' => 'Przedstawiciel handlowy (podpis)',
		'CommercialInterlocutor' => 'Commercial interlokutora',
		'ErrorWrongCode' => 'Niewłaściwy kod',
		'NoSalesRepresentativeAffected' => 'Nr szczególności przedstawiciel handlowy dotknięte',
		'ShowCustomer' => 'Pokaż klienta',
		'ShowProspect' => 'Pokaż perspektywa',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Lista perspektyw',
		'ListOfCustomers' => 'Lista klientów',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'Ostatnia %s wykonane zadania',
		'LastRecordedTasks' => 'Ostatnio zapisane zadania',
		'LastActionsToDo' => 'Ostatnia %s najstarszych działania nie zakończyły',
		'DoneAndToDoActionsFor' => 'Gotowe i zadania Aby zrobić dla %s',
		'DoneAndToDoActions' => 'Sporządzono zadań oraz do uczynienia',
		'DoneActions' => 'Sporządzono działania',
		'DoneActionsFor' => 'Sporządzono działań dla %s',
		'ToDoActions' => 'Niekompletne działań',
		'ToDoActionsFor' => 'Niekompletne działań na rzecz %s',
		'SendPropalRef' => 'Wyślij handlowych wniosku %s',
		'SendOrderRef' => 'Wyślij zamówienie %s',
		'StatusNotApplicable' => 'Nie dotyczy',
		'StatusActionToDo' => 'Aby to zrobić',
		'StatusActionDone' => 'Zrobione',
		'StatusActionInProcess' => 'W procesie',
		'MyActionsAsked' => 'Działania Mam zapisane',
		'MyActionsToDo' => 'Działania mam zrobić',
		'MyActionsDone' => 'Działania wpływa do mnie',
		'TasksHistoryForThisContact' => 'Działania na rzecz tego kontaktu',
		'LastProspectDoNotContact' => 'Nie kontakt',
		'LastProspectNeverContacted' => 'Nigdy nie skontaktował',
		'LastProspectToContact' => 'Aby skontaktować się',
		'LastProspectContactInProcess' => 'Kontakt w procesie',
		'LastProspectContactDone' => 'Kontakt zrobić',
		'DateActionPlanned' => 'Data działania planowane na',
		'DateActionDone' => 'Data zrobienia działania',
		'ActionAskedBy' => 'Działanie zadawane przez',
		'ActionAffectedTo' => 'Wpływ na działanie',
		'ActionDoneBy' => 'Działania wykonywane przez',
		'ActionUserAsk' => 'Zarejestrowane przez',
		'ErrorStatusCantBeZeroIfStarted' => 'Jeżeli pole <b>\'Data zrobienia</b> "jest wypełniona, rozpoczęto działania (lub gotowy), więc pole" <b>Status</b> "nie może być 0%%.',
		'ActionAC_TEL' => 'Telefon',
		'ActionAC_FAX' => 'Wyślij faks',
		'ActionAC_PROP' => 'Wyślij wniosek',
		'ActionAC_EMAIL' => 'Wyślij e-mail',
		'ActionAC_RDV' => 'Spotkania',
		'ActionAC_FAC' => 'Wyślij rozliczeniowe',
		'ActionAC_REL' => 'Wyślij rozliczeniowe (przypomnienie)',
		'ActionAC_CLO' => 'Blisko',
		'ActionAC_EMAILING' => 'Wyślij e-maila masa',
		'ActionAC_COM' => 'Wyślij zamówienie pocztą',
		'ActionAC_SHIP' => 'Wyślij wysyłki za pośrednictwem poczty',
		'ActionAC_SUP_ORD' => 'aby dostawca przesłać pocztą',
		'ActionAC_SUP_INV' => 'fakturze dostawcy przesłać pocztą',
		'ActionAC_OTH' => 'Inny',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Stan perspektywa',
		'DraftPropals' => 'Projekt komercyjne propozycje',
		'SearchPropal' => 'Szukaj komercyjnego projektu'
);
?>