<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$compta = array(
		'CHARSET' => 'UTF-8',
		'Accountancy' => 'Księgowość',
		'AccountancyCard' => 'Księgowość karty',
		'Treasury' => 'Skarbiec',
		'MenuFinancial' => 'Finansowego',
		'OptionMode' => 'Opcja dla księgowych',
		'OptionModeVirtual' => 'Opcja Kredyty-Debits',
		'OptionModeVirtualDesc' => 'W tym kontekście, obrót jest obliczana na fakturach (data zatwierdzenia). Gdy te faktury są należne, czy zostały zapłacone, czy nie są one wymienione w obrocie wyjście.',
		'FeatureIsSupportedInInOutModeOnly' => 'Funkcja dostępna tylko w KREDYTÓW-DŁUGI rachunkowych trybu (patrz Rachunkowych moduł konfiguracji)',
		'Param' => 'Instalator',
		'AccountsGeneral' => 'Konta',
		'Account' => 'Konto',
		'Accounts' => 'Konta',
		'BillsForSuppliers' => 'Rachunki dla dostawców',
		'Income' => 'Przychody',
		'Outcome' => 'Rezultat',
		'ReportInOut' => 'Przychody / Rezultat',
		'PaymentsNotLinkedToInvoice' => 'Płatności związane z wszelkich faktur, więc nie są związane z jakąkolwiek osobą trzecią',
		'PaymentsNotLinkedToUser' => 'Płatności związane z dowolnego użytkownika',
		'Profit' => 'Zysk',
		'Balance' => 'Saldo',
		'Debit' => 'Rozchody',
		'Credit' => 'Kredyt',
		'Withdrawal' => 'Wycofanie',
		'Withdrawals' => 'Wypłaty',
		'AmountHTVATRealReceived' => 'HT zebrane',
		'AmountHTVATRealPaid' => 'HT paid',
		'VATToPay' => 'VAT do zapłaty',
		'VATReceived' => 'VAT otrzymana',
		'VATToCollect' => 'VAT do gromadzenia',
		'VATSummary' => 'VAT Podsumowanie',
		'VATPaid' => 'VAT paid',
		'VATCollected' => 'VAT zebrane',
		'ToPay' => 'Aby zapłacić',
		'ToGet' => 'Aby powrócić',
		'TaxAndDividendsArea' => 'Podatek, składki na ubezpieczenie społeczne i dywidendy obszarze',
		'SocialContribution' => 'Społeczny wkład',
		'SocialContributions' => 'Składek na ubezpieczenia społeczne',
		'MenuTaxAndDividends' => 'Podatki i dywidendy',
		'MenuSocialContributions' => 'Składek na ubezpieczenia społeczne',
		'MenuNewSocialContribution' => 'Nowe Wkład',
		'NewSocialContribution' => 'Nowe społecznego wkładu',
		'ContributionsToPay' => 'Składki do zapłaty',
		'AccountancyTreasuryArea' => 'Księgowość / Skarbu obszarze',
		'AccountancySetup' => 'Księgowość konfiguracji',
		'NewPayment' => 'Nowa płatność',
		'Payments' => 'Płatności',
		'PaymentCustomerInvoice' => 'Klient płatności faktury',
		'PaymentSupplierInvoice' => 'Dostawca płatności faktury',
		'PaymentSocialContribution' => 'Społeczny wkład płatności',
		'PaymentVat' => 'Zapłaty podatku VAT',
		'ListPayment' => 'Wykaz płatności',
		'ListOfPayments' => 'Wykaz płatności',
		'ListOfCustomerPayments' => 'Lista klientów płatności',
		'ListOfSupplierPayments' => 'Lista dostawców płatności',
		'DatePayment' => 'Data płatności',
		'NewVATPayment' => 'Nowe zapłaty podatku VAT',
		'VATPayment' => 'Zapłaty podatku VAT',
		'VATPayments' => 'Płatności VAT',
		'TotalToPay' => 'Razem do zapłaty',
		'TotalVATReceived' => 'Razem VAT otrzymana',
		'CustomerAccountancyCode' => 'Klient rachunkowych kod',
		'AccountNumberShort' => 'Numer konta',
		'AccountNumber' => 'Numer konta',
		'NewAccount' => 'Nowe konto',
		'SalesTurnover' => 'Obrót',
		'ByThirdParties' => 'Bu trzecich',
		'ByUserAuthorOfInvoice' => 'Na fakturze autora',
		'AccountancyExport' => 'Księgowość eksportu',
		'ErrorWrongAccountancyCodeForCompany' => 'Bad klienta rachunkowych kod %s',
		'SuppliersProductsSellSalesTurnover' => 'Obrotów generowanych przez sprzedaż dostawców produktów.',
		'CheckReceipt' => 'Sprawdź depozyt',
		'CheckReceiptShort' => 'Sprawdź depozyt',
		'NewCheckReceipt' => 'Nowe zniżki',
		'NewCheckDeposit' => 'Nowe sprawdzić depozytu',
		'NewCheckDepositOn' => 'Nowe sprawdzić depozytu na konto: %s',
		'NoWaitingChecks' => 'Nie czekając na kontrole depozytów.',
		'DateChequeReceived' => 'Czek odbiór daty wejścia',
		'NbOfCheques' => 'Nb czeków',
		'PaySocialContribution' => 'Płacić składki społeczne',
		'ConfirmPaySocialContribution' => 'Czy na pewno chcesz sklasyfikować ten społecznego wkładu wypłatę?',
		'DeleteSocialContribution' => 'Usuń społecznego wkładu',
		'ConfirmDeleteSocialContribution' => 'Czy na pewno chcesz usunąć ten wkład społeczny?',
		'ExportDataset_tax_1' => 'Składek na ubezpieczenia społeczne i płatności',
		'AnnualSummaryDueDebtMode' => 'Bilan et des recettes dpenses, rsum annuel, pl <b>trybie %sCrances-dettes %s comptabilit</b> dit <b>d\'engagement.</b>',
		'AnnualSummaryInputOutputMode' => 'Bilan et des recettes dpenses, rsum annuel, pl <b>trybie %sRecettes-Dpenses %s comptabilit</b> dit <b>de Caisse.</b>',
		'AnnualByCompaniesDueDebtMode' => 'Bilan et des recettes dpenses, dtail par tiers, en <b>trybie %sCrances-dettes %s comptabilit</b> dit <b>d\'engagement.</b>',
		'AnnualByCompaniesInputOutputMode' => 'Bilan et des recettes dpenses, dtail par tiers, en <b>trybie %sRecettes-Dpenses %s comptabilit</b> dit <b>de Caisse.</b>',
		'SeeReportInInputOutputMode' => 'Voir le <b>rapport %sRecettes-Dpenses %s comptabilit</b> dit pour un <b>Caisse de</b> calcul sur les paiements effectivement raliss',
		'SeeReportInDueDebtMode' => 'Voir le <b>rapport %sCrances-dettes %s comptabilit</b> dit <b>d\'engagement</b> pour un calcul sur les factures mises',
		'RulesResultDue' => '- Kwoty wykazane są łącznie ze wszystkimi podatkami <br> - Obejmuje ona zaległych faktur, kosztów i podatku VAT, czy są one wypłacane lub nie. <br> - Jest on oparty na zatwierdzanie daty faktur i podatku VAT oraz o terminie płatności na wydatki.',
		'RulesResultInOut' => '- Kwoty wykazane są łącznie ze wszystkimi podatkami <br> - Obejmuje on rzeczywiste płatności faktur, koszty i VAT. <br> - Jest on oparty na terminy płatności faktur, koszty ANF VAT. <br>',
		'RulesCADue' => '- Obejmuje ona klientów z powodu faktury, czy są one wypłacane, czy nie. <br> - Jest on oparty na zatwierdzenie daty tych faktur. <br>',
		'RulesCAIn' => '- Obejmuje wszystkie skuteczne płatności faktur otrzymanych od klientów. <br> - Jest on oparty na dacie płatności tych faktur <br>',
		'PercentOfInvoice' => '%%/faktury',
		'Dispatch' => 'Dysponowanie',
		'Dispatched' => 'Wysłane',
		'ToDispatch' => 'Do wysyłki',
		'ReportTurnover' => 'Obrót',
		'NotUsedForGoods' => 'Nie używany od towarów',
		'OptionModeTrue' => 'Opcja Input-Output',
		'OptionModeTrueDesc' => 'W tym kontekście, obrót jest obliczana na płatności (data płatności). \ nThe ważności danych jest zapewniona tylko wtedy, gdy księgowości jest zbadane przez wejścia / wyjścia na rachunkach za pomocą faktur.',
		'ShowVatPayment' => 'Pokaż zapłaty podatku VAT',
		'SupplierAccountancyCode' => 'Dostawca rachunkowych kod',
		'AlreadyPaid' => 'Już wypłaconych',
		'TaxModuleSetupToModifyRules' => 'Przejdź do <a href="%s">konfiguracji modułu</a> , aby zmienić zasady obliczania',
		'VATReportBuildWithOptionDefinedInModule' => 'Kwoty wyświetlane tutaj są obliczane na zasadach określonych przez organy podatkowe moduł konfiguracji.',
		'SocialContributionsPayments' => 'Płatności składek na ubezpieczenia społeczne',
		'VATReportByCustomersInInputOutputMode' => 'Sprawozdanie z VAT klienta i opłacane (paragon VAT)',
		'VATReportByCustomersInDueDebtMode' => 'Sprawozdanie z VAT klienta i płatny (stawka VAT)',
		'VATReportByQuartersInInputOutputMode' => 'Sprawozdanie stawki VAT i wypłacane klejnoty (paragon VAT)',
		'VATReportByQuartersInDueDebtMode' => 'Sprawozdanie stawki VAT i gromadzonych zapłaty (stawka VAT)',
		'SeeVATReportInInputOutputMode' => 'Zobacz raport <b>%sVAT encasement%s</b> na standardowe obliczenia',
		'SeeVATReportInDueDebtMode' => '<b>%sVAT</b> sprawozdanie Zobacz <b>na flow%s</b> do obliczenia z opcją na przepływ',
		'RulesVATIn' => 'Dla usług, raport zawiera regulacji podatku VAT faktycznie otrzymane lub wydane na podstawie daty zapłaty. <br> - Dla dobra materialne, zawiera faktur VAT na podstawie daty zatwierdzenia faktury.',
		'RulesVATDue' => 'Dla usług, raport zawiera faktur VAT należny, zapłacone czy nie, w zależności od daty zatwierdzenia tych rachunków. <br> - Dla dobra materialne, zawiera VAT faktury, w zależności od daty zatwierdzenia faktury.',
		'OptionVatInfoModuleComptabilite' => 'Uwaga: W przypadku dóbr materialnych, należy użyć daty dostawy do bardziej sprawiedliwego.',
		'ThirdPartyMustBeEditAsCustomer' => 'Osoby trzecie muszą być określone jako klient',
		'AmountToBeCharged' => 'Łączna kwota do zapłaty:',
		'ProposalStats' => 'Statystyki na temat propozycji',
		'OrderStats' => 'Statystyki dotyczące zamówień',
		'InvoiceStats' => 'Statystyki na rachunkach',
		'SellsJournal' => 'Dziennik sprzedaży',
		'PurchasesJournal' => 'Dziennik zakupów',
		'DescSellsJournal' => 'Dziennik sprzedaży',
		'DescPurchasesJournal' => 'Dziennik zakupów',
		'InvoiceRef' => 'Faktura ref.',
		'CodeNotDef' => 'Nie zdefiniowane',
		'RemainingAmountPayment' => 'Płatność pozostałej kwoty:',
		'LT2SummaryES' => 'Balans IRPF',
		'LT2PaidES' => 'IRPF Płatny',
		'LT2CustomerES' => 'Sprzedaż IRPF',
		'LT2SupplierES' => 'Zakupy IRPF',
		'newLT2PaymentES' => 'Nowy IRPF płatności',
		'LT2PaymentES' => 'Płatność IRPF',
		'LT2PaymentsES' => 'Płatności IRPF',
		'DepositsAreNotIncluded' => '- Faktury depozytów są ani też',
		'DepositsAreIncluded' => '- Faktury depozytowe są zawarte',
		'LT2ReportByCustomersInInputOutputModeES' => 'Raport osób trzecich IRPF',
		'RulesVATInServices' => '- W przypadku usług, raport zawiera przepisy VAT faktycznie otrzymane lub wydane na podstawie daty płatności. <br> - W przypadku środków trwałych, to obejmuje faktur VAT na podstawie daty wystawienia faktury.',
		'RulesVATInProducts' => '- W przypadku środków trwałych, to obejmuje faktur VAT na podstawie daty wystawienia faktury.',
		'RulesVATDueServices' => '- W przypadku usług, raport zawiera faktur VAT należnego, płatnego lub nie, w oparciu o daty wystawienia faktury.',
		'RulesVATDueProducts' => '- W przypadku środków trwałych, to obejmuje faktury VAT, w oparciu o daty wystawienia faktury.',
		'AddRemind' => 'Wysłanie dostępną kwotę',
		'RemainToDivide' => 'Pozostają do wysyłki:',
		'WarningDepositsNotIncluded' => 'Depozyty faktury nie są zawarte w tej wersji z tego modułu księgowego.',
);
?>