<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$orders = array(
		'CHARSET' => 'UTF-8',
		'OrdersArea' => 'Klienci dziedzinie zamówień',
		'SuppliersOrdersArea' => 'Dostawcy dziedzinie zamówień',
		'OrderCard' => 'Zamów kartę',
		'OrderId' => 'Order Id',
		'Order' => 'Porządek',
		'Orders' => 'Zamówienia',
		'OrderLine' => 'Zamówienie linii',
		'OrderLines' => 'Order lines',
		'OrderFollow' => 'Kontynuacja',
		'OrderDate' => 'Kolejność Data',
		'OrderToProcess' => 'Aby proces',
		'NewOrder' => 'New Order',
		'ToOrder' => 'Zamów',
		'MakeOrder' => 'Zamów',
		'SupplierOrder' => 'Dostawca celu',
		'SuppliersOrders' => 'Dostawcy zleceń',
		'SuppliersOrdersRunning' => 'Aktualna dostawców zleceń',
		'CustomerOrder' => 'Zamówieniem',
		'CustomersOrders' => 'Klienci zleceń',
		'CustomersOrdersRunning' => 'Aktualna klientów zleceń',
		'CustomersOrdersAndOrdersLines' => 'Zamówień i zleceń linii',
		'OrdersToValid' => 'Zamówienia do ważnych',
		'OrdersToBill' => 'Zamówienia na rachunku',
		'OrdersInProcess' => 'Zamówienia w procesie',
		'OrdersToProcess' => 'Zamówienia na proces',
		'SuppliersOrdersToProcess' => 'Dostawcy zamówienia na przetwarzanie',
		'StatusOrderCanceledShort' => 'Odwołany',
		'StatusOrderDraftShort' => 'Szkic',
		'StatusOrderValidatedShort' => 'Zatwierdzona',
		'StatusOrderSentShort' => 'W procesie',
		'StatusOrderSent' => 'Shipment in process',
		'StatusOrderOnProcessShort' => 'Na proces',
		'StatusOrderProcessedShort' => 'Przetworzone',
		'StatusOrderToBillShort' => 'Do rachunku',
		'StatusOrderToBill2Short' => 'To bill',
		'StatusOrderApprovedShort' => 'Zatwierdzony',
		'StatusOrderRefusedShort' => 'Odmowa',
		'StatusOrderToProcessShort' => 'Aby proces',
		'StatusOrderReceivedPartiallyShort' => 'Częściowo otrzymała',
		'StatusOrderReceivedAllShort' => 'Wszystko otrzymała',
		'StatusOrderCanceled' => 'Odwołany',
		'StatusOrderDraft' => 'Projekt (musi zostać zatwierdzone)',
		'StatusOrderNew' => 'New order (needs to be validated)',
		'StatusOrderProcessing' => 'Processing',
		'StatusOrderValidated' => 'Zatwierdzona',
		'StatusOrderOnProcess' => 'Na proces',
		'StatusOrderProcessed' => 'Przetworzone',
		'StatusOrderToBill' => 'Do rachunku',
		'StatusOrderToBill2' => 'To bill',
		'StatusOrderApproved' => 'Zatwierdzony',
		'StatusOrderRefused' => 'Odmowa',
		'StatusOrderError' => 'Error',
		'StatusOrderReceivedPartially' => 'Częściowo otrzymała',
		'StatusOrderReceivedAll' => 'Wszystko otrzymała',
		'ShippingExist' => 'Przesyłka istnieje',
		'DraftOrWaitingApproved' => 'Projekt nie został jeszcze zatwierdzony lub sortowane',
		'DraftOrWaitingShipped' => 'Projekt lub zatwierdzonych jeszcze nie wysłane',
		'MenuOrdersToBill' => 'Zamówienia na rachunku',
		'MenuOrdersToBill2' => 'Orders to bill',
		'SearchOrder' => 'Szukaj celu',
		'Sending' => 'Wysyłanie',
		'Sendings' => 'Sendings',
		'ShipProduct' => 'Statek produktu',
		'Discount' => 'Rabat',
		'CreateOrder' => 'Tworzenie Zamówienie',
		'RefuseOrder' => 'Odmówić celu',
		'ApproveOrder' => 'Akceptuj zamówienie',
		'ValidateOrder' => 'Sprawdź zamówienie',
		'UnvalidateOrder' => 'Unvalidate zamówienie',
		'DeleteOrder' => 'Usuń zamówienie',
		'CancelOrder' => 'Anulować zamówienie',
		'AddOrder' => 'Dodaj zamówienie',
		'AddToMyOrders' => 'Dodaj do mojego zamówienia',
		'AddToOtherOrders' => 'Dodaj do zamówienia',
		'ShowOrder' => 'Pokaż zamówienie',
		'NoOpenedOrders' => 'Nie otworzył zamówień',
		'NoOtherOpenedOrders' => 'Żadne inne otwarte zamówienia',
		'OtherOrders' => 'Inne zamówienia',
		'LastOrders' => 'Ostatnia %s zamówień',
		'LastModifiedOrders' => 'Ostatnia %s zmodyfikowane zamówień',
		'LastClosedOrders' => 'Ostatnia %s zamkniętych zleceń',
		'AllOrders' => 'Wszystkie zlecenia',
		'NbOfOrders' => 'Liczba zleceń',
		'OrdersStatistics' => 'Zamówienia statystyk',
		'OrdersStatisticsSuppliers' => 'Dostawca zamówień statystyk',
		'NumberOfOrdersByMonth' => 'Liczba zleceń przez miesiąc',
		'AmountOfOrdersByMonthHT' => 'Kwota zamówienia przez miesiąc (po odliczeniu podatku)',
		'ListOfOrders' => 'Lista zamówień',
		'CloseOrder' => 'Zamknij celu',
		'ConfirmCloseOrder' => 'Czy na pewno chcesz zamknąć to zamówienie? Gdy zamówienie jest zamknięta, to może być rozliczone.',
		'ConfirmCloseOrderIfSending' => 'Czy na pewno chcesz zamknąć to zamówienie? Musisz zamknąć zamówienie tylko wtedy, gdy wszystkie wysyłki są zrobione.',
		'ConfirmDeleteOrder' => 'Czy na pewno chcesz usunąć to zamówienie?',
		'ConfirmValidateOrder' => 'Czy na pewno chcesz, aby potwierdzić tej kolejności pod <b>nazwą %s?</b>',
		'ConfirmUnvalidateOrder' => 'Czy na pewno chcesz przywrócić <b>%s</b> zamówień ze statusem projektu?',
		'ConfirmCancelOrder' => 'Czy na pewno chcesz anulować zamówienie?',
		'ConfirmMakeOrder' => 'Czy na pewno chcesz, aby potwierdzić wprowadzone tym celu <b>na %s?</b>',
		'GenerateBill' => 'Generowanie faktur',
		'ClassifyShipped' => 'Classify delivered',
		'ClassifyBilled' => 'Klasyfikacja "obciążonego"',
		'ComptaCard' => 'Księgowość karty',
		'DraftOrders' => 'Projekt zamówień',
		'RelatedOrders' => 'Podobne zamówienia',
		'OnProcessOrders' => 'Na proces zamówienia',
		'RefOrder' => 'Nr ref. porządek',
		'RefCustomerOrder' => 'Nr ref. zamówieniem',
		'CustomerOrder' => 'Zamówieniem',
		'RefCustomerOrderShort' => 'Nr ref. cust. porządek',
		'SendOrderByMail' => 'Wyślij zamówienie pocztą',
		'ActionsOnOrder' => 'Działania mające na celu',
		'NoArticleOfTypeProduct' => 'Nr artykułu typu "produktu", więc nie shippable artykule tej kolejności',
		'OrderMode' => 'Postanowienie metody',
		'AuthorRequest' => 'Wniosek autora',
		'UseCustomerContactAsOrderRecipientIfExist' => 'Użyj klienta adres, jeśli określone zamiast trzeciej kolejności adres odbiorcy adres',
		'RunningOrders' => 'Zamówienia na proces',
		'UserWithApproveOrderGrant' => 'Useres przyznane z "zatwierdza zamówienia zgody.',
		'PaymentOrderRef' => 'Płatność celu %s',
		'CloneOrder' => 'Clone celu',
		'ConfirmCloneOrder' => 'Czy na pewno chcesz klon tej <b>kolejności %s?</b>',
		'DispatchSupplierOrder' => '%s Odbiór aby dostawca',
		'DateDeliveryPlanned' => 'Date de livraison prévue',
		'SetDemandReason' => 'Définir l\'origine de la commande',
		////////// Types de contacts //////////
		'TypeContact_commande_internal_SALESREPFOLL' => 'Przedstawiciela w ślad za zamówienie klienta',
		'TypeContact_commande_internal_SHIPPING' => 'Przedstawiciela w ślad za koszty',
		'TypeContact_commande_external_BILLING' => 'kontakt faktury klienta',
		'TypeContact_commande_external_SHIPPING' => 'kontakt koszty klientów',
		'TypeContact_commande_external_CUSTOMER' => 'kontakt klienta w ślad za zamówienie',
		'TypeContact_order_supplier_internal_SALESREPFOLL' => 'Przedstawiciela w ślad za zamówienie dostawca',
		'TypeContact_order_supplier_internal_SHIPPING' => 'Przedstawiciela w ślad za koszty',
		'TypeContact_order_supplier_external_BILLING' => 'kontakt fakturze dostawcy',
		'TypeContact_order_supplier_external_SHIPPING' => 'kontakt koszty dostawcy',
		'TypeContact_order_supplier_external_CUSTOMER' => 'Kontaktowy dostawca w ślad za zamówienie',
		'Error_COMMANDE_SUPPLIER_ADDON_NotDefined' => 'Stała COMMANDE_SUPPLIER_ADDON nie zdefiniowane',
		'Error_COMMANDE_ADDON_NotDefined' => 'Stała COMMANDE_ADDON nie zdefiniowane',
		'Error_FailedToLoad_COMMANDE_SUPPLIER_ADDON_File' => 'Nie można załadować modułu pliku \' %s\'',
		'Error_FailedToLoad_COMMANDE_ADDON_File' => 'Nie można załadować modułu pliku \' %s\'',
		'Error_OrderNotChecked' => 'No orders to invoice selected',
		// Sources
		'OrderSource0' => 'Commercial wniosku',
		'OrderSource1' => 'Internet',
		'OrderSource2' => 'Poczta kampanii',
		'OrderSource3' => 'Telefon compain',
		'OrderSource4' => 'Faks kampanii',
		'OrderSource5' => 'Komercyjne',
		'OrderSource6' => 'Przechowywać',
		'QtyOrdered' => 'Ilosc sortowane',
		'AddDeliveryCostLine' => 'Dodaj dostawy koszt linii wskazujące wagi zamówienia',
		// Documents models
		'PDFEinsteinDescription' => 'Pełna kolejność modelu (logo. ..)',
		'PDFEdisonDescription' => 'Prosty model celu',
		// Orders modes
		'OrderByMail' => 'Poczta',
		'OrderByFax' => 'Faks',
		'OrderByEMail' => 'EMail',
		'OrderByWWW' => 'Online',
		'OrderByPhone' => 'Telefon',
		'CreateInvoiceForThisCustomer' => 'Bill orders',
		'NoOrdersToInvoice' => 'No orders billable',
		'CloseProcessedOrdersAutomatically' => 'Classify "Processed" all selected orders.',
		'MenuOrdersToBill2' => 'Orders to bill',
		'LinkedInvoices' => 'Linked invoices',
		'LinkedProposals' => 'Linked proposals'
);
?>