<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$propal = array(
		'CHARSET' => 'UTF-8',
		'Proposals' => 'Commercial propozycje',
		'Proposal' => 'Commercial wniosku',
		'ProposalShort' => 'Wniosek',
		'ProposalsDraft' => 'Projekt propozycji',
		'ProposalDraft' => 'Projekt wniosku handlowych',
		'ProposalsOpened' => 'Czynny propozycji',
		'Prop' => 'Commercial propozycje',
		'CommercialProposal' => 'Commercial wniosku',
		'CommercialProposals' => 'Commercial propozycje',
		'ProposalCard' => 'Karta Wniosek',
		'NewProp' => 'Nowy wniosek handlowych',
		'NewProposal' => 'Nowy wniosek handlowych',
		'NewPropal' => 'Nowa propozycja',
		'Prospect' => 'Prospect',
		'ProspectList' => 'Prospect listy',
		'DeleteProp' => 'Usuń handlowych wniosku',
		'ValidateProp' => 'Validate handlowych wniosku',
		'AddProp' => 'Dodaj projekt',
		'ConfirmDeleteProp' => 'Czy na pewno chcesz usunąć tę propozycję handlową?',
		'ConfirmValidateProp' => 'Czy na pewno chcesz, aby potwierdzić tę propozycję handlową?',
		'LastPropals' => 'Ostatnia %s propozycje',
		'LastClosedProposals' => 'Ostatnia %s zamknięte propozycje',
		'LastModifiedProposals' => 'Ostatnia %s zmodyfikowane propozycje',
		'AllPropals' => 'Wszystkie propozycje',
		'LastProposals' => 'Ostatnie propozycje',
		'SearchAProposal' => 'Szukaj projektu',
		'ProposalsStatistics' => 'Commercial propozycje "statystyki',
		'NumberOfProposalsByMonth' => 'Liczba miesięcy',
		'AmountOfProposalsByMonthHT' => 'Kwota przez miesiąc (po odliczeniu podatku)',
		'NbOfProposals' => 'Liczba propozycji',
		'ShowPropal' => 'Pokaż wniosku',
		'PropalsDraft' => 'Robocze',
		'PropalsOpened' => 'Czynny',
		'PropalsNotBilled' => 'Zamknięte nie rozliczone',
		'PropalStatusDraft' => 'Projekt (musi zostać zatwierdzone)',
		'PropalStatusValidated' => 'Zatwierdzona (projekt jest otwarty)',
		'PropalStatusOpened' => 'Zatwierdzona (projekt jest otwarty)',
		'PropalStatusClosed' => 'Zamknięte',
		'PropalStatusSigned' => 'Podpisano (do rachunku)',
		'PropalStatusNotSigned' => 'Nie podpisały (zamknięte)',
		'PropalStatusBilled' => 'Billed',
		'PropalStatusDraftShort' => 'Szkic',
		'PropalStatusValidatedShort' => 'Zatwierdzona',
		'PropalStatusOpenedShort' => 'Czynny',
		'PropalStatusClosedShort' => 'Zamknięte',
		'PropalStatusSignedShort' => 'Podpisano',
		'PropalStatusNotSignedShort' => 'Nie podpisała',
		'PropalStatusBilledShort' => 'Billed',
		'PropalsToClose' => 'Propozycji, aby zamknąć',
		'PropalsToBill' => 'Podpisano propozycji do rachunku',
		'ListOfProposals' => 'Lista propozycji',
		'ActionsOnPropal' => 'Działania na wniosek',
		'NoOpenedPropals' => 'Nie otworzył propozycji',
		'NoOtherOpenedPropals' => 'Żadne inne otwarte propozycji',
		'RefProposal' => 'Commercial wniosku ref',
		'SendPropalByMail' => 'Wyślij handlowych wniosku pocztą',
		'FileNotUploaded' => 'Plik nie został wysłany',
		'FileUploaded' => 'Plik został pomyślnie przesłany',
		'AssociatedDocuments' => 'Dokumenty związane z projektem:',
		'ErrorCantOpenDir' => 'Nie można otworzyć katalogu',
		'DatePropal' => 'Data wniosku',
		'DateEndPropal' => 'Data końca obowiązywania',
		'DateEndPropalShort' => 'Data zakończenia',
		'ValidityDuration' => 'Ważność czas',
		'CloseAs' => 'Zamknij ze statusu',
		'ClassifyBilled' => 'Klasyfikacja billed',
		'BuildBill' => 'Zbuduj faktury',
		'ErrorPropalNotFound' => 'Propal %s nie znaleziono',
		'Estimate' => 'Prognoza:',
		'EstimateShort' => 'Prognoza',
		'OtherPropals' => 'Inne propozycje',
		'CopyPropalFrom' => 'Tworzenie komercyjnych wniosek kopiowanie istniejących wniosku',
		'CreateEmptyPropal' => 'Utwórz pusty propozycji Vierge lub z wykazu produktów / usług',
		'DefaultProposalDurationValidity' => 'Domyślny czas ważności wniosku handlowych (w dniach)',
		'UseCustomerContactAsPropalRecipientIfExist' => 'Użyj klienta adres, jeśli określone zamiast trzeciej adres wniosku adres odbiorcy',
		'ClonePropal' => 'Clone handlowych wniosku',
		'ConfirmClonePropal' => 'Czy na pewno chcesz klon tej propozycji <b>komercyjnych %s?</b>',
		'ConfirmReOpenProp' => 'Czy na pewno chcesz otworzyć z powrotem handlowe <b>%s</b> propozycję?',
		'ProposalsAndProposalsLines' => 'Commercial wniosku i linie',
		'ProposalLine' => 'Wniosek linii',
		'AvailabilityPeriod' => 'Opóźnienie dostępność',
		'SetAvailability' => 'Ustaw opóźnienie dostępność',
		'AfterOrder' => 'od zamówienia',
		////////// Availability //////////
		'AvailabilityTypeAV_NOW' => 'Natychmiastowy',
		'AvailabilityTypeAV_1W' => '1 tydzień',
		'AvailabilityTypeAV_2W' => '2 tygodnie',
		'AvailabilityTypeAV_3W' => '3 tygodnie',
		'AvailabilityTypeAV_1M' => '1 miesiąc',
		////////// Types de contacts //////////
		'TypeContact_propal_internal_SALESREPFOLL' => 'Przedstawiciela w ślad za wniosek',
		'TypeContact_propal_external_BILLING' => 'kontakt faktury klienta',
		'TypeContact_propal_external_CUSTOMER' => 'kontakt klienta w ślad za wniosek',
		// Document models
		'DocModelAzurDescription' => 'Kompletny wniosek modelu (logo. ..)',
		'DocModelJauneDescription' => 'Jaune propozycję modelu'
);
?>