<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Magazyn karty',
		'Warehouse' => 'Magazyn',
		'Warehouses' => 'Warehouses',
		'NewWarehouse' => 'Nowy magazyn / Stock obszarze',
		'WarehouseEdit' => 'Modyfikacja składu',
		'MenuNewWarehouse' => 'Nowy magazyn',
		'WarehouseOpened' => 'Magazyn otwarty',
		'WarehouseClosed' => 'Magazyn zamknięte',
		'WarehouseSource' => 'Źródło magazynu',
		'WarehouseSourceNotDefined' => 'No warehouse defined,',
		'AddOne' => 'Add one',
		'WarehouseTarget' => 'Docelowe magazynie',
		'ValidateSending' => 'Usuń wysyłanie',
		'CancelSending' => 'Anuluj wysyłanie',
		'DeleteSending' => 'Usuń wysyłanie',
		'Stock' => 'Zasób',
		'Stocks' => 'Zapasy',
		'Movement' => 'Ruch',
		'Movements' => 'Ruchy',
		'ErrorWarehouseRefRequired' => 'Magazyn referencyjnego Wymagana jest nazwa',
		'ErrorWarehouseLabelRequired' => 'Magazyn etykiecie jest wymagane',
		'CorrectStock' => 'Poprawny stanie',
		'ListOfWarehouses' => 'Lista magazynów',
		'ListOfStockMovements' => 'Wykaz stanu magazynowego',
		'StocksArea' => 'Zapasy obszarze',
		'Location' => 'Lieu',
		'LocationSummary' => 'Nazwa skrócona lokalizacji',
		'NumberOfProducts' => 'Łączna liczba produktów',
		'LastMovement' => 'Ostatni ruch',
		'LastMovements' => 'Ostatnie ruchy',
		'Units' => 'Jednostki',
		'Unit' => 'Jednostka',
		'StockCorrection' => 'Poprawny stanie',
		'StockMovement' => 'Przeniesienie',
		'StockMovements' => 'Stock transfery',
		'NumberOfUnit' => 'Liczba jednostek',
		'UnitPurchaseValue' => 'Unit purchase price',
		'TotalStock' => 'Razem w akcji',
		'StockTooLow' => 'Zasób zbyt niska',
		'StockLowerThanLimit' => 'Stock lower than alert limit',
		'EnhancedValue' => 'Wartość',
		'PMPValue' => 'Wartość',
		'PMPValueShort' => 'WAP',
		'EnhancedValueOfWarehouses' => 'Magazyny wartości',
		'UserWarehouseAutoCreate' => 'Tworzenie stanie automatycznie podczas tworzenia użytkownika',
		'QtyDispatched' => 'Ilość wysyłanych',
		'OrderDispatch' => 'Postanowienie wysyłkowe',
		'RuleForStockManagementDecrease' => 'Artykuł na zarządzanie zapasami spadek',
		'RuleForStockManagementIncrease' => 'Artykuł na zarządzanie zapasami wzrost',
		'DeStockOnBill' => 'Spadek realnych zasobów faktur / not kredytowych',
		'DeStockOnValidateOrder' => 'Spadek realnych zasobów zamówień notatek',
		'DeStockOnShipment' => 'Spadek realnych zasobów wysyłką (zaleciły)',
		'ReStockOnBill' => 'Wzrost realnego zasobów faktur / not kredytowych',
		'ReStockOnValidateOrder' => 'Wzrost realnego zasobów zamówień notatek',
		'ReStockOnDispatchOrder' => 'Wzrost rzeczywisty stan zapasów w magazynach ręcznego wysyłki, po otrzymaniu zamówienia dostawca',
		'OrderStatusNotReadyToDispatch' => 'Zamówienie nie jest jeszcze lub nie więcej status, który umożliwia wysyłanie produktów w magazynach czas.',
		'StockDiffPhysicTeoric' => 'Powód różnica stanie fizycznym i teoretycznego',
		'NoPredefinedProductToDispatch' => 'Nie gotowych produktów dla tego obiektu. Więc nie w czas wysyłki jest wymagane.',
		'DispatchVerb' => 'Wysyłka',
		'StockLimitShort' => 'Limit',
		'StockLimit' => 'Stock limit wpisów',
		'PhysicalStock' => 'Fizyczne zapasy',
		'RealStock' => 'Real Stock',
		'TheoreticalStock' => 'Therocial stanie',
		'VirtualStock' => 'Wirtualne stanie',
		'MininumStock' => 'Minimum stock',
		'StockUp' => 'Stanie się',
		'MininumStockShort' => 'Stock min',
		'StockUpShort' => 'Stanie się',
		'IdWarehouse' => 'Identyfikator magazynu',
		'DescWareHouse' => 'Opis składu',
		'LieuWareHouse' => 'Lokalizacja hurtowni',
		'WarehousesAndProducts' => 'Magazyny i produktów',
		'AverageUnitPricePMPShort' => 'Średnia cena wejścia',
		'AverageUnitPricePMP' => 'Średnia cena wejścia',
		'SellPriceMin' => 'Cena sprzedaży jednostki',
		'EstimatedStockValueSellShort' => 'Wartość sprzedaży',
		'EstimatedStockValueSell' => 'Wartość sprzedaży',
		'EstimatedStockValueShort' => 'Szacunkowa wartość zapasów',
		'EstimatedStockValue' => 'Szacunkowa wartość zapasów',
		'DeleteAWarehouse' => 'Usuń magazyn',
		'ConfirmDeleteWarehouse' => 'Czy na pewno chcesz usunąć <b>%s</b> magazynie?',
		'PersonalStock' => 'Osobowych %s czas',
		'ThisWarehouseIsPersonalStock' => 'Tym składzie przedstawia osobiste zasobów %s %s',
		'SelectWarehouseForStockDecrease' => 'Wybierz magazyn użyć do zmniejszenia czas',
		'SelectWarehouseForStockIncrease' => 'Wybierz magazyn użyć do zwiększenia czas',
		'LastWaitingSupplierOrders' => 'Orders waiting for receptions'
);
?>