<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Magazyn karty',
		'Warehouse' => 'Magazyn',
		'NewWarehouse' => 'Nowy magazyn / Stock obszarze',
		'MenuNewWarehouse' => 'Nowy magazyn',
		'WarehouseOpened' => 'Magazyn otwarty',
		'WarehouseClosed' => 'Magazyn zamknięte',
		'WarehouseSource' => 'Źródło magazynu',
		'WarehouseTarget' => 'Docelowe magazynie',
		'ValidateSending' => 'Usuń wysyłanie',
		'CancelSending' => 'Anuluj wysyłanie',
		'DeleteSending' => 'Usuń wysyłanie',
		'Stock' => 'Zasób',
		'Stocks' => 'Zapasy',
		'Movement' => 'Ruch',
		'Movements' => 'Ruchy',
		'ErrorWarehouseRefRequired' => 'Magazyn referencyjnego Wymagana jest nazwa',
		'ErrorWarehouseLabelRequired' => 'Magazyn etykiecie jest wymagane',
		'CorrectStock' => 'Poprawny stanie',
		'ListOfWarehouses' => 'Lista magazynów',
		'ListOfStockMovements' => 'Wykaz stanu magazynowego',
		'StocksArea' => 'Zapasy obszarze',
		'Location' => 'Lieu',
		'LocationSummary' => 'Nazwa skrócona lokalizacji',
		'NumberOfProducts' => 'Łączna liczba produktów',
		'LastMovement' => 'Ostatni ruch',
		'LastMovements' => 'Ostatnie ruchy',
		'Units' => 'Jednostki',
		'Unit' => 'Jednostka',
		'StockCorrection' => 'Poprawny stanie',
		'StockMovement' => 'Przeniesienie',
		'StockMovements' => 'Stock transfery',
		'NumberOfUnit' => 'Liczba jednostek',
		'TotalStock' => 'Razem w akcji',
		'StockTooLow' => 'Zasób zbyt niska',
		'EnhancedValue' => 'Wartość',
		'PMPValue' => 'Wartość',
		'EnhancedValueOfWarehouses' => 'Magazyny wartości',
		'UserWarehouseAutoCreate' => 'Tworzenie stanie automatycznie podczas tworzenia użytkownika',
		'QtyDispatched' => 'Ilość wysyłanych',
		'OrderDispatch' => 'Postanowienie wysyłkowe',
		'RuleForStockManagementDecrease' => 'Artykuł na zarządzanie zapasami spadek',
		'RuleForStockManagementIncrease' => 'Artykuł na zarządzanie zapasami wzrost',
		'DeStockOnBill' => 'Spadek realnych zasobów faktur / not kredytowych',
		'DeStockOnValidateOrder' => 'Spadek realnych zasobów zamówień notatek',
		'DeStockOnShipment' => 'Spadek realnych zasobów wysyłką (zaleciły)',
		'ReStockOnBill' => 'Wzrost realnego zasobów faktur / not kredytowych',
		'ReStockOnValidateOrder' => 'Wzrost realnego zasobów zamówień notatek',
		'StockDiffPhysicTeoric' => 'Powód różnica stanie fizycznym i teoretycznego',
		'StockLimitShort' => 'Limit',
		'StockLimit' => 'Stock limit wpisów',
		'PhysicalStock' => 'Fizyczne zapasy',
		'RealStock' => 'Real Stock',
		'TheoreticalStock' => 'Therocial stanie',
		'VirtualStock' => 'Wirtualne stanie',
		'MininumStock' => 'Minimum stock',
		'StockUp' => 'Stanie się',
		'MininumStockShort' => 'Stock min',
		'StockUpShort' => 'Stanie się',
		'IdWarehouse' => 'Identyfikator magazynu',
		'DescWareHouse' => 'Opis składu',
		'LieuWareHouse' => 'Lokalizacja hurtowni',
		'WarehousesAndProducts' => 'Magazyny i produktów',
		'PMPValueShort' => 'WAP',
		'AverageUnitPricePMPShort' => 'Średnia cena wejścia',
		'AverageUnitPricePMP' => 'Średnia cena wejścia',
		'EstimatedStockValueShort' => 'Szacunkowa wartość zapasów',
		'EstimatedStockValue' => 'Szacunkowa wartość zapasów',
		'WarehouseEdit' => 'Modyfikacja składu',
		'ReStockOnDispatchOrder' => 'Wzrost rzeczywisty stan zapasów w magazynach ręcznego wysyłki, po otrzymaniu zamówienia dostawca',
		'OrderStatusNotReadyToDispatch' => 'Zamówienie nie jest jeszcze lub nie więcej status, który umożliwia wysyłanie produktów w magazynach czas.',
		'NoPredefinedProductToDispatch' => 'Nie gotowych produktów dla tego obiektu. Więc nie w czas wysyłki jest wymagane.',
		'DispatchVerb' => 'Wysyłka',
		'DeleteAWarehouse' => 'Usuń magazyn',
		'ConfirmDeleteWarehouse' => 'Czy na pewno chcesz usunąć <b>%s</b> magazynie?',
		'PersonalStock' => 'Osobowych %s czas',
		'ThisWarehouseIsPersonalStock' => 'Tym składzie przedstawia osobiste zasobów %s %s',
		'SellPriceMin' => 'Cena sprzedaży jednostki',
		'EstimatedStockValueSellShort' => 'Wartość sprzedaży',
		'EstimatedStockValueSell' => 'Wartość sprzedaży',
		'SelectWarehouseForStockDecrease' => 'Wybierz magazyn użyć do zmniejszenia czas',
		'SelectWarehouseForStockIncrease' => 'Wybierz magazyn użyć do zwiększenia czas',
);
?>