<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'Użytkownik karty',
		'ContactCard' => 'Kontakt karty',
		'GroupCard' => 'Grupa karty',
		'NoContactCard' => 'Nr karty kontaktów między',
		'Permission' => 'Zezwolenie',
		'Permissions' => 'Uprawnienia',
		'EditPassword' => 'Edytuj hasło',
		'SendNewPassword' => 'Wyślij nowe hasło',
		'ReinitPassword' => 'Wygeneruj nowe hasło',
		'PasswordChangedTo' => 'Hasło zmieniono na: %s',
		'SubjectNewPassword' => 'Twoje nowe hasło Dolibarr',
		'AvailableRights' => 'Dostępne uprawnienia',
		'OwnedRights' => 'Posiadanych uprawnień',
		'GroupRights' => 'Grupa uprawnienia',
		'UserRights' => 'Użytkownik uprawnienia',
		'UserGUISetup' => 'Użytkownik Display Setup',
		'DisableUser' => 'Wyłączyć',
		'DisableAUser' => 'Wyłącz użytkownika',
		'DeleteUser' => 'Usunąć',
		'DeleteAUser' => 'Usuń użytkownika',
		'DisableGroup' => 'Wyłączyć',
		'DisableAGroup' => 'Wyłącz grupy',
		'EnableAUser' => 'Włącz użytkownika',
		'EnableAGroup' => 'Włącz grupy',
		'DeleteGroup' => 'Usunąć',
		'DeleteAGroup' => 'Usuń grupę',
		'ConfirmDisableUser' => 'Czy na pewno chcesz wyłączyć <b>użytkownik %s?</b>',
		'ConfirmDisableGroup' => 'Czy na pewno chcesz wyłączyć <b>grupie %s?</b>',
		'ConfirmDeleteUser' => 'Czy na pewno chcesz usunąć <b>użytkownika %s?</b>',
		'ConfirmDeleteGroup' => 'Czy na pewno chcesz usunąć <b>grupę %s?</b>',
		'ConfirmEnableUser' => 'Czy na pewno chcesz, aby umożliwić <b>użytkownikowi %s?</b>',
		'ConfirmEnableGroup' => 'Czy na pewno chcesz, aby umożliwić <b>grupie %s?</b>',
		'ConfirmReinitPassword' => 'Czy na pewno chcesz, aby wygenerować nowe hasło dla <b>użytkownika %s?</b>',
		'ConfirmSendNewPassword' => 'Czy na pewno chcesz wygenerować i wysłać nowe hasło dla <b>użytkownika %s?</b>',
		'NewUser' => 'Nowy użytkownik',
		'CreateUser' => 'Utwórz użytkownika',
		'SearchAGroup' => 'Szukaj grupy',
		'SearchAUser' => 'Szukaj użytkownika',
		'LoginNotDefined' => 'Logowanie nie zostało zdefiniowane.',
		'NameNotDefined' => 'Nazwa nie jest zdefiniowane.',
		'ListOfUsers' => 'Lista użytkowników',
		'Administrator' => 'Administrator',
		'SuperAdministrator' => 'Super Administrator',
		'SuperAdministratorDesc' => 'Administrator ze wszystkich praw',
		'AdministratorDesc' => 'Administratora podmiot',
		'DefaultRights' => 'Domyślne uprawnienia',
		'DefaultRightsDesc' => 'Określ tutaj domyślne uprawnienia, które są przyznawane automatycznie utworzony nowy użytkownik.',
		'SpeedealingUsers' => 'Speedealing users',
		'LastName' => 'Imię',
		'FirstName' => 'Imię',
		'ListOfGroups' => 'Lista grup',
		'NewGroup' => 'Nowa grupa',
		'CreateGroup' => 'Tworzenie grupy',
		'RemoveFromGroup' => 'Usuń z grupy',
		'PasswordChangedAndSentTo' => 'Hasło zmieniło i wysyłane <b>do %s.</b>',
		'PasswordChangeRequestSent' => 'Wniosek o zmianę hasła <b>dla %s</b> wysłane <b>do %s.</b>',
		'MenuUsersAndGroups' => 'Użytkownicy i grupy',
		'LastGroupsCreated' => 'Ostatnia %s utworzonych grup',
		'LastUsersCreated' => 'Ostatnia %s użytkowników utworzonych',
		'ShowGroup' => 'Pokaż grupy',
		'ShowUser' => 'Pokaż użytkownika',
		'NonAffectedUsers' => 'Brak wpływu na użytkowników',
		'UserModified' => 'Użytkownik zmodyfikowano pomyślnie',
		'GroupModified' => 'Grupa zmodyfikowano pomyślnie',
		'PhotoFile' => 'Plików ze zdjęciami',
		'UserWithSpeedealingAccess' => 'User with Speedealing access',
		'ListOfUsersInGroup' => 'Lista użytkowników w tej grupie',
		'ListOfGroupsForUser' => 'Lista grup dla tego użytkownika',
		'UsersToAdd' => 'Użytkownicy będą mogli dodać do tej grupy',
		'GroupsToAdd' => 'Grupy, które można dodać do tego użytkownika',
		'NoLogin' => 'Brak logowania',
		'LinkToCompanyContact' => 'Link do strony trzeciej / kontakt',
		'LinkedToSpeedealingMember' => 'Link to member',
		'LinkedToSpeedealingUser' => 'Link to Speedealing user',
		'LinkedToSpeedealingThirdParty' => 'Link to Speedealing third party',
		'CreateSpeedealingLogin' => 'Create a user',
		'CreateSpeedealingThirdParty' => 'Create a third party',
		'LoginAccountDisable' => 'Konto wyłączone, położyć nowy login uaktywnić.',
		'LoginAccountDisableInSpeedealing' => 'Account disabled in Speedealing.',
		'LoginAccountDisableInLdap' => 'Wyłączone konto w domenie.',
		'UsePersonalValue' => 'Użyj wartości osobowych',
		'GuiLanguage' => 'Język interfejsu',
		'InternalUser' => 'Wewnętrzny użytkownik',
		'MyInformations' => 'Moje dane',
		'ExportDataset_user_1' => 'Dolibarr Użytkownicy i właściwości',
		'DomainUser' => 'Domena użytkownika %s',
		'Reactivate' => 'Przywraca',
		'CreateInternalUserDesc' => 'Ta forma pozwala na utworzenie jeden użytkownik wewnętrzną Twojej firmy / fundacji. Aby creat zewnętrznego użytkownika (klienta, dostawcy, ...), użyć przycisku "Utwórz Dolibarr użytkownika" od osoby trzeciej karcie kontaktu.',
		'InternalExternalDesc' => '<b>Wewnętrzny</b> użytkownik jest użytkownikiem, który jest częścią firmy / fundacji. <br> <b>Zewnętrzna</b> użytkownika klienta, dostawcy lub innym. <br><br> W obu przypadkach uprawnienia określa prawa Dolibarr, także zewnętrznych użytkownik może mieć różne menu menedżera niż użytkownika wewnętrznego (patrz strona główna - Instalator - Display)',
		'PermissionInheritedFromAGroup' => 'Zezwolenie udzielone ponieważ odziedziczył od jednego z użytkowników grupy.',
		'Inherited' => 'Odziedziczone',
		'UserWillBeInternalUser' => 'Utworzony użytkownik będzie wewnętrzny użytkownik (ponieważ nie związane z konkretnym trzeciej)',
		'UserWillBeExternalUser' => 'Utworzony użytkownik będzie zewnętrzny użytkownik (ponieważ związana z konkretnym trzeciej)',
		'IdPhoneCaller' => 'ID dzwoniącego telefonu',
		'UserLogged' => 'Użytkownik %s podłączony',
		'UserLogoff' => '%s użytkownika wylogować',
		'NewUserCreated' => 'Użytkownik %s tworzone',
		'NewUserPassword' => 'Zmiana hasła dla %s',
		'EventUserModified' => 'Użytkownik %s zmodyfikowane',
		'UserDisabled' => 'Użytkownik %s osób niepełnosprawnych',
		'UserEnabled' => 'Użytkownik %s aktywowany',
		'UserDeleted' => 'Użytkownik %s usunięto',
		'NewGroupCreated' => 'Grupa %s tworzone',
		'GroupModified' => 'Grupa zmodyfikowano pomyślnie',
		'GroupDeleted' => 'Grupa %s usunięto',
		'ConfirmCreateContact' => 'Czy na pewno chcesz yu Dolibarr utworzyć konto dla tego kontaktu?',
		'ConfirmCreateLogin' => 'Czy na pewno chcesz, aby utworzyć konto dla tego Dolibarr członkiem?',
		'ConfirmCreateThirdParty' => 'Czy na pewno chcesz, aby utworzyć trzecią dla tego członka?',
		'LoginToCreate' => 'Zaloguj się, aby utworzyć',
		'NameToCreate' => 'Nazwisko osoby trzeciej w celu stworzenia',
		'YourRole' => 'Swoje role',
		'YourQuotaOfUsersIsReached' => 'Limitu aktywnych użytkowników został osiągnięty!',
		'NbOfUsers' => 'Nb użytkowników',
		'DontDowngradeSuperAdmin' => 'Tylko superadmin niższej wersji superadmin',
		'NewDatabase' => 'Nouvelle base de données',
		'CreateDatabase' => 'Créer la base de données',
		'ListOfDatabases' => 'Liste des bases de données',
		'ListOfUsersInDatabase' => 'Liste des utilisateurs liés à la base de données',
		'ListOfRolesInDatabase' => 'Liste des groupes liés à la base de données',
		'DeleteADatabase' => 'Suppression d\'une database',
		'ConfirmDatabase' => 'Êtes-vous sûr de vouloir supprimer la base de données <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Groupes non affectés à la base de données',
		'NonAffectedUsersDatabase' => 'Utilisateurs non affectés à la base de données',
		'Collaborators' => 'Collaborateurs',
		'Profiles' => 'Profils collaborateurs'
);
?>