<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$withdrawals = array(
		'CHARSET' => 'UTF-8',
		'StandingOrdersArea' => 'Stały dziedzinie zamówień',
		'CustomersStandingOrdersArea' => 'Klienci stałych zleceń obszarze',
		'StandingOrders' => 'Zlecenia stałe',
		'StandingOrder' => 'Zlecenia stałe',
		'NewStandingOrder' => 'Nowe zlecenie stałe',
		'StandingOrderToProcess' => 'Do procesu',
		'StandingOrderProcessed' => 'Przetworzony',
		'Withdrawals' => 'Wypłaty',
		'Withdrawal' => 'Wycofanie',
		'WithdrawalsReceipts' => 'Wycofania wpływy',
		'WithdrawalReceipt' => 'Wycofanie otrzymania',
		'WithdrawalReceiptShort' => 'Odbiór',
		'LastWithdrawalReceipts' => 'Ostatnia %s wycofania wpływy',
		'WithdrawedBills' => 'Withdrawed faktur',
		'WithdrawalsLines' => 'Wycofania linie',
		'RequestStandingOrderToTreat' => 'Wniosek o stałych zleceń w leczeniu',
		'RequestStandingOrderTreated' => 'Wniosek o stałych zleceń leczonych',
		'CustomersStandingOrders' => 'Stałych zleceń klienta',
		'CustomerStandingOrder' => 'Klient zlecenie stałe',
		'NbOfInvoiceToWithdraw' => 'Nb faktury z wycofać wniosek',
		'NbOfInvoiceToWithdrawWithInfo' => 'Nb faktury z wycofać wniosek o klientów posiadających określone informacje o koncie bankowym',
		'InvoiceWaitingWithdraw' => 'Faktura czeka na wycofać',
		'AmountToWithdraw' => 'Kwota do wycofania',
		'WithdrawsRefused' => 'Wycofuje odmówił',
		'NoInvoiceToWithdraw' => 'Nr klienta zapłaty faktury w trybie "wycofania" czeka. Idź na "Wypłata" kartę na fakturze kartę do złożenia wniosku.',
		'ResponsibleUser' => 'Odpowiedzialny użytkownika',
		'WithdrawalsSetup' => 'Wycofanie konfiguracji',
		'WithdrawStatistics' => 'Wycofuje statystyk',
		'WithdrawRejectStatistics' => 'Wypłaty odrzuca "statystyki',
		'LastWithdrawalReceipt' => 'Ostatnia %s wycofanie wpływy',
		'MakeWithdrawRequest' => 'Zrób wycofać wniosek',
		'ThirdPartyBankCode' => 'Trzeciej kod banku',
		'ThirdPartyDeskCode' => 'Trzeciej biurko kod',
		'NoInvoiceCouldBeWithdrawed' => 'Nr faktury withdrawed sukces. Sprawdź, czy faktura jest na spółki z ważnych BAN.',
		'ClassCredited' => 'Klasyfikacja zapisane',
		'ClassCreditedConfirm' => 'Czy na pewno chcesz to wycofanie otrzymania sklasyfikowania jako wpłacone na konto bankowe?',
		'TransData' => 'Data Transmission',
		'TransMetod' => 'Tryb transmisji',
		'Send' => 'Wysłać',
		'Lines' => 'Linie',
		'StandingOrderReject' => 'Problem odrzucenia',
		'InvoiceRefused' => 'Za odrzucenie klienta',
		'WithdrawalRefused' => 'Wypłaty Refuseds',
		'WithdrawalRefusedConfirm' => 'Czy na pewno chcesz wprowadzić odrzucenie wycofania dla społeczeństwa',
		'RefusedData' => 'Od odrzucenia',
		'RefusedReason' => 'Powodem odrzucenia',
		'RefusedInvoicing' => 'Rozliczeniowych odrzucenia',
		'NoInvoiceRefused' => 'Nie za odrzucenie',
		'InvoiceRefused' => 'Za odrzucenie klienta',
		'Status' => 'Status',
		'StatusUnknown' => 'Nieznany',
		'StatusWaiting' => 'Czekanie',
		'StatusTrans' => 'Przekazywane',
		'StatusCredited' => 'Dobro',
		'StatusRefused' => 'Odmówił',
		'StatusMotif0' => 'Nieokreślone',
		'StatusMotif1' => 'Przepis insuffisante',
		'StatusMotif2' => 'conteste liqueur',
		'StatusMotif3' => 'Wycofanie zamówienia nie',
		'StatusMotif4' => 'Zamówienia klientów',
		'StatusMotif5' => 'RIB inexploitable',
		'StatusMotif6' => 'Salda rachunku bez',
		'StatusMotif7' => 'Orzeczenia sądowego',
		'StatusMotif8' => 'Inny powód',
		'CreateAll' => 'Wycofania wszystkich',
		'CreateGuichet' => 'Tylko biuro',
		'CreateBanque' => 'Tylko bank',
		'OrderWaiting' => 'Oczekiwania na leczenie',
		'NotifyTransmision' => 'Wycofanie Przekazanie',
		'NotifyEmision' => 'Wycofanie emisji',
		'NotifyCredit' => 'Odstąpienia od umowy kredytowej',
		'NumeroNationalEmetter' => 'Krajowy numer nadajnika',
		'PleaseSelectCustomerBankBANToWithdraw' => 'Wybierz informacje o rachunku bankowym klienta do odstąpienia',
		'WithBankUsingRIB' => 'Na rachunkach bankowych z wykorzystaniem RIB',
		'WithBankUsingBANBIC' => 'Na rachunkach bankowych z wykorzystaniem IBAN / BIC / SWIFT',
		'BankToReceiveWithdraw' => 'Konto bankowe do odbioru odstępuje',
		'CreditDate' => 'Kredyt na',
		'WithdrawalFileNotCapable' => 'Nie można wygenerować plik potwierdzenia wypłaty dla swojego kraju',
		'ShowWithdraw' => 'Pokaż Wypłata',
		'IfInvoiceNeedOnWithdrawPaymentWontBeClosed' => 'Jeśli jednak faktura nie co najmniej jeden wypłaty płatności jeszcze przetworzone, nie będzie ustawiony jako zapłaci, aby umożliwić zarządzanie wycofanie wcześniej.',
		'DoStandingOrdersBeforePayments' => 'Te karty pozwala z prośbą o zlecenia stałego. Gdy będzie gotowy, możesz wpisać płatność zamknąć faktury.',
		////// Notifications
		'InfoCreditSubject' => 'Płatność z %s zamówienia stojących przez bank',
		'InfoCreditMessage' => 'Stojąc %s zamówienie zostało wypłacone przez bank <br> Data płatności: %s',
		'InfoTransSubject' => 'Przekazywanie %s rzędu stojących na brzegu',
		'InfoTransMessage' => 'Stojąc %s zamówienie zostało przesłanych do banku przez %s %s. <br><br>',
		'InfoTransData' => 'Kwota: %s <br> Metode: %s <br> Data: %s',
		'InfoFoot' => 'Jest to zautomatyzowany wiadomość wysłana przez Speedealing',
		'InfoRejectSubject' => 'Zlecenie stałe odmówił',
		'InfoRejectMessage' => 'Witam, <br><br> standig aby fakturze %s związanych z %s firmy, w kwocie %s został odrzucony przez bank. <br><br> - <br> % $',
		'ModeWarning' => 'Opcja dla trybu rzeczywistego nie był ustawiony, zatrzymujemy po tej symulacji'
);
?>