<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$boxes = array(
		'﻿# Dolibarr language file - pt_PT - boxes' => '',
		'CHARSET' => 'UTF-8',
		'BoxLastRssInfos' => 'Links de informação RSS',
		'BoxLastProducts' => 'Últimos produtos/serviços',
		'BoxLastProductsInContract' => 'Últimos produtos/serviços contratados',
		'BoxLastSupplierBills' => 'Últimas facturas de Fornecedores',
		'BoxLastCustomerBills' => 'Últimas facturas a clientes',
		'BoxOldestUnpaidCustomerBills' => 'Facturas a clientes mais antiguas pendentes de pagamento',
		'BoxOldestUnpaidSupplierBills' => 'Facturas de Fornecedores mais antiguas pendentes de pagamento',
		'BoxLastProposals' => 'Últimos Orçamentos',
		'BoxLastProspects' => 'Últimos clientes potenciais',
		'BoxLastCustomers' => 'Últimos clientes',
		'BoxLastCustomerOrders' => 'Últimos pedidos',
		'BoxLastSuppliers' => 'Últimos Fornecedores',
		'BoxLastBooks' => 'Últimos books',
		'BoxLastActions' => 'Últimas acções',
		'BoxCurrentAccounts' => 'Saldos contas correntes',
		'BoxSalesTurnover' => 'Volume de negocio',
		'BoxTotalUnpaidCustomerBills' => 'Total facturas a clientes pendentes de pagamento',
		'BoxTotalUnpaidSuppliersBills' => 'Total facturas de Fornecedores pendentes de pagamento',
		'BoxTitleLastBooks' => 'Os %s últimos Favoritos registados',
		'BoxTitleNbOfCustomers' => 'Número de clientes',
		'BoxTitleLastRssInfos' => 'As %s Ultimas Infos de %s',
		'BoxTitleLastProducts' => 'Os %s Ultimos Produtos/Serviços Registados',
		'BoxTitleLastCustomerOrders' => 'Os %s últimos pedidos de clientes modificados',
		'BoxTitleLastSuppliers' => 'Os %s últimos Fornecedores modificados',
		'BoxTitleLastCustomers' => 'Os %s últimos clientes modificados',
		'BoxTitleLastCustomersOrProspects' => 'Os %s últimos clientes ou clientes potenciais registados',
		'BoxTitleLastPropals' => 'Os %s últimos Orçamentos registados',
		'BoxTitleLastCustomerBills' => 'As %s últimas facturas a clientes registadas',
		'BoxTitleLastSupplierBills' => 'As %s últimas facturas de Fornecedores registadas',
		'BoxTitleLastProspects' => 'Os %s últimos clientes potenciais modificados',
		'BoxTitleLastProductsInContract' => 'Os %s últimos produtos/serviços contratados',
		'BoxTitleOldestUnpaidCustomerBills' => 'As %s facturas mais antiguas a clientes Pendentes de cobrança',
		'BoxTitleOldestUnpaidSupplierBills' => 'As %s facturas mais antiguas de Fornecedores Pendentes de pagamento',
		'BoxTitleCurrentAccounts' => 'Saldos das contas correntes',
		'BoxTitleSalesTurnover' => 'Volume de negocio realizado',
		'BoxTitleTotalUnpaidCustomerBills' => 'Facturas pendentes de clientes',
		'BoxTitleTotalUnpaidSuppliersBills' => 'Facturas pendentes de Fornecedores',
		'BoxMyLastBookmarks' => 'Os meus ultimos Favoritos',
		'FailedToRefreshDataInfoNotUpToDate' => 'Erro ao  refresh fluxo RSS. data do último refresh: %s',
		'LastRefreshDate' => 'Data última actualização',
		'NoRecordedBookmarks' => 'Não existem favoritos pessoais. Click aqui para adicionar.',
		'NoRecordedCustomers' => 'Nenhum cliente registado',
		'BoxTitleLastActionsToDo' => 'As %s últimas acções a realizar',
		'NoActionsToDo' => 'Sem acções a realizar',
		'NoRecordedOrders' => 'Sem pedidos de clientes registados',
		'NoRecordedProposals' => 'Sem Orçamentos registados',
		'NoRecordedInvoices' => 'Sem facturas a clientes registados',
		'NoUnpaidCustomerBills' => 'Sem facturas a clientes Pendentes de pagamento',
		'NoRecordedSupplierInvoices' => 'Sem facturas de Fornecedores',
		'NoUnpaidSupplierBills' => 'Sem facturas de Fornecedores Pendentes de Pagamento',
		'NoRecordedProducts' => 'Não gravados produtos / serviços',
		'NoRecordedProspects' => 'Não gravadas perspectivas',
		'NoContractedProducts' => 'Não contractados produtos / serviços',
		'BoxLastContracts' => 'Ultimos Contractos',
		'LastRefreshDate' => 'Data última actualização',
		'BoxTitleLastContracts' => 'Últimos contratos',
		'NoModifiedSupplierBills' => 'Nenhuma factura de fornecedor registada',
		'NoRecordedProducts' => 'Não gravados produtos / serviços',
		'NoRecordedProspects' => 'Não gravadas perspectivas',
		'NoContractedProducts' => 'Não contractados produtos / serviços',
		'NoRecordedContracts' => 'Sem contratos registrados',
		'BoxLastContracts' => 'Ultimos Contractos',
		'BoxTitleLastContracts' => 'Última contratos',
		'NoModifiedSupplierBills' => 'Nenhuma factura de fornecedor registada',
		'NoRecordedContracts' => 'Sem contratos registrados',
		'BoxOldestUnpaidCustomerBills' => 'Facturas a clientes mais antiguas pendentes de pagamento',
		'BoxOldestUnpaidSupplierBills' => 'Facturas de Fornecedores mais antiguas pendentes de pagamento',
		'BoxLastContracts' => 'Ultimos Contractos',
		'BoxTotalUnpaidCustomerBills' => 'Total facturas a clientes pendentes de pagamento',
		'BoxTotalUnpaidSuppliersBills' => 'Total facturas de Fornecedores pendentes de pagamento',
		'BoxTitleOldestUnpaidCustomerBills' => 'As %s facturas mais antiguas a clientes Pendentes de cobrança',
		'BoxTitleOldestUnpaidSupplierBills' => 'As %s facturas mais antiguas de Fornecedores Pendentes de pagamento',
		'BoxTitleTotalUnpaidCustomerBills' => 'Facturas pendentes de clientes',
		'BoxTitleTotalUnpaidSuppliersBills' => 'Facturas pendentes de Fornecedores',
		'BoxTitleLastContracts' => 'Últimos contratos',
		'NoModifiedSupplierBills' => 'Nenhuma factura de fornecedor registada',
		'NoRecordedContracts' => 'Sem contratos registrados',
		'BoxLastContracts' => 'Ultimos Contractos',
		'BoxTitleLastProductsInContract' => 'Os %s últimos produtos/serviços contratados',
		'BoxTitleLastContracts' => 'Últimos contratos',
		'NoModifiedSupplierBills' => 'Nenhuma factura de fornecedor registada',
		'NoRecordedContracts' => 'Sem contratos registrados',
		'BoxLastContracts' => 'Última contratos',
		'BoxTitleLastContracts' => 'Últimos contratos %s',
		'NoModifiedSupplierBills' => 'Nenhuma factura de fornecedor registada',
		'NoRecordedContracts' => 'Sem contratos registrados',
		'BoxTitleLastModifiedSuppliers' => '%s Modificada fornecedores',
		'BoxTitleLastModifiedCustomers' => '%s Modificada clientes',
		'BoxTitleLastModifiedProspects' => '%s Modificada perspectivas',
		'BoxLastContacts' => 'Últimos contatos, endereços',
		'BoxLastMembers' => 'Últimos membros',
		'BoxTitleLastModifiedMembers' => '%s últimos membros modificados',
		'BoxTitleLastModifiedContacts' => '%s Última modificação contatos, endereços',
		'BoxOldestExpiredServices' => 'Mais antigos ativos de serviços vencidos',
		'BoxLastExpiredServices' => '%s últimos mais antigos contatos com serviços ativos expirados',
		'BoxTitleLastModifiedDonations' => '%s Última modificação doações',
		'BoxTitleLastModifiedExpenses' => '%s Última modificação despesas',
		'ClickToAdd' => 'Clique aqui para adicionar.',
		'NoRecordedContacts' => 'Não há contatos gravados',
);
?>