<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Categoria',
		'Categories' => 'Categorias',
		'Rubrique' => 'Categoria',
		'Rubriques' => 'Categorias',
		'categories' => 'categorias',
		'TheCategorie' => 'A Categoria',
		'NoCategoryYet' => 'Nenhuma Categoria Deste Tipo Criada',
		'In' => 'em',
		'AddIn' => 'Adicionar em',
		'modify' => 'Modificar',
		'Classify' => 'Classificar',
		'CategoriesArea' => 'Área Categorias',
		'ProductsCategoriesArea' => 'Área Categorias de Produtos e Serviços',
		'SuppliersCategoriesArea' => 'Área Categorias Fornecedores',
		'CustomersCategoriesArea' => 'Área Categorias Clientes',
		'ThirdPartyCategoriesArea' => 'Área Categorias de Terceiros',
		'MembersCategoriesArea' => 'Os membros da zona categorias',
		'MainCats' => 'Categorias Principais',
		'SubCats' => 'Sub-Categorias',
		'CatStatistics' => 'Estatísticas',
		'CatList' => 'Lista de Categorias',
		'AllCats' => 'Todas as Categorias',
		'ViewCat' => 'Ver Categoria',
		'NewCat' => 'Nova Categoria',
		'NewCategory' => 'Nova Categoria',
		'ModifCat' => 'Modificar uma Categoria',
		'CatCreated' => 'Categoria Criada',
		'CreateCat' => 'Adicionar uma Categoria',
		'CreateThisCat' => 'Adicionar esta Categoria',
		'ValidateFields' => 'Confirmar os campos',
		'NoSubCat' => 'Esta categoria não contem Nenhuma subcategoria.',
		'SubCatOf' => 'Subcategoria',
		'FoundCats' => 'Categorias Encontradas',
		'FoundCatsForName' => 'Categorias Encontradas com o Nome:',
		'FoundSubCatsIn' => 'Subcategorias Encontradas na Categoria',
		'ErrSameCatSelected' => 'Seleccionou a mesma categoria varias vezes',
		'ErrForgotCat' => 'Esqueceu-se escolher a categoria',
		'ErrForgotField' => 'Esqueceu-se atribuir um campo',
		'ErrCatAlreadyExists' => 'Este nome esta ser utilizado',
		'AddProductToCat' => 'Adicionar este produto a uma categoria?',
		'ImpossibleAddCat' => 'Impossivel adicionar a categoria',
		'ImpossibleAssociateCategory' => 'Impossível associar a categoria',
		'WasAddedSuccessfully' => 'Foi adicionado com êxito.',
		'ObjectAlreadyLinkedToCategory' => 'O elemento já está emparelhado a esta categoria',
		'CategorySuccessfullyCreated' => 'A Categoria %s foi inserida com sucesso',
		'ProductIsInCategories' => 'Este produto/serviço encontra-se nas seguintes categorias',
		'SupplierIsInCategories' => 'Este fornecedor encontra-se nas seguintes categorias',
		'CompanyIsInCustomersCategories' => 'Esta empresa encontra-se nas seguintes categorias',
		'CompanyIsInSuppliersCategories' => 'Esta empresa encontra-se nas seguintes categorias de Fornecedores',
		'MemberIsInCategories' => 'Este membro possui a seguinte membros categorias',
		'ProductHasNoCategory' => 'Este produto/serviço não se encontra em nenhuma categoria em particular',
		'SupplierHasNoCategory' => 'Este fornecedor não se encontra em Nenhuma categoria em particular',
		'CompanyHasNoCategory' => 'Esta empresa não se encontra em nenhuma categoria em particular',
		'MemberHasNoCategory' => 'Este membro não está em nenhuma categoria',
		'ClassifyInCategory' => 'Esta categoria não contem clientes',
		'NoneCategory' => 'Nenhuma',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Esta categoria já existe na mesma localização',
		'ReturnInProduct' => 'Voltar à ficha produto/serviço',
		'ReturnInSupplier' => 'Voltar à ficha fornecedor',
		'ReturnInCompany' => 'Voltar à ficha cliente/cliente potencial',
		'ContentsVisibleByAll' => 'O conteúdo será visível por todos?',
		'ContentsVisibleByAllShort' => 'Conteúdo visível por todos',
		'ContentsNotVisibleByAllShort' => 'Conteúdo não visível por todos',
		'CategoriesTree' => 'Árvore de Categorias',
		'DeleteCategory' => 'Eliminar Categoria',
		'ConfirmDeleteCategory' => 'Está seguro de querer eliminar esta categoria?',
		'RemoveFromCategory' => 'Eliminar link com categoria',
		'RemoveFromCategoryConfirm' => 'Está seguro de querer eliminar o link entre a transacção e a categoria?',
		'NoCategoriesDefined' => 'Nenhuma Categoria Definida',
		'SuppliersCategoryShort' => 'Categoria Fornecedores',
		'CustomersCategoryShort' => 'Categoria Clientes',
		'ProductsCategoryShort' => 'Categoria Produtos',
		'MembersCategoryShort' => 'Membros da categoria',
		'SuppliersCategoriesShort' => 'Categorias Fornecedores',
		'CustomersCategoriesShort' => 'Categorias Clientes',
		'CustomersProspectsCategoriesShort' => 'Cat. Clientes/Potenciais',
		'ProductsCategoriesShort' => 'Categorias Produtos',
		'MembersCategoriesShort' => 'categorias de membros',
		'ThisCategoryHasNoProduct' => 'Esta categoria não contem nenhum produto.',
		'ThisCategoryHasNoSupplier' => 'Esta categoria não contem a nenhum fornecedor.',
		'ThisCategoryHasNoCustomer' => 'Esta categoria não contem a nenhum cliente.',
		'ThisCategoryHasNoMember' => 'Esta categoria não contém nenhum membro.',
		'AssignedToCustomer' => 'Atribuir a um cliente',
		'AssignedToTheCustomer' => 'Atribuido a um cliente',
		'InternalCategory' => 'Categoria Interna',
		'CategoryContents' => 'Conteúdo da Categoria',
		'CategId' => 'Id Categoria',
		'CatSupList' => 'Lista de fornecedores categorias',
		'CatCusList' => 'Lista de clientes / perspectiva categorias',
		'CatProdList' => 'Lista dos produtos categorias',
		'CatMemberList' => 'Categorias Lista de membros',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>