<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Comercial',
		'CommercialArea' => 'Área comercial',
		'CommercialCard' => 'Ficha comercial',
		'CustomerArea' => 'Área de Clientes',
		'Customer' => 'Cliente',
		'Customers' => 'Clientes',
		'Prospect' => 'Cliente Potencial',
		'Prospects' => 'Clientes Potenciais',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Eliminar uma Acção',
		'NewAction' => 'Nova Acção',
		'AddAction' => 'Criar Acção',
		'AddAnAction' => 'Criar uma Acção',
		'AddActionRendezVous' => 'Criar uma Reunião',
		'Rendez-Vous' => 'Reunião',
		'ConfirmDeleteAction' => 'Está seguro de querer eliminar esta acção?',
		'CardAction' => 'Ficha da Acção',
		'PercentDone' => 'Percentagem Realizada',
		'ActionOnCompany' => 'Acção Relativa à Empresa',
		'ActionOnContact' => 'Acção Relativa ao Contacto',
		'TaskRDV' => 'Reunião',
		'TaskRDVWith' => 'Reunião com %s',
		'ShowTask' => 'Ver tarefa',
		'ShowAction' => 'Ver acção',
		'ActionsReport' => 'Relatório de acções',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Commercial',
		'SalesRepresentatives' => 'Comerciais',
		'SalesRepresentativeFollowUp' => 'Comercial (seguimento)',
		'SalesRepresentativeSignature' => 'Comercial (assinatura)',
		'CommercialInterlocutor' => 'Interlocutor comercial',
		'ErrorWrongCode' => 'Código incorrecto',
		'NoSalesRepresentativeAffected' => 'Nenhum comercial afectado',
		'ShowCustomer' => 'Ver cliente',
		'ShowProspect' => 'Ver clientes potenciais',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Lista de Clientes Potenciais',
		'ListOfCustomers' => 'Lista de Clientes',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'As %s últimas acções efectuadas',
		'LastRecordedTasks' => 'Ultimas acções registadas',
		'LastActionsToDo' => 'As %s últimas acções não completadas',
		'DoneAndToDoActionsFor' => 'Lista de acções realizadas ou a realizar por %s',
		'DoneAndToDoActions' => 'Lista de acções realizadas ou a realizar',
		'DoneActions' => 'Lista de acções realizadas',
		'DoneActionsFor' => 'Lista de acções realizadas por %s',
		'ToDoActions' => 'Lista de acções incompletas',
		'ToDoActionsFor' => 'Lista de acções incompletas de %s',
		'SendPropalRef' => 'Enviar orçamento %s',
		'SendOrderRef' => 'Enviar pedido %s',
		'StatusNotApplicable' => 'Não aplicável',
		'StatusActionToDo' => 'A realizar',
		'StatusActionDone' => 'Realizado',
		'StatusActionInProcess' => 'Em curso',
		'MyActionsAsked' => 'Acções que registei',
		'MyActionsToDo' => 'Acções que tenho que fazer',
		'MyActionsDone' => 'Acções que me afectam',
		'TasksHistoryForThisContact' => 'Acções respeito ao contacto',
		'LastProspectDoNotContact' => 'Não contactar',
		'LastProspectNeverContacted' => 'Não contactado',
		'LastProspectToContact' => 'A contactar',
		'LastProspectContactInProcess' => 'Contacto em curso',
		'LastProspectContactDone' => 'Clientes potenciais contactados',
		'DateActionPlanned' => 'Data planificação',
		'DateActionDone' => 'Data realização',
		'ActionAskedBy' => 'Acção questionada por',
		'ActionAffectedTo' => 'Acção assignada a',
		'ActionDoneBy' => 'Acção realizada por',
		'ActionUserAsk' => 'Registada por',
		'ErrorStatusCantBeZeroIfStarted' => 'Se o campo \'<b>Ficha de Realização</b>\' tiver dados a acção está em curso, por isso o campo \'Estado\' não pode ser 0%%.',
		'ActionAC_TEL' => 'Chamada telefónica',
		'ActionAC_FAX' => 'Envío Fax',
		'ActionAC_PROP' => 'Envío orçamento por correio',
		'ActionAC_EMAIL' => 'Envio E-Mail',
		'ActionAC_RDV' => 'Reunião',
		'ActionAC_FAC' => 'Envío factura por correio',
		'ActionAC_REL' => 'Lembrete factura por correio',
		'ActionAC_CLO' => 'Fechar',
		'ActionAC_EMAILING' => 'Envío mailing massivo',
		'ActionAC_COM' => 'Envío pedido por correio',
		'ActionAC_SHIP' => 'Enviar envio por correio',
		'ActionAC_SUP_ORD' => 'Enviar por e-mail para fornecedor',
		'ActionAC_SUP_INV' => 'Enviar fatura do fornecedor por e-mail',
		'ActionAC_OTH' => 'Outro',
		'Stats' => 'Estatisticas de Venda',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Estado Prospect',
		'DraftPropals' => 'Elaborar propostas comerciais',
		'SearchPropal' => 'Procure uma proposta comercial'
);
?>