<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Ficha Armazem',
		'Warehouse' => 'Armazem',
		'Warehouses' => 'Warehouses',
		'NewWarehouse' => 'Novo Armazem ou Zona de Armazenagem',
		'WarehouseEdit' => 'Modificar armazém',
		'MenuNewWarehouse' => 'Novo Armazem',
		'WarehouseOpened' => 'Armazem Aberto',
		'WarehouseClosed' => 'Armazem Fechado',
		'WarehouseSource' => 'Armazem Origem',
		'WarehouseSourceNotDefined' => 'No warehouse defined,',
		'AddOne' => 'Add one',
		'WarehouseTarget' => 'Armazem Destino',
		'ValidateSending' => 'Confirmar Envío',
		'CancelSending' => 'Cancelar Envío',
		'DeleteSending' => 'Eliminar Envío',
		'Stock' => 'Stock',
		'Stocks' => 'Stocks',
		'Movement' => 'Movimento',
		'Movements' => 'Movimentos',
		'ErrorWarehouseRefRequired' => 'O nome de referencia do armazem é obrigatório',
		'ErrorWarehouseLabelRequired' => 'A etiqueta do armazem é obrigatória',
		'CorrectStock' => 'Corrigir Stock',
		'ListOfWarehouses' => 'Lista de Armazens',
		'ListOfStockMovements' => 'Lista de movimentos de stock',
		'StocksArea' => 'Área stocks',
		'Location' => 'Localização',
		'LocationSummary' => 'Nome abreviado da localização',
		'NumberOfProducts' => 'Numero total de produtos',
		'LastMovement' => 'Último movimento',
		'LastMovements' => 'Últimos movimentos',
		'Units' => 'Unidades',
		'Unit' => 'Unidade',
		'StockCorrection' => 'Correcção stock',
		'StockMovement' => 'Transferencia',
		'StockMovements' => 'Movimentos de stock',
		'NumberOfUnit' => 'Número de peças',
		'UnitPurchaseValue' => 'Unit purchase price',
		'TotalStock' => 'Total em stock',
		'StockTooLow' => 'Stock insuficiente',
		'StockLowerThanLimit' => 'Stock lower than alert limit',
		'EnhancedValue' => 'Valor',
		'PMPValue' => 'Valor (PMP)',
		'PMPValueShort' => 'PMP',
		'EnhancedValueOfWarehouses' => 'Valor de stocks',
		'UserWarehouseAutoCreate' => 'Criar existencias automáticamente na criação de um utilizador',
		'QtyDispatched' => 'Quantidade desagregada',
		'OrderDispatch' => 'Recepção de stocks',
		'RuleForStockManagementDecrease' => 'Regra de Gestão de decrementos de stock',
		'RuleForStockManagementIncrease' => 'Regra de Gestão de incrementos de stock',
		'DeStockOnBill' => 'Decrementar os stocks físicos sobre as facturas/recibos',
		'DeStockOnValidateOrder' => 'Decrementar os stocks físicos sobre os pedidos',
		'DeStockOnShipment' => 'Decrementar os stocks físicos sobre os envíos (recomendado)',
		'ReStockOnBill' => 'Incrementar os stocks físicos sobre as facturas/recibos',
		'ReStockOnValidateOrder' => 'Incrementar os stocks físicos sobre os pedidos',
		'ReStockOnDispatchOrder' => 'Aumentar o stock real de manual de expedição em armazéns, após receber ordem de fornecedor',
		'OrderStatusNotReadyToDispatch' => 'Pedido não está pronto para despacho.',
		'StockDiffPhysicTeoric' => 'Motivo da diferença entre valores físicos e teóricos',
		'NoPredefinedProductToDispatch' => 'Não há produtos pré-definidos para este objeto. Portanto, não despachando em stock é exigido.',
		'DispatchVerb' => 'Expedição',
		'StockLimitShort' => 'Límite máximo',
		'StockLimit' => 'Límite máximo existencias',
		'PhysicalStock' => 'Stock físico',
		'RealStock' => 'Stock real',
		'TheoreticalStock' => 'Stock teórico',
		'VirtualStock' => 'Stock virtual',
		'MininumStock' => 'Stock mínimo',
		'StockUp' => 'Stock máximo',
		'MininumStockShort' => 'Stock min.',
		'StockUpShort' => 'Stock max.',
		'IdWarehouse' => 'Id. armazem',
		'DescWareHouse' => 'Descrição armazem',
		'LieuWareHouse' => 'Localização armazem',
		'WarehousesAndProducts' => 'Armazens e produtos',
		'AverageUnitPricePMPShort' => 'Média dos preços de entrada',
		'AverageUnitPricePMP' => 'Média dos preços de entrada',
		'SellPriceMin' => 'Vendendo Preço unitário',
		'EstimatedStockValueSellShort' => 'Valor para vender',
		'EstimatedStockValueSell' => 'Valor para vender',
		'EstimatedStockValueShort' => 'Valor estimado de stock',
		'EstimatedStockValue' => 'Valor estimado de stock',
		'DeleteAWarehouse' => 'Excluir um armazém',
		'ConfirmDeleteWarehouse' => 'Tem certeza de que deseja excluir o <b>%s</b> armazém?',
		'PersonalStock' => 'Pessoal %s stock',
		'ThisWarehouseIsPersonalStock' => 'Este armazém representa stock pessoal de %s %s',
		'SelectWarehouseForStockDecrease' => 'Escolha depósito a ser usado para diminuição de ações',
		'SelectWarehouseForStockIncrease' => 'Escolha depósito a ser usado para aumentar stock',
		'LastWaitingSupplierOrders' => 'Orders waiting for receptions'
);
?>