<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Categorie',
		'Categories' => 'Categorieën',
		'Rubrique' => 'Rubriek',
		'Rubriques' => 'Rubrieken',
		'categories' => 'categorieën',
		'TheCategorie' => 'De categorie',
		'NoCategoryYet' => 'Geen categorie van dit type gecreëerd',
		'In' => 'In',
		'AddIn' => 'Invoegen in categorie',
		'modify' => 'wijzigen',
		'Classify' => 'Classificeren',
		'CategoriesArea' => 'Categorieënoverzicht',
		'ProductsCategoriesArea' => 'Categorieënoverzicht van producten / diensten',
		'SuppliersCategoriesArea' => 'Categorieënoverzicht van leveranciers',
		'CustomersCategoriesArea' => 'Categorieënoverzicht van afnemers',
		'ThirdPartyCategoriesArea' => 'Categorieënoverzicht van derde partijen',
		'MembersCategoriesArea' => 'Categorieënoverzicht van leden',
		'MainCats' => 'Belangrijkste categorieën',
		'SubCats' => 'Subcategorieën',
		'CatStatistics' => 'Statistieken',
		'CatList' => 'categorieënlijst',
		'AllCats' => 'Alle categorieën',
		'ViewCat' => 'Bekijk categorie',
		'NewCat' => 'Categorie toevoegen',
		'NewCategory' => 'Nieuwe categorie',
		'ModifCat' => 'Categorie wijzigen',
		'CatCreated' => 'Categorie gecreëerd',
		'CreateCat' => 'Creëer categorie',
		'CreateThisCat' => 'Creëer deze categorie',
		'ValidateFields' => 'Valideer de velden',
		'NoSubCat' => 'Geen subcategorie.',
		'SubCatOf' => 'Subcategorie',
		'FoundCats' => 'Gevonden categorieën',
		'FoundCatsForName' => 'Gevonden categorieën voor de naam',
		'FoundSubCatsIn' => 'Subcategorie gevonden in de categorie',
		'ErrSameCatSelected' => 'U heeft meerder keren dezelfde categorie geselecteerd',
		'ErrForgotCat' => 'U vergat de categorie te kiezen',
		'ErrForgotField' => 'U vergat velden in te vullen',
		'ErrCatAlreadyExists' => 'Deze naam wordt al gebruikt',
		'AddProductToCat' => 'Dit product toevoegen aan een categorie?',
		'ImpossibleAddCat' => 'Niet mogelijk om de categorie toe te voegen',
		'ImpossibleAssociateCategory' => 'Niet mogelijk om de categorie te koppelen aan',
		'WasAddedSuccessfully' => '<b>%s</b> is succesvol toegevoegd.',
		'ObjectAlreadyLinkedToCategory' => 'Element is al gekoppeld aan deze categorie.',
		'CategorySuccessfullyCreated' => 'De categorie %s is met succes toegevoegd.',
		'ProductIsInCategories' => 'Product / dienst is eigenaar van de volgende categorieën',
		'SupplierIsInCategories' => 'Derde partij is eigenaar van de volgende leverancierscategorieën',
		'CompanyIsInCustomersCategories' => 'Deze derde partij is eigenaar van de volgende afnemers- / prospectencategorieën',
		'CompanyIsInSuppliersCategories' => 'Deze derde partij is eigenaar van de volgende leverancierscategorieën',
		'MemberIsInCategories' => 'Dit lid is eigenaar van de volgende ledencategorieën',
		'ProductHasNoCategory' => 'Dit product / dienst behoort tot geen enkele categorie',
		'SupplierHasNoCategory' => 'Deze leverancier behoort tot geen enkele categorie',
		'CompanyHasNoCategory' => 'Dit bedrijf behoort tot geen enkele categorie',
		'MemberHasNoCategory' => 'Dit lid behoort tot geen enkele categorie',
		'ClassifyInCategory' => 'Classificeren naar categorie',
		'NoneCategory' => 'Geen',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Deze categorie bestaat al op hetzelfde niveau',
		'ReturnInProduct' => 'Terug naar product- / dienstdetails',
		'ReturnInSupplier' => 'Terug naar leverancierdetails',
		'ReturnInCompany' => 'Terug naar de afnemer- / prospectdetails',
		'ContentsVisibleByAll' => 'De inhoud wordt zichtbaar voor iedereen',
		'ContentsVisibleByAllShort' => 'Inhoud zichtbaar voor iedereen',
		'ContentsNotVisibleByAllShort' => 'Inhoud is niet zichtbaar voor iedereen',
		'CategoriesTree' => 'Categoriestructuur',
		'DeleteCategory' => 'Categorie verwijderen',
		'ConfirmDeleteCategory' => 'Weet u zeker dat u deze categorie wilt verwijderen?',
		'RemoveFromCategory' => 'Verwijder de koppeling met de categorie',
		'RemoveFromCategoryConfirm' => 'Weet u zeker dat u het verband tussen de transactie en de categorie wilt verwijderen?',
		'NoCategoriesDefined' => 'Geen categorieën ingesteld',
		'SuppliersCategoryShort' => 'Leverancierscategorie',
		'CustomersCategoryShort' => 'Afnemerscategorie',
		'ProductsCategoryShort' => 'Productencategorie',
		'MembersCategoryShort' => 'Ledencategorie',
		'SuppliersCategoriesShort' => 'Leverancierscategorie',
		'CustomersCategoriesShort' => 'Afnemerscategorie',
		'CustomersProspectsCategoriesShort' => 'Afnemers- / Prospectencategorie',
		'ProductsCategoriesShort' => 'Productencategorie',
		'MembersCategoriesShort' => 'Ledencategorie',
		'ThisCategoryHasNoProduct' => 'Deze categorie bevat geen producten.',
		'ThisCategoryHasNoSupplier' => 'Deze categorie bevat geen enkele leverancier.',
		'ThisCategoryHasNoCustomer' => 'Deze categorie bevat geen enkele afnemer.',
		'ThisCategoryHasNoMember' => 'Deze categorie bevat geen enkel lid.',
		'AssignedToCustomer' => 'Toegewezen aan een afnemer',
		'AssignedToTheCustomer' => 'Toegewezen aan de afnemer',
		'InternalCategory' => 'Interne categorie',
		'CategoryContents' => 'Categorie-inhoud',
		'CategId' => 'Categorie-ID',
		'CatSupList' => 'Leverancierscategorieënlijst',
		'CatCusList' => 'afnemers- / prospectencategorieënlijst',
		'CatProdList' => 'productencategorieënlijst',
		'CatMemberList' => 'Ledencategorieënlijst',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>