<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Commercieel',
		'CommercialArea' => 'Commerciële gedeelte',
		'CommercialCard' => 'Commerciele details',
		'CustomerArea' => 'Afnemersdetails',
		'Customer' => 'Afnemer',
		'Customers' => 'Afnemers',
		'Prospect' => 'Prospect',
		'Prospects' => 'Prospecten',
		'DeleteAction' => 'Verwijder een actie',
		'NewAction' => 'Nieuwe actie',
		'AddAction' => 'Toevoegen actie',
		'AddAnAction' => 'Voeg een actie toe',
		'AddActionRendezVous' => 'Voeg een vergadering toe',
		'Rendez-Vous' => 'Vergadering',
		'ConfirmDeleteAction' => 'Weet u zeker dat u deze actie wilt verwijderen?',
		'CardAction' => 'Actiedetails',
		'PercentDone' => 'Percentage voltooid',
		'ActionOnCompany' => 'Actie voor bedrijf',
		'ActionOnContact' => 'Actie voor contact',
		'TaskRDV' => 'Vergaderingen',
		'TaskRDVWith' => 'Vergadering met %s',
		'ShowTask' => 'Toon taak',
		'ShowAction' => 'Toon actie',
		'ActionsReport' => 'Actiesverslag',
		'SalesRepresentative' => 'Vertegenwoordiger',
		'SalesRepresentatives' => 'Vertegenwoordigers',
		'SalesRepresentativeFollowUp' => 'Vertegenwoordiger (opvolging)',
		'SalesRepresentativeSignature' => 'Vertegenwoordiger (handtekening)',
		'CommercialInterlocutor' => 'Zakelijke gesprekspartner',
		'ErrorWrongCode' => 'Verkeerde code',
		'NoSalesRepresentativeAffected' => 'Geen specifieke vertegenwoordiger betrokken',
		'ShowCustomer' => 'Toon afnemer',
		'ShowProspect' => 'Toon prospect',
		'ListOfProspects' => 'Prospectenoverzicht',
		'ListOfCustomers' => 'Afnemersoverzicht',
		'LastDoneTasks' => 'Laatste %s gedane taken',
		'LastActionsToDo' => 'Laatste %s oudste acties niet voltooid',
		'LastRecordedTasks' => 'Laatste taken',
		'DoneActions' => 'Voltooide acties',
		'DoneActionsFor' => 'Voltooide acties voor %s',
		'ToDoActions' => 'Onvolledige acties',
		'ToDoActionsFor' => 'Onvolledige acties voor %s',
		'DoneAndToDoActionsFor' => 'Gedaan en To do taken voor %s',
		'DoneAndToDoActions' => 'Agenda',
		'SendPropalRef' => 'Stuur offerte %s',
		'SendOrderRef' => 'Stuur Opdracht %s',
		'StatusActionToDo' => 'Te doen',
		'StatusActionDone' => 'Gedaan',
		'StatusActionInProcess' => 'In uitvoering',
		'MyActionsAsked' => 'Acties die ik heb opgenomen',
		'MyActionsToDo' => 'Acties die ik moet doen',
		'MyActionsDone' => 'Acties aan mij toegewezen',
		'TasksHistoryForThisContact' => 'Acties voor deze contactpersoon',
		'LastProspectDoNotContact' => 'Geen contact opnemen',
		'LastProspectNeverContacted' => 'Nooit contact gehad',
		'LastProspectToContact' => 'Contact op te nemen met',
		'LastProspectContactInProcess' => 'Contact in uitvoering',
		'LastProspectContactDone' => 'Contact opgevolgd',
		'DateActionPlanned' => 'Datum actie gepland voor',
		'DateActionDone' => 'Datum actie uitgevoerd',
		'ActionAskedBy' => 'Actie gevraagd door',
		'ActionAffectedTo' => 'Toewijzen aan',
		'ActionDoneBy' => 'Actie gedaan door',
		'ActionUserAsk' => 'Geregistreerd door',
		'ErrorStatusCantBeZeroIfStarted' => 'Als veld \'<b>Datum uitgevoerd</b>\' is gevuld, is de actie gestart (of afgelopen), dus veld \'<b>Status</b>\' kan niet 0%% worden.',
		'ActionAC_TEL' => 'Telefoongesprek',
		'ActionAC_FAX' => 'Verzenden per fax',
		'ActionAC_PROP' => 'Verstuur offerte',
		'ActionAC_EMAIL' => 'E-mail verzenden',
		'ActionAC_RDV' => 'Vergaderingen',
		'ActionAC_FAC' => 'Stuur factuur',
		'ActionAC_REL' => 'Stuur factuur (herinnering)',
		'ActionAC_CLO' => 'Sluiten',
		'ActionAC_EMAILING' => 'Stuur bulkmail',
		'ActionAC_COM' => 'Verstuur order per mail',
		'ActionAC_SUP_ORD' => 'Stuur leverancier bestellen via e-mail',
		'ActionAC_SUP_INV' => 'Stuur factuur van de leverancier via e-mail',
		'Stats' => 'Verkoopstatistieken',
		'CAOrder' => 'Bedrijfsomzet (gevalideerde opdrachten)',
		'FromTo' => 'van %s tot %s',
		'MargeOrder' => 'Gerealiseerde marge (gevalideerde opdrachten)',
		'RecapAnnee' => 'Jaarsamenvatting',
		'NoData' => 'Geen gegevens',
		'StatusNotApplicable' => 'Niet van toepassing',
		'ActionAC_SHIP' => 'Stuur verzending per post',
		'ActionAC_OTH' => 'Ander',
		'StatusProsp' => 'Prospect-status',
		'DraftPropals' => 'Ontwerp van commerciële voorstellen',
		'SearchPropal' => 'Zoek een commercieel voorstel',
);
?>