<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$compta = array(
		'CHARSET' => 'UTF-8',
		'Accountancy' => 'Boekhouden',
		'AccountancyCard' => 'Boekhoudkundige details',
		'Treasury' => 'Treasury (schatkist) / Kasstromen',
		'MenuFinancial' => 'Financieel',
		'TaxModuleSetupToModifyRules' => 'Ga naar <a href="%s">Moduleinstellingen</a> om de regels voor berekening te wijzigen',
		'OptionMode' => 'Optie voor boekhouding',
		'OptionModeTrue' => 'Optie Inkomsten-Uitgaven',
		'OptionModeVirtual' => 'Optie crediteringen - debiteringen',
		'OptionModeTrueDesc' => 'In deze context wordt de omzet berekend op basis van betalingen (betaaldatum). \nDe validiteit van de cijfers kan alleen worden gegarandeerd wanneer de boekhouding wordt gecontroleerd door middel van de Inkomsten / Uitgaves via facturen op de rekeningen.',
		'OptionModeVirtualDesc' => 'In deze context, wordt de omzet berekend op basis van facturen (datum van validatie). Wanneer deze facturen verschuldigd zijn worden ze opgesomd in de omzetuitvoer, of ze nu betaald zijn of niet.',
		'FeatureIsSupportedInInOutModeOnly' => 'Functionaliteit alleen beschikbaar in de VORDERINGEN-SCHULDEN modus (zie de boekhoudingsmodule instellingen)',
		'VATReportBuildWithOptionDefinedInModule' => 'De hier getoonde bedragen zijn berekend door gebruik te maken van regels zoals ingesteld in de Belastingmoduleinstellingen.',
		'Param' => 'Instellen',
		'RemainingAmountPayment' => 'Bedrag betaling resteert:',
		'AmountToBeCharged' => 'Totaal te betalen bedrag:',
		'AccountsGeneral' => 'Rekeningen',
		'Account' => 'Rekening',
		'Accounts' => 'Rekeningen',
		'Accountparent' => 'Account parent',
		'Accountsparent' => 'Accounts parent',
		'BillsForSuppliers' => 'Facturen voor leveranciers',
		'Income' => 'Inkomsten',
		'Outcome' => 'Kosten',
		'ReportInOut' => 'Opbrengsten / kosten',
		'ReportTurnover' => 'Omzet',
		'PaymentsNotLinkedToInvoice' => 'Betalingen niet gekoppeld aan een factuur, dus niet gekoppeld aan een derde partij',
		'PaymentsNotLinkedToUser' => 'Betalingen niet gekoppeld aan een gebruiker',
		'Profit' => 'Winst',
		'Balance' => 'Saldo',
		'Debit' => 'Debet',
		'Credit' => 'Credit',
		'Withdrawal' => 'Intrekking',
		'Withdrawals' => 'Opnames',
		'AmountHTVATRealReceived' => 'Netto ontvangen',
		'AmountHTVATRealPaid' => 'Netto betaald',
		'VATToPay' => 'BTW verkopen',
		'VATReceived' => 'BTW ontvangen',
		'VATToCollect' => 'BTW aankopen',
		'VATSummary' => 'BTW saldo',
		'LT2SummaryES' => 'IRPF Balance',
		'VATPaid' => 'Betaalde BTW',
		'LT2PaidES' => 'IRPF Betaalde',
		'LT2CustomerES' => 'IRPF verkoop',
		'LT2SupplierES' => 'IRPF aankopen',
		'VATCollected' => 'Geïnde  BTW',
		'ToPay' => 'Te betalen',
		'ToGet' => 'Om terug te komen',
		'TaxAndDividendsArea' => 'Belastingen-, sociale bijdragen- en dividendenoverzicht',
		'SocialContribution' => 'Sociale bijdragen',
		'SocialContributions' => 'Sociale bijdragen',
		'MenuTaxAndDividends' => 'Belastingen en dividenden',
		'MenuSocialContributions' => 'Sociale premies',
		'MenuNewSocialContribution' => 'Nieuwe bijdrage',
		'NewSocialContribution' => 'Nieuwe sociale bijdrage',
		'ContributionsToPay' => 'Te betalen bijdragen',
		'AccountancyTreasuryArea' => 'Treasury- (schatkist) / boekhoudingsoverzicht',
		'AccountancySetup' => 'Boekhoudingsinstellingen',
		'NewPayment' => 'Nieuwe betaling',
		'Payments' => 'Betalingen',
		'PaymentCustomerInvoice' => 'Afnemersfactuur betaling',
		'PaymentSupplierInvoice' => 'Leveranciersfactuur betaling',
		'PaymentSocialContribution' => 'Sociale bijdrage betaling',
		'PaymentVat' => 'BTW betaling',
		'ListPayment' => 'Betalingenlijst',
		'ListOfPayments' => 'Betalingenlijst',
		'ListOfCustomerPayments' => 'Afnemersbetalingenlijst',
		'ListOfSupplierPayments' => 'Leveranciersbetalingenlijst',
		'DatePayment' => 'Betaaldatum',
		'NewVATPayment' => 'Nieuwe BTW-betaling',
		'newLT2PaymentES' => 'Nieuwe IRPF betaling',
		'LT2PaymentES' => 'IRPF betaling',
		'LT2PaymentsES' => 'IRPF Betalingen',
		'VATPayment' => 'BTW-betaling',
		'VATPayments' => 'BTW-betalingen',
		'SocialContributionsPayments' => 'Betalingen van sociale bijdragen',
		'ShowVatPayment' => 'Toon BTW-betaling',
		'TotalToPay' => 'Totaal te voldoen',
		'TotalVATReceived' => 'Totale BTW ontvangsten',
		'CustomerAccountancyCode' => 'Boekhoudkundige afnemerscode',
		'SupplierAccountancyCode' => 'Boekhoudkundige leverancierscode',
		'AlreadyPaid' => 'Reeds betaald',
		'AccountNumberShort' => 'Rek. nr.',
		'AccountNumber' => 'Rekeningnummer',
		'NewAccount' => 'Nieuwe rekening',
		'SalesTurnover' => 'Omzet',
		'ByThirdParties' => 'Door derde partijen',
		'ByUserAuthorOfInvoice' => 'Op factuurauteur',
		'AccountancyExport' => 'Boekhouding exporteren',
		'ErrorWrongAccountancyCodeForCompany' => 'Onjuiste boekhoudkundige afnemerscode voor %s',
		'SuppliersProductsSellSalesTurnover' => 'De omzet gegenereerd door de verkoop van leveranciersproducten.',
		'CheckReceipt' => 'Controleer stortingen',
		'CheckReceiptShort' => 'Controleer stortingen',
		'NewCheckReceipt' => 'Nieuwe korting',
		'NewCheckDeposit' => 'Nieuwe chequestorting',
		'NewCheckDepositOn' => 'Creeer een kwitantie voor de storting op rekening: %s',
		'NoWaitingChecks' => 'Geen cheques die op storting wachten',
		'DateChequeReceived' => 'Ontvangstdatum cheque',
		'NbOfCheques' => 'Aantal cheques',
		'PaySocialContribution' => 'Betaal een sociale bijdrage',
		'ConfirmPaySocialContribution' => 'Weet u zeker dat u deze sociale bijdrage als betaald wilt aanmerken ?',
		'DeleteSocialContribution' => 'Verwijder een sociale bijdrage',
		'ConfirmDeleteSocialContribution' => 'Weet u zeker dat u deze sociale bijdrage wilt verwijderen?',
		'ExportDataset_tax_1' => 'Sociale premies en betalingen',
		'AnnualSummaryDueDebtMode' => 'Saldo van inkomsten en uitgaven, jaarlijkse samenvatting, mode<b> %sClaims-Schulden%s</b> volgens <b>verplichte boekhouding</b>.',
		'AnnualSummaryInputOutputMode' => 'Saldo van inkomsten en uitgaven, jaarlijkse samenvatting, modus <b>%sOntvangsten-Uitgaven%s</b> volgens <b>kasboek</b>.',
		'AnnualByCompaniesDueDebtMode' => 'Saldo van inkomsten en uitgaven, details door derde partijen, mode<b> %sClaims-Schulden%s</b> volgens <b>verplichte boekhouding</b>.',
		'AnnualByCompaniesInputOutputMode' => 'Saldo van inkomsten en uitgaven, details door derde partijen, modus <b>%sOntvangsten-Uitgaven%s</b> volgens <b>kasboek</b>.',
		'SeeReportInInputOutputMode' => 'Zie de rapportage <b>%sInkomsten-Uitgaven%s</b> volgens <b>kasboek</b> voor een berekening pp de daadwerkelijke gedane betalingen',
		'SeeReportInDueDebtMode' => 'Zie de rapportage <b>%sClaims-Schulden%s</b> volgens <b>verplichte boekhouding</b> voor een berekening van uitgegeven facturen',
		'RulesResultDue' => '- Getoonde bedragen zijn inclusief alle belastingen<br>- Het bevat openstaande facturen, onkosten en BTW of ze nu betaald zijn of niet.<br>- Het is gebaseerd op de validatiedatum van facturen en BTW en op de vervaldatum van de kosten.',
		'RulesResultInOut' => '- De getoonde bedragen zijn inclusief alle belastingen<br>- Het bevat de daadwerkelijke betalingen van facturen, onkosten en BTW.<br>- Het is gebaseerd op de betaaldata van de facturen, uitgaven en BTW.<br>',
		'RulesCADue' => '- Het bevat de verschuldigde facturen van de afnemer (behalve depositofacturen) of ze nu betaald zijn of niet.<br>- Het is gebaseerd op de validatiedatum van deze facturen.<br>',
		'RulesCAIn' => '- Het bevat alle effectieve betalingen van afnemersfacturen.<br>- Het is gebaseerd op de betaaldatum van deze facturen<br>',
		'DepositsAreNotIncluded' => '- Storting facturen worden ook niet opgenomen',
		'DepositsAreIncluded' => '- Storting facturen zijn opgenomen',
		'LT2ReportByCustomersInInputOutputModeES' => 'Verslag van derden IRPF',
		'VATReportByCustomersInInputOutputMode' => 'Rapportage van de afnemer over geïnde en betaalde BTW (BTW ontvangst)',
		'VATReportByCustomersInDueDebtMode' => 'Rapportage van de afnemer over geïnde en betaalde BTW (BTW-tarief)',
		'VATReportByQuartersInInputOutputMode' => 'Rapportage van ontvangen en betaalde BTW opgesplitst naar tarief (BTW ontvangst)',
		'VATReportByQuartersInDueDebtMode' => 'Rapportage van ontvangen en betaalde BTW opgesplitst naar tarief (BTW-tarief)',
		'SeeVATReportInInputOutputMode' => 'Zie rapportage <b>%sBTW-inning%s</b> voor een standaard berekening',
		'SeeVATReportInDueDebtMode' => 'Zie rapportage <b>%sBTW op doorstroming%s</b> voor een berekening met een optie op de doorstroming',
		'RulesVATInServices' => '- Voor diensten, omvat het verslag van de BTW-regelgeving daadwerkelijk ontvangen of afgegeven op basis van de datum van betaling. <br> - Voor materiële goederen, het bevat de btw-facturen op basis van de factuurdatum.',
		'RulesVATInProducts' => '- Voor materiële goederen, het bevat de btw-facturen op basis van de factuurdatum.',
		'RulesVATDueServices' => '- Voor diensten, het rapport is inclusief BTW vervallen facturen, betaald of niet, op basis van de factuurdatum.',
		'RulesVATDueProducts' => '- Voor materiële goederen, het bevat de btw-facturen, op basis van de factuurdatum.',
		'OptionVatInfoModuleComptabilite' => 'Opmerking: Voor materiële activa, zou het gebruik moeten maken van de afleverdatum om eerlijker te zijn.',
		'PercentOfInvoice' => '%%/factuur',
		'NotUsedForGoods' => 'Niet gebruikt voor goederen',
		'ProposalStats' => 'Statistieken over de voorstellen',
		'OrderStats' => 'Opdrachtstatistieken',
		'InvoiceStats' => 'Statistieken over rekeningen',
		'Dispatch' => 'Verzending',
		'Dispatched' => 'Verzonden',
		'ToDispatch' => 'Te verzenden',
		'ThirdPartyMustBeEditAsCustomer' => 'Derde partij moet als afnemer worden gedefinieerd',
		'SellsJournal' => 'Verkoopdagboek',
		'PurchasesJournal' => 'Inkoopdagboek',
		'DescSellsJournal' => 'Verkoopdagboek',
		'DescPurchasesJournal' => 'Inkoopdagboek',
		'InvoiceRef' => 'Factuur ref.',
		'CodeNotDef' => 'Niet gedefinieerd',
		'AddRemind' => 'Verzending beschikbare bedrag',
		'RemainToDivide' => 'Blijven verzending:',
		'WarningDepositsNotIncluded' => 'Deposito facturen worden niet opgenomen in deze versie met deze accountancy module.',
		'DatePaymentTermCantBeLowerThanObjectDate' => 'Payment term date can\'t be lower than object date.',
		'Pcg_version' => 'Pcg version',
		'Pcg_type' => 'Pcg type',
		'Pcg_subtype' => 'Pcg subtype',
		'Withdrawl' => 'Prélèvement',
		'Withdrawls' => 'Prélèvements',
		'ToGetBack' => 'A récupérer',
		'Journaux' => 'Journaux',
		'Piece' => 'Piece compta',
		'JournalNum' => 'Journal',
		'COMPTA_JOURNAL_SELL' => 'Numéro comptable du Journal des Achats',
		'COMPTA_JOURNAL_BUY' => 'Numéro comptable du Journal des Ventes',
		'COMPTA_PRODUCT_BUY_ACCOUNT' => 'Compte comptable par défaut pour produits achetés (si non défini sur fiche produit)',
		'COMPTA_PRODUCT_SOLD_ACCOUNT' => 'Compte comptable par défaut pour produits vendus (si non défini sur fiche produit)',
		'COMPTA_SERVICE_BUY_ACCOUNT' => 'Compte comptable par défaut pour services achetés (si non défini sur fiche service)',
		'COMPTA_SERVICE_SOLD_ACCOUNT' => 'Compte comptable par défaut pour services vendus (si non défini sur fiche service)',
		'COMPTA_VAT_ACCOUNT' => 'Compte comptable par défaut pour TVA (si non défini dans dictionnaire "Taux de TVA")',
		'COMPTA_ACCOUNT_CUSTOMER' => 'Compte comptable client par défaut (si non défini sur fiche tiers)',
		'COMPTA_ACCOUNT_SUPPLIER' => 'Compte comptable fournisseur par défaut (si non défini sur fiche tiers)',
);
?>