<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$propal = array(
		'CHARSET' => 'UTF-8',
		'Proposals' => 'Offertes',
		'Proposal' => 'Offerte',
		'ProposalShort' => 'Offerte',
		'ProposalsDraft' => 'Conceptofferte',
		'ProposalDraft' => 'Conceptofferte',
		'ProposalsOpened' => 'Geopende offertes',
		'Prop' => 'Offertes',
		'CommercialProposal' => 'Offerte',
		'CommercialProposals' => 'Offertes',
		'ProposalCard' => 'Offertedetailkaart',
		'NewProp' => 'Nieuwe offerte',
		'NewProposal' => 'Nieuwe offerte',
		'NewPropal' => 'Nieuwe offerte',
		'Prospect' => 'Prospect',
		'ProspectList' => 'Prospectenlijst',
		'DeleteProp' => 'Offerte verwijderen',
		'ValidateProp' => 'Offerte valideren',
		'AddProp' => 'Offerte toevoegen',
		'ConfirmDeleteProp' => 'Weet u zeker dat u deze offerte wilt verwijderen?',
		'ConfirmValidateProp' => 'Weet u zeker dat u deze offerte wilt valideren?',
		'LastPropals' => 'Laatste %s offertes',
		'LastClosedProposals' => 'Laatste %s gesloten offertes',
		'LastModifiedProposals' => 'Laatste %s gewijzigde offertes',
		'AllPropals' => 'Alle offertes',
		'LastProposals' => 'Laatste offertes',
		'SearchAProposal' => 'Zoek een offerte',
		'ProposalsStatistics' => 'Offertestatistieken',
		'NumberOfProposalsByMonth' => 'Aantal per maand',
		'AmountOfProposalsByMonthHT' => 'Bedrag per maand (exclusief belastingen)',
		'NbOfProposals' => 'Aantal offertes',
		'ShowPropal' => 'Toon offerte',
		'PropalsDraft' => 'Concepten',
		'PropalsOpened' => 'Geopend',
		'PropalsNotBilled' => 'Gesloten niet gefactureerd',
		'PropalStatusDraft' => 'Concept (moet worden gevalideerd)',
		'PropalStatusValidated' => 'Gevalideerd (Offerte staat open)',
		'PropalStatusOpened' => 'Gevalideerd (Offerte staat open)',
		'PropalStatusClosed' => 'Gesloten',
		'PropalStatusSigned' => 'Ondertekend (te factureren)',
		'PropalStatusNotSigned' => 'Niet ondertekend (gesloten)',
		'PropalStatusBilled' => 'Gefactureerd',
		'PropalStatusDraftShort' => 'Concept',
		'PropalStatusValidatedShort' => 'Gevalideerd',
		'PropalStatusOpenedShort' => 'Geopend',
		'PropalStatusClosedShort' => 'Gesloten',
		'PropalStatusSignedShort' => 'Ondertekend',
		'PropalStatusNotSignedShort' => 'Niet ondertekend',
		'PropalStatusBilledShort' => 'Gefactureerd',
		'PropalsToClose' => 'Te sluiten offertes',
		'PropalsToBill' => 'Ondertekende offertes die gefactureerd moeten worden',
		'ListOfProposals' => 'Offertelijst',
		'ActionsOnPropal' => 'Offerte-acties',
		'NoOpenedPropals' => 'Aantal openstaande offertes',
		'NoOtherOpenedPropals' => 'Geen enkel andere openstaande offerte',
		'RefProposal' => 'Offertereferentie',
		'SendPropalByMail' => 'Stuur offerte per e-mail',
		'FileNotUploaded' => 'Het bestand is niet geüpload',
		'FileUploaded' => 'Het bestand is geüpload',
		'AssociatedDocuments' => 'Documenten gelinkt aan de offerte:',
		'ErrorCantOpenDir' => 'Kan map niet openen',
		'DatePropal' => 'Offertedatum',
		'DateEndPropal' => 'Einddatum geldigheid',
		'DateEndPropalShort' => 'Einddatum',
		'ValidityDuration' => 'Geldigheidsduur',
		'CloseAs' => 'Sluiten met status',
		'ClassifyBilled' => 'Classificeer als gefactureerd',
		'BuildBill' => 'Creëer factuur',
		'ErrorPropalNotFound' => 'Offerte %s niet gevonden',
		'Estimate' => 'Raming:',
		'EstimateShort' => 'Raming',
		'OtherPropals' => 'Andere offertes',
		'CopyPropalFrom' => 'Maak offerte door het kopiëren van een bestaande offerte',
		'CreateEmptyPropal' => 'Creëer een lege offerte of uit de lijst van producten / diensten',
		'DefaultProposalDurationValidity' => 'Standaardgeldigheid offerte (in dagen)',
		'UseCustomerContactAsPropalRecipientIfExist' => 'Gebruik,  indien ingesteld, het afnemerscontactadres als offerteontvangstadres in plaats van het adres van de derde partij',
		'ClonePropal' => 'Kloon offerte',
		'ConfirmClonePropal' => 'Weet u zeker dat u deze offerte <b>%s</b> wilt klonen?',
		'ConfirmReOpenProp' => 'Weet je zeker dat je wilt openen weer de commerciële voorstel <b>%s?</b>',
		'ProposalsAndProposalsLines' => 'Offertes en offerteregels',
		'ProposalLine' => 'Offerteregels',
		'ProposalLines' => 'Proposal lines',
		'AvailabilityPeriod' => 'Beschikbaarheid van vertraging',
		'SetAvailability' => 'Set beschikbaarheid vertraging',
		'AfterOrder' => 'na bestelling',
		////////// Availability //////////
		'AvailabilityTypeAV_NOW' => 'Onmiddellijk',
		'AvailabilityTypeAV_1W' => '1 week',
		'AvailabilityTypeAV_2W' => '2 weken',
		'AvailabilityTypeAV_3W' => '3 weken',
		'AvailabilityTypeAV_1M' => '1 maand',
		////////// Types de contacts //////////
		'TypeContact_propal_internal_SALESREPFOLL' => 'Vertegenwoordiger die de follow-up van de offerte doet',
		'TypeContact_propal_external_BILLING' => 'Afnemersfactuurcontactpersoon',
		'TypeContact_propal_external_CUSTOMER' => 'Afnemerscontactpersoon follow-up voorstel',
		// Document models
		'DocModelAzurDescription' => 'Een compleet offertemodel (logo, etc)',
		'DocModelJauneDescription' => 'Jaune offertemodel',
		'Numbershort' => 'N°',
		'LinkdedOrders' => 'Linked orders'
);
?>