<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Magazijndetailkaart',
		'Warehouse' => 'Magazijn',
		'NewWarehouse' => 'Nieuw magazijn / Vooraadoverzicht',
		'WarehouseEdit' => 'Magazijn wijzigen',
		'MenuNewWarehouse' => 'Nieuw magazijn',
		'WarehouseOpened' => 'Magazijn geopend',
		'WarehouseClosed' => 'Magazijn gesloten',
		'WarehouseSource' => 'Bronmagazijn',
		'WarehouseTarget' => 'Doelmagazijn',
		'ValidateSending' => 'Valideer verzending',
		'CancelSending' => 'Annuleer verzending',
		'DeleteSending' => 'Verwijder verzending',
		'Stock' => 'Voorraad',
		'Stocks' => 'Voorraden',
		'Movement' => 'Mutatie',
		'Movements' => 'Mutaties',
		'ErrorWarehouseRefRequired' => 'Magazijnreferentienaam is verplicht',
		'ErrorWarehouseLabelRequired' => 'Magazijnlable is vereist',
		'CorrectStock' => 'Corrigeer voorraad',
		'ListOfWarehouses' => 'Magazijnenlijst',
		'ListOfStockMovements' => 'Voorraadmutatielijst',
		'StocksArea' => 'Voorradenoverzicht',
		'Location' => 'Locatie',
		'LocationSummary' => 'Korte naam locatie',
		'NumberOfProducts' => 'Totaal aantal producten',
		'LastMovement' => 'Laatste mutatie',
		'LastMovements' => 'Laatste mutaties',
		'Units' => 'Eenheden',
		'Unit' => 'Eenheid',
		'StockCorrection' => 'Voorraadcorrectie',
		'StockMovement' => 'Voorraadmutatie',
		'StockMovements' => 'Voorraadmutaties',
		'NumberOfUnit' => 'Aantal eenheden',
		'TotalStock' => 'Totaal in voorraad',
		'StockTooLow' => 'Voorraad te laag',
		'EnhancedValue' => 'Waardering',
		'PMPValue' => 'Waardering (PMP)',
		'PMPValueShort' => 'Waarde',
		'EnhancedValueOfWarehouses' => 'Voorraadwaardering',
		'UserWarehouseAutoCreate' => 'Creëer automatisch een magazijn bij het aanmaken van een gebruiker',
		'QtyDispatched' => 'Hoeveelheid verzonden',
		'OrderDispatch' => 'Voorraadverzending',
		'RuleForStockManagementDecrease' => 'Regel voor voorraadbeheerafname',
		'RuleForStockManagementIncrease' => 'Regel voor voorraadbeheertoename',
		'DeStockOnBill' => 'Verlaag de echte voorraad na het valideren van afnemersfacturen / creditnota\'s',
		'DeStockOnValidateOrder' => 'Verlaag de echte voorraad na het valideren van opdrachten',
		'DeStockOnShipment' => 'Verlaag de echte voorraad na het valideren van verzendingen',
		'ReStockOnBill' => 'Verhoog de echte voorraad na het valideren van leveranciersfacturen / creditnota\'s',
		'ReStockOnValidateOrder' => 'Verhoog de echte voorraad na het valideren van leveranciersopdrachten',
		'ReStockOnDispatchOrder' => 'Verhoog de echte voorraad na het handmatig verzenden naar magazijnen, nadat de leveranciersopdracht ontvangst',
		'OrderStatusNotReadyToDispatch' => 'Opdracht heeft nog geen, of niet langer, een status die het verzenden van producten naar een magazijn toestaat.',
		'StockDiffPhysicTeoric' => 'Reden voor het verschil tussen de feitelijke en theoretische voorraad',
		'NoPredefinedProductToDispatch' => 'Geen vooraf ingestelde producten voor dit object. Daarom is verzending in voorraad niet vereist.',
		'DispatchVerb' => 'Verzending',
		'StockLimitShort' => 'Limiet',
		'StockLimit' => 'Voorraadlimiet voor kennisgeving',
		'PhysicalStock' => 'Fysieke voorraad',
		'RealStock' => 'Werkelijke voorraad',
		'TheoreticalStock' => 'Theoretische voorraad',
		'VirtualStock' => 'Virtuele voorraad',
		'MininumStock' => 'Minimumvoorraad',
		'StockUp' => 'Maximumvoorraad',
		'MininumStockShort' => 'Voorraad min',
		'StockUpShort' => 'Voorraad max',
		'IdWarehouse' => 'Magazijn-ID',
		'DescWareHouse' => 'Beschrijving magazijn',
		'LieuWareHouse' => 'Localisatie magazijn',
		'WarehousesAndProducts' => 'Magazijn en producten',
		'AverageUnitPricePMPShort' => 'Gewogen gemiddelde inkoopprijs',
		'AverageUnitPricePMP' => 'Gewogen gemiddelde inkoopprijs',
		'EstimatedStockValueShort' => 'Geschatte voorraadwaarde',
		'EstimatedStockValue' => 'Geschatte voorraadwaarde',
		'DeleteAWarehouse' => 'Verwijder een magazijn',
		'ConfirmDeleteWarehouse' => 'Weet u zeker dat u het magazijn <b>%s</b> wilt verwijderen?',
		'PersonalStock' => 'Persoonlijke voorraad %s',
		'ThisWarehouseIsPersonalStock' => 'Dit magazijn vertegenwoordigt een persoonlijke voorraad van %s %s',
		'SellPriceMin' => 'Verkopen Prijs per Eenheid',
		'EstimatedStockValueSellShort' => 'Waarde te verkopen',
		'EstimatedStockValueSell' => 'Waarde voor verkopen',
		'SelectWarehouseForStockDecrease' => 'Kies magazijn te gebruiken voor voorraad daling',
		'SelectWarehouseForStockIncrease' => 'Kies magazijn te gebruiken voor verhoging van voorraad',
);
?>