<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'Gebruikersdetails',
		'ContactCard' => 'Contactdetails',
		'GroupCard' => 'Groepsdetails',
		'NoContactCard' => 'Geen contactdetails',
		'Permission' => 'Toestemming',
		'Permissions' => 'Rechten',
		'EditPassword' => 'Wijzig wachtwoord',
		'SendNewPassword' => 'Genereer en stuur nieuw wachtwoord',
		'ReinitPassword' => 'Genereer een nieuw wachtwoord',
		'PasswordChangedTo' => 'Wachtwoord gewijzigd in: %s',
		'SubjectNewPassword' => 'Uw nieuwe wachtwoord voor Speedealing',
		'AvailableRights' => 'Beschikbare rechten',
		'OwnedRights' => 'Verkregen rechten',
		'GroupRights' => 'Groepsrechten',
		'UserRights' => 'Gebruikersrechten',
		'UserGUISetup' => 'Gebruikersscherminstellingen',
		'DisableUser' => 'Uitschakelen',
		'DisableAUser' => 'Schakel de gebruikertoegang uit',
		'DeleteUser' => 'Verwijderen',
		'DeleteAUser' => 'Verwijder een gebruiker',
		'DisableGroup' => 'Deactiveren',
		'DisableAGroup' => 'Deactiveer een groep',
		'EnableAUser' => 'Activeer een gebruiker',
		'EnableAGroup' => 'Activeer een groep',
		'DeleteGroup' => 'Verwijderen',
		'DeleteAGroup' => 'Verwijder een groep',
		'ConfirmDisableUser' => 'Weet u zeker dat u de toegang voor de gebruiker <b>%s</b> wilt uitschakelen?',
		'ConfirmDisableGroup' => 'Weet u zeker dat u de toegang voor de groep <b>%s</b> wilt uitschakelen?',
		'ConfirmDeleteUser' => 'Weet u zeker dat u de gebruiker <b>%s</b> wilt verwijderen?',
		'ConfirmDeleteGroup' => 'Weet u zeker dat u de groep <b>%s</b> wilt verwijderen?',
		'ConfirmEnableUser' => 'Weet u zeker dat u de gebruiker <b>%s</b> wilt activeren?',
		'ConfirmEnableGroup' => 'Weet u zeker dat u de groep <b>%s</b> wilt activeren?',
		'ConfirmReinitPassword' => 'Weet u zeker dat u voor de gebruiker <b>%s</b> een nieuw wachtwoord wilt genereren?',
		'ConfirmSendNewPassword' => 'Weet u zeker dat u een nieuw wachtwoord wilt genereren en verzenden voor de gebruiker <b>%s</b>?',
		'NewUser' => 'Nieuwe gebruiker',
		'CreateUser' => 'Creëer gebruiker',
		'SearchAGroup' => 'Zoek een groep',
		'SearchAUser' => 'Zoek een gebruiker',
		'LoginNotDefined' => 'Gebruikersnaam is niet ingesteld',
		'NameNotDefined' => 'Naam is niet gedefinierd.',
		'ListOfUsers' => 'Lijst van gebruikers',
		'Administrator' => 'Administrator',
		'SuperAdministrator' => 'Super administrator',
		'SuperAdministratorDesc' => 'Super administrateur heeft volledige rechten',
		'AdministratorDesc' => 'Administrators entiteit',
		'DefaultRights' => 'Standaardrechten',
		'DefaultRightsDesc' => 'Stel hier de standaardrechten in die automatisch toegekend worden aan nieuwe gebruiker.',
		'SpeedealingUsers' => 'Speedealing users',
		'LastName' => 'Achternaam',
		'FirstName' => 'Voornaam',
		'ListOfGroups' => 'Lijst van groepen',
		'NewGroup' => 'Nieuwe groep',
		'CreateGroup' => 'Groep maken',
		'RemoveFromGroup' => 'Verwijderen uit groep',
		'PasswordChangedAndSentTo' => 'Wachtwoord veranderd en verstuurd naar <b>%s</b>.',
		'PasswordChangeRequestSent' => 'Verzoek om wachtwoord te wijzigen van <b>%s</b> verstuurt naar <b>%s</b>.',
		'MenuUsersAndGroups' => 'Gebruikers & groepen',
		'LastGroupsCreated' => 'Laatste %s gemaakte groep(en)',
		'LastUsersCreated' => 'Laatste %s gemaakte gebruiker(s)',
		'ShowGroup' => 'Toon groep',
		'ShowUser' => 'Toon gebruiker',
		'NonAffectedUsers' => 'Niet betrokken gebruikers',
		'UserModified' => 'Gebruiker met succes gewijzigd',
		'GroupModified' => 'Groep %s bewerkt',
		'PhotoFile' => 'Foto bestand',
		'UserWithSpeedealingAccess' => 'User with Speedealing access',
		'ListOfUsersInGroup' => 'Lijst van gebruikers in deze groep',
		'ListOfGroupsForUser' => 'Lijst van groepen voor deze gebruiker',
		'UsersToAdd' => 'Gebruikers toe te voegen aan deze groep',
		'GroupsToAdd' => 'Groepen toe te voegen aan deze gebruiker',
		'NoLogin' => 'Geen gebruikersnaam',
		'LinkToCompanyContact' => 'Derden link/contact',
		'LinkedToSpeedealingMember' => 'Link to member',
		'LinkedToSpeedealingUser' => 'Link to Speedealing user',
		'LinkedToSpeedealingThirdParty' => 'Link to Speedealing third party',
		'CreateSpeedealingLogin' => 'Create a user',
		'CreateSpeedealingThirdParty' => 'Create a third party',
		'LoginAccountDisable' => 'Dit account is uitgeschakeld, zet een nieuwe login om te activeren.',
		'LoginAccountDisableInSpeedealing' => 'Account disabled in Speedealing.',
		'LoginAccountDisableInLdap' => 'Account uitgeschakeld op het domein.',
		'UsePersonalValue' => 'Gebruik persoonlijke waarde',
		'GuiLanguage' => 'Interface taal',
		'InternalUser' => 'Interne gebruiker',
		'MyInformations' => 'Mijn gegevens',
		'ExportDataset_user_1' => 'Speedealing\'s gebruikers en eigenschappen',
		'DomainUser' => 'Domeingebruikersaccount %s',
		'Reactivate' => 'Reactiveren',
		'CreateInternalUserDesc' => 'Hier kunt u een interne gebruiker voor uw bedrijf Creëren. Als u een externe gebruiker (afnemer, leverancier, etc) wilt creëren, gebruik dan de knop "Creëer nieuwe derde partij" uit in het menu "derde partijen".',
		'InternalExternalDesc' => 'Een <b>interne</b> gebruiker is een gebruiker die deel uitmaakt van uw bedrijf.<br>Een <b>externe</b> gebruiker is een afnemer, leverancier of andere. <br><br> In beide gevallen kunnen de rechten binnen Speedealing ingesteld worden. Ook kan een externe gebruiker over een ander menuverwerker beschikken dan een interne gebruiker (Zie Home->Instellingen->Scherm)',
		'PermissionInheritedFromAGroup' => 'Toestemming verleend, omdat geërfd van een bepaalde gebruikersgroep.',
		'Inherited' => 'Overgeërfd',
		'UserWillBeInternalUser' => 'Gemaakt gebruiker een interne gebruiker te zijn (want niet gekoppeld aan een bepaalde derde partij)',
		'UserWillBeExternalUser' => 'Gemaakt gebruiker zal een externe gebruiker (omdat gekoppeld aan een bepaalde derde partij)',
		'IdPhoneCaller' => 'Beller ID (telefoon)',
		'UserLogged' => 'Gebruiker %s ingelogd',
		'UserLogoff' => 'Gebruik %s uitgelogd',
		'NewUserCreated' => 'Gebruiker %s gemaakt',
		'NewUserPassword' => 'Wachtwoord wijzigen voor %s',
		'EventUserModified' => 'Gebruiker %s gewijzigd',
		'UserDisabled' => 'Gebruiker %s uitgeschakeld',
		'UserEnabled' => 'Gebruiker %s geactiveerd',
		'UserDeleted' => 'Gebruiker %s verwijderd',
		'NewGroupCreated' => 'Groep %s gemaakt',
		'GroupModified' => 'Groep %s bewerkt',
		'GroupDeleted' => 'Groep %s verwijderd',
		'ConfirmCreateContact' => 'Weet u zeker dat u een Speedealing account wilt maken voor deze contactpersoon?',
		'ConfirmCreateLogin' => 'Weet u zeker dat u een Speedealing account wilt maken voor dit lid?',
		'ConfirmCreateThirdParty' => 'Weet u zeker dat u een \'derden\' partij wilt maken voor dit lid?',
		'LoginToCreate' => 'Te creëren gebruikersnaam',
		'NameToCreate' => 'Naam van derden maken',
		'YourRole' => 'Uw rollen',
		'YourQuotaOfUsersIsReached' => 'Uw quotum van actieve gebruikers is bereikt!',
		'NbOfUsers' => 'Nb van gebruikers',
		'DontDowngradeSuperAdmin' => 'Alleen een superadmin kan downgrade een superadmin',
		'NewDatabase' => 'Nouvelle base de données',
		'CreateDatabase' => 'Créer la base de données',
		'ListOfDatabases' => 'Liste des bases de données',
		'ListOfUsersInDatabase' => 'Liste des utilisateurs liés à la base de données',
		'ListOfRolesInDatabase' => 'Liste des groupes liés à la base de données',
		'DeleteADatabase' => 'Suppression d\'une database',
		'ConfirmDatabase' => 'Êtes-vous sûr de vouloir supprimer la base de données <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Groupes non affectés à la base de données',
		'NonAffectedUsersDatabase' => 'Utilisateurs non affectés à la base de données',
		'Collaborators' => 'Collaborateurs',
		'Profiles' => 'Profils collaborateurs'
);
?>