<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Категория',
		'Categories' => 'Категории',
		'Rubrique' => 'Категория',
		'Rubriques' => 'Категории',
		'categories' => 'категории',
		'TheCategorie' => 'Категория',
		'NoCategoryYet' => 'Категории этого типа не созданы',
		'In' => 'В',
		'AddIn' => 'Добавить в',
		'modify' => 'изменить',
		'Classify' => 'Добавить',
		'CategoriesArea' => 'Область категорий',
		'ProductsCategoriesArea' => 'Область категорий Товаров/Услуг',
		'SuppliersCategoriesArea' => 'Область категорий Поставщиков',
		'CustomersCategoriesArea' => 'Область категорий Покупателей',
		'ThirdPartyCategoriesArea' => 'Область категорий Контрагентов',
		'MembersCategoriesArea' => 'Область категорий участников',
		'MainCats' => 'Основные категории',
		'SubCats' => 'Подкатегории',
		'CatStatistics' => 'Статистика',
		'CatList' => 'Список категорий',
		'AllCats' => 'Все категории',
		'ViewCat' => 'Просмотреть категорию',
		'NewCat' => 'Добавить категорию',
		'NewCategory' => 'Новая категория',
		'ModifCat' => 'Изменить категорию',
		'CatCreated' => 'Категория создана',
		'CreateCat' => 'Создать категорию',
		'CreateThisCat' => 'Создать эту категорию',
		'ValidateFields' => 'Проверить поля',
		'NoSubCat' => 'Нет подкатегории.',
		'SubCatOf' => 'Подкатегория',
		'FoundCats' => 'Найдено категорий',
		'FoundCatsForName' => 'Найдено категорей по имени:',
		'FoundSubCatsIn' => 'Подкатегории, найденные в категории',
		'ErrSameCatSelected' => 'Вы выбрали ту же самую категорию несколько раз',
		'ErrForgotCat' => 'Вы забыли выбрать категорию',
		'ErrForgotField' => 'Вы забыли заполнить поля',
		'ErrCatAlreadyExists' => 'Это имя уже используется',
		'AddProductToCat' => 'Добавить этот продукт в категорию?',
		'ImpossibleAddCat' => 'Невозможно добавить категорию',
		'ImpossibleAssociateCategory' => 'Невозможно добавить категорию к',
		'WasAddedSuccessfully' => '<b>%s</b> успешно добавлена.',
		'ObjectAlreadyLinkedToCategory' => 'Элемент уже связан с этой категорией.',
		'CategorySuccessfullyCreated' => 'Категория %s успешно добавлена.',
		'ProductIsInCategories' => 'Товар/услуга принадлежит к следующим категориям',
		'SupplierIsInCategories' => 'Контрагент принадлежит к следующим категориям поставщиков',
		'CompanyIsInCustomersCategories' => 'Этот контрагент принадлежит к следующим категориям покупателей/потенциальных клиентов',
		'CompanyIsInSuppliersCategories' => 'Этот контрагент принадлежит к следующим категориям поставщиков',
		'MemberIsInCategories' => 'Этот участник принадлежит к следующим категориям',
		'ProductHasNoCategory' => 'Этот товар/услуга не принадлежит к какой-либо категории',
		'SupplierHasNoCategory' => 'Этот поставщик не принадлежит к какой-либо категории',
		'CompanyHasNoCategory' => 'Эта компания не принадлежит к какой-либо категории',
		'MemberHasNoCategory' => 'Этот пользователь не находится в какой-либо категории',
		'ClassifyInCategory' => 'Добавить категорию',
		'NoneCategory' => 'Нет',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Категория к таким кодом уже существует',
		'ReturnInProduct' => 'Назад к карточке товара/услуги',
		'ReturnInSupplier' => 'Назад к карточке поставщика',
		'ReturnInCompany' => 'Назад к карточке покупателя/потенциального клиента',
		'ContentsVisibleByAll' => 'Содержимое будет доступно всем',
		'ContentsVisibleByAllShort' => 'Содержимое доступно всем',
		'ContentsNotVisibleByAllShort' => 'Содержание не доступно всем',
		'CategoriesTree' => 'Дерево категорий',
		'DeleteCategory' => 'Удалить категорию',
		'ConfirmDeleteCategory' => 'Вы уверены, что хотите удалить эту категорию?',
		'RemoveFromCategory' => 'Удалить связь с категорией',
		'RemoveFromCategoryConfirm' => 'Вы уверены, что хотите удалить связь операции и категории?',
		'NoCategoriesDefined' => 'Категории не определены',
		'SuppliersCategoryShort' => 'Категории Поставщиков',
		'CustomersCategoryShort' => 'Категории Покупателей',
		'ProductsCategoryShort' => 'Категории Товаров',
		'MembersCategoryShort' => 'Категории участников',
		'SuppliersCategoriesShort' => 'Категории Поставщиков',
		'CustomersCategoriesShort' => 'Категории Покупателей',
		'CustomersProspectsCategoriesShort' => 'Категории Покупателей/Потенц. клиентов',
		'ProductsCategoriesShort' => 'Категории Товаров',
		'MembersCategoriesShort' => 'Категории участников',
		'ThisCategoryHasNoProduct' => 'В этой категории нет товаров.',
		'ThisCategoryHasNoSupplier' => 'В этой категории нет поставщиков.',
		'ThisCategoryHasNoCustomer' => 'В этой категории нет покупателей.',
		'ThisCategoryHasNoMember' => 'Эта категория не содержит участников.',
		'AssignedToCustomer' => 'Установленное для покупателя',
		'AssignedToTheCustomer' => 'Установленное для покупателя',
		'InternalCategory' => 'Внутренняя категория',
		'CategoryContents' => 'Содержание категории',
		'CategId' => 'Код категории',
		'CatSupList' => 'Список категорий поставщиков',
		'CatCusList' => 'Список категорий покупателей / потенц. клиентов',
		'CatProdList' => 'Список категорий продукции',
		'CatMemberList' => 'Список категорий участников',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>