<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Коммерческие',
		'CommercialArea' => 'Коммерческие площади',
		'CommercialCard' => 'Коммерческая карту',
		'CustomerArea' => 'Клиенты область',
		'Customer' => 'Клиент',
		'Customers' => 'Заказчики',
		'Prospect' => 'Проспект',
		'Prospects' => 'Перспективы',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Удалить действия / задачи',
		'NewAction' => 'Новые меры / задачи',
		'AddAction' => 'Добавить действия / задачи',
		'AddAnAction' => 'Добавить меры / задачи',
		'AddActionRendezVous' => 'Добавить рандеву задачи',
		'Rendez-Vous' => 'Свидание',
		'ConfirmDeleteAction' => 'Вы уверены, что хотите удалить эту задачу?',
		'CardAction' => 'Действия карточки',
		'PercentDone' => 'Процент сделали',
		'ActionOnCompany' => 'Задача о компании',
		'ActionOnContact' => 'Задача о контакте',
		'TaskRDV' => 'Встречи',
		'TaskRDVWith' => 'Встреча с %s',
		'ShowTask' => 'Показать задачу',
		'ShowAction' => 'Показать действий',
		'ActionsReport' => 'Действия доклад',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Торговый представитель',
		'SalesRepresentatives' => 'Представители по продажам',
		'SalesRepresentativeFollowUp' => 'Представитель по продажам (последующих)',
		'SalesRepresentativeSignature' => 'Торговый представитель (подпись)',
		'CommercialInterlocutor' => 'Коммерческая собеседник',
		'ErrorWrongCode' => 'Неверный код',
		'NoSalesRepresentativeAffected' => 'Нет частности торговый представитель пострадавших',
		'ShowCustomer' => 'Показать заказчика',
		'ShowProspect' => 'Показать проспект',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Список перспективы',
		'ListOfCustomers' => 'Список клиентов',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'Последнее %s сделали задач',
		'LastRecordedTasks' => 'Последние зарегистрированные задач',
		'LastActionsToDo' => 'Последнее %s старейших действия не завершены',
		'DoneAndToDoActionsFor' => 'Составлено и делать задач %s',
		'DoneAndToDoActions' => 'Составлено и делать задач',
		'DoneActions' => 'Совершено действия',
		'DoneActionsFor' => 'Совершено меры для %s',
		'ToDoActions' => 'Неполные действия',
		'ToDoActionsFor' => 'Неполные действия %s',
		'SendPropalRef' => 'Отправить коммерческое предложение %s',
		'SendOrderRef' => 'Отправить заказ %s',
		'StatusNotApplicable' => 'Не применяется',
		'StatusActionToDo' => 'Чтобы сделать',
		'StatusActionDone' => 'Готово',
		'StatusActionInProcess' => 'В процессе',
		'MyActionsAsked' => 'Действия Я записала',
		'MyActionsToDo' => 'Действия я должен делать',
		'MyActionsDone' => 'Действия пострадавших мне',
		'TasksHistoryForThisContact' => 'Меры для этого контакта',
		'LastProspectDoNotContact' => 'Не контакт',
		'LastProspectNeverContacted' => 'Никогда не обращались',
		'LastProspectToContact' => 'Для контакта',
		'LastProspectContactInProcess' => 'Обратная связь в процессе',
		'LastProspectContactDone' => 'Контакт сделали',
		'DateActionPlanned' => 'Сроки действия, запланированные на',
		'DateActionDone' => 'Сроки действия сделали',
		'ActionAskedBy' => 'Действий, заданных',
		'ActionAffectedTo' => 'Действий для пострадавших',
		'ActionDoneBy' => 'Действий, проделанную',
		'ActionUserAsk' => 'Зарегистрировано',
		'ErrorStatusCantBeZeroIfStarted' => 'Если поле <b>\'Дата сделали\'</b> заполнен, действие начинается (или закончили), так что поле <b>"Статус"</b> не может быть 0%%.',
		'ActionAC_TEL' => 'Телефонный звонок',
		'ActionAC_FAX' => 'Отправить факс',
		'ActionAC_PROP' => 'Отправить предложение',
		'ActionAC_EMAIL' => 'Отправить электронное письмо',
		'ActionAC_RDV' => 'Встречи',
		'ActionAC_FAC' => 'Отправить платежную',
		'ActionAC_REL' => 'Отправить платежную (напоминание)',
		'ActionAC_CLO' => 'Закрыть',
		'ActionAC_EMAILING' => 'Отправить по электронной почте масса',
		'ActionAC_COM' => 'Отправить заказ по почте',
		'ActionAC_SHIP' => 'Отправить доставку по почте',
		'ActionAC_SUP_ORD' => 'Отправить поставщиком заказы по почте',
		'ActionAC_SUP_INV' => 'Отправить поставщиком счета по почте',
		'ActionAC_OTH' => 'Другой',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Проспект статус',
		'DraftPropals' => 'Проект коммерческих предложений',
		'SearchPropal' => 'Поиск коммерческих предложений'
);
?>