<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Коммерческие',
		'CommercialArea' => 'Коммерческие площади',
		'CommercialCard' => 'Коммерческая карту',
		'CustomerArea' => 'Клиенты область',
		'Customer' => 'Клиент',
		'Customers' => 'Заказчики',
		'Prospect' => 'Проспект',
		'Prospects' => 'Перспективы',
		'DeleteAction' => 'Удалить действия / задачи',
		'NewAction' => 'Новые меры / задачи',
		'AddAction' => 'Добавить действия / задачи',
		'AddAnAction' => 'Добавить меры / задачи',
		'ConfirmDeleteAction' => 'Вы уверены, что хотите удалить эту задачу?',
		'CardAction' => 'Действия карточки',
		'PercentDone' => 'Процент сделали',
		'ActionOnCompany' => 'Задача о компании',
		'ActionOnContact' => 'Задача о контакте',
		'TaskRDV' => 'Встречи',
		'TaskRDVWith' => 'Встреча с %s',
		'ShowTask' => 'Показать задачу',
		'ShowAction' => 'Показать действий',
		'ActionsReport' => 'Действия доклад',
		'SalesRepresentative' => 'Торговый представитель',
		'SalesRepresentatives' => 'Представители по продажам',
		'SalesRepresentativeFollowUp' => 'Представитель по продажам (последующих)',
		'SalesRepresentativeSignature' => 'Торговый представитель (подпись)',
		'CommercialInterlocutor' => 'Коммерческая собеседник',
		'ErrorWrongCode' => 'Неверный код',
		'NoSalesRepresentativeAffected' => 'Нет частности торговый представитель пострадавших',
		'ShowCustomer' => 'Показать заказчика',
		'ShowProspect' => 'Показать проспект',
		'ListOfProspects' => 'Список перспективы',
		'ListOfCustomers' => 'Список клиентов',
		'LastDoneTasks' => 'Последнее %s сделали задач',
		'LastRecordedTasks' => 'Последние зарегистрированные задач',
		'LastActionsToDo' => 'Последнее %s старейших действия не завершены',
		'DoneAndToDoActionsFor' => 'Составлено и делать задач %s',
		'DoneAndToDoActions' => 'Составлено и делать задач',
		'DoneActions' => 'Совершено действия',
		'DoneActionsFor' => 'Совершено меры для %s',
		'SendPropalRef' => 'Отправить коммерческое предложение %s',
		'SendOrderRef' => 'Отправить заказ %s',
		'NoRecordedProspects' => 'Нет перспективы зарегистрировано',
		'StatusActionToDo' => 'Чтобы сделать',
		'StatusActionDone' => 'Готово',
		'MyActionsAsked' => 'Действия Я записала',
		'MyActionsToDo' => 'Действия я должен делать',
		'MyActionsDone' => 'Действия пострадавших мне',
		'StatusActionInProcess' => 'В процессе',
		'TasksHistoryForThisContact' => 'Меры для этого контакта',
		'LastProspectDoNotContact' => 'Не контакт',
		'LastProspectNeverContacted' => 'Никогда не обращались',
		'LastProspectToContact' => 'Для контакта',
		'LastProspectContactInProcess' => 'Обратная связь в процессе',
		'LastProspectContactDone' => 'Контакт сделали',
		'DateActionPlanned' => 'Сроки действия, запланированные на',
		'DateActionDone' => 'Сроки действия сделали',
		'ActionAskedBy' => 'Действий, заданных',
		'ActionAffectedTo' => 'Действий для пострадавших',
		'ActionDoneBy' => 'Действий, проделанную',
		'ActionUserAsk' => 'Зарегистрировано',
		'ErrorStatusCantBeZeroIfStarted' => 'Если поле <b>\'Дата сделали\'</b> заполнен, действие начинается (или закончили), так что поле <b>"Статус"</b> не может быть 0%%.',
		'ActionAC_TEL' => 'Телефонный звонок',
		'ActionAC_FAX' => 'Отправить факс',
		'ActionAC_PROP' => 'Отправить предложение',
		'ActionAC_EMAIL' => 'Отправить электронное письмо',
		'ActionAC_RDV' => 'Встречи',
		'ActionAC_FAC' => 'Отправить платежную',
		'ActionAC_REL' => 'Отправить платежную (напоминание)',
		'ActionAC_CLO' => 'Закрыть',
		'ActionAC_EMAILING' => 'Отправить по электронной почте масса',
		'ActionAC_COM' => 'Отправить заказ по почте',
		'AddActionRendezVous' => 'Добавить рандеву задачи',
		'Rendez-Vous' => 'Свидание',
		'ToDoActions' => 'Неполные действия',
		'ToDoActionsFor' => 'Неполные действия %s',
		'ActionAC_SUP_ORD' => 'Отправить поставщиком заказы по почте',
		'ActionAC_SUP_INV' => 'Отправить поставщиком счета по почте',
		'StatusNotApplicable' => 'Не применяется',
		'ActionAC_SHIP' => 'Отправить доставку по почте',
		'ActionAC_OTH' => 'Другой',
		'StatusProsp' => 'Проспект статус',
		'DraftPropals' => 'Проект коммерческих предложений',
		'SearchPropal' => 'Поиск коммерческих предложений',
);
?>