<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$compta = array(
		'CHARSET' => 'UTF-8',
		'Accountancy' => 'Бухгалтерия',
		'AccountancyCard' => 'Бухгалтерия карту',
		'Treasury' => 'Казначейство',
		'MenuFinancial' => 'Финансовые',
		'OptionMode' => 'Вариант для бухгалтеров',
		'OptionModeVirtual' => 'Вариант Кредиты-Вычеты',
		'OptionModeVirtualDesc' => 'В этом контексте, оборот исчисляется более счетов (дата проверки). Когда эти счета-фактуры должны ли они были выплачены или нет, они перечислены в оборот продукции.',
		'FeatureIsSupportedInInOutModeOnly' => 'Функция доступна только в виде кредитов-ДОЛГОВ бухгалтерия (см. Бухгалтерия конфигурации модуля)',
		'Param' => 'Настройка',
		'AccountsGeneral' => 'Счета',
		'Account' => 'Учетная запись',
		'Accounts' => 'Счета',
		'BillsForSuppliers' => 'Законопроекты для поставщиков',
		'Income' => 'Поступления',
		'Outcome' => 'Итог',
		'ReportInOut' => 'Поступления / Результат',
		'PaymentsNotLinkedToInvoice' => 'Платежи, не связанные с какой-либо счет, это не связано с какой-либо третьей стороны',
		'PaymentsNotLinkedToUser' => 'Платежи, не связанные с какой-либо пользователь',
		'Profit' => 'Прибыль',
		'Balance' => 'Баланс',
		'Debit' => 'Дебет',
		'Credit' => 'Кредит',
		'Withdrawal' => 'Снятие',
		'Withdrawals' => 'Снятие',
		'AmountHTVATRealReceived' => 'HT собрали',
		'AmountHTVATRealPaid' => 'HT оплачивается',
		'VATToPay' => 'НДС к оплате',
		'VATReceived' => 'НДС получил',
		'VATToCollect' => 'НДС для сбора',
		'VATSummary' => 'НДС Резюме',
		'VATPaid' => 'НДС оплачивается',
		'VATCollected' => 'НДС собрали',
		'ToPay' => 'Для оплаты',
		'ToGet' => 'Чтобы вернуться',
		'TaxAndDividendsArea' => 'Налог, социальные отчисления и дивиденды области',
		'SocialContribution' => 'Социальный вклад',
		'SocialContributions' => 'Социальные взносы',
		'MenuTaxAndDividends' => 'Налоги и дивиденды',
		'MenuSocialContributions' => 'Социальные взносы',
		'MenuNewSocialContribution' => 'Новый вклад',
		'NewSocialContribution' => 'Новый социальный взнос',
		'ContributionsToPay' => 'Взносы платить',
		'AccountancyTreasuryArea' => 'Бухгалтерия / Казначейство области',
		'AccountancySetup' => 'Бухгалтерия установки',
		'NewPayment' => 'Новые оплаты',
		'Payments' => 'Платежи',
		'PaymentCustomerInvoice' => 'Заказчиком оплаты счетов-фактур',
		'PaymentSupplierInvoice' => 'Поставщик оплате счета-фактуры',
		'PaymentSocialContribution' => 'Социальный вклад оплаты',
		'PaymentVat' => 'НДС платеж',
		'ListPayment' => 'Список платежей',
		'ListOfPayments' => 'Список платежей',
		'ListOfCustomerPayments' => 'Список клиентов платежи',
		'ListOfSupplierPayments' => 'Список поставщиков платежей',
		'DatePayment' => 'Дата оплаты',
		'NewVATPayment' => 'Новые оплаты НДС',
		'VATPayment' => 'Оплата НДС',
		'VATPayments' => 'НДС Платежи',
		'TotalToPay' => 'Всего к оплате',
		'TotalVATReceived' => 'Общая сумма НДС, полученные',
		'CustomerAccountancyCode' => 'Заказчиком бухгалтерской код',
		'AlreadyPaid' => 'Уже оплачивается',
		'AccountNumberShort' => 'Номер счета',
		'AccountNumber' => 'Номер счета',
		'NewAccount' => 'Новый счет',
		'SalesTurnover' => 'Оборот по продажам',
		'ByThirdParties' => 'Бу-третьих сторон',
		'ByUserAuthorOfInvoice' => 'На счету автора',
		'AccountancyExport' => 'Бухгалтерия экспорт',
		'ErrorWrongAccountancyCodeForCompany' => 'Плохо заказчику бухгалтерские код %s',
		'SuppliersProductsSellSalesTurnover' => 'Генерируемый оборот по продажам поставщиков продукции.',
		'CheckReceipt' => 'Проверьте депозит',
		'CheckReceiptShort' => 'Проверьте депозит',
		'NewCheckReceipt' => 'Новые скидки',
		'NewCheckDeposit' => 'Новая проверка депозит',
		'NewCheckDepositOn' => 'Новый депозит проверить на счету: %s',
		'NoWaitingChecks' => 'Не дожидаясь проверок на хранение.',
		'DateChequeReceived' => 'Чек при ввода даты',
		'NbOfCheques' => 'Nb чеков',
		'PaySocialContribution' => 'Оплатить социального взноса',
		'ConfirmPaySocialContribution' => 'Вы уверены, что хотите классифицировать этот социальный вклад, как оплачивается?',
		'DeleteSocialContribution' => 'Удалить социального взноса',
		'ConfirmDeleteSocialContribution' => 'Вы уверены, что хотите удалить этот социальный взнос?',
		'ExportDataset_tax_1' => 'Социальные взносы и платежи',
		'AnnualSummaryDueDebtMode' => 'Билан DES recettes и dpenses, rsum annuel, в <b>режиме %sCrances-Dettes %s</b> DIT <b>comptabilit d\'участия.</b>',
		'AnnualSummaryInputOutputMode' => 'Билан DES recettes и dpenses, rsum annuel, в <b>режиме %sRecettes-Dpenses %s</b> DIT <b>comptabilit де ящик.</b>',
		'AnnualByCompaniesDueDebtMode' => 'Билан DES recettes и dpenses, dtail пар ярусов, в <b>режиме %sCrances-Dettes %s</b> DIT <b>comptabilit d\'участия.</b>',
		'AnnualByCompaniesInputOutputMode' => 'Билан DES recettes и dpenses, dtail пар ярусов, в <b>режиме %sRecettes-Dpenses %s</b> DIT <b>comptabilit де ящик.</b>',
		'SeeReportInInputOutputMode' => 'См. LE <b>отношения %sRecettes-Dpenses %s</b> DIT <b>comptabilit де ящик</b> POUR UN CALCUL SUR LES paiements effectivement raliss',
		'SeeReportInDueDebtMode' => 'См. LE <b>отношения %sCrances-Dettes %s</b> DIT <b>comptabilit d\'участие</b> POUR UN CALCUL SUR LES factures Мизеса',
		'RulesResultDue' => '- Суммы указаны с НДС <br> - Она включает в себя неоплаченные счета, расходы и НДС ли они выплачиваются или нет. <br> - Он основан на одобрении даты счета-фактуры и НДС, и на сегодняшний день из-за расходов.',
		'RulesResultInOut' => '- Суммы указаны с НДС <br> - Она включает в себя реальные выплаты на счета, расходы и НДС. <br> - Он основан на оплату даты счета-фактуры, расходы ANF НДС. <br>',
		'RulesCADue' => '- Она включает в себя клиентов из-за счетов ли они выплачиваются или нет. <br> - Он основан на дату одобрения этих счетов-фактур. <br>',
		'RulesCAIn' => '- Она включает в себя все эффективные платежи в счетах-фактурах, полученных от клиентов. <br> - Он основан на день оплаты этих счетов-фактур <br>',
		'VATReportByCustomersInInputOutputMode' => 'Rapport пар клиента DES TVA collectes и платит (TVA сюр encaissement)',
		'VATReportByCustomersInDueDebtMode' => 'Rapport пар клиента DES TVA collectes и платит (TVA сюр dbit)',
		'VATReportByQuartersInInputOutputMode' => 'Rapport пар trimestre DES TVA collectes и платит (TVA сюр encaissement)',
		'VATReportByQuartersInDueDebtMode' => 'Rapport пар trimestre DES TVA collectes и платит (TVA сюр dbit)',
		'SeeVATReportInInputOutputMode' => 'См. LE <b>отношения %sTVA encaissement %s</b> для режима де CALCUL стандарт',
		'SeeVATReportInDueDebtMode' => 'См. LE <b>отношения %sTVA сюр dbit %s</b> для режима де CALCUL AVEC вариант SUR LES dbits',
		'RulesVATIn' => '- POUR LES услуг, Le отношения inclut Ле дез TVA rglements effectivement Реус или MIS EN SE basant сюр-ла-дю rglement даты. <br> - POUR LES имущества matriels, IL inclut Ле дез TVA factures EN SE basant сюр-де-ла даты подтверждения де-ла-Фактура.',
		'RulesVATDue' => '- POUR LES услуг, Le отношения inclut Ле дез TVA factures взносы, или, не payes EN SE basant сюр-де-ла даты подтверждения DE CES factures. <br> - POUR LES имущества matriels, IL inclut Ле дез TVA factures EN SE basant сюр-де-ла даты подтверждения де-ла-Фактура.',
		'PercentOfInvoice' => '%%/счет-фактура',
		'Dispatch' => 'Экспедирование',
		'Dispatched' => 'Отправлено',
		'ToDispatch' => 'Направить',
		'ReportTurnover' => 'Оборот',
		'NotUsedForGoods' => 'Не используется на товары',
		'OptionModeTrue' => 'Вариант "затраты-выпуск"',
		'OptionModeTrueDesc' => 'В этом контексте, оборот исчисляется за платежи (дата выплаты). \ nThe действительности цифры обеспечивается только в том случае, если бухгалтерия является тщательно путем ввода / вывода по счетам с помощью счетов-фактур.',
		'ShowVatPayment' => 'Показать оплате НДС',
		'SupplierAccountancyCode' => 'Поставщик бухгалтерских код',
		'TaxModuleSetupToModifyRules' => 'Перейти на <a href="%s">модуль установки</a> для изменения правил расчета',
		'VATReportBuildWithOptionDefinedInModule' => 'Суммы, показанные здесь, рассчитанного с использованием установленных правил налоговыми модуля установки.',
		'SocialContributionsPayments' => 'Социальные отчисления платежей',
		'OptionVatInfoModuleComptabilite' => 'Примечание: Для материальных ценностей, она должна использовать даты доставки будет более справедливым.',
		'ThirdPartyMustBeEditAsCustomer' => 'Третий участник должен быть определен в качестве клиента',
		'RemainingAmountPayment' => 'Сумма оплаты Осталось:',
		'AmountToBeCharged' => 'Общая сумма для оплаты:',
		'ProposalStats' => 'Статистика по предложениям',
		'OrderStats' => 'Статистика по заказам',
		'InvoiceStats' => 'Статистика по векселям',
		'SellsJournal' => 'Продажи журнала',
		'PurchasesJournal' => 'Покупки Журнал',
		'DescSellsJournal' => 'Продажи журнала',
		'DescPurchasesJournal' => 'Покупки Журнал',
		'InvoiceRef' => 'Счет реф.',
		'CodeNotDef' => 'Не определено',
		'AddRemind' => 'Отправка доступная сумма',
		'RemainToDivide' => 'Оставайтесь на рассылки:',
		'WarningDepositsNotIncluded' => 'Депозиты счетов не включены в эту версию с этим бухгалтерский учет модуля.',
		'LT2SummaryES' => 'IRPF баланс',
		'LT2PaidES' => 'Платные IRPF',
		'LT2CustomerES' => 'IRPF продаж',
		'LT2SupplierES' => 'IRPF покупки',
		'newLT2PaymentES' => 'Новые IRPF оплаты',
		'LT2PaymentES' => 'IRPF оплаты',
		'LT2PaymentsES' => 'IRPF платежей',
		'DepositsAreNotIncluded' => '- Депозитные счета-фактуры и не включен',
		'DepositsAreIncluded' => '- Депозитные счета включены',
		'LT2ReportByCustomersInInputOutputModeES' => 'Доклад третьей стороной IRPF',
		'RulesVATInServices' => '- Для услуг, отчет включает в себя НДС, правила, фактически полученных и выданных на основании даты платежа. <br> - Для материальных ценностей, она включает в себя счета-фактуры на основе даты выставления счета.',
		'RulesVATInProducts' => '- Для материальных ценностей, она включает в себя счета-фактуры на основе даты выставления счета.',
		'RulesVATDueServices' => '- Для услуг, отчет включает в себя счета-фактуры за счет, оплачиваемый или нет, исходя из даты выставления счета.',
		'RulesVATDueProducts' => '- Для материальных ценностей, она включает в себя НДС, счета-фактуры, на основе даты выставления счета.',
);
?>