<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$contracts = array(
		'CHARSET' => 'UTF-8',
		'ContractsArea' => 'Контракты области',
		'ListOfContracts' => 'Список договоров',
		'LastContracts' => 'Последнее% с измененными контрактами',
		'AllContracts' => 'Все контракты',
		'ContractCard' => 'Контракт карту',
		'ContractStatus' => 'Контракт статус',
		'ContractStatusNotRunning' => 'Не работает',
		'ContractStatusRunning' => 'Запуск',
		'ContractStatusDraft' => 'Черновик',
		'ContractStatusValidated' => 'Подтвержденные',
		'ContractStatusClosed' => 'Закрытые',
		'ServiceStatusInitial' => 'Не работает',
		'ServiceStatusRunning' => 'Запуск',
		'ServiceStatusLate' => 'Запуск, истек',
		'ServiceStatusClosed' => 'Закрытые',
		'ServicesLegend' => 'Услуги легенда',
		'Contracts' => 'Договоры',
		'Contract' => 'Контракт',
		'NoContracts' => 'Нет контрактов',
		'MenuServices' => 'Услуги',
		'MenuInactiveServices' => 'Услуга не активна',
		'MenuRunningServices' => 'Запуск служб',
		'MenuExpiredServices' => 'Истекшим сроком службы',
		'MenuClosedServices' => 'Закрытые услуги',
		'NewContract' => 'Новый контракт',
		'AddContract' => 'Добавить контракт',
		'SearchAContract' => 'Поиск контракта',
		'DeleteAContract' => 'Удалить договор',
		'CloseAContract' => 'Закрыть контракта',
		'ConfirmDeleteAContract' => 'Вы уверены, что хотите удалить этот контракт, и на все свои услуги?',
		'ConfirmValidateContract' => 'Вы уверены, что хотите проверить этот договор?',
		'ConfirmCloseContract' => 'Это позволит закрыть все услуги (активный или нет). Вы уверены, что хотите закрыть этот договор?',
		'ConfirmCloseService' => 'Вы действительно хотите закрыть эту услугу с <b>даты %s?</b>',
		'ValidateAContract' => 'Проверить контракт',
		'ActivateService' => 'Активировать услугу',
		'ConfirmActivateService' => 'Вы уверены, что хотите, чтобы активировать данную услугу с <b>даты %s?</b>',
		'DateContract' => 'Контракт дата',
		'DateServiceActivate' => 'Дата активации услуги',
		'DateServiceUnactivate' => 'Сроки службы unactivation',
		'DateServiceStart' => 'Дата начала службы',
		'DateServiceEnd' => 'Дата окончания службы',
		'ShowContract' => 'Показать контракта',
		'ListOfServices' => 'Перечень услуг',
		'ListOfRunningContractsLines' => 'Список запуска контракта линий',
		'ListOfRunningServices' => 'Список запущенных служб',
		'NotActivatedServices' => 'Не активируется услуг (в том числе утверждены контракты)',
		'BoardNotActivatedServices' => 'Услуги для активации среди утверждены контракты',
		'LastContracts' => 'Последнее% контрактов',
		'LastActivatedServices' => 'Последнее %s активированных услуг',
		'LastModifiedServices' => 'Последнее% с измененными услуги',
		'EditServiceLine' => 'Изменить направление',
		'ContractStartDate' => 'Начальная дата',
		'ContractEndDate' => 'Конечная дата',
		'DateStartPlanned' => 'Планируемая дата начала',
		'DateStartPlannedShort' => 'Планируемая дата начала',
		'DateEndPlanned' => 'Планируемая дата окончания',
		'DateEndPlannedShort' => 'Планируемая дата окончания',
		'DateStartReal' => 'Реальная дата начала',
		'DateStartRealShort' => 'Реальная дата начала',
		'DateEndReal' => 'Реальная дата окончания',
		'DateEndRealShort' => 'Реальная дата окончания',
		'NbOfServices' => 'Nb услуг',
		'CloseService' => 'Закрыть службы',
		'ServicesNomberShort' => '%s служба (ы)',
		'RunningServices' => 'Запуск служб',
		'BoardRunningServices' => 'Истекшие Запуск услуги',
		'ServiceStatus' => 'Положение о службе',
		'DraftContracts' => 'Проекты контрактов',
		'CloseRefusedBecauseOneServiceActive' => 'Контракт не может быть закрыто, пока, по крайней мере один открытый службе по нему',
		'CloseAllContracts' => 'Закрыть все контракты',
		'MoveToAnotherContract' => 'Переместите службу в другой договор.',
		'ConfirmMoveToAnotherContract' => 'Я выбранного новая цель договора и подтвердить, я хочу перейти эту услугу в этом договоре.',
		'ConfirmMoveToAnotherContractQuestion' => 'Выборы, в которых существующего контракта (от же третья сторона), вы хотите переместить эту услугу?',
		'TypeContact_contrat_internal_SALESREPSIGN' => 'Торговый представитель подписания контракта',
		'TypeContact_contrat_internal_SALESREPFOLL' => 'Торговый представитель последующего договора',
		'TypeContact_contrat_external_BILLING' => 'Платежная заказчика контакт',
		'TypeContact_contrat_external_CUSTOMER' => 'После деятельность заказчика контакт',
		'TypeContact_contrat_external_SALESREPSIGN' => 'Подписание контракта заказчик контакт',
		'ServiceStatusNotLate' => 'Запуск, не истек',
		'ServiceStatusNotLateShort' => 'Не истек',
		'ServiceStatusLateShort' => 'Истек',
		'ListOfInactiveServices' => 'Перечень услуг не активен',
		'ListOfExpiredServices' => 'Список с истекшим сроком службы',
		'ListOfClosedServices' => 'Список закрытых услуги',
		'DeleteContractLine' => 'Удалить контракт линия',
		'ConfirmDeleteContractLine' => 'Вы уверены, что хотите удалить этот контракт линию?',
		'PaymentRenewContractId' => 'Продлить контракт линия (номер %s)',
		'ExpiredSince' => 'Срок действия',
		'RelatedContracts' => 'Связанные контрактов',
		'Error_CONTRACT_ADDON_NotDefined' => 'Постоянное CONTRACT_ADDON не определена',
		'NoExpiredServices' => 'Не истек активных услуг',
);
?>