<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$mails = array(
		'CHARSET' => 'UTF-8',
		'Mailing' => 'Отправка',
		'EMailing' => 'Отправка',
		'Mailings' => 'EMailings',
		'EMailings' => 'EMailings',
		'AllEMailings' => 'Все eMailings',
		'MailCard' => 'Отправка карточки',
		'MailTargets' => 'Цели',
		'MailRecipients' => 'Получатели',
		'MailRecipient' => 'Получатель',
		'MailTitle' => 'Название',
		'MailFrom' => 'Отправитель',
		'MailErrorsTo' => 'Ошибки в',
		'MailReply' => 'Ответить',
		'MailTo' => 'Получатель (и)',
		'MailCC' => 'Копия',
		'MailCCC' => 'Сохраненная копия',
		'MailTopic' => 'EMail темы',
		'MailText' => 'Сообщение',
		'MailFile' => 'Присоединенные файлы',
		'MailMessage' => 'EMail тела',
		'ShowEMailing' => 'Показать адреса',
		'ListOfEMailings' => 'Список emailings',
		'NewMailing' => 'Новый адрес',
		'EditMailing' => 'Изменить адрес',
		'ResetMailing' => 'Resend электронной почте',
		'DeleteMailing' => 'Удалить электронной почте',
		'DeleteAMailing' => 'Удалить электронной почте',
		'PreviewMailing' => 'Предварительный электронной почте',
		'PrepareMailing' => 'Подготовка по электронной почте',
		'CreateMailing' => 'Создание электронной почте',
		'MailingDesc' => 'Эта страница позволяет отправить emailings на группу людей.',
		'MailingResult' => 'Отправка писем результат',
		'TestMailing' => 'Тест по электронной почте',
		'ValidMailing' => 'Действующий по электронной почте',
		'ApproveMailing' => 'Утвердить по электронной почте',
		'MailingStatusDraft' => 'Черновик',
		'MailingStatusValidated' => 'Подтвержденные',
		'MailingStatusApproved' => 'Утверждено',
		'MailingStatusSent' => 'Отправленный',
		'MailingStatusSentPartialy' => 'Отправлено частично',
		'MailingStatusSentCompletely' => 'Отправлено полностью',
		'MailingStatusError' => 'Ошибка',
		'MailingStatusNotSent' => 'Не отправлено',
		'MailSuccessfulySent' => 'Электронная почта успешно отправлено (% от S в %s)',
		'MailingSuccessfullyValidated' => 'EMailing successfully validated',
		'MailUnsubcribe' => 'Unsubscribe',
		'Unsuscribe' => 'Unsubscribe',
		'MailingStatusNotContact' => 'Don\'t contact anymore',
		'ErrorMailRecipientIsEmpty' => 'Email получателя пуста',
		'WarningNoEMailsAdded' => 'Нет новых сообщений, чтобы добавить в список получателей.',
		'ConfirmValidMailing' => 'Вы уверены, что хотите проверить этот адрес?',
		'ConfirmResetMailing' => 'Предупреждение, по электронной почте <b>reinitializing %s,</b> вы позволите сделать массу отправки этого письма еще раз. Вы уверены, что это то, что вы хотите сделать?',
		'ConfirmDeleteMailing' => 'Вы уверены, что хотите удалить этот emailling?',
		'NbOfRecipients' => 'Число получателей',
		'NbOfUniqueEMails' => 'Nb уникальных писем',
		'NbOfEMails' => 'Nb писем',
		'TotalNbOfDistinctRecipients' => 'Число различных адресатов',
		'NoTargetYet' => 'Не определено еще получателей (Перейдите на вкладку \'Получатели\')',
		'AddRecipients' => 'Добавить получателей',
		'RemoveRecipient' => 'Удалить получателем',
		'CommonSubstitutions' => 'Общие подстановками',
		'YouCanAddYourOwnPredefindedListHere' => 'Чтобы создать свой электронный селектор модуля, см. htdocs / входит / модули / рассылки / README.',
		'EMailTestSubstitutionReplacedByGenericValues' => 'При тестовом режиме, замен переменных заменяются на общих ценностях',
		'MailingAddFile' => 'Приложите этот файл',
		'NoAttachedFiles' => 'Нет прикрепленных файлов',
		'BadEMail' => 'Плохо стоимости EMail',
		'CloneEMailing' => 'Клон Отправка',
		'ConfirmCloneEMailing' => 'Вы уверены, что хотите клон этой электронной почте?',
		'CloneContent' => 'Клон сообщение',
		'CloneReceivers' => 'Cloner получателей',
		'DateLastSend' => 'Дата последней отправки',
		'DateSending' => 'Дата отправки',
		'SentTo' => 'Направлено в <b>%s</b>',
		'MailingStatusRead' => 'Читать',
		'CheckRead' => 'Read Receipt',
		'YourMailUnsubcribeOK' => 'The email <b>%s</b>  is correctly unsubcribe from mailing list',
		'MailtoEMail' => 'Hyper link to email',
		'ActivateCheckRead' => 'Allow to use the Read receipt tracker and the unsubcribe link',
		'ActivateCheckReadKey' => 'Key use to encrypt URL use for Read Receipt and unsubcribe function',
		// Libelle des modules de liste de destinataires mailing
		'MailingModuleDescContactCompanies' => 'Контакты всех третьих лиц (клиентов, проспект, поставщик, ...)',
		'MailingModuleDescSpeedealingUsers' => 'Speedealing users',
		'MailingModuleDescFundationMembers' => 'Члены фонда с письма',
		'MailingModuleDescEmailsFromFile' => 'Письма из текстового файла (электронная почта; имя фамилия)',
		'MailingModuleDescEmailsFromUser' => 'EMails from user input (email;lastname;firstname;other)',
		'MailingModuleDescContactsCategories' => 'Контакты всех третьих лиц (по категориям)',
		'MailingModuleDescSpeedealingContractsLinesExpired' => 'Third parties with expired contract\'s lines',
		'MailingModuleDescContactsByCompanyCategory' => 'Контакты третьих лиц (по третьей категории сторон)',
		'MailingModuleDescMembersCategories' => 'Фонд членов (по категориям)',
		'MailingModuleDescContactsByFunction' => 'Контакты третьих лиц (по должности / функции)',
		'LineInFile' => 'Линия %s в файл',
		'RecipientSelectionModules' => 'Определяется запросы для получателей выбор',
		'MailSelectedRecipients' => 'Отобранные получатели',
		'MailingArea' => 'EMailings области',
		'LastMailings' => 'Последнее %s emailings',
		'TargetsStatistics' => 'Цели статистика',
		'NbOfCompaniesContacts' => 'Уникальный контактов компаний',
		'MailNoChangePossible' => 'Получатели для подтверждена электронной почте не может быть изменен',
		'SearchAMailing' => 'Поиск рассылку',
		'SendMailing' => 'Отправить по электронной почте',
		'SendMail' => 'Отправить письмо',
		'SentBy' => 'Прислал',
		'MailingNeedCommand' => 'Для ценных бумаг причине, отправка электронной почты могут быть выполнены только из командной строки. Попросите вашего администратора для запуска следующей команды для отправки по электронной почте всем адресатам:',
		'MailingNeedCommand2' => 'Однако вы можете отправить их в Интернете, добавив параметр MAILING_LIMIT_SENDBYWEB с величиной максимальное количество писем вы хотите отправить на сессии.',
		'ConfirmSendingEmailing' => 'Вы уверены, что хотите отправить почтовую? <br> В строке отправку emailings ограничены для обеспечения безопасности <b>причина %s</b> получателей, отправив сессии.',
		'LimitSendingEmailing' => 'В строке отправки emailings ограничены для обеспечения безопасности и тайм-аут причин <b>%s</b> получателей, отправив сессии.',
		'TargetsReset' => 'Очистить список',
		'ToClearAllRecipientsClickHere' => 'Чтобы очистить получателей список для этого адреса, нажмите кнопку',
		'ToAddRecipientsChooseHere' => 'Чтобы добавить адресатов, выберите в этих списках',
		'NbOfEMailingsReceived' => 'Массовые emailings получил',
		'IdRecord' => 'Код записи',
		'DeliveryReceipt' => 'Доставка квитанции',
		'YouCanUseCommaSeparatorForSeveralRecipients' => 'Вы можете использовать сепаратор для <b>запятую</b> указать несколько получателей.',
		'TagCheckMail' => 'Track mail opening',
		'TagUnsubscribe' => 'Unsubscribe link',
		'TagSignature' => 'Signature sending user',
		'TagMailtoEmail' => 'Recipient EMail',
		// Module Notifications
		'Notifications' => 'Уведомления',
		'NoNotificationsWillBeSent' => 'Нет электронной почте уведомления, планируется к этому мероприятию и компании',
		'ANotificationsWillBeSent' => '1 уведомление будет отправлено по электронной почте',
		'SomeNotificationsWillBeSent' => '%s уведомления будут отправлены по электронной почте',
		'AddNewNotification' => 'Включить новое уведомление запросу',
		'ListOfActiveNotifications' => 'Список всех активных уведомлений запросов',
		'ListOfNotificationsDone' => 'Список всех уведомлений по электронной почте отправлено'
);
?>