<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$propal = array(
		'CHARSET' => 'UTF-8',
		'Proposals' => 'Коммерческие предложения',
		'Proposal' => 'Коммерческое предложение',
		'ProposalShort' => 'Предложение',
		'ProposalsDraft' => 'Проект коммерческого предложения',
		'ProposalDraft' => 'Проект коммерческого предложения',
		'ProposalsOpened' => 'Открытие коммерческих предложений',
		'Prop' => 'Коммерческие предложения',
		'CommercialProposal' => 'Коммерческое предложение',
		'CommercialProposals' => 'Коммерческие предложения',
		'ProposalCard' => 'Предложение карты',
		'NewProp' => 'Новое коммерческое предложение',
		'NewProposal' => 'Новое коммерческое предложение',
		'NewPropal' => 'Новое предложение',
		'Prospect' => 'Проспект',
		'ProspectList' => 'Проспект список',
		'DeleteProp' => 'Удалить коммерческого предложения',
		'ValidateProp' => 'Проверка коммерческого предложения',
		'AddProp' => 'Добавить предложение',
		'ConfirmDeleteProp' => 'Вы уверены, что хотите удалить это коммерческое предложение?',
		'ConfirmValidateProp' => 'Вы уверены, что хотите проверить эту коммерческое предложение?',
		'LastPropals' => 'Последнее% с предложениями',
		'LastClosedProposals' => 'Последнее% с закрытых предложений',
		'LastModifiedProposals' => 'Последнее% с измененными предложения',
		'AllPropals' => 'Все предложения',
		'LastProposals' => 'Последние предложения',
		'SearchAProposal' => 'Поиск предложений',
		'ProposalsStatistics' => 'Коммерческие предложения Статистика',
		'NumberOfProposalsByMonth' => 'Количество в месяц',
		'AmountOfProposalsByMonthHT' => 'Сумма в месяц (за вычетом налогов)',
		'NbOfProposals' => 'Количество коммерческих предложений',
		'ShowPropal' => 'Показать предложение',
		'PropalsDraft' => 'Черновики',
		'PropalsOpened' => 'Открыты',
		'PropalsNotBilled' => 'Закрытые не будет взиматься',
		'PropalStatusDraft' => 'Проект (должно быть подтверждено)',
		'PropalStatusValidated' => 'Удостоверенная (предложение открыто)',
		'PropalStatusOpened' => 'Удостоверенная (предложение открыто)',
		'PropalStatusClosed' => 'Закрытые',
		'PropalStatusSigned' => 'Подпись (в законопроекте)',
		'PropalStatusNotSigned' => 'Не подписал (закрытые)',
		'PropalStatusBilled' => 'Billed',
		'PropalStatusDraftShort' => 'Черновик',
		'PropalStatusValidatedShort' => 'Подтвержденные',
		'PropalStatusOpenedShort' => 'Открыты',
		'PropalStatusClosedShort' => 'Закрытые',
		'PropalStatusSignedShort' => 'Подпись',
		'PropalStatusNotSignedShort' => 'Не подписано',
		'PropalStatusBilledShort' => 'Billed',
		'PropalsToClose' => 'Коммерческие предложения закрыть',
		'PropalsToBill' => 'Подпись коммерческие предложения по законопроекту',
		'ListOfProposals' => 'Список коммерческих предложений',
		'ActionsOnPropal' => 'Меры по предложению',
		'NoOpenedPropals' => 'Нет открыли коммерческие предложения',
		'NoOtherOpenedPropals' => 'Никакие другие открыли коммерческие предложения',
		'RefProposal' => 'Коммерческие предложения исх',
		'SendPropalByMail' => 'Отправить коммерческое предложение по почте',
		'FileNotUploaded' => 'Файл не был загружен',
		'FileUploaded' => 'Этот файл был успешно загружен',
		'AssociatedDocuments' => 'Документы, связанные с предложением:',
		'ErrorCantOpenDir' => 'Не удается открыть каталог',
		'DatePropal' => 'Дата предложения',
		'DateEndPropal' => 'Дата окончания действия',
		'DateEndPropalShort' => 'Дата окончания',
		'ValidityDuration' => 'Срок действия',
		'CloseAs' => 'Закрыть со статусом',
		'ClassifyBilled' => 'Классифицировать счета',
		'BuildBill' => 'Создание счета-фактуры',
		'ErrorPropalNotFound' => 'Пропал% не найдены',
		'Estimate' => 'Оценка:',
		'EstimateShort' => 'Расчетный показатель',
		'OtherPropals' => 'Другие предложения',
		'CopyPropalFrom' => 'Создание коммерческого предложения, копируя существующие предложения',
		'CreateEmptyPropal' => 'Создайте пустую коммерческих предложений vierge либо из списка товаров / услуг',
		'DefaultProposalDurationValidity' => 'По умолчанию коммерческого предложения действительности продолжительность (в днях)',
		'UseCustomerContactAsPropalRecipientIfExist' => 'Используйте адрес клиента, если определено, вместо третьей стороной решения, как предложение, адрес получателя',
		'ClonePropal' => 'Клон коммерческого предложения',
		'ConfirmClonePropal' => 'Вы уверены, что хотите этого клона коммерческие <b>предложения %s?</b>',
		'ConfirmReOpenProp' => 'Вы уверены, что хотите открыть обратно коммерческих <b>%s</b> предложение?',
		'ProposalsAndProposalsLines' => 'Коммерческое предложение и линий',
		'ProposalLine' => 'Предложение линия',
		'AvailabilityPeriod' => 'Наличие задержки',
		'SetAvailability' => 'Задержка устанавливается доступность',
		'AfterOrder' => 'после заказа',
		////////// Availability //////////
		'AvailabilityTypeAV_NOW' => 'Немедленный',
		'AvailabilityTypeAV_1W' => '1 неделя',
		'AvailabilityTypeAV_2W' => '2-х недель',
		'AvailabilityTypeAV_3W' => '3 недели',
		'AvailabilityTypeAV_1M' => '1 месяц',
		////////// Types de contacts //////////
		'TypeContact_propal_internal_SALESREPFOLL' => 'Представитель следующие меры предложение',
		'TypeContact_propal_external_BILLING' => 'свяжитесь со счета',
		'TypeContact_propal_external_CUSTOMER' => 'Абонентский отдел следующие меры предложение',
		// Document models
		'DocModelAzurDescription' => 'Полный текст предложения модели (logo. ..)',
		'DocModelJauneDescription' => 'Желтый предложение модель'
);
?>