<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$withdrawals = array(
		'CHARSET' => 'UTF-8',
		'StandingOrdersArea' => 'Постоянные заказы области',
		'CustomersStandingOrdersArea' => 'Клиенты Регламента области',
		'StandingOrders' => 'Постоянные заказы',
		'StandingOrder' => 'Постоянные заказы',
		'NewStandingOrder' => 'Новый постоянный порядок',
		'StandingOrderToProcess' => 'Для обработки',
		'StandingOrderProcessed' => 'Обработано',
		'Withdrawals' => 'Снятие',
		'Withdrawal' => 'Снятие',
		'WithdrawalsReceipts' => 'Снятие квитанции',
		'WithdrawalReceipt' => 'Снятие получения',
		'WithdrawalReceiptShort' => 'Квитанция',
		'LastWithdrawalReceipts' => 'Последнее% с выводом квитанции',
		'WithdrawedBills' => 'Withdrawed счетов-фактур',
		'WithdrawalsLines' => 'Снятие линии',
		'RequestStandingOrderToTreat' => 'Запрос Регламента для лечения',
		'RequestStandingOrderTreated' => 'Запрос Регламента лечение',
		'CustomersStandingOrders' => 'Клиент Регламент',
		'CustomerStandingOrder' => 'Для постоянных клиентов',
		'NbOfInvoiceToWithdraw' => 'Nb счета с просьбой отозвать',
		'NbOfInvoiceToWithdrawWithInfo' => 'Кол-во фактуру с отозвать запрос для клиентов, определив информацию о банковском счете',
		'InvoiceWaitingWithdraw' => 'Счет ждет снимать',
		'AmountToWithdraw' => 'Сумма снять',
		'WithdrawsRefused' => 'Отзывает отказала',
		'NoInvoiceToWithdraw' => 'Нет счета клиента в оплате режиме "отозвать" ждет. Переход на "Вывод \'вкладки на счету карточки сделать запрос.',
		'ResponsibleUser' => 'Ответственный пользователь',
		'WithdrawalsSetup' => 'Выход установки',
		'WithdrawStatistics' => 'Выходит статистика',
		'WithdrawRejectStatistics' => 'Снять отвергает Статистика',
		'LastWithdrawalReceipt' => 'Последнее %s снятия квитанции',
		'MakeWithdrawRequest' => 'Сделать отозвать запрос',
		'ThirdPartyBankCode' => 'Третьей стороной банковский код',
		'ThirdPartyDeskCode' => 'Третий участник стол код',
		'NoInvoiceCouldBeWithdrawed' => 'Нет счета withdrawed с успехом. Убедитесь в том, что счета-фактуры на компании с действительным запрета.',
		'ClassCredited' => 'Классифицировать зачисленных',
		'ClassCreditedConfirm' => 'Вы уверены, что хотите классифицировать этот вывод получения как кредитуются на ваш счет в банке?',
		'TransData' => 'Дата передачи',
		'TransMetod' => 'Метод передачи',
		'Send' => 'Послать',
		'Lines' => 'Линии',
		'StandingOrderReject' => 'Выпуск отклонить',
		'InvoiceRefused' => 'Зарядка отказа клиента',
		'WithdrawalRefused' => 'Выплаты Refuseds',
		'WithdrawalRefusedConfirm' => 'Вы уверены, что вы хотите ввести снятия отказа общества',
		'RefusedData' => 'Дата отказа',
		'RefusedReason' => 'Причина для отказа',
		'RefusedInvoicing' => 'Счета отказ',
		'NoInvoiceRefused' => 'Не заряжайте отказ',
		'InvoiceRefused' => 'Зарядка отказа клиента',
		'Status' => 'Статус',
		'StatusUnknown' => 'Неизвестный',
		'StatusWaiting' => 'Ожидание',
		'StatusTrans' => 'Передающиеся',
		'StatusCredited' => 'Кредитоваться',
		'StatusRefused' => 'Отказавшийся',
		'StatusMotif0' => 'Не указано',
		'StatusMotif1' => 'Предоставление insuffisante',
		'StatusMotif2' => 'Тираж conteste',
		'StatusMotif3' => 'Нет Выплаты порядка',
		'StatusMotif4' => 'Клиент Заказать',
		'StatusMotif5' => 'RIB inexploitable',
		'StatusMotif6' => 'Счет без остатка',
		'StatusMotif7' => 'Судебное решение',
		'StatusMotif8' => 'Другая причина',
		'CreateAll' => 'Снять все',
		'CreateGuichet' => 'Только служба',
		'CreateBanque' => 'Только банк',
		'OrderWaiting' => 'Ожидание для лечения',
		'NotifyTransmision' => 'Снятие передачи',
		'NotifyEmision' => 'Снятие выбросов',
		'NotifyCredit' => 'Снятие кредитную',
		'NumeroNationalEmetter' => 'Национальный передатчик Количество',
		'PleaseSelectCustomerBankBANToWithdraw' => 'Выберите информацию о счете клиента банк, чтобы снять',
		'WithBankUsingRIB' => 'Для банковских счетов с использованием RIB',
		'WithBankUsingBANBIC' => 'Для банковских счетов с использованием IBAN / BIC / SWIFT',
		'BankToReceiveWithdraw' => 'Банковский счет для получения отзывает',
		'CreditDate' => 'Кредит на',
		'WithdrawalFileNotCapable' => 'Невозможно создать файл вывода квитанцию ​​для вашей страны',
		'ShowWithdraw' => 'Показать Вывод',
		'IfInvoiceNeedOnWithdrawPaymentWontBeClosed' => 'Однако, если счет-фактура имеет по крайней мере один вывод оплаты еще не обработан, то он не будет установлен, как оплачиваются, чтобы управлять снятие ранее.',
		'DoStandingOrdersBeforePayments' => 'Это вкладок позволяет запросить за постоянного платежного поручения. Как только она будет закончена, вы можете ввести оплату, чтобы закрыть счета.',
		////// Notifications
		'InfoCreditSubject' => 'Оплата постоянных %s порядке банк',
		'InfoCreditMessage' => 'Постоянное поручение %s была выплачена банком <br> Данные оплаты: %s',
		'InfoTransSubject' => 'Передача стоять %s чтобы банк',
		'InfoTransMessage' => 'Постоянное поручение %s был Передано в банк %s %s. <br><br>',
		'InfoTransData' => 'Сумма: %s <br> Metode: %s <br> Дата: %s',
		'InfoFoot' => 'Это автоматизированное сообщение, отправленное Dolibarr',
		'InfoRejectSubject' => 'Постоянное платежное поручение отказался',
		'InfoRejectMessage' => 'Добрый день, <br><br> standig порядок счета %s, связанные с компанией %s, с количеством %s было отказано в банке. <br><br> - <br> % $',
		'ModeWarning' => 'Вариант для реального режима не был установлен, мы останавливаемся после этого моделирования'
);
?>