<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Kategória',
		'Categories' => 'Kategóriák',
		'Rubrique' => 'Kategória',
		'Rubriques' => 'Kategóriák',
		'categories' => 'kategóriák',
		'TheCategorie' => 'A kategória',
		'NoCategoryYet' => 'No category of this type created',
		'In' => 'In',
		'AddIn' => 'Add in',
		'modify' => 'módosítás',
		'Classify' => 'Osztályozás',
		'CategoriesArea' => 'Kategóriák terület',
		'ProductsCategoriesArea' => 'Termékek/Szolgáltatások kategória terület',
		'SuppliersCategoriesArea' => 'Beszállítói kategóriák terület',
		'CustomersCategoriesArea' => 'Ügyfél kategóriák terület',
		'ThirdPartyCategoriesArea' => 'Harmadik fél kategóriák terület',
		'MembersCategoriesArea' => 'Tagok kategória terület',
		'MainCats' => 'Fő kategóriák',
		'SubCats' => 'Alkategóriák',
		'CatStatistics' => 'Statisztikák',
		'CatList' => 'Kategóriák listája',
		'AllCats' => 'Minden kategória',
		'ViewCat' => 'Kategória megtekintése',
		'NewCat' => 'Add category',
		'NewCategory' => 'Új kategória',
		'ModifCat' => 'Kategória módosítása',
		'CatCreated' => 'Kategória létrehozva',
		'CreateCat' => 'Kategória létrehozása',
		'CreateThisCat' => 'Kategória létrehozása',
		'ValidateFields' => 'Mezők hitelesítése',
		'NoSubCat' => 'Nincs alkategória.',
		'SubCatOf' => 'Alkategória',
		'FoundCats' => 'Talált kategóriák',
		'FoundCatsForName' => 'Név számára talált kategóriák:',
		'FoundSubCatsIn' => 'Talált alkategória a kategóriában',
		'ErrSameCatSelected' => 'Többször választotta ki ugyan azt a kategóriát',
		'ErrForgotCat' => 'Elfelejtett kategóriát választani',
		'ErrForgotField' => 'Elfelejtette kitölteni a mezőket',
		'ErrCatAlreadyExists' => 'Ez a nvé már használatban van',
		'AddProductToCat' => 'Adjuk hozzá a terméket ehhez a kategóriához?',
		'ImpossibleAddCat' => 'Nem lehet kategorizálni',
		'ImpossibleAssociateCategory' => 'Nem lehet asszociálni a kategóriát',
		'WasAddedSuccessfully' => '<b>%s</b> sikeresen hozzá lett adva.',
		'ObjectAlreadyLinkedToCategory' => 'Már a kategóriához van linkelve.',
		'CategorySuccessfullyCreated' => 'Ez a kategória %s sikeresen hozzá lett adva.',
		'ProductIsInCategories' => 'Termékek/Szolgáltatások a következő kategóriákat tulajdonolják',
		'SupplierIsInCategories' => 'Ez a harmadik fél a következő beszállítókat tulajdonolják',
		'CompanyIsInCustomersCategories' => 'Ez a harmadik fél a következő ügyfeleket/kilátásokat tulajdonolják',
		'CompanyIsInSuppliersCategories' => 'Ez a harmadik fél a következő beszállítókat tulajdonolják',
		'MemberIsInCategories' => 'Ez a tag ebbe a tag kategóriába tartozik',
		'ProductHasNoCategory' => 'Ez a termék/szolgáltatás nincs egy kategóriában sem',
		'SupplierHasNoCategory' => 'Ez a beszállító nincs egy kategóriában sem',
		'CompanyHasNoCategory' => 'Ez a cég nincs egy kategóriában sem',
		'MemberHasNoCategory' => 'Ez a tag nincs egy kategóriában sem',
		'ClassifyInCategory' => 'Kategorizálni',
		'NoneCategory' => 'Nincs',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Ez a kategória ezzel a ref# -el már létezik',
		'ReturnInProduct' => 'Vissza a termék/szolgáltatás kártyához',
		'ReturnInSupplier' => 'Vissza a beszállító kártyához',
		'ReturnInCompany' => 'Vissza az ügyfél/kilátás kártyához',
		'ContentsVisibleByAll' => 'A tartalom mindenki számára látható lesz',
		'ContentsVisibleByAllShort' => 'Tartalom látható mindenki számára',
		'ContentsNotVisibleByAllShort' => 'Tartalom nem látható mindenki számára',
		'CategoriesTree' => 'Kategória fa',
		'DeleteCategory' => 'Kategória törlése',
		'ConfirmDeleteCategory' => 'Biztos törölni akarja a kategóriát?',
		'RemoveFromCategory' => 'Kategória link eltávolítása',
		'RemoveFromCategoryConfirm' => 'Biztos törölni akarja a kapcsolatot a tranzakció és a kategória közt?',
		'NoCategoriesDefined' => 'Nincs definiált kategóriáa',
		'SuppliersCategoryShort' => 'Beszállítói kategória',
		'CustomersCategoryShort' => 'Vásárlói kategória',
		'ProductsCategoryShort' => 'Termék kategória',
		'MembersCategoryShort' => 'Tag kategória',
		'SuppliersCategoriesShort' => 'Beszállítói kategória',
		'CustomersCategoriesShort' => 'Vásárlói kategória',
		'CustomersProspectsCategoriesShort' => 'Vásárló/Kilátás kategóriák',
		'ProductsCategoriesShort' => 'Termék kategória',
		'MembersCategoriesShort' => 'Tag kategória',
		'ThisCategoryHasNoProduct' => 'Ez a kategória nem tartalmaz termékeket.',
		'ThisCategoryHasNoSupplier' => 'Ez a kategória nem tartalmaz beszállítót.',
		'ThisCategoryHasNoCustomer' => 'Ez a kategória nem tartalmaz vásárlót.',
		'ThisCategoryHasNoMember' => 'Ez a kategória nem tartalmaz tagot.',
		'AssignedToCustomer' => 'Vásárlóhoz rendelve',
		'AssignedToTheCustomer' => 'Vásárlóhoz rendelve',
		'InternalCategory' => 'Belső kategória',
		'CategoryContents' => 'Kategória tartalmak',
		'CategId' => 'Kategória azon#',
		'CatSupList' => 'Beszállítói kategóriák listázása',
		'CatCusList' => 'Ügyfél/kilátás kategóriák listázása',
		'CatProdList' => 'Termék kategóriák listázása',
		'CatMemberList' => 'Tag kategóriák listázása',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>