<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Kereskedelem',
		'CommercialArea' => 'Kereskedelemi terület',
		'CommercialCard' => 'Kereskedelemi kártya',
		'CustomerArea' => 'Ügyfél terület',
		'Customer' => 'Ügyfél',
		'Customers' => 'Ügyfelek',
		'Prospect' => 'Kilátás',
		'Prospects' => 'Kilátások',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Cselekvés / feladat törlése',
		'NewAction' => 'Új cselekvés / feladat',
		'AddAction' => 'Cselekvés / feladat hozzáadása',
		'AddAnAction' => 'Cselekvés / feladat hozzáadása',
		'AddActionRendezVous' => 'Találkozó hozzáadása',
		'Rendez-Vous' => 'Találkozó',
		'ConfirmDeleteAction' => 'Biztos törölni akarja ezt a feladatot?',
		'CardAction' => 'Cselekvés kártya',
		'PercentDone' => 'százalék kész',
		'ActionOnCompany' => 'Céggel kapcsolatos feladat',
		'ActionOnContact' => 'Kapcsolattal kapcsolatos feladat',
		'TaskRDV' => 'Találkozó',
		'TaskRDVWith' => 'Találkozó %s -al',
		'ShowTask' => 'Feladat mutatása',
		'ShowAction' => 'Cselekvés mutatása',
		'ActionsReport' => 'Cselekvés jelentés',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Értékesítő',
		'SalesRepresentatives' => 'Értékesítők',
		'SalesRepresentativeFollowUp' => 'Értékesítő (utólagos)',
		'SalesRepresentativeSignature' => 'Értékesítő (aláírás)',
		'CommercialInterlocutor' => 'Kereskedelmi partnere',
		'ErrorWrongCode' => 'Rossz kód',
		'NoSalesRepresentativeAffected' => 'Nincs érintett értékesítő',
		'ShowCustomer' => 'Ügyfél mutatása',
		'ShowProspect' => 'Kilátás mutatása',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Kilátások listája',
		'ListOfCustomers' => 'Ügyfelek listája',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'Utolsó %s kész feladat',
		'LastRecordedTasks' => 'Utolsó jegyzett feladatok',
		'LastActionsToDo' => 'Utolsó %s legrégebbi nem végrehajtott feladat',
		'DoneAndToDoActionsFor' => 'Végrehajtott és végrehajtásra váró feladatok %s részére',
		'DoneAndToDoActions' => 'Végrehajtott és végrehajtásra váró feladatok',
		'DoneActions' => 'Befejezett cselekvések',
		'DoneActionsFor' => 'Befejezett cselekvések %s részére',
		'ToDoActions' => 'Befejezetlen cselekvések',
		'ToDoActionsFor' => 'Befejezetlen cselekvések %s részére',
		'SendPropalRef' => 'Ajánlat küldése %s',
		'SendOrderRef' => 'Megrendelés küldése %s',
		'StatusNotApplicable' => 'Nem alkalmazható',
		'StatusActionToDo' => 'Végrehajtani',
		'StatusActionDone' => 'Kész',
		'StatusActionInProcess' => 'Folyamatban',
		'MyActionsAsked' => 'Általam jegyzett cselekvések',
		'MyActionsToDo' => 'Általam végrahajtandó cselekvések',
		'MyActionsDone' => 'Engem befolyásoló események',
		'TasksHistoryForThisContact' => 'Cselekvések ehhez a kapcsolathoz',
		'LastProspectDoNotContact' => 'Ne forduljon hozzá',
		'LastProspectNeverContacted' => 'Soha nem volt kapcsolatfölvétel',
		'LastProspectToContact' => 'Kapcsolatba lépés',
		'LastProspectContactInProcess' => 'Kapcsolatba lépés folyamatban',
		'LastProspectContactDone' => 'Kapcsolatba lépés megtörtént',
		'DateActionPlanned' => 'Cselekmény dátuma',
		'DateActionDone' => 'Cselekvés befejezésésnek a dátuma',
		'ActionAskedBy' => 'Cselekvést kérte',
		'ActionAffectedTo' => 'Cselekvés hatással van rá',
		'ActionDoneBy' => 'Cselekvést végrehatja',
		'ActionUserAsk' => 'Jegyezte',
		'ErrorStatusCantBeZeroIfStarted' => 'Ha a \'<b>Cselekvés befejezésésnek a dátuma</b>\' mező rendelkezik tartalommal, a cselekvés elkezdődőtt (vagy befejeződtt), az \'<b>Állapot</b>\' mező nem lehet 0%%.',
		'ActionAC_TEL' => 'Telefon hívás',
		'ActionAC_FAX' => 'Fax küldés',
		'ActionAC_PROP' => 'Ajánlat küldése emailben',
		'ActionAC_EMAIL' => 'Email küldése',
		'ActionAC_RDV' => 'Találkozó',
		'ActionAC_FAC' => 'Számla küldése ügyfélnek levélben',
		'ActionAC_REL' => 'Számla küldése ügyfélnek levélben (emlékeztető)',
		'ActionAC_CLO' => 'Bezár',
		'ActionAC_EMAILING' => 'Tömeges email küldés',
		'ActionAC_COM' => 'Ügyfél rendelése elküldése levélben',
		'ActionAC_SHIP' => 'Küldje hajózás mail',
		'ActionAC_SUP_ORD' => 'Beszállítói rendelés elküldése levélben',
		'ActionAC_SUP_INV' => 'Beszállítói számla elküldése levélben',
		'ActionAC_OTH' => 'Más',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Prospect állapot',
		'DraftPropals' => 'Készítsen üzleti ajánlatot',
		'SearchPropal' => 'Keressen egy kereskedelmi javaslatot'
);
?>