<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$contracts = array(
		'CHARSET' => 'UTF-8',
		'ContractsArea' => 'Szerzősdések terólet',
		'ListOfContracts' => 'Szerződések listája',
		'LastContracts' => 'Utolsó %s módosított szerződés',
		'AllContracts' => 'Minden szerződés',
		'ContractCard' => 'Szerződés kártya',
		'ContractStatus' => 'Szerződés állpaot',
		'ContractStatusNotRunning' => 'Nem fut',
		'ContractStatusRunning' => 'Fut',
		'ContractStatusDraft' => 'Piszkozat',
		'ContractStatusValidated' => 'Hitelesítve',
		'ContractStatusClosed' => 'Lezárva',
		'ServiceStatusInitial' => 'Nem fut',
		'ServiceStatusRunning' => 'Fut',
		'ServiceStatusNotLate' => 'Fut, nem járt le',
		'ServiceStatusNotLateShort' => 'Nem járt le',
		'ServiceStatusLate' => 'Fut, lejárt',
		'ServiceStatusLateShort' => 'Lejárt',
		'ServiceStatusClosed' => 'Lezárva',
		'ServicesLegend' => 'Szolgáltatások magyarázat',
		'Contracts' => 'Szerződések',
		'Contract' => 'Szerződés',
		'NoContracts' => 'Nincs szerződés',
		'MenuServices' => 'Szolgáltatás',
		'MenuInactiveServices' => 'Nincs aktív szolgáltatás',
		'MenuRunningServices' => 'Futó szolgáltatások',
		'MenuExpiredServices' => 'Lejárt szolgáltatások',
		'MenuClosedServices' => 'Lezárt szolgáltatások',
		'NewContract' => 'Új szerződés',
		'AddContract' => 'Szerződés hozzáadása',
		'SearchAContract' => 'Szerződés keresése',
		'DeleteAContract' => 'Szerződés törlése',
		'CloseAContract' => 'Szerződés lezárása',
		'ConfirmDeleteAContract' => 'Biztos törölni akarja a szerződést és minden hozzá tartozó szolgáltatást?',
		'ConfirmValidateContract' => 'Biztos hitelesíteni akarja a szerződést?',
		'ConfirmCloseContract' => 'Lezár minden szolgáltatást (aktív vagy nem). Biztos le akarja zárni a szerződést?',
		'ConfirmCloseService' => 'Biztos le akarja zárni a <b>%s</b> dátummal ellátott szolgáltatást?',
		'ValidateAContract' => 'Szerződés hitelesítése',
		'ActivateService' => 'Aktív szolgáltatás',
		'ConfirmActivateService' => 'Biztos aktiválni akarja a <b>%s</b> dátummal ellátott szolgáltatást?',
		'RefContract' => 'Contract reference',
		'DateContract' => 'Szerződés dátuma',
		'DateServiceActivate' => 'Szolgáltatás aktiválásának dátuma',
		'DateServiceUnactivate' => 'Szolgáltatás deaktiválásának dátuma',
		'DateServiceStart' => 'Szolgáltatás kezdetének a dátuma',
		'DateServiceEnd' => 'Szolgáltatás végének a dátuma',
		'ShowContract' => 'Szerződés mutatása',
		'ListOfServices' => 'List of services',
		'ListOfInactiveServices' => 'Nem aktív szolágltatások listája',
		'ListOfExpiredServices' => 'Lejárt, de még aktív szolgáltatások listája',
		'ListOfClosedServices' => 'Lezárt szolgáltatások listája',
		'ListOfRunningContractsLines' => 'Futó szerződések listája',
		'ListOfRunningServices' => 'Futó szolgáltatások listája',
		'NotActivatedServices' => 'Inaktív szolgáltatások (a hitelesített szerződések között)',
		'BoardNotActivatedServices' => 'Hitelesített szerződésekhez tartozó aktiválandó szolgáltatások',
		'LastContracts' => 'Utolsó %s módosított szerződés',
		'LastActivatedServices' => 'Utolós %s aktivált szolgáltatás',
		'LastModifiedServices' => 'Utolsó %s módosított szolgáltatás',
		'EditServiceLine' => 'Szolgáltatás sor szerkesztése',
		'ContractStartDate' => 'Kezdési dátum',
		'ContractEndDate' => 'Befejezési dátum',
		'DateStartPlanned' => 'Tervezett kezdési dátum',
		'DateStartPlannedShort' => 'Tervezett kezdési dátum',
		'DateEndPlanned' => 'Tervezett befejezési dátum',
		'DateEndPlannedShort' => 'Tervezett befejezési dátum',
		'DateStartReal' => 'Tényleges kezdési dátum',
		'DateStartRealShort' => 'Tényleges kezdési dátum',
		'DateEndReal' => 'Tényleges befejezési dátum',
		'DateEndRealShort' => 'Tényleges befejezési dátum',
		'NbOfServices' => 'Szolgáltatások száma',
		'CloseService' => 'Szolgáltatás lezárása',
		'ServicesNomberShort' => '%s szolgáltatás(ok)',
		'RunningServices' => 'Futó szolgáltatások',
		'BoardRunningServices' => 'Lejárt futó szolgáltatások',
		'ServiceStatus' => 'Szolgáltatások állapota',
		'DraftContracts' => 'Szerződés tervezetek',
		'CloseRefusedBecauseOneServiceActive' => 'A szerződés addig nem zárható le amig legalább 1 nyitott szolgáltatás van még',
		'CloseAllContracts' => 'Minden szerződés sor lezárása',
		'DeleteContractLine' => 'Szerződés sor törlése',
		'ConfirmDeleteContractLine' => 'Biztos törölni akarja a szerződés sort?',
		'MoveToAnotherContract' => 'Szolgáltatás átmozgatása másik szerződéshez.',
		'ConfirmMoveToAnotherContract' => 'Új cél szerződést választottam a szolgáltatásnak, és át akarok helyezni a szolgáltatást.',
		'ConfirmMoveToAnotherContractQuestion' => 'Melyik létező szerződéshez (ugyan azon harmadik fél) szeretné átmozgatni a szolgáltatást?',
		'PaymentRenewContractId' => 'Szerződés sor megújítása (%s)',
		'ExpiredSince' => 'Lejárati dátum',
		'RelatedContracts' => 'Csatlakozó szerződések',
		'NoExpiredServices' => 'Nincs lejárt aktív szolgáltatások',
		////////// Types de contacts //////////
		'TypeContact_contrat_internal_SALESREPSIGN' => 'Értékesítési képviselő a szerződés aláírásakor',
		'TypeContact_contrat_internal_SALESREPFOLL' => 'Értékesítési képviselő a szerződés követésekor',
		'TypeContact_contrat_external_BILLING' => 'Számlázandó ügyfél',
		'TypeContact_contrat_external_CUSTOMER' => 'Ügyfél kapcsolat tartó',
		'TypeContact_contrat_external_SALESREPSIGN' => 'A szerződést aláíró ügyfél',
		'Error_CONTRACT_ADDON_NotDefined' => 'Állandó CONTRACT_ADDON nincs definiálva'
);
?>