<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$errors = array(
		'CHARSET' => 'UTF-8',
		'MenuManager' => 'Menükezelőben',
		// Errors
		'Error' => 'Hiba',
		'Errors' => 'Hibák',
		'ErrorBadEMail' => 'E-mail %s rossz',
		'ErrorBadUrl' => 'Url %s rossz',
		'ErrorLoginAlreadyExists' => 'Bejelentkezés %s már létezik.',
		'ErrorGroupAlreadyExists' => 'Csoport %s már létezik.',
		'ErrorRecordNotFound' => 'Jegyezze fel nem található.',
		'ErrorFailToCopyFile' => 'Fájl másolása sikertelen <b>&quot;%s&quot;</b> a <b>&quot;%s&quot;.</b>',
		'ErrorFailToRenameFile' => 'Nem sikerült átnevezni file <b>&quot;%s&quot;</b> a <b>&quot;%s&quot;.</b>',
		'ErrorFailToDeleteFile' => 'Nem sikerült eltávolítani fájl <b>&quot;%s&quot;.</b>',
		'ErrorFailToCreateFile' => 'Nem sikerült létrehozni a fájlt <b>&quot;%s&quot;.</b>',
		'ErrorFailToRenameDir' => 'Nem sikerült átnevezni könyvtár <b>&quot;%s&quot;</b> a <b>&quot;%s&quot;.</b>',
		'ErrorFailToCreateDir' => 'Nem sikerült létrehozni a könyvtárat <b>&quot;%s&quot;.</b>',
		'ErrorFailToDeleteDir' => 'Nem sikerült törölni a könyvtárat <b>&quot;%s&quot;.</b>',
		'ErrorFailedToDeleteJoinedFiles' => 'Nem lehet törölni a környezetet, mert van néhány kép csatlakozott. Vegye csatlakozni fájlok.',
		'ErrorThisContactIsAlreadyDefinedAsThisType' => 'Ez a kapcsolat már definiálva van, mint az ilyen típusú kapcsolatot.',
		'ErrorCashAccountAcceptsOnlyCashMoney' => 'Ez egy bankszámlán pénzszámlájának, ezért fizetést elfogadó típus csak készpénzes.',
		'ErrorFromToAccountsMustDiffers' => 'Forrás és célok bankszámlák különbözőnek kell lennie.',
		'ErrorBadThirdPartyName' => 'Rossz érték a harmadik fél nevében',
		'ErrorBadCustomerCodeSyntax' => 'Rossz a szintaxisa az ügyfél kód',
		'ErrorCustomerCodeRequired' => 'Ügyfél kód szükséges',
		'ErrorCustomerCodeAlreadyUsed' => 'Ügyfél kód már használatban',
		'ErrorPrefixRequired' => 'Előtag szükséges',
		'ErrorUrlNotValid' => 'A honlap címe hibás',
		'ErrorBadSupplierCodeSyntax' => 'Rossz szintaxisa szállító kód',
		'ErrorSupplierCodeRequired' => 'Szállító kód szükséges',
		'ErrorSupplierCodeAlreadyUsed' => 'Szállító kód már használatban',
		'ErrorBadParameters' => 'Hibás paraméterek',
		'ErrorBadValueForParameter' => 'Rossz érték &quot;%s&quot; helytelen paraméter &quot;%s&quot;',
		'ErrorBadImageFormat' => 'Kép fájl formátuma nem támogatott',
		'ErrorBadDateFormat' => 'Érték &quot;%s&quot; rossz a dátum formátumát',
		'ErrorFailedToWriteInDir' => 'Nem sikerült írni a könyvtárban %s',
		'ErrorFoundBadEmailInFile' => 'Talált rossz e-mail szintaxisa %s sorok fájlt (például az e-mail vonal %s %s =)',
		'ErrorUserCannotBeDelete' => 'A felhasználó nem törölhető. Lehet, hogy ez jár a Speedealing szervezetek.',
		'ErrorFieldsRequired' => 'Néhány jelölt mezők kitöltése kötelező nem töltött.',
		'ErrorFailedToCreateDir' => 'Nem sikerült létrehozni egy könyvtárat. Ellenőrizze, hogy a Web szerver felhasználó engedélyekkel rendelkezik, hogy ültesse át Speedealing dokumentumok könyvtárba. Ha a paraméter <b>safe_mode</b> engedélyezve van ez a PHP-t, ellenőrizze, hogy Speedealing PHP fájlok tulajdonosa a webszerver felhasználó (vagy csoport).',
		'ErrorNoMailDefinedForThisUser' => 'Nincs definiálva mail felhasználó',
		'ErrorFeatureNeedJavascript' => 'Ez a funkció JavaScript aktiválni kell dolgozni. Változtassa meg ezt a setup - kijelző.',
		'ErrorTopMenuMustHaveAParentWithId0' => 'Egy menü típusú &quot;fent&quot; nem lehet egy szülő menüben. Tedd 0 szülő menüből, vagy válasszon egy menüt típusú &quot;baloldal&quot;.',
		'ErrorLeftMenuMustHaveAParentId' => 'Egy menü típusú &quot;Bal&quot; kell egy szülő id.',
		'ErrorFileNotFound' => '<b>%s</b> fájl nem található (Rossz út, rossz engedélyek vagy a hozzáférés megtagadva a PHP safe_mode openbasedir vagy paraméter)',
		'ErrorDirNotFound' => '<b>%s</b> könyvtár nem található (Rossz út, rossz engedélyek vagy a hozzáférés megtagadva a PHP safe_mode openbasedir vagy paraméter)',
		'ErrorFunctionNotAvailableInPHP' => 'Funkció <b>%s</b> van szükség, de ez a funkció nem érhető el ez a verzió / beállítását PHP.',
		'ErrorDirAlreadyExists' => 'A könyvtár ezzel a névvel már létezik.',
		'ErrorFileAlreadyExists' => 'Egy ugyanilyen nevű fájl már létezik.',
		'ErrorPartialFile' => 'A fájl nem kapott teljesen szerver.',
		'ErrorNoTmpDir' => 'Ideiglenes directy %s nem létezik.',
		'ErrorUploadBlockedByAddon' => 'Töltsd blokkolja PHP / Apache plugin.',
		'ErrorFileSizeTooLarge' => 'A fájl mérete túl nagy.',
		'ErrorSizeTooLongForIntType' => 'Méret túl hosszú int típusú (maximum %s számjegy)',
		'ErrorSizeTooLongForVarcharType' => 'Méret túl hosszú a string típusú (%s karakter maximum)',
		'ErrorFieldCanNotContainSpecialCharacters' => '<b>%s</b> mező nem tartalmaz speciális karaktereket.',
		'ErrorNoAccountancyModuleLoaded' => 'Nem számviteli modul aktiválódik',
		'ErrorExportDuplicateProfil' => 'Ez a profil név már létezik ez a kivitel készlet.',
		'ErrorLDAPSetupNotComplete' => 'Speedealing LDAP-egyezés nem teljes.',
		'ErrorLDAPMakeManualTest' => 'Egy. LDIF fájlt keletkezett %s könyvtárban. Próbálja meg kézzel betölteni a parancssorból, hogy több információt hibákat.',
		'ErrorCantSaveADoneUserWithZeroPercentage' => 'Nem lehet menteni akciót &quot;az alapszabály nem kezdődött el&quot;, ha a területen &quot;történik&quot; is ki van töltve.',
		'ErrorRefAlreadyExists' => 'Ref használt létrehozására már létezik.',
		'ErrorPleaseTypeBankTransactionReportName' => 'Kérjük, írja banki átvételi ügylet neve, ahol a jelentések (Format ÉÉÉÉHH vagy ÉÉÉÉHHNN)',
		'ErrorRecordHasChildren' => 'Nem sikerült törölni rekordokat, mert van néhány gyermek.',
		'ErrorModuleRequireJavascript' => 'Javascript nem szabad tiltani, hogy ez a funkció működik. Annak engedélyezése / tiltása Javascript, menj a menü Home-> Beállítások-> Kijelző.',
		'ErrorPasswordsMustMatch' => 'Mindkét típusú jelszavakat kell egyeznie egymással',
		'ErrorContactEMail' => 'Egy technikai hiba történt. Kérjük, lépjen kapcsolatba a következő e-mail rendszergazda <b>%s</b> en biztosítja a hibakódot <b>%s</b> be az üzenetet, vagy még jobb hozzáadásával képernyő ezen oldal másolatát.',
		'ErrorWrongValueForField' => 'Rossz érték mezőszám <b>%s</b> (érték <b>&quot;%s&quot;</b> nem egyezik regex szabály <b>%s)</b>',
		'ErrorFieldValueNotIn' => 'Rossz érték mezőszám <b>%s</b> (érték <b>&quot;%s&quot;</b> nem érték áll rendelkezésre a területen <b>%s %s</b> táblázat)',
		'ErrorFieldRefNotIn' => 'Rossz érték mezőszám <b>%s</b> (érték <b>&quot;%s&quot;</b> nem létező <b>%s</b> ref)',
		'ErrorsOnXLines' => '<b>%s</b> hibák forrása vonalak',
		'ErrorFileIsInfectedWithAVirus' => 'A víruskereső program nem tudta érvényesíteni a fájl (file lehet megfertőzte egy vírus)',
		'ErrorSpecialCharNotAllowedForField' => 'Speciális karakterek használata nem engedélyezett területen &quot;%s&quot;',
		'ErrorDatabaseParameterWrong' => 'Adatbázis beállítás paraméter <b>&quot;%s&quot;,</b> amelynek értéke nem kompatibilis használni Speedealing (kell érték <b>&quot;%s&quot;).</b>',
		'ErrorNumRefModel' => 'A referencia létezik az adatbázis (%s), és nem kompatibilis ezzel a számozással a szabály. Vegye rekord vagy átnevezték hivatkozással, hogy aktiválja ezt a modult.',
		'ErrorQtyTooLowForThisSupplier' => 'Mennyiség túl alacsony ehhez a szállító vagy nincs ár megadva a termék erre a szállító',
		'ErrorModuleSetupNotComplete' => 'Beállítás modul néz ki, hogy uncomplete. Menj a Setup - modulok befejezéséhez.',
		'ErrorBadMask' => 'Hiba a maszk',
		'ErrorBadMaskFailedToLocatePosOfSequence' => 'Hiba, maszk sorozatszám nélkül',
		'ErrorBadMaskBadRazMonth' => 'Hiba, rossz érték visszaállítása',
		'ErrorSelectAtLeastOne' => 'Hiba. Válasszon legalább egy bejegyzést.',
		'ErrorProductWithRefNotExist' => 'Termék referencia <i>&quot;%s&quot;</i> nem létezik',
		'ErrorDeleteNotPossibleLineIsConsolidated' => 'Törlése nem lehetséges, mert rekord kapcsolódik egy bank, amely egyeztetett transation',
		'ErrorProdIdAlreadyExist' => '%s van rendelve egy másik harmadik',
		'ErrorFailedToSendPassword' => 'Nem sikerült elküldeni a jelszót',
		'ErrorFailedToLoadRSSFile' => 'Nem kap RSS feed. Próbálja felvenni, ha állandó MAIN_SIMPLEXMLLOAD_DEBUG hibaüzenetek nem nyújt elegendő információt.',
		'ErrorPasswordDiffers' => 'Jelszavak eltér, kérjük, írja be őket újra.',
		'ErrorForbidden' => 'A hozzáférés megtagadva. <br> Ha megpróbál hozzáférni egy oldalra, terület vagy szolgáltatás, anélkül, hogy hiteles ülésen, vagy, hogy nem szabad a felhasználó számára.',
		'ErrorForbidden2' => 'Engedély e be lehet meghatározni a Speedealing rendszergazda menüből %s-> %s.',
		'ErrorForbidden3' => 'Úgy tűnik, hogy Speedealing nem használt keresztül hitelesített ülésén. Vessen egy pillantást Speedealing üzembe helyezési dokumentációban tudni, hogyan kell kezelni hitelesítések (htaccess, mod_auth vagy más ...).',
		'ErrorNoImagickReadimage' => 'Osztály imagick nem található ebben a PHP. Nem előnézet elérhető. A rendszergazdák letilthatják ezt a lapot menüből Setup - Display.',
		'ErrorRecordAlreadyExists' => 'Felvétel már létezik',
		'ErrorCantReadFile' => 'Nem sikerült olvasni file "%s"',
		'ErrorCantReadDir' => 'Nem sikerült olvasni könyvtár "%s"',
		'ErrorFailedToFindEntity' => 'Nem sikerült olvasni környezet "%s"',
		'ErrorBadLoginPassword' => 'Rossz érték be vagy jelszó',
		'ErrorLoginDisabled' => 'A fiók le van tiltva',
		'ErrorFailedToRunExternalCommand' => 'Nem sikerült futtatni külső parancsot. Ellenőrizze, hogy elérhető és futtatható a PHP szerver. Ha a PHP <b>Safe Mode</b> be van kapcsolva, ellenőrizze, hogy a parancs belsejében egy könyvtár által meghatározott paraméter <b>safe_mode_exec_dir.</b>',
		'ErrorFailedToChangePassword' => 'Nem sikerült megváltoztatni a jelszót',
		'ErrorLoginDoesNotExists' => 'Felhasználó bejelentkezési <b>%s</b> nem található.',
		'ErrorLoginHasNoEmail' => 'Ennek a felhasználónak nincs e-mail címre. Folyamat megszakítva.',
		'ErrorBadValueForCode' => 'Rossz érték a biztonsági kódot. Próbálja újra, az új érték ...',
		'ErrorBothFieldCantBeNegative' => 'Fields %s %s és nem lehet egyszerre negatív',
		'ErrorWebServerUserHasNotPermission' => 'Felhasználói fiók <b>%s</b> végrehajtására használnak web szerver nincs engedélye az adott',
		'ErrorNoActivatedBarcode' => 'Nem vonalkód típus aktivált',
		'ErrUnzipFails' => 'Failed to unzip %s with ZipArchive',
		'ErrNoZipEngine' => 'No engine to unzip %s file in this PHP',
		'ErrorFileMustBeASpeedealingPackage' => 'The file %s must be a Speedealing zip package',
		'ErrorFileRequired' => 'It takes a package Speedealing file',
		'ErrorPhpCurlNotInstalled' => 'The PHP CURL is not installed, this is essential to talk with Paypal',
		'ErrorFailedToAddToMailmanList' => 'Failed to add record to Mailman list or SPIP base',
		'ErrorNewVaueCantMatchOldValue' => 'New value can\'t be equal to old one',
		'ErrorDuplicateTrigger' => 'Un fichier trigger de classe \'<b>%s</b>\' est présent plusieurs fois. Supprimer le doublon du répertoire \'<b>%s</b>\'.',
		'SESSIONEXPIRE' => 'La session est expirée',
		// Warnings
		'WarningMandatorySetupNotComplete' => 'Mandatory setup parameters are not yet defined',
		'WarningSafeModeOnCheckExecDir' => 'Figyelem, a PHP <b>safe_mode</b> beállítás be van kapcsolva, így parancsot kell tárolni benne egy könyvtár által bejelentett PHP paraméter <b>safe_mode_exec_dir.</b>',
		'WarningAllowUrlFopenMustBeOn' => 'Paraméter <b>allow_url_fopen</b> kell állítani <b>a php.ini-ben</b> Filer, amiért ez a modul működése teljesen. Módosítania kell ezt a fájlt kézzel.',
		'WarningBuildScriptNotRunned' => 'Script <b>%s</b> még nem futott építeni grafika, vagy nincs adat megjelenítéséhez.',
		'WarningBookmarkAlreadyExists' => 'A könyvjelző ezzel a címmel, vagy ez a cél (URL) már létezik.',
		'WarningPassIsEmpty' => 'Figyelem, az adatbázis jelszó üres. Ez egy biztonsági lyuk. Meg kell hozzá egy jelszót, hogy az adatbázis és változtassa meg a fájl conf.php ezt tükröznie kell.',
		'WarningConfFileMustBeReadOnly' => 'Figyelem, a config file <b>(htdocs / conf / conf.php)</b> át lehet írni a webszerver. Ez egy komoly biztonsági rést. Jogosultságát módosítani a fájlt, hogy a csak olvasható módban az operációs rendszer felhasználói által használt webszerver. Ha Windows FAT és az a lemez, akkor tudnia kell, hogy ez a fájl rendszer nem engedi hozzáadni file jogosultságokat, így nem lehet teljesen biztonságos.',
		'WarningsOnXLines' => 'Figyelmeztetések <b>%s</b> forrás vonalak',
		'WarningNoDocumentModelActivated' => 'Nem modell, a dokumentum generáció, be van kapcsolva. A modell kerül választottunk alapértelmezés szerint amíg ellenőrizze a modul beállításait.',
		'WarningLockFileDoesNotExists' => 'Warning, once setup is finished, you must disable install/migrate tools by adding a file <b>install.lock</b> into directory <b>%s</b>. Missing this file is a security hole.',
		'WarningUntilDirRemoved' => 'Minden biztonsági figyelmeztetések (látható: admin felhasználó esetén) továbbra is aktív marad, amíg a biztonsági rés van jelen (vagy állandó MAIN_REMOVE_INSTALL_WARNING egészül ki a Setup-> Egyéb beállítás).',
		'WarningCloseAlways' => 'Warning, closing is done even if amount differs between source and target elements. Enable this feature with caution.'
);
?>