<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'Felhasználó kártya',
		'ContactCard' => 'Kapcsolat kártya',
		'GroupCard' => 'Csoport kártya',
		'NoContactCard' => 'Nincs kapcsolat kártya',
		'Permission' => 'Engedély',
		'Permissions' => 'Engedélyek',
		'EditPassword' => 'Jelszó szerkesztése',
		'SendNewPassword' => 'Jelszó újragenerálása és küldése',
		'ReinitPassword' => 'Jelszó újragenerálása',
		'PasswordChangedTo' => '%s -ra lett megváltoztatva a jelszó',
		'SubjectNewPassword' => 'Az új jelszava',
		'AvailableRights' => 'Elérhető engedélyek',
		'OwnedRights' => 'Tulajdonolt engedélyek',
		'GroupRights' => 'Csoport engedélyek',
		'UserRights' => 'Felhasználói engedélyek',
		'UserGUISetup' => 'Felhasználó megjelenésének beállításai',
		'DisableUser' => 'Letiltás',
		'DisableAUser' => 'Felhasználó letiltása',
		'DeleteUser' => 'Törlés',
		'DeleteAUser' => 'Felhasználó törlése',
		'DisableGroup' => 'Letiltás',
		'DisableAGroup' => 'Csoport letiltása',
		'EnableAUser' => 'Felhasználó engedélyezése',
		'EnableAGroup' => 'Csoport engedélyezése',
		'DeleteGroup' => 'Törlés',
		'DeleteAGroup' => 'Csoport törlése',
		'ConfirmDisableUser' => 'Biztos le akarja tiltani <b>%s</b> felhasználót?',
		'ConfirmDisableGroup' => 'Biztos le akarja tiltani <b>%s</b> csoportot?',
		'ConfirmDeleteUser' => 'Biztos törölni akarja <b>%s</b> felhasználót?',
		'ConfirmDeleteGroup' => 'Biztos törölni akarja <b>%s</b> csoportot?',
		'ConfirmEnableUser' => 'Biztos engedélyezni akarja <b>%s</b> felhasználót?',
		'ConfirmEnableGroup' => 'Biztos engedélyezni akarja <b>%s</b> csoportot?',
		'ConfirmReinitPassword' => 'Biztos új leszavat szeretne generálni <b>%s</b> felhasználó számára?',
		'ConfirmSendNewPassword' => 'Biztos új leszavat szeretne generálni <b>%s</b> felhasználó számára és elküldeni azt neki?',
		'NewUser' => 'Új felhasználó',
		'CreateUser' => 'Felhasználó létrehozása',
		'SearchAGroup' => 'Csoport keresése',
		'SearchAUser' => 'Felhasználó keresése',
		'LoginNotDefined' => 'Bejelentkezés nincs definiálva.',
		'NameNotDefined' => 'Név nincs megadva.',
		'ListOfUsers' => 'Felhasználók listája',
		'Administrator' => 'Adminisztrátor',
		'SuperAdministrator' => 'Szuper Adminisztrátor',
		'SuperAdministratorDesc' => 'Adminisztrátor minden joggal',
		'AdministratorDesc' => 'Rendszergazda személy',
		'DefaultRights' => 'Alapértelmezett engedélyek',
		'DefaultRightsDesc' => 'Itt adhatja meg az <u>alapértelmezett</u> jogokat amiket az <u>új felhasználók</u> autómatikusan megkapnak (A meglévő felasználók engedélyeit a felhasználó kártyáján szerkesztheti).',
		'SpeedealingUsers' => 'Speedealing users',
		'LastName' => 'Vezetéknév',
		'FirstName' => 'Keresztnév',
		'ListOfGroups' => 'Csoportok listája',
		'NewGroup' => 'Új csoport',
		'CreateGroup' => 'Csoport létrehozása',
		'RemoveFromGroup' => 'Eltávolítás a csoportból',
		'PasswordChangedAndSentTo' => 'A jelszó megváltoztatva és elküldve: <b>%s</b>.',
		'PasswordChangeRequestSent' => '<b>%s</b> által kért jelszóváltoztatás el lett küldve ide: <b>%s</b>.',
		'MenuUsersAndGroups' => 'Felhasználók és csoportok',
		'LastGroupsCreated' => 'Utolsó %s létrehozott csoport',
		'LastUsersCreated' => 'Utolsó %s létrehozott felhasználó',
		'ShowGroup' => 'Csoport mutatása',
		'ShowUser' => 'Felhasználó mutatása',
		'NonAffectedUsers' => 'Nem érintett felhasználók',
		'UserModified' => 'Felhasználó sikeresen módosítva',
		'GroupModified' => 'Csoport sikeresen módosítva',
		'PhotoFile' => 'Fénykép',
		'UserWithSpeedealingAccess' => 'User with Speedealing access',
		'ListOfUsersInGroup' => 'Csoporthoz tartozó felhasználók listája',
		'ListOfGroupsForUser' => 'Felhasználóhoz tartozó csoportok listája',
		'UsersToAdd' => 'Csoporthoz adandó felhasználók',
		'GroupsToAdd' => 'Felhasználóhoz adandó csoportok',
		'NoLogin' => 'Nincs bejelentkezés',
		'LinkToCompanyContact' => 'Harmadik félhez/kapcsolathoz kapcsolás',
		'LinkedToSpeedealingMember' => 'Link to member',
		'LinkedToSpeedealingUser' => 'Link to Speedealing user',
		'LinkedToSpeedealingThirdParty' => 'Link to Speedealing third party',
		'CreateSpeedealingLogin' => 'Create a user',
		'CreateSpeedealingThirdParty' => 'Create a third party',
		'LoginAccountDisable' => 'Fiók kikapcsolva, új bejelentkezés megadásával aktiválhatja.',
		'LoginAccountDisableInSpeedealing' => 'Account disabled in Speedealing.',
		'LoginAccountDisableInLdap' => 'Fiók kiakpcsolva az adott domainben.',
		'UsePersonalValue' => 'Személyes érték használata',
		'GuiLanguage' => 'Interfész nyelv',
		'InternalUser' => 'Belső felahsználó',
		'MyInformations' => 'Adataim',
		'ExportDataset_user_1' => 'Speedealing felhasználók és tulajdonságaik',
		'DomainUser' => 'Domain felhasználók %s',
		'Reactivate' => 'Újra aktiválás',
		'CreateInternalUserDesc' => 'Ez az űrlap lehetővé teszi, hogy a cége/alapítványa számára egy belső felhasználót hozzon létre. Külső felhasználó létrehozásához (ügyfél, beszállító, ...), használja a \'Speedealing felhasználó létrehozása\' gombot a harmadik fél kapcsolat kártyájáról.',
		'InternalExternalDesc' => 'A <b>belső</b> felhasználó része a cégnek/alapítványnak.<br>A <b>külső</b> felhasználó lehet ügyfél, beszállító vagy bármi egyéb.<br><br>Minden esetben az engedélyek adják a jogokat, és a külső felasználók használhatnak más megjelenésü interfészt',
		'PermissionInheritedFromAGroup' => 'Engedélyek megadva mert örökölte az egyik csoporttól.',
		'Inherited' => 'Örökölve',
		'UserWillBeInternalUser' => 'Létrehozta felhasználó lesz egy belső felhasználó (mivel nem kapcsolódik az adott harmadik fél)',
		'UserWillBeExternalUser' => 'Létrehozott felhasználó lesz egy külső felhasználó (mivel kapcsolódnak az adott harmadik fél)',
		'IdPhoneCaller' => 'Telfon hívó azonosító',
		'UserLogged' => 'Felhasználó %s kapcsolva',
		'UserLogoff' => 'Felhasználó %s logout',
		'NewUserCreated' => 'Felhasználó %s létrehozva',
		'NewUserPassword' => 'Jelszó megváltoztatása %s',
		'EventUserModified' => 'Felhasználó %s módosítva',
		'UserDisabled' => 'Felhasználó %s kikapcsolva',
		'UserEnabled' => 'Felhasználó %s aktiválva',
		'UserDeleted' => 'Felhasználó %s eltávolítva',
		'NewGroupCreated' => 'Csoport %s létrehozva',
		'GroupModified' => 'Csoport sikeresen módosítva',
		'GroupDeleted' => 'Csoport %s eltávolítva',
		'ConfirmCreateContact' => 'Biztos szeretne Speedealing fiókot létrehozni ehhez a kapcsolathoz?',
		'ConfirmCreateLogin' => 'Biztos szeretne Speedealing fiókot létrehozni ennek a tagnak?',
		'ConfirmCreateThirdParty' => 'Biztos szeretne harmadik felet létrehozni ehhez a taghoz?',
		'LoginToCreate' => 'Létrehozandó bejelentkezés',
		'NameToCreate' => 'Létrehozandó harmadik fél neve',
		'YourRole' => 'Szerepkörei',
		'YourQuotaOfUsersIsReached' => 'Aktív felhasználói kvóta elérve!',
		'NbOfUsers' => 'Nb felhasználók',
		'DontDowngradeSuperAdmin' => 'Csak egy superadmin lehet downgrade 1 superadmin',
		'NewDatabase' => 'Nouvelle base de données',
		'CreateDatabase' => 'Créer la base de données',
		'ListOfDatabases' => 'Liste des bases de données',
		'ListOfUsersInDatabase' => 'Liste des utilisateurs liés à la base de données',
		'ListOfRolesInDatabase' => 'Liste des groupes liés à la base de données',
		'DeleteADatabase' => 'Suppression d\'une database',
		'ConfirmDatabase' => 'Êtes-vous sûr de vouloir supprimer la base de données <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Groupes non affectés à la base de données',
		'NonAffectedUsersDatabase' => 'Utilisateurs non affectés à la base de données',
		'Collaborators' => 'Collaborateurs',
		'Profiles' => 'Profils collaborateurs'
);
?>