<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$withdrawals = array(
		'CHARSET' => 'UTF-8',
		'StandingOrdersArea' => 'Házszabályok terület',
		'CustomersStandingOrdersArea' => 'Vásárlói házszabályok terület',
		'StandingOrders' => 'Házszabályok',
		'StandingOrder' => 'Házszabály',
		'NewStandingOrder' => 'Új Házszabály',
		'StandingOrderToProcess' => 'Feldolgozásához',
		'StandingOrderProcessed' => 'Feldolgozott',
		'Withdrawals' => 'Visszavonások',
		'Withdrawal' => 'Visszavonás',
		'WithdrawalsReceipts' => 'Visszavonási bizonylatok',
		'WithdrawalReceipt' => 'Visszavonási bizonylat',
		'WithdrawalReceiptShort' => 'Bizonylat',
		'LastWithdrawalReceipts' => '%s utolsó visszavonási bizonylatok',
		'WithdrawedBills' => 'Visszavont bizonylatok',
		'WithdrawalsLines' => 'Visszavonási sorok',
		'RequestStandingOrderToTreat' => 'Kérelem házszabályok kezelésére',
		'RequestStandingOrderTreated' => 'Request for standing orders treated',
		'CustomersStandingOrders' => 'Vásárlói házszabályok',
		'CustomerStandingOrder' => 'Vásárlói házszabály',
		'NbOfInvoiceToWithdraw' => 'Nb of invoice with withdraw request',
		'NbOfInvoiceToWithdrawWithInfo' => 'Nb a számlát visszavonja kérelmét rendelkező ügyfelek meghatározott bankszámlára vonatkozó információkat',
		'InvoiceWaitingWithdraw' => 'Visszavonásra váró bizonylat',
		'AmountToWithdraw' => 'Visszavonási mennyiség',
		'WithdrawsRefused' => 'Visszavonás elutasítva',
		'NoInvoiceToWithdraw' => 'No customer invoice in payment mode "withdraw" is waiting. Go on \'Withdraw\' tab on invoice card to make a request.',
		'ResponsibleUser' => 'Felelős felhasználó',
		'WithdrawalsSetup' => 'Visszavonás beállítás',
		'WithdrawStatistics' => 'Visszavonási statisztikák',
		'WithdrawRejectStatistics' => 'Visszavonás elutasitási statisztikák',
		'LastWithdrawalReceipt' => '%s utolsó visszavont bizonylatok',
		'MakeWithdrawRequest' => 'Visszavonási kérelem létrehozása',
		'ThirdPartyBankCode' => 'Harmadik fél Bank kód',
		'ThirdPartyDeskCode' => 'Harmadik fél asztal kód',
		'NoInvoiceCouldBeWithdrawed' => 'No invoice withdrawed with success. Check that invoice are on companies with a valid BAN.',
		'ClassCredited' => 'Jóváírtan osztályozva',
		'ClassCreditedConfirm' => 'Biztos, hogy jóvírtan akarja osztályozni a visszavonást a bankszámlájáról?',
		'TransData' => 'Dátum Átviteli',
		'TransMetod' => 'Átviteli módszer',
		'Send' => 'Küld',
		'Lines' => 'Vonalak',
		'StandingOrderReject' => 'Add ki egy visszautasító',
		'InvoiceRefused' => 'Számla visszautasította',
		'WithdrawalRefused' => 'Megtagadta visszavonása',
		'WithdrawalRefusedConfirm' => 'Biztosan meg szeretné adni a visszavonás elutasító a társadalom',
		'RefusedData' => 'Elutasításának napjától',
		'RefusedReason' => 'Az elutasítás indoka',
		'RefusedInvoicing' => 'Billing elutasítása',
		'NoInvoiceRefused' => 'Ne töltse az elutasítás',
		'InvoiceRefused' => 'Számla visszautasította',
		'Status' => 'Állapot',
		'StatusUnknown' => 'Ismeretlen',
		'StatusWaiting' => 'Várakozás',
		'StatusTrans' => 'Küldött',
		'StatusCredited' => 'Jóváírt',
		'StatusRefused' => 'Megtagadta',
		'StatusMotif0' => 'Meghatározatlan',
		'StatusMotif1' => 'Rendelkezni insuffisante',
		'StatusMotif2' => 'Conteste tirázs',
		'StatusMotif3' => 'Nem visszavonása érdekében',
		'StatusMotif4' => 'Az ügyfelek érdekében',
		'StatusMotif5' => 'RIB inexploitable',
		'StatusMotif6' => 'Számla nélküli egyenleg',
		'StatusMotif7' => 'Bírósági határozat',
		'StatusMotif8' => 'Egyéb ok',
		'CreateAll' => 'Visszavonja az összes',
		'CreateGuichet' => 'Csak az Office',
		'CreateBanque' => 'Csak a bank',
		'OrderWaiting' => 'Várakozás kezelés',
		'NotifyTransmision' => 'Felmondás Átviteli',
		'NotifyEmision' => 'Élelmezés-kibocsátás',
		'NotifyCredit' => 'Felmondás Hitel',
		'NumeroNationalEmetter' => 'Nemzeti Adó száma',
		'PleaseSelectCustomerBankBANToWithdraw' => 'Válassza ki információt ügyfél bankszámlájáról, hogy vonja vissza',
		'WithBankUsingRIB' => 'A bankszámlák segítségével RIB',
		'WithBankUsingBANBIC' => 'A bankszámlák segítségével IBAN / BIC / SWIFT',
		'BankToReceiveWithdraw' => 'Bankszámla kapni kilép',
		'CreditDate' => 'Hitelt',
		'WithdrawalFileNotCapable' => 'Nem sikerült létrehozni visszavonása kézhezvétele fájlt az Ön országában',
		'ShowWithdraw' => 'Mutasd Kifizetés',
		'IfInvoiceNeedOnWithdrawPaymentWontBeClosed' => 'Azonban, ha számlát legalább egy fizetési visszavonása még nem feldolgozott, akkor nem kell beállítani, hogy fizetni kell kezelni visszavonása előtt.',
		'DoStandingOrdersBeforePayments' => 'Ez a lap lehetővé teszi, hogy kérje a fennálló rendelés. Amint kész lesz, akkor írja be a fizetési zárja be a számlát.',
		////// Notifications
		'InfoCreditSubject' => 'Kifizetése érdekében állt a bank által %s',
		'InfoCreditMessage' => 'A folyamatos rendelés %s fizettek a bank által <br> Adatok fizetési: %s',
		'InfoTransSubject' => 'Továbbítása érdekében %s álló banki',
		'InfoTransMessage' => 'A folyamatos rendelés %s már transmited a bank %s %s. <br><br>',
		'InfoTransData' => 'Összeg: %s <br> Metode: %s <br> Dátum: %s',
		'InfoFoot' => 'Ez egy automatikus üzenetet küldött Speedealing',
		'InfoRejectSubject' => 'Állandó érdekében hajlandó',
		'InfoRejectMessage' => 'Helló, <br><br> Az állva sorrendben számla %s kapcsolatos %s cég, amelynek összege %s már elutasította a bank. <br><br> - <br> % $',
		'ModeWarning' => 'Opció a valós módban nem volt beállítva, akkor hagyja abba ezt követően szimuláció'
);
?>