<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$banks = array(
		'CHARSET' => 'UTF-8',
		'Bank' => 'בנק',
		'Banks' => 'הבנקים',
		'MenuBankCash' => 'בנק / מזומן',
		'MenuSetupBank' => 'בנק / מזומן ההתקנה',
		'BankName' => 'שם הבנק',
		'FinancialAccount' => 'חשבון',
		'FinancialAccounts' => 'חשבונות',
		'BankAccount' => 'חשבון הבנק',
		'BankAccounts' => 'חשבונות בנק',
		'AccountRef' => 'החשבון הפיננסי REF',
		'AccountLabel' => 'החשבון הפיננסי תווית',
		'CashAccount' => 'מזומנים בחשבון',
		'CashAccounts' => 'מזומנים חשבונות',
		'MainAccount' => 'ראשי החשבון',
		'CurrentAccount' => 'חשבון עובר ושב',
		'CurrentAccounts' => 'עו&quot;ש',
		'SavingAccount' => 'חשבון חיסכון',
		'SavingAccounts' => 'חיסכון חשבונות',
		'ErrorBankLabelAlreadyExists' => 'התווית החשבון הפיננסי כבר קיים',
		'BankBalance' => 'יתרה',
		'BalanceMinimalAllowed' => 'איזון מותר מינימום',
		'BalanceMinimalDesired' => 'האיזון הרצוי מינימום',
		'InitialBankBalance' => 'האיזון הראשוני',
		'EndBankBalance' => 'סוף איזון',
		'CurrentBalance' => 'יתרה נוכחית',
		'FutureBalance' => 'בעתיד איזון',
		'ShowAllTimeBalance' => 'הצג איזון מההתחלה',
		'Reconciliation' => 'פיוס',
		'RIB' => 'מספר חשבון בנק',
		'IBAN' => 'מספר IBAN',
		'BIC' => 'BIC / מספר SWIFT',
		'StandingOrders' => 'הוראות קבע',
		'StandingOrder' => 'פקודת קבע',
		'Withdrawals' => 'משיכות',
		'Withdrawal' => 'נסיגה',
		'AccountStatement' => 'חשבון הצהרה',
		'AccountStatementShort' => 'הצהרה',
		'AccountStatements' => 'החשבון לדוחות',
		'LastAccountStatements' => 'החשבון הצהרות אחרונות',
		'Rapprochement' => 'לפייס',
		'IOMonthlyReporting' => 'דיווח חודשי',
		'BankAccountDomiciliation' => 'חשבון כתובת',
		'BankAccountCountry' => 'חשבון המדינה',
		'BankAccountOwner' => 'שם בעל החשבון',
		'BankAccountOwnerAddress' => 'בעל חשבון כתובת',
		'RIBControlError' => 'בדיקת תקינות של ערכים נכשל. משמעות הדבר היא מידע עבור מספר חשבון זה לא שלם או לא (הסימון של הארץ, מספרים IBAN).',
		'CreateAccount' => 'צור חשבון',
		'NewAccount' => 'חשבון חדש',
		'NewBankAccount' => 'חשבון בנק חדש',
		'NewFinancialAccount' => 'החשבון הפיננסי החדש',
		'MenuNewFinancialAccount' => 'החשבון הפיננסי החדש',
		'NewCurrentAccount' => 'בחשבון השוטף חדש',
		'NewSavingAccount' => 'חשבון חדש חיסכון',
		'NewCashAccount' => 'מזומן לחשבון חדש',
		'EditFinancialAccount' => 'עריכת חשבון',
		'AccountSetup' => 'חשבונות כספיים ההתקנה',
		'SearchBankMovement' => 'חיפוש התנועה בגדה',
		'Debts' => 'חובות',
		'LabelBankCashAccount' => 'בנק או תווית במזומן',
		'AccountType' => 'סוג חשבון',
		'BankType0' => 'חשבון חיסכון',
		'BankType1' => 'כרטיס אשראי או חשבון נוכחי',
		'BankType2' => 'מזומנים בחשבון',
		'IfBankAccount' => 'אם חשבון הבנק',
		'AccountsArea' => 'חשבונות באזור',
		'AccountCard' => 'חשבון הכרטיס',
		'DeleteAccount' => 'למחוק את החשבון',
		'ConfirmDeleteAccount' => 'האם אתה בטוח שברצונך למחוק את החשבון הזה?',
		'Account' => 'חשבון',
		'ByCategories' => 'לפי קטגוריות',
		'ByRubriques' => 'לפי קטגוריות',
		'BankTransactionByCategories' => 'הבנק עסקאות לפי קטגוריות',
		'BankTransactionForCategory' => 'הבנק עסקאות <b>%s</b> הקטגוריה',
		'RemoveFromRubrique' => 'הסר קישור עם קטגוריה',
		'RemoveFromRubriqueConfirm' => 'האם אתה בטוח שברצונך להסיר את הקשר בין העסקה לבין קטגוריה?',
		'ListBankTransactions' => 'רשימת עסקאות בנקאיות',
		'IdTransaction' => 'העסקה מזהה',
		'BankTransactions' => 'הבנק עסקאות',
		'SearchTransaction' => 'חיפוש העסקה',
		'ListTransactions' => 'רשימת עסקאות',
		'ListTransactionsByCategory' => 'רשימת העסקה / קטגוריה',
		'TransactionsToConciliate' => 'עסקאות ליישב',
		'Conciliable' => 'ניתן ליישב',
		'Conciliate' => 'להשלים',
		'Conciliation' => 'פיוס',
		'ConciliationForAccount' => 'ליישב את החשבון הזה',
		'IncludeClosedAccount' => 'כוללים חשבונות סגורים',
		'OnlyOpenedAccount' => 'נפתחו רק חשבונות',
		'AccountToCredit' => 'חשבון האשראי',
		'AccountToDebit' => 'חשבון לחיוב',
		'DisableConciliation' => 'בטל תכונה פיוס עבור חשבון זה',
		'ConciliationDisabled' => 'פיוס תכונה מושבתת',
		'StatusAccountOpened' => 'פתח',
		'StatusAccountClosed' => 'סגור',
		'AccountIdShort' => 'מספר',
		'EditBankRecord' => 'עריכת רשומה',
		'LineRecord' => 'עסקה',
		'AddBankRecord' => 'הוסף העסקה',
		'AddBankRecordLong' => 'הוסף את העסקה באופן ידני',
		'ConciliatedBy' => 'השלימו ידי',
		'DateConciliating' => 'ליישב תאריך',
		'BankLineConciliated' => 'העסקה השלימו',
		'CustomerInvoicePayment' => 'לקוחות תשלום',
		'SupplierInvoicePayment' => 'הספק תשלום',
		'WithdrawalPayment' => 'הנסיגה תשלום',
		'SocialContributionPayment' => 'תרומה חברתית תשלום',
		'FinancialAccountJournal' => 'החשבון הפיננסי העת',
		'BankTransfer' => 'העברה בנקאית',
		'BankTransfers' => 'העברות בנקאיות',
		'TransferDesc' => 'העברה מחשבון אחד זה מזה, Speedealing אכתוב שתי רשומות (חיוב בחשבון מקור אשראי בחשבון היעד, של אותו סכום. תווית התאריך אותו ישמש עסקה זו)',
		'TransferFrom' => 'מן',
		'TransferTo' => 'אל',
		'TransferFromToDone' => 'העברת מ <b>%s</b> כדי <b>%s</b> של %s <b>%s</b> נרשמה.',
		'CheckTransmitter' => 'משדר',
		'ValidateCheckReceipt' => 'אמת זה קבלת הצ\'ק?',
		'ConfirmValidateCheckReceipt' => 'האם אתה בטוח שברצונך לאמת את קבלת הצ\'ק, השינוי לא יהיה אפשרי כאשר זה מתבצע?',
		'DeleteCheckReceipt' => 'מחק את קבלת הצ\'ק?',
		'ConfirmDeleteCheckReceipt' => 'האם אתה בטוח שברצונך למחוק זאת קבלת הצ\'ק?',
		'BankChecks' => 'הבנק בודק',
		'BankChecksToReceipt' => 'בדיקות מחכים הפיקדון',
		'ShowCheckReceipt' => 'הצג לבדוק קבלת הפיקדון',
		'NumberOfCheques' => 'Nb של הסימון',
		'DeleteTransaction' => 'מחק את העסקה',
		'ConfirmDeleteTransaction' => 'האם אתה בטוח שברצונך למחוק זאת העסקה?',
		'ThisWillAlsoDeleteBankRecord' => 'זה יהיה גם למחוק עסקאות בנקאיות שנוצר',
		'BankMovements' => 'תנועות',
		'CashBudget' => 'מזומנים תקציב',
		'PlannedTransactions' => 'עסקאות מתוכננות',
		'Graph' => 'גרפיקה',
		'ExportDataset_banque_1' => 'הבנק עסקאות הצהרת חשבון',
		'TransactionOnTheOtherAccount' => 'עסקה על חשבון השני',
		'TransactionWithOtherAccount' => 'העברת חשבון',
		'PaymentNumberUpdateSucceeded' => 'מספר תשלומים מעודכן בהצלחה',
		'PaymentNumberUpdateFailed' => 'מספר תשלומים לא יכול היה להיות מעודכן',
		'PaymentDateUpdateSucceeded' => 'התשלום נקבע לעדכן בהצלחה',
		'PaymentDateUpdateFailed' => 'התשלום לא יכול להיות מעודכן',
		'Transactions' => 'Transactions',
		'BankTransactionLine' => 'בנק העסקה',
		'AllAccounts' => 'כל בנק / מזומן חשבונות',
		'BackToAccount' => 'בחזרה לחשבון',
		'ShowAllAccounts' => 'הצג את כל החשבונות',
		'FutureTransaction' => 'עסקה futur. כל דרך לפייס.',
		'SelectChequeTransactionAndGenerate' => 'בחר / לסנן בדיקות על מנת לכלול את קבלת הפיקדון הסימון ולחץ על &quot;צור&quot;.',
		'InputReceiptNumber' => 'Choose the bank statement related with the conciliation. Use a sortable numeric value (such as, YYYYMM)',
		'EventualyAddCategory' => 'Eventually, specify a category in which to classify the records',
		'ToConciliate' => 'To conciliate?',
		'ThenCheckLinesAndConciliate' => 'Then, check the lines present in the bank statement and click'
);
?>