<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'מסחרי',
		'CommercialArea' => 'שטח מסחרי',
		'CommercialCard' => 'כרטיס מסחרי',
		'CustomerArea' => 'לקוחות באזור',
		'Customer' => 'לקוח',
		'Customers' => 'לקוחות',
		'Prospect' => 'פרוספקט',
		'Prospects' => 'הסיכויים',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'מחק את האירוע / משימה',
		'NewAction' => 'האירוע משימה חדשה /',
		'AddAction' => 'הוסף אירוע / פעילות',
		'AddAnAction' => 'הוסף אירוע / פעילות',
		'AddActionRendezVous' => 'הוסף אירוע Rendez-Vous',
		'Rendez-Vous' => 'מפגש',
		'ConfirmDeleteAction' => 'האם אתה בטוח שברצונך למחוק את האירוע / משימה?',
		'CardAction' => 'אירוע כרטיס',
		'PercentDone' => 'שלמה אחוז',
		'ActionOnCompany' => 'המשימה על החברה',
		'ActionOnContact' => 'משימה על קשר',
		'TaskRDV' => 'מפגשים',
		'TaskRDVWith' => 'פגישה עם %s',
		'ShowTask' => 'הצג המשימה',
		'ShowAction' => 'הצג האירוע',
		'ActionsReport' => 'אירועים מדווחים',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'נציג מכירות',
		'SalesRepresentatives' => 'נציגי מכירות',
		'SalesRepresentativeFollowUp' => 'נציג מכירות (מעקב)',
		'SalesRepresentativeSignature' => 'נציג מכירות (חתימה)',
		'CommercialInterlocutor' => 'מסחרי בן שיחו',
		'ErrorWrongCode' => 'קוד לא נכון',
		'NoSalesRepresentativeAffected' => 'לא נציג המכירות בפרט מושפעים',
		'ShowCustomer' => 'הצג הלקוח',
		'ShowProspect' => 'הצג את הסיכוי',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'רשימה של לקוחות פוטנציאליים',
		'ListOfCustomers' => 'רשימת הלקוחות',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => '%s האחרונים השלימו את משימות',
		'LastRecordedTasks' => 'משימות הקלטה אחרונה',
		'LastActionsToDo' => '%s האחרונים העתיקים פעולות שלא הושלמו',
		'DoneAndToDoActionsFor' => 'הושלם ולעשות אירועים עבור %s',
		'DoneAndToDoActions' => 'הושלם ולעשות אירועים',
		'DoneActions' => 'הושלם אירועים',
		'DoneActionsFor' => 'אירועים הושלם עבור %s',
		'ToDoActions' => 'שלם אירועים',
		'ToDoActionsFor' => 'אירועים שלמים עבור %s',
		'SendPropalRef' => 'שלח %s ההצעה מסחריים',
		'SendOrderRef' => 'שלח %s סדר',
		'StatusNotApplicable' => 'לא ישים',
		'StatusActionToDo' => 'לעשות',
		'StatusActionDone' => 'להשלים',
		'StatusActionInProcess' => 'בתהליך',
		'MyActionsAsked' => 'אירועים אני נרשם',
		'MyActionsToDo' => 'אירועים אני צריך לעשות',
		'MyActionsDone' => 'האירועים השפיעו לי',
		'TasksHistoryForThisContact' => 'אירועים עבור איש קשר זה',
		'LastProspectDoNotContact' => 'אין קשר',
		'LastProspectNeverContacted' => 'מעולם לא יצר קשר',
		'LastProspectToContact' => 'ליצירת קשר',
		'LastProspectContactInProcess' => 'צור בתהליך',
		'LastProspectContactDone' => 'צור עשה',
		'DateActionPlanned' => 'תאריך האירוע המתוכנן',
		'DateActionDone' => 'תאריך האירוע לעשות',
		'ActionAskedBy' => 'האירוע דווח',
		'ActionAffectedTo' => 'האירוע השפיע על',
		'ActionDoneBy' => 'האירוע נעשה על ידי',
		'ActionUserAsk' => 'דווח ע&quot;י',
		'ErrorStatusCantBeZeroIfStarted' => 'אם <b>&quot;תאריך ראוי&quot;</b> השדה מלא, הפעולה החלה (או גמר), כדי <b>\'סטטוס\'</b> שדה לא יכול להיות% 0%.',
		'ActionAC_TEL' => 'שיחת טלפון',
		'ActionAC_FAX' => 'שלח פקס',
		'ActionAC_PROP' => 'שלח הצעת בדואר',
		'ActionAC_EMAIL' => 'שלח',
		'ActionAC_RDV' => 'מפגשים',
		'ActionAC_FAC' => 'שלח החשבונית ללקוח בדואר',
		'ActionAC_REL' => 'שלח החשבונית ללקוח בדואר (תזכורת)',
		'ActionAC_CLO' => 'לסגור',
		'ActionAC_EMAILING' => 'שלח דוא&quot;ל המונית',
		'ActionAC_COM' => 'שלח הזמנת הלקוח באמצעות הדואר',
		'ActionAC_SHIP' => 'שלח משלוח בדואר',
		'ActionAC_SUP_ORD' => 'כדי לשלוח בדואר הספק',
		'ActionAC_SUP_INV' => 'שלח חשבונית הספק בדואר',
		'ActionAC_OTH' => 'אחר',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'פרוספקט מעמד',
		'DraftPropals' => 'לנסח הצעות מסחריות',
		'SearchPropal' => 'חיפוש הצעה מסחרית'
);
?>