<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$compta = array(
		'CHARSET' => 'UTF-8',
		'Accountancy' => 'הנהלת חשבונות',
		'AccountancyCard' => 'כרטיס הנהלת חשבונות',
		'Treasury' => 'משרד האוצר',
		'MenuFinancial' => 'כספי',
		'TaxModuleSetupToModifyRules' => 'עבור <a href="%s">ההתקנה מודול</a> לשנות כללים לחישוב',
		'OptionMode' => 'אפשרות ראיית חשבון',
		'OptionModeTrue' => 'אפשרות הכנסות כולל הוצאות',
		'OptionModeVirtual' => 'אפשרות בטענות חובות',
		'OptionModeTrueDesc' => 'בהקשר זה, המחזור מחושב על תשלומים (מועד תשלום). \ תוקף nThe הדמויות מובטחת רק אם הספר שמירה הוא בחן את הקלט / פלט על חשבונות באמצעות חשבוניות.',
		'OptionModeVirtualDesc' => 'בהקשר זה, המחזור מחושב על חשבוניות (תאריך תוקף). כאשר חשבוניות אלו נובעים, בין אם שולמו או לא, הם מופיעים בפלט המחזור.',
		'FeatureIsSupportedInInOutModeOnly' => 'זמין רק במצב קרדיטים למוצרי החוב ראיית חשבון (ראה מודול התצורה חשבונאות) תכונה',
		'VATReportBuildWithOptionDefinedInModule' => 'הסכומים המוצגים כאן מחושבים באמצעות כללים שהוגדרו על ידי הגדרת מודול מס.',
		'Param' => 'הגדרת',
		'RemainingAmountPayment' => 'תשלום יתרת הסכום:',
		'AmountToBeCharged' => 'הסכום הכולל לתשלום:',
		'AccountsGeneral' => 'חשבונות',
		'Account' => 'חשבון',
		'Accounts' => 'חשבונות',
		'Accountparent' => 'Account parent',
		'Accountsparent' => 'Accounts parent',
		'BillsForSuppliers' => 'חשבונות ספקים',
		'Income' => 'הכנסה',
		'Outcome' => 'הוצאה',
		'ReportInOut' => 'הכנסות / הוצאות',
		'ReportTurnover' => 'מחזור',
		'PaymentsNotLinkedToInvoice' => 'תשלומים לא צמודים כל חשבונית, כל כך לא קשור לשום צד שלישי',
		'PaymentsNotLinkedToUser' => 'תשלומים לא מקושר לכל משתמש',
		'Profit' => 'רווח',
		'Balance' => 'יתרה',
		'Debit' => 'חובה',
		'Credit' => 'אשראי',
		'Withdrawal' => 'נסיגה',
		'Withdrawals' => 'משיכות',
		'AmountHTVATRealReceived' => 'נטו אסף',
		'AmountHTVATRealPaid' => 'נטו ששולם',
		'VATToPay' => 'מע&quot;מ מוכרת',
		'VATReceived' => 'מע&quot;מ קיבל',
		'VATToCollect' => 'מע&quot;מ רכישות',
		'VATSummary' => 'מע&quot;מ מאזן',
		'LT2SummaryES' => 'IRPF מאזן',
		'VATPaid' => 'שילם מע&quot;מ',
		'LT2PaidES' => 'IRPF בתשלום',
		'LT2CustomerES' => 'IRPF מכירות',
		'LT2SupplierES' => 'IRPF רכישות',
		'VATCollected' => 'מע&quot;מ אסף',
		'ToPay' => 'לשלם',
		'ToGet' => 'לחזור',
		'TaxAndDividendsArea' => 'מס, הפרשות סוציאליות ושטח דיבידנדים',
		'SocialContribution' => 'תרומה חברתית',
		'SocialContributions' => 'תשלומים סוציאליים',
		'MenuTaxAndDividends' => 'מסים וחלוקת דיבידנד',
		'MenuSocialContributions' => 'תשלומים סוציאליים',
		'MenuNewSocialContribution' => 'חדש תרומה',
		'NewSocialContribution' => 'תרומה חברתית חדשה',
		'ContributionsToPay' => 'תרומות כדי לשלם',
		'AccountancyTreasuryArea' => 'חשבונאות / שטח האוצר',
		'AccountancySetup' => 'חשבונאות ההתקנה',
		'NewPayment' => 'חדש התשלום',
		'Payments' => 'תשלומים',
		'PaymentCustomerInvoice' => 'חשבונית הלקוח תשלום',
		'PaymentSupplierInvoice' => 'חשבונית הספק לתשלום',
		'PaymentSocialContribution' => 'תרומה חברתית תשלום',
		'PaymentVat' => 'תשלום מע&quot;מ',
		'ListPayment' => 'רשימת התשלומים',
		'ListOfPayments' => 'רשימת התשלומים',
		'ListOfCustomerPayments' => 'רשימת התשלומים של לקוחות',
		'ListOfSupplierPayments' => 'רשימת התשלומים הספק',
		'DatePayment' => 'תאריך תשלום',
		'NewVATPayment' => 'תשלום מע&quot;מ חדש',
		'newLT2PaymentES' => 'חדש התשלום IRPF',
		'LT2PaymentES' => 'IRPF תשלום',
		'LT2PaymentsES' => 'IRPF תשלומים',
		'VATPayment' => 'תשלום מע&quot;מ',
		'VATPayments' => 'מע&quot;מ תשלומים',
		'SocialContributionsPayments' => 'תשלומים סוציאליים תשלומים',
		'ShowVatPayment' => 'הצג תשלום מע&quot;מ',
		'TotalToPay' => 'סה&quot;כ לשלם',
		'TotalVATReceived' => 'מע&quot;מ סך הכל קיבל',
		'CustomerAccountancyCode' => 'הנהלת חשבונות לקוחות קוד',
		'SupplierAccountancyCode' => 'חשבון הספק קוד',
		'AlreadyPaid' => 'כבר שילם',
		'AccountNumberShort' => 'מספר חשבון',
		'AccountNumber' => 'מספר חשבון',
		'NewAccount' => 'חשבון חדש',
		'SalesTurnover' => 'מחזור המכירות',
		'ByThirdParties' => 'Bu צדדים שלישיים',
		'ByUserAuthorOfInvoice' => 'מחבר חשבונית',
		'AccountancyExport' => 'חשבונאות יצוא',
		'ErrorWrongAccountancyCodeForCompany' => 'לקוח רע ראיית חשבון קוד %s',
		'SuppliersProductsSellSalesTurnover' => 'מחזור שנוצר על ידי מכירות של מוצרים של ספקים.',
		'CheckReceipt' => 'בדוק הפיקדון',
		'CheckReceiptShort' => 'בדוק הפיקדון',
		'NewCheckReceipt' => 'חדש דיסקונט',
		'NewCheckDeposit' => 'הסימון החדש ההפקדה',
		'NewCheckDepositOn' => 'יצירת קבלה על הפקדה בחשבון: %s',
		'NoWaitingChecks' => 'המחאות לא מחכה ההפקדה.',
		'DateChequeReceived' => 'יש לבדוק את תאריך הקבלה',
		'NbOfCheques' => 'נ.ב. הצ\'קים',
		'PaySocialContribution' => 'לשלם תרומה חברתית',
		'ConfirmPaySocialContribution' => 'האם אתה בטוח שברצונך למיין את התרומה החברתית תשלום?',
		'DeleteSocialContribution' => 'מחיקת תרומה חברתית',
		'ConfirmDeleteSocialContribution' => 'האם אתה בטוח שברצונך למחוק זאת תרומה חברתית?',
		'ExportDataset_tax_1' => 'הפרשות סוציאליות ותשלומים',
		'AnnualSummaryDueDebtMode' => 'מאזן הכנסות והוצאות, סיכום שנתי, מצב <b>%sClaims למוצרי Debt%sS</b> אמר <b>חשבונאות מחויבות.</b>',
		'AnnualSummaryInputOutputMode' => 'מאזן הכנסות והוצאות, סיכום שנתי, מצב <b>%sIncomes למוצרי Expense%sS</b> אמר <b>חשבונאית במזומן.</b>',
		'AnnualByCompaniesDueDebtMode' => 'מאזן הכנסות והוצאות, פירוט על ידי צדדים שלישיים, מצב <b>%sClaims למוצרי Debt%sS</b> אמר <b>חשבונאות מחויבות.</b>',
		'AnnualByCompaniesInputOutputMode' => 'מאזן הכנסות והוצאות, פירוט על ידי צדדים שלישיים, מצב <b>%sIncomes למוצרי Expense%sS</b> אמר <b>חשבונאית במזומן.</b>',
		'SeeReportInInputOutputMode' => 'ראה דו&quot;ח <b>%sIncomes למוצרי Expense%sS</b> אמר <b>חשבונאית במזומן</b> לצורך חישוב על התשלומים בפועל עשה',
		'SeeReportInDueDebtMode' => 'ראה דו&quot;ח <b>%sClaims למוצרי Debt%sS</b> אמר <b>התחייבות חשבונאית</b> לחישוב על חשבוניות שהונפקו',
		'RulesResultDue' => '- הסכומים המוצגים הם עם כלל את כל המסים <br> - זה כולל חשבוניות יוצאות דופן, הוצאות ומע&quot;מ אם הם משתלמים או לא. <br> - הוא מבוסס על תאריך אימות של חשבוניות מע&quot;מ במועד בשל הוצאות.',
		'RulesResultInOut' => '- הסכומים המוצגים הם עם כלל את כל המסים <br> - זה כולל את תשלומי אמיתיים שנעשו על חשבוניות, הוצאות ומע&quot;מ. <br> - הוא מבוסס על תאריכי תשלום של חשבוניות מע&quot;מ, ANF הוצאות. <br>',
		'RulesCADue' => '- זה כולל חשבוניות בשל הלקוח בין אם הם משתלמים או לא. <br> - הוא מבוסס על תאריך אימות של חשבוניות אלה. <br>',
		'RulesCAIn' => '- זה כולל את כל התשלומים יעיל של חשבוניות שהתקבלו מלקוחות. <br> - הוא מבוסס על תאריך התשלום של חשבוניות אלה <br>',
		'DepositsAreNotIncluded' => '- חשבוניות הפקדה הם לא כלולים',
		'DepositsAreIncluded' => '- חשבוניות הפקדה כלולים',
		'LT2ReportByCustomersInInputOutputModeES' => 'דווח על ידי צד שלישי IRPF',
		'VATReportByCustomersInInputOutputMode' => 'דווח על ידי מע&quot;מ הלקוח אסף ושילם (קבלת מע&quot;מ)',
		'VATReportByCustomersInDueDebtMode' => 'דווח על ידי מע&quot;מ הלקוח אסף ושילם (שיעור המע&quot;מ)',
		'VATReportByQuartersInInputOutputMode' => 'דו&quot;ח של שיעור המע&quot;מ שנגבה ושילם (קבלת מע&quot;מ)',
		'VATReportByQuartersInDueDebtMode' => 'דו&quot;ח של שיעור המע&quot;מ שנגבה ושילם (שיעור המע&quot;מ)',
		'SeeVATReportInInputOutputMode' => 'ראה לדווח <b>encasement%s %sVAT</b> לחישוב תקן',
		'SeeVATReportInDueDebtMode' => 'ראה <b>%sVAT</b> דיווח <b>על flow%s</b> לחישוב עם אופציה על תזרים',
		'RulesVATInServices' => '- עבור שירותים, הדו&quot;ח כולל את תקנות מע&quot;מ שהתקבלו בפועל או שהונפקו על בסיס התשלום. <br> - לגבי נכסים חומריים, היא כוללת את חשבוניות מע&quot;מ על בסיס מתאריך החשבונית.',
		'RulesVATInProducts' => '- לגבי נכסים חומריים, היא כוללת את חשבוניות מע&quot;מ על בסיס מתאריך החשבונית.',
		'RulesVATDueServices' => '- עבור שירותים, הדו&quot;ח כולל חשבוניות מע&quot;מ בשל, בתשלום או לא, בהתבסס על תאריך החשבונית.',
		'RulesVATDueProducts' => '- לגבי נכסים חומריים, היא כוללת את חשבוניות מע&quot;מ, מחושב על סמך חשבונית.',
		'OptionVatInfoModuleComptabilite' => 'הערה: לקבלת נכסים חומריים, יש להשתמש מועד ההספקה להיות הוגן יותר.',
		'PercentOfInvoice' => '%% / חשבונית',
		'NotUsedForGoods' => 'לא נעשה שימוש על סחורות',
		'ProposalStats' => 'נתונים על ההצעות',
		'OrderStats' => 'נתונים על הזמנות',
		'InvoiceStats' => 'נתונים על חשבונות',
		'Dispatch' => 'שגור',
		'Dispatched' => 'נשלח',
		'ToDispatch' => 'לשלוח',
		'ThirdPartyMustBeEditAsCustomer' => 'צד שלישי חייב להיות מוגדר כלקוח',
		'SellsJournal' => 'מכירות Journal',
		'PurchasesJournal' => 'רכישות Journal',
		'DescSellsJournal' => 'מכירות Journal',
		'DescPurchasesJournal' => 'רכישות Journal',
		'InvoiceRef' => 'חשבונית השופט.',
		'CodeNotDef' => 'לא מוגדר',
		'AddRemind' => 'לשלוח כמות זמינה',
		'RemainToDivide' => 'להישאר לשלוח:',
		'WarningDepositsNotIncluded' => 'חשבוניות פיקדונות אינם כלולים בגרסה זו עם מודול זה ראיית חשבון.',
		'DatePaymentTermCantBeLowerThanObjectDate' => 'Payment term date can\'t be lower than object date.',
		'Pcg_version' => 'Pcg version',
		'Pcg_type' => 'Pcg type',
		'Pcg_subtype' => 'Pcg subtype',
		'Withdrawl' => 'Prélèvement',
		'Withdrawls' => 'Prélèvements',
		'ToGetBack' => 'A récupérer',
		'Journaux' => 'Journaux',
		'Piece' => 'Piece compta',
		'JournalNum' => 'Journal',
		'COMPTA_JOURNAL_SELL' => 'Numéro comptable du Journal des Achats',
		'COMPTA_JOURNAL_BUY' => 'Numéro comptable du Journal des Ventes',
		'COMPTA_PRODUCT_BUY_ACCOUNT' => 'Compte comptable par défaut pour produits achetés (si non défini sur fiche produit)',
		'COMPTA_PRODUCT_SOLD_ACCOUNT' => 'Compte comptable par défaut pour produits vendus (si non défini sur fiche produit)',
		'COMPTA_SERVICE_BUY_ACCOUNT' => 'Compte comptable par défaut pour services achetés (si non défini sur fiche service)',
		'COMPTA_SERVICE_SOLD_ACCOUNT' => 'Compte comptable par défaut pour services vendus (si non défini sur fiche service)',
		'COMPTA_VAT_ACCOUNT' => 'Compte comptable par défaut pour TVA (si non défini dans dictionnaire "Taux de TVA")',
		'COMPTA_ACCOUNT_CUSTOMER' => 'Compte comptable client par défaut (si non défini sur fiche tiers)',
		'COMPTA_ACCOUNT_SUPPLIER' => 'Compte comptable fournisseur par défaut (si non défini sur fiche tiers)',
);
?>