<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$install = array(
		'CHARSET' => 'UTF-8',
		'InstallEasy' => 'עקוב אחר ההוראות צעד אחר צעד.',
		'MiscellanousChecks' => 'תנאים מוקדמים לבדוק',
		'SpeedealingWelcome' => 'Welcome to Speedealing',
		'ConfFileExists' => 'קובץ <b>%s</b> תצורת קיים.',
		'ConfFileDoesNotExists' => 'קובץ <b>%s</b> תצורת לא קיים!',
		'ConfFileDoesNotExistsAndCouldNotBeCreated' => 'קבצים <b>%s</b> תצורה לא קיים ולא יכול להיווצר!',
		'ConfFileCouldBeCreated' => 'קבצים <b>%s</b> תצורה יכול להיווצר.',
		'ConfFileIsNotWritable' => 'קבצים <b>%s</b> תצורה אינו ניתן לכתיבה. בדוק את ההרשאות. עבור ההתקנה הראשונה, שרת האינטרנט צריך לקבל כדי להיות מסוגל לכתוב לתוך קובץ זה במהלך תהליך קביעת התצורה (&quot;chmod 666&quot;, למשל על יוניקס כמו מערכת הפעלה).',
		'ConfFileIsWritable' => 'קובץ <b>%s</b> תצורת הוא ניתן לכתיבה.',
		'ConfFileReload' => 'רענן כל מידע מקובץ התצורה.',
		'PHPSupportSessions' => 'PHP זה תומך מפגשים.',
		'PHPSupportPOSTGETOk' => 'PHP זה תומך משתנים POST ו-GET.',
		'PHPSupportPOSTGETKo' => 'יכול להיות ההתקנה PHP שלך אינו תומך משתנים POST ו / או GET. בדוק <b>variables_order</b> הפרמטר שלך php.ini.',
		'PHPSupportGD' => 'תמיכה זו PHP פונקציות אלוקים גרפיים.',
		'PHPSupportUTF8' => 'תמיכה זו PHP פונקציות UTF8.',
		'PHPMemoryOK' => 'זיכרון PHP ​​שלך מקס הפגישה מוגדרת <b>%s.</b> זה אמור להספיק.',
		'PHPMemoryTooLow' => 'זיכרון PHP ​​שלך מקס הפגישה מוגדרת בתים <b>%s.</b> זה צריך להיות נמוך מדי. שנה <b>php.ini</b> שלך להגדיר פרמטר <b>memory_limit</b> לפחות בתים <b>%s.</b>',
		'Recheck' => 'לחץ כאן למבחן significative יותר',
		'ErrorPHPDoesNotSupportSessions' => 'התקנת PHP שלך לא תומך מפגשים. תכונה זו נדרש כדי להפוך את העבודה Speedealing. בדוק את הגדרות PHP שלך.',
		'ErrorPHPDoesNotSupportGD' => 'התקנת PHP שלך לא תומך בפונקציה GD גרפי. הגרף לא תהיה זמינה.',
		'ErrorPHPDoesNotSupportUTF8' => 'התקנת PHP שלך לא תומך בפונקציות UTF8. Speedealing לא יכול לעבוד בצורה נכונה. לפתור את זה לפני ההתקנה Speedealing.',
		'ErrorDirDoesNotExists' => '%s הספרייה לא קיימת.',
		'ErrorGoBackAndCorrectParameters' => 'ללכת אחורה ולתקן את הפרמטרים הלא נכונים.',
		'ErrorWrongValueForParameter' => 'ייתכן הקלדת ערך שגוי לפרמטר &quot;%s&quot;.',
		'ErrorFailedToCreateDatabase' => 'נכשל נסיון ליצור &quot;%s&quot; מסד הנתונים.',
		'ErrorFailedToConnectToDatabase' => 'נכשל נסיון להתחבר &quot;%s&quot; מסד הנתונים.',
		'ErrorDatabaseVersionTooLow' => 'Database version (%s) too old. Version %s or higher is required.',
		'ErrorPHPVersionTooLow' => 'PHP גרסה ישנה מדי. %s גרסה נדרשת.',
		'WarningPHPVersionTooLow' => 'PHP גרסה ישנה מדי. %s גרסה או יותר צפוי. גרסה זו אמורה לאפשר להתקין אך לא נתמך.',
		'ErrorConnectedButDatabaseNotFound' => 'חיבור לשרת מוצלחת אבל לא &quot;%s של מסד הנתונים נמצא.',
		'ErrorDatabaseAlreadyExists' => '&quot;%s&quot; מסד הנתונים כבר קיים.',
		'IfDatabaseNotExistsGoBackAndUncheckCreate' => 'אם מסד הנתונים אינו קיים, לחזור ולבדוק את האפשרות &quot;צור מסד נתונים&quot;.',
		'IfDatabaseExistsGoBackAndCheckCreate' => 'אם מסד הנתונים כבר קיים, לחזור ולהוריד את הסימון &quot;צור מסד נתונים&quot; אפשרות.',
		'WarningBrowserTooOld' => 'גרסה ישנה יותר של הדפדפן. שדרוג הדפדפן לגרסה האחרונה של פיירפוקס, כרום או אופרה הוא מומלצים מאוד.',
		'PHPVersion' => 'PHP Version',
		'YouCanContinue' => 'אתה יכול להמשיך ...',
		'PleaseBePatient' => 'אנא המתן בסבלנות ...',
		'License' => 'באמצעות רישיון',
		'ConfigurationFile' => 'תצורת הקובץ',
		'WebPagesDirectory' => 'הספרייה שבה דפי אינטרנט מאוחסנים',
		'DocumentsDirectory' => 'מדריך לאחסון מסמכים שנטענו שנוצר',
		'URLRoot' => 'כתובת האתר רוט',
		'ForceHttps' => 'לכפות חיבורים מאובטחים (HTTPS)',
		'CheckToForceHttps' => 'לבדוק אפשרות זו כדי לכפות חיבורים מאובטחים (HTTPS). <br> פעולה זו דורשת שרת האינטרנט מוגדר עם תעודת SSL.',
		'SpeedealingDatabase' => 'Speedealing Database',
		'DatabaseChoice' => 'בחירת בסיס נתונים',
		'DatabaseType' => 'מסד נתונים מסוג',
		'DriverType' => 'הנהג סוג',
		'Server' => 'שרת',
		'ServerAddressDescription' => 'שם או כתובת IP של שרת מסד הנתונים, בדרך כלל \'localhost\', כאשר שרת מסד הנתונים מאוחסן על אותו שרת מ שרת האינטרנט',
		'ServerPortDescription' => 'יציאת שרת בסיס הנתונים. שמור על ריק אם לא ידוע.',
		'DatabaseServer' => 'שרת מסד הנתונים',
		'DatabaseName' => 'שם מסד הנתונים',
		'DatabasePrefix' => 'קידומת מסד הנתונים בטבלה',
		'Login' => 'כניסה',
		'AdminLogin' => 'כניסה לבעל מסד הנתונים Speedealing.',
		'Password' => 'סיסמה',
		'PasswordAgain' => 'הקלד שוב את הסיסמה פעם נוספת',
		'AdminPassword' => 'הסיסמה של מסד הנתונים בעל Speedealing.',
		'CreateDatabase' => 'יצירת מסד נתונים',
		'CreateUser' => 'צור הבעלים',
		'DatabaseSuperUserAccess' => 'שרת מסד הנתונים - משתמש על גישה',
		'CheckToCreateDatabase' => 'תיבת הסימון אם מסד הנתונים אינו קיים יש ליצור. <br> במקרה זה, עליך למלא כניסה / הסיסמה של חשבון משתמש על בתחתית דף זה.',
		'CheckToCreateUser' => 'תיבת הסימון אם בעל מסד הנתונים אינו קיים יש ליצור. <br> במקרה זה, עליך לבחור הכניסה שלו וסיסמה וגם למלא כניסה / הסיסמה של חשבון משתמש על בתחתית דף זה. אם התיבה מסומנת באתר זה, הבעלים סיסמאות שלה חייב קיים.',
		'Experimental' => '(ניסיוני)',
		'DatabaseRootLoginDescription' => 'כניסה של המשתמש רשאי ליצור מסדי נתונים חדשים או משתמשים חדשים, חסר תועלת אם מסד הנתונים שלך ואת ההתחברות מסד הנתונים כבר קיים (כמו כשאתה מתארח על ידי ספק אירוח אתרים).',
		'KeepEmptyIfNoPassword' => 'השאר ריק אם המשתמש אין סיסמה (למנוע זאת)',
		'SaveConfigurationFile' => 'שמירת ערכי',
		'ConfigurationSaving' => 'תצורת שמירת הקובץ',
		'ServerConnection' => 'שרת חיבור',
		'DatabaseConnection' => 'מסד נתונים חיבור',
		'DatabaseCreation' => 'יצירת מסד נתונים',
		'UserCreation' => 'יצירת משתמש',
		'CreateDatabaseObjects' => 'יצירת אובייקטי מסד נתונים',
		'ReferenceDataLoading' => 'נתונים הפניה הטעינה',
		'TablesAndPrimaryKeysCreation' => 'לוחות ראשי יצירת מפתחות',
		'CreateTableAndPrimaryKey' => 'צור %s שולחן',
		'CreateOtherKeysForTable' => 'יצירת מפתחות זרים ואינדקסים עבור %s שולחן',
		'OtherKeysCreation' => 'המפתחות חוץ יצירת אינדקסים',
		'FunctionsCreation' => 'פונקציות היצירה',
		'AdminAccountCreation' => 'כניסה למנהל היצירה',
		'PleaseTypePassword' => 'יש להקליד סיסמה, סיסמאות ריקות אסור!',
		'PleaseTypeALogin' => 'אנא הקלד התחברות!',
		'PasswordsMismatch' => 'סיסמאות שונה, אנא נסה שוב!',
		'SetupEnd' => 'סוף ההתקנה',
		'SystemIsInstalled' => 'התקנה זו היא מוחלטת.',
		'SystemIsUpgraded' => 'Speedealing שודרג בהצלחה.',
		'YouNeedToPersonalizeSetup' => 'אתה צריך להגדיר Speedealing בהתאם לצרכיך (מראה, תכונות, ...). לשם כך, אנא לחץ על הקישור למטה:',
		'AdminLoginCreatedSuccessfuly' => '<b>&quot;%s&quot;</b> Speedealing מנהל ההתחברות נוצר בהצלחה.',
		'GoToSpeedealing' => 'Go to Speedealing',
		'GoToSetupArea' => 'עבור Speedealing (באזור ההתקנה)',
		'MigrationNotFinished' => 'גרסה של מסד הנתונים שלך הוא לא לגמרי מעודכן, אז תצטרך להפעיל את תהליך השדרוג מחדש.',
		'GoToUpgradePage' => 'עבור לדף לשדרג שוב',
		'Examples' => 'דוגמאות',
		'WithNoSlashAtTheEnd' => 'ללא קו נטוי &quot;/&quot; על הקצה',
		'DirectoryRecommendation' => 'היא מומלצים להשתמש במדריך מחוץ המדריך שלך של דפי האינטרנט שלך.',
		'LoginAlreadyExists' => 'כבר קיים',
		'SpeedealingAdminLogin' => 'Speedealing admin login',
		'AdminLoginAlreadyExists' => '<b>&quot;%s&quot;</b> Speedealing חשבון מנהל כבר קיים. נחזור, אם אתה רוצה ליצור עוד אחד.',
		'WarningRemoveInstallDir' => 'אזהרה, מסיבות ביטחוניות, לאחר ההתקנה או השדרוג, עליך להסיר את <b>ספריית ההתקנה או להוסיף קובץ בשם install.lock לתוך ספריית מסמכים Speedealing, כדי למנוע שימוש זדוני ממנו.</b>',
		'ThisPHPDoesNotSupportTypeBase' => 'זו מערכת PHP אינו תומך באף ממשק גישה מסוג %s באתר',
		'FunctionNotAvailableInThisPHP' => 'לא זמין זה PHP',
		'MigrateScript' => 'הגירה התסריט',
		'ChoosedMigrateScript' => 'בחר סקריפט הגירה',
		'DataMigration' => 'העברת נתונים',
		'DatabaseMigration' => 'באתר מבנה ההגירה',
		'ProcessMigrateScript' => 'התסריט לעיבוד',
		'ChooseYourSetupMode' => 'בחר מצב ההתקנה ולחץ על &quot;התחל&quot; ...',
		'FreshInstall' => 'טרי התקנה',
		'FreshInstallDesc' => 'השתמש במצב זה אם זו ההתקנה הראשונה שלך. אם לא, מצב זה יכול לתקן את התקנה הקודמת לא מושלם, אבל אם אתם רוצים לשדרג את הגירסה שלך, לבחור במצב &quot;שדרוג&quot;.',
		'Upgrade' => 'שדרוג',
		'UpgradeDesc' => 'השתמש במצב זה אם להחליף קבצים Speedealing ישנים עם קבצים בגירסה חדשה יותר. זה יהיה לשדרג את מסד הנתונים ונתונים.',
		'Start' => 'להפעיל',
		'InstallNotAllowed' => 'ההתקנה לא שמאפשר הרשאות <b>conf.php</b>',
		'NotAvailable' => 'לא זמין',
		'YouMustCreateWithPermission' => 'עליך ליצור %s קבצים ולהגדיר הרשאות כתיבה על אותה עבור שרת האינטרנט במהלך תהליך ההתקנה.',
		'CorrectProblemAndReloadPage' => 'נא לתקן את הבעיה ולחץ F5 לטעון מחדש דף.',
		'AlreadyDone' => 'כבר היגרו',
		'DatabaseVersion' => 'גרסת מסד נתונים',
		'ServerVersion' => 'שרת מסד הנתונים לגרסה',
		'YouMustCreateItAndAllowServerToWrite' => 'עליך ליצור את הספרייה ולאפשר לשרת האינטרנט לכתוב לתוכו.',
		'CharsetChoice' => 'התווים הבחירה',
		'CharacterSetClient' => 'התווים המשמש שנוצר דפי אינטרנט ב-HTML',
		'CharacterSetClientComment' => 'בחר בערכת התווים להצגה באינטרנט. <br/> מערכת המוצעת מחדל הדמות היא זו של מסד הנתונים.',
		'CollationConnection' => 'מיון תו כדי',
		'CollationConnectionComment' => 'בחר קוד מקור המגדיר סדר המיון של הדמות בשימוש על ידי מסד הנתונים. פרמטר זה נקרא גם &quot;איסוף&quot; של כמה מסדי נתונים. <br/> פרמטר זה לא ניתן להגדיר אם מסד הנתונים כבר קיים.',
		'CharacterSetDatabase' => 'התווים עבור מסד הנתונים',
		'CharacterSetDatabaseComment' => 'בחר בערכת התווים רצה ליצירת מסד הנתונים. <br/> פרמטר זה לא ניתן להגדיר אם מסד הנתונים כבר קיים.',
		'YouAskDatabaseCreationSoSpeedealingNeedToConnect' => 'You ask to create database <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'YouAskLoginCreationSoSpeedealingNeedToConnect' => 'You ask to create database login <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'BecauseConnectionFailedParametersMayBeWrong' => 'כחיבור נכשל, המארח או פרמטרים משתמש סופר חייב להיות לא בסדר.',
		'OrphelinsPaymentsDetectedByMethod' => 'התשלום ליתומים זוהה על ידי %s השיטה',
		'RemoveItManuallyAndPressF5ToContinue' => 'הסר אותו באופן ידני ולחץ על F5 כדי להמשיך.',
		'KeepDefaultValuesWamp' => 'ניתן להשתמש באשף ההגדרה Speedealing מ DoliWamp, אז הערכים המוצעים כאן מותאמים כבר. לשנות אותם רק אם אתה יודע מה שאתה עושה.',
		'KeepDefaultValuesDeb' => 'ניתן להשתמש באשף ההגדרה Speedealing מחבילה לינוקס (אובונטו, דביאן, פדורה ...), אז הערכים המוצעים כאן מותאמים כבר. רק הסיסמה של בעל מסד הנתונים כדי ליצור יש להשלים. שינוי פרמטרים אחרים רק אם אתה יודע מה שאתה עושה.',
		'KeepDefaultValuesMamp' => 'ניתן להשתמש באשף ההגדרה Speedealing מ DoliMamp, אז הערכים המוצעים כאן מותאמים כבר. לשנות אותם רק אם אתה יודע מה שאתה עושה.',
		'KeepDefaultValuesProxmox' => 'ניתן להשתמש באשף ההגדרה Speedealing ממכשיר Proxmox וירטואלי, אז הערכים המוצעים כאן מותאמים כבר. לשנות אותם רק אם אתה יודע מה שאתה עושה.',
		'FieldRenamed' => 'שדה שמם',
		'IfLoginDoesNotExistsCheckCreateUser' => 'אם הכניסה אינה קיימת עדיין, אתה חייב לבדוק את האפשרות &quot;צור משתמש&quot;',
		'ErrorConnection' => 'שרת <b>&quot;%s&quot;,</b> שם מסד הנתונים <b>&quot;%s&quot;,</b> הכניסה <b>&quot;%s&quot;,</b> או את הסיסמה מסד הנתונים עשוי להיות שגוי או גרסה הלקוח PHP יכול להיות זקן מדי בהשוואה לגרסה מסד הנתונים.',
		'InstallChoiceRecommanded' => 'הבחירה מומלץ להתקין גרסה <b>%s</b> מ <b>%s</b> הנוכחיות גרסה',
		'InstallChoiceSuggested' => '<b>התקן הבחירה שהציע המתקין.</b>',
		'MigrateIsDoneStepByStep' => 'גרסה ממוקדת (%s) יש פער של מספר גירסאות, אז להתקין אשף יחזור להציע ההגירה פעם הבאה זה יסתיים.',
		'CheckThatDatabasenameIsCorrect' => 'בדוק שם מסד הנתונים <b>&quot;%s&quot;</b> נכון.',
		'IfAlreadyExistsCheckOption' => 'אם שם זה נכון מסד נתונים אינו קיים עדיין, יש לבדוק אפשרות &quot;צור מסד נתונים&quot;.',
		'OpenBaseDir' => 'PHP פרמטר openbasedir',
		'YouAskToCreateDatabaseSoRootRequired' => 'בדקת את תיבת &quot;צור מסד נתונים&quot;. בשביל זה, אתה צריך לספק כניסה / סיסמה של משתמש על (בתחתית הטופס).',
		'YouAskToCreateDatabaseUserSoRootRequired' => 'בדקת את תיבת &quot;צור הבעלים של מסד הנתונים&quot;. בשביל זה, אתה צריך לספק כניסה / סיסמה של משתמש על (בתחתית הטופס).',
		'NextStepMightLastALongTime' => 'הצעד הנוכחי עשוי להימשך מספר דקות. אנא המתן עד המסך הבא מוצג לחלוטין לפני שתמשיך.',
		'LastStepDesc' => '<strong>השלב האחרון:</strong> הגדרת כאן שם המשתמש והסיסמה אתה מתכוון להשתמש להתחבר לתוכנה. לא לאבד את זה כפי שהוא חשבון לנהל את כל האחרים.',
		'ActivateModule' => 'להפעיל את מודול %s',
		'ShowEditTechnicalParameters' => 'Click here to show/edit advanced parameters (expert mode)',
		'ServerPortCouchdbDescription' => 'Port du serveur. Défaut 5984.',
		'ServerAddressCouchdbDescription' => 'Nom FQDN du serveur de base de données, \'localhost.localdomain\' quand le serveur est installé sur la même machine que le serveur web',
		'DatabaseCouchdbUserDescription' => 'Login du super administrateur ayant tous les droits sur le serveur CouchDB ou l\'administrateur propriétaire de la base si la base et son compte d\'accès existent déjà (comme lorsque vous êtes chez un hébergeur).<br><br><div class="alert-box info">Cet utilisateur/mot de passe sera l\'administrateur pour se connecter à Speedealing.</div>',
		'CheckToCreateCouchdbDatabase' => 'Cochez cette option si la base de données n\'existe pas et doit être créée.',
		'CreateAdminUser' => 'Créer le super administrateur (Première installation de couchDB)',
		'MemcachedDescription' => 'Activer Memcached necessite l\'installation d\'un serveur Memcached et des lib php-memcached ou php-memcache. Il peut être activer après l\'installation.',
		'ServerAddressMemcachedDesc' => 'Nom ou adresse ip du serveur memcached, généralement \'localhost\' quand le serveur est installé sur la même machine que le serveur web',
		'ServerPortMemcachedDesc' => 'Port du serveur memcached. Défaut : 11211',
		'EnabledMemcached' => 'Activer Memcached',
		'DatabaseNoSQL' => 'Base de données CouchDB',
		'FailedToCreateAdminLogin' => 'Echec de la création du compte administrateur Speedealing.',
		'LinkedElementsInvalidDeleted' => '<b>%s</b> liaisons invalides ont été supprimées',
		'NothingToDelete' => 'Aucune liaison invalide trouvée',
		'SourceType' => 'Source',
		'TargetType' => 'Cible'
);
?>