<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$other = array(
		'CHARSET' => 'UTF-8',
		'SecurityCode' => 'קוד אבטחה',
		'Calendar' => 'לוח שנה',
		'AddTrip' => 'הוסף הנסיעה',
		'Tools' => 'כלים',
		'ToolsDesc' => 'אזור זה מוקדש כלים קבוצתיות שונות לא זמין לתוך התפריט ערכים אחרים. <br><br> כלים אלה ניתן להגיע מהתפריט בצד.',
		'Birthday' => 'יום הולדת',
		'BirthdayDate' => 'יום הולדת',
		'DateToBirth' => 'תאריך הלידה',
		'BirthdayAlertOn' => 'יום הולדת התראה פעילה',
		'BirthdayAlertOff' => 'יום ההולדת פעיל התראה',
		'Notify_FICHINTER_VALIDATE' => 'התערבות תוקף',
		'Notify_BILL_VALIDATE' => 'חשבונית ללקוח תוקף',
		'Notify_ORDER_SUPPLIER_APPROVE' => 'כדי ספק מאושר',
		'Notify_ORDER_SUPPLIER_REFUSE' => 'סדר הספק סירב',
		'Notify_ORDER_VALIDATE' => 'סדר לקוחות תוקף',
		'Notify_PROPAL_VALIDATE' => 'הצעת לקוחות תוקף',
		'Notify_WITHDRAW_TRANSMIT' => 'שידור הנסיגה',
		'Notify_WITHDRAW_CREDIT' => 'אשראי הנסיגה',
		'Notify_WITHDRAW_EMIT' => 'לבצע נסיגה',
		'Notify_ORDER_SENTBYMAIL' => 'לקוחות על מנת לשלוח בדואר',
		'Notify_COMPANY_CREATE' => 'הצד השלישי יצר',
		'Notify_PROPAL_SENTBYMAIL' => 'הצעה מסחרית לשלוח בדואר',
		'Notify_ORDER_SENTBYMAIL' => 'לקוחות על מנת לשלוח בדואר',
		'Notify_BILL_PAYED' => 'חשבונית הלקוח שילם',
		'Notify_BILL_CANCEL' => 'חשבונית הלקוח ביטל',
		'Notify_BILL_SENTBYMAIL' => 'לקוחות החשבונית בדואר',
		'Notify_ORDER_SUPPLIER_VALIDATE' => 'הספק כדי תוקף',
		'Notify_ORDER_SUPPLIER_SENTBYMAIL' => 'הספק על מנת לשלוח בדואר',
		'Notify_BILL_SUPPLIER_VALIDATE' => 'הספק חשבונית תוקף',
		'Notify_BILL_SUPPLIER_PAYED' => 'חשבונית הספק שילם',
		'Notify_BILL_SUPPLIER_SENTBYMAIL' => 'הספק חשבונית בדואר',
		'Notify_CONTRACT_VALIDATE' => 'תוקף החוזה',
		'Notify_FICHEINTER_VALIDATE' => 'התערבות תוקף',
		'Notify_SHIPPING_VALIDATE' => 'משלוח תוקף',
		'Notify_SHIPPING_SENTBYMAIL' => 'משלוח בדואר',
		'Notify_MEMBER_VALIDATE' => 'חבר תוקף',
		'Notify_MEMBER_SUBSCRIPTION' => 'משתמש רשום',
		'Notify_MEMBER_RESILIATE' => 'חבר resiliated',
		'Notify_MEMBER_DELETE' => 'המשתמש נמחק',
		'NbOfAttachedFiles' => 'מספר קבצים / מסמכים מצורפים',
		'TotalSizeOfAttachedFiles' => 'הגודל הכולל של הקבצים / מסמכים מצורפים',
		'MaxSize' => 'גודל מרבי של',
		'AttachANewFile' => 'צירוף קובץ מסמך חדש /',
		'LinkedObject' => 'אובייקט מקושר',
		'Miscellanous' => 'שונות',
		'NbOfActiveNotifications' => 'מספר הודעות',
		'PredefinedMailTest' => 'זהו אלקטרוני הבדיקה. \ NThe שני קווים מפרידים בהחזרת גררה.',
		'PredefinedMailTestHtml' => 'זהו אלקטרוני <b>המבחן</b> (מבחן מילה חייב להיות מודגש). <br> שני קווים מפרידים בהחזרת גררה.',
		'PredefinedMailContentSendInvoice' => 'You will find here the invoice __FACREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendInvoiceReminder' => 'We would like to warn you that the invoice  __FACREF__ seems to not being payed. So this is the invoice in attachment again, as a reminder.\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendProposal' => 'You will find here the commercial propoal __PROPREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendOrder' => 'You will find here the order __ORDERREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierOrder' => 'You will find here our order __ORDERREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierInvoice' => 'You will find here the invoice __FACREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendShipping' => 'You will find here the shipping __SHIPPINGREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendFichInter' => 'You will find here the intervention __FICHINTERREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'DemoDesc' => 'Speedealing היא קומפקטית ERP / CRM שהלחין מודולים פונקציונליים שונים. הדגמה הכוללת את כל מודולי לא אומר כלום כי זה לא עולה. אז, כמה פרופילים הדגמה זמינים.',
		'ChooseYourDemoProfil' => 'בחר את הפרופיל הדגמה התואמים את הפעילות שלך ...',
		'DemoFundation' => 'נהל את חברי קרן',
		'DemoFundation2' => 'ניהול חברים ו חשבון בנק של הקרן',
		'DemoCompanyServiceOnly' => 'ניהול פעילות עצמאי שירות ומכירה בלבד',
		'DemoCompanyShopWithCashDesk' => 'ניהול חנות עם שולחן במזומן',
		'DemoCompanyProductAndStocks' => 'ניהול מכירת מוצרים קטנים או בינוניים החברה',
		'DemoCompanyAll' => 'ניהול חברה קטנה או בינונית עם פעילויות רבות (כל המודולים העיקריים)',
		'GoToDemo' => 'עבור הדגמה',
		'CreatedBy' => 'נוצר על ידי %s',
		'ModifiedBy' => 'שונה על ידי %s',
		'ValidatedBy' => 'מאומת על ידי %s',
		'CanceledBy' => 'בוטל על ידי %s',
		'ClosedBy' => 'סגור %s',
		'FileWasRemoved' => '%s הקובץ הוסר',
		'DirWasRemoved' => '%s מדריך הוסר',
		'FeatureNotYetAvailableShort' => 'זמין בגירסה הבאה',
		'FeatureNotYetAvailable' => 'התכונה עדיין לא זמינה בגרסה זו',
		'FeatureExperimental' => 'תכונה ניסיונית. לא יציבה בגרסה זו',
		'FeatureDevelopment' => 'פיתוח תכונה. לא יציבה בגרסה זו',
		'FeaturesSupported' => 'התכונות הנתמכות',
		'Width' => 'רוחב',
		'Height' => 'גובה',
		'Depth' => 'עומק',
		'Top' => 'ראש',
		'Bottom' => 'תחתית',
		'Left' => 'עזבו',
		'Right' => 'נכון',
		'CalculatedWeight' => 'מחושב משקל',
		'CalculatedVolume' => 'לפי חישוב נפח',
		'Weight' => 'משקל',
		'TotalWeight' => 'משקל כללי',
		'WeightUnitton' => 'טון',
		'WeightUnitkg' => 'ק&quot;ג',
		'WeightUnitg' => 'g',
		'WeightUnitmg' => 'מ&quot;ג',
		'WeightUnitpound' => 'פאונד',
		'Length' => 'משך',
		'LengthUnitm' => 'מ \'',
		'LengthUnitdm' => 'DM',
		'LengthUnitcm' => 'ס&quot;מ',
		'LengthUnitmm' => 'מ&quot;מ',
		'Surface' => 'אזור',
		'SurfaceUnitm2' => 'M2',
		'SurfaceUnitdm2' => 'dm2',
		'SurfaceUnitcm2' => 'CM2',
		'SurfaceUnitmm2' => 'mm2',
		'SurfaceUnitfoot2' => 'ft2',
		'SurfaceUnitinch2' => 'in2',
		'Volume' => 'נפח',
		'TotalVolume' => 'סה&quot;כ נפח',
		'VolumeUnitm3' => 'M3',
		'VolumeUnitdm3' => 'dm3',
		'VolumeUnitcm3' => 'cm3',
		'VolumeUnitmm3' => 'mm3',
		'VolumeUnitfoot3' => 'ft3',
		'VolumeUnitinch3' => 'in3',
		'VolumeUnitounce' => 'אונקיה',
		'VolumeUnitlitre' => 'ליטר',
		'VolumeUnitgallon' => 'גלון',
		'Size' => 'גודל',
		'SizeUnitm' => 'מ \'',
		'SizeUnitdm' => 'DM',
		'SizeUnitcm' => 'ס&quot;מ',
		'SizeUnitmm' => 'מ&quot;מ',
		'SizeUnitinch' => 'אינטש',
		'SizeUnitfoot' => 'רגל',
		'SizeUnitpoint' => 'point',
		'BugTracker' => 'גשש באג',
		'SendNewPasswordDesc' => 'טופס זה מאפשר לך לבקש סיסמה חדשה. זה יהיה לשלוח את כתובת הדוא&quot;ל שלך. <br> השינוי ייכנס לתוקף רק לאחר לחיצה על הקישור אישור בתוך לדוא&quot;ל זה. <br> בדוק התוכנה הקורא הדוא&quot;ל שלך.',
		'BackToLoginPage' => 'לגבות להתחבר לדף',
		'AuthenticationDoesNotAllowSendNewPassword' => 'מצב אימות הוא <b>%s.</b> <br> במצב זה, Speedealing לא יכול לדעת וגם לא לשנות את הסיסמה שלך. <br> צרו קשר עם מנהל המערכת שלך אם אתה רוצה לשנות את הסיסמה שלך.',
		'EnableGDLibraryDesc' => 'להתקין או להפעיל את ספריית GD עם PHP שלך להשתמש באפשרות זו.',
		'EnablePhpAVModuleDesc' => 'אתה צריך להתקין מודול תואם את האנטי וירוס שלך. (ClamAV: PHP4 clamavlib-ou-PHP5 clamavlib)',
		'ProfIdShortDesc' => '<b>פרופ \'עיד %s</b> הוא מידע בהתאם למדינה של צד שלישי. <br> לדוגמה, עבור <b>%s</b> המדינה, זה <b>%s</b> קוד.',
		'SpeedealingDemo' => 'Speedealing ERP/CRM demo',
		'StatsByNumberOfUnits' => 'סטטיסטיקה של מספר מוצרים / שירותים יחידות',
		'StatsByNumberOfEntities' => 'סטטיסטיקה של מספר גופים המתייחסים',
		'NumberOfProposals' => 'מספר הצעות על החודש האחרון 12',
		'NumberOfCustomerOrders' => 'מספר הזמנות של לקוחות לעומת החודש האחרון 12',
		'NumberOfCustomerInvoices' => 'מספר חשבונות של לקוחות כל חודש 12 האחרון',
		'NumberOfSupplierInvoices' => 'מספר חשבוניות הספקים על 12 חודש שעבר',
		'NumberOfUnitsProposals' => 'מספר יחידות על הצעות על החודש האחרון 12',
		'NumberOfUnitsCustomerOrders' => 'מספר יחידות על הזמנות של לקוחות לעומת החודש האחרון 12',
		'NumberOfUnitsCustomerInvoices' => 'מספר יחידות על חשבוניות של לקוחות לעומת החודש האחרון 12',
		'NumberOfUnitsSupplierInvoices' => 'מספר יחידות על חשבוניות ספקים על החודש האחרון 12',
		'EMailTextInterventionValidated' => '%s התערבות קיבל תוקף.',
		'EMailTextInvoiceValidated' => '%s החשבונית קיבל תוקף.',
		'EMailTextProposalValidated' => '%s ההצעה קיבל תוקף.',
		'EMailTextOrderValidated' => '%s מנת קיבל תוקף.',
		'EMailTextOrderApproved' => '%s כדי אושרה.',
		'EMailTextOrderApprovedBy' => '%s כדי אושרה על ידי %s.',
		'EMailTextOrderRefused' => '%s כדי סורב.',
		'EMailTextOrderRefusedBy' => '%s כדי סורב על ידי %s.',
		'ImportedWithSet' => 'נתוני היבוא, שנקבעים',
		'SpeedealingNotification' => 'Automatic notification',
		'ResizeDesc' => 'הזן רוחב <b>או</b> גובה חדש חדש. יחס יישמר במהלך שינוי גודל ...',
		'NewLength' => 'חדש רוחב',
		'NewHeight' => 'גובה חדש',
		'NewSizeAfterCropping' => 'גודל לאחר חיתוך חדש',
		'DefineNewAreaToPick' => 'הגדרת תחום חדש על התמונה כדי לבחור (שמאל לחץ על התמונה ולאחר מכן גרור עד שתגיע את הפינה הנגדית)',
		'CurrentInformationOnImage' => 'כלי זה נועד לעזור לכם לשנות את גודל או לחתוך את התמונה. זהו ידיעות על התמונה נערך הנוכחי',
		'ImageEditor' => 'תמונה עורך',
		'YouReceiveMailBecauseOfNotification' => 'אתה מקבל הודעה כי הדוא&quot;ל שלך נוספה רשימת מטרות יעודכנו אירועים מסוימים לתוך התוכנה %s של %s.',
		'YouReceiveMailBecauseOfNotification2' => 'אירוע זה הוא:',
		'ThisIsListOfModules' => 'זוהי רשימה של המודולים שנבחרו מראש על ידי הפרופיל של הדמו (רק המודולים הנפוצים ביותר הם גלויים הדגמה זו). עריכה זו כדי הדגמה אישית יותר ולחץ על &quot;התחל&quot;.',
		'ClickHere' => 'לחץ כאן',
		'UseAdvancedPerms' => 'שימוש בהרשאות מתקדמות של מודולים מסוימים',
		'FileFormat' => 'קובץ בפורמט',
		'SelectAColor' => 'בחירת צבע',
		'AddFiles' => 'הוסף קבצים',
		'StartUpload' => 'להתחיל להעלות',
		'CancelUpload' => 'ביטול להעלות',
		'FileIsTooBig' => 'קבצים גדול מדי',
		'PleaseBePatient' => 'Please be patient...',
		////////// Calendar common //////////
		'AddCalendarEntry' => 'הוסף רשומה בלוח השנה %s',
		'NewCompanyToSpeedealing' => 'Company %s added into Speedealing',
		'ContractValidatedInSpeedealing' => 'Contract %s validated in Speedealing',
		'ContractCanceledInSpeedealing' => 'Contract %s canceled in Speedealing',
		'ContractClosedInSpeedealing' => 'Contract %s closed in Speedealing',
		'PropalClosedSignedInSpeedealing' => 'Proposal %s signed in Speedealing',
		'PropalClosedRefusedInSpeedealing' => 'Proposal %s refused in Speedealing',
		'PropalValidatedInSpeedealing' => 'Proposal %s validated in Speedealing',
		'InvoiceValidatedInSpeedealing' => 'Invoice %s validated in Speedealing',
		'InvoicePaidInSpeedealing' => 'Invoice %s changed to paid in Speedealing',
		'InvoiceCanceledInSpeedealing' => 'Invoice %s canceled in Speedealing',
		'PaymentDoneInSpeedealing' => 'Payment %s done in Speedealing',
		'CustomerPaymentDoneInSpeedealing' => 'Customer payment %s done in Speedealing',
		'SupplierPaymentDoneInSpeedealing' => 'Supplier payment %s done in Speedealing',
		'MemberValidatedInSpeedealing' => 'Member %s validated in Speedealing',
		'MemberResiliatedInSpeedealing' => 'Member %s resiliated in Speedealing',
		'MemberDeletedInSpeedealing' => 'Member %s deleted from Speedealing',
		'MemberSubscriptionAddedInSpeedealing' => 'Subscription for member %s added in Speedealing',
		'ShipmentValidatedInSpeedealing' => 'Shipment %s validated in Speedealing',
		////////// Export //////////
		'Export' => 'יצוא',
		'ExportsArea' => 'יצוא שטח',
		'AvailableFormats' => 'זמין פורמטים',
		'LibraryUsed' => 'Librairy שימוש',
		'LibraryVersion' => 'גרסה',
		'ExportableDatas' => 'לייצוא הנתונים',
		'NoExportableData' => 'אין נתונים לייצוא (אין מודולים עם נתונים לייצוא טעון או הרשאות חסרים)',
		'ToExport' => 'יצוא',
		'NewExport' => 'חדש לייצוא',
		////////// External sites //////////
		'ExternalSites' => 'אתרים חיצוניים'
);
?>