<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'המחסן כרטיס',
		'Warehouse' => 'מחסן',
		'Warehouses' => 'Warehouses',
		'NewWarehouse' => 'תחום חדש מחסן / צילומים',
		'WarehouseEdit' => 'שנה במחסן',
		'MenuNewWarehouse' => 'מחסן חדש',
		'WarehouseOpened' => 'המחסן נפתח',
		'WarehouseClosed' => 'המחסן סגור',
		'WarehouseSource' => 'מקור מחסן',
		'WarehouseSourceNotDefined' => 'No warehouse defined,',
		'AddOne' => 'Add one',
		'WarehouseTarget' => 'המטרה של Google',
		'ValidateSending' => 'מחק את שליחת',
		'CancelSending' => 'ביטול שליחת',
		'DeleteSending' => 'מחק את שליחת',
		'Stock' => 'מניות',
		'Stocks' => 'מניות',
		'Movement' => 'תנועה',
		'Movements' => 'תנועות',
		'ErrorWarehouseRefRequired' => 'שם מחסן התייחסות נדרש',
		'ErrorWarehouseLabelRequired' => 'תווית של Google נדרש',
		'CorrectStock' => 'נכון במלאי',
		'ListOfWarehouses' => 'רשימת מחסנים',
		'ListOfStockMovements' => 'רשימה של תנועות מלאי',
		'StocksArea' => 'מניות אזור',
		'Location' => 'מקום',
		'LocationSummary' => 'שם קצר מיקום',
		'NumberOfProducts' => 'המספר הכולל של מוצרים',
		'LastMovement' => 'לאחרונה התנועה',
		'LastMovements' => 'תנועות אחרונות',
		'Units' => 'יחידות',
		'Unit' => 'יחידה',
		'StockCorrection' => 'נכון במלאי',
		'StockMovement' => 'להעביר',
		'StockMovements' => 'מניות העברות',
		'NumberOfUnit' => 'מספר יחידות',
		'UnitPurchaseValue' => 'Unit purchase price',
		'TotalStock' => 'סך כל המניות',
		'StockTooLow' => 'המניה נמוך מדי',
		'StockLowerThanLimit' => 'Stock lower than alert limit',
		'EnhancedValue' => 'ערך',
		'PMPValue' => 'מחיר ממוצע משוקלל',
		'PMPValueShort' => 'WAP',
		'EnhancedValueOfWarehouses' => 'מחסני ערך',
		'UserWarehouseAutoCreate' => 'צור מחסן אוטומטי בעת יצירת משתמש',
		'QtyDispatched' => 'כמות שיגר',
		'OrderDispatch' => 'המניות שיגור',
		'RuleForStockManagementDecrease' => 'כלל לירידה ניהול מלאי',
		'RuleForStockManagementIncrease' => 'כלל לעלייה ניהול מלאי',
		'DeStockOnBill' => 'ירידה במניות אמיתיות על חשבוניות לקוחות / הערות אימות אשראי',
		'DeStockOnValidateOrder' => 'ירידה במניות אמיתיות על אימות הזמנות הלקוחות',
		'DeStockOnShipment' => 'ירידה במניות אמיתיות על אימות המשלוח',
		'ReStockOnBill' => 'הגדל את מניות אמיתיים על חשבוניות ספקים / הערות אימות אשראי',
		'ReStockOnValidateOrder' => 'הגדל את מניות אמיתיים על הסכמה הזמנות ספקים',
		'ReStockOnDispatchOrder' => 'הגדל את מניות אמיתיים על המדריך שיגרו אל מחסני הספק, לאחר קבלת צו',
		'OrderStatusNotReadyToDispatch' => 'סדר עדיין לא, אם בכלל, יותר מעמד המאפשר שיגור של מוצרים במחסנים מלאי.',
		'StockDiffPhysicTeoric' => 'הסיבה המניות ההבדל הפיזי תיאורטי',
		'NoPredefinedProductToDispatch' => 'אין מוצרים מוגדרים מראש עבור אובייקט זה. אז לא שגור במלאי נדרשת.',
		'DispatchVerb' => 'לשגר',
		'StockLimitShort' => 'להגביל',
		'StockLimit' => 'המניות הגבול התראות',
		'PhysicalStock' => 'פיזית המניה',
		'RealStock' => 'נדל במלאי',
		'TheoreticalStock' => 'Therocial המניות',
		'VirtualStock' => 'Virtual המניות',
		'MininumStock' => 'מינימום המניות',
		'StockUp' => 'להכין מלאי',
		'MininumStockShort' => 'המניות דקות',
		'StockUpShort' => 'להכין מלאי',
		'IdWarehouse' => 'Id מחסן',
		'DescWareHouse' => 'תיאור מחסן',
		'LieuWareHouse' => 'Localisation מחסן',
		'WarehousesAndProducts' => 'מחסני ומוצרים',
		'AverageUnitPricePMPShort' => 'מחיר הכניסה הממוצע המשוקלל',
		'AverageUnitPricePMP' => 'מחיר הכניסה הממוצע המשוקלל',
		'SellPriceMin' => 'מכירת מחיר ליחידה',
		'EstimatedStockValueSellShort' => 'ערך למכור',
		'EstimatedStockValueSell' => 'ערך למכור',
		'EstimatedStockValueShort' => 'מניות ערך קלט',
		'EstimatedStockValue' => 'מניות ערך קלט',
		'DeleteAWarehouse' => 'מחיקת מחסן',
		'ConfirmDeleteWarehouse' => 'האם אתה בטוח שברצונך למחוק את <b>%s</b> מחסן?',
		'PersonalStock' => 'מניות %s אישיים',
		'ThisWarehouseIsPersonalStock' => 'מחסן זה מייצג המניות האישי של %s %s',
		'SelectWarehouseForStockDecrease' => 'בחר מחסן לשימוש ירידה במלאי',
		'SelectWarehouseForStockIncrease' => 'בחר במחסן להשתמש לעלייה במלאי',
		'LastWaitingSupplierOrders' => 'Orders waiting for receptions'
);
?>