<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'כרטיס המשתמש',
		'ContactCard' => 'צור כרטיס',
		'GroupCard' => 'קבוצת כרטיס',
		'NoContactCard' => 'אין כרטיס בקרב אנשי קשר',
		'Permission' => 'רשות',
		'Permissions' => 'הרשאות',
		'EditPassword' => 'ערוך את הסיסמה',
		'SendNewPassword' => 'לחדש ולשלוח את הסיסמה',
		'ReinitPassword' => 'לחדש את הסיסמה',
		'PasswordChangedTo' => 'סיסמה שונה: %s',
		'SubjectNewPassword' => 'הסיסמה החדשה של Speedealing',
		'AvailableRights' => 'זמין הרשאות',
		'OwnedRights' => 'בבעלות הרשאות',
		'GroupRights' => 'קבוצת הרשאות',
		'UserRights' => 'הרשאות משתמש',
		'UserGUISetup' => 'התצוגה המשתמש ההתקנה',
		'DisableUser' => 'השבת',
		'DisableAUser' => 'בטל המשתמש',
		'DeleteUser' => 'למחוק',
		'DeleteAUser' => 'מחק את המשתמש',
		'DisableGroup' => 'השבת',
		'DisableAGroup' => 'בטל קבוצה',
		'EnableAUser' => 'לאפשר למשתמש',
		'EnableAGroup' => 'אפשר הקבוצה',
		'DeleteGroup' => 'למחוק',
		'DeleteAGroup' => 'מחיקת קבוצה',
		'ConfirmDisableUser' => 'האם אתה בטוח שברצונך להשבית <b>%s</b> משתמש?',
		'ConfirmDisableGroup' => 'האם אתה בטוח שברצונך להשבית <b>%s</b> הקבוצה?',
		'ConfirmDeleteUser' => 'האם אתה בטוח שברצונך למחוק <b>%s</b> משתמש?',
		'ConfirmDeleteGroup' => 'האם אתה בטוח שברצונך למחוק <b>%s</b> הקבוצה?',
		'ConfirmEnableUser' => 'האם אתה בטוח שברצונך להפעיל <b>%s</b> משתמש?',
		'ConfirmEnableGroup' => 'האם אתה בטוח שברצונך להפעיל <b>%s</b> הקבוצה?',
		'ConfirmReinitPassword' => 'האם אתה בטוח שברצונך ליצור סיסמה חדשה עבור המשתמש <b>%s?</b>',
		'ConfirmSendNewPassword' => 'האם אתה בטוח שברצונך ליצור ולשלוח סיסמה חדשה עבור המשתמש <b>%s?</b>',
		'NewUser' => 'משתמש חדש',
		'CreateUser' => 'צור משתמש',
		'SearchAGroup' => 'חיפוש קבוצה',
		'SearchAUser' => 'חיפוש משתמש',
		'LoginNotDefined' => 'כניסה לא מוגדרת.',
		'NameNotDefined' => 'שם לא מוגדר.',
		'ListOfUsers' => 'רשימת משתמשים',
		'Administrator' => 'מנהל',
		'SuperAdministrator' => 'סופר מנהל',
		'SuperAdministratorDesc' => 'מנהל גלובלי',
		'AdministratorDesc' => 'המנהל הראשי של הישות',
		'DefaultRights' => 'ברירת המחדל של הרשאות',
		'DefaultRightsDesc' => 'הגדרת הרשאות <u>ברירת המחדל</u> כאן הניתנות באופן אוטומטי המשתמש <u>החדש שנוצר</u> (קדימה כרטיס המשתמש לשנות הרשאות של משתמש קיים).',
		'SpeedealingUsers' => 'Speedealing users',
		'LastName' => 'שם',
		'FirstName' => 'שם פרטי',
		'ListOfGroups' => 'רשימת קבוצות',
		'NewGroup' => 'קבוצה חדשה',
		'CreateGroup' => 'צור קבוצה',
		'RemoveFromGroup' => 'הסר מהקבוצה',
		'PasswordChangedAndSentTo' => 'שינוי סיסמה ונשלח <b>%s.</b>',
		'PasswordChangeRequestSent' => 'בקשה לשנות את הסיסמה עבור <b>%s</b> שנשלחו <b>%s.</b>',
		'MenuUsersAndGroups' => 'משתמשים &amp; \'קבוצות\'',
		'LastGroupsCreated' => '%s האחרונות יצרו קבוצות',
		'LastUsersCreated' => 'משתמשים %s האחרונות נוצר',
		'ShowGroup' => 'הצג הקבוצה',
		'ShowUser' => 'הצג המשתמש',
		'NonAffectedUsers' => 'משתמשים שאינם מושפעים',
		'UserModified' => 'המשתמש שונה בהצלחה',
		'GroupModified' => 'קבוצה שונה בהצלחה',
		'PhotoFile' => 'קובץ תמונה',
		'UserWithSpeedealingAccess' => 'User with Speedealing access',
		'ListOfUsersInGroup' => 'רשימת משתמשים בקבוצה זו',
		'ListOfGroupsForUser' => 'רשימת קבוצות עבור משתמש זה',
		'UsersToAdd' => 'למשתמשים להוסיף לקבוצה זו',
		'GroupsToAdd' => 'קבוצות להוסיף משתמש זה',
		'NoLogin' => 'אין כניסה',
		'LinkToCompanyContact' => 'קישור לצד מגע 3 /',
		'LinkedToSpeedealingMember' => 'Link to member',
		'LinkedToSpeedealingUser' => 'Link to Speedealing user',
		'LinkedToSpeedealingThirdParty' => 'Link to Speedealing third party',
		'CreateSpeedealingLogin' => 'Create a user',
		'CreateSpeedealingThirdParty' => 'Create a third party',
		'LoginAccountDisable' => 'חשבון לא זמין, את הכניסה החדשה כדי להפעיל אותו.',
		'LoginAccountDisableInSpeedealing' => 'Account disabled in Speedealing.',
		'LoginAccountDisableInLdap' => 'חשבון נכים בתחום.',
		'UsePersonalValue' => 'השתמש בערך אישי',
		'GuiLanguage' => 'שפת ממשק',
		'InternalUser' => 'פנימית המשתמש',
		'MyInformations' => 'הנתונים שלי',
		'ExportDataset_user_1' => 'Speedealing של משתמשים ומאפיינים',
		'DomainUser' => 'המשתמש בתחום %s',
		'Reactivate' => 'מחדש',
		'CreateInternalUserDesc' => 'טופס זה מאפשר לך Creat משתמש פנימי לחברה שלך / קרן. כדי creat משתמש חיצוני (, לקוחות הספק, ...), יש להשתמש בלחצן \'צור המשתמש Speedealing\' מכרטיס מגע של צד ג\'.',
		'InternalExternalDesc' => 'משתמש <b>פנימי</b> הוא משתמש, כי הוא חלק של החברה שלך / קרן. <br> משתמש <b>חיצוני</b> הוא, לקוחות הספק או אחר. <br><br> בשני המקרים, הרשאות מגדיר הזכויות על Speedealing, גם משתמש חיצוני יכול להיות מנהל התפריט שונה משתמש פנימי (ראה בית - התקנה - תצוגה)',
		'PermissionInheritedFromAGroup' => 'ההרשאה שניתנה, כי בירושה מאחד קבוצה של המשתמש.',
		'Inherited' => 'בירושה',
		'UserWillBeInternalUser' => 'המשתמש נוצר יהיה משתמש פנימי (כי לא קשור לצד שלישי מסוים)',
		'UserWillBeExternalUser' => 'המשתמש נוצר יהיה משתמש חיצוני (צמוד כי לצד שלישי מסוים)',
		'IdPhoneCaller' => 'טלפון שיחה מזוהה',
		'UserLogged' => 'משתמש %s התחברות',
		'UserLogoff' => '%s משתמש להתנתקות',
		'NewUserCreated' => '%s המשתמש שנוצר',
		'NewUserPassword' => 'שינוי סיסמה עבור %s',
		'EventUserModified' => '%s משתמש שונה',
		'UserDisabled' => '%s משתמשים זמינה',
		'UserEnabled' => '%s משתמש פעיל',
		'UserDeleted' => '%s המשתמש הוסר',
		'NewGroupCreated' => '%s הקבוצה נוצר',
		'GroupModified' => 'קבוצה שונה בהצלחה',
		'GroupDeleted' => '%s קבוצה הוסר',
		'ConfirmCreateContact' => 'האם אתה בטוח שברצונך ליצור חשבון Speedealing עבור איש קשר זה?',
		'ConfirmCreateLogin' => 'האם אתה בטוח שברצונך ליצור חשבון Speedealing עבור משתמש זה?',
		'ConfirmCreateThirdParty' => 'האם אתה בטוח שברצונך ליצור צד שלישי עבור משתמש זה?',
		'LoginToCreate' => 'כניסה כדי ליצור',
		'NameToCreate' => 'שמו של צד שלישי כדי ליצור',
		'YourRole' => 'התפקידים שלך',
		'YourQuotaOfUsersIsReached' => 'המכסה שלך המשתמשים הפעילים הוא הגיע!',
		'NbOfUsers' => 'Nb של משתמשים',
		'DontDowngradeSuperAdmin' => 'רק superadmin בדרגה יכול superadmin',
		'NewDatabase' => 'Nouvelle base de données',
		'CreateDatabase' => 'Créer la base de données',
		'ListOfDatabases' => 'Liste des bases de données',
		'ListOfUsersInDatabase' => 'Liste des utilisateurs liés à la base de données',
		'ListOfRolesInDatabase' => 'Liste des groupes liés à la base de données',
		'DeleteADatabase' => 'Suppression d\'une database',
		'ConfirmDatabase' => 'Êtes-vous sûr de vouloir supprimer la base de données <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Groupes non affectés à la base de données',
		'NonAffectedUsersDatabase' => 'Utilisateurs non affectés à la base de données',
		'Collaborators' => 'Collaborateurs',
		'Profiles' => 'Profils collaborateurs'
);
?>