<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$banks = array(
		'CHARSET' => 'UTF-8',
		'Bank' => 'Bank',
		'Banks' => 'Banken',
		'MenuBankCash' => 'Bank / Kas',
		'MenuSetupBank' => 'Bank / Kas setup',
		'BankName' => 'Banknaam',
		'FinancialAccount' => 'Rekening',
		'FinancialAccounts' => 'Rekeningen',
		'BankAccount' => 'Bankrekening',
		'BankAccounts' => 'Bankrekeningen',
		'AccountRef' => 'Financiële rekening ref',
		'AccountLabel' => 'Label financiële rekening',
		'CashAccount' => 'Kasrekening',
		'CashAccounts' => 'Kasrekeningen',
		'MainAccount' => 'Hoofdrekening',
		'CurrentAccount' => 'Lopende rekening',
		'CurrentAccounts' => 'Lopende rekeningen',
		'SavingAccount' => 'Spaarrekening',
		'SavingAccounts' => 'Spaarrekeningen',
		'ErrorBankLabelAlreadyExists' => 'Label financiële rekening bestaat al',
		'BankBalance' => 'Saldo',
		'BalanceMinimalAllowed' => 'Minimum toegestaan saldo',
		'BalanceMinimalDesired' => 'Minimum gewenst saldo',
		'InitialBankBalance' => 'Beginsaldo',
		'EndBankBalance' => 'Eindsaldo',
		'CurrentBalance' => 'Huidig saldo',
		'FutureBalance' => 'Toekomstig saldo',
		'ShowAllTimeBalance' => 'Toon saldo van start',
		'Reconciliation' => 'Reconciliation',
		'RIB' => 'Bankrekeningnummer',
		'IBAN' => 'IBAN-nummer',
		'BIC' => 'BIC / SWIFT-nummer',
		'StandingOrders' => 'Vaste opdrachten',
		'StandingOrder' => 'Vaste opdracht',
		'Withdrawals' => 'Intrekkingen',
		'Withdrawal' => 'Intrekking',
		'AccountStatement' => 'Rekeningoverzicht',
		'AccountStatementShort' => 'Rekeningoverzicht',
		'AccountStatements' => 'Rekeningafschriften',
		'LastAccountStatements' => 'Laatste rekeningafschriften',
		'Rapprochement' => 'Reconciliate',
		'IOMonthlyReporting' => 'Maandelijkse rapportage',
		'BankAccountDomiciliation' => 'Bank adres',
		'BankAccountCountry' => 'Account country',
		'BankAccountOwner' => 'Rekeninghouder naam',
		'BankAccountOwnerAddress' => 'Rekeninghouder adres',
		'RIBControlError' => 'Integrity check of values fails. This means information for this account number are not complete or wrong (check country, numbers and IBAN).',
		'CreateAccount' => 'Maak rekening',
		'NewAccount' => 'Nieuw rekening',
		'NewBankAccount' => 'Nieuwe bankrekening',
		'NewFinancialAccount' => 'Nieuwe financiële rekening',
		'MenuNewFinancialAccount' => 'Nieuwe financiële rekening',
		'NewCurrentAccount' => 'Nieuwe lopende rekening',
		'NewSavingAccount' => 'Nieuwe spaarrekening',
		'NewCashAccount' => 'Nieuwe kasrekening',
		'EditFinancialAccount' => 'Aanmaken account',
		'AccountSetup' => 'Setup financiële rekeningen',
		'SearchBankMovement' => 'Zoek bankbeweging',
		'Debts' => 'Schulden',
		'LabelBankCashAccount' => 'Bank of Kas label',
		'AccountType' => 'Type rekening',
		'BankType0' => 'Spaarrekening',
		'BankType1' => 'Lopende rekening',
		'BankType2' => 'Kasrekening',
		'IfBankAccount' => 'Als bankrekening',
		'AccountsArea' => 'Rekeningen gebied',
		'AccountCard' => 'Rekening kaart',
		'DeleteAccount' => 'Rekening verwijderen',
		'ConfirmDeleteAccount' => 'Weet u zeker dat u deze rekening wilt verwijderen?',
		'Account' => 'Rekening',
		'ByCategories' => 'Per categorie',
		'ByRubriques' => 'Per categorie',
		'BankTransactionByCategories' => 'Bank transacties per categorie',
		'BankTransactionForCategory' => 'Bank transacties categorie <b>%s</b>',
		'RemoveFromRubrique' => 'Verwijder link met de categorie',
		'RemoveFromRubriqueConfirm' => 'Weet u zeker dat u de link tussen de transactie en de categorie wilt verwijderen?',
		'ListBankTransactions' => 'Lijst van de banktransacties',
		'IdTransaction' => 'Transactie ID',
		'BankTransactions' => 'Banktransacties',
		'SearchTransaction' => 'Zoek transactie',
		'ListTransactions' => 'Lijst transacties',
		'ListTransactionsByCategory' => 'Lijst transacties per categorie',
		'TransactionsToConciliate' => 'Transacties te bemiddelen',
		'Conciliable' => 'Bemiddelbaar',
		'Conciliate' => 'Bemiddelen',
		'Conciliation' => 'Bemiddeling',
		'ConciliationForAccount' => 'Bemiddel deze account',
		'IncludeClosedAccount' => 'Voeg gesloten rekeningen toe',
		'OnlyOpenedAccount' => 'Alleen geopende rekeningen',
		'AccountToCredit' => 'Rekening te krediteren',
		'AccountToDebit' => 'Rekening te debiteren',
		'DisableConciliation' => 'Schakel bemiddelingsfunctie uit voor deze rekening',
		'ConciliationDisabled' => 'Bemiddelingsfunctie uitgeschakeld',
		'StatusAccountOpened' => 'Geopend',
		'StatusAccountClosed' => 'Gesloten',
		'AccountIdShort' => 'Aantal',
		'EditBankRecord' => 'Bewerk record',
		'LineRecord' => 'Transactie',
		'AddBankRecord' => 'Toevoegen transactie',
		'AddBankRecordLong' => 'Handmatig transactie toevoegen',
		'ConciliatedBy' => 'Na bemiddeling door',
		'DateConciliating' => 'Bemiddelingsdatum',
		'BankLineConciliated' => 'Transactie na bemiddeling',
		'CustomerInvoicePayment' => 'Klant betaling',
		'SupplierInvoicePayment' => 'Leverancier betaling',
		'WithdrawalPayment' => 'Withdrawal payment',
		'SocialContributionPayment' => 'Sociale bijdragen betalen',
		'FinancialAccountJournal' => 'Journaal financiële rekening',
		'BankTransfer' => 'Bankoverschrijving',
		'BankTransfers' => 'Bankoverschrijvingen',
		'TransferDesc' => 'Overdracht van de ene rekening naar een andere, Speedealing zal twee records schrijven(een debitering in bron-account en een krediet in rekening doelgroep, van hetzelfde bedrag. Hetzelfde label en datum zal worden gebruikt voor deze transactie)',
		'TransferFrom' => 'Van',
		'TransferTo' => 'Aan',
		'TransferFromToDone' => 'Een overdracht van <b>%s</b> naar <b>%s</b> van <b>%s</b> %s is opgenomen.',
		'CheckTransmitter' => 'Zender',
		'ValidateCheckReceipt' => 'Valideer deze cheque ontvangst?',
		'ConfirmValidateCheckReceipt' => 'Weet u zeker dat u deze cheque wilt valideren voor ontvangst? Geen verandering is mogelijk eens dit is gebeurd!',
		'DeleteCheckReceipt' => 'Verwijder deze cheque ontvangst?',
		'ConfirmDeleteCheckReceipt' => 'Weet u zeker dat u deze cheque ontvangst wilt verwijderen?',
		'BankChecks' => 'Bankcheque',
		'BankChecksToReceipt' => 'Cheques wachten voor neerlegging',
		'ShowCheckReceipt' => 'Show check deposit receipt',
		'NumberOfCheques' => 'Nummer van cheques',
		'DeleteTransaction' => 'Verwijderen transactie',
		'ConfirmDeleteTransaction' => 'Weet u zeker dat u deze transactie wilt verwijderen?',
		'ThisWillAlsoDeleteBankRecord' => 'Dit zal ook gegenereerde banktransacties verwijderen',
		'BankMovements' => 'Bewegingen',
		'CashBudget' => 'Kas budget',
		'PlannedTransactions' => 'Geplande transacties',
		'Graph' => 'Graphics',
		'ExportDataset_banque_1' => 'Banktransacties en rekeningoverzicht',
		'TransactionOnTheOtherAccount' => 'Transactie op de andere rekening',
		'TransactionWithOtherAccount' => 'Rekening transfer',
		'PaymentNumberUpdateSucceeded' => 'Betalingsnummer bijgewerkt',
		'PaymentNumberUpdateFailed' => 'Betalingsnummer kon niet worden bijgewerkt',
		'PaymentDateUpdateSucceeded' => 'Betaaldatum succesvol bijgewerkt',
		'PaymentDateUpdateFailed' => 'Betaaldatum kon niet worden bijgewerkt',
		'Transactions' => 'Transactions',
		'BankTransactionLine' => 'Banktransactie',
		'AllAccounts' => 'Alle bank -/ Kasrekeningen',
		'BackToAccount' => 'Terug naar de rekening',
		'ShowAllAccounts' => 'Toon voor alle rekeningen',
		'FutureTransaction' => 'Transaction in futur. No way to conciliate.',
		'SelectChequeTransactionAndGenerate' => 'Select/filter checks to include into the check deposit receipt and click on "Create".',
		'InputReceiptNumber' => 'Choose the bank statement related with the conciliation. Use a sortable numeric value (such as, YYYYMM)',
		'EventualyAddCategory' => 'Eventually, specify a category in which to classify the records',
		'ToConciliate' => 'To conciliate?',
		'ThenCheckLinesAndConciliate' => 'Then, check the lines present in the bank statement and click'
);
?>