<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Categorie',
		'Categories' => 'Categorieën',
		'Rubrique' => 'Categorie',
		'Rubriques' => 'Categorieën',
		'categories' => 'categorieën',
		'TheCategorie' => 'De categorie',
		'NoCategoryYet' => 'No category of this type created',
		'In' => 'In',
		'AddIn' => 'Voeg in',
		'modify' => 'wijzigen',
		'Classify' => 'Classificeer',
		'CategoriesArea' => 'Categorieën gebied',
		'ProductsCategoriesArea' => 'Producten / Diensten\' categorieën gebied',
		'SuppliersCategoriesArea' => 'Leveranciers categorieën gebied',
		'CustomersCategoriesArea' => 'Klanten categorieën gebied',
		'ThirdPartyCategoriesArea' => 'Derde partijen\' categorieën gebied',
		'MembersCategoriesArea' => 'Members categories area',
		'MainCats' => 'Belangrijkste categorieën',
		'SubCats' => 'Subcategorieën',
		'CatStatistics' => 'Statistieken',
		'CatList' => 'Lijst van catgorieën',
		'AllCats' => 'Alle categorieën',
		'ViewCat' => 'Bekijk categorie',
		'NewCat' => 'Categorie toevoegen',
		'NewCategory' => 'Nieuwe categorie',
		'ModifCat' => 'Wijzigen categorie',
		'CatCreated' => 'Categorie aangemaakt',
		'CreateCat' => 'Maak categorie',
		'CreateThisCat' => 'Maak deze categorie',
		'ValidateFields' => 'Valideer velden',
		'NoSubCat' => 'Geen subcategorie.',
		'SubCatOf' => 'Subcategorie',
		'FoundCats' => 'Gevonden categorieën',
		'FoundCatsForName' => 'Categorieën gevonden voor de naam:',
		'FoundSubCatsIn' => 'Subcategorieën gevonden in de categorie',
		'ErrSameCatSelected' => 'U heeft dezelfde categorie meerdere malen geselecteerd',
		'ErrForgotCat' => 'U vergat uw categorie te kiezen',
		'ErrForgotField' => 'Je vergat om de velden te kiezen',
		'ErrCatAlreadyExists' => 'Deze naam wordt al gebruikt',
		'AddProductToCat' => 'Voeg dit product naar een categorie?',
		'ImpossibleAddCat' => 'Onmogelijk om de categorie toe te voegen',
		'ImpossibleAssociateCategory' => 'Onmogelijk om de categorie toe te wijzen aan',
		'WasAddedSuccessfully' => '<b>%s</b> is succesvol toegevoegd.',
		'ObjectAlreadyLinkedToCategory' => 'Dit element is gekoppeld aan deze categorie.',
		'CategorySuccessfullyCreated' => 'De categorie %s is met succes toegevoegd.',
		'ProductIsInCategories' => 'Dit product / dienst zit in de volgende categorieën',
		'SupplierIsInCategories' => 'Deze leverancier zit in de volgende categorieën',
		'CompanyIsInCustomersCategories' => 'Dit bedrijf zit in de volgende categorieën van klanten / potentiële klanten',
		'CompanyIsInSuppliersCategories' => 'Dit bedrijf zit in de volgende categorieën van leveranciers',
		'MemberIsInCategories' => 'This member owns to following members categories',
		'ProductHasNoCategory' => 'Dit product / dienst zit in geen enkele categorie',
		'SupplierHasNoCategory' => 'Deze leverancier zit in geen enkele categorie',
		'CompanyHasNoCategory' => 'Dit bedrijf zit in geen enkele categorie',
		'MemberHasNoCategory' => 'This member is not in any categories',
		'ClassifyInCategory' => 'Classificeer in categorie',
		'NoneCategory' => 'Geen',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Deze categorie bestaat al op diezelfde plaats',
		'ReturnInProduct' => 'Terug naar product / dienst-kaart',
		'ReturnInSupplier' => 'Terug naar leverancierskaart',
		'ReturnInCompany' => 'Terug naar de klant of potentiël klantenkaart',
		'ContentsVisibleByAll' => 'De inhoud zichtbaar door iedereen',
		'ContentsVisibleByAllShort' => 'Inhoud zichtbaar door iedereen',
		'ContentsNotVisibleByAllShort' => 'Inhoud niet zichtbaar door iedereen',
		'CategoriesTree' => 'Categorieën boom',
		'DeleteCategory' => 'Verwijderen categorie',
		'ConfirmDeleteCategory' => 'Weet u zeker dat u deze categorie wilt verwijderen?',
		'RemoveFromCategory' => 'Verwijder de link met de categorie',
		'RemoveFromCategoryConfirm' => 'Weet u zeker dat u de link tussen de transactie en de categorie wilt verwijderen?',
		'NoCategoriesDefined' => 'Geen gedefiniëerde categorie',
		'SuppliersCategoryShort' => 'Leveranciers categorie',
		'CustomersCategoryShort' => 'Categorie klanten',
		'ProductsCategoryShort' => 'Categorie producten',
		'MembersCategoryShort' => 'Members category',
		'SuppliersCategoriesShort' => 'Categorieën leveranciers',
		'CustomersCategoriesShort' => 'Categorieën klanten',
		'CustomersProspectsCategoriesShort' => 'Categorieën <br>Klanten / Potentiële klanten',
		'ProductsCategoriesShort' => 'Categorieën producten',
		'MembersCategoriesShort' => 'Members categories',
		'ThisCategoryHasNoProduct' => 'Deze categorie bevat geen producten.',
		'ThisCategoryHasNoSupplier' => 'Deze categorie bevat geen enkele leverancier.',
		'ThisCategoryHasNoCustomer' => 'Deze categorie bevat geen klant.',
		'ThisCategoryHasNoMember' => 'This category does not contain any member.',
		'AssignedToCustomer' => 'Toegewezen aan een klant',
		'AssignedToTheCustomer' => 'Toegewezen aan de klant',
		'InternalCategory' => 'Interne categorie',
		'CategoryContents' => 'Categorie inhoud',
		'CategId' => 'Categorie id',
		'CatSupList' => 'List of supplier categories',
		'CatCusList' => 'List of customer/prospect categories',
		'CatProdList' => 'List of products categories',
		'CatMemberList' => 'List of members categories',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>