<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Commerciëel',
		'CommercialArea' => 'Commerciële ruimte',
		'CommercialCard' => 'Commerciële kaart',
		'CustomerArea' => 'Klanten ruimte',
		'Customer' => 'Klant',
		'Customers' => 'Klanten',
		'Prospect' => 'Potentiële klant',
		'Prospects' => 'Potentiële klanten',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Verwijder een actie / taak',
		'NewAction' => 'Nieuwe actie / taak',
		'AddAction' => 'Toevoegen actie / taak',
		'AddAnAction' => 'Voeg een actie / taak',
		'AddActionRendezVous' => 'Maak een afspraak',
		'Rendez-Vous' => 'Rendezvous',
		'ConfirmDeleteAction' => 'Weet u zeker dat u deze taak wilt verwijderen?',
		'CardAction' => 'Actie kaart',
		'PercentDone' => 'Percentage gedaan',
		'ActionOnCompany' => 'Taak over bedrijf',
		'ActionOnContact' => 'Taak over contact',
		'TaskRDV' => 'Vergaderingen',
		'TaskRDVWith' => 'Ontmoeting met %s',
		'ShowTask' => 'Toon taak',
		'ShowAction' => 'Toon actie',
		'ActionsReport' => 'Verslag acties',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Verkoopvertegenwoordiger',
		'SalesRepresentatives' => 'Verkoopvertegenwoordigers',
		'SalesRepresentativeFollowUp' => 'Verkoopvertegenwoordiger (opvolging)',
		'SalesRepresentativeSignature' => 'Verkoopvertegenwoordiger (handtekening)',
		'CommercialInterlocutor' => 'Commerciëel gesprekspartner',
		'ErrorWrongCode' => 'Verkeerde code',
		'NoSalesRepresentativeAffected' => 'Geen bijzondere verkoopvertegenwoordiger getroffen',
		'ShowCustomer' => 'Toon klant',
		'ShowProspect' => 'Toon potentiële klant',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Lijst van Potentiële klanten',
		'ListOfCustomers' => 'Lijst van klanten',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'Laatste %s gedane taken',
		'LastRecordedTasks' => 'Laatste taken',
		'LastActionsToDo' => 'Laatste %s oudste acties niet voltooid',
		'DoneAndToDoActionsFor' => 'Gedaan en taken nog te doen voor %s',
		'DoneAndToDoActions' => 'Gedaan en doe taken',
		'DoneActions' => 'Gedane acties',
		'DoneActionsFor' => 'Gedane acties voor %s',
		'ToDoActions' => 'Onvolledige acties',
		'ToDoActionsFor' => 'Onvolledige acties voor %s',
		'SendPropalRef' => 'Stuur commerciëel voorstel %s',
		'SendOrderRef' => 'Stuur bestelling %s',
		'StatusNotApplicable' => 'Not applicable',
		'StatusActionToDo' => 'Te doen',
		'StatusActionDone' => 'Gedaan',
		'StatusActionInProcess' => 'Gaande',
		'MyActionsAsked' => 'Acties die ik heb geregistreerd',
		'MyActionsToDo' => 'Acties die ik moet doen',
		'MyActionsDone' => 'Acties die ik heb gemaakt',
		'TasksHistoryForThisContact' => 'Acties voor deze contactpersoon',
		'LastProspectDoNotContact' => 'Niet contacteren',
		'LastProspectNeverContacted' => 'Nog nooit gecontacteerd',
		'LastProspectToContact' => 'Contact op te nemen met',
		'LastProspectContactInProcess' => 'Contact in process',
		'LastProspectContactDone' => 'Gecontacteerd',
		'DateActionPlanned' => 'Datum actie gepland voor',
		'DateActionDone' => 'Datum actie gedaan',
		'ActionAskedBy' => 'Actie gevraagd door',
		'ActionAffectedTo' => 'Actie getroffen om',
		'ActionDoneBy' => 'Actie gedaan door',
		'ActionUserAsk' => 'Geregistreerd door',
		'ErrorStatusCantBeZeroIfStarted' => 'Als veld \'<b>Datum gedaan</b>\' is ingevuld, de actie is gestart (of beëindigd), dus veld \'<b>Status</b>\' kan niet 0%% zijn.  If field \'<b>Date done</b>\' is filled, action is started (or finished), so field \'<b>Status</b>\' can\'t be 0%%.',
		'ActionAC_TEL' => 'Telefoongesprek',
		'ActionAC_FAX' => 'Verzend per fax',
		'ActionAC_PROP' => 'Verzend voorstel',
		'ActionAC_EMAIL' => 'E-mail verzenden',
		'ActionAC_RDV' => 'Vergaderingen',
		'ActionAC_FAC' => 'Stuur factuur',
		'ActionAC_REL' => 'Stuur factuur (herinnering)',
		'ActionAC_CLO' => 'Sluiten',
		'ActionAC_EMAILING' => 'Stuur massa e-mail',
		'ActionAC_COM' => 'Verzend bestelling per mail',
		'ActionAC_SHIP' => 'Send shipping by mail',
		'ActionAC_SUP_ORD' => 'Send supplier order by mail',
		'ActionAC_SUP_INV' => 'Send supplier invoice by mail',
		'ActionAC_OTH' => 'Other',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Prospect status',
		'DraftPropals' => 'Draft commercial proposals',
		'SearchPropal' => 'Search a commercial proposal'
);
?>