<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$compta = array(
		'CHARSET' => 'UTF-8',
		'Accountancy' => 'De boekhouding',
		'AccountancyCard' => 'Kaart boekhouding',
		'Treasury' => 'Penningmeester',
		'MenuFinancial' => 'Financiëel',
		'TaxModuleSetupToModifyRules' => 'Go to <a href="%s">module setup</a> to modify rules for calculation',
		'OptionMode' => 'Optie voor de boekhouding',
		'OptionModeTrue' => 'Optie Input-Ouput',
		'OptionModeVirtual' => 'Optie Credit-Debet',
		'OptionModeTrueDesc' => 'In deze context is de omzet berekend op betalingen (datum van de betalingen). \n De geldigheid van de cijfers zijn slechts verzekerd wanneer de boekhouding wordt gecontroleerd door middel van de input / output op de rekeningen via facturen.',
		'OptionModeVirtualDesc' => 'In deze context wordt de omzet berekend op de facturen (datum van validatie). Wanneer deze facturen verschuldigd zijn, ongeacht of zij betaald zijn of niet, ze zijn opgenomen in de omzet.',
		'FeatureIsSupportedInInOutModeOnly' => 'Feature only available in CREDITS-DEBTS accountancy mode (See Accountancy module configuration)',
		'VATReportBuildWithOptionDefinedInModule' => 'Amounts shown here are calculated using rules defined by Tax module setup.',
		'Param' => 'Setup',
		'RemainingAmountPayment' => 'Amount payment remaining :',
		'AmountToBeCharged' => 'Total amount to pay :',
		'AccountsGeneral' => 'Rekeningen',
		'Account' => 'Rekening',
		'Accounts' => 'Rekeningen',
		'Accountparent' => 'Account parent',
		'Accountsparent' => 'Accounts parent',
		'BillsForSuppliers' => 'Facturen van leveranciers',
		'Income' => 'Inkomsten',
		'Outcome' => 'Uitgaven',
		'ReportInOut' => 'Inkomsten / Uitgaven',
		'ReportTurnover' => 'Turnover',
		'PaymentsNotLinkedToInvoice' => 'Betalingen niet gekoppeld aan een factuur, dus niet gekoppeld aan een derde partij',
		'PaymentsNotLinkedToUser' => 'Betalingen niet gekoppeld aan een gebruiker',
		'Profit' => 'Winst',
		'Balance' => 'Saldo',
		'Debit' => 'Debet',
		'Credit' => 'Credit',
		'Withdrawal' => 'Intrekking',
		'Withdrawals' => 'Intrekkingen',
		'AmountHTVATRealReceived' => 'HT ontvangen',
		'AmountHTVATRealPaid' => 'HT betaald',
		'VATToPay' => 'BTW te betalen',
		'VATReceived' => 'BTW ontvangen',
		'VATToCollect' => 'BTW te ontvangen',
		'VATSummary' => 'BTW Samenvatting',
		'LT2SummaryES' => 'IRPF Balance',
		'VATPaid' => 'BTW betaald',
		'LT2PaidES' => 'IRPF Paid',
		'LT2CustomerES' => 'IRPF sales',
		'LT2SupplierES' => 'IRPF purchases',
		'VATCollected' => 'Geïnde BTW',
		'ToPay' => 'Te betalen',
		'ToGet' => 'To get back',
		'TaxAndDividendsArea' => 'Belastingen, sociale premies en dividenden gebied',
		'SocialContribution' => 'Sociale bijdrage',
		'SocialContributions' => 'Sociale premies',
		'MenuTaxAndDividends' => 'Belastingen en dividenden',
		'MenuSocialContributions' => 'Sociale premies',
		'MenuNewSocialContribution' => 'Nieuwe bijdrage',
		'NewSocialContribution' => 'Nieuwe sociale bijdrage',
		'ContributionsToPay' => 'Bijdragen te betalen',
		'AccountancyTreasuryArea' => 'Boekhouding / Penningmeester gebied',
		'AccountancySetup' => 'Boekhouding setup',
		'NewPayment' => 'Nieuwe betaling',
		'Payments' => 'Betalingen',
		'PaymentCustomerInvoice' => 'Factuur betaling klant',
		'PaymentSupplierInvoice' => 'Factuur betaling leverancier',
		'PaymentSocialContribution' => 'Sociale bijdrage betalen',
		'PaymentVat' => 'BTW-betaling',
		'ListPayment' => 'Lijst van de betalingen',
		'ListOfPayments' => 'Lijst van de betalingen',
		'ListOfCustomerPayments' => 'Lijst van klantenbetalingen',
		'ListOfSupplierPayments' => 'Lijst van leveranciersbetalingen',
		'DatePayment' => 'Betaaldatum',
		'NewVATPayment' => 'Nieuwe BTW-betaling',
		'newLT2PaymentES' => 'New IRPF payment',
		'LT2PaymentES' => 'IRPF Payment',
		'LT2PaymentsES' => 'IRPF Payments',
		'VATPayment' => 'BTW-betaling',
		'VATPayments' => 'BTW-betalingen',
		'SocialContributionsPayments' => 'Social contributions payments',
		'ShowVatPayment' => 'Toon BTW-betaling',
		'TotalToPay' => 'Totaal te betalen',
		'TotalVATReceived' => 'Totaal BTW ontvangen',
		'CustomerAccountancyCode' => 'Klant boekhouding code',
		'SupplierAccountancyCode' => 'Leverancier boekhouding code',
		'AlreadyPaid' => 'Reeds betaald',
		'AccountNumberShort' => 'Rekeningnummer',
		'AccountNumber' => 'Rekeningnummer',
		'NewAccount' => 'Nieuwe rekening',
		'SalesTurnover' => 'Omzet',
		'ByThirdParties' => 'Door derde partijen',
		'ByUserAuthorOfInvoice' => 'Door auteur factuur',
		'AccountancyExport' => 'Export boekhouding',
		'ErrorWrongAccountancyCodeForCompany' => 'Onjuiste boekhouding code voor %s',
		'SuppliersProductsSellSalesTurnover' => 'Omzet gegenereerd door de verkoop van producten van leveranciers.',
		'CheckReceipt' => 'Check neerlegging',
		'CheckReceiptShort' => 'Check neerlegging',
		'NewCheckReceipt' => 'Nieuwe korting',
		'NewCheckDeposit' => 'Nieuwe neerlegging controleren',
		'NewCheckDepositOn' => 'Nieuwe neerlegging controleren op rekening: %s',
		'NoWaitingChecks' => 'Geen wachtende neerleggingen.',
		'DateChequeReceived' => 'Datum cheque ontvangen',
		'NbOfCheques' => 'Aantal cheques',
		'PaySocialContribution' => 'Betalen van een sociale bijdrage',
		'ConfirmPaySocialContribution' => 'Weet u zeker dat u deze sociale bijdrage als betaald wilt klasseren?',
		'DeleteSocialContribution' => 'Verwijderen van een sociale bijdrage',
		'ConfirmDeleteSocialContribution' => 'Weet u zeker dat u deze sociale bijdrage wilt verwijderen?',
		'ExportDataset_tax_1' => 'Sociale premies en betalingen',
		'AnnualSummaryDueDebtMode' => 'Saldo van inkomsten en uitgaven, jaarlijks overzicht, en mode <b>%sLeningen Schulden%s</b> dit <b>comptabilité d\'engagement</b>.',
		'AnnualSummaryInputOutputMode' => 'Balance of income and expenses, annual summary, mode <b>%sIncomes-Expenses%s</b> said <b>cash accounting</b>.',
		'AnnualByCompaniesDueDebtMode' => 'Balance of income and expenses, detail by third parties, mode <b>%sClaims-Debts%s</b> said <b>Commitment accounting</b>.',
		'AnnualByCompaniesInputOutputMode' => 'Balance of income and expenses, detail by third parties, mode <b>%sIncomes-Expenses%s</b> said <b>cash accounting</b>.',
		'SeeReportInInputOutputMode' => 'See report <b>%sIncomes-Expenses%s</b> said <b>cash accounting</b> for a calculation on actual payments made',
		'SeeReportInDueDebtMode' => 'See report <b>%sClaims-Debts%s</b> said <b>commitment accounting</b> for a calculation on issued invoices',
		'RulesResultDue' => '- Bedragen zijn inclusief alle belastingen <br> - Het omvat openstaande facturen, onkosten en BTW of ze betaald zijn of niet. <br> - Het is gebaseerd op de validatiedatum van de facturen en BTW en op de vervaldag voor de kosten.',
		'RulesResultInOut' => '- Bedragen zijn inclusief alle belastingen <br> - Het omvat de werkelijke betalingen op facturen, onkosten en BTW. <br> - Het is gebaseerd op de data van betaling van de facturen, uitgaven en BTW. <br>',
		'RulesCADue' => '- It includes the clients\' due invoices whether they are paid or not. <br>- It is based on the validation date of these invoices. <br>',
		'RulesCAIn' => '- Het omvat alle effectieve betalingen van facturen van klanten. <br> - Het is gebaseerd op de betalingsdatum van deze facturen <br>',
		'DepositsAreNotIncluded' => '- Deposit invoices are nor included',
		'DepositsAreIncluded' => '- Deposit invoices are included',
		'LT2ReportByCustomersInInputOutputModeES' => 'Report by third party IRPF',
		'VATReportByCustomersInInputOutputMode' => 'Verslag de geïnd en betaalde BTW van de klant (BTW ontvangst)',
		'VATReportByCustomersInDueDebtMode' => 'Report by the customer VAT collected and paid (VAT rate)',
		'VATReportByQuartersInInputOutputMode' => 'Report by rate of the VAT collected and paid (VAT receipt)',
		'VATReportByQuartersInDueDebtMode' => 'Report by rate of the VAT collected and paid (VAT rate)',
		'SeeVATReportInInputOutputMode' => 'See report <b>%sVAT encasement%s</b> for a standard calculation',
		'SeeVATReportInDueDebtMode' => 'See report <b>%sVAT on flow%s</b> for a calculation with an option on the flow',
		'RulesVATInServices' => '- For services, the report includes the VAT regulations actually received or issued on the basis of the date of payment.<br>- For material assets, it includes the VAT invoices on the basis of the invoice date.',
		'RulesVATInProducts' => '- For material assets, it includes the VAT invoices on the basis of the invoice date.',
		'RulesVATDueServices' => '- For services, the report includes VAT invoices due, paid or not, based on the invoice date.',
		'RulesVATDueProducts' => '- For material assets, it includes the VAT invoices, based on the invoice date.',
		'OptionVatInfoModuleComptabilite' => 'Note: For material assets, it should use the date of delivery to be more fair.',
		'PercentOfInvoice' => '%%/factuur',
		'NotUsedForGoods' => 'Not used on goods',
		'ProposalStats' => 'Statistics on proposals',
		'OrderStats' => 'Statistics on orders',
		'InvoiceStats' => 'Statistics on bills',
		'Dispatch' => 'Verzending',
		'Dispatched' => 'Verzonden',
		'ToDispatch' => 'Te verzenden',
		'ThirdPartyMustBeEditAsCustomer' => 'Third party must be defined as a customer',
		'SellsJournal' => 'Sales Journal',
		'PurchasesJournal' => 'Purchases Journal',
		'DescSellsJournal' => 'Sales Journal',
		'DescPurchasesJournal' => 'Purchases Journal',
		'InvoiceRef' => 'Invoice ref.',
		'CodeNotDef' => 'Not defined',
		'AddRemind' => 'Dispatch available amount',
		'RemainToDivide' => 'Remain to dispatch :',
		'WarningDepositsNotIncluded' => 'Deposits invoices are not included in this version with this accountancy module.',
		'DatePaymentTermCantBeLowerThanObjectDate' => 'Payment term date can\'t be lower than object date.',
		'Pcg_version' => 'Pcg version',
		'Pcg_type' => 'Pcg type',
		'Pcg_subtype' => 'Pcg subtype',
		'Withdrawl' => 'Prélèvement',
		'Withdrawls' => 'Prélèvements',
		'ToGetBack' => 'A récupérer',
		'Journaux' => 'Journaux',
		'Piece' => 'Piece compta',
		'JournalNum' => 'Journal',
		'COMPTA_JOURNAL_SELL' => 'Numéro comptable du Journal des Achats',
		'COMPTA_JOURNAL_BUY' => 'Numéro comptable du Journal des Ventes',
		'COMPTA_PRODUCT_BUY_ACCOUNT' => 'Compte comptable par défaut pour produits achetés (si non défini sur fiche produit)',
		'COMPTA_PRODUCT_SOLD_ACCOUNT' => 'Compte comptable par défaut pour produits vendus (si non défini sur fiche produit)',
		'COMPTA_SERVICE_BUY_ACCOUNT' => 'Compte comptable par défaut pour services achetés (si non défini sur fiche service)',
		'COMPTA_SERVICE_SOLD_ACCOUNT' => 'Compte comptable par défaut pour services vendus (si non défini sur fiche service)',
		'COMPTA_VAT_ACCOUNT' => 'Compte comptable par défaut pour TVA (si non défini dans dictionnaire "Taux de TVA")',
		'COMPTA_ACCOUNT_CUSTOMER' => 'Compte comptable client par défaut (si non défini sur fiche tiers)',
		'COMPTA_ACCOUNT_SUPPLIER' => 'Compte comptable fournisseur par défaut (si non défini sur fiche tiers)',
);
?>