<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$contracts = array(
		'CHARSET' => 'UTF-8',
		'ContractsArea' => 'Contracten gebied',
		'ListOfContracts' => 'Lijst van opdrachten',
		'LastContracts' => 'Laatste %s bewerkte contracten',
		'AllContracts' => 'Alle contracten',
		'ContractCard' => 'Contract kaart',
		'ContractStatus' => 'Contract status',
		'ContractStatusNotRunning' => 'Niet actief',
		'ContractStatusRunning' => 'Actief',
		'ContractStatusDraft' => 'Ontwerp',
		'ContractStatusValidated' => 'Gevalideerd',
		'ContractStatusClosed' => 'Gesloten',
		'ServiceStatusInitial' => 'Niet actief',
		'ServiceStatusRunning' => 'Actief',
		'ServiceStatusNotLate' => 'Running, not expired',
		'ServiceStatusNotLateShort' => 'Not expired',
		'ServiceStatusLate' => 'Actief, verstreken',
		'ServiceStatusLateShort' => 'Expired',
		'ServiceStatusClosed' => 'Gesloten',
		'ServicesLegend' => 'Legende diensten',
		'Contracts' => 'Contracten',
		'Contract' => 'Contract',
		'NoContracts' => 'Geen contracten',
		'MenuServices' => 'Diensten',
		'MenuInactiveServices' => 'Diensten niet actief',
		'MenuRunningServices' => 'Diensten actief',
		'MenuExpiredServices' => 'Verstreken diensten',
		'MenuClosedServices' => 'Gesloten diensten',
		'NewContract' => 'Nieuw contract',
		'AddContract' => 'Contract toevoegen',
		'SearchAContract' => 'Zoek een contract',
		'DeleteAContract' => 'Verwijderen een contract',
		'CloseAContract' => 'Sluit een contract',
		'ConfirmDeleteAContract' => 'Weet u zeker dat u dit contract en al haar diensten wilt verwijderen?',
		'ConfirmValidateContract' => 'Weet u zeker dat u dit contract wilt valideren?',
		'ConfirmCloseContract' => 'Dit sluit alle diensten (actief of niet). Weet u zeker dat u dit contract wilt afsluiten?',
		'ConfirmCloseService' => 'Weet u zeker dat u eze dienst met datum <b>%s</b> wilt afsluiten?',
		'ValidateAContract' => 'Valideren van een contract',
		'ActivateService' => 'Dienst activeren',
		'ConfirmActivateService' => 'Weet u zeker dat u deze dienst met de datum van <b>%s</b> wilt activeren?',
		'RefContract' => 'Contract reference',
		'DateContract' => 'Contractdatum',
		'DateServiceActivate' => 'Datum van de activering van de dienst',
		'DateServiceUnactivate' => 'Deactiveringsdatum van de dienst',
		'DateServiceStart' => 'Begindatum van de dienst',
		'DateServiceEnd' => 'Einddatum van de dienst',
		'ShowContract' => 'Toon contract',
		'ListOfServices' => 'Lijst van diensten',
		'ListOfInactiveServices' => 'List of not active services',
		'ListOfExpiredServices' => 'List of expired active services',
		'ListOfClosedServices' => 'List of closed services',
		'ListOfRunningContractsLines' => 'Lijst van lopende contract lijnen',
		'ListOfRunningServices' => 'Lijst van actieve diensten',
		'NotActivatedServices' => 'Niet geactiveerde diensten (onder gevalideerde contracten)',
		'BoardNotActivatedServices' => 'Diensten te activeren onder gevalideerde contracten',
		'LastContracts' => 'Laatste %s bewerkte contracten',
		'LastActivatedServices' => 'Laatste %s geactiveerde diensten',
		'LastModifiedServices' => 'Laatste %s bewerkte diensten',
		'EditServiceLine' => 'Bewerken service lijn',
		'ContractStartDate' => 'Begindatum',
		'ContractEndDate' => 'Einddatum',
		'DateStartPlanned' => 'Geplande startdatum',
		'DateStartPlannedShort' => 'Geplande startdatum',
		'DateEndPlanned' => 'Geplande einddatum',
		'DateEndPlannedShort' => 'Geplande einddatum',
		'DateStartReal' => 'Werkelijke startdatum',
		'DateStartRealShort' => 'Werkelijke startdatum',
		'DateEndReal' => 'Werkelijke einddatum van de dienst',
		'DateEndRealShort' => 'Werkelijke einddatum',
		'NbOfServices' => 'Aantal diensten',
		'CloseService' => 'Sluit dienst',
		'ServicesNomberShort' => '%s dienst(en)',
		'RunningServices' => 'Actieve diensten',
		'BoardRunningServices' => 'Actieve verstreken diensten',
		'ServiceStatus' => 'Status van de dienst',
		'DraftContracts' => 'Ontwerp-contracten',
		'CloseRefusedBecauseOneServiceActive' => 'Het contract kan niet worden gesloten omdat er ten minste één open dienst is.',
		'CloseAllContracts' => 'Sluit alle contracten',
		'DeleteContractLine' => 'Delete a contract line',
		'ConfirmDeleteContractLine' => 'Are you sure you want to delete this contract line ?',
		'MoveToAnotherContract' => 'Verplaats dienst naar een ander contract.',
		'ConfirmMoveToAnotherContract' => 'Ik kies een nieuw contract en bevestig dat deze dienst verplaatst wordt naar dit contract.',
		'ConfirmMoveToAnotherContractQuestion' => 'In welk bestaand contract (of zelfde derde partij) wilt u deze dienst verplaatsen?',
		'PaymentRenewContractId' => 'Renew contract line (number %s)',
		'ExpiredSince' => 'Expiration date',
		'RelatedContracts' => 'Related contracts',
		'NoExpiredServices' => 'No expired active services',
		////////// Types de contacts //////////
		'TypeContact_contrat_internal_SALESREPSIGN' => 'Verkoopvertegenwoordiger ondertekening contract',
		'TypeContact_contrat_internal_SALESREPFOLL' => 'Verkoopvertegenwoordiger opvolging contract',
		'TypeContact_contrat_external_BILLING' => 'Factureer contact met klant',
		'TypeContact_contrat_external_CUSTOMER' => 'Opvolging contact met klant',
		'TypeContact_contrat_external_SALESREPSIGN' => 'Ondertekening contract klantencontact',
		'Error_CONTRACT_ADDON_NotDefined' => 'Constant CONTRACT_ADDON not defined'
);
?>