<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$errors = array(
		'CHARSET' => 'UTF-8',
		'MenuManager' => 'Menu manager',
		// Errors
		'Error' => 'Error',
		'Errors' => 'Errors',
		'ErrorBadEMail' => 'EMail %s is wrong',
		'ErrorBadUrl' => 'Url %s is wrong',
		'ErrorLoginAlreadyExists' => 'Inloggen %s bestaat reeds.',
		'ErrorGroupAlreadyExists' => 'Groep %s bestaat reeds.',
		'ErrorRecordNotFound' => 'Record not found.',
		'ErrorFailToCopyFile' => 'Failed to copy file \'<b>%s</b>\' into \'<b>%s</b>\'.',
		'ErrorFailToRenameFile' => 'Failed to rename file \'<b>%s</b>\' into \'<b>%s</b>\'.',
		'ErrorFailToDeleteFile' => 'Mislukt om bestand \'<b>%s</b>\' te verwijderen',
		'ErrorFailToCreateFile' => 'Mislukt om bestand \'<b>%s</b>\' te creëren',
		'ErrorFailToRenameDir' => 'Mislukt om directory \'<b>%s</b>\' in \'<b>%s</b>\' te hernoemen',
		'ErrorFailToCreateDir' => 'Mislukt om de directory \'<b>%s</b>\' te creëren',
		'ErrorFailToDeleteDir' => 'Mislukt om de directory \'<b>%s</b>\' te verwijderen',
		'ErrorFailedToDeleteJoinedFiles' => 'Kan niet verwijderen omdat bestanden gekoppeld zijn. Verwijder deze bestanden eerst.',
		'ErrorThisContactIsAlreadyDefinedAsThisType' => 'Deze contactpersoon is al omschreven als contactpersoon voor dit type.',
		'ErrorCashAccountAcceptsOnlyCashMoney' => 'Deze bankrekening is een KAS-rekening, zodat zij enkel betalingen in contanten (cash) aanvaard.',
		'ErrorFromToAccountsMustDiffers' => 'Bron en toegewezen bankrekeningen moet verschillend zijn.',
		'ErrorBadThirdPartyName' => 'Onjuiste waarde voor derden naam',
		'ErrorBadCustomerCodeSyntax' => 'Bad syntaxis voor klantcode',
		'ErrorCustomerCodeRequired' => 'Klantencode nodig',
		'ErrorCustomerCodeAlreadyUsed' => 'Klantencode al gebruikt',
		'ErrorPrefixRequired' => 'Prefix nodig',
		'ErrorUrlNotValid' => 'The website address is incorrect',
		'ErrorBadSupplierCodeSyntax' => 'Slechte syntaxis voor Leverancierscode',
		'ErrorSupplierCodeRequired' => 'Leverancierscode nodig',
		'ErrorSupplierCodeAlreadyUsed' => 'Leverancierscode al gebruikt',
		'ErrorBadParameters' => 'Slechte parameters',
		'ErrorBadValueForParameter' => 'Wrong value \'%s\' for parameter incorrect \'%s\'',
		'ErrorBadImageFormat' => 'Image file has not a supported format',
		'ErrorBadDateFormat' => 'Value \'%s\' has wrong date format',
		'ErrorFailedToWriteInDir' => 'Mislukt om in de map %s te schrijven',
		'ErrorFoundBadEmailInFile' => 'Found incorrect email syntax for %s lines in file (example line %s with email=%s)',
		'ErrorUserCannotBeDelete' => 'User can not be deleted. May be it is associated on Dolibarr entities.',
		'ErrorFieldsRequired' => 'Enkele verplichte velden zijn niet ingevuld.',
		'ErrorFailedToCreateDir' => 'Mislukt om een directory te creëren. Check that Web server user has permissions to write into Dolibarr documents directory. If parameter <b>safe_mode</b> is enabled on this PHP, check that Dolibarr php files owns to web server user (or group).',
		'ErrorNoMailDefinedForThisUser' => 'Geen mail gedefinieerd voor deze gebruiker',
		'ErrorFeatureNeedJavascript' => 'Javascript moet geactiveerd zijn voor deze functie. Verander dit in de setup - display.',
		'ErrorTopMenuMustHaveAParentWithId0' => 'A menu of type \'Top\' can\'t have a parent menu. Put 0 in parent menu or choose a menu of type \'Left\'.',
		'ErrorLeftMenuMustHaveAParentId' => 'A menu of type \'Left\' must have a parent id.',
		'ErrorFileNotFound' => 'Bestand niet gevonden (Slecht pad, verkeerde permissies of toegang geweigerd door openbasedir parameter)',
		'ErrorDirNotFound' => 'Directory <b>%s</b> not found (Bad path, wrong permissions or access denied by PHP openbasedir or safe_mode parameter)',
		'ErrorFunctionNotAvailableInPHP' => 'Functie <b>%s</b> is vereist voor deze toepassing, maar is niet beschikbaar in deze versie / setup van PHP.',
		'ErrorDirAlreadyExists' => 'Een map met deze naam bestaat al.',
		'ErrorFileAlreadyExists' => 'A file with this name already exists.',
		'ErrorPartialFile' => 'File not received completely by server.',
		'ErrorNoTmpDir' => 'Temporary directy %s does not exists.',
		'ErrorUploadBlockedByAddon' => 'Upload blocked by a PHP/Apache plugin.',
		'ErrorFileSizeTooLarge' => 'File size is too large.',
		'ErrorSizeTooLongForIntType' => 'Size too long for int type (%s digits maximum)',
		'ErrorSizeTooLongForVarcharType' => 'Size too long for string type (%s chars maximum)',
		'ErrorFieldCanNotContainSpecialCharacters' => 'Veld <b>%s</b> mag geen speciale tekens bevat.',
		'ErrorNoAccountancyModuleLoaded' => 'Geen "accountancy" module geactiveerd',
		'ErrorExportDuplicateProfil' => 'Deze profielnaam bestaat al voor deze export set.',
		'ErrorLDAPSetupNotComplete' => 'Dolibarr LDAP-matching is niet compleet.',
		'ErrorLDAPMakeManualTest' => 'A .ldif file has been generated in directory %s. Try to load it manually from command line to have more informations on errors.',
		'ErrorCantSaveADoneUserWithZeroPercentage' => 'Can\'t save an action with "statut not started" if field "done by" is also filled.',
		'ErrorRefAlreadyExists' => 'Ref gebruikt voor de oprichting bestaat al.',
		'ErrorPleaseTypeBankTransactionReportName' => 'Vul bankontvangst naam in waar transactie wordt gemeld (Formaat YYYYMM of JJJJMMDD)',
		'ErrorRecordHasChildren' => 'Mislukt om records te verwijderen omdat er nog gelinkte bestanden zijn.',
		'ErrorModuleRequireJavascript' => 'Javascript must not be disabled to have this feature working. To enable/disable Javascript, go to menu Home->Setup->Display.',
		'ErrorPasswordsMustMatch' => 'Both typed passwords must match each other',
		'ErrorContactEMail' => 'A technical error occured. Please, contact administrator to following email <b>%s</b> en provide the error code <b>%s</b> in your message, or even better by adding a screen copy of this page.',
		'ErrorWrongValueForField' => 'Wrong value for field number <b>%s</b> (value \'<b>%s</b>\' does not match regex rule <b>%s</b>)',
		'ErrorFieldValueNotIn' => 'Wrong value for field number <b>%s</b> (value \'<b>%s</b>\' is not a value available into field <b>%s</b> of table <b>%s</b>)',
		'ErrorFieldRefNotIn' => 'Wrong value for field number <b>%s</b> (value \'<b>%s</b>\' is not a <b>%s</b> existing ref)',
		'ErrorsOnXLines' => 'Errors on <b>%s</b> source lines',
		'ErrorFileIsInfectedWithAVirus' => 'The antivirus program was not able to validate the file (file might be infected by a virus)',
		'ErrorSpecialCharNotAllowedForField' => 'Special characters are not allowed for field "%s"',
		'ErrorDatabaseParameterWrong' => 'Database setup parameter \'<b>%s</b>\' has a value not compatible to use Dolibarr (must have value \'<b>%s</b>\').',
		'ErrorNumRefModel' => 'A reference exists into database (%s) and is not compatible with this numbering rule. Remove record or renamed reference to activate this module.',
		'ErrorQtyTooLowForThisSupplier' => 'Quantity too low for this supplier or no price defined on this product for this supplier',
		'ErrorModuleSetupNotComplete' => 'Setup of module looks to be uncomplete. Go on Setup - Modules to complete.',
		'ErrorBadMask' => 'Error on mask',
		'ErrorBadMaskFailedToLocatePosOfSequence' => 'Error, mask without sequence number',
		'ErrorBadMaskBadRazMonth' => 'Error, bad reset value',
		'ErrorSelectAtLeastOne' => 'Error. Select at least one entry.',
		'ErrorProductWithRefNotExist' => 'Product with reference \'<i>%s</i>\' don\'t exist',
		'ErrorDeleteNotPossibleLineIsConsolidated' => 'Delete not possible because record is linked to a bank transation that is conciliated',
		'ErrorProdIdAlreadyExist' => '%s is assigned to another third',
		'ErrorFailedToSendPassword' => 'Mislukt om wachtwoord te verzenden',
		'ErrorFailedToLoadRSSFile' => 'Fails to get RSS feed. Try to add constant MAIN_SIMPLEXMLLOAD_DEBUG if error messages does not provide enough information.',
		'ErrorPasswordDiffers' => 'Wachtwoorden verschilt, typt u deze opnieuw.',
		'ErrorForbidden' => 'Toegang verboden. <br> U probeert toegang te krijgen tot een pagina of functie zonder in een geauthentiseerde sessie te gaan, of dat niet is toegestaan voor uw gebruikersaccount.',
		'ErrorForbidden2' => 'De machtigingen voor deze aanmelding kan worden verleend door de beheerder van Dolibarr via menu %s -> %s.',
		'ErrorForbidden3' => 'Dolibarr lijkt niet te werken binnen een geauthentiseerde sessie. Raadpleeg de installatie documentatie voor Dolibarr over hoe de authenticatie te beheren (htaccess, mod_auth of andere ...).',
		'ErrorNoImagickReadimage' => 'Imagick_readimage functie is niet aanwezig in deze installatie van PHP. De samenvatting is niet beschikbaar. Beheerders kunnen dit uitschakelen via het menu Opstelling - Grafische Instellingen.',
		'ErrorRecordAlreadyExists' => 'Record bestaat al',
		'ErrorCantReadFile' => 'Mislukt om bestand \'%s\' te lezen',
		'ErrorCantReadDir' => 'Mislukt om directorie \'%s\' te lezen',
		'ErrorFailedToFindEntity' => 'Mislukt om entiteit \'%s\' te lezen',
		'ErrorBadLoginPassword' => 'Onjuiste waarde voor login of wachtwoord',
		'ErrorLoginDisabled' => 'Uw account is uitgeschakeld',
		'ErrorFailedToRunExternalCommand' => 'Failed to run external command. Check it is available and runnable by your PHP server. If PHP <b>Safe Mode</b> is enabled, check that command is inside a directory defined by parameter <b>safe_mode_exec_dir</b>.',
		'ErrorFailedToChangePassword' => 'Mislukt om wachtwoord te wijzigen',
		'ErrorLoginDoesNotExists' => 'Gebruiker met login <b>%s</b> kon niet worden gevonden.',
		'ErrorLoginHasNoEmail' => 'Deze gebruiker heeft geen e-mail adres. Proces afgebroken.',
		'ErrorBadValueForCode' => 'Slechte waarde voor de input-code. Probeer het opnieuw met een nieuwe waarde ...',
		'ErrorBothFieldCantBeNegative' => 'Fields %s and %s can\'t be both negative',
		'ErrorWebServerUserHasNotPermission' => 'User account <b>%s</b> used to execute web server has no permission for that',
		'ErrorNoActivatedBarcode' => 'No barcode type activated',
		'ErrUnzipFails' => 'Failed to unzip %s with ZipArchive',
		'ErrNoZipEngine' => 'No engine to unzip %s file in this PHP',
		'ErrorFileMustBeADolibarrPackage' => 'The file %s must be a Dolibarr zip package',
		'ErrorFileRequired' => 'It takes a package Dolibarr file',
		'ErrorPhpCurlNotInstalled' => 'The PHP CURL is not installed, this is essential to talk with Paypal',
		'ErrorFailedToAddToMailmanList' => 'Failed to add record to Mailman list or SPIP base',
		'ErrorNewVaueCantMatchOldValue' => 'New value can\'t be equal to old one',
		'ErrorDuplicateTrigger' => 'Un fichier trigger de classe \'<b>%s</b>\' est présent plusieurs fois. Supprimer le doublon du répertoire \'<b>%s</b>\'.',
		'SESSIONEXPIRE' => 'La session est expirée',
		// Warnings
		'WarningMandatorySetupNotComplete' => 'Mandatory setup parameters are not yet defined',
		'WarningSafeModeOnCheckExecDir' => 'Warning, PHP option <b>safe_mode</b> is on so command must be stored inside a directory declared by php parameter <b>safe_mode_exec_dir</b>.',
		'WarningAllowUrlFopenMustBeOn' => 'Parameter <b>allow_url_fopen</b> must be set to <b>on</b> in filer <b>php.ini</b> for having this module working completely. U moet dit bestand handmatig wijzigen.',
		'WarningBuildScriptNotRunned' => 'Script <b>%s</b> was not yet ran to build graphics, or there is no data to show.',
		'WarningBookmarkAlreadyExists' => 'Een bladwijzer met deze titel of deze URL bestaat al.',
		'WarningPassIsEmpty' => 'Waarschuwing, database wachtwoord is leeg. Dit is een gat in de beveiliging. You should add a password to your database and change your conf.php file to reflect this.',
		'WarningConfFileMustBeReadOnly' => 'Warning, your config file (<b>htdocs/conf/conf.php</b>) can be overwritten by the web server. This is a serious security hole. Modify permissions on file to be in read only mode for operating system user used by Web server. If you use Windows and FAT format for your disk, you must know that this file system does not allow to add permissions on file, so can\'t be completely safe.',
		'WarningsOnXLines' => 'Warnings on <b>%s</b> source lines',
		'WarningNoDocumentModelActivated' => 'No model, for document generation, has been activated. A model will be choosed by default until you check your module setup.',
		'WarningLockFileDoesNotExists' => 'Warning, once setup is finished, you must disable install/migrate tools by adding a file <b>install.lock</b> into directory <b>%s</b>. Missing this file is a security hole.',
		'WarningUntilDirRemoved' => 'Deze waarschuwing zal actief blijven zolang deze map aanwezig is (alleen weergegeven voor admin-gebruikers).WarningInstallDirExists=Waarschuwing, install directorie (%s) bestaat nog steeds. Dit is een ernstig beveiligingslek. U moet deze zo spoedig mogelijk verwijderen.',
		'WarningCloseAlways' => 'Warning, closing is done even if amount differs between source and target elements. Enable this feature with caution.'
);
?>