<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$exports = array(
		'CHARSET' => 'UTF-8',
		'ExportsArea' => 'Export gebied',
		'ImportArea' => 'Import gebied',
		'NewExport' => 'Nieuwe exportmogelijkheden',
		'NewImport' => 'Nieuwe import',
		'ExportableDatas' => 'Exportable dataset',
		'ImportableDatas' => 'Importable dataset',
		'SelectExportDataSet' => 'Kies dataset die u wilt exporteren ...',
		'SelectImportDataSet' => 'Choose dataset you want to import...',
		'SelectExportFields' => 'Kies velden die u wilt exporteren, of selecteer een vooraf gedefinieerde uitvoer-profiel',
		'SelectImportFields' => 'Choose source file fields you want to import and their target field in database by moving them up and down with anchor %s, or select a predefined import profil:',
		'NotImportedFields' => 'Fields of source file not imported',
		'SaveExportModel' => 'Bewaar dit uitvoer-profiel als u van plan bent om het later te hergebruiken ...',
		'SaveImportModel' => 'Save this import profile if you plan to reuse it later...',
		'ExportModelName' => 'Export profielnaam',
		'ExportModelSaved' => 'Export profiel opgeslagen onder de naam <b>%s</b>.',
		'ExportableFields' => 'Exportable velden',
		'ExportedFields' => 'Geëxporteerde velden',
		'ImportModelName' => 'Import profile name',
		'ImportModelSaved' => 'Import profile saved under name <b>%s</b>.',
		'ImportableFields' => 'Importable fields',
		'ImportedFields' => 'Imported fields',
		'DatasetToExport' => 'Dataset te exporteren',
		'DatasetToImport' => 'Import file into dataset',
		'NoDiscardedFields' => 'No fields in source file are discarded',
		'Dataset' => 'Dataset',
		'ChooseFieldsOrdersAndTitle' => 'Kies velden Om ...',
		'FieldsOrder' => 'Velden bestelling',
		'FieldsTitle' => 'Velden titel',
		'FieldOrder' => 'Field order',
		'FieldTitle' => 'Field title',
		'ChooseExportFormat' => 'Kies exportformaat',
		'NowClickToGenerateToBuildExportFile' => 'Nu, klik op "Genereer" om het exportbestand te creëren',
		'AvailableFormats' => 'Formaten beschikbaar',
		'LibraryShort' => 'Library',
		'LibraryUsed' => 'Librairie',
		'LibraryVersion' => 'Versie',
		'Step' => 'Stap',
		'FormatedImport' => 'Import-assistent',
		'FormatedImportDesc1' => 'Dit gebied maakt het mogelijk om persoonlijke gegevens te importeren, met behulp van een assistent om u te helpen in het proces, zonder technische kennis.',
		'FormatedImportDesc2' => 'First step is to choose a king of data you want to load, then file to load, then to choose which fields you want to load.',
		'FormatedExport' => 'Export assistent',
		'FormatedExportDesc1' => 'Dit gebied maakt het mogelijk om persoonlijke gegevens te exporteren, met behulp van een assistent om u te helpen in het proces, zonder technische kennis.',
		'FormatedExportDesc2' => 'First step is to choose a predefined dataset, then to choose which fields you want in your result files, and which order.',
		'FormatedExportDesc3' => 'When data to export are selected, you can define output file format you want to export your data to.',
		'Sheet' => 'Blad',
		'NoImportableData' => 'Geen importable gegevens (no module with definitions to allow data imports)',
		'FileSuccessfullyBuilt' => 'Export bestand gegenereerd',
		'SQLUsedForExport' => 'SQL Request used to build export file',
		'LineId' => 'Id of line',
		'LineDescription' => 'Description of line',
		'LineUnitPrice' => 'Unit price of line',
		'LineVATRate' => 'VAT Rate of line',
		'LineQty' => 'Quantity for line',
		'LineTotalHT' => 'Amount net of tax for line',
		'LineTotalTTC' => 'Amount with tax for line',
		'LineTotalVAT' => 'Amount of VAT for line',
		'TypeOfLineServiceOrProduct' => 'Type of line (0=product, 1=service)',
		'FileWithDataToImport' => 'File with data to import',
		'FileToImport' => 'Source file to import',
		'FileMustHaveOneOfFollowingFormat' => 'File to import must have one of following format',
		'DownloadEmptyExample' => 'Download example of empty source file',
		'ChooseFormatOfFileToImport' => 'Choose file format to use as import file format by clicking on picto %s to select it...',
		'ChooseFileToImport' => 'Upload file then click on picto %s to select file as source import file...',
		'SourceFileFormat' => 'Source file format',
		'FieldsInSourceFile' => 'Fields in source file',
		'FieldsInTargetDatabase' => 'Target fields in Speedealing database (*=mandatory)',
		'Field' => 'Field',
		'NoFields' => 'No fields',
		'MoveField' => 'Move field column number %s',
		'ExampleOfImportFile' => 'Example_of_import_file',
		'SaveImportProfile' => 'Save this import profile',
		'ErrorImportDuplicateProfil' => 'Failed to save this import profile with this name. An existing profile already exists with this name.',
		'ImportSummary' => 'Import setup summary',
		'TablesTarget' => 'Targeted tables',
		'FieldsTarget' => 'Targeted fields',
		'TableTarget' => 'Targeted table',
		'FieldTarget' => 'Targeted field',
		'FieldSource' => 'Source field',
		'DoNotImportFirstLine' => 'Do not import first line of source file',
		'NbOfSourceLines' => 'Number of lines in source file',
		'NowClickToTestTheImport' => 'Check import parameters you have defined. If they are correct, click on button "<b>%s</b>" to launch a simulation of import process (no data will be changed in your database, it\'s only a simulation for the moment)...',
		'RunSimulateImportFile' => 'Launch the import simulation',
		'FieldNeedSource' => 'This fiels in database require a data from source file',
		'SomeMandatoryFieldHaveNoSource' => 'Some mandatory fields have no source from data file',
		'InformationOnSourceFile' => 'Information on source file',
		'InformationOnTargetTables' => 'Information on target fields',
		'SelectAtLeastOneField' => 'Switch at least one source field in the column of fields to export',
		'SelectFormat' => 'Choose this import file format',
		'RunImportFile' => 'Launch import file',
		'NowClickToRunTheImport' => 'Check result of import simulation. If everything is ok, launch the definitive import.',
		'DataLoadedWithId' => 'All data will be loaded with the following import id: <b>%s<b>',
		'ErrorMissingMandatoryValue' => 'Mandatory data is empty in source file for field <b>%s</b>.',
		'TooMuchErrors' => 'There is still <b>%s</b> other source lines with errors but output has been limited.',
		'TooMuchWarnings' => 'There is still <b>%s</b> other source lines with warnings but output has been limited.',
		'EmptyLine' => 'Empty line (will be discarded)',
		'CorrectErrorBeforeRunningImport' => 'You must first correct all errors before running definitive import.',
		'FileWasImported' => 'File was imported with number <b>%s</b>.',
		'YouCanUseImportIdToFindRecord' => 'You can find all imported records in your database by filtering on field <b>import_key=\'%s\'</b>.',
		'NbOfLinesOK' => 'Number of lines with no errors and no warnings: <b>%s</b>.',
		'NbOfLinesImported' => 'Number of lines successfully imported: <b>%s</b>.',
		'DataComeFromNoWhere' => 'Value to insert comes from nowhere in source file.',
		'DataComeFromFileFieldNb' => 'Value to insert comes from field number <b>%s</b> in source file.',
		'DataComeFromIdFoundFromRef' => 'Value that comes from field number <b>%s</b> of source file will be used to find id of parent object to use (So the objet <b>%s</b> that has the ref. from source file must exists into Speedealing).',
		'DataComeFromIdFoundFromCodeId' => 'Code that comes from field number <b>%s</b> of source file will be used to find id of parent object to use (So the code from source file must exists into dictionnary <b>%s</b>). Note that if you know id, you can also use it into source file instead of code. Import should work in both cases.',
		'DataIsInsertedInto' => 'Data coming from source file will be inserted into the following field:',
		'DataIDSourceIsInsertedInto' => 'The id of parent object found using the data in source file, will be inserted into the following field:',
		'DataCodeIDSourceIsInsertedInto' => 'The id of parent line found from code, will be inserted into following field:',
		'SourceRequired' => 'Data value is mandatory',
		'SourceExample' => 'Example of possible data value',
		'ExampleAnyRefFoundIntoElement' => 'Any ref found for element <b>%s</b>',
		'ExampleAnyCodeOrIdFoundIntoDictionnary' => 'Any code (or id) found into dictionnary <b>%s</b>',
		'CSVFormatDesc' => '<b>Comma Separated Value</b> file format (.csv).<br>This is a text file format where fields are separated by separator [ %s ]. If separator is found inside a field content, field is rounded by round character [ %s ]. Escape character to escape round character is [ %s ].',
		'Excel95FormatDesc' => '<b>Excel</b> file format (.xls)<br>This is native Excel 95 format (BIFF5).',
		'Excel2007FormatDesc' => '<b>Excel</b> file format (.xlsx)<br>This is native Excel 2007 format (SpreadsheetML).',
		'TsvFormatDesc' => '<b>Tab Separated Value</b> file format (.tsv)<br>This is a text file format where fields are separated by a tabulator [tab].',
		'ExportFieldAutomaticallyAdded' => 'Field <b>%s</b> was automatically added. It will avoid you to have similar lines to be treated as duplicate records (with this field added, all ligne will own its own id and will differ).',
		'CsvOptions' => 'Csv Options',
		'Separator' => 'Separator',
		'Enclosure' => 'Enclosure',
		'SuppliersProducts' => 'Suppliers Products'
);
?>