<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$mails = array(
		'CHARSET' => 'UTF-8',
		'Mailing' => 'Mailing',
		'EMailing' => 'E-mailing',
		'Mailings' => 'Mailings',
		'EMailings' => 'E-mailings',
		'AllEMailings' => 'All eMailings',
		'MailCard' => 'E-mail kaart',
		'MailTargets' => 'Doelen',
		'MailRecipients' => 'Ontvangers',
		'MailRecipient' => 'Ontvanger',
		'MailTitle' => 'Titel',
		'MailFrom' => 'Afzender',
		'MailErrorsTo' => 'Fouten',
		'MailReply' => 'Antwoord op',
		'MailTo' => 'Ontvanger(s)',
		'MailCC' => 'Kopiëren naar',
		'MailCCC' => 'Cached kopie aan',
		'MailTopic' => 'EMail onderwerp',
		'MailText' => 'Bericht',
		'MailFile' => 'Bijgevoegde bestanden',
		'MailMessage' => 'EMail bericht',
		'ShowEMailing' => 'Toon mailing',
		'ListOfEMailings' => 'Lijst van mailings',
		'NewMailing' => 'Nieuwe mailing',
		'EditMailing' => 'Bewerk mailing',
		'ResetMailing' => 'Resend emailing',
		'DeleteMailing' => 'Verwijder mailing',
		'DeleteAMailing' => 'Verwijder een mailing',
		'PreviewMailing' => 'Voorbeeld mailing',
		'PrepareMailing' => 'Mailing voorbereiden',
		'CreateMailing' => 'Maak mailing',
		'MailingDesc' => 'Deze pagina laat u toe om een mailing te sturen naar een groep van mensen.',
		'MailingResult' => 'Resultaat verzonden E-mails',
		'TestMailing' => 'Test mailing',
		'ValidMailing' => 'Bevestig mailing',
		'ApproveMailing' => 'Mailing goedkeuren',
		'MailingStatusDraft' => 'Ontwerp',
		'MailingStatusValidated' => 'Gevalideerd',
		'MailingStatusApproved' => 'Goedgekeurd',
		'MailingStatusSent' => 'Verstuurd',
		'MailingStatusSentPartialy' => 'Gedeeltelijk verzonden',
		'MailingStatusSentCompletely' => 'Volledig verzonden',
		'MailingStatusError' => 'Fout',
		'MailingStatusNotSent' => 'Niet verzonden',
		'MailSuccessfulySent' => 'E-mail succesvol verzonden (van %s naar %s)',
		'MailingSuccessfullyValidated' => 'EMailing successfully validated',
		'MailUnsubcribe' => 'Unsubscribe',
		'Unsuscribe' => 'Unsubscribe',
		'MailingStatusNotContact' => 'Don\'t contact anymore',
		'ErrorMailRecipientIsEmpty' => 'E-mailadres ontvanger is leeg',
		'WarningNoEMailsAdded' => 'Geen nieuwe E-mail toe te voegen aan de ontvangerslijst.',
		'ConfirmValidMailing' => 'Weet u zeker dat u deze mailing wilt valideren om te verzenden?',
		'ConfirmResetMailing' => 'Warning, by reinitializing emailing <b>%s</b>, you allow to make a mass sending of this email another time. Are you sure you this is what you want to do ?',
		'ConfirmDeleteMailing' => 'Weet u zeker dat u deze mailing wilt verwijderen?',
		'NbOfRecipients' => 'Aantal ontvangers',
		'NbOfUniqueEMails' => 'Aantal unieke e-mails',
		'NbOfEMails' => 'Aantal e-mails',
		'TotalNbOfDistinctRecipients' => 'Aantal afzonderlijke ontvangers',
		'NoTargetYet' => 'Nog geen ontvangers gedefiniëerd (Ga op het tabblad "Ontvangers")',
		'AddRecipients' => 'Ontvangers toevoegen',
		'RemoveRecipient' => 'Verwijder ontvanger',
		'CommonSubstitutions' => 'Common substitutions',
		'YouCanAddYourOwnPredefindedListHere' => 'Om uw email selector module te creëren, zie htdocs/core/modules/mailings/README.',
		'EMailTestSubstitutionReplacedByGenericValues' => 'Bij het gebruik van test-modus, substituties variabelen worden vervangen door algemene waarden',
		'MailingAddFile' => 'Bestand toevoegen',
		'NoAttachedFiles' => 'Geen bijgevoegde bestanden',
		'BadEMail' => 'Bad value for EMail',
		'CloneEMailing' => 'Clone Emailing',
		'ConfirmCloneEMailing' => 'Are you sure you want to clone this emailing ?',
		'CloneContent' => 'Clone message',
		'CloneReceivers' => 'Cloner recipients',
		'DateLastSend' => 'Date of last sending',
		'DateSending' => 'Date sending',
		'SentTo' => 'Sent to <b>%s</b>',
		'MailingStatusRead' => 'Read',
		'CheckRead' => 'Read Receipt',
		'YourMailUnsubcribeOK' => 'The email <b>%s</b>  is correctly unsubcribe from mailing list',
		'MailtoEMail' => 'Hyper link to email',
		'ActivateCheckRead' => 'Allow to use the Read receipt tracker and the unsubcribe link',
		'ActivateCheckReadKey' => 'Key use to encrypt URL use for Read Receipt and unsubcribe function',
		// Libelle des modules de liste de destinataires mailing
		'MailingModuleDescContactCompanies' => 'Contacten van alle derde partijen (klant, potentiële klant, leverancier, ...)',
		'MailingModuleDescSpeedealingUsers' => 'Speedealing users',
		'MailingModuleDescFundationMembers' => 'Foundation members with emails',
		'MailingModuleDescEmailsFromFile' => 'E-mails van een tekstbestand (e-mail, naam, achternaam, commentaar)',
		'MailingModuleDescEmailsFromUser' => 'EMails from user input (email;lastname;firstname;other)',
		'MailingModuleDescContactsCategories' => 'Derde partijen met e-mails (per categorie)',
		'MailingModuleDescSpeedealingContractsLinesExpired' => 'Third parties with expired contract\'s lines',
		'MailingModuleDescContactsByCompanyCategory' => 'Contacts of third parties (by third parties category)',
		'MailingModuleDescMembersCategories' => 'Foundation members (by categories)',
		'MailingModuleDescContactsByFunction' => 'Contacts of third parties (by position/function)',
		'LineInFile' => 'Regel %s in bestand',
		'RecipientSelectionModules' => 'Omschreven verzoeken om ontvangers te selecteren',
		'MailSelectedRecipients' => 'Geselecteerde ontvangers',
		'MailingArea' => 'Mailing gebied',
		'LastMailings' => 'Laatste %s mailings',
		'TargetsStatistics' => 'Statistieken ontvangers',
		'NbOfCompaniesContacts' => 'Unieke contacten van bedrijven',
		'MailNoChangePossible' => 'Ontvangers voor een gevalideerde mailing kan niet meer worden gewijzigd',
		'SearchAMailing' => 'Zoek een mailing',
		'SendMailing' => 'Stuur mailing',
		'SendMail' => 'Stuur een e-mailbericht',
		'SentBy' => 'Verzonden door',
		'MailingNeedCommand' => 'Om veiligheidsredenen kan het verzendenvan een mailing enkel uitgevoerd worden vanaf command-line. Vraag aan de administrator voor deze mailing naar alle ontvangers te versturen:',
		'MailingNeedCommand2' => 'U kunt ze echter online sturen door het toevoegen van parameter MAILING_LIMIT_SENDBYWEB met een maximale waarde van het aantal e-mails die u wilt verzenden per sessie.',
		'ConfirmSendingEmailing' => 'Weet u zeker dat u deze mailing wilt verzenden? <br> Online verzenden van mailings zijn door veiligheidredenen beperkt om naar <b>%s</b> ontvangers sturen per sessie.',
		'LimitSendingEmailing' => 'On line sending of emailings are limited for security and timeout reasons to <b>%s</b> recipients by sending session.',
		'TargetsReset' => 'Verwijder lijst',
		'ToClearAllRecipientsClickHere' => 'Als u de lijst van ontvangers van deze mailing wilt verwijderen, klik op de knop',
		'ToAddRecipientsChooseHere' => 'Om ontvangers toe te voegen, kiest u in deze lijsten',
		'NbOfEMailingsReceived' => 'Massa mailings ontvangen',
		'IdRecord' => 'Record ID',
		'DeliveryReceipt' => 'Ontvangstbewijs',
		'YouCanUseCommaSeparatorForSeveralRecipients' => 'You can use the <b>comma</b> separator to specify several recipients.',
		'TagCheckMail' => 'Track mail opening',
		'TagUnsubscribe' => 'Unsubscribe link',
		'TagSignature' => 'Signature sending user',
		'TagMailtoEmail' => 'Recipient EMail',
		// Module Notifications
		'Notifications' => 'Berichtgevingen',
		'NoNotificationsWillBeSent' => 'Geen e-mail berichtgevingen staan gepland voor dit evenement en bedrijf',
		'ANotificationsWillBeSent' => '1 berichtgeving zal worden verzonden per e-mail',
		'SomeNotificationsWillBeSent' => '%s berichtgevingen worden verzonden per e-mail',
		'AddNewNotification' => 'Activeer een nieuw verzoek van berichtgeving',
		'ListOfActiveNotifications' => 'Lijst van alle actieve berichtgevingen',
		'ListOfNotificationsDone' => 'List all email notifications sent'
);
?>