<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$other = array(
		'CHARSET' => 'UTF-8',
		'SecurityCode' => 'Beveiligingscode',
		'Calendar' => 'Calendar',
		'AddTrip' => 'Verplaatsing toevoegen',
		'Tools' => 'Gereedschap',
		'ToolsDesc' => 'This area is dedicated to group miscellaneous tools not available into other menu entries.<br><br>Those tools can be reached from menu on the side.',
		'Birthday' => 'Verjaardag',
		'BirthdayDate' => 'Datum verjaardag',
		'DateToBirth' => 'Geboortedatum',
		'BirthdayAlertOn' => 'birthday alert active',
		'BirthdayAlertOff' => 'birthday alert inactive',
		'Notify_FICHINTER_VALIDATE' => 'Valideer interventie',
		'Notify_BILL_VALIDATE' => 'Valideer factuur',
		'Notify_ORDER_SUPPLIER_APPROVE' => 'Supplier order approved',
		'Notify_ORDER_SUPPLIER_REFUSE' => 'Supplier order refused',
		'Notify_ORDER_VALIDATE' => 'Customer order validated',
		'Notify_PROPAL_VALIDATE' => 'Customer proposal validated',
		'Notify_WITHDRAW_TRANSMIT' => 'Transmission withdrawal',
		'Notify_WITHDRAW_CREDIT' => 'Credit withdrawal',
		'Notify_WITHDRAW_EMIT' => 'Perform withdrawal',
		'Notify_ORDER_SENTBYMAIL' => 'Customer order sent by mail',
		'Notify_COMPANY_CREATE' => 'Third party created',
		'Notify_PROPAL_SENTBYMAIL' => 'Commercial proposal sent by mail',
		'Notify_ORDER_SENTBYMAIL' => 'Customer order sent by mail',
		'Notify_BILL_PAYED' => 'Customer invoice payed',
		'Notify_BILL_CANCEL' => 'Customer invoice canceled',
		'Notify_BILL_SENTBYMAIL' => 'Customer invoice sent by mail',
		'Notify_ORDER_SUPPLIER_VALIDATE' => 'Supplier order validated',
		'Notify_ORDER_SUPPLIER_SENTBYMAIL' => 'Supplier order sent by mail',
		'Notify_BILL_SUPPLIER_VALIDATE' => 'Supplier invoice validated',
		'Notify_BILL_SUPPLIER_PAYED' => 'Supplier invoice payed',
		'Notify_BILL_SUPPLIER_SENTBYMAIL' => 'Supplier invoice sent by mail',
		'Notify_CONTRACT_VALIDATE' => 'Contract validated',
		'Notify_FICHEINTER_VALIDATE' => 'Intervention validated',
		'Notify_SHIPPING_VALIDATE' => 'Shipping validated',
		'Notify_SHIPPING_SENTBYMAIL' => 'Shipping sent by mail',
		'Notify_MEMBER_VALIDATE' => 'Member validated',
		'Notify_MEMBER_SUBSCRIPTION' => 'Member subscribed',
		'Notify_MEMBER_RESILIATE' => 'Member resiliated',
		'Notify_MEMBER_DELETE' => 'Member deleted',
		'NbOfAttachedFiles' => 'Aantal bijgevoegde bestanden / documenten',
		'TotalSizeOfAttachedFiles' => 'Totale omvang van de bijgevoegde bestanden / documenten',
		'MaxSize' => 'Maximale grootte',
		'AttachANewFile' => 'Voeg een nieuw bestand / document toe',
		'LinkedObject' => 'Gekoppeld object',
		'Miscellanous' => 'Diversen',
		'NbOfActiveNotifications' => 'Aantal aanmeldingen',
		'PredefinedMailTest' => 'This is a test mail.\nThe two lines are separated by a carriage return.\n\n__SIGNATURE__',
		'PredefinedMailTestHtml' => 'This is a <b>test</b> mail (the word test must be in bold).<br>The two lines are separated by a carriage return.<br><br>__SIGNATURE__',
		'PredefinedMailContentSendInvoice' => 'You will find here the invoice __FACREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendInvoiceReminder' => 'We would like to warn you that the invoice  __FACREF__ seems to not being payed. So this is the invoice in attachment again, as a reminder.\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendProposal' => 'You will find here the commercial propoal __PROPREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendOrder' => 'You will find here the order __ORDERREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierOrder' => 'You will find here our order __ORDERREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierInvoice' => 'You will find here the invoice __FACREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendShipping' => 'You will find here the shipping __SHIPPINGREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendFichInter' => 'You will find here the intervention __FICHINTERREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'DemoDesc' => 'Speedealing is geen compacte ERP maar is opgebouwd uit verschillende functionele modules. Een demo waarin alle modules zijn geactiveerd heeft geen zin, omdat niet alle modules in praktijk worden gebruikt. Het kan echter zijn dat alle modules wel worden gebruikt, dus zijn er verschillende demo-profielen beschikbaar.',
		'ChooseYourDemoProfil' => 'Kies een demo profiel die overeenkomt met uw activiteit ...',
		'DemoFundation' => 'Leden beheren van een vereniging',
		'DemoFundation2' => 'Beheer van leden en een bankrekening van een vereniging',
		'DemoCompanyServiceOnly' => 'Het beheren van een freelance activiteit met enkel diensten als verkoop',
		'DemoCompanyShopWithCashDesk' => 'Beheren van een winkel met een kassa',
		'DemoCompanyProductAndStocks' => 'Het beheren van een kleine of middelgrote onderneming met als hoofdzaak het verkopen van producten',
		'DemoCompanyAll' => 'Het beheren van een kleine of middelgrote onderneming met meerdere activiteiten (alle modules)',
		'GoToDemo' => 'Ga naar de demo',
		'CreatedBy' => 'Gemaakt door %s',
		'ModifiedBy' => 'Gewijzigd door %s',
		'ValidatedBy' => 'Gevalideerd door %s',
		'CanceledBy' => 'Geannuleerd door %s',
		'ClosedBy' => 'Gesloten door %s',
		'FileWasRemoved' => 'Bestand is verwijderd',
		'DirWasRemoved' => 'Directorie is verwijderd',
		'FeatureNotYetAvailableShort' => 'Beschikbaar in een volgende versie',
		'FeatureNotYetAvailable' => 'Functie nog niet beschikbaar in deze versie',
		'FeatureExperimental' => 'Experimentele functie. Niet stabiel in deze versie',
		'FeatureDevelopment' => 'Ontwikkeling functie. Niet stabiel in deze versie',
		'FeaturesSupported' => 'Functies ondersteund',
		'Width' => 'Breedte',
		'Height' => 'Hoogte',
		'Depth' => 'Diepte',
		'Top' => 'Top',
		'Bottom' => 'Bottom',
		'Left' => 'Left',
		'Right' => 'Right',
		'CalculatedWeight' => 'Calculated weight',
		'CalculatedVolume' => 'Calculated volume',
		'Weight' => 'Gewicht',
		'TotalWeight' => 'Totaal gewicht',
		'WeightUnitton' => 'ton',
		'WeightUnitkg' => 'kg',
		'WeightUnitg' => 'g',
		'WeightUnitmg' => 'mg',
		'WeightUnitpound' => 'pound',
		'Length' => 'Length',
		'LengthUnitm' => 'm',
		'LengthUnitdm' => 'dm',
		'LengthUnitcm' => 'cm',
		'LengthUnitmm' => 'mm',
		'Surface' => 'Area',
		'SurfaceUnitm2' => 'm2',
		'SurfaceUnitdm2' => 'dm2',
		'SurfaceUnitcm2' => 'cm2',
		'SurfaceUnitmm2' => 'mm2',
		'SurfaceUnitfoot2' => 'ft2',
		'SurfaceUnitinch2' => 'in2',
		'Volume' => 'Volume',
		'TotalVolume' => 'Totaal volume',
		'VolumeUnitm3' => 'm3',
		'VolumeUnitdm3' => 'dm3',
		'VolumeUnitcm3' => 'cm3',
		'VolumeUnitmm3' => 'mm3',
		'VolumeUnitfoot3' => 'ft3',
		'VolumeUnitinch3' => 'in3',
		'VolumeUnitounce' => 'ounce',
		'VolumeUnitlitre' => 'litre',
		'VolumeUnitgallon' => 'gallon',
		'Size' => 'grootte',
		'SizeUnitm' => 'm',
		'SizeUnitdm' => 'dm',
		'SizeUnitcm' => 'cm',
		'SizeUnitmm' => 'mm',
		'SizeUnitinch' => 'inch',
		'SizeUnitfoot' => 'foot',
		'SizeUnitpoint' => 'point',
		'BugTracker' => 'Bug tracker',
		'SendNewPasswordDesc' => 'Dit formulier laat u toe om een nieuwe wachtwoord aan te vragen. Het zal worden verstuurd naar uw e-mailadres. <br> Verandering van het wachtwoord zal enkel gebeuren na het klikken op de bevestigingslink van deze mail. <br> Controleer uw e-mail ontvanger.',
		'BackToLoginPage' => 'Naar login pagina',
		'AuthenticationDoesNotAllowSendNewPassword' => 'De verificatie van Speedealing is ingesteld op <b>%s</b>.<br> In deze modus kan Speedealing uw wachtwoord niet weten of wijzigen. <br> Neem contact op met uw systeembeheerder voor het wijzigen van uw wachtwoord.',
		'EnableGDLibraryDesc' => 'Install or enable GD library with your PHP for use this option.',
		'EnablePhpAVModuleDesc' => 'You need to install a module compatible with your anti-virus. (Clamav : php4-clamavlib ou php5-clamavlib)',
		'ProfIdShortDesc' => '<b>Prof Id %s</b> is an information depending on third party country.<br>For example, for country <b>%s</b>, it\'s code <b>%s</b>.',
		'SpeedealingDemo' => 'Speedealing ERP/CRM demo',
		'StatsByNumberOfUnits' => 'Statistieken van het aantal eenheden',
		'StatsByNumberOfEntities' => 'Statistieken van het aantal verwezen entiteiten',
		'NumberOfProposals' => 'Aantal offertes op de laatste 12 maanden',
		'NumberOfCustomerOrders' => 'Aantal klantenbestellingen op de laatste 12 maanden',
		'NumberOfCustomerInvoices' => 'Aantal facturen klanten op de laatste 12 maanden',
		'NumberOfSupplierInvoices' => 'Aantal facturen leveranciers op de laatste 12 maanden',
		'NumberOfUnitsProposals' => 'Aantal eenheden op offertes van de afgelopen 12 maanden',
		'NumberOfUnitsCustomerOrders' => 'Aantal eenheden van klantenbestellingen op de laatste 12 maanden',
		'NumberOfUnitsCustomerInvoices' => 'Aantal eenheden van facturen klanten op de laatste 12 maanden',
		'NumberOfUnitsSupplierInvoices' => 'Aantal eenheden van facturen leveranciers op de laatste 12 maanden',
		'EMailTextInterventionValidated' => 'The intervention %s has been validated.',
		'EMailTextInvoiceValidated' => 'The invoice %s has been validated.',
		'EMailTextProposalValidated' => 'The proposal %s has been validated.',
		'EMailTextOrderValidated' => 'The order %s has been validated.',
		'EMailTextOrderApproved' => 'Bestelling %s goedgekeurd',
		'EMailTextOrderApprovedBy' => 'Bestelling % is goedgekeurd door %s',
		'EMailTextOrderRefused' => 'Bestelling %s geweigerd',
		'EMailTextOrderRefusedBy' => 'Bestelling %s geweigerd door %s',
		'ImportedWithSet' => 'Importation data set',
		'SpeedealingNotification' => 'Automatic notification',
		'ResizeDesc' => 'Enter new width <b>OR</b> new height. Ratio will be kept during resizing...',
		'NewLength' => 'New width',
		'NewHeight' => 'New height',
		'NewSizeAfterCropping' => 'New size after cropping',
		'DefineNewAreaToPick' => 'Define new area on image to pick (left click on image then drag until you reach the opposite corner)',
		'CurrentInformationOnImage' => 'This tool was designed to help you to resize or crop an image. This is informations on current edited image',
		'ImageEditor' => 'Image editor',
		'YouReceiveMailBecauseOfNotification' => 'You receive this message because your email has been added to list of targets to be informed of particular events into %s software of %s.',
		'YouReceiveMailBecauseOfNotification2' => 'This event is the following:',
		'ThisIsListOfModules' => 'This is a list of modules preselected by this demo profile (only most common modules are visible in this demo). Edit this to have a more personalized demo and click on "Start".',
		'ClickHere' => 'Click here',
		'UseAdvancedPerms' => 'Use the advanced permissions of some modules',
		'FileFormat' => 'File format',
		'SelectAColor' => 'Choose a color',
		'AddFiles' => 'Add Files',
		'StartUpload' => 'Start upload',
		'CancelUpload' => 'Cancel upload',
		'FileIsTooBig' => 'Files is too big',
		'PleaseBePatient' => 'Please be patient...',
		////////// Calendar common //////////
		'AddCalendarEntry' => 'Voeg item toe in kalender %s',
		'NewCompanyToSpeedealing' => 'Company %s added into Speedealing',
		'ContractValidatedInSpeedealing' => 'Contract %s validated in Speedealing',
		'ContractCanceledInSpeedealing' => 'Contract %s canceled in Speedealing',
		'ContractClosedInSpeedealing' => 'Contract %s closed in Speedealing',
		'PropalClosedSignedInSpeedealing' => 'Proposal %s signed in Speedealing',
		'PropalClosedRefusedInSpeedealing' => 'Proposal %s refused in Speedealing',
		'PropalValidatedInSpeedealing' => 'Proposal %s validated in Speedealing',
		'InvoiceValidatedInSpeedealing' => 'Invoice %s validated in Speedealing',
		'InvoicePaidInSpeedealing' => 'Invoice %s changed to paid in Speedealing',
		'InvoiceCanceledInSpeedealing' => 'Invoice %s canceled in Speedealing',
		'PaymentDoneInSpeedealing' => 'Payment %s done in Speedealing',
		'CustomerPaymentDoneInSpeedealing' => 'Customer payment %s done in Speedealing',
		'SupplierPaymentDoneInSpeedealing' => 'Supplier payment %s done in Speedealing',
		'MemberValidatedInSpeedealing' => 'Member %s validated in Speedealing',
		'MemberResiliatedInSpeedealing' => 'Member %s resiliated in Speedealing',
		'MemberDeletedInSpeedealing' => 'Member %s deleted from Speedealing',
		'MemberSubscriptionAddedInSpeedealing' => 'Subscription for member %s added in Speedealing',
		'ShipmentValidatedInSpeedealing' => 'Shipment %s validated in Speedealing',
		////////// Export //////////
		'Export' => 'Export',
		'ExportsArea' => 'Export gebied',
		'AvailableFormats' => 'Beschikbare formaten',
		'LibraryUsed' => 'Librairy gebruikt',
		'LibraryVersion' => 'Versie',
		'ExportableDatas' => 'Exportable gegevens',
		'NoExportableData' => 'Geen gegevens exporteerbaar (geen modules geladen met exporteerbare gegevens, of het ontbreken van machtigingen)',
		'ToExport' => 'Export',
		'NewExport' => 'Nieuwe exportmogelijkheden',
		////////// External sites //////////
		'ExternalSites' => 'External sites'
);
?>