<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$projects = array(
		'CHARSET' => 'UTF-8',
		'Project' => 'Project',
		'Projects' => 'Projecten',
		'SharedProject' => 'Gezamenlijk project',
		'PrivateProject' => 'Contacts of project',
		'MyProjectsDesc' => 'This view is limited to projects you are a contact for (whatever is the type).',
		'ProjectsPublicDesc' => 'This view presents all projects you are allowed to read.',
		'ProjectsDesc' => 'This view presents all projects (your user permissions grant you permission to view everything).',
		'MyTasksDesc' => 'This view is limited to projects or tasks you are a contact for (whatever is the type).',
		'TasksPublicDesc' => 'This view presents all projects and tasks you are allowed to read.',
		'TasksDesc' => 'This view presents all projects and tasks (your user permissions grant you permission to view everything).',
		'Myprojects' => 'Mijn projecten',
		'ProjectsArea' => 'Projecten gebied',
		'NewProject' => 'Nieuw project',
		'AddProject' => 'Project toevoegen',
		'DeleteAProject' => 'Verwijder een project',
		'DeleteATask' => 'Verwijder een taak',
		'ConfirmDeleteAProject' => 'Weet u zeker dat u dit project wilt verwijderen?',
		'ConfirmDeleteATask' => 'Weet u zeker dat u deze taak wilt verwijderen?',
		'OfficerProject' => 'Projectleider',
		'LastProjects' => 'Laatste % projecten',
		'AllProjects' => 'Alle projecten',
		'ProjectsList' => 'Lijst van projecten',
		'ShowProject' => 'Toon project',
		'SetProject' => 'Instellen project',
		'NoProject' => 'Geen enkel project gedefinieerd',
		'NbOpenTasks' => 'Aantal open taken',
		'NbOfProjects' => 'Aantal projecten',
		'TimeSpent' => 'Bestede tijd',
		'TimesSpent' => 'Time spent',
		'RefTask' => 'Ref. taak',
		'LabelTask' => 'Label taak',
		'NewTimeSpent' => 'Nieuwe tijd',
		'MyTimeSpent' => 'Mijn tijd besteed',
		'MyTasks' => 'Mijn taken',
		'Tasks' => 'Taken',
		'Task' => 'Taak',
		'NewTask' => 'Nieuwe taak',
		'AddTask' => 'Toevoegen taak',
		'AddDuration' => 'Tijd toevoegen',
		'Activity' => 'Activiteit',
		'Activities' => 'Taken / activiteiten',
		'MyActivity' => 'Mijn activiteit',
		'MyActivities' => 'Mijn taken / activiteiten',
		'MyProjects' => 'Mijn projecten',
		'DurationEffective' => 'Effectieve looptijd',
		'Progress' => 'Progress',
		'Time' => 'Tijd',
		'ListProposalsAssociatedProject' => 'Lijst van de commerciële voorstellen in verband met het project',
		'ListOrdersAssociatedProject' => 'Lijst van de orders in verband met het project',
		'ListInvoicesAssociatedProject' => 'Lijst van de facturen in verband met het project',
		'ListPredefinedInvoicesAssociatedProject' => 'List of customer\'s predefined invoices associated with project',
		'ListSupplierOrdersAssociatedProject' => 'Lijst van de bestellingen bij leveranciers in verband met het project',
		'ListSupplierInvoicesAssociatedProject' => 'Lijst van de facturen bij leveranciers in verband met het project',
		'ListContractAssociatedProject' => 'Lijst van opdrachten in verband met het project',
		'ListFichinterAssociatedProject' => 'List of interventions associated with the project',
		'ListTripAssociatedProject' => 'List of trips and expenses associated with the project',
		'ListActionsAssociatedProject' => 'List of events associated with the project',
		'ActivityOnProjectThisWeek' => 'Activiteiten op project(en) van deze week',
		'ActivityOnProjectThisMonth' => 'Activiteiten op project(en) van deze maand',
		'ActivityOnProjectThisYear' => 'Activiteiten op projecten van dit jaar',
		'ChildOfTask' => 'Uitvoering in project / taak',
		'NotOwnerOfProject' => 'Geen eigenaar van dit project',
		'AffectedTo' => 'Uitgevoerd door',
		'CantRemoveProject' => 'This project can\'t be removed as it is referenced by some other objects (invoice, orders or other). See referers tab.',
		'ValidateProject' => 'Validate projet',
		'ConfirmValidateProject' => 'Are you sure you want to validate this project ?',
		'CloseAProject' => 'Close project',
		'ConfirmCloseAProject' => 'Are you sure you want to close this project ?',
		'ReOpenAProject' => 'Open project',
		'ConfirmReOpenAProject' => 'Are you sure you want to re-open this project ?',
		'ProjectContact' => 'Project contacts',
		'ActionsOnProject' => 'Events on project',
		'YouAreNotContactOfProject' => 'You are not a contact of this private project',
		'DeleteATimeSpent' => 'Delete time spent',
		'ConfirmDeleteATimeSpent' => 'Are you sure you want to delete this time spent ?',
		'DoNotShowMyTasksOnly' => 'See also tasks not allocated to me',
		'ShowMyTasksOnly' => 'View only tasks allocated to me',
		'TaskRessourceLinks' => 'Ressources',
		'ProjectsDedicatedToThisThirdParty' => 'Projects dedicated to this third party',
		'NoTasks' => 'No tasks for this project',
		'LinkedToAnotherCompany' => 'Linked to other third party',
		'TaskIsNotAffectedToYou' => 'Task not allocated to you',
		'ErrorTimeSpentIsEmpty' => 'Time spent is empty',
		'ThisWillAlsoRemoveTasks' => 'This action will also delete all tasks of project (<b>%s</b> tasks at the moment) and all inputs of time spent.',
		'IfNeedToUseOhterObjectKeepEmpty' => 'If some objects (invoice, order, ...), belonging to another third party, must be linked to the project to create, keep this empty to have the project being multi third parties.',
		'CloneProject' => 'Clone project',
		'CloneTasks' => 'Clone tasks',
		'CloneContacts' => 'Clone contacts',
		'CloneNotes' => 'Clone notes',
		'CloneFiles' => 'Clone joined files',
		'ConfirmCloneProject' => 'Are you sure to clone this project ?',
		'ProjectReportDate' => 'Change task date according project start date',
		'ErrorShiftTaskDate' => 'Impossible to shift task date according to new project start date',
		////////// Types de contacts //////////
		'TypeContact_project_internal_PROJECTLEADER' => 'Project leader',
		'TypeContact_project_external_PROJECTLEADER' => 'Project leader',
		'TypeContact_project_internal_CONTRIBUTOR' => 'Contributor',
		'TypeContact_project_external_CONTRIBUTOR' => 'Contributor',
		'TypeContact_project_task_internal_TASKEXECUTIVE' => 'Task executive',
		'TypeContact_project_task_external_TASKEXECUTIVE' => 'Task executive',
		'TypeContact_project_task_internal_CONTRIBUTOR' => 'Contributor',
		'TypeContact_project_task_external_CONTRIBUTOR' => 'Contributor',
		// Documents models
		'DocumentModelBaleine' => 'A complete project\'s report model (logo...)'
);
?>