<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Opslagplaats kaart',
		'Warehouse' => 'Opslagplaats',
		'Warehouses' => 'Warehouses',
		'NewWarehouse' => 'Nieuw opslagplaats / Stock gebied',
		'WarehouseEdit' => 'Modify warehouse',
		'MenuNewWarehouse' => 'Nieuw opslagplaats',
		'WarehouseOpened' => 'Opslagplaats geopend',
		'WarehouseClosed' => 'Opslagplaats gesloten',
		'WarehouseSource' => 'Bron opslagplaats',
		'WarehouseSourceNotDefined' => 'No warehouse defined,',
		'AddOne' => 'Add one',
		'WarehouseTarget' => 'Target opslagplaats',
		'ValidateSending' => 'Wissen verzenden',
		'CancelSending' => 'Verzending annuleren',
		'DeleteSending' => 'Verzenden verwijderen',
		'Stock' => 'Voorraad',
		'Stocks' => 'Voorraden',
		'Movement' => 'Beweging',
		'Movements' => 'bewegingen',
		'ErrorWarehouseRefRequired' => 'Opslagplaats "Ref." is verplicht',
		'ErrorWarehouseLabelRequired' => 'Opslagplaats etiket wordt vereist',
		'CorrectStock' => 'Aanpassen voorraad',
		'ListOfWarehouses' => 'Lijst van opslagplaatsen',
		'ListOfStockMovements' => 'Lijst van de voorraden',
		'StocksArea' => 'Voorraden gebied',
		'Location' => 'Locatie',
		'LocationSummary' => 'Korte naam locatie',
		'NumberOfProducts' => 'Totaal aantal producten',
		'LastMovement' => 'Laatste beweging',
		'LastMovements' => 'Laatste bewegingen',
		'Units' => 'Eenheden',
		'Unit' => 'Eenheid',
		'StockCorrection' => 'Voorraad aanpassing',
		'StockMovement' => 'Voorraadbeweging',
		'StockMovements' => 'Voorraadbewegingen',
		'NumberOfUnit' => 'Aantal eenheden',
		'UnitPurchaseValue' => 'Unit purchase price',
		'TotalStock' => 'Totaal in voorraad',
		'StockTooLow' => 'Voorraad te laag',
		'StockLowerThanLimit' => 'Stock lower than alert limit',
		'EnhancedValue' => 'Waarde',
		'PMPValue' => 'PMP waarde',
		'PMPValueShort' => 'WAP',
		'EnhancedValueOfWarehouses' => 'Opslagruimtes waarde',
		'UserWarehouseAutoCreate' => 'Maak een voorraad automatisch aan bij het aanmaken van een gebruiker',
		'QtyDispatched' => 'Hoeveelheid verzonden',
		'OrderDispatch' => 'Bestel dispatching',
		'RuleForStockManagementDecrease' => 'Regel voor voorraadbeheer daling',
		'RuleForStockManagementIncrease' => 'Regel voor voorraadbeheer verhogen',
		'DeStockOnBill' => 'Daling van de reële voorraad op de facturen / creditnota\'s',
		'DeStockOnValidateOrder' => 'Daling van de reële voorraad op bestellingen notities',
		'DeStockOnShipment' => 'Daling van de reële voorraad op overbrenging (aanbevolen)',
		'ReStockOnBill' => 'Toename echte voorraden op facturen / creditnota\'s',
		'ReStockOnValidateOrder' => 'Toename voorraden echt op bestellingen notities',
		'ReStockOnDispatchOrder' => 'Increase real stocks on manual dispatching into warehouses, after supplier order receiving',
		'OrderStatusNotReadyToDispatch' => 'Order has not yet or no more a status that allows dispatching of products in stock warehouses.',
		'StockDiffPhysicTeoric' => 'Reden voor het verschil voorraad fysieke en theoretische',
		'NoPredefinedProductToDispatch' => 'No predefined products for this object. So no dispatching in stock is required.',
		'DispatchVerb' => 'Dispatch',
		'StockLimitShort' => 'Limiet',
		'StockLimit' => 'Voorraad limiet voor signaleringen',
		'PhysicalStock' => 'Fysieke voorraad',
		'RealStock' => 'Reële voorraad',
		'TheoreticalStock' => 'Therocial voorraad',
		'VirtualStock' => 'Virtuele voorraad',
		'MininumStock' => 'Minimumvoorraad',
		'StockUp' => 'Voorraad op',
		'MininumStockShort' => 'Minimum voorraad',
		'StockUpShort' => 'Voorraad op',
		'IdWarehouse' => 'Id opslagplaats',
		'DescWareHouse' => 'Beschrijving opslagplaats',
		'LieuWareHouse' => 'Localisatie opslagplaats',
		'WarehousesAndProducts' => 'opslagplaatsen en producten',
		'AverageUnitPricePMPShort' => 'Weighted average input price',
		'AverageUnitPricePMP' => 'Weighted average input price',
		'SellPriceMin' => 'Selling Unit Price',
		'EstimatedStockValueSellShort' => 'Value to sell',
		'EstimatedStockValueSell' => 'Value to Sell',
		'EstimatedStockValueShort' => 'Input stock value',
		'EstimatedStockValue' => 'Input stock value',
		'DeleteAWarehouse' => 'Delete a warehouse',
		'ConfirmDeleteWarehouse' => 'Are you sure you want to delete the warehouse <b>%s</b> ?',
		'PersonalStock' => 'Personal stock %s',
		'ThisWarehouseIsPersonalStock' => 'This warehouse represents personal stock of %s %s',
		'SelectWarehouseForStockDecrease' => 'Choose warehouse to use for stock decrease',
		'SelectWarehouseForStockIncrease' => 'Choose warehouse to use for stock increase',
		'LastWaitingSupplierOrders' => 'Orders waiting for receptions'
);
?>