<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'Gebruikerskaart',
		'ContactCard' => 'Contactkaart',
		'GroupCard' => 'Groepskaart',
		'NoContactCard' => 'Geen contactkaart',
		'Permission' => 'Toestemming',
		'Permissions' => 'Toestemmingen',
		'EditPassword' => 'Wachtwoord bewerken',
		'SendNewPassword' => 'Stuur nieuw wachtwoord',
		'ReinitPassword' => 'Genereer een nieuw wachtwoord',
		'PasswordChangedTo' => 'Wachtwoord veranderd naar: %s',
		'SubjectNewPassword' => 'Uw nieuwe wachtwoord voor Dolibarr',
		'AvailableRights' => 'Verkrijgbare rechten',
		'OwnedRights' => 'Bezeten rechten',
		'GroupRights' => 'Groep machtigingen',
		'UserRights' => 'Gebruiker machtigingen',
		'UserGUISetup' => 'Gebruiker display setup',
		'DisableUser' => 'Maak gebruiker onbruikbaar',
		'DisableAUser' => 'Uitschakelen van een gebruiker',
		'DeleteUser' => 'Wissen',
		'DeleteAUser' => 'Verwijderen van een gebruiker',
		'DisableGroup' => 'Uitschakelen',
		'DisableAGroup' => 'Uitschakelen van een groep',
		'EnableAUser' => 'Activeer een gebruiker',
		'EnableAGroup' => 'Inschakelen van een groep',
		'DeleteGroup' => 'Wissen',
		'DeleteAGroup' => 'Verwijderen van een groep',
		'ConfirmDisableUser' => 'Weet u zeker dat u gebruiker <b>%s</b> wilt uitschakelen?',
		'ConfirmDisableGroup' => 'Weet u zeker dat u groep <b>%s</b> wilt uitschakelen?',
		'ConfirmDeleteUser' => 'Weet u zeker dat u gebruiker <b>%s</b> wilt verwijderen?',
		'ConfirmDeleteGroup' => 'Weet u zeker dat u groep <b>%s</b> wilt verwijderen?',
		'ConfirmEnableUser' => 'Weet u zeker dat u gebruiker <b>%s</b> wilt inschakelen?',
		'ConfirmEnableGroup' => 'Weet u zeker dat u groep <b>%s</b> wilt inschakelen?',
		'ConfirmReinitPassword' => 'Weet u zeker dat u voor gebruiker <b>%s</b> een nieuw wachtwoord wilt genereren?',
		'ConfirmSendNewPassword' => 'Weet u zeker dat u een nieuw wachtwoord wilt genereren en verzenden voor gebruiker <b>%s</b>?',
		'NewUser' => 'Nieuwe gebruiker',
		'CreateUser' => 'Creëer gebruiker',
		'SearchAGroup' => 'Zoek een groep',
		'SearchAUser' => 'Zoek een gebruiker',
		'LoginNotDefined' => 'Inloggen is niet gedefiniëerd.',
		'NameNotDefined' => 'Naam is niet gedefiniëerd.',
		'ListOfUsers' => 'Lijsten van gebruikers',
		'Administrator' => 'De administrator',
		'SuperAdministrator' => 'Super Administrator',
		'SuperAdministratorDesc' => 'Global administrator',
		'AdministratorDesc' => 'Administrator\'s entity',
		'DefaultRights' => 'Standaardtoestemmingen',
		'DefaultRightsDesc' => 'Definiëer hier standaardtoestemmingen die automatisch gegund zijn naar een nieuwe gecreëerde gebruiker.',
		'DolibarrUsers' => 'Dolibarr gebruikers',
		'LastName' => 'Naam',
		'FirstName' => 'Voornaam',
		'ListOfGroups' => 'Lijst van groepen',
		'NewGroup' => 'Nieuwe groep',
		'CreateGroup' => 'Groep maken',
		'RemoveFromGroup' => 'Verwijderen uit groep',
		'PasswordChangedAndSentTo' => 'Wachtwoord veranderd en verstuurd naar <b>%s</b>.',
		'PasswordChangeRequestSent' => 'Verzoek om wachtwoord te wijzigen van <b>%s</b> naar <b>%s</b>.',
		'MenuUsersAndGroups' => 'Gebruikers en groepen',
		'LastGroupsCreated' => 'Laatste %s gemaakte groepen',
		'LastUsersCreated' => 'Laatste %s gebruikers gecreëerd',
		'ShowGroup' => 'Toon groep',
		'ShowUser' => 'Toon gebruiker',
		'NonAffectedUsers' => 'Niet betrokken gebruikers',
		'UserModified' => 'Gebruiker met succes gewijzigd',
		'GroupModified' => 'Groep met succes gewijzigd',
		'PhotoFile' => 'Foto bestand',
		'UserWithDolibarrAccess' => 'Gebruiker met Dolibarr toegang',
		'ListOfUsersInGroup' => 'Lijst van gebruikers in deze groep',
		'ListOfGroupsForUser' => 'Lijst van groepen voor deze gebruiker',
		'UsersToAdd' => 'Gebruikers toe te voegen aan deze groep',
		'GroupsToAdd' => 'Groepen toe te voegen aan deze gebruiker',
		'NoLogin' => 'Geen login',
		'LinkToCompanyContact' => 'Link to third party / contact',
		'LinkedToDolibarrMember' => 'Link to member',
		'LinkedToDolibarrUser' => 'Link to Dolibarr user',
		'LinkedToDolibarrThirdParty' => 'Link to Dolibarr third party',
		'CreateDolibarrLogin' => 'Maak Dolibarr login',
		'CreateDolibarrThirdParty' => 'Create a third party',
		'LoginAccountDisable' => 'Dit account is uitgeschakeld, zet een nieuwe login om te activeren.',
		'LoginAccountDisableInDolibarr' => 'Account uitgeschakeld in Dolibarr.',
		'LoginAccountDisableInLdap' => 'Account uitgeschakeld in het domein.',
		'UsePersonalValue' => 'Gebruik persoonlijke waarde',
		'GuiLanguage' => 'Taal van de interface',
		'InternalUser' => 'Interne gebruiker',
		'MyInformations' => 'Mijn gegevens',
		'ExportDataset_user_1' => 'Dolibarr gebruikers en eigenschappen',
		'DomainUser' => 'Domeingebruikersaccount %s',
		'Reactivate' => 'Reactiveren',
		'CreateInternalUserDesc' => 'Dit formulier laat u toe om een interne gebruiker te maken binnen uw bedrijf. Als u een externe gebruiker (klant, leverancier, ...) wil maken, gebruik de knop "Creëer Dolibarr gebruiker" uit derde partij contactkaart.',
		'InternalExternalDesc' => 'Een <b>interne</b> gebruiker is een gebruiker die deel uitmaakt van uw bedrijf. <br> Een <b>externe</b> gebruiker is een klant, leverancier of andere. <br><br> In beide gevallen, machtigingen omschrijft de rechten op Dolibarr, ook externe gebruiker kan beschikken over een ander menu manager dan een interne gebruiker (Zie Home - Opstelling - Display)',
		'PermissionInheritedFromAGroup' => 'Toestemming verleend, omdat deze voort komt uit een bepaalde gebruikersgroep.',
		'Inherited' => 'Inherited',
		'UserWillBeInternalUser' => 'Created user will be an internal user (because not linked to a particular third party)',
		'UserWillBeExternalUser' => 'Created user will be an external user (because linked to a particular third party)',
		'IdPhoneCaller' => 'Beller ID (telefoon)',
		'UserLogged' => 'Gebruiker %s ingelogd',
		'UserLogoff' => 'User %s logout',
		'NewUserCreated' => 'Gebruiker %s gemaakt',
		'NewUserPassword' => 'Wachtwoord wijzigen voor %s',
		'EventUserModified' => 'Gebruiker %s bewerkt',
		'UserDisabled' => 'Gebruiker %s uitgeschakeld',
		'UserEnabled' => 'Gebruiker %s geactiveerd',
		'UserDeleted' => 'Gebruiker %s verwijderd',
		'NewGroupCreated' => 'Groep %s gemaakt',
		'GroupModified' => 'Groep met succes gewijzigd',
		'GroupDeleted' => 'Groep %s verwijderd',
		'ConfirmCreateContact' => 'Weet u zeker dat u een Dolibarr account wilt maken voor deze contactpersoon?',
		'ConfirmCreateLogin' => 'Weet u zeker dat u een Dolibarr account wilt maken voor dit lid?',
		'ConfirmCreateThirdParty' => 'Weet u zeker dat u een derde partij wilt maken voor dit lid?',
		'LoginToCreate' => 'Login te creëren',
		'NameToCreate' => 'Naam van derde partij te creëren',
		'YourRole' => 'Your roles',
		'YourQuotaOfUsersIsReached' => 'Your quota of active users is reached !',
		'NbOfUsers' => 'Nb of users',
		'DontDowngradeSuperAdmin' => 'Only a superadmin can downgrade a superadmin',
		'NewDatabase' => 'Nouvelle base de données',
		'CreateDatabase' => 'Créer la base de données',
		'ListOfDatabases' => 'Liste des bases de données',
		'ListOfUsersInDatabase' => 'Liste des utilisateurs liés à la base de données',
		'ListOfRolesInDatabase' => 'Liste des groupes liés à la base de données',
		'DeleteADatabase' => 'Suppression d\'une database',
		'ConfirmDatabase' => 'Êtes-vous sûr de vouloir supprimer la base de données <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Groupes non affectés à la base de données',
		'NonAffectedUsersDatabase' => 'Utilisateurs non affectés à la base de données',
		'Collaborators' => 'Collaborateurs',
		'Profiles' => 'Profils collaborateurs'
);
?>