<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$withdrawals = array(
		'CHARSET' => 'UTF-8',
		'StandingOrdersArea' => 'Permanente opdrachten gebied',
		'CustomersStandingOrdersArea' => 'Klanten permanente opdrachten gebied',
		'StandingOrders' => 'Permanente opdrachten',
		'StandingOrder' => 'Permanente opdrachten',
		'NewStandingOrder' => 'Nieuwe doorlopende opdracht',
		'StandingOrderToProcess' => 'To process',
		'StandingOrderProcessed' => 'Processed',
		'Withdrawals' => 'Intrekkingen',
		'Withdrawal' => 'Intrekking',
		'WithdrawalsReceipts' => 'Intrekking van aandelen',
		'WithdrawalReceipt' => 'Intrekking ontvangst',
		'WithdrawalReceiptShort' => 'Ontvangst',
		'LastWithdrawalReceipts' => 'Last %s intrekking van aandelen',
		'WithdrawedBills' => 'Withdrawed facturen',
		'WithdrawalsLines' => 'Opnemingen lijnen',
		'RequestStandingOrderToTreat' => 'Verzoek om permanente opdrachten te behandelen',
		'RequestStandingOrderTreated' => 'Verzoek om permanente opdrachten behandeld',
		'CustomersStandingOrders' => 'Klant permanente opdrachten',
		'CustomerStandingOrder' => 'Klant doorlopende opdracht',
		'NbOfInvoiceToWithdraw' => 'Aantal van de factuur met verzoek intrekken',
		'NbOfInvoiceToWithdrawWithInfo' => 'Nb of invoice with withdraw request for customers having defined bank account information',
		'InvoiceWaitingWithdraw' => 'Factuur wachten intrekken',
		'AmountToWithdraw' => 'Bedrag terug te trekken',
		'WithdrawsRefused' => 'Intrekt geweigerd',
		'NoInvoiceToWithdraw' => 'Geen klant factuur betaling modus "trekken" wacht. Ga op \'Trek\' lipje op factuur kaart te maken van een verzoek.',
		'ResponsibleUser' => 'Verantwoordelijke gebruiker',
		'WithdrawalsSetup' => 'Intrekking setup',
		'WithdrawStatistics' => 'Intrekt "statistieken',
		'WithdrawRejectStatistics' => 'Intrekken verwerpt \'statistieken',
		'LastWithdrawalReceipt' => 'Last %s intrekking van aandelen',
		'MakeWithdrawRequest' => 'Maak een verzoek intrekken',
		'ThirdPartyBankCode' => 'Derde bankcode',
		'ThirdPartyDeskCode' => 'Derde bureau code',
		'NoInvoiceCouldBeWithdrawed' => 'Geen factuur withdrawed met succes. Controleer of de factuur zijn op bedrijven met een geldige BAN.',
		'ClassCredited' => 'Classify gecrediteerd',
		'ClassCreditedConfirm' => 'Weet u zeker dat u wilt classificeren deze terugtrekking ontvangst als bijgeschreven op uw bankrekening?',
		'TransData' => 'Date Transmission',
		'TransMetod' => 'Method Transmission',
		'Send' => 'Send',
		'Lines' => 'Lines',
		'StandingOrderReject' => 'Issue a reject',
		'InvoiceRefused' => 'Invoice refused',
		'WithdrawalRefused' => 'Withdrawal Refused',
		'WithdrawalRefusedConfirm' => 'Are you sure you want to enter a withdrawal rejection for society',
		'RefusedData' => 'Date of rejection',
		'RefusedReason' => 'Reason for rejection',
		'RefusedInvoicing' => 'Billing the rejection',
		'NoInvoiceRefused' => 'Do not charge the rejection',
		'InvoiceRefused' => 'Invoice refused',
		'Status' => 'Status',
		'StatusUnknown' => 'Unknown',
		'StatusWaiting' => 'Waiting',
		'StatusTrans' => 'Transmitted',
		'StatusCredited' => 'Credited',
		'StatusRefused' => 'Refused',
		'StatusMotif0' => 'Unspecified',
		'StatusMotif1' => 'Provision insuffisante',
		'StatusMotif2' => 'Tirage conteste',
		'StatusMotif3' => 'No Withdrawal order',
		'StatusMotif4' => 'Customer Order',
		'StatusMotif5' => 'RIB inexploitable',
		'StatusMotif6' => 'Account without balance',
		'StatusMotif7' => 'Judicial Decision',
		'StatusMotif8' => 'Other reason',
		'CreateAll' => 'Withdraw all',
		'CreateGuichet' => 'Only office',
		'CreateBanque' => 'Only bank',
		'OrderWaiting' => 'Waiting for treatment',
		'NotifyTransmision' => 'Withdrawal Transmission',
		'NotifyEmision' => 'Withdrawal Emission',
		'NotifyCredit' => 'Withdrawal Credit',
		'NumeroNationalEmetter' => 'National Transmitter Number',
		'PleaseSelectCustomerBankBANToWithdraw' => 'Select information about customer bank account to withdraw',
		'WithBankUsingRIB' => 'For bank accounts using RIB',
		'WithBankUsingBANBIC' => 'For bank accounts using IBAN/BIC/SWIFT',
		'BankToReceiveWithdraw' => 'Bank account to receive withdraws',
		'CreditDate' => 'Credit on',
		'WithdrawalFileNotCapable' => 'Unable to generate withdrawal receipt file for your country',
		'ShowWithdraw' => 'Show Withdraw',
		'IfInvoiceNeedOnWithdrawPaymentWontBeClosed' => 'However, if invoice has at least one withdrawal payment not yet processed, it won\'t be set as payed to allow to manage withdrawal before.',
		'DoStandingOrdersBeforePayments' => 'This tabs allows you to request for a standing order. Once it will be finished, you can type the payment to close the invoice.',
		////// Notifications
		'InfoCreditSubject' => 'Payment of standing order %s by the bank',
		'InfoCreditMessage' => 'The standing order %s has been paid by the bank<br>Data of payment: %s',
		'InfoTransSubject' => 'Transmission of standing order %s to bank',
		'InfoTransMessage' => 'The standing order %s has been transmited to bank by %s %s.<br><br>',
		'InfoTransData' => 'Amount: %s<br>Metode: %s<br>Date: %s',
		'InfoFoot' => 'This is an automated message sent by Dolibarr',
		'InfoRejectSubject' => 'Standing order refused',
		'InfoRejectMessage' => 'Hello,<br><br>the standig order of invoice %s related to the company %s, with an amount of %s has been refused by the bank.<br><br>--<br>%$',
		'ModeWarning' => 'Option for real mode was not set, we stop after this simulation'
);
?>