<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$compta = array(
		'CHARSET' => 'UTF-8',
		'Accountancy' => 'Accountancy',
		'AccountancyCard' => 'Accountancy card',
		'Treasury' => 'Treasury',
		'MenuFinancial' => 'Financial',
		'TaxModuleSetupToModifyRules' => 'Go to <a href="%s">module setup</a> to modify rules for calculation',
		'OptionMode' => 'Option for accountancy',
		'OptionModeTrue' => 'Option Incomes-Expenses',
		'OptionModeVirtual' => 'Option Claims-Debts',
		'OptionModeTrueDesc' => 'In this context, the turnover is calculated over payments (date of payments). The validity of the figures is assured only if the book-keeping is scrutinized through the input/output on the accounts via invoices.',
		'OptionModeVirtualDesc' => 'In this context, the turnover is calculated over invoices (date of validation). When these invoices are due, whether they have been paid or not, they are listed in the turnover output.',
		'FeatureIsSupportedInInOutModeOnly' => 'Feature only available in CREDITS-DEBTS accountancy mode (See Accountancy module configuration)',
		'VATReportBuildWithOptionDefinedInModule' => 'Amounts shown here are calculated using rules defined by Tax module setup.',
		'Param' => 'Setup',
		'RemainingAmountPayment' => 'Amount payment remaining :',
		'AmountToBeCharged' => 'Total amount to pay :',
		'AccountsGeneral' => 'Accounts',
		'Account' => 'Account',
		'Accounts' => 'Accounts',
		'Accountparent' => 'Account parent',
		'Accountsparent' => 'Accounts parent',
		'BillsForSuppliers' => 'Bills for suppliers',
		'Income' => 'Income',
		'Outcome' => 'Expense',
		'ReportInOut' => 'Income / Expense',
		'ReportTurnover' => 'Turnover',
		'PaymentsNotLinkedToInvoice' => 'Payments not linked to any invoice, so not linked to any third party',
		'PaymentsNotLinkedToUser' => 'Payments not linked to any user',
		'Profit' => 'Profit',
		'Balance' => 'Balance',
		'Debit' => 'Debit',
		'Credit' => 'Credit',
		'Withdrawal' => 'Withdrawal',
		'Withdrawals' => 'Withdrawals',
		'AmountHTVATRealReceived' => 'Net collected',
		'AmountHTVATRealPaid' => 'Net paid',
		'VATToPay' => 'IVU ventas',
		'VATReceived' => 'IVU repercutido',
		'VATToCollect' => 'IVU compras',
		'VATSummary' => 'Balance de IVU',
		'LT2SummaryES' => 'IRPF Balance',
		'VATPaid' => 'IVU Pagado',
		'LT2PaidES' => 'IRPF Paid',
		'LT2CustomerES' => 'IRPF sales',
		'LT2SupplierES' => 'IRPF purchases',
		'VATCollected' => 'IVU recuperado',
		'ToPay' => 'To pay',
		'ToGet' => 'To get back',
		'TaxAndDividendsArea' => 'Tax, social contributions and dividends area',
		'SocialContribution' => 'Social contribution',
		'SocialContributions' => 'Social contributions',
		'MenuTaxAndDividends' => 'Taxes and dividends',
		'MenuSocialContributions' => 'Social contributions',
		'MenuNewSocialContribution' => 'New contribution',
		'NewSocialContribution' => 'New social contribution',
		'ContributionsToPay' => 'Contributions to pay',
		'AccountancyTreasuryArea' => 'Accountancy/Treasury area',
		'AccountancySetup' => 'Accountancy setup',
		'NewPayment' => 'New payment',
		'Payments' => 'Payments',
		'PaymentCustomerInvoice' => 'Customer invoice payment',
		'PaymentSupplierInvoice' => 'Supplier invoice payment',
		'PaymentSocialContribution' => 'Social contribution payment',
		'PaymentVat' => 'Pago IVU',
		'ListPayment' => 'List of payments',
		'ListOfPayments' => 'List of payments',
		'ListOfCustomerPayments' => 'List of customer payments',
		'ListOfSupplierPayments' => 'List of supplier payments',
		'DatePayment' => 'Payment date',
		'NewVATPayment' => 'Nuevo pago de IVU',
		'newLT2PaymentES' => 'New IRPF payment',
		'LT2PaymentES' => 'IRPF Payment',
		'LT2PaymentsES' => 'IRPF Payments',
		'VATPayment' => 'Pago IVU',
		'VATPayments' => 'Pagos IVU',
		'SocialContributionsPayments' => 'Pagos cargas sociales',
		'ShowVatPayment' => 'Ver pagos IVU',
		'TotalToPay' => 'Total to pay',
		'TotalVATReceived' => 'Total IVU percibido',
		'CustomerAccountancyCode' => 'Customer accountancy code',
		'SupplierAccountancyCode' => 'Supplier accountancy code',
		'AlreadyPaid' => 'Already paid',
		'AccountNumberShort' => 'Account number',
		'AccountNumber' => 'Account number',
		'NewAccount' => 'New account',
		'SalesTurnover' => 'Sales turnover',
		'ByThirdParties' => 'Bu third parties',
		'ByUserAuthorOfInvoice' => 'By invoice author',
		'AccountancyExport' => 'Accountancy export',
		'ErrorWrongAccountancyCodeForCompany' => 'Bad customer accountancy code for %s',
		'SuppliersProductsSellSalesTurnover' => 'The generated turnover by the sales of supplier\'s products.',
		'CheckReceipt' => 'Check deposit',
		'CheckReceiptShort' => 'Check deposit',
		'NewCheckReceipt' => 'New discount',
		'NewCheckDeposit' => 'New check deposit',
		'NewCheckDepositOn' => 'Create receipt for deposit on account: %s',
		'NoWaitingChecks' => 'No checks waiting for deposit.',
		'DateChequeReceived' => 'Check reception date',
		'NbOfCheques' => 'Nb of checks',
		'PaySocialContribution' => 'Pay a social contribution',
		'ConfirmPaySocialContribution' => 'Are you sure you want to classify this social contribution as paid?',
		'DeleteSocialContribution' => 'Delete a social contribution',
		'ConfirmDeleteSocialContribution' => 'Are you sure you want to delete this social contribution?',
		'ExportDataset_tax_1' => 'Social contributions and payments',
		'AnnualSummaryDueDebtMode' => 'Balance of income and expenses, annual summary, mode <b>%sClaims-Debts%s</b> said <b>Commitment accounting</b>.',
		'AnnualSummaryInputOutputMode' => 'Balance of income and expenses, annual summary, mode <b>%sIncomes-Expenses%s</b> said <b>cash accounting</b>.',
		'AnnualByCompaniesDueDebtMode' => 'Balance of income and expenses, detail by third parties, mode <b>%sClaims-Debts%s</b> said <b>Commitment accounting</b>.',
		'AnnualByCompaniesInputOutputMode' => 'Balance of income and expenses, detail by third parties, mode <b>%sIncomes-Expenses%s</b> said <b>cash accounting</b>.',
		'SeeReportInInputOutputMode' => 'See report <b>%sIncomes-Expenses%s</b> said <b>cash accounting</b> for a calculation on actual payments made',
		'SeeReportInDueDebtMode' => 'See report <b>%sClaims-Debts%s</b> said <b>commitment accounting</b> for a calculation on issued invoices',
		'RulesResultDue' => '- Los importes mostrados son importes totales<br>- Incluye las facturas, cargas e IVU debidos, que estén pagadas o no.<br>- Se basa en la fecha de validación para las facturas y el IVU y en la fecha de vencimiento para las cargas.<br>',
		'RulesResultInOut' => '- Los importes mostrados son importes totales<br>- Incluye los pagos realizados para las facturas, cargas e IVU.<br>- Se basa en la fecha de pago de las mismas.<br>',
		'RulesCADue' => '- It includes the client\'s due invoices whether they are paid or not. <br>- It is based on the validation date of these invoices. <br>',
		'RulesCAIn' => '- It includes all the effective payments of invoices received from clients.<br>- It is based on the payment date of these invoices<br>',
		'DepositsAreNotIncluded' => '- Deposit invoices are nor included',
		'DepositsAreIncluded' => '- Deposit invoices are included',
		'LT2ReportByCustomersInInputOutputModeES' => 'Report by third party IRPF',
		'VATReportByCustomersInInputOutputMode' => 'Informe por cliente del IVU repercutido y pagado (IVU pagado)',
		'VATReportByCustomersInDueDebtMode' => 'Informe por cliente del IVU repercutido y pagado (IVU debido)',
		'VATReportByQuartersInInputOutputMode' => 'Informe por tasa del IVU repercutido y pagado (IVU pagado)',
		'VATReportByQuartersInDueDebtMode' => 'Informe por tasa del IVU repercutido y pagado (IVU debido)',
		'SeeVATReportInInputOutputMode' => 'Ver el informe <b>%sIVU pagado%s</b> para un modo de cálculo estandard',
		'SeeVATReportInDueDebtMode' => 'Ver el informe <b>%sIVU debido%s</b> para un modo de cálculo con la opción sobre lo debido',
		'RulesVATInServices' => '- For services, the report includes the VAT regulations actually received or issued on the basis of the date of payment.<br>- For material assets, it includes the VAT invoices on the basis of the invoice date.',
		'RulesVATInProducts' => '- For material assets, it includes the VAT invoices on the basis of the invoice date.',
		'RulesVATDueServices' => '- For services, the report includes VAT invoices due, paid or not, based on the invoice date.',
		'RulesVATDueProducts' => '- For material assets, it includes the VAT invoices, based on the invoice date.',
		'OptionVatInfoModuleComptabilite' => 'Note: For material assets, it should use the date of delivery to be more fair.',
		'PercentOfInvoice' => '%%/invoice',
		'NotUsedForGoods' => 'Not used on goods',
		'ProposalStats' => 'Statistics on proposals',
		'OrderStats' => 'Statistics on orders',
		'InvoiceStats' => 'Statistics on bills',
		'Dispatch' => 'Dispatching',
		'Dispatched' => 'Dispatched',
		'ToDispatch' => 'To dispatch',
		'ThirdPartyMustBeEditAsCustomer' => 'Third party must be defined as a customer',
		'SellsJournal' => 'Sales Journal',
		'PurchasesJournal' => 'Purchases Journal',
		'DescSellsJournal' => 'Sales Journal',
		'DescPurchasesJournal' => 'Purchases Journal',
		'InvoiceRef' => 'Invoice ref.',
		'CodeNotDef' => 'Not defined',
		'AddRemind' => 'Dispatch available amount',
		'RemainToDivide' => 'Remain to dispatch :',
		'WarningDepositsNotIncluded' => 'Deposits invoices are not included in this version with this accountancy module.',
		'DatePaymentTermCantBeLowerThanObjectDate' => 'Payment term date can\'t be lower than object date.',
		'Pcg_version' => 'Pcg version',
		'Pcg_type' => 'Pcg type',
		'Pcg_subtype' => 'Pcg subtype',
		'Withdrawl' => 'Prélèvement',
		'Withdrawls' => 'Prélèvements',
		'ToGetBack' => 'A récupérer',
		'Journaux' => 'Journaux',
		'Piece' => 'Piece compta',
		'JournalNum' => 'Journal',
		'COMPTA_JOURNAL_SELL' => 'Numéro comptable du Journal des Achats',
		'COMPTA_JOURNAL_BUY' => 'Numéro comptable du Journal des Ventes',
		'COMPTA_PRODUCT_BUY_ACCOUNT' => 'Compte comptable par défaut pour produits achetés (si non défini sur fiche produit)',
		'COMPTA_PRODUCT_SOLD_ACCOUNT' => 'Compte comptable par défaut pour produits vendus (si non défini sur fiche produit)',
		'COMPTA_SERVICE_BUY_ACCOUNT' => 'Compte comptable par défaut pour services achetés (si non défini sur fiche service)',
		'COMPTA_SERVICE_SOLD_ACCOUNT' => 'Compte comptable par défaut pour services vendus (si non défini sur fiche service)',
		'COMPTA_VAT_ACCOUNT' => 'Compte comptable par défaut pour TVA (si non défini dans dictionnaire "Taux de TVA")',
		'COMPTA_ACCOUNT_CUSTOMER' => 'Compte comptable client par défaut (si non défini sur fiche tiers)',
		'COMPTA_ACCOUNT_SUPPLIER' => 'Compte comptable fournisseur par défaut (si non défini sur fiche tiers)',
);
?>