<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Auglýsing',
		'CommercialArea' => 'Eiðsvík',
		'CommercialCard' => 'Auglýsing kort',
		'CustomerArea' => 'Viðskiptavinir area',
		'Customer' => 'Viðskiptavinur',
		'Customers' => 'Viðskiptavinir',
		'Prospect' => 'Prospect',
		'Prospects' => 'Horfur',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Eyða aðgerð / verkefni',
		'NewAction' => 'Ný aðgerð / verkefni',
		'AddAction' => 'Bæta við aðgerðir / verkefni',
		'AddAnAction' => 'Bæta við óákveðinn greinir í ensku aðgerð / verkefni',
		'AddActionRendezVous' => 'Bæta við stefnumót verkefni',
		'Rendez-Vous' => 'Stefnumót',
		'ConfirmDeleteAction' => 'Ertu viss um að þú viljir eyða þessu verkefni?',
		'CardAction' => 'Aðgerð kort',
		'PercentDone' => 'Hlutfall lokið',
		'ActionOnCompany' => 'Verkefni um fyrirtæki',
		'ActionOnContact' => 'Verkefni um tengilið',
		'TaskRDV' => 'Fundir',
		'TaskRDVWith' => 'Fundur með %s',
		'ShowTask' => 'Sýna verkefni',
		'ShowAction' => 'Sýna aðgerðir',
		'ActionsReport' => 'Actions skýrslu',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Sölufulltrúi',
		'SalesRepresentatives' => 'Sölufulltrúi',
		'SalesRepresentativeFollowUp' => 'Sölufulltrúi (eftirfylgni)',
		'SalesRepresentativeSignature' => 'Sölufulltrúi (undirskrift)',
		'CommercialInterlocutor' => 'Auglýsing interlocutor',
		'ErrorWrongCode' => 'Rangt númer',
		'NoSalesRepresentativeAffected' => 'Nei einkum við sölufulltrúa fyrir áhrifum',
		'ShowCustomer' => 'Sýna viðskiptavinum',
		'ShowProspect' => 'Sýna horfur',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Listi yfir horfur',
		'ListOfCustomers' => 'Listi yfir viðskiptavini',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'Last %s  lokið verkefni',
		'LastRecordedTasks' => 'Síðast skráð verkefni',
		'LastActionsToDo' => 'Last %s  elstu aðgerðir ekki lokið',
		'DoneAndToDoActionsFor' => 'Lokið og til að gera verkefni fyrir %s',
		'DoneAndToDoActions' => 'Lokið og til að gera verkefni',
		'DoneActions' => 'Lauk aðgerðum',
		'DoneActionsFor' => 'Lauk aðgerðum á %s',
		'ToDoActions' => 'Ófullnægjandi aðgerðir',
		'ToDoActionsFor' => 'Ófullnægjandi aðgerðir til %s',
		'SendPropalRef' => 'Senda auglýsing tillögu %s',
		'SendOrderRef' => 'Senda til %s',
		'StatusNotApplicable' => 'Á ekki við',
		'StatusActionToDo' => 'Til að gera',
		'StatusActionDone' => 'Complete',
		'StatusActionInProcess' => 'Í vinnslu',
		'MyActionsAsked' => 'Aðgerðir sem ég hef skráð',
		'MyActionsToDo' => 'Actions ég að gera',
		'MyActionsDone' => 'Actions áhrif á mig',
		'TasksHistoryForThisContact' => 'Actions for this samband',
		'LastProspectDoNotContact' => 'Ekki hafa samband ekki',
		'LastProspectNeverContacted' => 'Aldrei samband',
		'LastProspectToContact' => 'Til að hafa samband',
		'LastProspectContactInProcess' => 'Hafðu í vinnslu',
		'LastProspectContactDone' => 'Hafðu gert',
		'DateActionPlanned' => 'Date aðgerð skipuleggjandi fyrir',
		'DateActionDone' => 'Date aðgerð lokið',
		'ActionAskedBy' => 'Aðgerð bað',
		'ActionAffectedTo' => 'Aðgerð áhrif til',
		'ActionDoneBy' => 'Aðgerð lokið við',
		'ActionUserAsk' => 'Skráð af',
		'ErrorStatusCantBeZeroIfStarted' => 'Ef <b>"Date</b> sviði <b>gert</b> \'er fyllt, aðgerð er hafin (eða búin),\' <b>Staða</b> \'svo sviði er ekki hægt að 0%%.',
		'ActionAC_TEL' => 'Símtal',
		'ActionAC_FAX' => 'Senda símbréfi',
		'ActionAC_PROP' => 'Senda tillögu með tölvupósti',
		'ActionAC_EMAIL' => 'Send Email',
		'ActionAC_RDV' => 'Fundir',
		'ActionAC_FAC' => 'Senda viðskiptavinur reikning í pósti',
		'ActionAC_REL' => 'Senda viðskiptavinur reikning í pósti (áminning)',
		'ActionAC_CLO' => 'Loka',
		'ActionAC_EMAILING' => 'Senda massi tölvupósti',
		'ActionAC_COM' => 'Senda viðskiptavina þess með pósti',
		'ActionAC_SHIP' => 'Senda skipum með pósti',
		'ActionAC_SUP_ORD' => 'Senda birgir röð í pósti',
		'ActionAC_SUP_INV' => 'Senda birgir reikning í pósti',
		'ActionAC_OTH' => 'Annað',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Prospect stöðu',
		'DraftPropals' => 'Drög auglýsing tillögur',
		'SearchPropal' => 'Leita að auglýsing tillögu'
);
?>