<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$contracts = array(
		'CHARSET' => 'UTF-8',
		'ContractsArea' => 'Samningar area',
		'ListOfContracts' => 'Listi yfir samninga',
		'LastContracts' => 'Last %s  breytt samninga',
		'AllContracts' => 'Allir samningar',
		'ContractCard' => 'Samningur kort',
		'ContractStatus' => 'Samningur stöðu',
		'ContractStatusNotRunning' => 'Ekki í keyrslu',
		'ContractStatusRunning' => 'Running',
		'ContractStatusDraft' => 'Víxill',
		'ContractStatusValidated' => 'Staðfestar',
		'ContractStatusClosed' => 'Loka',
		'ServiceStatusInitial' => 'Ekki í keyrslu',
		'ServiceStatusRunning' => 'Running',
		'ServiceStatusNotLate' => 'Running, ekki útrunnið',
		'ServiceStatusNotLateShort' => 'Ekki lokið',
		'ServiceStatusLate' => 'Running, falla úr gildi',
		'ServiceStatusLateShort' => 'Útrunnið',
		'ServiceStatusClosed' => 'Loka',
		'ServicesLegend' => 'Þjónusta þjóðsaga',
		'Contracts' => 'Samningar',
		'Contract' => 'Samningur',
		'NoContracts' => 'Engir samningar',
		'MenuServices' => 'Þjónusta',
		'MenuInactiveServices' => 'Þjónusta ekki virk',
		'MenuRunningServices' => 'Running þjónusta',
		'MenuExpiredServices' => 'Útrunninn þjónusta',
		'MenuClosedServices' => 'Lokað þjónusta',
		'NewContract' => 'Nýr samningur',
		'AddContract' => 'Bæta við samning',
		'SearchAContract' => 'Leita samning',
		'DeleteAContract' => 'Eyða samning',
		'CloseAContract' => 'Loka samning',
		'ConfirmDeleteAContract' => 'Ertu viss um að þú viljir eyða þessum samningi og alla þjónustu sína?',
		'ConfirmValidateContract' => 'Ertu viss um að þú viljir setja í gildi á þessum samningi?',
		'ConfirmCloseContract' => 'Þetta mun loka allri þjónustu (virkt eða ekki). Ertu viss um að þú viljir loka þessum samningi?',
		'ConfirmCloseService' => 'Ertu viss um að þú viljir loka þessum þjónustu <b>með%</b> dagsetning <b>s?</b>',
		'ValidateAContract' => 'Staðfesta samning',
		'ActivateService' => 'Virkja þjónusta',
		'ConfirmActivateService' => 'Ertu viss um að þú viljir virkja þessa þjónustu <b>með%</b> dagsetning <b>s?</b>',
		'RefContract' => 'Contract reference',
		'DateContract' => 'Samningur dagsetningu',
		'DateServiceActivate' => 'Þjónusta Virkjunardagsetning',
		'DateServiceUnactivate' => 'Þjónusta deactivation dagsetningu',
		'DateServiceStart' => 'Dagsetning fyrir byrjun þjónusta',
		'DateServiceEnd' => 'Dagsetning fyrir lok þjónusta',
		'ShowContract' => 'Sýna samning',
		'ListOfServices' => 'Listi yfir þjónustu',
		'ListOfInactiveServices' => 'Listi af ekki virka þjónusta',
		'ListOfExpiredServices' => 'Listi af útrunnum virkt þjónusta',
		'ListOfClosedServices' => 'Listi yfir loka þjónusta',
		'ListOfRunningContractsLines' => 'Listi yfir gangi samningur línur',
		'ListOfRunningServices' => 'Listi af hlaupandi þjónusta',
		'NotActivatedServices' => 'Óvirkur þjónustu (meðal gildi samninga)',
		'BoardNotActivatedServices' => 'Þjónusta til virkja meðal gildi samninga',
		'LastContracts' => 'Last %s  breytt samninga',
		'LastActivatedServices' => 'Last %s  virkt þjónusta',
		'LastModifiedServices' => 'Last %s  breytt þjónusta',
		'EditServiceLine' => 'Breyta þjónustu línu',
		'ContractStartDate' => 'Upphafsdagur',
		'ContractEndDate' => 'Lokadagur',
		'DateStartPlanned' => 'Fyrirhugaður upphafsdagur',
		'DateStartPlannedShort' => 'Fyrirhugaður upphafsdagur',
		'DateEndPlanned' => 'Áætlaðir lokadagur',
		'DateEndPlannedShort' => 'Áætlaðir lokadagur',
		'DateStartReal' => 'Real upphafsdagur',
		'DateStartRealShort' => 'Real upphafsdagur',
		'DateEndReal' => 'Real lokadagur',
		'DateEndRealShort' => 'Real lokadagur',
		'NbOfServices' => 'ATH þjónusta',
		'CloseService' => 'Loka þjónusta',
		'ServicesNomberShort' => '%s  þjónustu (s)',
		'RunningServices' => 'Running þjónusta',
		'BoardRunningServices' => 'Útrunnið hlaupandi þjónusta',
		'ServiceStatus' => 'Staða þjónustu',
		'DraftContracts' => 'Drög samninga',
		'CloseRefusedBecauseOneServiceActive' => 'Samningur getur ekki verið lokað þar sem það er að minnsta kosti einn opinn þjónusta á það',
		'CloseAllContracts' => 'Lokaðu öllum samning línur',
		'DeleteContractLine' => 'Eyða samning línu',
		'ConfirmDeleteContractLine' => 'Ertu viss um að þú viljir eyða þessum samningi línu?',
		'MoveToAnotherContract' => 'Færa þjónustuna í annað samning.',
		'ConfirmMoveToAnotherContract' => 'Ég choosed ný markmið samningsins og staðfesta mig langar til að færa þessa þjónustu inn í þennan samning.',
		'ConfirmMoveToAnotherContractQuestion' => 'Veldu hér fyrirliggjandi samning (af sama þriðja aðila), þú vilt færa þessa þjónustu til?',
		'PaymentRenewContractId' => 'Endurnýja samning línu (númer %s )',
		'ExpiredSince' => 'Gildistími',
		'RelatedContracts' => 'Svipaðir samningar',
		'NoExpiredServices' => 'Engar útrunnin virk þjónusta',
		////////// Types de contacts //////////
		'TypeContact_contrat_internal_SALESREPSIGN' => 'Sölufulltrúi undirrita samning',
		'TypeContact_contrat_internal_SALESREPFOLL' => 'Sölufulltrúi eftirfarandi upp samningi',
		'TypeContact_contrat_external_BILLING' => 'Innheimta viðskiptavina samband',
		'TypeContact_contrat_external_CUSTOMER' => 'Eftirfylgni viðskiptavina samband',
		'TypeContact_contrat_external_SALESREPSIGN' => 'Undirritun samnings viðskiptavina samband',
		'Error_CONTRACT_ADDON_NotDefined' => 'Constant CONTRACT_ADDON skilgreind ekki'
);
?>