<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$other = array(
		'CHARSET' => 'UTF-8',
		'SecurityCode' => 'Öryggisnúmer',
		'Calendar' => 'Calendar',
		'AddTrip' => 'Bæta ferð',
		'Tools' => 'Verkfæri',
		'ToolsDesc' => 'Þetta svæði er tileinkað hópi ýmissa verkfærum er ekki í boði í öðrum færslum valmyndinni. <br><br> Þeir verkfæri geta verið náð úr valmyndinni til hliðar.',
		'Birthday' => 'Afmæli',
		'BirthdayDate' => 'Afmæli',
		'DateToBirth' => 'Dags til fæðingu',
		'BirthdayAlertOn' => 'afmæli viðvörun virk',
		'BirthdayAlertOff' => 'afmæli viðvörun óvirk',
		'Notify_FICHINTER_VALIDATE' => 'Intervention staðfestar',
		'Notify_BILL_VALIDATE' => 'Viðskiptavinur Reikningar staðfestar',
		'Notify_ORDER_SUPPLIER_APPROVE' => 'Birgir röð samþykkt',
		'Notify_ORDER_SUPPLIER_REFUSE' => 'Birgir þess neitaði',
		'Notify_ORDER_VALIDATE' => 'Viðskiptavinur til setja í gildi',
		'Notify_PROPAL_VALIDATE' => 'Viðskiptavinur tillögu staðfestar',
		'Notify_WITHDRAW_TRANSMIT' => 'Gírskipting afturköllun',
		'Notify_WITHDRAW_CREDIT' => 'Credit afturköllun',
		'Notify_WITHDRAW_EMIT' => 'Isue afturköllun',
		'Notify_ORDER_SENTBYMAIL' => 'Viðskiptavinur röð send með pósti',
		'Notify_COMPANY_CREATE' => 'Þriðja aðila til',
		'Notify_PROPAL_SENTBYMAIL' => 'Auglýsing tillögu send með pósti',
		'Notify_ORDER_SENTBYMAIL' => 'Viðskiptavinur röð send með pósti',
		'Notify_BILL_PAYED' => 'Viðskiptavinur Reikningar borgað',
		'Notify_BILL_CANCEL' => 'Viðskiptavinur reikning niður',
		'Notify_BILL_SENTBYMAIL' => 'Viðskiptavinur Reikningar send með pósti',
		'Notify_ORDER_SUPPLIER_VALIDATE' => 'Birgir röð fullgilt',
		'Notify_ORDER_SUPPLIER_SENTBYMAIL' => 'Birgir röð send með pósti',
		'Notify_BILL_SUPPLIER_VALIDATE' => 'Birgir reikning fullgilt',
		'Notify_BILL_SUPPLIER_PAYED' => 'Birgir reikning borgað',
		'Notify_BILL_SUPPLIER_SENTBYMAIL' => 'Birgir reikningi send með pósti',
		'Notify_CONTRACT_VALIDATE' => 'Samningur fullgilt',
		'Notify_FICHEINTER_VALIDATE' => 'Afskipti fullgilt',
		'Notify_SHIPPING_VALIDATE' => 'Shipping fullgilt',
		'Notify_SHIPPING_SENTBYMAIL' => 'Shipping send með pósti',
		'Notify_MEMBER_VALIDATE' => 'Member fullgilt',
		'Notify_MEMBER_SUBSCRIPTION' => 'Member áskrift',
		'Notify_MEMBER_RESILIATE' => 'Member resiliated',
		'Notify_MEMBER_DELETE' => 'Member eytt',
		'NbOfAttachedFiles' => 'Fjöldi meðfylgjandi skrá / gögn',
		'TotalSizeOfAttachedFiles' => 'Heildarstærð meðfylgjandi skrá / gögn',
		'MaxSize' => 'Hámarks stærð',
		'AttachANewFile' => 'Hengja nýja skrá / skjal',
		'LinkedObject' => 'Tengd mótmæla',
		'Miscellanous' => 'Ýmislegt',
		'NbOfActiveNotifications' => 'Fjöldi tilkynninga',
		'PredefinedMailTest' => 'Þetta er prófun póst. \ NThe tvær línur eru aðskilin með vagn til baka.',
		'PredefinedMailTestHtml' => 'Þetta er <b>prófun</b> póstur (orðið próf verður feitletruð). <br> Þessar tvær línur eru aðskilin með vagn til baka.',
		'PredefinedMailContentSendInvoice' => 'Þú vilja finna hér á reikningsnúmerið __ FACREF__ \n\n__PERSONALIZED__ kveðju \n\n__SIGNATURE__',
		'PredefinedMailContentSendInvoiceReminder' => 'Við viljum vara þig á að reikningur __ FACREF__ virðist ekki vera greiddur. Svo er þetta reikningur í viðhengi aftur, sem áminningu. \n\n__PERSONALIZED__ kveðju \n\n__SIGNATURE__',
		'PredefinedMailContentSendProposal' => 'Þú vilja finna hér auglýsing propoal __ PROPREF__ \n\n__PERSONALIZED__ kveðju \n\n__SIGNATURE__',
		'PredefinedMailContentSendOrder' => 'Þú vilja finna hér til __ ORDERREF__ \n\n__PERSONALIZED__ kveðju \n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierOrder' => 'Þú vilja finna hér til __ORDERREF__ okkar \n\n__PERSONALIZED__Sincerely \n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierInvoice' => 'Þú vilja finna hér á reikningsnúmerið __ FACREF__ \n\n__PERSONALIZED__ kveðju \n\n__SIGNATURE__',
		'PredefinedMailContentSendShipping' => 'Þú vilja finna hér siglinga __ SHIPPINGREF__ \n\n__PERSONALIZED__ kveðju \n\n__SIGNATURE__',
		'PredefinedMailContentSendFichInter' => 'Þú vilja finna hér á afskiptum __FICHINTERREF__ \n\n__PERSONALIZED__Sincerely \n\n__SIGNATURE__',
		'DemoDesc' => 'Speedealing er samningur ERP / CRM samanstendur af nokkrum hagnýtur mát. A kynningu sem inniheldur allar einingar þýðir ekki neitt eins og það gerist aldrei. Svo eru nokkrir snið kynningu í boði.',
		'ChooseYourDemoProfil' => 'Veldu kynningu profil sem passa við starfsemi þína ...',
		'DemoFundation' => 'Manage meðlimum úr grunni',
		'DemoFundation2' => 'Manage Aðilar og bankareikning sem grunn',
		'DemoCompanyServiceOnly' => 'Manage sjálfstæður starfsemi selja þjónustu aðeins',
		'DemoCompanyShopWithCashDesk' => 'Manage búð með reiðufé skrifborðið',
		'DemoCompanyProductAndStocks' => 'Stjórna litlum eða miðlungs fyrirtæki selja vörur',
		'DemoCompanyAll' => 'Stjórna litlum eða miðlungs fyrirtæki með marga starfsemi (helstu einingar)',
		'GoToDemo' => 'Fara til kynningu',
		'CreatedBy' => 'Búið til af %s',
		'ModifiedBy' => 'Breytt af %s',
		'ValidatedBy' => 'Staðfestar af %s',
		'CanceledBy' => 'Hætt við %s',
		'ClosedBy' => 'Lokað eftir %s',
		'FileWasRemoved' => 'File %s  var eytt',
		'DirWasRemoved' => 'Listinn %s  hefur verið fjarlægt',
		'FeatureNotYetAvailableShort' => 'Laus í næsta útgáfa',
		'FeatureNotYetAvailable' => 'Lögun ekki enn til staðar í þessari útgáfu',
		'FeatureExperimental' => 'Experimental lögun. Ekki stöðugt í þessari útgáfu',
		'FeatureDevelopment' => 'Þróun lögun. Ekki stöðugt í þessari útgáfu',
		'FeaturesSupported' => 'Lögun stuðningsmaður',
		'Width' => 'Breidd',
		'Height' => 'Hæð',
		'Depth' => 'Dýpt',
		'Top' => 'Top',
		'Bottom' => 'Bottom',
		'Left' => 'Vinstri',
		'Right' => 'Hægri',
		'CalculatedWeight' => 'Reiknað þyngd',
		'CalculatedVolume' => 'Reiknað magn',
		'Weight' => 'Þyngd',
		'TotalWeight' => 'Samtals þyngd',
		'WeightUnitton' => 'tonn',
		'WeightUnitkg' => 'kg',
		'WeightUnitg' => 'g',
		'WeightUnitmg' => 'mg',
		'WeightUnitpound' => 'pund',
		'Length' => 'Lengd',
		'LengthUnitm' => 'm',
		'LengthUnitdm' => 'dm',
		'LengthUnitcm' => 'cm',
		'LengthUnitmm' => 'mm',
		'Surface' => 'Svæði',
		'SurfaceUnitm2' => 'm2',
		'SurfaceUnitdm2' => 'dm2',
		'SurfaceUnitcm2' => 'cm2',
		'SurfaceUnitmm2' => 'mm2',
		'SurfaceUnitfoot2' => 'ft2',
		'SurfaceUnitinch2' => 'in2',
		'Volume' => 'Bindi',
		'TotalVolume' => 'Samtals magn',
		'VolumeUnitm3' => 'm3',
		'VolumeUnitdm3' => 'dm3',
		'VolumeUnitcm3' => 'cm3',
		'VolumeUnitmm3' => 'mm3',
		'VolumeUnitfoot3' => 'ft3',
		'VolumeUnitinch3' => 'in3',
		'VolumeUnitounce' => 'eyri',
		'VolumeUnitlitre' => 'l',
		'VolumeUnitgallon' => 'gálgi',
		'Size' => 'Stærð',
		'SizeUnitm' => 'm',
		'SizeUnitdm' => 'dm',
		'SizeUnitcm' => 'cm',
		'SizeUnitmm' => 'mm',
		'SizeUnitinch' => 'tomma',
		'SizeUnitfoot' => 'fótur',
		'SizeUnitpoint' => 'point',
		'BugTracker' => 'Bug rekja spor einhvers',
		'SendNewPasswordDesc' => 'Þetta eyðublað er hægt að biðja um nýtt lykilorð. Það verður sent á netfangið þitt. <br> Breyting verður því aðeins eftir að smella á tengilinn staðfesting inni í þessu bréfi. <br> Kíktu á póstinn lesandi hugbúnaður.',
		'BackToLoginPage' => 'Til baka innskráningarsíðu',
		'AuthenticationDoesNotAllowSendNewPassword' => 'Auðkenning háttur <b>er %s .</b> <br> Í þessum ham, Speedealing geta ekki veit né breyta lykilorðinu þínu. <br> Hafðu samband við kerfisstjóra ef þú vilt breyta lykilorðinu þínu.',
		'EnableGDLibraryDesc' => 'Setja upp eða gera GD bókasafn með PHP fyrir að velja þennan valkost.',
		'EnablePhpAVModuleDesc' => 'Þú þarft að setja upp einingu samrýmist andstæðingur þinn-veira. (Samloka: PHP4-clamavlib OU PHP5-clamavlib)',
		'ProfIdShortDesc' => '<b>Prof Id %s </b> er upplýsingamiðstöð ráðast á þriðja aðila land. <br> Til dæmis, þegar <b>landið %s , kóði%</b> það <b>er.</b>',
		'SpeedealingDemo' => 'Speedealing ERP/CRM demo',
		'StatsByNumberOfUnits' => 'Tölfræði í fjölda af vörum / þjónustu eininga',
		'StatsByNumberOfEntities' => 'Tölfræði í fjölda vísa aðila',
		'NumberOfProposals' => 'Fjöldi tillögur um síðustu 12 mánuði',
		'NumberOfCustomerOrders' => 'Fjöldi fyrirmæla viðskiptavina á síðustu 12 mánuði',
		'NumberOfCustomerInvoices' => 'Fjöldi reikninga viðskiptavina á síðustu 12 mánuði',
		'NumberOfSupplierInvoices' => 'Fjöldi reikninga birgir á síðustu 12 mánuði',
		'NumberOfUnitsProposals' => 'Fjöldi eininga á tillögur um síðustu 12 mánuði',
		'NumberOfUnitsCustomerOrders' => 'Fjöldi eininga á pöntunum viðskiptavina á síðustu 12 mánuði',
		'NumberOfUnitsCustomerInvoices' => 'Fjöldi eininga á reikningum viðskiptavina á síðustu 12 mánuði',
		'NumberOfUnitsSupplierInvoices' => 'Fjöldi eininga í reikningum birgir á síðustu 12 mánuði',
		'EMailTextInterventionValidated' => 'Á% afskipti s hefur verið staðfest.',
		'EMailTextInvoiceValidated' => 'Í% reikningi s hefur verið staðfest.',
		'EMailTextProposalValidated' => 'Á% Tillagan s hefur verið staðfest.',
		'EMailTextOrderValidated' => 'Á %s kyni s hefur verið staðfest.',
		'EMailTextOrderApproved' => 'Á %s kyni s hefur verið samþykkt.',
		'EMailTextOrderApprovedBy' => 'Á %s kyni s hefur verið samþykkt af %s .',
		'EMailTextOrderRefused' => 'Á %s kyni s hefur verið hafnað.',
		'EMailTextOrderRefusedBy' => 'Á %s kyni s hefur verið hafnað af %s .',
		'ImportedWithSet' => 'Innflutningur gögnum',
		'SpeedealingNotification' => 'Automatic notification',
		'ResizeDesc' => 'Sláðu inn nýja breidd <b>EÐA</b> nýja hæð. Hlutfall verður haldið á resizing ...',
		'NewLength' => 'New breidd',
		'NewHeight' => 'Ný hæð',
		'NewSizeAfterCropping' => 'Ný stærð eftir cropping',
		'DefineNewAreaToPick' => 'Skilgreina ný svæði á mynd til að velja (vinstri smella á myndina þá draga þar til þú nærð fjær hornið)',
		'CurrentInformationOnImage' => 'Upplýsingar um núverandi mynd',
		'ImageEditor' => 'Image ritstjóri',
		'YouReceiveMailBecauseOfNotification' => 'Þú færð þessi skilaboð vegna þess að netfangið þitt hefur verið bætt við lista yfir markmið að fá upplýsingar um sérstaka atburði í %s  hugbúnað af %s .',
		'YouReceiveMailBecauseOfNotification2' => 'Þessi atburður er eftirfarandi:',
		'ThisIsListOfModules' => 'Þetta er listi yfir einingar forvalinn þessi kynningu uppsetningu (aðeins algengustu einingar eru sýnilegar í þessari kynningu). Breyta þessari að hafa meira einstaklingsmiðuð kynningu og smelltu á &quot;Start&quot;.',
		'ClickHere' => 'Smelltu hér',
		'UseAdvancedPerms' => 'Notaðu háþróaður heimildir sum mát',
		'FileFormat' => 'Skráarsnið',
		'SelectAColor' => 'Veldu lit',
		'AddFiles' => 'Bæta við skrár',
		'StartUpload' => 'Byrja senda',
		'CancelUpload' => 'Hætta við',
		'FileIsTooBig' => 'Skrár er of stór',
		'PleaseBePatient' => 'Please be patient...',
		////////// Calendar common //////////
		'AddCalendarEntry' => 'Bæta við færslu í dagbók %s',
		'NewCompanyToSpeedealing' => 'Company %s added into Speedealing',
		'ContractValidatedInSpeedealing' => 'Contract %s validated in Speedealing',
		'ContractCanceledInSpeedealing' => 'Contract %s canceled in Speedealing',
		'ContractClosedInSpeedealing' => 'Contract %s closed in Speedealing',
		'PropalClosedSignedInSpeedealing' => 'Proposal %s signed in Speedealing',
		'PropalClosedRefusedInSpeedealing' => 'Proposal %s refused in Speedealing',
		'PropalValidatedInSpeedealing' => 'Proposal %s validated in Speedealing',
		'InvoiceValidatedInSpeedealing' => 'Invoice %s validated in Speedealing',
		'InvoicePaidInSpeedealing' => 'Invoice %s changed to paid in Speedealing',
		'InvoiceCanceledInSpeedealing' => 'Invoice %s canceled in Speedealing',
		'PaymentDoneInSpeedealing' => 'Payment %s done in Speedealing',
		'CustomerPaymentDoneInSpeedealing' => 'Customer payment %s done in Speedealing',
		'SupplierPaymentDoneInSpeedealing' => 'Supplier payment %s done in Speedealing',
		'MemberValidatedInSpeedealing' => 'Member %s validated in Speedealing',
		'MemberResiliatedInSpeedealing' => 'Member %s resiliated in Speedealing',
		'MemberDeletedInSpeedealing' => 'Member %s deleted from Speedealing',
		'MemberSubscriptionAddedInSpeedealing' => 'Subscription for member %s added in Speedealing',
		'ShipmentValidatedInSpeedealing' => 'Shipment %s validated in Speedealing',
		////////// Export //////////
		'Export' => 'Útflutningur',
		'ExportsArea' => 'Útflutningur area',
		'AvailableFormats' => 'Laus snið',
		'LibraryUsed' => 'Librairy notaður',
		'LibraryVersion' => 'Útgáfa',
		'ExportableDatas' => 'Exportable gögn',
		'NoExportableData' => 'Nei exportable gögn (ekki einingum með exportable gögn hlaðinn eða vantar heimildir)',
		'ToExport' => 'Útflutningur',
		'NewExport' => 'New útflutningur',
		////////// External sites //////////
		'ExternalSites' => 'Ytri síður'
);
?>