<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Lager-kort',
		'Warehouse' => 'Lager',
		'Warehouses' => 'Warehouses',
		'NewWarehouse' => 'Nýr lager / lager area',
		'WarehouseEdit' => 'Breyta vörugeymsla',
		'MenuNewWarehouse' => 'Nýr lager',
		'WarehouseOpened' => 'Warehouse opna',
		'WarehouseClosed' => 'Lager lokaður',
		'WarehouseSource' => 'Heimild vörugeymsla',
		'WarehouseSourceNotDefined' => 'No warehouse defined,',
		'AddOne' => 'Add one',
		'WarehouseTarget' => 'Markmál vörugeymsla',
		'ValidateSending' => 'Eyða sendingu',
		'CancelSending' => 'Hætta við að senda',
		'DeleteSending' => 'Eyða sendingu',
		'Stock' => 'Stock',
		'Stocks' => 'Verðbréf',
		'Movement' => 'Hreyfing',
		'Movements' => 'Hreyfing',
		'ErrorWarehouseRefRequired' => 'Lager tilvísun nafn er krafist',
		'ErrorWarehouseLabelRequired' => 'Lager merki er krafist',
		'CorrectStock' => 'Rétt lager',
		'ListOfWarehouses' => 'Listi yfir vöruhús',
		'ListOfStockMovements' => 'Listi yfir hreyfingar lager',
		'StocksArea' => 'Stocks area',
		'Location' => 'Staðsetning',
		'LocationSummary' => 'Stutt nafn staðsetning',
		'NumberOfProducts' => 'Heildarfjöldi vörur',
		'LastMovement' => 'Síðasta hreyfing',
		'LastMovements' => 'Síðasta hreyfing',
		'Units' => 'Einingar',
		'Unit' => 'Unit',
		'StockCorrection' => 'Rétt lager',
		'StockMovement' => 'Transfer',
		'StockMovements' => 'Kauphöll millifærslur',
		'NumberOfUnit' => 'Fjöldi eininga',
		'UnitPurchaseValue' => 'Unit purchase price',
		'TotalStock' => 'Samtals á lager',
		'StockTooLow' => 'Stock of lágt',
		'StockLowerThanLimit' => 'Stock lower than alert limit',
		'EnhancedValue' => 'Gildi',
		'PMPValue' => 'Vegið meðalverð',
		'PMPValueShort' => 'WAP',
		'EnhancedValueOfWarehouses' => 'Vöruhús gildi',
		'UserWarehouseAutoCreate' => 'Búa til birgðir sjálfkrafa þegar þú býrð til notanda',
		'QtyDispatched' => 'Magn send',
		'OrderDispatch' => 'Kauphöll dispatching',
		'RuleForStockManagementDecrease' => 'Regla fyrir lager stjórnun lækka',
		'RuleForStockManagementIncrease' => 'Regla fyrir lager stjórnun aukast',
		'DeStockOnBill' => 'Minnka raunverulegur birgðir á viðskiptavini reikningum / kredit athugasemdir löggilding',
		'DeStockOnValidateOrder' => 'Minnka raunverulegur birgðir á viðskiptavini pantanir löggilding',
		'DeStockOnShipment' => 'Minnka alvöru stofnum á sendingunni löggilding',
		'ReStockOnBill' => 'Auka raunverulegur birgðir birgja reikningum / kredit athugasemdir löggilding',
		'ReStockOnValidateOrder' => 'Auka raunverulegur birgðir birgja pantanir approbation',
		'ReStockOnDispatchOrder' => 'Auka raunverulegur birgðir á handbók dispatching í vöruhús, eftir röð birgja sem fá',
		'OrderStatusNotReadyToDispatch' => 'Panta hefur ekki enn eða ekki meira stöðu sem gerir dispatching af vörum í vöruhús lager.',
		'StockDiffPhysicTeoric' => 'Ástæða fyrir lager munur líkamlega og fræðilegum',
		'NoPredefinedProductToDispatch' => 'Engar fyrirfram skilgreindum vörum fyrir þennan hlut. Svo neitun dispatching til á lager er krafist.',
		'DispatchVerb' => 'Senda',
		'StockLimitShort' => 'Takmörk',
		'StockLimit' => 'Kauphöll takmörk fyrir viðvaranir',
		'PhysicalStock' => 'Líkamleg lager',
		'RealStock' => 'Real lager',
		'TheoreticalStock' => 'Therocial lager',
		'VirtualStock' => 'Virtual Stock',
		'MininumStock' => 'Lágmark lager',
		'StockUp' => 'Stock upp',
		'MininumStockShort' => 'Kauphöll mín',
		'StockUpShort' => 'Stock upp',
		'IdWarehouse' => 'Auðkenni vörugeymsla',
		'DescWareHouse' => 'Lýsing vörugeymsla',
		'LieuWareHouse' => 'Staðsetning lager',
		'WarehousesAndProducts' => 'Vöruhús og vörur',
		'AverageUnitPricePMPShort' => 'Meðaltal inntak verð',
		'AverageUnitPricePMP' => 'Meðaltal inntak verð',
		'SellPriceMin' => 'Selja Unit verð',
		'EstimatedStockValueSellShort' => 'Gildi til að selja',
		'EstimatedStockValueSell' => 'Gildi til að selja',
		'EstimatedStockValueShort' => 'Áætlað virði hlutabréfa',
		'EstimatedStockValue' => 'Áætlað virði hlutabréfa',
		'DeleteAWarehouse' => 'Eyða vörugeymsla',
		'ConfirmDeleteWarehouse' => 'Ertu viss um að þú viljir eyða <b>lager %s ?</b>',
		'PersonalStock' => 'Starfsfólk lager %s',
		'ThisWarehouseIsPersonalStock' => 'Þetta vöruhús táknar persónulegt birgðir af %s  %s',
		'SelectWarehouseForStockDecrease' => 'Veldu vöruhús að nota til lækkunar hlutabréfa',
		'SelectWarehouseForStockIncrease' => 'Veldu vöruhús að nota fyrir hækkun hlutabréfa',
		'LastWaitingSupplierOrders' => 'Orders waiting for receptions'
);
?>