<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$withdrawals = array(
		'CHARSET' => 'UTF-8',
		'ThirdPartyDeskCode' => 'Í þriðja aðila skrifborðið kóða',
		'NoInvoiceCouldBeWithdrawed' => 'Engin reikningur withdrawed með góðum árangri. Athugaðu að Reikningar eru fyrirtæki með gilt bann.',
		'ClassCredited' => 'Flokka fært',
		'ClassCreditedConfirm' => 'Ertu viss um að þú viljir að flokka þessa afturköllun berst sem lögð á bankareikning þinn?',
		'TransData' => 'Date Sending',
		'TransMetod' => 'Aðferð Sending',
		'Send' => 'Senda',
		'Lines' => 'Línur',
		'StandingOrderReject' => 'Útgáfudagur a hafna',
		'WithdrawalRefused' => 'Útborganir Refuseds',
		'WithdrawalRefusedConfirm' => 'Ertu viss um að þú viljir að slá inn uppsögn höfnun fyrir samfélagið',
		'RefusedData' => 'Dagsetning synjunar',
		'RefusedReason' => 'Ástæða fyrir höfnun',
		'RefusedInvoicing' => 'Innheimta höfnun',
		'NoInvoiceRefused' => 'Ekki hlaða höfnun',
		'InvoiceRefused' => 'Hleðsla höfnun til viðskiptavina',
		'Status' => 'Status',
		'StatusUnknown' => 'Óþekkt',
		'StatusWaiting' => 'Bíð',
		'StatusCredited' => 'Trúnaður',
		'StatusRefused' => 'Neitaði',
		'StatusMotif0' => 'Ótilgreint',
		'StatusMotif1' => 'Kveða insuffisante',
		'StatusMotif2' => 'Tirage conteste',
		'StatusMotif3' => 'Nei Uppsögn röð',
		'StatusMotif4' => 'Customer Order',
		'StatusMotif5' => 'RIB inexploitable',
		'StatusMotif6' => 'Reikningur án jafnvægi',
		'StatusMotif7' => 'Dómstóla ákvörðun',
		'StatusMotif8' => 'Aðrar ástæður',
		'CreateAll' => 'Dragið alla',
		'CreateGuichet' => 'Aðeins skrifstofa',
		'CreateBanque' => 'Eini bankinn',
		'OrderWaiting' => 'Beðið eftir meðferð',
		'NotifyTransmision' => 'Uppsögn Sending',
		'NotifyEmision' => 'Uppsögn Útsending',
		'NotifyCredit' => 'Uppsögn Credit',
		'NumeroNationalEmetter' => 'National Sendandi Fjöldi',
		'StandingOrdersArea' => 'Standandi fyrirmæli area',
		'CustomersStandingOrdersArea' => 'Viðskiptavinir standandi fyrirmæli area',
		'StandingOrders' => 'Standandi pantanir',
		'StandingOrder' => 'Standandi pantanir',
		'NewStandingOrder' => 'Ný staða þess',
		'StandingOrderToProcess' => 'Til að ganga frá',
		'StandingOrderProcessed' => 'Afgreitt',
		'Withdrawals' => 'Útborganir',
		'Withdrawal' => 'Uppsögn',
		'WithdrawalsReceipts' => 'Uppsögn kvittunum',
		'WithdrawalReceipt' => 'Uppsögn barst',
		'WithdrawalReceiptShort' => 'Kvittun',
		'LastWithdrawalReceipts' => 'Last %s  afturköllun kvittunum',
		'WithdrawedBills' => 'Afturkallað reikningum',
		'WithdrawalsLines' => 'Uppsögn línur',
		'RequestStandingOrderToTreat' => 'Beiðni fyrir standandi fyrirmæli til meðferðar',
		'RequestStandingOrderTreated' => 'Beiðni um stöðu pantana sem fengu',
		'CustomersStandingOrders' => 'Viðskiptavinur standa pantanir',
		'CustomerStandingOrder' => 'Viðskiptavinur standandi röð',
		'NbOfInvoiceToWithdraw' => 'ATH reiknings með afturkalla beiðni',
		'InvoiceWaitingWithdraw' => 'Invoice að bíða eftir að afturkalla',
		'AmountToWithdraw' => 'Upphæð til baka',
		'WithdrawsRefused' => 'Segir upp neitaði',
		'NoInvoiceToWithdraw' => 'Enginn viðskiptavinur reikning í ham greiðslu "afturkalla" er í bið. Fara á flipanum \'Dragið\' reikning kort til að leggja fram beiðni.',
		'ResponsibleUser' => 'Ábyrg notanda',
		'WithdrawalsSetup' => 'Uppsögn skipulag',
		'WithdrawStatistics' => 'tölfræði Dragið\'s',
		'WithdrawRejectStatistics' => 'Dragið hafna\'s tölfræði',
		'LastWithdrawalReceipt' => 'Last %s  afturkalla kvittunum',
		'MakeWithdrawRequest' => 'Gerðu afturkalla beiðni',
		'ThirdPartyBankCode' => 'Í þriðja aðila bankakóði',
		'NbOfInvoiceToWithdrawWithInfo' => 'Nb af reikningi með afturkalla beiðni um viðskiptavini sem hafa skilgreint upplýsingar um bankareikning',
		'StatusTrans' => 'Senda',
		'PleaseSelectCustomerBankBANToWithdraw' => 'Veldu upplýsingar um viðskiptavini bankareikning til að taka',
		'WithBankUsingRIB' => 'Fyrir bankareikninga með RIB',
		'WithBankUsingBANBIC' => 'Fyrir bankareikninga með IBAN / BIC / Swift',
		'BankToReceiveWithdraw' => 'Bankareikning til að fá hættir',
		'CreditDate' => 'Útlán á',
		'WithdrawalFileNotCapable' => 'Ekki er hægt að búa til fráhvarfs kvittunar skrá fyrir þínu landi',
		'ShowWithdraw' => 'Sýna Dragið',
		'IfInvoiceNeedOnWithdrawPaymentWontBeClosed' => 'Hins vegar, ef reikningur hefur að minnsta kosti einn hætt greiðslu ekki enn afgreidd, mun það ekki vera eins og borgað til að leyfa að stjórna afturköllun áður.',
		'DoStandingOrdersBeforePayments' => 'Þetta tabs leyfa þér að biðja fyrir standandi röð. Þegar það verður lokið, getur þú slegið greiðslu til loka reikning.',
		'InfoCreditSubject' => 'Greiðsla standa röð %s af bankanum',
		'InfoCreditMessage' => 'Það stendur til %s hefur verið greitt af bankanum <br> Gögn um greiðslu: %s',
		'InfoTransSubject' => 'Sending standa röð %s í bankann',
		'InfoTransMessage' => 'Það stendur til %s hefur verið transmited í bankann með %s %s. <br><br>',
		'InfoTransData' => 'Upphæð: %s <br> Metode: %s <br> Date: %s',
		'InfoFoot' => 'Þetta er sjálfvirkt skilaboð send með Dolibarr',
		'InfoRejectSubject' => 'Standandi þess neitaði',
		'InfoRejectMessage' => 'Halló, <br><br> að standig þess reiknings %s tengjast félaginu %s, með fjárhæð %s hefur verið hafnað af bankanum. <br><br> - <br> % $',
		'ModeWarning' => 'Valkostur fyrir alvöru ham var ekki sett, að hætta við eftir þessa uppgerð',
);
?>