<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$install = array(
		'CHARSET' => 'UTF-8',
		'InstallEasy' => 'Wir haben uns bemüht, die Installation von speedealing so einfach wie möglich zu gestalten. Folgen Sie einfach Schritt für Schritt den Anweisungen auf dem Bildschirm.',
		'MiscellanousChecks' => 'Systemvoraussetzungen prüfen',
		'SpeedealingWelcome' => 'Welcome to Speedealing',
		'ConfFileExists' => 'Die Konfigurationsdatei <b>%s</b> ist vorhanden.',
		'ConfFileDoesNotExists' => 'Die Konfigurationsdatei <b>%s</b> existiert nicht!',
		'ConfFileDoesNotExistsAndCouldNotBeCreated' => 'Die Konfigurationsdatei <b>%s</b> ist nicht vorhanden und konnte auch nicht erstellt werden!',
		'ConfFileCouldBeCreated' => 'Die Konfigurationsdatei <b>%s</b> wurde erfolgreich erstellt.',
		'ConfFileIsNotWritable' => 'Die Konfigurationsdatei <b>%s</b> ist nicht beschreibbar. Bitte überprüfen Sie die Dateizugriffsrechte. Für die Erstinstallation muss Ihr Webserver in die Konfigurationsdatei schreiben können, sezzten Sie die Dateiberechtigungen entsprechend (z.B. mittels "chmod 666" auf Unix-Betriebssystemen).',
		'ConfFileIsWritable' => 'Die Konfigurationsdatei <b>%s</b> ist beschreibbar.',
		'ConfFileReload' => 'Alle Information aus der Konfigurationsdatei laden.',
		'PHPSupportSessions' => 'Ihre PHP-Konfiguration unterstützt Sitzungen (Sessions).',
		'PHPSupportPOSTGETOk' => 'Ihre PHP-Konfiguration unterstützt GET- und POST-Variablen',
		'PHPSupportPOSTGETKo' => 'Ihre PHP-Konfiguration scheint GET- und/oder POST-Variablen nicht zu unterstützen. Überprüfen Sie in der php.ini den Parameter <b>variables_order</b>.',
		'PHPSupportGD' => 'Ihre PHP-Konfiguration unterstützt grafische Funktionen mittels GD.',
		'PHPSupportUTF8' => 'Ihre PHP-Konfiguration unterstützt UTF8-Funktionen.',
		'PHPMemoryOK' => 'Die Sitzungsspeicherbegrenzung ihrer PHP-Konfiguration steht auf <b>%s</b>. Dies sollte ausreichend sein.',
		'PHPMemoryTooLow' => 'Die Sitzungsspeicherbegrenzung ihrer PHP-Konfiguration steht auf <b>%s</b> Bytes. Dies ist nicht ausreichend. Ändern Sie in Ihrer <b>php.ini</b> den Parameter <b>memory_limit</b> auf mindestens <b>%s</b> Bytes.',
		'Recheck' => 'Voraussetzungen erneut prüfen',
		'ErrorPHPDoesNotSupportSessions' => 'Ihre PHP-Installation unterstützt keine Sitzungen. Diese Funktion ist für das Arbeiten mit speedealing erforderlich. Bitte überprüfen Sie Ihre PHP-Konfiguration.',
		'ErrorPHPDoesNotSupportGD' => 'Ihre PHP-Installation unterstützt keine grafischen Funktion mittels GD. Ihnen stehen dadurch keine Diagramme zur Verfügung.',
		'ErrorPHPDoesNotSupportUTF8' => 'Ihre PHP-Installation unterstützt keine UTF8-Funktionen. Dies könnte die korrekte Funktionsweise von speedealing behindern und Sie sollten dieses Problem vor der Installation beheben.',
		'ErrorDirDoesNotExists' => 'Das Verzeichnis %s existiert nicht.',
		'ErrorGoBackAndCorrectParameters' => 'Gehen Sie zurück und korrigieren Sie die ungültigen Parameter.',
		'ErrorWrongValueForParameter' => 'Sie haben einen falschen Wert für den Parameter \'%s\' eingegeben.',
		'ErrorFailedToCreateDatabase' => 'Fehler beim Erstellen der Datenbank \'%s\'.',
		'ErrorFailedToConnectToDatabase' => 'Es konnte keine Verbindung zur Datenbank \' %s\'.',
		'ErrorDatabaseVersionTooLow' => 'Database version (%s) too old. Version %s or higher is required.',
		'ErrorPHPVersionTooLow' => 'Ihre PHP-Version ist veraltet. Sie benötigen mindestens Version %s .',
		'WarningPHPVersionTooLow' => 'Die PHP-Version ist zu alt. Es wird Version %s oder höher erwartet. Sie können unter dieser PHP-Version installieren, aber sie wird nicht unterstützt.',
		'ErrorConnectedButDatabaseNotFound' => 'Die Verbindung zum Server wurde erfolgreich hergestellt, die Datenbank \'%s\' jedoch nicht gefunden.',
		'ErrorDatabaseAlreadyExists' => 'Eine Datenbank mit dem Namen \'%s\' exisitiert bereits.',
		'IfDatabaseNotExistsGoBackAndUncheckCreate' => 'Sollte die Datenbank noch nicht existieren, gehen Sie bitte zurück und aktivieren Sie das Kontrollkästchen "Datenbank erstellen".',
		'IfDatabaseExistsGoBackAndCheckCreate' => 'Sollte die Datebank bereits existieren, gehen Sie bitte zurück und deaktivieren Sie das Kontrollkästchen "Datenbank erstellen".',
		'WarningBrowserTooOld' => 'Sie verwenden eine zu alte Version des Browsers. Installieren Sie die aktuelle Version  Ihres Browser (Empfehlung: Firefox, Chrome oder Opera).',
		'PHPVersion' => 'PHP-Version',
		'YouCanContinue' => 'Sie können mit der Installation fortfahren',
		'PleaseBePatient' => 'Bitte haben Sie ein wenig Geduld ...',
		'License' => 'Lizenzverwendung',
		'ConfigurationFile' => 'Konfigurationsdatei',
		'WebPagesDirectory' => 'Verzeichnis für die Speicherung von Websites',
		'DocumentsDirectory' => 'Verzeichnis zur Speicherung von Dokumenten (Dokumentenverzeichnis)',
		'URLRoot' => 'URL root',
		'ForceHttps' => 'Sichere Verbindung (https) erzwingen',
		'CheckToForceHttps' => 'Aktivieren Sie diese Option, um sichere Verbindungen (https) zu erzwingen.<br>Hierfür ist ein auf Ihrem Webserver eingerichtetes SSL-Zertifikat erforderlich.',
		'SpeedealingDatabase' => 'Speedealing Database',
		'DatabaseChoice' => 'Datenbankwahl',
		'DatabaseType' => 'Datenbanktyp',
		'DriverType' => 'Art des Treibers',
		'Server' => 'Server',
		'ServerAddressDescription' => 'Name oder IP-Adresse des Datenbankservers, in der Regel ist dies "localhost" (Datenbank und Webserver liegen auf demselben Server).',
		'ServerPortDescription' => 'Datenbankserver-Port. Lassen Sie dieses Feld im Zweifel leer.',
		'DatabaseServer' => 'Datenbankserver',
		'DatabaseName' => 'Name der Datenbank',
		'DatabasePrefix' => 'Präfix für die Tabellen der Datenbank',
		'Login' => 'Anmeldung',
		'AdminLogin' => 'Login für Speedealing Datenbank-Administrator.',
		'Password' => 'Passwort',
		'PasswordAgain' => 'Passwort wiederholen',
		'AdminPassword' => 'Passwort des speedealing-Datenbankadministrators',
		'CreateDatabase' => 'Datenbank erstellen',
		'CreateUser' => 'Benutzer erstellen',
		'DatabaseSuperUserAccess' => 'Superuser-Zugang zum Datenbankserver',
		'CheckToCreateDatabase' => 'Aktivieren Sie dieses Kontrollkästchen, falls Sie noch keine Datenbank angelegt haben und diese im Zuge der Installation erstellt werden soll.<br>Hierfür müssen Sie Benutzername und Passwort des Datenbank-Superusers am Ende der Seite angeben.',
		'CheckToCreateUser' => 'Aktivieren Sie dieses Kontrollkästchen, falls Sie noch keinen Datenbankbenutzer angelegt haben und dieser im Zuge der Installation erstellt werden soll.<br>Hierfür müssen Sie Benutzername und Passwort des Datenbank-Superusers am Ende der Seite angeben.',
		'Experimental' => '(experimentell)',
		'DatabaseRootLoginDescription' => 'Anmeldedaten des Datenbank-Superusers zur Erstellung neuer Datenbanken und -benutzer. Sollten diese bereits existieren (z.B. weil Ihre Website bei einem Hosting-Provider liegt), ist diese Option nutzlos.',
		'KeepEmptyIfNoPassword' => 'Leer lassen wenn der Benutzer kein Passwort hat (nicht empfohlen)',
		'SaveConfigurationFile' => 'Einstellungen speichern',
		'ConfigurationSaving' => 'Speichern der Konfigurationsdatei',
		'ServerConnection' => 'Serververbindung',
		'DatabaseConnection' => 'Datenbankverbindung',
		'DatabaseCreation' => 'Datenbankerstellung',
		'UserCreation' => 'Benutzererstellung',
		'CreateDatabaseObjects' => 'Anlegen der Datenbankobjekte',
		'ReferenceDataLoading' => 'Referenzdaten werden geladen',
		'TablesAndPrimaryKeysCreation' => 'Erstellen der Tabellen und Primärschlüssel',
		'CreateTableAndPrimaryKey' => 'Erstellen der Tabelle %s',
		'CreateOtherKeysForTable' => 'Erstellen der Fremdschlüssel und Indizes für Tabelle %s',
		'OtherKeysCreation' => 'Erstellen der Fremdschlüssel und Indizes',
		'FunctionsCreation' => 'Erstellen der Funktionen',
		'AdminAccountCreation' => 'Erstellen des Administrationskontos',
		'PleaseTypePassword' => 'Bitte geben Sie ein Passwort ein. Leere Passwörter sind unzulässig.',
		'PleaseTypeALogin' => 'Bitte geben Sie einen Benutzernamen ein.',
		'PasswordsMismatch' => 'Die eingegebenen Passwörter unterscheiden sich. Bitte versuchen Sie es erneut!',
		'SetupEnd' => 'Ende der Erstkonfiguration',
		'SystemIsInstalled' => 'Die Installation wurde erfolgreich abgeschlossen.',
		'SystemIsUpgraded' => 'Der Aktualisierungsvorgang wurde erfolgreich abgeschlossen.',
		'YouNeedToPersonalizeSetup' => 'Nun sollten Sie speedealing an Ihre Bedürfnisse anpassen (Aussehen, Funktionen, ...). Hierzu folgen Sie bitte dem untenstehenden Link:',
		'AdminLoginCreatedSuccessfuly' => 'Das speedealing-Administratorkonto \'<b>%s</b>\' wurde erfolgreich erstellt.',
		'GoToSpeedealing' => 'Go to Speedealing',
		'GoToSetupArea' => 'Zu den speedealing-Einstellungen',
		'MigrationNotFinished' => 'Ihre Datenbankversion ist nicht auf dem neuesten Stand, bitte wiederholen Sie den Aktualisierungsvorgang.',
		'GoToUpgradePage' => 'Noch einmal zur Aktualisierungsseite',
		'Examples' => 'Beispiele',
		'WithNoSlashAtTheEnd' => 'Ohne Schrägstrich "/" am Ende',
		'DirectoryRecommendation' => 'Es empfiehlt sich die Verwendung eines Ordners außerhalb Ihres Webverzeichnisses.',
		'LoginAlreadyExists' => 'Dieser Benutzername ist bereits vergeben',
		'SpeedealingAdminLogin' => 'Speedealing admin login',
		'AdminLoginAlreadyExists' => 'Ein Administratorkonto namens \'<b>%s</b>\' ist bereits vorhanden.',
		'WarningRemoveInstallDir' => 'Aus Sicherheitsgründen sollten Sie nach abgeschlossenem Installations-/Aktualisierungsvorgang das Installationsverzeichnis (<b>install</b>) löschen oder in "install.lock" umbenennen.',
		'ThisPHPDoesNotSupportTypeBase' => 'Ihr PHP-System unterstützt keinen Zugriff auf Datenbanken des Typs %s',
		'FunctionNotAvailableInThisPHP' => 'Diese Funktion steht in Ihrer PHP-Version nicht zur Verfügung.',
		'MigrateScript' => 'Migrationsskript',
		'ChoosedMigrateScript' => 'Migrationsskript auswählen',
		'DataMigration' => 'Datenmigration',
		'DatabaseMigration' => 'Struktur der Datenbankmigration',
		'ProcessMigrateScript' => 'Script-Verarbeitung',
		'ChooseYourSetupMode' => 'Wählen Sie Ihre Installationsart und klicken Sie anschließend auf "Start"...',
		'FreshInstall' => 'Neue Installation',
		'FreshInstallDesc' => 'Verwenden Sie diesen Modus für Erstinstallationen. Sie können damit auch frühere, unvollständige Installationen reparieren. Für eine Aktualisierung Ihres Systems wählen Sie bitte den Installationstyp "Aktualisierung".',
		'Upgrade' => 'Aktualisierung',
		'UpgradeDesc' => 'Verwenden Sie diesen Modus zum Ersetzen Ihrer bisherigen Dateien durch eine neuere Version. Dieser Vorgang beinhaltet eine Aktualisierung Ihrer Datenbank und -daten.',
		'Start' => 'Start',
		'InstallNotAllowed' => 'Die in der Konfigurationsdatei <b>conf.php</b> gesetzten Berechtigungen verhindern eine Ausführung des Installationsvorganges.',
		'NotAvailable' => 'Nicht verfügbar',
		'YouMustCreateWithPermission' => 'Für den Installationsvorgang erstellen Sie bitte die Datei %s und machen Sie diese für Ihren Webserver beschreibbar.',
		'CorrectProblemAndReloadPage' => 'Bitte beheben Sie das Problem und klicken Sie anschließend auf F5 um die Seite neu zu laden.',
		'AlreadyDone' => 'Migration bereits durchgeführt',
		'DatabaseVersion' => 'Datenbankversion',
		'ServerVersion' => 'Version des Datenbankservers',
		'YouMustCreateItAndAllowServerToWrite' => 'Bitte erstellen Sie dieses Verzeichnis und machen Sie dieses für Ihren Webserver beschreibbar.',
		'CharsetChoice' => 'Zeichensatzauswahl',
		'CharacterSetClient' => 'Zeichensatz für die generierten HTML-Seiten',
		'CharacterSetClientComment' => 'Wählen Sie den gewünschten Zeichensatz für die Anzeige im Web.<br/>Standardmäßig empfiehlt sich jener Ihrer Datenbank.',
		'CollationConnection' => 'Reihenfolge der Zeichensortierung',
		'CollationConnectionComment' => 'Wählen Sie den page-code zur Definition der Sortierreihenfolge für Zeichen in der Datenbank. Dieser Parameter wird von einigen Datenbanken auch als "Collation" bezeichnet.<br/>Dieser Wert kann nicht festgelegt werden, wenn die Datenbank bereits existiert.',
		'CharacterSetDatabase' => 'Datenbankzeichensatz',
		'CharacterSetDatabaseComment' => 'Wählen Sie den Zeichensatz für die anzulegende Datenbank.<br/>Dieser Wert kann nicht festgelegt werden, wenn die Datenbank bereits existiert.',
		'YouAskDatabaseCreationSoSpeedealingNeedToConnect' => 'You ask to create database <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'YouAskLoginCreationSoSpeedealingNeedToConnect' => 'You ask to create database login <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'BecauseConnectionFailedParametersMayBeWrong' => 'Der Verbindungsaufbau ist fehlgeschlagen. Bitte überprüfen Sie die Einstellungen des Servers und Super-User-Zugangs.',
		'OrphelinsPaymentsDetectedByMethod' => 'Verwaiste Zahlung gefunden durch Methode %s',
		'RemoveItManuallyAndPressF5ToContinue' => 'Bitte manuell entfernen und F5 drücken um fortzufahren.',
		'KeepDefaultValuesWamp' => 'Sie verwenden den DoliWamp-Installationsassistent, entsprechend sind die hier vorgeschlagenen Werte bereits optimiert. Ändern Sie diese nur wenn Sie wissen was Sie tun.',
		'KeepDefaultValuesDeb' => 'Sie verwenden den speedealing-Installationsassistenten auf einem Ubuntu oder Debian-Paket, entsprechend sind die hier vorgeschlagenen Werte bereits optimiert. Sie müssen lediglich das Passwort des anzulegenden Datenbankbenutzers angeben. Ändern Sie die übrigen Parameter nur, wenn Sie wissen was Sie tun.',
		'KeepDefaultValuesMamp' => 'Sie verwenden den DoliMamp-Installationsassistent, entsprechend sind die hier vorgeschlagenen Werte bereits optimiert. Ändern Sie diese nur wenn Sie wissen was Sie tun.',
		'KeepDefaultValuesProxmox' => 'Sie verwenden den Speedealing Installationsassistenten einer Proxmox "virtual appliance". Die hier vorgeschlagenen Werte sind bereits optimiert. Bitte nehmen Sie nur Änderungen vor wenn Sie wissen was Sie tun.',
		'FieldRenamed' => 'Feld umbenannt',
		'IfLoginDoesNotExistsCheckCreateUser' => 'Sollte der Benutzer noch nicht existieren, müssen Sie das Kontrollkästchen "Benutzer erstellen" aktivieren',
		'ErrorConnection' => 'Server <b>%s</b>\', Datenbank \'<b>%s</b>\', Benutzer \'<b>%s</b>\' oder Datenbankpasswort scheinen falsch zu sein. Eventuell verhindert auch eine veraltete PHP- oder Datenbankversion den korrekten Verbindungsaufbau.',
		'InstallChoiceRecommanded' => 'Es empfiehlt sich eine Aktualisierung auf Version <b>%s</b>. Ihre aktuelle Version ist <b>%s</b>.',
		'InstallChoiceSuggested' => '<b>Vom Installationsassistenten vorgeschlagene Wahl.</b>',
		'MigrateIsDoneStepByStep' => 'Die gewählte Version (%s) hat ein Lücke von mehrerer Versionen. Der Installationsassistent wird sich wieder melden, um die nächste Migration vorzuschlagen. Dies geschieht bis zur endgültigen Fertigstellung.',
		'CheckThatDatabasenameIsCorrect' => 'Bitte überprüfen Sie die Schreibweise des Datenbanknamens "<b>%s</b>".',
		'IfAlreadyExistsCheckOption' => 'Sollte dieser Name korrekt und die Datenbank noch nicht vorhanden sein, aktivieren Sie bitte das Kontrollkästchen "Datenbank erstellen".',
		'OpenBaseDir' => 'PHP openbasedir Einstellungen',
		'YouAskToCreateDatabaseSoRootRequired' => 'Sie haben die Option "Datenbank erstellen" ausgewählt. Hierfür müssen Sie Benutzername und Passwort des Datenbank-Super-Users in das untenstehende Formular eintragen.',
		'YouAskToCreateDatabaseUserSoRootRequired' => 'Sie haben die Option "Datenbankbenutzer erstellen" ausgewählt. Hierfür müssen Sie Benutzername und Passwort des Datenbank-Super-Users in das untenstehende Formular eintragen.',
		'NextStepMightLastALongTime' => 'Der aktuelle Vorgang kann mehrere Minuten dauern. Holen Sie sich eine frische Tasse Kaffee, oder nutzen Sie die Gelegenheit für eine Rauchpause. Warten Sie jedoch bitte in jedem Fall, bis der nächste Bildschirm vollständig angezeigt wird, bevor Sir fortfahren.',
		'LastStepDesc' => '<strong>Letzter Schritt</strong>: Legen Sie Ihr Logo und das Passwort fest, welches Sie für speedealing verwenden möchten. Verlieren Sie diese Administrator-Passwort nicht, da es der "Generalschlüssel" ist.',
		'ActivateModule' => 'Aktivieren von Modul %s',
		'ShowEditTechnicalParameters' => 'Click here to show/edit advanced parameters (expert mode)',
		'ServerPortCouchdbDescription' => 'Port du serveur. Défaut 5984.',
		'ServerAddressCouchdbDescription' => 'Nom FQDN du serveur de base de données, \'localhost.localdomain\' quand le serveur est installé sur la même machine que le serveur web',
		'DatabaseCouchdbUserDescription' => 'Login du super administrateur ayant tous les droits sur le serveur CouchDB ou l\'administrateur propriétaire de la base si la base et son compte d\'accès existent déjà (comme lorsque vous êtes chez un hébergeur).<br><br><div class="alert-box info">Cet utilisateur/mot de passe sera l\'administrateur pour se connecter à Speedealing.</div>',
		'CheckToCreateCouchdbDatabase' => 'Cochez cette option si la base de données n\'existe pas et doit être créée.',
		'CreateAdminUser' => 'Créer le super administrateur (Première installation de couchDB)',
		'MemcachedDescription' => 'Activer Memcached necessite l\'installation d\'un serveur Memcached et des lib php-memcached ou php-memcache. Il peut être activer après l\'installation.',
		'ServerAddressMemcachedDesc' => 'Nom ou adresse ip du serveur memcached, généralement \'localhost\' quand le serveur est installé sur la même machine que le serveur web',
		'ServerPortMemcachedDesc' => 'Port du serveur memcached. Défaut : 11211',
		'EnabledMemcached' => 'Activer Memcached',
		'DatabaseNoSQL' => 'Base de données CouchDB',
		'FailedToCreateAdminLogin' => 'Echec de la création du compte administrateur Speedealing.',
		'LinkedElementsInvalidDeleted' => '<b>%s</b> liaisons invalides ont été supprimées',
		'NothingToDelete' => 'Aucune liaison invalide trouvée',
		'SourceType' => 'Source',
		'TargetType' => 'Cible',
                // Upgrade
                'UpgradeOk' => 'Upgrade is ok !',
                'NewInstalledVersion' => 'Your new version is %s',
                'NeedUpgrade' => 'New Speedealing version !',
                'WarningUpgrade' => 'Installed version is %s, you must upgrade to %s. <br>Please contact your administrator.'
);
?>