<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Warenlagerkarte',
		'Warehouse' => 'Warenlager',
		'Warehouses' => 'Warehouses',
		'NewWarehouse' => 'Neues Warenlager',
		'WarehouseEdit' => 'Warenlager bearbeiten',
		'MenuNewWarehouse' => 'Neues Warenlager',
		'WarehouseOpened' => 'Warenlager aktiv',
		'WarehouseClosed' => 'Warenlager geschlossen',
		'WarehouseSource' => 'Ursprungslager',
		'WarehouseSourceNotDefined' => 'No warehouse defined,',
		'AddOne' => 'Add one',
		'WarehouseTarget' => 'Ziellager',
		'ValidateSending' => 'Sendung freigeben',
		'CancelSending' => 'Sendung abbrechen',
		'DeleteSending' => 'Sendung löschen',
		'Stock' => 'Warenbestand',
		'Stocks' => 'Warenbestände',
		'Movement' => 'Lagerbewegung',
		'Movements' => 'Lagerbewegungen',
		'ErrorWarehouseRefRequired' => 'Warenlager-Referenz erforderlich',
		'ErrorWarehouseLabelRequired' => 'Warenlager-Label erforderlich',
		'CorrectStock' => 'Lagerbestand anpassen',
		'ListOfWarehouses' => 'Liste der Warenlager',
		'ListOfStockMovements' => 'Liste der Lagerbewegungen',
		'StocksArea' => 'Warenbestandsübersicht',
		'Location' => 'Standort',
		'LocationSummary' => 'Kurzbezeichnung Standort',
		'NumberOfProducts' => 'Anzahl der Produkte',
		'LastMovement' => 'Letzte Bewegung',
		'LastMovements' => 'Letzte Bewegungen',
		'Units' => 'Einheiten',
		'Unit' => 'Einheit',
		'StockCorrection' => 'Lageranpassung',
		'StockMovement' => 'Lagerbewegung',
		'StockMovements' => 'Lagerbewegungen',
		'NumberOfUnit' => 'Anzahl der Einheiten',
		'UnitPurchaseValue' => 'Unit purchase price',
		'TotalStock' => 'Gesamtbestand',
		'StockTooLow' => 'Mindestbestand unterschritten',
		'StockLowerThanLimit' => 'Stock lower than alert limit',
		'EnhancedValue' => 'Warenwert',
		'PMPValue' => 'Gewichteter Warenwert',
		'PMPValueShort' => 'DSWP',
		'EnhancedValueOfWarehouses' => 'Lagerwert',
		'UserWarehouseAutoCreate' => 'Beim Anlegen eines Benutzers automatisch neues Warenlager erstellen',
		'QtyDispatched' => 'Menge',
		'OrderDispatch' => 'Bestellabwicklung',
		'RuleForStockManagementDecrease' => 'Regel für Lagerstandsanpassung (Verringerung)',
		'RuleForStockManagementIncrease' => 'Regel für Lagerstandsanpassung (Erhöhung)',
		'DeStockOnBill' => 'Verringere realen Bestände in den Rechnungen / Gutschriften',
		'DeStockOnValidateOrder' => 'Decrease realen Bestände auf Bestellungen stellt fest',
		'DeStockOnShipment' => 'Verringere Lagerstände nach erfolgtem Versand (empfohlen)',
		'ReStockOnBill' => 'Erhöhung der tatsächlichen Bestände in den Rechnungen / Gutschriften',
		'ReStockOnValidateOrder' => 'Erhöhung der realen Bestände auf Bestellungen stellt fest',
		'ReStockOnDispatchOrder' => 'Reale Bestände auf manuelle Dispatching in Hallen, nach Erhalt Lieferanten bestellen',
		'OrderStatusNotReadyToDispatch' => 'Auftrag wurde noch nicht oder nicht mehr ein Status, der Erzeugnisse auf Lager Hallen Versand ermöglicht.',
		'StockDiffPhysicTeoric' => 'Grund für die Differenz physisch. und theoret. Lagerbestand',
		'NoPredefinedProductToDispatch' => 'Keine vordefinierten Produkte für dieses Objekt. Also kein Versand im Lager erforderlich ist.',
		'DispatchVerb' => 'Versand',
		'StockLimitShort' => 'Mindestbestand',
		'StockLimit' => 'Sicherungsbestand für autom. Benachrichtigung',
		'PhysicalStock' => 'Physisches Warenlager',
		'RealStock' => 'Realer Lagerbestand',
		'TheoreticalStock' => 'Theoretischer Lagerbestand',
		'VirtualStock' => 'Virtuelles Warenlager',
		'MininumStock' => 'Mindestlagerstand',
		'StockUp' => 'Aufstocken',
		'MininumStockShort' => 'Sicherungsbestand',
		'StockUpShort' => 'Aufstocken',
		'IdWarehouse' => 'Warenlager ID',
		'DescWareHouse' => 'Beschreibung Warenlager',
		'LieuWareHouse' => 'Standort Warenlager',
		'WarehousesAndProducts' => 'Warenlager und Produkte',
		'AverageUnitPricePMPShort' => 'Gewichteter Durchschnitts-Einkaufspreis',
		'AverageUnitPricePMP' => 'Gewichteter Durchschnitts-Eingangspreis',
		'SellPriceMin' => 'Verkaufspreis',
		'EstimatedStockValueSellShort' => 'Abverkaufsmenge',
		'EstimatedStockValueSell' => 'Abverkaufsmenge',
		'EstimatedStockValueShort' => 'Eingangsmenge',
		'EstimatedStockValue' => 'Eingangsmenge',
		'DeleteAWarehouse' => 'Warenlager löschen',
		'ConfirmDeleteWarehouse' => 'Möchten Sie das Warenlager <b>%s</b> wirklich löschen?',
		'PersonalStock' => 'Persönlicher Warenbestand %s',
		'ThisWarehouseIsPersonalStock' => 'Dieses Lager bezeichnet den persönlichen Bestand von %s %s',
		'SelectWarehouseForStockDecrease' => 'Wählen Sie das Lager für die Entnahme',
		'SelectWarehouseForStockIncrease' => 'Wählen Sie das Lager für den Wareneingang',
		'LastWaitingSupplierOrders' => 'Orders waiting for receptions'
);
?>