<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'Benutzerkarte',
		'ContactCard' => 'Kontaktkarte',
		'GroupCard' => 'Firmenverbundkarte',
		'NoContactCard' => 'Keine Kontaktkarte',
		'Permission' => 'Berechtigung',
		'Permissions' => 'Berechtigungen',
		'EditPassword' => 'Passwort bearbeiten',
		'SendNewPassword' => 'Neues Passwort zusenden',
		'ReinitPassword' => 'Passwort zurücksetzen',
		'PasswordChangedTo' => 'Neues Passwort: %s',
		'SubjectNewPassword' => 'Ihr neues Passwort',
		'AvailableRights' => 'Verfügbare Berechtigungen',
		'OwnedRights' => 'Besitz Berechtigungen',
		'GroupRights' => 'Gruppe Berechtigungen',
		'UserRights' => 'Benutzerberechtigungen',
		'UserGUISetup' => 'Einstellungen Benutzeroberfläche',
		'DisableUser' => 'Deaktiviere Benutzer',
		'DisableAUser' => 'Einen Benutzer deaktivieren',
		'DeleteUser' => 'Lösche Benutzer',
		'DeleteAUser' => 'Einen Benutzer löschen',
		'DisableGroup' => 'Deaktiviere Gruppe',
		'DisableAGroup' => 'Eine Gruppe deaktivieren',
		'EnableAUser' => 'Einen Benutzer aktivieren',
		'EnableAGroup' => 'Eine Gruppe aktivieren',
		'DeleteGroup' => 'Lösche Gruppe',
		'DeleteAGroup' => 'Eine Gruppe löschen',
		'ConfirmDisableUser' => 'Möchten Sie diesen Benutzer <b>%s</b> wirklich deaktivieren?',
		'ConfirmDisableGroup' => 'Möchten Sie diese Gruppe <b>%s</b> wirklich deaktivieren?',
		'ConfirmDeleteUser' => 'Möchten Sie diesen Benutzer <b>%s</b> wirklich löschen?',
		'ConfirmDeleteGroup' => 'Möchten Sie diese Gruppe <b>%s</b> wirklich löschen?',
		'ConfirmEnableUser' => 'Möchten Sie diesen Benutzer <b>%s</b> wirklich aktivieren?',
		'ConfirmEnableGroup' => 'Möchten Sie diese Gruppe <b>%s</b> wirklich aktivieren?',
		'ConfirmReinitPassword' => 'Möchten Sie das Passwort für Benutzer <b>%s</b> wirklich zurücksetzen',
		'ConfirmSendNewPassword' => 'Möchten Sie für diesen Benutzer <b>%s</b> wirklich ein neues Passwort generieren und diesem per Mail zusenden?',
		'NewUser' => 'Neuer Benutzer',
		'CreateUser' => 'Benutzer anlegen',
		'SearchAGroup' => 'Suche Gruppe',
		'SearchAUser' => 'Suche Benutzer',
		'LoginNotDefined' => 'Benutzername ist nicht gesetzt.',
		'NameNotDefined' => 'Name ist nicht gesetzt.',
		'ListOfUsers' => 'Liste der Benutzer',
		'Administrator' => 'Administrator',
		'SuperAdministrator' => 'Super Administrator',
		'SuperAdministratorDesc' => 'Administrator mit allen Rechten',
		'AdministratorDesc' => 'Administrator',
		'DefaultRights' => 'Standardberechtigungen',
		'DefaultRightsDesc' => 'Definieren Sie hier die neu erstellten Benutzern automatisch zugewiesenen Standardberechtigungen.',
		'SpeedealingUsers' => 'Speedealing users',
		'LastName' => 'Nachname',
		'FirstName' => 'Vorname',
		'ListOfGroups' => 'Liste von Gruppen',
		'NewGroup' => 'Neue Gruppe',
		'CreateGroup' => 'Gruppe erstellen',
		'RemoveFromGroup' => 'Gruppenzuweisung entfernen',
		'PasswordChangedAndSentTo' => 'Passwort geändert und an <b>%s</b> gesendet.',
		'PasswordChangeRequestSent' => 'Anfrage auf eine Änderung das Passworts für <b>%s</b> an <b>%s</b> gesendet.',
		'MenuUsersAndGroups' => 'Benutzer & Gruppen',
		'LastGroupsCreated' => '%s zuletzt erstellte Gruppen',
		'LastUsersCreated' => '%s zuletzt erstellte Benutzer',
		'ShowGroup' => 'Zeige Gruppe',
		'ShowUser' => 'Zeige Benutzer',
		'NonAffectedUsers' => 'Nicht betroffene Benutzer',
		'UserModified' => 'Benutzer erfolgreich bearbeitet',
		'GroupModified' => 'Gruppe erfolgreich bearbeitet',
		'PhotoFile' => 'Bilddatei',
		'UserWithSpeedealingAccess' => 'User with Speedealing access',
		'ListOfUsersInGroup' => 'Liste der Benutzer in dieser Gruppe',
		'ListOfGroupsForUser' => 'Liste der Gruppen dieses Benutzers',
		'UsersToAdd' => 'Dieser Gruppe zuzuweisende Benutzer',
		'GroupsToAdd' => 'Diesem Benutzer zuzuweisende Gruppen',
		'NoLogin' => 'Kein Login',
		'LinkToCompanyContact' => 'Mit Partner/Kontakt verknüpfen',
		'LinkedToSpeedealingMember' => 'Link to member',
		'LinkedToSpeedealingUser' => 'Link to Speedealing user',
		'LinkedToSpeedealingThirdParty' => 'Link to Speedealing third party',
		'CreateSpeedealingLogin' => 'Create a user',
		'CreateSpeedealingThirdParty' => 'Create a third party',
		'LoginAccountDisable' => 'Benutzerkonto deaktiviert. Zum Aktivieren bitte neuen Login anlegen.',
		'LoginAccountDisableInSpeedealing' => 'Account disabled in Speedealing.',
		'LoginAccountDisableInLdap' => 'Benutzerkonto in dieser Domäne deaktiviert.',
		'UsePersonalValue' => 'Eigenen Wert verwenden',
		'GuiLanguage' => 'Sprache der Benutzeroberfläche',
		'InternalUser' => 'Interne Benutzer',
		'MyInformations' => 'Meine Daten',
		'ExportDataset_user_1' => 'Benutzer und -eigenschaften',
		'DomainUser' => 'Domain-Benutzer %s',
		'Reactivate' => 'Reaktivieren',
		'CreateInternalUserDesc' => 'Dieses Formular erlaubt Ihnen das Anlegen eines unternehmensinternen Benutzers. Zum Anlegen eines externen Benutzers (Kunden, Lieferanten, ...), verwenden Sie bitte die \'Benutzer erstellen\'-Schaltfläche in der Kontaktkarte des jeweiligen Partnerkontakts.',
		'InternalExternalDesc' => 'Ein <b>interner</b> Benutzer ist Teil Ihres Unternehmens/Ihrer Stiftung. <br> Ein <b>externer</b> Benutzer ist ein Kunde, Lieferant oder Anderes.',
		'PermissionInheritedFromAGroup' => 'Berechtigung durch eine Gruppenzugehörigkeit gererbt.',
		'Inherited' => 'Geerbt',
		'UserWillBeInternalUser' => 'Erstellter Benutzer ist intern (mit keinem bestimmten Partner verknüpft)',
		'UserWillBeExternalUser' => 'Erstellter Benutzer ist extern (mit einem bestimmten Partner verknüpft)',
		'IdPhoneCaller' => 'Anrufer ID',
		'UserLogged' => 'Benutzer %s eingeloggt',
		'UserLogoff' => 'User %s ausgeloggt',
		'NewUserCreated' => 'Benutzer %s erstellt',
		'NewUserPassword' => 'Passwort ändern für %s',
		'EventUserModified' => 'Benutzer %s geändert',
		'UserDisabled' => 'Benutzer %s deaktiviert',
		'UserEnabled' => 'Benutzer %s aktiviert',
		'UserDeleted' => 'Benutzer %s entfernt',
		'NewGroupCreated' => 'Gruppe %s erstellt',
		'GroupModified' => 'Gruppe erfolgreich bearbeitet',
		'GroupDeleted' => 'Gruppe %s entfernt',
		'ConfirmCreateContact' => 'Möchten Sie für diesen Kontakt wirklich ein Systembenutzerkonto anlegen?',
		'ConfirmCreateLogin' => 'Möchten Sie für dieses Mitglied wirklich ein Benutzerkonto erstellen?',
		'ConfirmCreateThirdParty' => 'Möchten Sie zu diesem Mitglied wirklich einen Partner erstellen?',
		'LoginToCreate' => 'Zu erstellende Anmeldung',
		'NameToCreate' => 'Name des neuen Partners',
		'YourRole' => 'Ihre Rolle',
		'YourQuotaOfUsersIsReached' => 'Ihr Kontingent aktiver Benutzer ist erreicht',
		'NbOfUsers' => 'Anzahl der Benutzer',
		'DontDowngradeSuperAdmin' => 'Nur ein SuperAdmin kann einen SuperAdmin downgraden',
		'NewDatabase' => 'Nouvelle base de données',
		'CreateDatabase' => 'Créer la base de données',
		'ListOfDatabases' => 'Liste des bases de données',
		'ListOfUsersInDatabase' => 'Liste des utilisateurs liés à la base de données',
		'ListOfRolesInDatabase' => 'Liste des groupes liés à la base de données',
		'DeleteADatabase' => 'Suppression d\'une database',
		'ConfirmDatabase' => 'Êtes-vous sûr de vouloir supprimer la base de données <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Groupes non affectés à la base de données',
		'NonAffectedUsersDatabase' => 'Utilisateurs non affectés à la base de données',
		'Collaborators' => 'Collaborateurs',
		'Profiles' => 'Profils collaborateurs'
);
?>