<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Categoria',
		'Categories' => 'Categories',
		'Rubrique' => 'Categoria',
		'Rubriques' => 'Categorie',
		'categories' => 'Categorie',
		'TheCategorie' => 'La categoria',
		'NoCategoryYet' => 'Non esiste alcuna categoria di questo tipo',
		'In' => 'In',
		'AddIn' => 'Aggiungi a',
		'modify' => 'modifica',
		'Classify' => 'Classifica',
		'CategoriesArea' => 'Area categorie',
		'ProductsCategoriesArea' => 'Area categorie prodotti/servizi',
		'SuppliersCategoriesArea' => 'Area categorie fornitori',
		'CustomersCategoriesArea' => 'Area categorie di clienti',
		'ThirdPartyCategoriesArea' => 'Area categorie terzi',
		'MembersCategoriesArea' => 'Area categorie membri',
		'MainCats' => 'Categorie principali',
		'SubCats' => 'Sub-categorie',
		'CatStatistics' => 'Statistiche',
		'CatList' => 'Elenco delle categorie',
		'AllCats' => 'Tutte le categorie',
		'ViewCat' => 'Visualizza categoria',
		'NewCat' => 'Aggiungi categoria',
		'NewCategory' => 'Nuova categoria',
		'ModifCat' => 'Modifica categoria',
		'CatCreated' => 'Categoria creata',
		'CreateCat' => 'Crea categoria',
		'CreateThisCat' => 'Crea questa categoria',
		'ValidateFields' => 'Convalidare i campi',
		'NoSubCat' => 'Nessuna sottocategoria',
		'SubCatOf' => 'Sottocategoria',
		'FoundCats' => 'Categorie trovate',
		'FoundCatsForName' => 'Categorie trovate per il nome:',
		'FoundSubCatsIn' => 'Sottocategorie trovate nella categoria',
		'ErrSameCatSelected' => 'Hai selezionato la stessa categoria più volte',
		'ErrForgotCat' => 'Hai dimenticato di scegliere la categoria',
		'ErrForgotField' => 'Hai dimenticato di indicare i campi',
		'ErrCatAlreadyExists' => 'La categoria esiste già',
		'AddProductToCat' => 'Inserire il prodotto in una categoria?',
		'ImpossibleAddCat' => 'Impossibile aggiungere la categoria',
		'ImpossibleAssociateCategory' => 'Impossibile associare la categoria a',
		'WasAddedSuccessfully' => '<b> %s </b> aggiunta con successo',
		'ObjectAlreadyLinkedToCategory' => 'L\'elemento appartiene già questa categoria.',
		'CategorySuccessfullyCreated' => 'La categoria %s è stata aggiunta con successo.',
		'ProductIsInCategories' => 'Il Prodotto/servizio appartiene alle seguenti categorie',
		'SupplierIsInCategories' => 'Questo Fornitore appartiene alle seguenti categorie',
		'CompanyIsInCustomersCategories' => 'Questa società si trova nelle seguenti categorie di clienti',
		'CompanyIsInSuppliersCategories' => 'Questa società si trova nelle seguenti categorie di fornitori',
		'MemberIsInCategories' => 'Questo membro appartiene alle seguenti categorie',
		'ProductHasNoCategory' => 'Il prodotto/servizio non apaprtiene ad alcuna categoria',
		'SupplierHasNoCategory' => 'Questo fornitore non appartiene ad alcuna categoria',
		'CompanyHasNoCategory' => 'Questa società non è in alcuna categoria',
		'MemberHasNoCategory' => 'Questo membro non è in alcuna categoria',
		'ClassifyInCategory' => 'Classificare nella categoria',
		'NoneCategory' => 'Nessuna',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Questa categoria esiste già allo stesso livello',
		'ReturnInProduct' => 'Torna alla scheda prodotto/servizio',
		'ReturnInSupplier' => 'Torna alla scheda fornitore',
		'ReturnInCompany' => 'Torna alla scheda cliente',
		'ContentsVisibleByAll' => 'I contenuti saranno visibili a tutti gli utenti',
		'ContentsVisibleByAllShort' => 'Contenuti visibili a tutti',
		'ContentsNotVisibleByAllShort' => 'Contenuti non visibili a tutti',
		'CategoriesTree' => 'Gerarchia delle categorie',
		'DeleteCategory' => 'Elimina categoria',
		'ConfirmDeleteCategory' => 'Vuoi davvero eliminare questa categoria?',
		'RemoveFromCategory' => 'Rimuovi collegamento con la categoria',
		'RemoveFromCategoryConfirm' => 'Sei sicuro di voler rimuovere il legame tra l\'operazione e la categoria?',
		'NoCategoriesDefined' => 'Nessuna categoria definita',
		'SuppliersCategoryShort' => 'Categoria fornitori',
		'CustomersCategoryShort' => 'Categoria clienti',
		'ProductsCategoryShort' => 'Categorie prodotti',
		'MembersCategoryShort' => 'Categoria membri',
		'SuppliersCategoriesShort' => 'Categorie fornitori',
		'CustomersCategoriesShort' => 'Categorie clienti',
		'CustomersProspectsCategoriesShort' => 'Categorie clienti potenziali',
		'ProductsCategoriesShort' => 'Categorie dei prodotti/servizi',
		'MembersCategoriesShort' => 'Categorie membri',
		'ThisCategoryHasNoProduct' => 'Questa categoria non contiene alcun prodotto',
		'ThisCategoryHasNoSupplier' => 'Questa categoria non contiene alcun fornitore',
		'ThisCategoryHasNoCustomer' => 'Questa categoria non contiene alcun cliente',
		'ThisCategoryHasNoMember' => 'Questa categoria non contiene alcun membro',
		'AssignedToCustomer' => 'Assegnato ad un cliente',
		'AssignedToTheCustomer' => 'Assegnato al cliente',
		'InternalCategory' => 'Categoria interna',
		'CategoryContents' => 'Contenuti categoria',
		'CategId' => 'Id categoria',
		'CatSupList' => 'Elenco delle categorie per i fornitori',
		'CatCusList' => 'Elenco delle categorie per i clienti/clienti potenziali',
		'CatProdList' => 'Elenco delle categorie per i prodotti',
		'CatMemberList' => 'Elenco delle categorie per i membri',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>