<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Commerciale',
		'CommercialArea' => 'Area commerciale',
		'CommercialCard' => 'Scheda commerciale',
		'CustomerArea' => 'Sezione clienti',
		'Customer' => 'Cliente',
		'Customers' => 'Clienti',
		'Prospect' => 'Cliente potenziale',
		'Prospects' => 'Clienti potenziali',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Elimina un\'azione/compito',
		'NewAction' => 'Nuova azione/compito',
		'AddAction' => 'Aggiungi azione/compito',
		'AddAnAction' => 'Aggiungi un\'azione/compito',
		'AddActionRendezVous' => 'Aggiungi un appuntamento',
		'Rendez-Vous' => 'Appuntantamenti',
		'ConfirmDeleteAction' => 'Vuoi davvero eliminare questa azione?',
		'CardAction' => 'Scheda Azione/compito',
		'PercentDone' => 'Percentuale di completamento',
		'ActionOnCompany' => 'Azione per la società',
		'ActionOnContact' => 'Azione al contatto',
		'TaskRDV' => 'Riunioni',
		'TaskRDVWith' => 'Incontro con %s',
		'ShowTask' => 'Visualizza compito',
		'ShowAction' => 'Visualizza azione',
		'ActionsReport' => 'Prospetto azioni',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Venditore',
		'SalesRepresentatives' => 'Venditori',
		'SalesRepresentativeFollowUp' => 'Venditore (di follow-up)',
		'SalesRepresentativeSignature' => 'Venditore (firma)',
		'CommercialInterlocutor' => 'Interlocutore commerciale',
		'ErrorWrongCode' => 'Codice sbagliato',
		'NoSalesRepresentativeAffected' => 'Nessun venditore interessato',
		'ShowCustomer' => 'Visualizza cliente',
		'ShowProspect' => 'Visualizza cliente potenziale',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Elenco dei clienti potenziali',
		'ListOfCustomers' => 'Elenco dei clienti',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'Ultime %s azioni portate a termine',
		'LastRecordedTasks' => 'Ultime azioni registrate',
		'LastActionsToDo' => 'Ultime %s azioni più vecchie da fare',
		'DoneAndToDoActionsFor' => 'Azioni fatte o da fare per %s',
		'DoneAndToDoActions' => 'Azioni fatte o da fare',
		'DoneActions' => 'Azioni fatte',
		'DoneActionsFor' => 'Azioni fatte per %s',
		'ToDoActions' => 'Azioni da fare',
		'ToDoActionsFor' => 'Azioni da fare per %s',
		'SendPropalRef' => 'Invia preventivo %s',
		'SendOrderRef' => 'Invia per %s',
		'StatusNotApplicable' => 'Non applicabile',
		'StatusActionToDo' => 'Da fare',
		'StatusActionDone' => 'Fatto',
		'StatusActionInProcess' => 'In corso',
		'MyActionsAsked' => 'Azioni registrate da me',
		'MyActionsToDo' => 'Azioni che devo fare',
		'MyActionsDone' => 'Azioni fatte da me',
		'TasksHistoryForThisContact' => 'Storico del contatto',
		'LastProspectDoNotContact' => 'Non contattare',
		'LastProspectNeverContacted' => 'Mai contattato',
		'LastProspectToContact' => 'Da contattare',
		'LastProspectContactInProcess' => 'Contatti in corso',
		'LastProspectContactDone' => 'Ultimo contatto effettuato',
		'DateActionPlanned' => 'Data prevista per l\'azione',
		'DateActionDone' => 'Data compimento azione',
		'ActionAskedBy' => 'Azione richiesta da',
		'ActionAffectedTo' => 'Azione riguardante',
		'ActionDoneBy' => 'Azione da fare',
		'ActionUserAsk' => 'Riferita da',
		'ErrorStatusCantBeZeroIfStarted' => 'Se il campo "fatto in <b>Data</b>" contiene qualcosa e l\'azione è stata avviata (o finita), il campo "<b>Stato</b>" non può essere 0%%.',
		'ActionAC_TEL' => 'Telefonata',
		'ActionAC_FAX' => 'Invia fax',
		'ActionAC_PROP' => 'Invia proposta',
		'ActionAC_EMAIL' => 'Invia email',
		'ActionAC_RDV' => 'Riunione',
		'ActionAC_FAC' => 'Invia fattura',
		'ActionAC_REL' => 'Invia la fattura (promemoria)',
		'ActionAC_CLO' => 'Chiudere',
		'ActionAC_EMAILING' => 'Invia email di massa',
		'ActionAC_COM' => 'Per inviare via email',
		'ActionAC_SHIP' => 'Invia spedizione per posta',
		'ActionAC_SUP_ORD' => 'Invia ordine fornitore tramite email',
		'ActionAC_SUP_INV' => 'Invia fattura fornitore tramite email',
		'ActionAC_OTH' => 'Altro',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Stato del cliente potenziale',
		'DraftPropals' => 'Bozze di proposte commerciali',
		'SearchPropal' => 'Cerca una proposta commerciale'
);
?>