<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$errors = array(
		'CHARSET' => 'UTF-8',
		'MenuManager' => 'Gestore dei menu',
		// Errors
		'Error' => 'Errore',
		'Errors' => 'Errori',
		'ErrorBadEMail' => 'L\'indirizzo email %s è sbagliato',
		'ErrorBadUrl' => 'L\'URL %s è sbagliato',
		'ErrorLoginAlreadyExists' => 'Login %s già esistente',
		'ErrorGroupAlreadyExists' => 'Il gruppo %s esiste già',
		'ErrorRecordNotFound' => 'Record non trovato',
		'ErrorFailToCopyFile' => 'Impossibile copiare il file <b>%s</b> in <b>%s</b>',
		'ErrorFailToRenameFile' => 'Impossibile rinominare il file <b>%s</b> in <b>%s</b>',
		'ErrorFailToDeleteFile' => 'Impossibile rimuovere il file <b>%s</b>',
		'ErrorFailToCreateFile' => 'Impossibile creare il file <b>%s</b>',
		'ErrorFailToRenameDir' => 'Impossibile rinominare la directory <b>%s</b> in <b>%s</b>',
		'ErrorFailToCreateDir' => 'Impossibile creare la directory <b>%s</b>',
		'ErrorFailToDeleteDir' => 'Impossibile eliminare la directory <b>%s</b>',
		'ErrorFailedToDeleteJoinedFiles' => 'Impossibile eliminare i file collegati. Rimuovere i collegamenti ai file prima di eliminare.',
		'ErrorThisContactIsAlreadyDefinedAsThisType' => 'Questo contatto è già stato definito per questo tipo.',
		'ErrorCashAccountAcceptsOnlyCashMoney' => 'Questo conto corrente è un conto di cassa che accetta solo pagamenti in contanti.',
		'ErrorFromToAccountsMustDiffers' => 'I conti bancari di origine e destinazione devono essere diversi.',
		'ErrorBadThirdPartyName' => 'Valore non valido per il nome del soggetto terzo',
		'ErrorBadCustomerCodeSyntax' => 'Sintassi errata per il codice cliente',
		'ErrorCustomerCodeRequired' => 'Codice cliente necessario',
		'ErrorCustomerCodeAlreadyUsed' => 'Codice cliente già utilizzato',
		'ErrorPrefixRequired' => 'È richiesto il prefisso',
		'ErrorUrlNotValid' => 'L\'indirizzo del sito è errato',
		'ErrorBadSupplierCodeSyntax' => 'Sintassi del codice fornitore errata',
		'ErrorSupplierCodeRequired' => 'Il codice fornitore è un dato necessario',
		'ErrorSupplierCodeAlreadyUsed' => 'Codice fornitore già utilizzato',
		'ErrorBadParameters' => 'Parametri errati',
		'ErrorBadValueForParameter' => 'Valore errato &#39;%s&#39; per il parametro &#39;%s&#39;',
		'ErrorBadImageFormat' => 'Formato del file immagine non supportato',
		'ErrorBadDateFormat' => 'Il valore \'%s\' ha un formato della data sbagliato',
		'ErrorFailedToWriteInDir' => 'Impossibile scrivere nella directory %s',
		'ErrorFoundBadEmailInFile' => 'Sintassi email errata nelle righe %s del file (ad esempio, alla riga %s con email = %s)',
		'ErrorUserCannotBeDelete' => 'L\'utente non può essere eliminato. Probabilmente è necessario al funzionamento di Dolibarr.',
		'ErrorFieldsRequired' => 'Alcuni campi obbligatori non sono stati riempiti.',
		'ErrorFailedToCreateDir' => 'Creazione directory impossibile. Verifica che l\'utente del server Web abbia i permessi per scrivere nella directory Dolibarr. Se il parametro <b>safe_mode</b> è abilitato in PHP, verificare che i file php di Dolibarr appartengano all\'utente o gruppo del server web (per esempio www-data).',
		'ErrorNoMailDefinedForThisUser' => 'Nessun messaggio impostato per questo utente',
		'ErrorFeatureNeedJavascript' => 'Questa funzione necessita di javascript per essere attivata. Modificare questa impostazione nel menu Impostazioni - layout di visualizzazione.',
		'ErrorTopMenuMustHaveAParentWithId0' => 'Un menu di tipo "Top" non può avere un menu principale. Metti 0 menu genitori o scegli un menu di tipo "Left".',
		'ErrorLeftMenuMustHaveAParentId' => 'Un menu di tipo \'sub-menu\' deve avere un id genitore',
		'ErrorFileNotFound' => 'File non trovato (percorso errato o autorizzazioni insufficienti per l\'accesso)',
		'ErrorDirNotFound' => 'Directory <b>%s</b> non trovata (permessi errati o accesso negato da openbasedir, PHP safe_mode o altri parametri)',
		'ErrorFunctionNotAvailableInPHP' => 'Per questa funzione occorre l\'estensione <b>%s</b>, ma non è disponibile in questa versione/configurazione di PHP.',
		'ErrorDirAlreadyExists' => 'Una directory con questo nome esiste già.',
		'ErrorFileAlreadyExists' => 'Un file con questo nome esiste già.',
		'ErrorPartialFile' => 'File non completamente ricevuto dal server.',
		'ErrorNoTmpDir' => 'La directory temporanea %s non esiste.',
		'ErrorUploadBlockedByAddon' => 'Upload bloccato da un plugin di Apache/PHP',
		'ErrorFileSizeTooLarge' => 'La dimensione del file è troppo grande.',
		'ErrorSizeTooLongForIntType' => 'Numero troppo lungo (massimo %s cifre)',
		'ErrorSizeTooLongForVarcharType' => 'Stringa troppo lunga (%s caratteri al massimo)',
		'ErrorFieldCanNotContainSpecialCharacters' => 'Il campo <b>%s</b> non può contenere caratteri speciali.',
		'ErrorNoAccountancyModuleLoaded' => 'Modulo contabilità disattivato',
		'ErrorExportDuplicateProfil' => 'Questo nome di profilo esiste già nell\'esportazione.',
		'ErrorLDAPSetupNotComplete' => 'La configurazione per l\'uso di LDAP è incompleta',
		'ErrorLDAPMakeManualTest' => 'Un file Ldif è stato generato nella directory %s. Prova a caricarlo dalla riga di comando per avere maggiori informazioni sugli errori.',
		'ErrorCantSaveADoneUserWithZeroPercentage' => 'Impossibile salvare un\'azione con "stato non iniziato" se il campo "da fare" non è vuoto.',
		'ErrorRefAlreadyExists' => 'Il riferimento utilizzato esiste già.',
		'ErrorPleaseTypeBankTransactionReportName' => 'Indicare il nome del report della transazione bancaria (Nel formato AAAAMM o AAAAMMGG)',
		'ErrorRecordHasChildren' => 'Impossibile eliminare i record da cui dipendono altri record',
		'ErrorModuleRequireJavascript' => 'Per questa funzionalità Javascript deve essere attivo. Per abilitare/disabilitare Javascript, vai su <b>Home - Impostazioni - Schermo</b>',
		'ErrorPasswordsMustMatch' => 'Le due password digitate devono essere identiche',
		'ErrorContactEMail' => 'Si è verificato un errore tecnico. Si prega di contattare l\'amministratore all\'indirizzo <b>%s</b> <b>%s</b> indicando il codice di errore nel messaggio, o, meglio ancora, allegando uno screenshot della schermata attuale.',
		'ErrorWrongValueForField' => 'Valore errato nel campo numero <b>%s</b> (il valore <b>\'%s\'</b>non corrisponde alla regex <b>%s</b>)',
		'ErrorFieldValueNotIn' => 'Valore errato nel campo numero <b>%s</b>(il valore <b>%s</b> non è un valore disponibile nel campo<b>%s</b> campo della tabella <b>%s</b>)',
		'ErrorFieldRefNotIn' => 'Valore errato nel campo numero <b>%s</b> (il valore <b>%s</b>non è un riferimento <b>%s</b> esistente)',
		'ErrorsOnXLines' => 'Errori in <b>%s</b> righe del sorgente',
		'ErrorFileIsInfectedWithAVirus' => 'Il programma antivirus non è stato in grado di convalidare il file (il file potrebbe essere infetto)',
		'ErrorSpecialCharNotAllowedForField' => 'I caratteri speciali non sono ammessi per il campo <b>%s</b>',
		'ErrorDatabaseParameterWrong' => 'Il parametro di configurazione database <b>\'%s\'</b> ha un valore non compatibile con il funzionamento di Dolibarr (deve avere un valore <b>\'%s\').</b>',
		'ErrorNumRefModel' => 'Esiste un riferimento nel database (%s) e non è compatibile con questa regola di numerazione. Rimuovere o rinominare il record per attivare questo modulo.',
		'ErrorQtyTooLowForThisSupplier' => 'Quantità troppa bassa per questo fornitore o nessun prezzo definito sul prodotto per questo fornitore',
		'ErrorModuleSetupNotComplete' => 'L\'installazione del modulo pare incompleta. Vai su <b>Impostazioni - Moduli</b> per completarla.',
		'ErrorBadMask' => 'Errore sulla maschera',
		'ErrorBadMaskFailedToLocatePosOfSequence' => 'Errore, maschera senza numero di sequenza',
		'ErrorBadMaskBadRazMonth' => 'Errore, valore di reset non valido',
		'ErrorSelectAtLeastOne' => 'Errore. Selezionare almeno una voce.',
		'ErrorProductWithRefNotExist' => 'Il prodotto con riferimento %s non esiste',
		'ErrorDeleteNotPossibleLineIsConsolidated' => 'Impossibile cancellare il record perché è collegato ad una transazione bancaria conciliata',
		'ErrorProdIdAlreadyExist' => '%s è già assegnato',
		'ErrorFailedToSendPassword' => 'Impossibile inviare la password',
		'ErrorFailedToLoadRSSFile' => 'Impossibile ottenere feed RSS. Prova ad ativare il debug con MAIN_SIMPLEXMLLOAD_DEBUG, se i messaggi di errore non forniscono informazioni sufficienti.',
		'ErrorPasswordDiffers' => 'Le password immesse sono diverse, digitarle nuovamente.',
		'ErrorForbidden' => 'Accesso vietato.<br/>Si tenta di accedere a una pagina o a un\'area senza autenticazione o con diritti insufficienti',
		'ErrorForbidden2' => 'L\'autorizzazione all\'accesso per questi dati può essere impostata dall\'amministratore di Dolibarr tramite il menu %s - %s.',
		'ErrorForbidden3' => 'Sembra che Dolibarr non venga utilizzato tramite una sessione autenticata. Dai un\'occhiata alla documentazione di installazione Dolibarr per sapere come gestire le autenticazioni (htaccess, mod_auth o altri...).',
		'ErrorNoImagickReadimage' => 'La funzione Imagick_readimage non è stata trovato nel PHP. L\'anteprima non è disponibile. Gli amministratori possono disattivare questa scheda dal menu <b>Impostazioni - Schermo</b>',
		'ErrorRecordAlreadyExists' => 'Il record esiste già',
		'ErrorCantReadFile' => 'Impossibile leggere il file <b>%s</b>',
		'ErrorCantReadDir' => 'Impossibile leggere nella directory <b>%s</b>',
		'ErrorFailedToFindEntity' => 'Impossibile leggere l\'entità \'%s\' (non trovata)',
		'ErrorBadLoginPassword' => 'Errore: Username o password non corretti',
		'ErrorLoginDisabled' => 'L\'account è stato disabilitato',
		'ErrorFailedToRunExternalCommand' => 'Impossibile eseguire il comando esterno. Controlla che sia disponibile ed eseguibile dal server PHP. Se la modalità <b>safe_mode</ b> è abilitata in PHP, verificare che il comando sia all\'interno di una directory definita dal parametro <b>safe_mode_exec_dir</ b>.',
		'ErrorFailedToChangePassword' => 'Impossibile cambiare la password',
		'ErrorLoginDoesNotExists' => 'Utente con accesso <b>%s</b> inesistente',
		'ErrorLoginHasNoEmail' => 'Questo utente non ha alcun indirizzo email. Processo interrotto.',
		'ErrorBadValueForCode' => 'Valore del codice errato. Riprova con un nuovo valore...',
		'ErrorBothFieldCantBeNegative' => 'I campi %s e %s non possono essere entrambi negativi',
		'ErrorWebServerUserHasNotPermission' => 'L\'account utente <b>%s</b> utilizzato per eseguire il server web non ha i permessi necessari',
		'ErrorNoActivatedBarcode' => 'Nessun tipo di codice a barre attivato',
		'ErrUnzipFails' => 'Failed to unzip %s with ZipArchive',
		'ErrNoZipEngine' => 'No engine to unzip %s file in this PHP',
		'ErrorFileMustBeADolibarrPackage' => 'The file %s must be a Dolibarr zip package',
		'ErrorFileRequired' => 'It takes a package Dolibarr file',
		'ErrorPhpCurlNotInstalled' => 'The PHP CURL is not installed, this is essential to talk with Paypal',
		'ErrorFailedToAddToMailmanList' => 'Failed to add record to Mailman list or SPIP base',
		'ErrorNewVaueCantMatchOldValue' => 'New value can\'t be equal to old one',
		'ErrorDuplicateTrigger' => 'Un fichier trigger de classe \'<b>%s</b>\' est présent plusieurs fois. Supprimer le doublon du répertoire \'<b>%s</b>\'.',
		'SESSIONEXPIRE' => 'La session est expirée',
		// Warnings
		'WarningMandatorySetupNotComplete' => 'Mandatory setup parameters are not yet defined',
		'WarningSafeModeOnCheckExecDir' => 'Attenzione, quando l\'opzione <b>safe_mode</b> del PHP è attiva, il comando deve essere contenuto in una directory dichiarata dal parametro <b>safe_mode_exec_dir</b>.',
		'WarningAllowUrlFopenMustBeOn' => 'Il parametro <b>allow_url_fopen</b> deve essere impostato su <b>on</b> nel file <b>php.ini</b> perché questo modulo funzioni correttamente. È necessario modificare questo file manualmente.',
		'WarningBuildScriptNotRunned' => 'Lo script <b>%s</b> per disegnare il grafico non è stato eseguito, o non ci sono dati da visualizzare.',
		'WarningBookmarkAlreadyExists' => 'Un segnalibro per questo link (URL) o con lo stesso titolo esiste già.',
		'WarningPassIsEmpty' => 'Attenzione, il database è accessibile senza password. Questa è una grave falla di sicurezza! Si dovrebbe aggiungere una password per il database e cambiare il file <b>conf.php</b> di conseguenza.',
		'WarningConfFileMustBeReadOnly' => 'Attenzione, il file di configurazione <b>htdocs/conf/conf.php</b> è scrivibile dal server web. Questa è una grave falla di sicurezza! Impostare il file in sola lettura per l\'utente utilizzato dal server web. Se si utilizza Windows e il formato FAT per il disco, dovete sapere che tale filesystem non consente la gestione delle autorizzazioni sui file, quindi non può essere completamente sicuro.',
		'WarningsOnXLines' => 'Warning su <b>%s</b> righe del sorgente',
		'WarningNoDocumentModelActivated' => 'Nessun modello per la generazione di documenti attivato. Finché non si verifica la configurazione del modulo, verrà usato un modello predefinito.',
		'WarningLockFileDoesNotExists' => 'Warning, once setup is finished, you must disable install/migrate tools by adding a file <b>install.lock</b> into directory <b>%s</b>. Missing this file is a security hole.',
		'WarningUntilDirRemoved' => 'Questo avviso sarà visualizzato fino a quando questa directory è presente (disponibile solo per gli utenti admin).',
		'WarningCloseAlways' => 'Warning, closing is done even if amount differs between source and target elements. Enable this feature with caution.'
);
?>