<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$other = array(
		'CHARSET' => 'UTF-8',
		'SecurityCode' => 'Codice di sicurezza',
		'Calendar' => 'Calendario',
		'AddTrip' => 'Aggiungi viaggio',
		'Tools' => 'Strumenti',
		'ToolsDesc' => 'Quest\'area è dedicata agli strumenti di gruppo non disponibili in varie voci di menu.<br/><br/>Questi strumenti sono raggiungibili dal menu laterale.',
		'Birthday' => 'Compleanno',
		'BirthdayDate' => 'Data compleanno',
		'DateToBirth' => 'Data di nascita',
		'BirthdayAlertOn' => 'Attiva avviso compleanni',
		'BirthdayAlertOff' => 'Avviso compleanni inattivo',
		'Notify_FICHINTER_VALIDATE' => 'Intervento convalidato',
		'Notify_BILL_VALIDATE' => 'Convalida fattura attiva',
		'Notify_ORDER_SUPPLIER_APPROVE' => 'Ordine fornitore approvato',
		'Notify_ORDER_SUPPLIER_REFUSE' => 'Ordine fornitore rifiutato',
		'Notify_ORDER_VALIDATE' => 'Ordine cliente convalidato',
		'Notify_PROPAL_VALIDATE' => 'proposta convalidata',
		'Notify_WITHDRAW_TRANSMIT' => 'Invia prelievo',
		'Notify_WITHDRAW_CREDIT' => 'Accredita prelievo',
		'Notify_WITHDRAW_EMIT' => 'Esegui prelievo',
		'Notify_ORDER_SENTBYMAIL' => 'Ordine cliente inviato per email',
		'Notify_COMPANY_CREATE' => 'Creato soggetto terzo',
		'Notify_PROPAL_SENTBYMAIL' => 'Proposta inviata per email',
		'Notify_ORDER_SENTBYMAIL' => 'Ordine cliente inviato per email',
		'Notify_BILL_PAYED' => 'Fattura attiva pagata',
		'Notify_BILL_CANCEL' => 'Fattura attiva annullata',
		'Notify_BILL_SENTBYMAIL' => 'Fattura attiva inviata per email',
		'Notify_ORDER_SUPPLIER_VALIDATE' => 'Ordine fornitore convalidato',
		'Notify_ORDER_SUPPLIER_SENTBYMAIL' => 'Ordine fornitore inviato per email',
		'Notify_BILL_SUPPLIER_VALIDATE' => 'Fattura fornitore convalidata',
		'Notify_BILL_SUPPLIER_PAYED' => 'Fattura fornitore pagata',
		'Notify_BILL_SUPPLIER_SENTBYMAIL' => 'Fattura fornitore inviata per email',
		'Notify_CONTRACT_VALIDATE' => 'Contratto convalidato',
		'Notify_FICHEINTER_VALIDATE' => 'Intervento convalidato',
		'Notify_SHIPPING_VALIDATE' => 'Spedizione convalidata',
		'Notify_SHIPPING_SENTBYMAIL' => 'Spedizione inviata per email',
		'Notify_MEMBER_VALIDATE' => 'Membro convalidato',
		'Notify_MEMBER_SUBSCRIPTION' => 'Membro aggiunto',
		'Notify_MEMBER_RESILIATE' => 'Membro revocato',
		'Notify_MEMBER_DELETE' => 'Membro eliminato',
		'NbOfAttachedFiles' => 'Numero di file/documenti allegati',
		'TotalSizeOfAttachedFiles' => 'Dimensione totale dei file/documenti allegati',
		'MaxSize' => 'La dimensione massima è',
		'AttachANewFile' => 'Allega un nuovo file/documento',
		'LinkedObject' => 'Oggetto collegato',
		'Miscellanous' => 'Varie',
		'NbOfActiveNotifications' => 'Numero di notifiche attive',
		'PredefinedMailTest' => 'Questa è una mail di prova. \NLe due linee sono separate da un a capo.',
		'PredefinedMailTestHtml' => 'Questa è una mail <b>di test</b> (la parola test deve risultare in grassetto).<br/> Le due linee sono separate da un a capo.',
		'PredefinedMailContentSendInvoice' => 'Alleghiamo la fattura __FACREF__ \n\n__PERSONALIZED__ Cordiali Saluti \n\n__SIGNATURE__',
		'PredefinedMailContentSendInvoiceReminder' => 'Vorremmo portare alla Vostra attenzione che la fattura __FACREF__ sembra non essere stata saldata. La fattura è allegata alla presente, come promemoria. \n\n__PERSONALIZED__ Cordiali saluti \n\n__SIGNATURE__',
		'PredefinedMailContentSendProposal' => 'Alleghiamo la proposta commerciale __PROPREF__ \n\n__PERSONALIZED__ Cordiali Saluti \n\n__SIGNATURE__',
		'PredefinedMailContentSendOrder' => 'Alleghiamo l\'ordine __ORDERREF__ \n\n__PERSONALIZED__ Cordiali Saluti \n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierOrder' => 'Alleghiamo il nostro ordine n __ORDERREF__ \n\n__PERSONALIZED__Cordiali Saluti \n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierInvoice' => 'Alleghiamo la fattura __FACREF__ \n\n__PERSONALIZED__Cordiali Saluti \n\n__SIGNATURE__',
		'PredefinedMailContentSendShipping' => 'Alleghiamo la spedizione __SHIPPINGREF__ \n\n__PERSONALIZED__Cordiali Saluti \n\n__SIGNATURE__',
		'PredefinedMailContentSendFichInter' => 'Alleghiamo l\'intervento __FICHINTERREF__ \n\n__PERSONALIZED__Cordiali saluti \n\n__SIGNATURE__',
		'DemoDesc' => 'Speedealing è un ERP/CRM compatto composto di diversi moduli funzionali. Un demo comprendente tutti i moduli non ha alcun senso, perché un caso simile non esiste nella realtà. Sono dunque disponibili diversi profili demo.',
		'ChooseYourDemoProfil' => 'Scegli il profilo demo che corrisponde alla tua attività ...',
		'DemoFundation' => 'Gestisci i membri di una Fondazione',
		'DemoFundation2' => 'Gestisci i membri e un conto bancario di una Fondazione',
		'DemoCompanyServiceOnly' => 'Gestire un\'attività freelance di vendita di soli servizi',
		'DemoCompanyShopWithCashDesk' => 'Gestire un negozio con una cassa',
		'DemoCompanyProductAndStocks' => 'Gestire una piccola o media azienda che vende prodotti',
		'DemoCompanyAll' => 'Gestire una piccola o media azienda con più attività (tutti i moduli principali)',
		'GoToDemo' => 'Vai alla demo',
		'CreatedBy' => 'Creato da %s',
		'ModifiedBy' => 'Modificato da %s',
		'ValidatedBy' => 'Convalidato da %s',
		'CanceledBy' => 'Annullato da %s',
		'ClosedBy' => 'Chiuso da %s',
		'FileWasRemoved' => 'Il file è stato eliminato',
		'DirWasRemoved' => 'La directory è stata rimossa',
		'FeatureNotYetAvailableShort' => 'Available in a next version',
		'FeatureNotYetAvailable' => 'Funzionalità non ancora disponibile in questa versione',
		'FeatureExperimental' => 'Funzinalità sperimentale. Non stabile in questa versione',
		'FeatureDevelopment' => 'Funzionalità in fase di sviluppo. Non stabile in questa versione',
		'FeaturesSupported' => 'Funzionalità supportate',
		'Width' => 'Larghezza',
		'Height' => 'Altezza',
		'Depth' => 'Profondità',
		'Top' => 'Top',
		'Bottom' => 'Fondo',
		'Left' => 'Sinistra',
		'Right' => 'Destra',
		'CalculatedWeight' => 'Peso calcolato',
		'CalculatedVolume' => 'volume calcolato',
		'Weight' => 'Peso',
		'TotalWeight' => 'Peso totale',
		'WeightUnitton' => 't',
		'WeightUnitkg' => 'kg',
		'WeightUnitg' => 'g',
		'WeightUnitmg' => 'mg',
		'WeightUnitpound' => 'pound',
		'Length' => 'Lunghezza',
		'LengthUnitm' => 'm',
		'LengthUnitdm' => 'dm',
		'LengthUnitcm' => 'cm',
		'LengthUnitmm' => 'mm',
		'Surface' => 'Superficie',
		'SurfaceUnitm2' => 'm<sup>2</sup>',
		'SurfaceUnitdm2' => 'dm<sup>2</sup>',
		'SurfaceUnitcm2' => 'cm<sup>2</sup>',
		'SurfaceUnitmm2' => 'mm<sup>2</sup>',
		'SurfaceUnitfoot2' => 'ft2',
		'SurfaceUnitinch2' => 'in2',
		'Volume' => 'Volume',
		'TotalVolume' => 'Volume totale',
		'VolumeUnitm3' => 'm<sup>3</sup>',
		'VolumeUnitdm3' => 'dm<sup>3</sup>',
		'VolumeUnitcm3' => 'cm<sup>3</sup>',
		'VolumeUnitmm3' => 'mm<sup>3</sup>',
		'VolumeUnitfoot3' => 'ft3',
		'VolumeUnitinch3' => 'in3',
		'VolumeUnitounce' => 'oncia',
		'VolumeUnitlitre' => 'litro',
		'VolumeUnitgallon' => 'gallone',
		'Size' => 'Dimensione',
		'SizeUnitm' => 'm',
		'SizeUnitdm' => 'dm',
		'SizeUnitcm' => 'cm',
		'SizeUnitmm' => 'mm',
		'SizeUnitinch' => 'pollice',
		'SizeUnitfoot' => 'piede',
		'SizeUnitpoint' => 'point',
		'BugTracker' => 'Bug tracker',
		'SendNewPasswordDesc' => 'Questo modulo consente di richiedere una nuova password che verrà inviata al tuo indirizzo email.<br/> Il cambiamento sarà effettivo solo dopo aver cliccato sul link di conferma contenuto nell\'email.<br/> Controlla la tua casella email.',
		'BackToLoginPage' => 'Torna alla pagina di login',
		'AuthenticationDoesNotAllowSendNewPassword' => 'La modalità di autenticazione è <b>%s</b>.<br/>In questa modalità Speedealing non può sapere né cambiare la tua password.<br/>Contatta l\'amministratore di sistema se desideri cambiare password.',
		'EnableGDLibraryDesc' => 'Per usare questa opzione bisogna installare o abilitare la libreria GD in PHP.',
		'EnablePhpAVModuleDesc' => 'È necessario installare un modulo compatibile con il vostro antivirus. (per ClamAV: php4-clamavlib o php5-clamavlib)',
		'ProfIdShortDesc' => '<b>Prof ID %s</b> è un dato dipendente dal paese terzo.<br/> Ad esempio, per il <b>paese %s,</b> è il <b>codice %s.</b>',
		'SpeedealingDemo' => 'Speedealing ERP/CRM demo',
		'StatsByNumberOfUnits' => 'Statistiche per numero di unità',
		'StatsByNumberOfEntities' => 'Statistiche per numero di entità',
		'NumberOfProposals' => 'Numero di proposte degli ultimi 12 mesi',
		'NumberOfCustomerOrders' => 'Numero di ordini dei clienti degli ultimi 12 mesi',
		'NumberOfCustomerInvoices' => 'Numero di fatture attive degli ultimi 12 mesi',
		'NumberOfSupplierInvoices' => 'Numero di fatture fornitore degli ultimi 12 mesi',
		'NumberOfUnitsProposals' => 'Numero di unità sulle proposte degli ultimi 12 mesi',
		'NumberOfUnitsCustomerOrders' => 'Numero di unità sugli ordini dei clienti degli ultimi 12 mesi',
		'NumberOfUnitsCustomerInvoices' => 'Numero di unità sulle fatture attive degli ultimi 12 mesi',
		'NumberOfUnitsSupplierInvoices' => 'Numero di unità sulle fatture fornitore degli ultimi 12 mesi',
		'EMailTextInterventionValidated' => 'Intervento %s convalidato',
		'EMailTextInvoiceValidated' => 'Fattura %s convalidata',
		'EMailTextProposalValidated' => 'Proposta %s convalidata.',
		'EMailTextOrderValidated' => 'Ordine %s convalidato.',
		'EMailTextOrderApproved' => 'Ordine %s approvato',
		'EMailTextOrderApprovedBy' => 'Ordine %s approvato da %s',
		'EMailTextOrderRefused' => 'Ordine %s rifiutato',
		'EMailTextOrderRefusedBy' => 'Ordine %s rifiutato da %s',
		'ImportedWithSet' => 'Set dati importazione',
		'SpeedealingNotification' => 'Automatic notification',
		'ResizeDesc' => 'Ridimesiona con larghezza <b>o</b> altezza nuove. Il ridimensionamento è proporzionale, il rapporto tra le due dimenzioni verrà mantenuto.',
		'NewLength' => 'Nuovo larghezza',
		'NewHeight' => 'Nuova altezza',
		'NewSizeAfterCropping' => 'Nuovo formato dopo il ritaglio',
		'DefineNewAreaToPick' => 'Definisci una nuova area della foto da scegliere (clicca sull\'immagine e trascina fino a raggiungere l\'angolo opposto)',
		'CurrentInformationOnImage' => 'Strumento progettato per ridimensionare o tagliare un\'immagine. Informazioni sull\'immagine attualmente modificata',
		'ImageEditor' => 'Editor per le immagini',
		'YouReceiveMailBecauseOfNotification' => 'Ricevi messaggio perché il tuo indirizzo email è compreso nella lista dei riceventi per informazioni su eventi particolari in un software di %s %s.',
		'YouReceiveMailBecauseOfNotification2' => 'L\'evento è il seguente:',
		'ThisIsListOfModules' => 'Questa è una lista dei moduli preselezionati da questo profilo demo (in questa demo sono attivi solo i moduli più comuni). Per personalizzare la demo applica delle modifiche e clicca su &quot;Start&quot;.',
		'ClickHere' => 'Clicca qui',
		'UseAdvancedPerms' => 'Utilizza permessi avanzati nei moduli',
		'FileFormat' => 'Formato del file',
		'SelectAColor' => 'Scegli un colore',
		'AddFiles' => 'Aggiungi file',
		'StartUpload' => 'Carica',
		'CancelUpload' => 'Annulla caricamento',
		'FileIsTooBig' => 'File troppo grande',
		'PleaseBePatient' => 'Please be patient...',
		////////// Calendar common //////////
		'AddCalendarEntry' => 'Aggiungi evento al calendario %s',
		'NewCompanyToSpeedealing' => 'Company %s added into Speedealing',
		'ContractValidatedInSpeedealing' => 'Contract %s validated in Speedealing',
		'ContractCanceledInSpeedealing' => 'Contract %s canceled in Speedealing',
		'ContractClosedInSpeedealing' => 'Contract %s closed in Speedealing',
		'PropalClosedSignedInSpeedealing' => 'Proposal %s signed in Speedealing',
		'PropalClosedRefusedInSpeedealing' => 'Proposal %s refused in Speedealing',
		'PropalValidatedInSpeedealing' => 'Proposal %s validated in Speedealing',
		'InvoiceValidatedInSpeedealing' => 'Invoice %s validated in Speedealing',
		'InvoicePaidInSpeedealing' => 'Invoice %s changed to paid in Speedealing',
		'InvoiceCanceledInSpeedealing' => 'Invoice %s canceled in Speedealing',
		'PaymentDoneInSpeedealing' => 'Payment %s done in Speedealing',
		'CustomerPaymentDoneInSpeedealing' => 'Customer payment %s done in Speedealing',
		'SupplierPaymentDoneInSpeedealing' => 'Supplier payment %s done in Speedealing',
		'MemberValidatedInSpeedealing' => 'Member %s validated in Speedealing',
		'MemberResiliatedInSpeedealing' => 'Member %s resiliated in Speedealing',
		'MemberDeletedInSpeedealing' => 'Member %s deleted from Speedealing',
		'MemberSubscriptionAddedInSpeedealing' => 'Subscription for member %s added in Speedealing',
		'ShipmentValidatedInSpeedealing' => 'Shipment %s validated in Speedealing',
		////////// Export //////////
		'Export' => 'Esportazione',
		'ExportsArea' => 'Area esportazioni',
		'AvailableFormats' => 'Formati disponibili',
		'LibraryUsed' => 'Libreria usata',
		'LibraryVersion' => 'Versione libreria',
		'ExportableDatas' => 'Dati Esportabili',
		'NoExportableData' => 'Nessun dato esportabile (nessun modulo con dati esportabili attivo o autorizzazioni mancanti)',
		'ToExport' => 'Esportare',
		'NewExport' => 'Nuova esportazione',
		////////// External sites //////////
		'ExternalSites' => 'Siti esterni'
);
?>