<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$projects = array(
		'CHARSET' => 'UTF-8',
		'ActionsOnProject' => 'Azioni sul progetto',
		'Activities' => 'Compiti/attività',
		'Activity' => 'Attività',
		'ActivityOnProjectThisMonth' => 'Attività sul progetto questo mese',
		'ActivityOnProjectThisWeek' => 'Attività sul progetto questa settimana',
		'ActivityOnProjectThisYear' => 'Attività sul progetto nell\'anno in corso',
		'AddDuration' => 'Aggiungi durata',
		'AddProject' => 'Aggiungi progetto',
		'AddTask' => 'Aggiungi compito',
		'AffectedTo' => 'Interessato da',
		'AllProjects' => 'Tutti i progetti',
		'CantRemoveProject' => 'Questo progetto non può essere rimosso: altri oggetti (fatture, ordini, ecc...) vi fanno riferimento. Vedi scheda riferimenti.',
		'ChildOfTask' => 'Figlio del progetto/attività',
		'CloseAProject' => 'Chiudi progetto',
		'ConfirmCloseAProject' => 'Vuoi davvero chiudere il progetto?',
		'ConfirmDeleteAProject' => 'Vuoi davvero eliminare il progetto?',
		'ConfirmDeleteATask' => 'Vuoi davvero eliminare il compito?',
		'ConfirmDeleteATimeSpent' => 'Vuoi davvero cancellare questo tempo?',
		'ConfirmReOpenAProject' => 'Vuoi davvero riaprire il progetto?',
		'ConfirmValidateProject' => 'Vuoi davvero convalidare il progetto?',
		'DeleteAProject' => 'Elimina un progetto',
		'DeleteATask' => 'Cancella un compito',
		'DeleteATimeSpent' => 'Cancella il tempo trascorso',
		'DocumentModelBaleine' => 'Modello per il report di progetto completo (logo, etc..)',
		'DoNotShowMyTasksOnly' => 'Vedi anche compiti che non mi riguardano',
		'DurationEffective' => 'Durata effettiva',
		'ErrorTimeSpentIsEmpty' => 'Tempo trascorso vuoto',
		'IfNeedToUseOhterObjectKeepEmpty' => 'Se alcuni oggetti (fattura, ordine, ...), appartenente ad un altro di terze parti, deve essere collegato al progetto di creare, mantenere questo vuoto di avere il progetto di essere multi terzi.',
		'LabelTask' => 'Etichetta compito',
		'LastProjects' => 'Ultimi %s progetti',
		'LinkedToAnotherCompany' => 'Collegato a un soggetto terzo',
		'ListActionsAssociatedProject' => 'Elenco delle azioni associate al progetto',
		'ListContractAssociatedProject' => 'Elenco dei contratti associati al progetto',
		'ListFichinterAssociatedProject' => 'Elenco degli interventi legati al progetto',
		'ListInvoicesAssociatedProject' => 'Elenco delle fatture associate al progetto',
		'ListOrdersAssociatedProject' => 'Elenco degli ordini associati al progetto',
		'ListPredefinedInvoicesAssociatedProject' => 'Elenco delle fatture clienti predefinite associate al progetto',
		'ListProposalsAssociatedProject' => 'Elenco delle proposte commerciali associate al progetto',
		'ListSupplierInvoicesAssociatedProject' => 'Elenco delle fatture fornitori associate al progetto',
		'ListSupplierOrdersAssociatedProject' => 'Elenco degli ordini fornitori associati al progetto',
		'ListTripAssociatedProject' => 'Elenco dei viaggi e delle spese associate al progetto',
		'MyActivities' => 'I miei compiti / attività',
		'MyActivity' => 'La mia attività',
		'MyProjectsDesc' => 'Questa visione è limitata a progetti che state per un contatto (qualunque sia il tipo).',
		'Myprojects' => 'I miei progetti',
		'MyProjects' => 'I miei progetti',
		'MyTasksDesc' => 'Questa visione è limitata a progetti o attività che sono per un contatto (qualunque sia il tipo).',
		'MyTasks' => 'Le mie attività',
		'MyTimeSpent' => 'Il mio tempo trascorso',
		'NbOfProjects' => 'Numero dei progetti',
		'NbOpenTasks' => 'Numeri attività aperte',
		'NewProject' => 'Nuovo progetto',
		'NewTask' => 'Nuova attività',
		'NewTimeSpent' => 'Nuovo tempo trascorso',
		'NoProject' => 'Nessun progetto definito',
		'NoTasks' => 'Le funzioni di questo progetto',
		'NotOwnerOfProject' => 'Non proprietario di questo progetto privato',
		'OfficerProject' => 'Responsabile del progetto',
		'PrivateProject' => 'Contatti di progetto',
		'Progress' => 'Progressi',
		'ProjectContact' => 'Progetto contatti',
		'Project' => 'Progetto',
		'ProjectsArea' => 'Sezione progetti',
		'ProjectsDedicatedToThisThirdParty' => 'I progetti dedicati a questo terzo',
		'ProjectsDesc' => 'Questo punto di vista presenta tutti i progetti (le autorizzazioni utente si concede l\'autorizzazione per visualizzare tutto).',
		'ProjectsList' => 'Elenco dei progetti',
		'Projects' => 'Progetti',
		'ProjectsPublicDesc' => 'Questo punto di vista presenta tutti i progetti sono autorizzati a leggere.',
		'RefTask' => 'Rif. attività',
		'ReOpenAProject' => 'Apri progetto',
		'SetProject' => 'Imposta progetto',
		'SharedProject' => 'Progetto condiviso',
		'ShowMyTasksOnly' => 'Visualizza solo compiti sono affetto da',
		'ShowProject' => 'Visualizza progetto',
		'Task' => 'Attività',
		'TaskIsNotAffectedToYou' => 'Compito non è assegnato a voi',
		'TaskRessourceLinks' => 'Risorse',
		'Tasks' => 'Attività',
		'TasksDesc' => 'Questo punto di vista presenta tutti i progetti e le attività (le autorizzazioni utente si concede l\'autorizzazione per visualizzare tutto).',
		'TasksPublicDesc' => 'Questo punto di vista presenta tutti i progetti e le attività sono permesso di leggere.',
		'ThisWillAlsoRemoveTasks' => 'Questa azione anche eliminare tutte le attività del progetto (compiti <b>%s</b> al momento) e tutti gli ingressi del tempo trascorso.',
		'TimeSpent' => 'Tempo trascorso',
		'TimesSpent' => 'Il tempo trascorso',
		'Time' => 'Tempo',
		'TypeContact_project_external_CONTRIBUTOR' => 'Contributore',
		'TypeContact_project_external_PROJECTLEADER' => 'Capo progetto',
		'TypeContact_project_internal_CONTRIBUTOR' => 'Contributore',
		'TypeContact_project_internal_PROJECTLEADER' => 'Capo progetto',
		'TypeContact_project_task_external_CONTRIBUTOR' => 'Contributore',
		'TypeContact_project_task_external_TASKEXECUTIVE' => 'Compito dell\'esecutivo',
		'TypeContact_project_task_internal_CONTRIBUTOR' => 'Contributore',
		'TypeContact_project_task_internal_TASKEXECUTIVE' => 'Compito dell\'esecutivo',
		'ValidateProject' => 'Valida projet',
		'YouAreNotContactOfProject' => 'Lei non è un contatto di questo progetto privato',
);
?>