<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$propal = array(
		'CHARSET' => 'UTF-8',
		'Proposals' => 'Preventivi/Proposte commerciali',
		'Proposal' => 'Preventivo/Proposta commerciale',
		'ProposalsDraft' => 'Bozza di proposte commerciali',
		'ProposalDraft' => 'Bozza di proposta commerciale',
		'ProposalsOpened' => 'Proposte commerciali aperte',
		'Prop' => 'Preventivi/Prop. commerciali',
		'CommercialProposal' => 'Preventivo/Proposta commerciale',
		'CommercialProposals' => 'Preventivi/Proposte commerciali',
		'NewProp' => 'Nuova proposta commerciale',
		'NewProposal' => 'Nuova proposta commerciale',
		'NewPropal' => 'Nuova proposta',
		'Prospect' => 'Potenziale cliente',
		'ProspectList' => 'Lista Potenziali clienti',
		'DeleteProp' => 'Elimina proposta commerciale',
		'ValidateProp' => 'Convalida proposta commerciale',
		'AddProp' => 'Aggiungi proposta',
		'ConfirmDeleteProp' => 'Sei sicuro di voler cancellare questa proposta commerciale?',
		'ConfirmValidateProp' => 'Sei sicuro di voler convalidare questa proposta commerciale?',
		'LastPropals' => 'Ultimo %s proposte',
		'LastClosedProposals' => 'Ultimo %s proposte chiuse',
		'AllPropals' => 'Tutte le proposte',
		'LastProposals' => 'Ultimo proposte',
		'SearchAProposal' => 'Cerca una proposta',
		'ProposalsStatistics' => 'Statistiche Proposte commerciali',
		'NumberOfProposalsByMonth' => 'Numero per mese',
		'NbOfProposals' => 'Numero di proposte commerciali',
		'ShowPropal' => 'Visualizza proposta',
		'PropalsDraft' => 'Bozze',
		'PropalsOpened' => 'Aperte',
		'PropalsNotBilled' => 'Chiuse non fatturate',
		'PropalStatusDraft' => 'Bozza (deve essere convalidata)',
		'PropalStatusValidated' => 'Convalidato (proposta è aperta)',
		'PropalStatusOpened' => 'Convalidato (proposta è aperta)',
		'PropalStatusClosed' => 'Chiuso',
		'PropalStatusSigned' => 'Firmata (da fatturare)',
		'PropalStatusNotSigned' => 'Non firmata (chiuso)',
		'PropalStatusBilled' => 'Fatturata',
		'PropalStatusDraftShort' => 'Bozza',
		'PropalStatusValidatedShort' => 'Convalidato',
		'PropalStatusOpenedShort' => 'Aperta',
		'PropalStatusClosedShort' => 'Chiusa',
		'PropalStatusSignedShort' => 'Firmata',
		'PropalStatusNotSignedShort' => 'Non firmata',
		'PropalStatusBilledShort' => 'Fatturata',
		'PropalsToClose' => 'Proposte commerciali da chiudere',
		'PropalsToBill' => 'Proposte commerciali firmate da fatturare',
		'ListOfProposals' => 'Elenco delle proposte commerciali',
		'ActionsOnPropal' => 'Azioni su proposta',
		'NoOpenedPropals' => 'Nessuna proposta commerciale aperta',
		'NoOtherOpenedPropals' => 'Nessun altro ha aperto proposte commerciali',
		'RefProposal' => 'Rif. Proposta commerciale',
		'SendPropalByMail' => 'Invia proposta commerciale via e-mail',
		'FileNotUploaded' => 'Il file non è stato caricato',
		'FileUploaded' => 'Il file è stato caricato con successo',
		'AssociatedDocuments' => 'Documenti associati con la proposta:',
		'ErrorCantOpenDir' => 'Impossibile aprire la directory',
		'DateEndPropal' => 'Data di fine validità',
		'DateEndPropalShort' => 'Data fine',
		'ValidityDuration' => 'Durata validità',
		'CloseAs' => 'Chiudere con lo status',
		'ClassifyBilled' => 'Classificare  fatturata',
		'BuildBill' => 'Crea fattura',
		'RelatedBill' => 'Fattura correlata',
		'RelatedBills' => 'Fatture correlate',
		'ErrorPropalNotFound' => 'Proposta %s non trovata',
		'Estimate' => 'Stima:',
		'EstimateShort' => 'Stima',
		'OtherPropals' => 'Altre proposte',
		'CopyPropalFrom' => 'Crea proposta commerciale da copia esistente',
		'CreateEmptyPropal' => 'Crea proposta commerciale vuota o dalla lista dei prodotti / servizi',
		'DefaultProposalDurationValidity' => 'Durata di validità predefinita per proposta commerciale (in giorni)',
		'UseCustomerContactAsPropalRecipientIfExist' => 'Utilizzare l\'indirizzo del contatto cliente se definito al posto dell\'indirizzo del destinatario',
		'AmountOfProposalsByMonthHT' => 'Importo per mese (al netto delle imposte)',
		'ClonePropal' => 'Clona proposta commerciale',
		'ConfirmClonePropal' => 'Sei sicuro di voler clonare la presente proposta commerciale <b>%s?</b>',
		'ProposalShort' => 'Proposta',
		'LastModifiedProposals' => 'Ultimo %s proposte modificate',
		'DatePropal' => 'Data della proposta',
		'ProposalsAndProposalsLines' => 'Proposta commerciale e le linee',
		'ProposalLine' => 'Linea della proposta',
		'TypeContact_propal_internal_SALESREPFOLL' => 'Responsabile proposta vendita',
		'TypeContact_propal_external_BILLING' => 'Contatto proposta fatturazione',
		'TypeContact_propal_external_CUSTOMER' => 'Contatto proposta clienti',
		// Documents models
		'DocModelAzurDescription' => 'Modello di proposta completa (logo...)',
		'DocModelJauneDescription' => 'Modello di proposta Jaune',
		'DocModelRoigDescription' => 'Un modello di proposta completa con la tassa RE spagnolo e IRPF',
		'ProposalCard' => 'Proposta di carta',
		'AvailabilityPeriod' => 'Disponibilità ritardo',
		'SetAvailability' => 'Imposta la disponibilità di ritardo',
		'AfterOrder' => 'dopo la fine',
		'AvailabilityTypeAV_NOW' => 'Immediato',
		'AvailabilityTypeAV_1W' => '1 settimana',
		'AvailabilityTypeAV_2W' => '2 settimane',
		'AvailabilityTypeAV_3W' => '3 settimane',
		'AvailabilityTypeAV_1M' => '1 mese',
		'ConfirmReOpenProp' => 'Sei sicuro di voler aprire di nuovo le <b>%s</b> proposta commerciale?',
);
?>