<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Scheda Magazzino',
		'Warehouse' => 'Magazzino',
		'Warehouses' => 'Warehouses',
		'NewWarehouse' => 'Nuovo magazzino/deposito',
		'WarehouseEdit' => 'Modifica magazzino',
		'MenuNewWarehouse' => 'Nuovo Magazzino',
		'WarehouseOpened' => 'Magazzino aperto',
		'WarehouseClosed' => 'Magazzino chiuso',
		'WarehouseSource' => 'Magazzino di origine',
		'WarehouseSourceNotDefined' => 'No warehouse defined,',
		'AddOne' => 'Add one',
		'WarehouseTarget' => 'Magazzino di destinazione',
		'ValidateSending' => 'Convalida spedizione',
		'CancelSending' => 'Annulla spedizione',
		'DeleteSending' => 'Elimina spedizione',
		'Stock' => 'Scorta',
		'Stocks' => 'Scorte',
		'Movement' => 'Movimento',
		'Movements' => 'Movimenti',
		'ErrorWarehouseRefRequired' => 'Riferimento magazzino mancante',
		'ErrorWarehouseLabelRequired' => 'Etichetta del magazzino mancante',
		'CorrectStock' => 'Scorte di magazzino corrette',
		'ListOfWarehouses' => 'Elenco magazzini',
		'ListOfStockMovements' => 'Elenco movimenti delle scorte',
		'StocksArea' => 'Area scorte di magazzino',
		'Location' => 'Ubicazione',
		'LocationSummary' => 'Ubicazione abbreviata',
		'NumberOfProducts' => 'Numero totale prodotti',
		'LastMovement' => 'Ultimo movimento',
		'LastMovements' => 'Ultimi movimenti',
		'Units' => 'Unità',
		'Unit' => 'Unità',
		'StockCorrection' => 'Correzione scorte',
		'StockMovement' => 'Movimento scorta',
		'StockMovements' => 'Movimenti scorte',
		'NumberOfUnit' => 'Numero di unità',
		'UnitPurchaseValue' => 'Unit purchase price',
		'TotalStock' => 'Totale a magazzino',
		'StockTooLow' => 'Scorte insufficienti',
		'StockLowerThanLimit' => 'Stock lower than alert limit',
		'EnhancedValue' => 'Incremento valore',
		'PMPValue' => 'Media ponderata prezzi',
		'PMPValueShort' => 'MPP',
		'EnhancedValueOfWarehouses' => 'Incremento valore dei magazzini',
		'UserWarehouseAutoCreate' => 'Creare automaticamente un magazzino alla creazione di un utente',
		'QtyDispatched' => 'Quantità spedita',
		'OrderDispatch' => 'Spedizione dell\'ordine',
		'RuleForStockManagementDecrease' => 'Regola per la gestione della diminuzione delle scorte',
		'RuleForStockManagementIncrease' => 'Regola per la gestione dell\'aumento delle scorte',
		'DeStockOnBill' => 'Riduci scorte effettive all\'emissione della fattura/nota di credito',
		'DeStockOnValidateOrder' => 'Riduci scorte effettive alla convalida dell\'ordine',
		'DeStockOnShipment' => 'Riduci scorte effettive alla spedizione (Raccomandato)',
		'ReStockOnBill' => 'Incrementa scorte effettive alla fattura/nota di credito',
		'ReStockOnValidateOrder' => 'Aumenta scorte effettive alla convalida dell\'ordine',
		'ReStockOnDispatchOrder' => 'Incrementa scorte effettive alla consegna manuale in magazzino, dopo il ricevimento dell\'ordine fornitore',
		'OrderStatusNotReadyToDispatch' => 'Lo stato dell\'ordine non ne consente la spedizione dei prodotti a magazzino.',
		'StockDiffPhysicTeoric' => 'Motivo della differenza tra scorta effettiva e teorica',
		'NoPredefinedProductToDispatch' => 'Per l\'oggetto non ci sono prodotti impostati. Quindi non è necessario alterare la scorta.',
		'DispatchVerb' => 'Spedizione',
		'StockLimitShort' => 'Limite',
		'StockLimit' => 'Limite minimo scorta per segnalazioni',
		'PhysicalStock' => 'Scorta fisica',
		'RealStock' => 'Scorta reale',
		'TheoreticalStock' => 'Scorta teorica',
		'VirtualStock' => 'Scorta virtuale',
		'MininumStock' => 'Scorta minima',
		'StockUp' => 'Scorta massima',
		'MininumStockShort' => 'Scorta min',
		'StockUpShort' => 'Scorta max',
		'IdWarehouse' => 'Id magazzino',
		'DescWareHouse' => 'Descrizione magazzino',
		'LieuWareHouse' => 'Ubicazione magazzino',
		'WarehousesAndProducts' => 'Magazzini e prodotti',
		'AverageUnitPricePMPShort' => 'Media prezzi scorte',
		'AverageUnitPricePMP' => 'Media dei prezzi delle scorte',
		'SellPriceMin' => 'Prezzo di vendita unitario',
		'EstimatedStockValueSellShort' => 'Valore vendita',
		'EstimatedStockValueSell' => 'Valore di vendita',
		'EstimatedStockValueShort' => 'Valore stimato scorte',
		'EstimatedStockValue' => 'Valore stimato delle scorte',
		'DeleteAWarehouse' => 'Elimina un magazzino',
		'ConfirmDeleteWarehouse' => 'Sei sicuro di voler eliminare il magazzino <b>%s</b>?',
		'PersonalStock' => 'Scorta personale %s',
		'ThisWarehouseIsPersonalStock' => 'Questo magazzino rappresenta la riserva personale di %s %s',
		'SelectWarehouseForStockDecrease' => 'Scegli magazzino da utilizzare per la riduzione delle scorte',
		'SelectWarehouseForStockIncrease' => 'Scegli magazzino da utilizzare per l\'aumento delle scorte',
		'LastWaitingSupplierOrders' => 'Orders waiting for receptions'
);
?>