<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$withdrawals = array(
		'CHARSET' => 'UTF-8',
		'StandingOrdersArea' => 'Area ordini permanenti',
		'CustomersStandingOrdersArea' => 'Area ordini permanenti clienti',
		'StandingOrders' => 'Ordini permanenti',
		'StandingOrder' => 'Ordine permanente',
		'NewStandingOrder' => 'Nuovo ordine permanente',
		'StandingOrderToProcess' => 'Da processare',
		'StandingOrderProcessed' => 'Processato',
		'Withdrawals' => 'Bonifici',
		'Withdrawal' => 'Bonifico',
		'WithdrawalsReceipts' => 'Ricevute domiciliazioni',
		'WithdrawalReceipt' => 'Ricevuta domiciliazione',
		'WithdrawalReceiptShort' => 'Ricevuta',
		'LastWithdrawalReceipts' => 'Ultime %s ricevute di domiciliazione',
		'WithdrawedBills' => 'Fatture delle domiciliazioni',
		'WithdrawalsLines' => 'Righe dei domiciliazioni',
		'RequestStandingOrderToTreat' => 'Richiesta ordini permanenti da trattare',
		'RequestStandingOrderTreated' => 'Richiesta ordini permanenti trattati',
		'CustomersStandingOrders' => 'Ordini permanenti clienti',
		'CustomerStandingOrder' => 'Ordine permanente cliente',
		'NbOfInvoiceToWithdraw' => 'Numero di fattura da prelevare',
		'NbOfInvoiceToWithdrawWithInfo' => 'Numero di fattura da prelevare per i clienti con informazioni bancarie definite',
		'InvoiceWaitingWithdraw' => 'Fattura in attesa di domiciliazione',
		'AmountToWithdraw' => 'Importo da prelevare',
		'WithdrawsRefused' => 'Bonifico rifiutato',
		'NoInvoiceToWithdraw' => 'Non ci sono fatture attive in attesa con modalità di pagamento "domiciliazione".',
		'ResponsibleUser' => 'Utente responsabile',
		'WithdrawalsSetup' => 'Impostazione domiciliazioni',
		'WithdrawStatistics' => 'Statistiche domiciliazioni',
		'WithdrawRejectStatistics' => 'Statistiche domiciliazioni respinti',
		'LastWithdrawalReceipt' => 'Last %s withdrawing receipts',
		'MakeWithdrawRequest' => 'Effettuare una richiesta di domiciliazione',
		'ThirdPartyBankCode' => 'Codice bancario di soggetti terzi',
		'ThirdPartyDeskCode' => 'Codice ufficio di soggetti terzi',
		'NoInvoiceCouldBeWithdrawed' => 'Non ci sono fatture riscuotibili con domiciliazione. Verificare che sulle fatture sia riportato il corretto codice IBAN.',
		'ClassCredited' => 'Classifica come accreditata',
		'ClassCreditedConfirm' => 'Vuoi davvero classificare questa ricevuta di domiciliazione come accreditata sul vostro conto bancario?',
		'TransData' => 'Data di trasmissione',
		'TransMetod' => 'Metodo di trasmissione',
		'Send' => 'Invia',
		'Lines' => 'Righe',
		'StandingOrderReject' => 'Invia rifiuto',
		'InvoiceRefused' => 'Fattura rifiutata',
		'WithdrawalRefused' => 'Bonifici rifiutati',
		'WithdrawalRefusedConfirm' => 'Vuoi davvero inserire un rifiuto per la società?',
		'RefusedData' => 'Data del rifiuto',
		'RefusedReason' => 'Motivo del rifiuto',
		'RefusedInvoicing' => 'Fatturazione rifiutata',
		'NoInvoiceRefused' => 'Non ricaricare il rifiuto',
		'InvoiceRefused' => 'Fattura rifiutata',
		'Status' => 'Stato',
		'StatusUnknown' => 'Sconosciuto',
		'StatusWaiting' => 'In attesa',
		'StatusTrans' => 'Trasmesso',
		'StatusCredited' => 'Accreditato',
		'StatusRefused' => 'Rifiutato',
		'StatusMotif0' => 'Imprecisato',
		'StatusMotif1' => 'Disponibilità insufficiente',
		'StatusMotif2' => 'Bonifico contestato',
		'StatusMotif3' => 'Nessun ordine',
		'StatusMotif4' => 'Ordine del cliente',
		'StatusMotif5' => 'IBAN non valido',
		'StatusMotif6' => 'Conto in rosso',
		'StatusMotif7' => 'Decisione giudiziaria',
		'StatusMotif8' => 'Altri motivi',
		'CreateAll' => 'Ritira tutto',
		'CreateGuichet' => 'Solo ufficio',
		'CreateBanque' => 'Solo banca',
		'OrderWaiting' => 'In attesa di esecuzione',
		'NotifyTransmision' => 'Trasmissione domiciliazione',
		'NotifyEmision' => 'Emissione domiciliazione',
		'NotifyCredit' => 'Credito',
		'NumeroNationalEmetter' => 'Numero nazionale dell\'inviante',
		'PleaseSelectCustomerBankBANToWithdraw' => 'Selezionare le informazioni del conto bancario per bonificare',
		'WithBankUsingRIB' => 'Per i conti correnti bancari che utilizzano RIB',
		'WithBankUsingBANBIC' => 'Per conti bancari che utilizzano IBAN/BIC/SWIFT',
		'BankToReceiveWithdraw' => 'Conto corrente bancario per il domiciliazione',
		'CreditDate' => 'Data di accredito',
		'WithdrawalFileNotCapable' => 'Impossibile generare file di ricevuta per il vostro paese',
		'ShowWithdraw' => 'Mostra domiciliazione',
		'IfInvoiceNeedOnWithdrawPaymentWontBeClosed' => 'Tuttavia, se per la fattura ci sono ancora pagamenti da elaborare, non sarà impostata come pagata per consentire prima la gestione dei domiciliazioni.',
		'DoStandingOrdersBeforePayments' => 'Questa scheda consente di richiedere un ordine permanente. Una volta finito, è possibile inserire il pagamento per chiudere la fattura.',
		////// Notifications
		'InfoCreditSubject' => 'Il pagamento dell\'ordine permanente %s da parte della banca',
		'InfoCreditMessage' => 'La banca ha pagato l\'ordine permanente %s.<br/>Dati di pagamento: %s',
		'InfoTransSubject' => 'Trasmissione dell\'ordine permanente %s alla banca',
		'InfoTransMessage' => 'L\'ordine permanente %s è stato trasmesso alla banca da %s %s.<br/><br/>',
		'InfoTransData' => 'Importo: %s <br> Metodo: %s <br> Data: %s',
		'InfoFoot' => 'Questo è un messaggio automatico inviato da Speedealing',
		'InfoRejectSubject' => 'Ordine permanente rifiutato',
		'InfoRejectMessage' => '<br/><br/>L&#39;ordine permanente %s per la fattura relativa alla società %s , con un importo di %s è stato rifiutato dalla banca.<br/><br/>-<br/>% $',
		'ModeWarning' => 'Non è stata impostata la modalità reale, ci fermiamo dopo questa simulazione'
);
?>