<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$banks = array(
		'CHARSET' => 'UTF-8',
		'Bank' => 'Bank',
		'Banks' => 'Banken',
		'MenuBankCash' => 'Finanzen',
		'MenuSetupBank' => 'Finanzkonten einrichten',
		'BankName' => 'Name der Bank',
		'FinancialAccount' => 'Finanzkonto',
		'FinancialAccounts' => 'Finanzkonten',
		'BankAccount' => 'Finanzkontenübersicht',
		'BankAccounts' => 'Kontenübersicht',
		'AccountRef' => 'Konto-Referenz',
		'AccountLabel' => 'Kontobezeichnung',
		'CashAccount' => 'Kassa',
		'CashAccounts' => 'Kassen',
		'MainAccount' => 'Hauptkonto',
		'CurrentAccount' => 'Girokonto',
		'CurrentAccounts' => 'Girokonten',
		'SavingAccount' => 'Sparkonto',
		'SavingAccounts' => 'Sparkonten',
		'ErrorBankLabelAlreadyExists' => 'Kontenbezeichnung existiert bereits',
		'BankBalance' => 'Kontostand',
		'BalanceMinimalAllowed' => 'Mindestbestand',
		'BalanceMinimalDesired' => 'Gewünschter Mindestbestand',
		'InitialBankBalance' => 'Eröffnungsbestand',
		'EndBankBalance' => 'Endbestand',
		'CurrentBalance' => 'Aktueller Kontostand',
		'FutureBalance' => 'Zukünftiger Kontostand',
		'ShowAllTimeBalance' => 'Zeige Kontostand seit Eröffnung',
		'Reconciliation' => 'Zahlungsabgleich',
		'RIB' => 'Kontonummer',
		'IBAN' => 'IBAN',
		'BIC' => 'BIC / SWIFT Code',
		'StandingOrders' => 'Daueraufträge',
		'StandingOrder' => 'Dauerauftrag',
		'Withdrawals' => 'Entnahmen',
		'Withdrawal' => 'Entnahme',
		'AccountStatement' => 'Kontoauszug',
		'AccountStatementShort' => 'Auszug',
		'AccountStatements' => 'Kontoauszüge',
		'LastAccountStatements' => 'Letzte Kontoauszüge',
		'Rapprochement' => 'Zahlungsabgleich',
		'IOMonthlyReporting' => 'Monatsbericht',
		'BankAccountDomiciliation' => 'Konto-Adresse',
		'BankAccountCountry' => 'Bankkonto Land',
		'BankAccountOwner' => 'Kontoinhaber',
		'BankAccountOwnerAddress' => 'Kontoinhaber-Adresse',
		'RIBControlError' => 'Prüfung auf Vollständigkeit fehlgeschlagen. Informationen zu Bankkonto sind nicht vollständig oder falsch (Land überprüfen, Zahlen und IBAN).',
		'CreateAccount' => 'Konto anlegen',
		'NewAccount' => 'Neues Konto',
		'NewBankAccount' => 'Neues Bankkonto',
		'NewFinancialAccount' => 'Neues Finanzkonto',
		'MenuNewFinancialAccount' => 'Neues Finanzkonto',
		'NewCurrentAccount' => 'Neues Girokonto',
		'NewSavingAccount' => 'Neues Sparkonto',
		'NewCashAccount' => 'Neue Kassa',
		'EditFinancialAccount' => 'Konto bearbeiten',
		'AccountSetup' => 'Finanzielle Konten einrichten',
		'SearchBankMovement' => 'Suche Bankbewegung',
		'Debts' => 'Schulden',
		'LabelBankCashAccount' => 'Bank- oder Kassabezeichnung',
		'AccountType' => 'Kontoart',
		'BankType0' => 'Sparkonto',
		'BankType1' => 'Girokonto',
		'BankType2' => 'Kassa',
		'IfBankAccount' => 'Falls Bankkonto',
		'AccountsArea' => 'Finanzkonten',
		'AccountCard' => 'Konto-Karte',
		'DeleteAccount' => 'Konto löschen',
		'ConfirmDeleteAccount' => 'Möchten Sie dieses Konto wirklich löschen?',
		'Account' => 'Konto',
		'ByCategories' => 'Nach Kategorien',
		'ByRubriques' => 'Nach Kategorien',
		'BankTransactionByCategories' => 'Bank-Transaktionen nach Kategorien',
		'BankTransactionForCategory' => 'Bank-Transaktionen für die Kategorie <b>%s</b>',
		'RemoveFromRubrique' => 'Aus Kategorie entfernen',
		'RemoveFromRubriqueConfirm' => 'Möchten Sie die Kategoriezuweisung wirklich entfernen?',
		'ListBankTransactions' => 'Liste der Transaktionen',
		'IdTransaction' => 'Transaktions-ID',
		'BankTransactions' => 'Bank-Transaktionen',
		'SearchTransaction' => 'Suche Transaktion',
		'ListTransactions' => 'Transaktionsliste',
		'ListTransactionsByCategory' => 'Transaktionen/Kategorie',
		'TransactionsToConciliate' => 'Auszugleichende Transaktionen',
		'Conciliable' => 'Ausgleichsfähig',
		'Conciliate' => 'Ausgleichen',
		'Conciliation' => 'Ausgleich',
		'ConciliationForAccount' => 'Dieses Konto ausgleichen',
		'IncludeClosedAccount' => 'Geschlossene konten miteinbeziehen',
		'OnlyOpenedAccount' => 'Nur geöffnete Konten',
		'AccountToCredit' => 'Konto für Gutschrift',
		'AccountToDebit' => 'Zu belastendes Konto',
		'DisableConciliation' => 'Zahlungsausgleich für dieses Konto deaktivieren',
		'ConciliationDisabled' => 'Zahlungsausgleich deaktiviert',
		'StatusAccountOpened' => 'Geöffnet',
		'StatusAccountClosed' => 'Geschlossen',
		'AccountIdShort' => 'Nummer',
		'EditBankRecord' => 'Eintrag bearbeiten',
		'LineRecord' => 'Transaktion',
		'AddBankRecord' => 'Erstelle Transaktion',
		'AddBankRecordLong' => 'Transaktion manuell hinzufügen',
		'ConciliatedBy' => 'Ausgeglichen durch',
		'DateConciliating' => 'Ausgleichsdatum',
		'BankLineConciliated' => 'Transaktion ausgeglichen',
		'CustomerInvoicePayment' => 'Kundenzahlung',
		'SupplierInvoicePayment' => 'Lieferantenzahlung',
		'WithdrawalPayment' => 'Widerrufsrecht Zahlung',
		'SocialContributionPayment' => 'Sozialbeitragszahlung',
		'FinancialAccountJournal' => 'Finanzkonto-Journal',
		'BankTransfer' => 'Kontentransfer',
		'BankTransfers' => 'Kontentransfer',
		'TransferDesc' => 'Transfer zwischen Konten. Gebucht werden beide Sätze (eine Belastung im Haben-Konto und eine Gutschrift im Soll-Konto mit gleichem Betrag, Bezeichner und Datum)',
		'TransferFrom' => 'Von',
		'TransferTo' => 'An',
		'TransferFromToDone' => 'Eine Überweisung <b>von %s nach %s iHv %s %s</b> wurde verbucht.',
		'CheckTransmitter' => 'Überbringer',
		'ValidateCheckReceipt' => 'Scheck annehmen?',
		'ConfirmValidateCheckReceipt' => 'Scheck wirklich annehmen? Eine Änderung ist anschliessend nicht mehr möglich.',
		'DeleteCheckReceipt' => 'Scheck löschen',
		'ConfirmDeleteCheckReceipt' => 'Möchten Sie diesen Scheck wirklich löschen?',
		'BankChecks' => 'Bankschecks',
		'BankChecksToReceipt' => 'Schecks zur Einlösung',
		'ShowCheckReceipt' => 'Zeige überprüfen Einzahlungsbeleg',
		'NumberOfCheques' => 'Anzahl der Schecks',
		'DeleteTransaction' => 'Transaktion löschen',
		'ConfirmDeleteTransaction' => 'Möchten Sie diese Transaktion wirklich löschen?',
		'ThisWillAlsoDeleteBankRecord' => 'Dies löscht auch erstellte Bankbewegungen',
		'BankMovements' => 'Bankbewegungen',
		'CashBudget' => 'Bargeldbestand',
		'PlannedTransactions' => 'Geplante Transaktionen',
		'Graph' => 'Grafik',
		'ExportDataset_banque_1' => 'Bankbewegungen und Kontoauszug',
		'TransactionOnTheOtherAccount' => 'Transaktion auf dem anderem Konto',
		'TransactionWithOtherAccount' => 'Kontoübertrag',
		'PaymentNumberUpdateSucceeded' => 'Zahlungsnummer erfolgreich aktualisiert',
		'PaymentNumberUpdateFailed' => 'Zahlungsnummer konnte nicht aktualisiert werden',
		'PaymentDateUpdateSucceeded' => 'Zahlungsdatum erfolgreich aktualisiert',
		'PaymentDateUpdateFailed' => 'Zahlungsdatum konnte nicht aktualisiert werden',
		'Transactions' => 'Transactions',
		'BankTransactionLine' => 'Banküberweisung',
		'AllAccounts' => 'Alle Finanzkonten',
		'BackToAccount' => 'Zurück zum Konto',
		'ShowAllAccounts' => 'Alle Finanzkonten',
		'FutureTransaction' => 'Transaction in futur. Kein Weg zu versöhnen.',
		'SelectChequeTransactionAndGenerate' => 'Select / Filter prüft, in die Scheckeinreichung Erhalt gehören und klicken Sie auf &quot;Erstellen&quot;.',
		'InputReceiptNumber' => 'Choose the bank statement related with the conciliation. Use a sortable numeric value (such as, YYYYMM)',
		'EventualyAddCategory' => 'Eventually, specify a category in which to classify the records',
		'ToConciliate' => 'To conciliate?',
		'ThenCheckLinesAndConciliate' => 'Then, check the lines present in the bank statement and click'
);
?>