<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Kategorie',
		'Categories' => 'Kategorien',
		'Rubrique' => 'Kategorie',
		'Rubriques' => 'Kategorien',
		'categories' => 'Kategorien',
		'TheCategorie' => 'Die Kategorie',
		'NoCategoryYet' => 'No category of this type created',
		'In' => 'In',
		'AddIn' => 'Einfügen in',
		'modify' => 'Ändern',
		'Classify' => 'Einordnen',
		'CategoriesArea' => 'Kategorien',
		'ProductsCategoriesArea' => 'Produktkategorien',
		'SuppliersCategoriesArea' => 'Lieferantenkategorien',
		'CustomersCategoriesArea' => 'Kundenkategorien',
		'ThirdPartyCategoriesArea' => 'Organisationskategorien',
		'MembersCategoriesArea' => 'Kategoriemitglieder-Bereich',
		'MainCats' => 'Hauptkategorien',
		'SubCats' => 'Unterkategorien',
		'CatStatistics' => 'Statistik',
		'CatList' => 'Kategorieliste',
		'AllCats' => 'Alle Kategorien',
		'ViewCat' => 'Kategorie',
		'NewCat' => 'Kategorie hinzufügen',
		'NewCategory' => 'Neue Kategorie',
		'ModifCat' => 'Kategorie bearbeiten',
		'CatCreated' => 'Kategorie erstellt',
		'CreateCat' => 'Kategorie erstellen',
		'CreateThisCat' => 'Kategorie anlegen',
		'ValidateFields' => 'Überprüfen Sie die Felder',
		'NoSubCat' => 'Keine Unterkategorie',
		'SubCatOf' => 'Unterkategorie von',
		'FoundCats' => 'Kategorien gefunden',
		'FoundCatsForName' => 'Treffer für den Namen:',
		'FoundSubCatsIn' => 'Kategorie besitzt Unterkategorien',
		'ErrSameCatSelected' => 'Sie haben die gleiche Kategorie mehrmals ausgewählt',
		'ErrForgotCat' => 'Sie haben vergessen eine Kategorie zu wählen',
		'ErrForgotField' => 'Sie haben ein oder mehrere Felder nicht ausgefüllt',
		'ErrCatAlreadyExists' => 'Dieser Name wird bereits verwendet',
		'AddProductToCat' => 'Dieses Produkt einer Kategorie zuweisen?',
		'ImpossibleAddCat' => 'Das Hinzufügen dieser Kategorie ist nicht möglich',
		'ImpossibleAssociateCategory' => 'Kann die Kategorie nicht zuweisen zu',
		'WasAddedSuccessfully' => '<b> %s</b> wurde erfolgreich hinzugefügt.',
		'ObjectAlreadyLinkedToCategory' => 'Element ist bereits mit dieser Kategorie verknüpft.',
		'CategorySuccessfullyCreated' => 'Die Kategorie %s wurde erfolgreich hinzugefügt.',
		'ProductIsInCategories' => 'Produkt gehört zu folgenden Kategorien',
		'SupplierIsInCategories' => 'Dieser Lieferant ist folgenden Kategorien zugewiesen',
		'CompanyIsInCustomersCategories' => 'Diese Organisation ist folgenden Lead-/Kundenkategorien zugewiesen',
		'CompanyIsInSuppliersCategories' => 'Diese Organisation ist folgenden Lieferantenkategorien zugewiesen',
		'MemberIsInCategories' => 'Dieses Mitglied ist Mitglied folgender Kategorien',
		'ProductHasNoCategory' => 'Dieses Produkt / Dienstleistung ist nicht in allen Kategorien',
		'SupplierHasNoCategory' => 'Dieser Lieferant ist keiner Kategorie zugewiesen',
		'CompanyHasNoCategory' => 'Diese Organisation ist keiner Kategorie zugewiesen',
		'MemberHasNoCategory' => 'Dieses Mitglied ist in keiner Kategorie',
		'ClassifyInCategory' => 'Folgender Kategorie zuweisen',
		'NoneCategory' => 'Keine',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Gleichnamige Kategorie auf diesem Level gefunden',
		'ReturnInProduct' => 'Zurück zur Produktkarte',
		'ReturnInSupplier' => 'Zurück zur Anbieterkarte',
		'ReturnInCompany' => 'Zurück zur Kunden-/Lead-Karte',
		'ContentsVisibleByAll' => 'Für alle sichtbarer Inhalt',
		'ContentsVisibleByAllShort' => 'Öffentl. Inhalt',
		'ContentsNotVisibleByAllShort' => 'Privater Inhalt',
		'CategoriesTree' => 'Kategoriebaum',
		'DeleteCategory' => 'Kategorie',
		'ConfirmDeleteCategory' => 'Möchten Sie diese Kategorie wirklich löschen?',
		'RemoveFromCategory' => 'Aus Kategorie entfernen',
		'RemoveFromCategoryConfirm' => 'Zuordnung zu dieser Kategorie wirklich entfernen?',
		'NoCategoriesDefined' => 'Keine Kategorie definiert',
		'SuppliersCategoryShort' => 'Kategorielieferanten',
		'CustomersCategoryShort' => 'Kategoriekunden',
		'ProductsCategoryShort' => 'Kategorieprodukte',
		'MembersCategoryShort' => 'Kategoriemitglieder',
		'SuppliersCategoriesShort' => 'Lieferantenkategorien',
		'CustomersCategoriesShort' => 'Kundenkategorien',
		'CustomersProspectsCategoriesShort' => 'Lead- / Kundenkategorien',
		'ProductsCategoriesShort' => 'Produktkategorien',
		'MembersCategoriesShort' => 'Mitgliedergruppen',
		'ThisCategoryHasNoProduct' => 'Diese Kategorie enthält keine Produkte.',
		'ThisCategoryHasNoSupplier' => 'Diese Kategorie enthält keine Lieferanten.',
		'ThisCategoryHasNoCustomer' => 'Diese Kategorie enthält keine Kunden.',
		'ThisCategoryHasNoMember' => 'Diese Kategorie enthält keine Mitglieder.',
		'AssignedToCustomer' => 'Einem Kunden zugeordnet',
		'AssignedToTheCustomer' => 'An den Kunden',
		'InternalCategory' => 'Interne Kategorie',
		'CategoryContents' => 'Kategorieinhalte',
		'CategId' => 'Kategorie-ID',
		'CatSupList' => 'List of supplier categories',
		'CatCusList' => 'List of customer/prospect categories',
		'CatProdList' => 'List of products categories',
		'CatMemberList' => 'Liste der Kategoriemitglieder',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>