<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$mails = array(
		'CHARSET' => 'UTF-8',
		'Mailing' => 'EMailing',
		'EMailing' => 'E-Mail-Kampagne',
		'Mailings' => 'E-Mail-Kampagnen',
		'EMailings' => 'E-Mail-Kampagne',
		'AllEMailings' => 'Alle E-Mail-Kampagnen',
		'MailCard' => 'E-Mail-Kampagnenkarte',
		'MailTargets' => 'Ziele',
		'MailRecipients' => 'Empfänger',
		'MailRecipient' => 'Empfänger',
		'MailTitle' => 'Titel',
		'MailFrom' => 'Absender',
		'MailErrorsTo' => 'Fehler an',
		'MailReply' => 'Antwort an',
		'MailTo' => 'Empfänger',
		'MailCC' => 'Kopie an',
		'MailCCC' => 'Blindkopie an',
		'MailTopic' => 'E-Mail-Betreff',
		'MailText' => 'E-Mail-Text',
		'MailFile' => 'Angehängte Dateien',
		'MailMessage' => 'E-Mail-Text',
		'ShowEMailing' => 'Zeige E-Mail-Kampagne',
		'ListOfEMailings' => 'Liste der E-Mail-Kampagnen',
		'NewMailing' => 'Neue E-Mail-Kampagne',
		'EditMailing' => 'E-Mail-Kampagne bearbeiten',
		'ResetMailing' => 'E-Mail-Kampagne erneut senden',
		'DeleteMailing' => 'E-Mail-Kampagne löschen',
		'DeleteAMailing' => 'Löschen einer E-Mail-Kampagne',
		'PreviewMailing' => 'E-Mail-Kampagnen-Vorschau',
		'PrepareMailing' => 'E-Mail-Kampagne vorbereiten',
		'CreateMailing' => 'E-Mail-Kampagne erstellen',
		'MailingDesc' => 'Auf dieser Seite können Sie E-Mail-Kampagnen an Gruppen versenden',
		'MailingResult' => 'Ergebnis des E-Mail-Versands',
		'TestMailing' => 'E-Mail-Kampagne testen',
		'ValidMailing' => 'E-Mail-Kampagne freigeben',
		'ApproveMailing' => 'E-Mail-Kampagne bestätigen',
		'MailingStatusDraft' => 'Entwurf',
		'MailingStatusValidated' => 'Freigegeben',
		'MailingStatusApproved' => 'Bestätigt',
		'MailingStatusSent' => 'Gesendet',
		'MailingStatusSentPartialy' => 'Teilweise gesendet',
		'MailingStatusSentCompletely' => 'Vollständig gesendet',
		'MailingStatusError' => 'Fehler beim Versand',
		'MailingStatusNotSent' => 'Nicht gesendet',
		'MailSuccessfulySent' => 'E-Mail-Kampagne erfolgreich versandt (von %s an %s)',
		'MailingSuccessfullyValidated' => 'EMailing successfully validated',
		'MailUnsubcribe' => 'Unsubscribe',
		'Unsuscribe' => 'Unsubscribe',
		'MailingStatusNotContact' => 'Don\'t contact anymore',
		'ErrorMailRecipientIsEmpty' => 'Das Empfängerfeld ist leer',
		'WarningNoEMailsAdded' => 'Keine neuen E-Mail-Adressen für das Hinzufügen zur Empfängerliste.',
		'ConfirmValidMailing' => 'Möchten Sie diese E-Mail-Kampagne wirklich freigeben?',
		'ConfirmResetMailing' => 'Achtung: Die neuerliche Ausführung der E-Mail-Kampagne <b>%s</b> erlaubt Ihnen den Massenversand von E-Mails zu einem anderen Zeitpunkt. Möchten Sie wirklich fortfahren?',
		'ConfirmDeleteMailing' => 'Möchten Sie diese E-Mail-Kampagne wirklich löschen?',
		'NbOfRecipients' => 'Anzahl der Empfänger',
		'NbOfUniqueEMails' => 'Zahl der einzigartigen E-Mail-Adressen',
		'NbOfEMails' => 'Anzahl der E-Mails',
		'TotalNbOfDistinctRecipients' => 'Anzahl der Empfänger',
		'NoTargetYet' => 'Noch keine Empfänger ausgewählt (Bitte wechseln Sie zur Registerkarte "Empfänger")',
		'AddRecipients' => 'Empfänger hinzufügen',
		'RemoveRecipient' => 'Empfänger entfernen',
		'CommonSubstitutions' => 'Allgemeine Ersetzungen',
		'YouCanAddYourOwnPredefindedListHere' => 'Für nähere Informationen zur Erstellung Ihres eigenen E-Mail-Selector-Moduls, lesen Sie bitte die Datei htdocs/core/modules/mailings/README.',
		'EMailTestSubstitutionReplacedByGenericValues' => 'Im Testmodus werden die Variablen durch generische Werte ersetzt',
		'MailingAddFile' => 'Diese Datei anhängen',
		'NoAttachedFiles' => 'Keine angehängten Dateien',
		'BadEMail' => 'Ungültige E-Mail-Adresse',
		'CloneEMailing' => 'E-Mail-Kampagne duplizieren',
		'ConfirmCloneEMailing' => 'Möchten Sie diese E-Mail-Kampagne wirklich duplizieren?',
		'CloneContent' => 'Inhalt duplizieren',
		'CloneReceivers' => 'Empfängerliste duplizieren',
		'DateLastSend' => 'Datum des letzten Versands',
		'DateSending' => 'Versanddatum',
		'SentTo' => 'Versandt an <b>%s</b>',
		'MailingStatusRead' => 'Read',
		'CheckRead' => 'Read Receipt',
		'YourMailUnsubcribeOK' => 'The email <b>%s</b>  is correctly unsubcribe from mailing list',
		'MailtoEMail' => 'Hyper link to email',
		'ActivateCheckRead' => 'Allow to use the Read receipt tracker and the unsubcribe link',
		'ActivateCheckReadKey' => 'Key use to encrypt URL use for Read Receipt and unsubcribe function',
		// Libelle des modules de liste de destinataires mailing
		'MailingModuleDescContactCompanies' => 'Kontakte aller Partner (Kunden, Leads, Lieferanten, ...)',
		'MailingModuleDescDolibarrUsers' => 'Alle Systembenutzer mit E-Mail-Adresse',
		'MailingModuleDescFundationMembers' => 'Alle Stiftungsmitglieder mit E-Mail-Adresse',
		'MailingModuleDescEmailsFromFile' => 'E-Mail-Adressen aus einer Text-Datei (Format: E-Mail, Vorname, Nachname)',
		'MailingModuleDescEmailsFromUser' => 'EMails from user input (email;lastname;firstname;other)',
		'MailingModuleDescContactsCategories' => 'Partnerkontakte (nach Kategorie)',
		'MailingModuleDescDolibarrContractsLinesExpired' => 'Partner mit abgelaufenen Vertragspositionen',
		'MailingModuleDescContactsByCompanyCategory' => 'Kontakte Dritter (durch Dritte Kategorie)',
		'MailingModuleDescMembersCategories' => 'Mitglieder der Stiftung (nach Kategorien)',
		'MailingModuleDescContactsByFunction' => 'Kontakte von Dritten (nach Position / Funktion)',
		'LineInFile' => 'Zeile %s in der Datei',
		'RecipientSelectionModules' => 'Definiert Empfängerauswahlen',
		'MailSelectedRecipients' => 'Ausgewählte Empfänger',
		'MailingArea' => 'E-Mail-Kampagnenübersicht',
		'LastMailings' => '%s neueste E-Mail-Kampagnen',
		'TargetsStatistics' => 'Zielstatistiken',
		'NbOfCompaniesContacts' => 'Einzigartige Partnerkontakte',
		'MailNoChangePossible' => 'Die Empfängerliste einer freigegebenen E-Mail-Kampagne kann nicht mehr geändert werden',
		'SearchAMailing' => 'Suche E-Mail-Kampagne',
		'SendMailing' => 'E-Mail-Kampagne versenden',
		'SendMail' => 'E-Mail versenden',
		'SentBy' => 'Gesendet von',
		'MailingNeedCommand' => 'Aus Sicherheitsgründen sollten E-Mail-Kampagnen von der Kommandozeile aus versandt werden. Bitten Sie Ihren Administrator um die Ausführung des folgenden Befehls, um den Versand an alle Empfänger zu starten:',
		'MailingNeedCommand2' => 'Sie können den Versand jedoch auch online starten, indem Sie den Parameter MAILING_LIMIT_SENDBYWEB auf den Wert der pro Sitzung gleichzeitig zu versendenden Mails setzen. Die entsprechenden Einstellungen finden Sie unter Übersicht-Einstellungen-Andere.',
		'ConfirmSendingEmailing' => 'Möchten Sie diese E-Mail-Kampagne wirklich versenden?<br>Aus Sicherheitsgründen ist der gleichzeitige Versand auf <b>%s</b> Empfänger pro Sitzung beschränkt.',
		'LimitSendingEmailing' => 'Aus Sicherheits- und Zeitüberschreitungsgründen ist der Online-Versadn von E-Mails auf <b>%s</b> Empfänger je Sitzung beschränkt.',
		'TargetsReset' => 'Liste leeren',
		'ToClearAllRecipientsClickHere' => 'Klicken Sie hier, um die Empfängerliste zu leeren',
		'ToAddRecipientsChooseHere' => 'Fügen Sie Empfänger über die Listenauswahl hinzu',
		'NbOfEMailingsReceived' => 'Empfangene E-Mail-Kampagnen',
		'IdRecord' => 'Eintrags ID',
		'DeliveryReceipt' => 'Zustellbestätigung',
		'YouCanUseCommaSeparatorForSeveralRecipients' => 'Trennen Sie mehrere Empfänger mit einem <b>Komma</b>',
		'TagCheckMail' => 'Track mail opening',
		'TagUnsubscribe' => 'Unsubscribe link',
		'TagSignature' => 'Signature sending user',
		'TagMailtoEmail' => 'Recipient EMail',
		// Module Notifications
		'Notifications' => 'Benachrichtigungen',
		'NoNotificationsWillBeSent' => 'Für dieses Ereignis und diesen Partner sind keine Benachrichtigungen geplant',
		'ANotificationsWillBeSent' => '1 Benachrichtigung wird per E-Mail versandt',
		'SomeNotificationsWillBeSent' => '%s Benachrichtigungen werden per E-Mail versandt',
		'AddNewNotification' => 'Aktivieren Sie eine neue E-Mail-Benachrichtigungsanfrage',
		'ListOfActiveNotifications' => 'Liste aller aktiven E-Mail-Benachrichtigungen',
		'ListOfNotificationsDone' => 'Liste aller versandten E-Mail-Benachrichtigungen',
);
?>