<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$orders = array(
		'CHARSET' => 'UTF-8',
		'OrdersArea' => 'Kundenbestellungsübersicht',
		'SuppliersOrdersArea' => 'Lieferantenbestellungsübersicht',
		'OrderCard' => 'Bestell-Karte',
		'OrderId' => 'Order Id',
		'Order' => 'Bestellung',
		'Orders' => 'Bestellungen',
		'OrderLine' => 'Bestellposition',
		'OrderLines' => 'Order lines',
		'OrderFollow' => 'Follow-up',
		'OrderDate' => 'Bestelldatum',
		'OrderToProcess' => 'Zu bearbeitende Bestellung',
		'NewOrder' => 'Neue Bestellung',
		'ToOrder' => 'Erzeuge Bestellung',
		'MakeOrder' => 'Erzeuge Bestellung',
		'SupplierOrder' => 'Lieferantenbestellung',
		'SuppliersOrders' => 'Lieferantenbestellungen',
		'SuppliersOrdersRunning' => 'Aktuelle Lieferantenbestellungen',
		'CustomerOrder' => 'Kundenbestellung',
		'CustomersOrders' => 'Kundenbestellungen',
		'CustomersOrdersRunning' => 'Aktuelle Kundenbestellungen',
		'CustomersOrdersAndOrdersLines' => 'Kundenbestellungen und Bestellpositionen',
		'OrdersToValid' => 'Freizugebende Bestellungen',
		'OrdersToBill' => 'Zu verrechnende Bestellungen',
		'OrdersInProcess' => 'Bestellunen in Bearbeitung',
		'OrdersToProcess' => 'Zu bearbeitende Bestellungen',
		'SuppliersOrdersToProcess' => 'Supplier\'s orders to process',
		'StatusOrderCanceledShort' => 'Storniert',
		'StatusOrderDraftShort' => 'Entwurf',
		'StatusOrderValidatedShort' => 'Freigegeben',
		'StatusOrderSentShort' => 'In process',
		'StatusOrderSent' => 'Shipment in process',
		'StatusOrderOnProcessShort' => 'In Arbeit',
		'StatusOrderProcessedShort' => 'Bearbeitet',
		'StatusOrderToBillShort' => 'Zu verrechnen',
		'StatusOrderToBill2Short' => 'To bill',
		'StatusOrderApprovedShort' => 'Genehmigt',
		'StatusOrderRefusedShort' => 'Abgelehnt',
		'StatusOrderToProcessShort' => 'Zu bearbeiten',
		'StatusOrderReceivedPartiallyShort' => 'Teilweise erhalten',
		'StatusOrderReceivedAllShort' => 'Zur Gänze erhalten',
		'StatusOrderCanceled' => 'Storniert',
		'StatusOrderDraft' => 'Entwurf (freizugeben)',
		'StatusOrderAuto' => 'Draft Internet (needs to be validated)',
		'StatusOrderValidated' => 'Freigegeben',
		'StatusOrderOnProcess' => 'In Arbeit',
		'StatusOrderProcessed' => 'Bearbeitet',
		'StatusOrderToBill' => 'Zu verrechnen',
		'StatusOrderToBill2' => 'To bill',
		'StatusOrderApproved' => 'Genehmigt',
		'StatusOrderRefused' => 'Abgelehnt',
		'StatusOrderReceivedPartially' => 'Teilweise erhalten',
		'StatusOrderReceivedAll' => 'Zur Gänze erhalten',
		'ShippingExist' => 'A shipment exists',
		'DraftOrWaitingApproved' => 'Entwurf oder freigegeben, noch nicht bestellt',
		'DraftOrWaitingShipped' => 'Entwurf oder freigegeben, noch nicht versandt',
		'MenuOrdersToBill' => 'Bestellverrechnung',
		'MenuOrdersToBill2' => 'Orders to bill',
		'SearchOrder' => 'Suche Bestellung',
		'Sending' => 'Sendung',
		'Sendings' => 'Sendungen',
		'ShipProduct' => 'Produkt versenden',
		'Discount' => 'Rabatt',
		'CreateOrder' => 'Erzeuge Bestellung',
		'RefuseOrder' => 'Bestellung ablehnen',
		'ApproveOrder' => 'Bestellung bestätigen',
		'ValidateOrder' => 'Bestellung freigeben',
		'UnvalidateOrder' => 'Unvalidate order',
		'DeleteOrder' => 'Bestellung löschen',
		'CancelOrder' => 'Bestellung verwerfen',
		'AddOrder' => 'Bestellung hinzufügen',
		'AddToMyOrders' => 'Zu meinen Bestellungen hinzufügen',
		'AddToOtherOrders' => 'Zu Bestellungen Anderer hinzufügen',
		'ShowOrder' => 'Zeige Bestellung',
		'NoOpenedOrders' => 'Keine offenen Bestellungen',
		'NoOtherOpenedOrders' => 'Keine offenen Bestellungen Anderer',
		'OtherOrders' => 'Bestellungen Anderer',
		'LastOrders' => 'Neueste %s Bestellungen',
		'LastModifiedOrders' => '%s zuletzt bearbeitete Bestellungen',
		'LastClosedOrders' => '%s zuletzt geschlossene Bestellungen',
		'AllOrders' => 'Alle Bestellungen',
		'NbOfOrders' => 'Anzahl der Bestellungen',
		'OrdersStatistics' => 'Bestellstatistik',
		'OrdersStatisticsSuppliers' => 'Statistik Lieferantenbestellungen',
		'NumberOfOrdersByMonth' => 'Anzahl der Bestellungen pro Monat',
		'AmountOfOrdersByMonthHT' => 'Anzahl der Aufträge pro Monat (nach Steuern)',
		'ListOfOrders' => 'Liste der Bestellungen',
		'CloseOrder' => 'Bestellung schließen',
		'ConfirmCloseOrder' => 'Möchten Sie diese Bestellung wirklich schließen? Nach ihrer Schließung kann eine Bestellung nur mehr in Rechnung gestellt werden.',
		'ConfirmCloseOrderIfSending' => 'Möchten Sie diese Bestellung wirklich schließen? Tun Sie dies erst nachdem alle Versandvorgäng abgeschlossen wurden.',
		'ConfirmDeleteOrder' => 'Möchten Sie diese Bestellung wirklich löschen?',
		'ConfirmValidateOrder' => 'Möchten Sie diese Bestellung wirklich unter dem Namen <b>%s</b> freigeben?',
		'ConfirmUnvalidateOrder' => 'Are you sure you want to restore order <b>%s</b> to draft status ?',
		'ConfirmCancelOrder' => 'Möchten Sie diese Bestellung wirklich verwerfen?',
		'ConfirmMakeOrder' => 'Hiermit bestätigen Sie, diese Bestellung am <b>%s</b> persönlich angelegt zu haben.',
		'GenerateBill' => 'Erzeuge Rechnung',
		'ClassifyShipped' => 'Classify delivered',
		'ClassifyBilled' => 'Als verrechnet markieren',
		'ComptaCard' => 'Buchhaltungskarte',
		'DraftOrders' => 'Bestellentwürfe',
		'RelatedOrders' => 'Verknüpfte Bestellungen',
		'OnProcessOrders' => 'Bestellungen in Bearbeitung',
		'RefOrder' => 'Bestellung Nr.',
		'RefCustomerOrder' => 'Kundenbestellung Nr.',
		'CustomerOrder' => 'Kundenbestellung',
		'RefCustomerOrderShort' => 'Kundenbestellung Nr.',
		'SendOrderByMail' => 'Bestellung per Post versenden',
		'ActionsOnOrder' => 'Maßnahmen zu dieser Bestellung',
		'NoArticleOfTypeProduct' => 'Keine Artikel vom Typ \'Produkt\' und deshalb keine Versandkostenposition',
		'OrderMode' => 'Bestellweise',
		'AuthorRequest' => 'Authorenrechte beantragen',
		'UseCustomerContactAsOrderRecipientIfExist' => 'Anschrift des Partnerkontakts statt Partneradresse für die Zustellung verwenden',
		'RunningOrders' => 'Offene Bestellungen',
		'UserWithApproveOrderGrant' => 'Benutzer mit Berechtigung zur \'Bestellfreigabe\'',
		'PaymentOrderRef' => 'Zahlung zu Bestellung %s',
		'CloneOrder' => 'Duplizieren',
		'ConfirmCloneOrder' => 'Möchten Sie die Bestellung <b>%s</b> wirklich duplizieren?',
		'DispatchSupplierOrder' => 'Lieferantenbestellung %s erhalten',
		'DateDeliveryPlanned' => 'Date de livraison prévue',
		'SetDemandReason' => 'Définir l\'origine de la commande',
		////////// Types de contacts //////////
		'TypeContact_commande_internal_SALESREPFOLL' => 'Kundenauftrags-Nachverfolgung durch Vertreter',
		'TypeContact_commande_internal_SHIPPING' => 'Versand-Nachverfolgung durch Vertreter',
		'TypeContact_commande_external_BILLING' => 'Rechnungskontakt des Kunden',
		'TypeContact_commande_external_SHIPPING' => 'Versandkontakt des Kunden',
		'TypeContact_commande_external_CUSTOMER' => 'Bestellungs-Nachverfolgung durch Kundenkontakt',
		'TypeContact_order_supplier_internal_SALESREPFOLL' => 'Lieferantenbestellungs-Nachverfolgung durch Vertreter',
		'TypeContact_order_supplier_internal_SHIPPING' => 'Versand-Nachverfolgung durch Vertreter',
		'TypeContact_order_supplier_external_BILLING' => 'Kontakt für Lieferantenrechnungen',
		'TypeContact_order_supplier_external_SHIPPING' => 'Kontakt für Lieferantenversand',
		'TypeContact_order_supplier_external_CUSTOMER' => 'Lieferantenkontakt für Bestellverfolgung',
		'Error_COMMANDE_SUPPLIER_ADDON_NotDefined' => 'Konstante COMMANDE_SUPPLIER_ADDON nicht definiert',
		'Error_COMMANDE_ADDON_NotDefined' => 'Konstante COMMANDE_ADDON nicht definiert',
		'Error_FailedToLoad_COMMANDE_SUPPLIER_ADDON_File' => 'Fehler beim Laden der Moduldatei \'%s\'',
		'Error_FailedToLoad_COMMANDE_ADDON_File' => 'Fehler beim Laden der Moduldatei \'%s\'',
		'Error_OrderNotChecked' => 'No orders to invoice selected',
		// Sources
		'OrderSource0' => 'Angebot',
		'OrderSource1' => 'Internet',
		'OrderSource2' => 'E-Mail-Kampagne',
		'OrderSource3' => 'Telefonkampagne',
		'OrderSource4' => 'Fax-Kampagne',
		'OrderSource5' => 'Vertrieb',
		'OrderSource6' => 'Andere',
		'QtyOrdered' => 'Bestellmenge',
		'AddDeliveryCostLine' => 'Fügen Sie eine Versandkostenzeile zur Erfassung des Bestellgewichts ein',
		// Documents models
		'PDFEinsteinDescription' => 'Eine vollständige Bestellvorlage (Logo, ...)',
		'PDFEdisonDescription' => 'Eine einfache Bestellungsvorlage',
		// Orders modes
		'OrderByMail' => 'Mail',
		'OrderByFax' => 'Fax',
		'OrderByEMail' => 'EMail',
		'OrderByWWW' => 'Online',
		'OrderByPhone' => 'Phone',
		'CreateInvoiceForThisCustomer' => 'Bill orders',
		'NoOrdersToInvoice' => 'No orders billable',
		'CloseProcessedOrdersAutomatically' => 'Classify "Processed" all selected orders.',
		'MenuOrdersToBill2' => 'Orders to bill',
		'LinkedInvoices' => 'Linked invoices',
		'LinkedProposals' => 'Linked proposals'
);
?>