<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$other = array(
		'CHARSET' => 'UTF-8',
		'SecurityCode' => 'Sicherheitsschlüssel',
		'Calendar' => 'Kalender',
		'AddTrip' => 'Reise hinzufügen',
		'Tools' => 'Werkzeuge',
		'ToolsDesc' => 'Dieser Bereich ist zur Gruppe diverse Werkzeuge nicht verfügbar in andere Menüeinträge gewidmet. <br><br> Diese Tools können aus dem Menü auf der Seite zu erreichen.',
		'Birthday' => 'Geburtstag',
		'BirthdayDate' => 'Geburtstag',
		'DateToBirth' => 'Geburtstdatum',
		'BirthdayAlertOn' => 'Geburtstagserinnerung EIN',
		'BirthdayAlertOff' => 'Geburtstagserinnerung AUS',
		'Notify_FICHINTER_VALIDATE' => 'Eingriff freigegeben',
		'Notify_BILL_VALIDATE' => 'Rechnung freigegeben',
		'Notify_ORDER_SUPPLIER_APPROVE' => 'Lieferantenbestellung freigegeben',
		'Notify_ORDER_SUPPLIER_REFUSE' => 'Lieferantenbestellung abgelehnt',
		'Notify_ORDER_VALIDATE' => 'Kundenbestellung freigegeben',
		'Notify_PROPAL_VALIDATE' => 'Angebot freigegeben',
		'Notify_WITHDRAW_TRANSMIT' => 'Transmission Rückzug',
		'Notify_WITHDRAW_CREDIT' => 'Kreditkarten Rückzug',
		'Notify_WITHDRAW_EMIT' => 'Isue Rückzug',
		'Notify_ORDER_SENTBYMAIL' => 'Kunden bestellen per Post geschickt',
		'Notify_COMPANY_CREATE' => 'Dritter erstellt',
		'Notify_PROPAL_SENTBYMAIL' => 'Gewerbliche Vorschlag per Post',
		'Notify_ORDER_SENTBYMAIL' => 'Kunden bestellen per Post geschickt',
		'Notify_BILL_PAYED' => 'Kunden Rechnung bezahlt',
		'Notify_BILL_CANCEL' => 'Kunden Rechnung storniert',
		'Notify_BILL_SENTBYMAIL' => 'Kunden Rechnung per Post geschickt',
		'Notify_ORDER_SUPPLIER_VALIDATE' => 'Lieferanten, um validierte',
		'Notify_ORDER_SUPPLIER_SENTBYMAIL' => 'Lieferant Bestellung per Post geschickt',
		'Notify_BILL_SUPPLIER_VALIDATE' => 'Lieferantenrechnung validiert',
		'Notify_BILL_SUPPLIER_PAYED' => 'Lieferantenrechnung bezahlt',
		'Notify_BILL_SUPPLIER_SENTBYMAIL' => 'Lieferant Rechnung per Post geschickt',
		'Notify_CONTRACT_VALIDATE' => 'Contract validiert',
		'Notify_FICHEINTER_VALIDATE' => 'Intervention validiert',
		'Notify_SHIPPING_VALIDATE' => 'Liefer-validierte',
		'Notify_SHIPPING_SENTBYMAIL' => 'Versand per Post',
		'Notify_MEMBER_VALIDATE' => 'Mitglied validiert',
		'Notify_MEMBER_SUBSCRIPTION' => 'Mitglied gezeichneten',
		'Notify_MEMBER_RESILIATE' => 'Mitglied resiliated',
		'Notify_MEMBER_DELETE' => 'Mitglied gelöscht',
		'NbOfAttachedFiles' => 'Anzahl der angehängten Dateien/okumente',
		'TotalSizeOfAttachedFiles' => 'Gesamtgröße der angehängten Dateien/Dokumente',
		'MaxSize' => 'Maximalgröße',
		'AttachANewFile' => 'Neue Datei/Dokument anhängen',
		'LinkedObject' => 'Verknüpftes Objekt',
		'Miscellanous' => 'Verschiedenes',
		'NbOfActiveNotifications' => 'Anzahl aktiver Benachrichtigungen',
		'PredefinedMailTest' => 'Dies ist ein Test-Mail.\n Die beiden Zeilen sind durch eine Zeilenschaltung getrennt.',
		'PredefinedMailTestHtml' => 'Dies ist ein (HTML)-<b>Test</b> Mail (das Wort Test muss in Fettschrift erscheinen). <br> Die beiden Zeilen sollteb durch eine Zeilenschaltung getrennt sein.',
		'PredefinedMailContentSendInvoice' => 'Bitte entnehmen Sie dem Anhang die Rechnung __FACREF__\n\n__PERSONALIZED__Mit freundlichen Grüßen\n\n__SIGNATURE__',
		'PredefinedMailContentSendInvoiceReminder' => 'Bedauerlicherweise scheint die Rechnung __FACREF__ bislang unbeglichen. Als Erinnerung übersenden wir Ihnen diese nochmals im Anhang\n\n__PERSONALIZED__Mit freundlichen Grüßen\n\n__SIGNATURE__',
		'PredefinedMailContentSendProposal' => 'Bitte entnehmen Sie dem Anhang unser Angebot __PROPREF__ \n\n__PERSONALIZED__Mit freundlichen Grüßen\n\n__SIGNATURE__',
		'PredefinedMailContentSendOrder' => 'Bitte entnehmen Sie dem Anhang die Bestellung __ORDERREF__ \n\n__PERSONALIZED__Mit freundlichen Grüßen\n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierOrder' => 'Hier finden Sie unser Bestellformular __ORDERREF__ \n\nMit freundlichen Grüßen\n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierInvoice' => 'Hier finden Sie die Rechnung __FACREF__ \n\nSincerely \n\n__SIGNATURE__',
		'PredefinedMailContentSendShipping' => 'Hier finden Sie die Versandkosten __SHIPPINGREF__ \n\nSincerely \n\n__SIGNATURE__',
		'PredefinedMailContentSendFichInter' => 'Hier finden Sie die Intervention __FICHINTERREF__ \n\nSincerely \n\n__SIGNATURE__',
		'DemoDesc' => 'Bei Speedealing handelt es sich um ein kompaktes ERP/CRM-System, bestehend aus einzelnen Modulen. Da eine Demo aller Module kaum eine praxisnahe Anwendung darstellt, stehen Ihnen unterschiedliche Demo-Profile zur Verfügung.',
		'ChooseYourDemoProfil' => 'Bitte wählen Sie das Demo-Profil das Ihrem Berufsfeld am ehesten entspricht',
		'DemoFundation' => 'Verwalten Sie die Mitglieder einer Stiftung',
		'DemoFundation2' => 'Verwalten Sie die Mitglieder und Bankkonten einer Stiftung',
		'DemoCompanyServiceOnly' => 'Verwalten Sie ein reines Service-/Dienstleistungsunternehmen',
		'DemoCompanyShopWithCashDesk' => 'Verwalten Sie ein Geschäft mit Kasse',
		'DemoCompanyProductAndStocks' => 'Verwalten Sie den Produktverkauf und die Lagerstandsverwaltung eines kleinen oder mittleren Unternehmen',
		'DemoCompanyAll' => 'Verwalten Sie ein kleines oder mittleres Unternehmen mit mehreren Aktivitäten (alle wesentlichen Module)',
		'GoToDemo' => 'Demo ansehen',
		'CreatedBy' => 'Erstellt von %s',
		'ModifiedBy' => 'Bearbeitet von %s',
		'ValidatedBy' => 'Freigegeben von %s',
		'CanceledBy' => 'Storniert von %s',
		'ClosedBy' => 'Geschlossen von %s',
		'FileWasRemoved' => 'Datei wurde entfernt',
		'DirWasRemoved' => 'Verzeichnis wurde entfernt',
		'FeatureNotYetAvailableShort' => 'Erhältlich in einer der nächsten Versionen',
		'FeatureNotYetAvailable' => 'Diese Funktion steht in der derzeitigen Version noch nicht zur Verfügung',
		'FeatureExperimental' => 'Experimentelle Funktion. In dieser Version noch nicht als stabil geführt.',
		'FeatureDevelopment' => 'Funktion in Entwicklung. In dieser Version noch nicht als stabil geführt.',
		'FeaturesSupported' => 'Unterstützte Funktionen',
		'Width' => 'Breite',
		'Height' => 'Höhe',
		'Depth' => 'Tiefe',
		'Top' => 'Top',
		'Bottom' => 'Boden',
		'Left' => 'Links',
		'Right' => 'Recht',
		'CalculatedWeight' => 'Errechnetes Gewicht',
		'CalculatedVolume' => 'Errechnetes Volumen',
		'Weight' => 'Gewicht',
		'TotalWeight' => 'Gesamtgewicht',
		'WeightUnitton' => 't',
		'WeightUnitkg' => 'kg',
		'WeightUnitg' => 'g',
		'WeightUnitmg' => 'mg',
		'WeightUnitpound' => 'Pfund',
		'Length' => 'Länge',
		'LengthUnitm' => 'm',
		'LengthUnitdm' => 'dm',
		'LengthUnitcm' => 'cm',
		'LengthUnitmm' => 'mm',
		'Surface' => 'Oberfläche',
		'SurfaceUnitm2' => 'm²',
		'SurfaceUnitdm2' => 'dm²',
		'SurfaceUnitcm2' => 'cm²',
		'SurfaceUnitmm2' => 'mm²',
		'SurfaceUnitfoot2' => 'ft2',
		'SurfaceUnitinch2' => 'in2',
		'Volume' => 'Volumen',
		'TotalVolume' => 'Gesamtvolumen',
		'VolumeUnitm3' => 'm³',
		'VolumeUnitdm3' => 'dm³',
		'VolumeUnitcm3' => 'cm³',
		'VolumeUnitmm3' => 'mm³',
		'VolumeUnitfoot3' => 'ft3',
		'VolumeUnitinch3' => 'in3',
		'VolumeUnitounce' => 'Unze',
		'VolumeUnitlitre' => 'Liter',
		'VolumeUnitgallon' => 'Gallone',
		'Size' => 'Größe',
		'SizeUnitm' => 'm',
		'SizeUnitdm' => 'dm',
		'SizeUnitcm' => 'cm',
		'SizeUnitmm' => 'mm',
		'SizeUnitinch' => 'Zoll',
		'SizeUnitfoot' => 'Fuß',
		'SizeUnitpoint' => 'point',
		'BugTracker' => 'Fehlerverfolgung (Bug-Tracker)',
		'SendNewPasswordDesc' => 'Über dieses Formular können Sie sich ein neues Passwort zusenden lassen.<br>Die Änderungen an Ihrem Passwort werden erst wirksam, wenn Sie auf den im Mail enthaltenen Bestätigungslink klicken. <br> Überprüfen Sie den Posteingang Ihrer E-Mail-Anwendung.',
		'BackToLoginPage' => 'Zurück zur Anmeldeseite',
		'AuthenticationDoesNotAllowSendNewPassword' => 'Im derzeit gewählten Authentifizierungsmodus <b>(%s)</b> kann das System nicht auf Ihre Passwortdaten zugreifen und diese auch nicht ändern.<br> Wenden Sie sich hierzu bitte an den Systemadministrator.',
		'EnableGDLibraryDesc' => 'Für den Einsatz dieser Option installieren, bzw. aktivieren Sie bitte die GD-Library.',
		'EnablePhpAVModuleDesc' => 'Bitte installieren Sie ein mit Ihrem Virenschutz kompatibles Modul. (ClamAV: php4-clamavlib oder php5-clamavlib)',
		'ProfIdShortDesc' => '<b>Prof ID %s</b> dient zur Speicherung landesabhängiger Partnerdaten. <br> Für das Land <b>%s</b> ist dies beispielsweise Code <b>%s</b>.',
		'SpeedealingDemo' => 'Speedealing ERP/CRM demo',
		'StatsByNumberOfUnits' => 'Statistik der Zahl der Einheiten',
		'StatsByNumberOfEntities' => 'Statistik der Zahl der Entitäten',
		'NumberOfProposals' => 'Anzahl der Angebote in den letzten 12 Monaten',
		'NumberOfCustomerOrders' => 'Anzahl der Kundenaufträge in den letzten 12 Monaten',
		'NumberOfCustomerInvoices' => 'Anzahl der Kundenrechnungen in den letzten 12 Monaten',
		'NumberOfSupplierInvoices' => 'Anzahl der Lieferantenrechnungen in den letzten 12 Monaten',
		'NumberOfUnitsProposals' => 'Anzahl der Produkte/Services in Angeboten der letzten 12 Monate',
		'NumberOfUnitsCustomerOrders' => 'Anzahl der Produkte/Services in Kundenaufträgen der letzten 12 Monate',
		'NumberOfUnitsCustomerInvoices' => 'Anzahl der Produkte/Services in Kundenrechnungen der letzten 12 Monate',
		'NumberOfUnitsSupplierInvoices' => 'Anzahl der Produkte/Services in Lieferantenrechnungen der letzten 12 Monate',
		'EMailTextInterventionValidated' => 'Eingriff %s freigegeben',
		'EMailTextInvoiceValidated' => 'Rechnung %s freigegeben',
		'EMailTextProposalValidated' => 'Angebot %s wurde freigegeben.',
		'EMailTextOrderValidated' => 'Bestellung %s wurde freigegeben.',
		'EMailTextOrderApproved' => 'Bestellung %s genehmigt',
		'EMailTextOrderApprovedBy' => 'Bestellung %s von %s genehmigt',
		'EMailTextOrderRefused' => 'Bestellung %s abgelehnt',
		'EMailTextOrderRefusedBy' => 'Bestellung %s von %s abgelehnt',
		'ImportedWithSet' => 'Import Datensatz',
		'SpeedealingNotification' => 'Automatic notification',
		'ResizeDesc' => 'Bitte geben Sie eine neue Breite <b>oder</b> Höhe ein. Das Verhältnis wird während des Zuschneidens erhalten...',
		'NewLength' => 'Neue Breite',
		'NewHeight' => 'Neue Höhe',
		'NewSizeAfterCropping' => 'Neue Größe nach dem Zuschneiden',
		'DefineNewAreaToPick' => 'Definieren Sie einen neuen Bereich innerhalb des Bildes (Klicken Sie mit der linken Maustaste auf das Bild und halten Sie bis zur gegenüberligenden Ecke)',
		'CurrentInformationOnImage' => 'Dieses Werzeug hilft Ihnen beim Skalieren und Zuschneiden von Bildern. Diese Informationen existieren derzeit zur Bilddatei',
		'ImageEditor' => 'Bildbearbeitung',
		'YouReceiveMailBecauseOfNotification' => 'Sie erhalten diese Nachricht, weil Ihre E-Mail-Adresse zur Liste der zu benachrichtigenden Kontakte für %s von %s hinzugefügt wurde.',
		'YouReceiveMailBecauseOfNotification2' => 'Sie erhalten dieses Mail aufgrund folgender Benachrichtigung:',
		'ThisIsListOfModules' => 'Dies ist eine Liste der Module, die von dieser Demo-Profil (nur gängigsten Module sind in dieser Demo) vorgewählt. Bearbeiten, um eine personalisierte Demo haben und klicken Sie auf &quot;Start&quot;.',
		'ClickHere' => 'Klicken Sie hier',
		'UseAdvancedPerms' => 'Verwenden Sie die erweiterten Berechtigungen einiger Module',
		'FileFormat' => 'Dateiformat',
		'SelectAColor' => 'Wählen Sie eine Farbe',
		'AddFiles' => 'Dateien hinzufügen',
		'StartUpload' => 'Start upload',
		'CancelUpload' => 'Cancel upload',
		'FileIsTooBig' => 'Files is too big',
		'PleaseBePatient' => 'Please be patient...',
		////////// Calendar common //////////
		'AddCalendarEntry' => 'Neuer Eintrag im Kalender %s',
		'NewCompanyToSpeedealing' => 'Company %s added into Speedealing',
		'ContractValidatedInSpeedealing' => 'Contract %s validated in Speedealing',
		'ContractCanceledInSpeedealing' => 'Contract %s canceled in Speedealing',
		'ContractClosedInSpeedealing' => 'Contract %s closed in Speedealing',
		'PropalClosedSignedInSpeedealing' => 'Proposal %s signed in Speedealing',
		'PropalClosedRefusedInSpeedealing' => 'Proposal %s refused in Speedealing',
		'PropalValidatedInSpeedealing' => 'Proposal %s validated in Speedealing',
		'InvoiceValidatedInSpeedealing' => 'Invoice %s validated in Speedealing',
		'InvoicePaidInSpeedealing' => 'Invoice %s changed to paid in Speedealing',
		'InvoiceCanceledInSpeedealing' => 'Invoice %s canceled in Speedealing',
		'PaymentDoneInSpeedealing' => 'Payment %s done in Speedealing',
		'CustomerPaymentDoneInSpeedealing' => 'Customer payment %s done in Speedealing',
		'SupplierPaymentDoneInSpeedealing' => 'Supplier payment %s done in Speedealing',
		'MemberValidatedInSpeedealing' => 'Member %s validated in Speedealing',
		'MemberResiliatedInSpeedealing' => 'Member %s resiliated in Speedealing',
		'MemberDeletedInSpeedealing' => 'Member %s deleted from Speedealing',
		'MemberSubscriptionAddedInSpeedealing' => 'Subscription for member %s added in Speedealing',
		'ShipmentValidatedInSpeedealing' => 'Shipment %s validated in Speedealing',
		////////// Export //////////
		'Export' => 'Export',
		'ExportsArea' => 'Exportübersicht',
		'AvailableFormats' => 'Verfügbare Formate',
		'LibraryUsed' => 'Verwendete Bibliothek',
		'LibraryVersion' => 'Bibliotheksversion',
		'ExportableDatas' => 'Exportfähige Daten',
		'NoExportableData' => 'Keine exportfähigen Daten (keine Module mit exportfähigen Dateien oder fehlende Berechtigungen)',
		'ToExport' => 'Export',
		'NewExport' => 'Neuer Export',
		////////// External sites //////////
		'ExternalSites' => 'Externe Seiten'
);
?>