<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$projects = array(
		'CHARSET' => 'UTF-8',
		'Project' => 'Projekt',
		'Projects' => 'Projekte',
		'SharedProject' => 'Jeder',
		'PrivateProject' => 'Projektansprechpartner',
		'MyProjectsDesc' => 'Diese Ansicht ist auf Projekte beschränkt, zu denen Sie als Kontakt definiert sind (unabhängig vom Typ).',
		'ProjectsPublicDesc' => 'Diese Ansicht zeigt alle für Sie sichtbaren Projekte.',
		'ProjectsDesc' => 'Diese Ansicht zeigt alle Projekte (Ihre Benutzerberechtigung erlaubt Ihnen eine volle Einsicht aller Projekte).',
		'MyTasksDesc' => 'Diese Ansicht ist auf Aufgaben beschränkt, zu denen Sie als Kontakt definiert sind (unabhängig vom Typ).',
		'TasksPublicDesc' => 'Diese Ansicht zeigt alle für Sie sichtbaren Aufgaben.',
		'TasksDesc' => 'Diese Ansicht zeigt alle Aufgaben (Ihre Benutzerberechtigung erlaubt Ihnen eine volle Einsicht aller Aufgaben).',
		'Myprojects' => 'Meine Projekte',
		'ProjectsArea' => 'Projektübersicht',
		'NewProject' => 'Neues Projekt',
		'AddProject' => 'Projekt hinzufügen',
		'DeleteAProject' => 'Löschen eines Projekts',
		'DeleteATask' => 'Löschen einer Aufgabe',
		'ConfirmDeleteAProject' => 'Möchten Sie dieses Projekt wirklich löschen?',
		'ConfirmDeleteATask' => 'Möchten Sie diese Aufgabe wirklich löschen?',
		'OfficerProject' => 'Projektverantwortlicher',
		'LastProjects' => '%s neueste Projekte',
		'AllProjects' => 'Alle Projekte',
		'ProjectsList' => 'Liste der Projekte',
		'ShowProject' => 'Zeige Projekt',
		'SetProject' => 'Projekt setzen',
		'NoProject' => 'Kein Projekt definiert',
		'NbOpenTasks' => 'Anzahl der offenen Aufgaben',
		'NbOfProjects' => 'Anzahl der Projekte',
		'TimeSpent' => 'Zeitaufwand',
		'TimesSpent' => 'Time spent',
		'RefTask' => 'Aufgaben Nr.',
		'LabelTask' => 'Aufgabenbezeichnung',
		'NewTimeSpent' => 'Neuer Zeitaufwand',
		'MyTimeSpent' => 'Mein Zeitaufwand',
		'MyTasks' => 'Meine Aufgaben',
		'Tasks' => 'Aufgaben',
		'Task' => 'Aufgabe',
		'NewTask' => 'Neue Aufgabe',
		'AddTask' => 'Aufgabe hinzufügen',
		'AddDuration' => 'Dauer hinzufügen',
		'Activity' => 'Tätigkeit',
		'Activities' => 'Aufgaben/Tätigkeiten',
		'MyActivity' => 'Meine Tätigkeit',
		'MyActivities' => 'Meine Tätigkeiten',
		'MyProjects' => 'Meine Projekte',
		'DurationEffective' => 'Effektivdauer',
		'Progress' => 'Fortschritt',
		'Time' => 'Zeitaufwand',
		'ListProposalsAssociatedProject' => 'Liste der mit diesem Projekt verbundenen Angebote',
		'ListOrdersAssociatedProject' => 'Liste der mit diesem Projekt verbundenen Bestellungen',
		'ListInvoicesAssociatedProject' => 'Liste der mit diesem Projekt verbundenen Rechnungen',
		'ListPredefinedInvoicesAssociatedProject' => 'Liste der mit diesem Projekt verknüpften Rechnungsvorlagen',
		'ListSupplierOrdersAssociatedProject' => 'Liste der mit diesem Projekt verbundenen Lieferantenbestellungen',
		'ListSupplierInvoicesAssociatedProject' => 'Liste der mit diesem Projekt verbundenen Lieferantenrechnungen',
		'ListContractAssociatedProject' => 'Liste der mit diesem Projekt verbundenen Verträge',
		'ListFichinterAssociatedProject' => 'Liste der mit diesem Projekt verknüpften Eingriffe',
		'ListTripAssociatedProject' => 'Liste der mit diesem Projekt verknüpften Reise- und Fahrtspesen',
		'ListActionsAssociatedProject' => 'Liste der mit diesem Projekt verknüpften Maßnahmen',
		'ActivityOnProjectThisWeek' => 'Projektaktivitäten dieser Woche',
		'ActivityOnProjectThisMonth' => 'Projektaktivitäten dieses Monats',
		'ActivityOnProjectThisYear' => 'Projektaktivitäten dieses Jahres',
		'ChildOfTask' => 'Kindelement von Projekt/Aufgabe',
		'NotOwnerOfProject' => 'Nicht Eigner des privaten Projekts',
		'AffectedTo' => 'Zugewiesen an',
		'CantRemoveProject' => 'Löschen des Projekts auf Grund verbundener Elemente (Rechnungen, Bestellungen oder andere) nicht möglich. Näheres finden Sie in der Verweiskarte.',
		'ValidateProject' => 'Projekt freigeben',
		'ConfirmValidateProject' => 'Möchten Sie dieses Projekt wirklich freigeben?',
		'CloseAProject' => 'Schließe Projekt',
		'ConfirmCloseAProject' => 'Möchten Sie dieses Projekt wirklich schließen?',
		'ReOpenAProject' => 'Öffne Projekt',
		'ConfirmReOpenAProject' => 'Möchten Sie dieses Projekt wirklich wiedereröffnen?',
		'ProjectContact' => 'Projektkontakt',
		'ActionsOnProject' => 'Projektaktionen',
		'YouAreNotContactOfProject' => 'Sie sind diesem privaten Projekt nicht als Kontakt zugeordnet.',
		'DeleteATimeSpent' => 'Lösche einen Zeitaufwand',
		'ConfirmDeleteATimeSpent' => 'Möchten Sie diesen Zeitaufwand wirklich löschen?',
		'DoNotShowMyTasksOnly' => 'Zeige auch die Aufgaben Anderer',
		'ShowMyTasksOnly' => 'Zeige nur meine Aufgaben',
		'TaskRessourceLinks' => 'Ressourcen',
		'ProjectsDedicatedToThisThirdParty' => 'Mit diesem Partner verknüpfte Projekte',
		'NoTasks' => 'Keine Aufgaben für dieses Projekt',
		'LinkedToAnotherCompany' => 'Mit Partner verknüpft',
		'TaskIsNotAffectedToYou' => 'Task not allocated to you',
		'ErrorTimeSpentIsEmpty' => 'Time spent is empty',
		'ThisWillAlsoRemoveTasks' => 'This action will also delete all tasks of project (<b>%s</b> tasks at the moment) and all inputs of time spent.',
		'IfNeedToUseOhterObjectKeepEmpty' => 'If some objects (invoice, order, ...), belonging to another third party, must be linked to the project to create, keep this empty to have the project being multi third parties.',
		'CloneProject' => 'Clone project',
		'CloneTasks' => 'Clone tasks',
		'CloneContacts' => 'Clone contacts',
		'CloneNotes' => 'Clone notes',
		'CloneFiles' => 'Clone joined files',
		'ConfirmCloneProject' => 'Are you sure to clone this project ?',
		'ProjectReportDate' => 'Change task date according project start date',
		'ErrorShiftTaskDate' => 'Impossible to shift task date according to new project start date',
		////////// Types de contacts //////////
		'TypeContact_project_internal_PROJECTLEADER' => 'Projektleiter',
		'TypeContact_project_external_PROJECTLEADER' => 'Projektleiter',
		'TypeContact_project_internal_CONTRIBUTOR' => 'Mitwirkender',
		'TypeContact_project_external_CONTRIBUTOR' => 'Mitwirkender',
		'TypeContact_project_task_internal_TASKEXECUTIVE' => 'Task Exekutive',
		'TypeContact_project_task_external_TASKEXECUTIVE' => 'Task Exekutive',
		'TypeContact_project_task_internal_CONTRIBUTOR' => 'Mitwirkender',
		'TypeContact_project_task_external_CONTRIBUTOR' => 'Mitwirkender',
		// Documents models
		'DocumentModelBaleine' => 'Eine vollständige Projektberichtsvorlage (Logo, ...)'
);
?>