<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$propal = array(
		'CHARSET' => 'UTF-8',
		'Proposals' => 'Angebote',
		'Proposal' => 'Angebot',
		'ProposalShort' => 'Angebot',
		'ProposalsDraft' => 'Angebotsentwürfe',
		'ProposalDraft' => 'Angebotsentwurf',
		'ProposalsOpened' => 'Offene Angebote',
		'Prop' => 'Angebot',
		'CommercialProposal' => 'Angebot',
		'CommercialProposals' => 'Angebote',
		'ProposalCard' => 'Proposal card',
		'NewProp' => 'Neues Angebot',
		'NewProposal' => 'Neues Angebot',
		'NewPropal' => 'Neues Angebot',
		'Prospect' => 'Lead',
		'ProspectList' => 'Liste der Leads',
		'DeleteProp' => 'Angebot löschen',
		'ValidateProp' => 'Angebot freigeben',
		'AddProp' => 'Angebot hinzufügen',
		'ConfirmDeleteProp' => 'Möchten Sie dieses Angebot wirklich löschen?',
		'ConfirmValidateProp' => 'Möchten Sie dieses Angebots wirklich freigeben?',
		'LastPropals' => '%s zuletzt bearbeitete Angebote',
		'LastClosedProposals' => '%s zuletzt abgeschlossene Angebote',
		'LastModifiedProposals' => '%s zuletzt bearbeitete Angebote',
		'AllPropals' => 'Alle Angebote',
		'LastProposals' => 'Letzte Angebote',
		'SearchAProposal' => 'Angebot suchen',
		'ProposalsStatistics' => 'Angebotsstatistiken',
		'NumberOfProposalsByMonth' => 'Anzahl pro Monat',
		'AmountOfProposalsByMonthHT' => 'Betrag pro Monat (nach Steuern)',
		'NbOfProposals' => 'Zahl der Angebote',
		'ShowPropal' => 'Zeige Angebot',
		'PropalsDraft' => 'Entwurf',
		'PropalsOpened' => 'Offen',
		'PropalsNotBilled' => 'Geschlossen, nicht verrechnet',
		'PropalStatusDraft' => 'Entwurf (freizugeben)',
		'PropalStatusValidated' => 'Freigegeben (Angebot ist offen)',
		'PropalStatusOpened' => 'Freigegeben (Angebot ist offen)',
		'PropalStatusClosed' => 'Geschlossen',
		'PropalStatusSigned' => 'Unterzeichnet (auf Rechnung)',
		'PropalStatusNotSigned' => 'Nicht unterzeichnet (geschlossen)',
		'PropalStatusBilled' => 'Verrechnet',
		'PropalStatusDraftShort' => 'Entwurf',
		'PropalStatusValidatedShort' => 'Freigegeben',
		'PropalStatusOpenedShort' => 'Offen',
		'PropalStatusClosedShort' => 'Geschlossen',
		'PropalStatusSignedShort' => 'Unterzeichnet',
		'PropalStatusNotSignedShort' => 'Nicht unterzeichnet',
		'PropalStatusBilledShort' => 'Verrechnet',
		'PropalsToClose' => 'Zu schließende Angebote',
		'PropalsToBill' => 'Unterzeichnete Angebote zur Verrechnung',
		'ListOfProposals' => 'Liste der Angebote',
		'ActionsOnPropal' => 'Maßnahmen zum Angebot',
		'NoOpenedPropals' => 'Keine offenen Angebote',
		'NoOtherOpenedPropals' => 'Keine offenen Angebote Anderer',
		'RefProposal' => 'Angebots Nr.',
		'SendPropalByMail' => 'Angebot per E-Mail senden',
		'FileNotUploaded' => 'Datei nicht hochgeladen',
		'FileUploaded' => 'Datei erfolgreich hochgeladen',
		'AssociatedDocuments' => 'Dokumente mit Bezug zum Angebot:',
		'ErrorCantOpenDir' => 'Verzeichnis kann nicht geöffnet werden',
		'DatePropal' => 'Datum des Angebots',
		'DateEndPropal' => 'Ablauf der Bindefrist',
		'DateEndPropalShort' => 'Ablaufdatum',
		'ValidityDuration' => 'Bindefrist',
		'CloseAs' => 'Schließen mit dem Status',
		'ClassifyBilled' => 'Verrechnet',
		'BuildBill' => 'Erzeuge Rechnung',
		'ErrorPropalNotFound' => 'Angebot %s nicht gefunden',
		'Estimate' => 'Geschätzt :',
		'EstimateShort' => 'Schätzung',
		'OtherPropals' => 'Andere Angebote',
		'CopyPropalFrom' => 'Erstelle neues Angebot durch Duplikation',
		'CreateEmptyPropal' => 'Erstelle leeres Angebot oder aus der Produkt-/Dienstleistungsliste',
		'DefaultProposalDurationValidity' => 'Standardmäßige Bindefrist (Tage)',
		'UseCustomerContactAsPropalRecipientIfExist' => 'Falls vorhanden die Adresse des Partnerkontakts statt der Partneradresse verwenden',
		'ClonePropal' => 'Angebot duplizieren',
		'ConfirmClonePropal' => 'Möchten Sie das Angebot <b>%s</b> wirklich duplizieren?',
		'ConfirmReOpenProp' => 'Are you sure you want to open back the commercial proposal <b>%s</b> ?',
		'ProposalsAndProposalsLines' => 'Angebote und Positionen',
		'ProposalLine' => 'Angebotsposition',
		'AvailabilityPeriod' => 'Availability delay',
		'SetAvailability' => 'Set availability delay',
		'AfterOrder' => 'after order',
		////////// Availability //////////
		'AvailabilityTypeAV_NOW' => 'Immediate',
		'AvailabilityTypeAV_1W' => '1 week',
		'AvailabilityTypeAV_2W' => '2 weeks',
		'AvailabilityTypeAV_3W' => '3 weeks',
		'AvailabilityTypeAV_1M' => '1 month',
		////////// Types de contacts //////////
		'TypeContact_propal_internal_SALESREPFOLL' => 'Angebotsnachverfolgung durch Vertreter',
		'TypeContact_propal_external_BILLING' => 'Kontakt für Kundenrechnungen',
		'TypeContact_propal_external_CUSTOMER' => 'Angebots-Nachverfolgung durch Partnerkontakt',
		// Document models
		'DocModelAzurDescription' => 'Eine vollständige Angebotsvorlage (Logo, ...)',
		'DocModelJauneDescription' => 'Angebotsvorlage Jaune',
		'Numbershort' => 'N°',
		'LinkdedOrders' => 'Linked orders'
);
?>