<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Warenlagerkarte',
		'Warehouse' => 'Warenlager',
		'Warehouses' => 'Warehouses',
		'NewWarehouse' => 'Neues Warenlager',
		'WarehouseEdit' => 'Warenlager bearbeiten',
		'MenuNewWarehouse' => 'Neues Warenlager',
		'WarehouseOpened' => 'Warenlager aktiv',
		'WarehouseClosed' => 'Warenlager geschlossen',
		'WarehouseSource' => 'Ursprungslager',
		'WarehouseSourceNotDefined' => 'No warehouse defined,',
		'AddOne' => 'Add one',
		'WarehouseTarget' => 'Ziellager',
		'ValidateSending' => 'Sendung freigeben',
		'CancelSending' => 'Sendung abbrechen',
		'DeleteSending' => 'Sendung löschen',
		'Stock' => 'Warenbestand',
		'Stocks' => 'Warenbestände',
		'Movement' => 'Lagerbewegung',
		'Movements' => 'Lagerbewegungen',
		'ErrorWarehouseRefRequired' => 'Warenlager-Referenz erforderlich',
		'ErrorWarehouseLabelRequired' => 'Warenlager-Label erforderlich',
		'CorrectStock' => 'Lagerbestand anpassen',
		'ListOfWarehouses' => 'Liste der Warenlager',
		'ListOfStockMovements' => 'Liste der Lagerbewegungen',
		'StocksArea' => 'Warenbestandsübersicht',
		'Location' => 'Standort',
		'LocationSummary' => 'Kurzbezeichnung Standort',
		'NumberOfProducts' => 'Anzahl der Produkte',
		'LastMovement' => 'Letzte Bewegung',
		'LastMovements' => 'Letzte Bewegungen',
		'Units' => 'Einheiten',
		'Unit' => 'Einheit',
		'StockCorrection' => 'Lageranpassung',
		'StockMovement' => 'Lagerbewegung',
		'StockMovements' => 'Lagerbewegungen',
		'NumberOfUnit' => 'Anzahl der Einheiten',
		'UnitPurchaseValue' => 'Unit purchase price',
		'TotalStock' => 'Gesamtbestand',
		'StockTooLow' => 'Mindestbestand unterschritten',
		'StockLowerThanLimit' => 'Stock lower than alert limit',
		'EnhancedValue' => 'Warenwert',
		'PMPValue' => 'Warenwert',
		'PMPValueShort' => 'WAP',
		'EnhancedValueOfWarehouses' => 'Lagerwert',
		'UserWarehouseAutoCreate' => 'Beim Anlegen eines Benutzers automatisch neues Warenlager erstellen',
		'QtyDispatched' => 'Menge',
		'OrderDispatch' => 'Bestellabwicklung',
		'RuleForStockManagementDecrease' => 'Regel für Lagerstandsanpassung (Verringerung)',
		'RuleForStockManagementIncrease' => 'Regel für Lagerstandsanpassung (Erhöhung)',
		'DeStockOnBill' => 'Verringere realen Bestände in den Rechnungen / Gutschriften',
		'DeStockOnValidateOrder' => 'Decrease realen Bestände auf Bestellungen stellt fest',
		'DeStockOnShipment' => 'Verringere Lagerstände nach erfolgtem Versand (empfohlen)',
		'ReStockOnBill' => 'Erhöhung der tatsächlichen Bestände in den Rechnungen / Gutschriften',
		'ReStockOnValidateOrder' => 'Erhöhung der realen Bestände auf Bestellungen stellt fest',
		'ReStockOnDispatchOrder' => 'Reale Bestände auf manuelle Dispatching in Hallen, nach Erhalt Lieferanten bestellen',
		'OrderStatusNotReadyToDispatch' => 'Auftrag wurde noch nicht oder nicht mehr ein Status, der Erzeugnisse auf Lager Hallen Versand ermöglicht.',
		'StockDiffPhysicTeoric' => 'Grund für die Differenz physisch. und theoret. Lagerbestand',
		'NoPredefinedProductToDispatch' => 'Keine vordefinierten Produkte für dieses Objekt. Also kein Versand im Lager erforderlich ist.',
		'DispatchVerb' => 'Versand',
		'StockLimitShort' => 'Mindestbestand',
		'StockLimit' => 'Sicherungsbestand für autom. Benachrichtigung',
		'PhysicalStock' => 'Physisches Warenlager',
		'RealStock' => 'Realer Lagerbestand',
		'TheoreticalStock' => 'Theoretischer Lagerbestand',
		'VirtualStock' => 'Virtuelles Warenlager',
		'MininumStock' => 'Mindestlagerstand',
		'StockUp' => 'Aufstocken',
		'MininumStockShort' => 'Sicherungsbestand',
		'StockUpShort' => 'Aufstocken',
		'IdWarehouse' => 'Warenlager ID',
		'DescWareHouse' => 'Beschreibung Warenlager',
		'LieuWareHouse' => 'Standort Warenlager',
		'WarehousesAndProducts' => 'Warenlager und Produkte',
		'AverageUnitPricePMPShort' => 'Weighted average input price',
		'AverageUnitPricePMP' => 'Weighted average input price',
		'SellPriceMin' => 'Selling Unit Price',
		'EstimatedStockValueSellShort' => 'Value to sell',
		'EstimatedStockValueSell' => 'Value to Sell',
		'EstimatedStockValueShort' => 'Input stock value',
		'EstimatedStockValue' => 'Input stock value',
		'DeleteAWarehouse' => 'Warenlager löschen',
		'ConfirmDeleteWarehouse' => 'Möchten Sie das Warenlager <b>%s</b> wirklich löschen?',
		'PersonalStock' => 'Persönlicher Warenbestand %s',
		'ThisWarehouseIsPersonalStock' => 'Dieses Lager bezeichnet den persönlichen Bestand von %s %s',
		'SelectWarehouseForStockDecrease' => 'Choose warehouse to use for stock decrease',
		'SelectWarehouseForStockIncrease' => 'Choose warehouse to use for stock increase',
		'LastWaitingSupplierOrders' => 'Orders waiting for receptions'
);
?>