<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'Benutzerkarte',
		'ContactCard' => 'Kontaktkarte',
		'GroupCard' => 'Firmenverbundkarte',
		'NoContactCard' => 'Keine Kontaktkarte',
		'Permission' => 'Berechtigung',
		'Permissions' => 'Berechtigungen',
		'EditPassword' => 'Passwort bearbeiten',
		'SendNewPassword' => 'Neues Passwort zusenden',
		'ReinitPassword' => 'Passwort zurücksetzen',
		'PasswordChangedTo' => 'Neues Passwort: %s',
		'SubjectNewPassword' => 'Ihr neues Passwort',
		'AvailableRights' => 'Verfügbare Berechtigungen',
		'OwnedRights' => 'Besitz Berechtigungen',
		'GroupRights' => 'Gruppe Berechtigungen',
		'UserRights' => 'Benutzerberechtigungen',
		'UserGUISetup' => 'Einstellungen Benutzeroberfläche',
		'DisableUser' => 'Deaktiviere Benutzer',
		'DisableAUser' => 'Einen Benutzer deaktivieren',
		'DeleteUser' => 'Lösche Benutzer',
		'DeleteAUser' => 'Einen Benutzer löschen',
		'DisableGroup' => 'Deaktiviere Gruppe',
		'DisableAGroup' => 'Eine Gruppe deaktivieren',
		'EnableAUser' => 'Einen Benutzer aktivieren',
		'EnableAGroup' => 'Eine Gruppe aktivieren',
		'DeleteGroup' => 'Lösche Gruppe',
		'DeleteAGroup' => 'Eine Gruppe löschen',
		'ConfirmDisableUser' => 'Möchten Sie diesen Benutzer <b>%s</b> wirklich deaktivieren?',
		'ConfirmDisableGroup' => 'Möchten Sie diese Gruppe <b>%s</b> wirklich deaktivieren?',
		'ConfirmDeleteUser' => 'Möchten Sie diesen Benutzer <b>%s</b> wirklich löschen?',
		'ConfirmDeleteGroup' => 'Möchten Sie diese Gruppe <b>%s</b> wirklich löschen?',
		'ConfirmEnableUser' => 'Möchten Sie diesen Benutzer <b>%s</b> wirklich aktivieren?',
		'ConfirmEnableGroup' => 'Möchten Sie diese Gruppe <b>%s</b> wirklich aktivieren?',
		'ConfirmReinitPassword' => 'Möchten Sie das Passwort für Benutzer <b>%s</b> wirklich zurücksetzen',
		'ConfirmSendNewPassword' => 'Möchten Sie für diesen Benutzer <b>%s</b> wirklich ein neues Passwort generieren und diesem per Mail zusenden?',
		'NewUser' => 'Neuer Benutzer',
		'CreateUser' => 'Benutzer anlegen',
		'SearchAGroup' => 'Suche Gruppe',
		'SearchAUser' => 'Suche Benutzer',
		'LoginNotDefined' => 'Benutzername ist nicht gesetzt.',
		'NameNotDefined' => 'Name ist nicht gesetzt.',
		'ListOfUsers' => 'Liste der Benutzer',
		'Administrator' => 'Administrator',
		'SuperAdministrator' => 'Super Administrator',
		'SuperAdministratorDesc' => 'Administrator mit allen Rechten',
		'AdministratorDesc' => 'Administrator\'s entity',
		'DefaultRights' => 'Standardberechtigungen',
		'DefaultRightsDesc' => 'Definieren Sie hier die, neu erstellten Benutzern automatisch zugewiesenen, Standardberechtigungen.',
		'DolibarrUsers' => 'Benutzer',
		'LastName' => 'Nachname',
		'FirstName' => 'Vorname',
		'ListOfGroups' => 'Liste von Gruppen',
		'NewGroup' => 'Neue Gruppe',
		'CreateGroup' => 'Gruppe erstellen',
		'RemoveFromGroup' => 'Gruppenzuweisung entfernen',
		'PasswordChangedAndSentTo' => 'Passwort geändert und an <b>%s</b> gesandt.',
		'PasswordChangeRequestSent' => 'Antrag auf eine Änderung das Passworts für <b>%s</b> an <b>%s</b> gesandt.',
		'MenuUsersAndGroups' => 'Benutzer & Gruppen',
		'LastGroupsCreated' => '%s zuletzt erstellte Gruppen',
		'LastUsersCreated' => '%s zuletzt erstellte Benutzer',
		'ShowGroup' => 'Zeige Gruppe',
		'ShowUser' => 'Zeige Benutzer',
		'NonAffectedUsers' => 'Nicht betroffene Benutzer',
		'UserModified' => 'Benutzer erfolgreich bearbeitet',
		'GroupModified' => 'Gruppe erfolgreich bearbeitet',
		'PhotoFile' => 'Bilddatei',
		'UserWithDolibarrAccess' => 'Benutzer mit Zugangsberechtigung',
		'ListOfUsersInGroup' => 'Liste der Benutzer in dieser Gruppe',
		'ListOfGroupsForUser' => 'Liste der Gruppen dieses Benutzers',
		'UsersToAdd' => 'Dieser Gruppe zuzuweisende Benutzer',
		'GroupsToAdd' => 'Diesem Benutzer zuzuweisende Gruppen',
		'NoLogin' => 'Kein Login',
		'LinkToCompanyContact' => 'Mit Partner/Kontakt verknüpfen',
		'LinkedToDolibarrMember' => 'Mit Mitglied verknüpfen',
		'LinkedToDolibarrUser' => 'Mit Systembenutzer verknüpfen',
		'LinkedToDolibarrThirdParty' => 'Mit Partner verknüpfen',
		'CreateDolibarrLogin' => 'Benutzerkonto erstellen',
		'CreateDolibarrThirdParty' => 'Neuen Partner erstellen',
		'LoginAccountDisable' => 'Benutzerkonto deaktiviert. Zum Aktivieren bitte neuen Login anlegen.',
		'LoginAccountDisableInDolibarr' => 'Benutzerkonto im System deaktiviert.',
		'LoginAccountDisableInLdap' => 'Benutzerkonto in dieser Domäne deaktiviert.',
		'UsePersonalValue' => 'Eigenen Wert verwenden',
		'GuiLanguage' => 'Sprache der Benutzeroberfläche',
		'InternalUser' => 'Interne Benutzer',
		'MyInformations' => 'Meine Daten',
		'ExportDataset_user_1' => 'Benutzer und -eigenschaften',
		'DomainUser' => 'Domain-Benutzer %s',
		'Reactivate' => 'Reaktivieren',
		'CreateInternalUserDesc' => 'Dieses Formular erlaubt Ihnen das Anlegen eines unternehmensinternen Benutzers. Zum Anlegen eines externen Benutzers (Kunden, Lieferanten, ...), verwenden Sie bitte die \'Benutzer erstellen\'-Schaltfläche in der Kontaktkarte des jeweiligen Partnerkontakts.',
		'InternalExternalDesc' => 'Ein <b>interner</b> Benutzer ist Teil Ihres Unternehmens/Ihrer Stiftung. <br> Ein <b>externer</b> Benutzer ist ein Kunde, Lieferant oder Anderes. <br><br> In beiden Fällen können Sie die Berechtigungen definieren - externe Benutzer können zudem auch einen andere Menüverwaltung als interne Benutzer haben (siehe Home - Einstellungen - Anzeige)',
		'PermissionInheritedFromAGroup' => 'Berechtigung durch eine Gruppenzugehörigkeit gererbt.',
		'Inherited' => 'Geerbt',
		'UserWillBeInternalUser' => 'Created user will be an internal user (because not linked to a particular third party)',
		'UserWillBeExternalUser' => 'Created user will be an external user (because linked to a particular third party)',
		'IdPhoneCaller' => 'Anrufer ID',
		'UserLogged' => 'Benutzer %s verbunden',
		'UserLogoff' => 'User %s logout',
		'NewUserCreated' => 'Benutzer %s erstellt',
		'NewUserPassword' => 'Passwort ändern für %s',
		'EventUserModified' => 'Benutzer %s geändert',
		'UserDisabled' => 'Benutzer %s deaktiviert',
		'UserEnabled' => 'Benutzer %s aktiviert',
		'UserDeleted' => 'Benutzer %s entfernt',
		'NewGroupCreated' => 'Gruppe %s erstellt',
		'GroupModified' => 'Gruppe erfolgreich bearbeitet',
		'GroupDeleted' => 'Gruppe %s entfernt',
		'ConfirmCreateContact' => 'Möchten Sie für diesen Kontakt wirklich ein Systembenutzerkonto anlegen?',
		'ConfirmCreateLogin' => 'Möchten Sie für dieses Mitglied wirklich ein Benutzerkonto erstellen?',
		'ConfirmCreateThirdParty' => 'Möchten Sie zu diesem Mitglied wirklich einen Partner erstellen?',
		'LoginToCreate' => 'Zu erstellende Anmeldung',
		'NameToCreate' => 'Name des neuen Partners',
		'YourRole' => 'Ihre Rolle',
		'YourQuotaOfUsersIsReached' => 'Ihr Kontingent aktiver Benutzer ist erreicht',
		'NbOfUsers' => 'Nb of users',
		'DontDowngradeSuperAdmin' => 'Only a superadmin can downgrade a superadmin',
);
?>