<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$install = array(
		'CHARSET' => 'UTF-8',
		'InstallEasy' => 'فقط اتبع التعليمات خطوة بخطوة.',
		'MiscellanousChecks' => 'التحقق من الشروط الأساسية',
		'SpeedealingWelcome' => 'Welcome to Speedealing',
		'ConfFileExists' => 'ملفات موجودة <b>٪ ق.</b>',
		'ConfFileDoesNotExists' => 'ملفات <b>ل ٪</b> لا وجود له!',
		'ConfFileDoesNotExistsAndCouldNotBeCreated' => 'ملفات <b>ل ٪</b> لا وجود له وأنه لا يمكن خلق!',
		'ConfFileCouldBeCreated' => 'ملفات <b>ل ٪</b> ويمكن أن تنشأ.',
		'ConfFileIsNotWritable' => 'ملفات <b>٪ ق</b> ليست للكتابة. التحقق من الأذونات. أولا لتركيب وخدمة الويب الخاص بك يجب أن تمنح ليكون قادرا على الكتابة في هذا الملف خلال عملية التهيئة ( "chmod 666" على سبيل المثال ، مثل نظام التشغيل يونكس).',
		'ConfFileIsWritable' => 'ملفات للكتابة هو <b>٪ ق.</b>',
		'ConfFileReload' => 'تحديث جميع المعلومات من ملف التكوين.',
		'PHPSupportSessions' => 'ويدعم هذا PHP الدورات.',
		'PHPSupportPOSTGETOk' => 'ويدعم هذا PHP المتغيرات والحصول على الوظائف.',
		'PHPSupportPOSTGETKo' => 'فمن الممكن PHP الإعداد الخاص بك لا يدعم الوظائف المتغيرات و / أو الحصول عليه. التحقق من اتصالك <b>variables_order</b> معلمة في php.ini.',
		'PHPSupportGD' => 'PHP هذا الدعم البيانية ش ج المهام.',
		'PHPSupportUTF8' => 'PHP دعم UTF8 هذه المهام.',
		'PHPMemoryOK' => 'الحد الأقصى الخاص بك PHP دورة الذاكرة ومن المقرر <b>٪ ق.</b> وينبغي أن يكون هذا كافيا.',
		'PHPMemoryTooLow' => 'الحد الأقصى الخاص بك PHP دورة الذاكرة ومن المقرر <b>٪ ق</b> بايت. لهذا ينبغي أن يكون منخفضا جدا. تغيير <b>php.ini</b> وضع <b>memory_limit</b> المعلم إلى ما لا يقل عن <b>٪ ق</b> بايت.',
		'Recheck' => 'اضغط هنا لمزيد من الاختبار ذو معنى',
		'ErrorPHPDoesNotSupportSessions' => 'PHP تركيب الخاص بك لا يدعم الدورات. هذه الميزة هو مطلوب لجعل العمل Speedealing. التحقق من اتصالك PHP الإعداد.',
		'ErrorPHPDoesNotSupportGD' => 'PHP تركيب الخاص بك لا يدعم وظيفة بيانية ش ج. لا الرسم البياني سيكون متاحا.',
		'ErrorPHPDoesNotSupportUTF8' => 'PHP تركيب الخاص بك لا يدعم UTF8 المهام. Speedealing لا يمكن أن تعمل بشكل صحيح. لحل هذه قبل تثبيت Speedealing.',
		'ErrorDirDoesNotExists' => 'دليل ٪ ق لا يوجد.',
		'ErrorGoBackAndCorrectParameters' => 'العودة إلى الوراء وتصحيح الخطأ البارامترات.',
		'ErrorWrongValueForParameter' => 'قد تكون لديكم مطبوعة خاطئة قيمة معلمة \'٪ ق.',
		'ErrorFailedToCreateDatabase' => 'فشل إنشاء قاعدة بيانات \'٪ ق.',
		'ErrorFailedToConnectToDatabase' => 'فشل في الاتصال بقاعدة البيانات \'٪ ق.',
		'ErrorDatabaseVersionTooLow' => 'Database version (%s) too old. Version %s or higher is required.',
		'ErrorPHPVersionTooLow' => 'PHP نسخة قديمة جدا. النسخة ٪ ق هو مطلوب.',
		'WarningPHPVersionTooLow' => 'PHP نسخة قديمة جدا. ومن المتوقع %s نسخة أو أكثر. وينبغي أن تسمح هذه النسخة تثبيت ولكن لم يتم اعتماد.',
		'ErrorConnectedButDatabaseNotFound' => 'خادم الصدد الى قاعدة البيانات ولكن النجاح في \'٪ ق\' لم يتم العثور عليه.',
		'ErrorDatabaseAlreadyExists' => 'قاعدة البيانات \'٪ ق\' موجود بالفعل.',
		'IfDatabaseNotExistsGoBackAndUncheckCreate' => 'إذا كان لا وجود قاعدة بيانات ، والتأكد من العودة الخيار "إنشاء قاعدة بيانات".',
		'IfDatabaseExistsGoBackAndCheckCreate' => 'إذا كانت قاعدة البيانات موجود بالفعل ، من العودة وإلغاء "إنشاء قاعدة بيانات" الخيار.',
		'WarningBrowserTooOld' => 'Too old version of browser. Upgrading your browser to a recent version of Firefox, Chrome or Opera is highly recommanded.',
		'PHPVersion' => 'PHP الإصدار',
		'YouCanContinue' => 'يمكنك الاستمرار...',
		'PleaseBePatient' => 'يرجى التحلي بالصبر...',
		'License' => 'الترخيص باستعمال',
		'ConfigurationFile' => 'ملفات',
		'WebPagesDirectory' => 'الدليل حيث يتم تخزين صفحات الويب',
		'DocumentsDirectory' => 'دليل لتخزين وتحميل وثائق ولدت',
		'URLRoot' => 'عنوان روت',
		'ForceHttps' => 'اتصالات آمنة قوة ([هتبس)',
		'CheckToForceHttps' => 'تحقق هذا الخيار لفرض اتصالات آمنة ([هتبس). <br> وهذا يتطلب أن يتم تكوين خادم الويب مع شهادة خدمة تصميم المواقع.',
		'SpeedealingDatabase' => 'Speedealing Database',
		'DatabaseChoice' => 'اختيار قاعدة البيانات',
		'DatabaseType' => 'قاعدة بيانات من نوع',
		'DriverType' => 'سائق نوع',
		'Server' => 'الخادم',
		'ServerAddressDescription' => 'الملكية الفكرية في اسم أو عنوان خادم قاعدة البيانات ، وعادة \'localhost\' عندما يستضيف خادم قاعدة البيانات على نفس الخادم من خدمة الويب',
		'ServerPortDescription' => 'قاعدة بيانات الميناء. تبقي فارغة إذا كانت غير معروفة.',
		'DatabaseServer' => 'خادم قاعدة البيانات',
		'DatabaseName' => 'اسم قاعدة البيانات',
		'DatabasePrefix' => 'قاعدة بيانات بادئة الجدول',
		'Login' => 'تسجيل الدخول',
		'AdminLogin' => 'ادخل لSpeedealing مدير قاعدة البيانات. تبقي فارغة إذا لم يذكر اسمه في اتصال',
		'Password' => 'كلمة السر',
		'PasswordAgain' => 'أعد كتابة كلمة المرور مرة ثانية',
		'AdminPassword' => 'Speedealing كلمة السر لمدير قاعدة البيانات. تبقي فارغة إذا لم يذكر اسمه في اتصال',
		'CreateDatabase' => 'إنشاء قاعدة بيانات',
		'CreateUser' => 'إنشاء مستخدم',
		'DatabaseSuperUserAccess' => 'قاعدة بيانات -- وصول مستخدم الكومبيوتر ذو الصلاحيات العليا',
		'CheckToCreateDatabase' => 'المربع إذا كان لا وجود قاعدة بيانات ، ويجب تهيئة. <br> في هذه الحالة ، يجب عليك ملء ادخل كلمة السر لحساب المستعملين المتميزين في أسفل هذه الصفحة.',
		'CheckToCreateUser' => 'المربع اذا ادخل لا وجود له ، ويجب تهيئة. <br> في هذه الحالة ، يجب عليك ملء ادخل كلمة السر لحساب المستعملين المتميزين في أسفل هذه الصفحة.',
		'Experimental' => '(التجريبية وغير التشغيلية)',
		'DatabaseRootLoginDescription' => 'ادخل يسمح للمستخدم لإنشاء قواعد بيانات جديدة أو المستخدمين الجدد ، وإذا كانت غير مجدية وقاعدة البيانات وقاعدة البيانات ادخل موجود بالفعل (مثل عندما كنت استضافته استضافة ويب).',
		'KeepEmptyIfNoPassword' => 'ترك فارغا إذا لم المستخدم كلمة السر (تجنب هذا؟)',
		'SaveConfigurationFile' => 'إنقاذ القيم',
		'ConfigurationSaving' => 'إنقاذ ملفات',
		'ServerConnection' => 'اتصال الخادم',
		'DatabaseConnection' => 'قاعدة بيانات الصدد',
		'DatabaseCreation' => 'إنشاء قاعدة بيانات',
		'UserCreation' => 'إنشاء مستخدم',
		'CreateDatabaseObjects' => 'إنشاء قاعدة بيانات الأجسام',
		'ReferenceDataLoading' => 'تحميل البيانات المرجعية',
		'TablesAndPrimaryKeysCreation' => 'الجداول وإنشاء المفاتيح الأساسية',
		'CreateTableAndPrimaryKey' => 'إنشاء الجدول ق ٪',
		'CreateOtherKeysForTable' => 'خلق الخارجية مفاتيح الأرقام القياسية والجدول ق ٪',
		'OtherKeysCreation' => 'مفاتيح الخارجية وإنشاء الفهارس',
		'FunctionsCreation' => 'خلق وظائف',
		'AdminAccountCreation' => 'مدير ادخل خلق',
		'PleaseTypePassword' => 'الرجاء كتابة كلمة المرور ، وكلمات السر فارغة لا يسمح!',
		'PleaseTypeALogin' => 'اكتب من فضلك ادخل!',
		'PasswordsMismatch' => 'وتختلف كلمات السر ، يرجى المحاولة مرة أخرى!',
		'SetupEnd' => 'نهاية الإعداد',
		'SystemIsInstalled' => 'هذا التثبيت الكامل.',
		'SystemIsUpgraded' => 'وقد تم تطوير Speedealing بنجاح.',
		'YouNeedToPersonalizeSetup' => 'عليك تكوين Speedealing لتناسب احتياجاتك (ظهور مقالات...). لذلك ، يرجى اتباع الوصلة التالية :',
		'AdminLoginCreatedSuccessfuly' => 'مدير Speedealing ادخل <b>\'٪ ق\'</b> خلق بنجاح.',
		'GoToSpeedealing' => 'Go to Speedealing',
		'GoToSetupArea' => 'الذهاب إلى Speedealing (مجال الإعداد)',
		'MigrationNotFinished' => 'نسخة من قاعدة البيانات الخاصة بك لا يصل تماما حتى الآن ، لذلك سيكون لديك لتشغيل عملية الترقية مرة أخرى.',
		'GoToUpgradePage' => 'الذهاب لتحديث الصفحة مرة أخرى',
		'Examples' => 'أمثلة',
		'WithNoSlashAtTheEnd' => 'بدون خفض "/" في نهاية',
		'DirectoryRecommendation' => 'وrecommanded به لاستخدام دليل خارج الدليل الخاص من صفحات موقعك.',
		'LoginAlreadyExists' => 'موجود بالفعل',
		'SpeedealingAdminLogin' => 'Speedealing admin login',
		'AdminLoginAlreadyExists' => 'Speedealing حساب مشرف <b>\'٪ ق\'</b> موجود بالفعل.',
		'WarningRemoveInstallDir' => 'تحذير ، لأسباب أمنية ، بعد تثبيت أو تحديث كاملة ، يجب إزالة <b>تثبيت أو إعادة تسمية الدليل على install.lock من أجل تجنب استخدام الخبيثة.</b>',
		'ThisPHPDoesNotSupportTypeBase' => 'PHP هذا النظام لا يدعم أي واجهة للحصول على قاعدة بيانات من نوع ق ٪',
		'FunctionNotAvailableInThisPHP' => 'لا تتوفر على هذا PHP',
		'MigrateScript' => 'تهاجر سكريبت',
		'ChoosedMigrateScript' => 'اختار الهجرة سكريبت',
		'DataMigration' => 'بيانات الهجرة',
		'DatabaseMigration' => 'هيكل قاعدة بيانات الهجرة',
		'ProcessMigrateScript' => 'السيناريو تجهيز',
		'ChooseYourSetupMode' => 'اختر طريقة الإعداد وانقر على "ابدأ"...',
		'FreshInstall' => 'تركيب جديد',
		'FreshInstallDesc' => 'استخدام هذا الأسلوب إذا كان هذا هو أول تركيب. إذا لم يكن هذا الوضع لا يمكن إصلاح تثبيت سابقة غير مكتملة ، ولكن إذا كنت ترغب في تحديث الإصدار الخاص بك ، اختر "ترقية" واسطة.',
		'Upgrade' => 'ترقية',
		'UpgradeDesc' => 'استخدام هذه الطريقة إذا كنت قد حلت محل القديمة Speedealing الملفات من الملفات مع إصدار أحدث. وهذا من شأنه رفع مستوى قاعدة البيانات والبيانات.',
		'Start' => 'يبدأ',
		'InstallNotAllowed' => 'الإعداد غير مسموح به <b>conf.php</b> الاذونات',
		'NotAvailable' => 'غير متاحة',
		'YouMustCreateWithPermission' => 'يجب إنشاء ملف ق ٪ ومجموعة الكتابة على أذونات لملقم الويب أثناء عملية التثبيت.',
		'CorrectProblemAndReloadPage' => 'يرجى تحديد المشكلة والصحافة F5 لإعادة تحميل الصفحة.',
		'AlreadyDone' => 'بالفعل هاجر',
		'DatabaseVersion' => 'قاعدة بيانات النسخة',
		'ServerVersion' => 'خادم قاعدة البيانات النسخة',
		'YouMustCreateItAndAllowServerToWrite' => 'يجب إنشاء هذا الدليل ، والسماح لخادم الويب أن يكتبوا فيه.',
		'CharsetChoice' => 'اختيار مجموعة حروف',
		'CharacterSetClient' => 'مجموعة الحروف المستخدمة في توليدها صفحات هتمل',
		'CharacterSetClientComment' => 'اختيار الطابع المحدد لعرضها على الإنترنت. <br/> واقترحت مجموعة الطابع الافتراضي هو واحد من قاعدة البيانات.',
		'CollationConnection' => 'طابع الفرز بغية',
		'CollationConnectionComment' => 'اختر صفحة المدونة التي تحدد طبيعة النظام \'sفرز قاعدة البيانات التي تستخدمها. هذا هو المعلم كما دعا \'مقارنتها\' بعض قواعد البيانات. <br/> هذا المعلم لا يمكن أن يعرف إذا كانت قاعدة البيانات موجودة بالفعل.',
		'CharacterSetDatabase' => 'الطابع المحدد لقاعدة البيانات',
		'CharacterSetDatabaseComment' => 'اختيار مجموعة حروف تريد لإنشاء قاعدة بيانات. <br/> هذا المعلم لا يمكن أن يعرف إذا كانت قاعدة البيانات موجودة بالفعل.',
		'YouAskDatabaseCreationSoSpeedealingNeedToConnect' => 'You ask to create database <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'YouAskLoginCreationSoSpeedealingNeedToConnect' => 'You ask to create database login <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'BecauseConnectionFailedParametersMayBeWrong' => 'كما فشلت الصدد ، أو استضافة السوبر معالم المستخدم يجب أن يكون على خطأ.',
		'OrphelinsPaymentsDetectedByMethod' => 'Orphelins من اكتشاف طريقة الدفع ق ٪',
		'RemoveItManuallyAndPressF5ToContinue' => 'إزالته يدويا واضغط F5 للمتابعة.',
		'KeepDefaultValuesWamp' => 'استخدام معالج الإعداد DoliWamp ، حتى القيم المقترحة هنا بالفعل الأمثل. تغييرها إلا إذا كنت تعرف ما تفعله.',
		'KeepDefaultValuesDeb' => 'يمكنك استخدام معالج الإعداد Speedealing من أوبونتو أو حزمة ديبيان ، لذلك القيم المقترحة هنا هي الأمثل بالفعل. يجب أن تكتمل إلا كلمة السر للمالك قاعدة البيانات لإنشاء. تغيير معلمات أخرى إلا إذا كنت تعرف ما تفعله.',
		'KeepDefaultValuesMamp' => 'استخدام معالج الإعداد DoliMamp ، حتى القيم المقترحة هنا بالفعل الأمثل. تغييرها إلا إذا كنت تعرف ما تفعله.',
		'KeepDefaultValuesProxmox' => 'يمكنك استخدام معالج إعداد Speedealing من الأجهزة الظاهرية Proxmox، بحيث يتم تحسين بالفعل القيم المقترحة هنا. تغييرها إلا إذا كنت تعرف ما تفعله.',
		'FieldRenamed' => 'تغيير اسم الميدان',
		'IfLoginDoesNotExistsCheckCreateUser' => 'اذا ادخل لا يوجد حتى الآن ، يجب عليك التحقق من خيار "تكوين المستخدم"',
		'ErrorConnection' => 'الخادم <b>"٪ ل"</b> اسم قاعدة بيانات <b>"٪ ل"</b> ادخل <b>"٪ ل"</b> أو كلمة سر قاعدة البيانات قد تكون خاطئة أو PHP العميل نسخة قديمة جدا ويمكن مقارنة مع قاعدة البيانات نسخة.',
		'InstallChoiceRecommanded' => 'وأوصت لتثبيت اختيار النسخة <b>٪ المستندات</b> الخاصة بك من النسخة الحالية <b>ل ٪</b>',
		'InstallChoiceSuggested' => '<b>اقترح تثبيت اختيار المثبت.</b>',
		'MigrateIsDoneStepByStep' => 'النسخة المستهدفة (%s) لديها فجوة من إصدارات عديدة، لذلك تثبيت المعالج سوف يعود تشير إلى الهجرة مرة القادمة سوف يتم الانتهاء من هذا واحد.',
		'CheckThatDatabasenameIsCorrect' => 'تأكد من أن اسم قاعدة البيانات <b>"%s"</b> هو الصحيح.',
		'IfAlreadyExistsCheckOption' => 'وإذا كان هذا الاسم هو الصحيح وأنه لا وجود قاعدة بيانات حتى الآن ، ويجب التحقق من خيار "إنشاء قاعدة بيانات".',
		'OpenBaseDir' => 'بي openbasedir المعلمة',
		'YouAskToCreateDatabaseSoRootRequired' => 'يمكنك التحقق من مربع "إنشاء قاعدة بيانات". لهذا ، تحتاج إلى توفير الدخول وكلمة السر من المستعملين المتميزين (الجزء السفلي من النموذج).',
		'YouAskToCreateDatabaseUserSoRootRequired' => 'يمكنك التحقق من مربع "إنشاء قاعدة بيانات مالك". لهذا ، تحتاج إلى توفير الدخول وكلمة السر من المستعملين المتميزين (الجزء السفلي من النموذج).',
		'NextStepMightLastALongTime' => 'الخطوة الحالية قد تستمر لعدة دقائق. ويرد الرجاء الانتظار حتى الشاشة التالية تماما قبل الشروع في الاستمرار.',
		'LastStepDesc' => '<strong>الخطوة الأخيرة</strong> : تعريف المستخدم وكلمة السر هنا كنت تخطط لاستخدامها للاتصال البرمجيات. لا تفقد هذا كما هو حساب لإدارة جميع الآخرين.',
		'ActivateModule' => 'تفعيل وحدة %s',
		'ShowEditTechnicalParameters' => 'Click here to show/edit advanced parameters (expert mode)',
		'ServerPortCouchdbDescription' => 'Port du serveur. Défaut 5984.',
		'ServerAddressCouchdbDescription' => 'Nom FQDN du serveur de base de données, \'localhost.localdomain\' quand le serveur est installé sur la même machine que le serveur web',
		'DatabaseCouchdbUserDescription' => 'Login du super administrateur ayant tous les droits sur le serveur CouchDB ou l\'administrateur propriétaire de la base si la base et son compte d\'accès existent déjà (comme lorsque vous êtes chez un hébergeur).<br><br><div class="alert-box info">Cet utilisateur/mot de passe sera l\'administrateur pour se connecter à Speedealing.</div>',
		'CheckToCreateCouchdbDatabase' => 'Cochez cette option si la base de données n\'existe pas et doit être créée.',
		'CreateAdminUser' => 'Créer le super administrateur (Première installation de couchDB)',
		'MemcachedDescription' => 'Activer Memcached necessite l\'installation d\'un serveur Memcached et des lib php-memcached ou php-memcache. Il peut être activer après l\'installation.',
		'ServerAddressMemcachedDesc' => 'Nom ou adresse ip du serveur memcached, généralement \'localhost\' quand le serveur est installé sur la même machine que le serveur web',
		'ServerPortMemcachedDesc' => 'Port du serveur memcached. Défaut : 11211',
		'EnabledMemcached' => 'Activer Memcached',
		'DatabaseNoSQL' => 'Base de données CouchDB',
		'FailedToCreateAdminLogin' => 'Echec de la création du compte administrateur Speedealing.',
		'LinkedElementsInvalidDeleted' => '<b>%s</b> liaisons invalides ont été supprimées',
		'NothingToDelete' => 'Aucune liaison invalide trouvée',
		'SourceType' => 'Source',
		'TargetType' => 'Cible',
                // Upgrade
                'UpgradeOk' => 'Upgrade is ok !',
                'NewInstalledVersion' => 'Your new version is %s',
                'NeedUpgrade' => 'New Speedealing version !',
                'WarningUpgrade' => 'Installed version is %s, you must upgrade to %s. <br>Please contact your administrator.'
);
?>