<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$other = array(
		'CHARSET' => 'UTF-8',
		'SecurityCode' => 'رمز الحماية',
		'Calendar' => 'التقويم',
		'AddTrip' => 'إضافة رحلة',
		'Tools' => 'أدوات',
		'ToolsDesc' => 'ويكرس هذا المجال لمجموعة الأدوات المتنوعة التي لم تتوفر في إدخالات القوائم الأخرى. <br><br> ويمكن الوصول إلى هذه الأدوات من القائمة على الجانب.',
		'Birthday' => 'عيد ميلاد',
		'BirthdayDate' => 'عيد ميلاد',
		'DateToBirth' => 'تاريخ الميلاد',
		'BirthdayAlertOn' => 'عيد ميلاد النشطة في حالة تأهب',
		'BirthdayAlertOff' => 'عيد الميلاد فى حالة تأهب الخاملة',
		'Notify_FICHINTER_VALIDATE' => 'تدخل المصادق',
		'Notify_BILL_VALIDATE' => 'فاتورة مصادق',
		'Notify_ORDER_SUPPLIER_APPROVE' => 'من أجل الموافقة على المورد',
		'Notify_ORDER_SUPPLIER_REFUSE' => 'من أجل رفض الموردين',
		'Notify_ORDER_VALIDATE' => 'التحقق من صحة النظام العميل',
		'Notify_PROPAL_VALIDATE' => 'التحقق من صحة اقتراح العملاء',
		'Notify_WITHDRAW_TRANSMIT' => 'انتقال انسحاب',
		'Notify_WITHDRAW_CREDIT' => 'انسحاب الائتمان',
		'Notify_WITHDRAW_EMIT' => 'Isue انسحاب',
		'Notify_ORDER_SENTBYMAIL' => 'النظام العميل ترسل عن طريق البريد',
		'Notify_COMPANY_CREATE' => 'طرف ثالث خلق',
		'Notify_PROPAL_SENTBYMAIL' => 'اقتراح التجارية المرسلة عن طريق البريد',
		'Notify_ORDER_SENTBYMAIL' => 'النظام العميل ترسل عن طريق البريد',
		'Notify_BILL_PAYED' => 'دفعت فاتورة العميل',
		'Notify_BILL_CANCEL' => 'فاتورة الزبون إلغاء',
		'Notify_BILL_SENTBYMAIL' => 'فاتورة الزبون إرسالها عن طريق البريد',
		'Notify_ORDER_SUPPLIER_VALIDATE' => 'أجل التحقق من صحة المورد',
		'Notify_ORDER_SUPPLIER_SENTBYMAIL' => 'النظام مزود ترسل عن طريق البريد',
		'Notify_BILL_SUPPLIER_VALIDATE' => 'فاتورة المورد المصادق',
		'Notify_BILL_SUPPLIER_PAYED' => 'دفعت فاتورة المورد',
		'Notify_BILL_SUPPLIER_SENTBYMAIL' => 'فاتورة المورد ترسل عن طريق البريد',
		'Notify_CONTRACT_VALIDATE' => 'التحقق من صحة العقد',
		'Notify_FICHEINTER_VALIDATE' => 'التحقق من التدخل',
		'Notify_SHIPPING_VALIDATE' => 'التحقق من صحة الشحن',
		'Notify_SHIPPING_SENTBYMAIL' => 'الشحن ترسل عن طريق البريد',
		'Notify_MEMBER_VALIDATE' => 'عضو مصدق',
		'Notify_MEMBER_SUBSCRIPTION' => 'عضو المكتتب',
		'Notify_MEMBER_RESILIATE' => 'عضو resiliated',
		'Notify_MEMBER_DELETE' => 'عضو حذف',
		'NbOfAttachedFiles' => 'عدد الملفات المرفقة / وثائق',
		'TotalSizeOfAttachedFiles' => 'اجمالى حجم الملفات المرفقة / وثائق',
		'MaxSize' => 'الحجم الأقصى',
		'AttachANewFile' => 'إرفاق ملف جديد / وثيقة',
		'LinkedObject' => 'ربط وجوه',
		'Miscellanous' => 'متفرقات',
		'NbOfActiveNotifications' => 'عدد الإخطارات',
		'PredefinedMailTest' => 'هذا هو الاختبار الإلكتروني. تكون مفصولة \ nThe سطرين من قبل حرف إرجاع.',
		'PredefinedMailTestHtml' => 'هذا هو البريد <b>الاختبار</b> (الاختبار يجب أن تكون في كلمة جريئة). <br> وتفصل بين الخطين من قبل حرف إرجاع.',
		'PredefinedMailContentSendInvoice' => 'You will find here the invoice __FACREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendInvoiceReminder' => 'We would like to warn you that the invoice  __FACREF__ seems to not being payed. So this is the invoice in attachment again, as a reminder.\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendProposal' => 'You will find here the commercial propoal __PROPREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendOrder' => 'You will find here the order __ORDERREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierOrder' => 'You will find here our order __ORDERREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierInvoice' => 'You will find here the invoice __FACREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendShipping' => 'You will find here the shipping __SHIPPINGREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendFichInter' => 'You will find here the intervention __FICHINTERREF__\n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'DemoDesc' => 'Speedealing الاتفاق هو تخطيط موارد المؤسسات وإدارة علاقات العملاء وتتكون من عدة وحدات وظيفية. وقال ان العرض يشمل جميع وحدات لا يعني اي شيء يحدث هذا أبدا. بذلك ، عرض عدة ملامح المتاحة.',
		'ChooseYourDemoProfil' => 'اختيار عرض ملف المباراة التي أنشطتك...',
		'DemoFundation' => 'أعضاء في إدارة مؤسسة',
		'DemoFundation2' => 'إدارة وأعضاء في الحساب المصرفي للمؤسسة',
		'DemoCompanyServiceOnly' => 'إدارة نشاط بيع الخدمة لحسابهم الخاص فقط',
		'DemoCompanyShopWithCashDesk' => 'تدير متجر مع مكتب النقدية',
		'DemoCompanyProductAndStocks' => 'إدارة شركة صغيرة أو متوسطة بيع المنتجات',
		'DemoCompanyAll' => 'إدارة شركة صغيرة أو متوسطة متعددة الأنشطة الرئيسية لجميع وحدات)',
		'GoToDemo' => 'الذهاب الى التجريبي',
		'CreatedBy' => 'أوجدتها ٪ ق',
		'ModifiedBy' => 'المعدلة ق ٪',
		'ValidatedBy' => 'يصادق عليها ق ٪',
		'CanceledBy' => 'ألغى به ق ٪',
		'ClosedBy' => 'أغلقت ٪ ق',
		'FileWasRemoved' => 'تم حذف الملف',
		'DirWasRemoved' => 'دليل أزيل',
		'FeatureNotYetAvailableShort' => 'متاحة في الإصدار التالي',
		'FeatureNotYetAvailable' => 'ميزة لم تتوفر بعد في هذه النسخة',
		'FeatureExperimental' => 'ميزة تجريبية. غير مستقر في هذه النسخة',
		'FeatureDevelopment' => 'تنمية الميزة. غير مستقر في هذه النسخة',
		'FeaturesSupported' => 'المزايا',
		'Width' => 'عرض',
		'Height' => 'ارتفاع',
		'Depth' => 'متعمق',
		'Top' => 'أعلى',
		'Bottom' => 'أسفل',
		'Left' => 'اليسار',
		'Right' => 'حق',
		'CalculatedWeight' => 'يحسب الوزن',
		'CalculatedVolume' => 'يحسب حجم',
		'Weight' => 'وزن',
		'TotalWeight' => 'الوزن الإجمالي',
		'WeightUnitton' => 'طن',
		'WeightUnitkg' => 'كجم',
		'WeightUnitg' => 'ز',
		'WeightUnitmg' => 'مغلم',
		'WeightUnitpound' => 'جنيه',
		'Length' => 'طول',
		'LengthUnitm' => 'م',
		'LengthUnitdm' => 'مارك ألماني',
		'LengthUnitcm' => 'الطول',
		'LengthUnitmm' => 'مم',
		'Surface' => 'منطقة',
		'SurfaceUnitm2' => 'm2',
		'SurfaceUnitdm2' => 'dm2',
		'SurfaceUnitcm2' => 'cm2',
		'SurfaceUnitmm2' => 'mm2',
		'SurfaceUnitfoot2' => 'ft2',
		'SurfaceUnitinch2' => 'in2',
		'Volume' => 'حجم',
		'TotalVolume' => 'الحجم الإجمالي',
		'VolumeUnitm3' => 'm3',
		'VolumeUnitdm3' => 'dm3',
		'VolumeUnitcm3' => 'cm3',
		'VolumeUnitmm3' => 'mm3',
		'VolumeUnitfoot3' => 'ft3',
		'VolumeUnitinch3' => 'in3',
		'VolumeUnitounce' => 'أوقية',
		'VolumeUnitlitre' => 'لتر',
		'VolumeUnitgallon' => 'غالون',
		'Size' => 'حجم',
		'SizeUnitm' => 'م',
		'SizeUnitdm' => 'مارك ألماني',
		'SizeUnitcm' => 'سم',
		'SizeUnitmm' => 'مم',
		'SizeUnitinch' => 'بوصة',
		'SizeUnitfoot' => 'قدم',
		'SizeUnitpoint' => 'point',
		'BugTracker' => 'علة تعقب',
		'SendNewPasswordDesc' => 'هذا الشكل يتيح لك طلب كلمة مرور جديدة. سيكون من إرسالها إلى عنوان البريد الإلكتروني الخاص بك. <br> التغيير لن تكون فعالة إلا بعد النقر على تأكيد الصلة داخل هذه الرسالة. <br> تحقق من بريدك الالكتروني القارئ البرمجيات.',
		'BackToLoginPage' => 'عودة إلى صفحة تسجيل الدخول',
		'AuthenticationDoesNotAllowSendNewPassword' => 'طريقة التوثيق <b>٪ ق.</b> <br> في هذا الوضع ، لا يمكن معرفة Speedealing أو تغيير كلمة السر الخاصة بك. <br> اتصل بمسؤول النظام إذا كنت تريد تغيير كلمة السر الخاصة بك.',
		'EnableGDLibraryDesc' => 'تثبيت أو تمكين ش ج مكتبة لديكم PHP لاستخدام هذا الخيار.',
		'EnablePhpAVModuleDesc' => 'كنت بحاجة إلى تثبيت وحدة متوافقة مع مكافحة الفيروسات الخاص بك. (Clamav : PHP4 - clamavlib où PHP5 - clamavlib)',
		'ProfIdShortDesc' => '<b>الأستاذ عيد ٪ ق</b> هي المعلومات التي تعتمد على طرف ثالث. <br> على سبيل المثال ، لبلد <b>ق ٪</b> انها رمز <b>٪ ق.</b>',
		'SpeedealingDemo' => 'Speedealing ERP/CRM demo',
		'StatsByNumberOfUnits' => 'إحصاءات في عدد من المنتجات / الخدمات وحدات',
		'StatsByNumberOfEntities' => 'إحصاءات في عدد من الكيانات في اشارة',
		'NumberOfProposals' => 'عددا من المقترحات بشأن 12 الشهر الماضي',
		'NumberOfCustomerOrders' => 'عدد طلبات الزبائن على 12 في الشهر الماضي',
		'NumberOfCustomerInvoices' => 'عدد من العملاء والفواتير على 12 الشهر الماضي',
		'NumberOfSupplierInvoices' => 'عدد من فواتير الموردين على 12 الشهر الماضي',
		'NumberOfUnitsProposals' => 'عدد من الوحدات على مقترحات بشأن 12 الشهر الماضي',
		'NumberOfUnitsCustomerOrders' => 'عدد من الوحدات على طلبات الزبائن على 12 في الشهر الماضي',
		'NumberOfUnitsCustomerInvoices' => 'عدد من الوحدات على فواتير العملاء على 12 الشهر الماضي',
		'NumberOfUnitsSupplierInvoices' => 'عدد من الوحدات على فواتير الموردين على 12 الشهر الماضي',
		'EMailTextInterventionValidated' => 'التدخل ٪ ق المصادق',
		'EMailTextInvoiceValidated' => 'فاتورة ٪ ق المصادق',
		'EMailTextProposalValidated' => 'وقد تم اقتراح %s التحقق من صحة.',
		'EMailTextOrderValidated' => 'وقد تم التحقق من صحة %s النظام.',
		'EMailTextOrderApproved' => 'من أجل الموافقة على ق ٪',
		'EMailTextOrderApprovedBy' => 'من أجل ٪ ق ق ٪ وافقت عليها',
		'EMailTextOrderRefused' => 'من أجل رفض ق ٪',
		'EMailTextOrderRefusedBy' => 'من أجل أن ترفض ٪ ق ق ٪',
		'ImportedWithSet' => 'استيراد مجموعة البيانات',
		'SpeedealingNotification' => 'Automatic notification',
		'ResizeDesc' => 'أدخل عرض جديدة <b>أو</b> ارتفاع جديد. وستبقى نسبة خلال تغيير حجم...',
		'NewLength' => 'عرض جديد',
		'NewHeight' => 'ارتفاع جديد',
		'NewSizeAfterCropping' => 'حجم جديد بعد الاقتصاص',
		'DefineNewAreaToPick' => 'تحديد منطقة جديدة على الصورة لاختيار (اليسار انقر على الصورة ثم اسحب حتى تصل إلى الزاوية المقابلة)',
		'CurrentInformationOnImage' => 'معلومات عن الصورة الحالية',
		'ImageEditor' => 'صورة المحرر',
		'YouReceiveMailBecauseOfNotification' => 'تلقيت هذه الرسالة لأنه قد تم إضافة البريد الإلكتروني الخاص بك إلى قائمة الأهداف التي يتعين على علم الأحداث ولا سيما في صناعة البرمجيات من %s %s.',
		'YouReceiveMailBecauseOfNotification2' => 'هذا الحدث هو ما يلي :',
		'ThisIsListOfModules' => 'هذه هي قائمة من وحدات انتقاؤه من قبل هذا الملف التجريبي (وحدات فقط الأكثر شيوعا هي واضحة في هذا العرض). تعديل هذه لديها أكثر تخصيصا التجريبي وانقر على &quot;ابدأ&quot;.',
		'ClickHere' => 'اضغط هنا',
		'UseAdvancedPerms' => 'استخدام أذونات متقدمة من بعض الوحدات',
		'FileFormat' => 'تنسيق الملف',
		'SelectAColor' => 'اختيار لون',
		'AddFiles' => 'إضافة الملفات',
		'StartUpload' => 'بدء التحميل',
		'CancelUpload' => 'إلغاء التحميل',
		'FileIsTooBig' => 'ملفات كبيرة جدا',
		'PleaseBePatient' => 'Please be patient...',
		////////// Calendar common //////////
		'AddCalendarEntry' => 'إضافة الدخول في التقويم ق ٪',
		'NewCompanyToSpeedealing' => 'Company %s added into Speedealing',
		'ContractValidatedInSpeedealing' => 'Contract %s validated in Speedealing',
		'ContractCanceledInSpeedealing' => 'Contract %s canceled in Speedealing',
		'ContractClosedInSpeedealing' => 'Contract %s closed in Speedealing',
		'PropalClosedSignedInSpeedealing' => 'Proposal %s signed in Speedealing',
		'PropalClosedRefusedInSpeedealing' => 'Proposal %s refused in Speedealing',
		'PropalValidatedInSpeedealing' => 'Proposal %s validated in Speedealing',
		'InvoiceValidatedInSpeedealing' => 'Invoice %s validated in Speedealing',
		'InvoicePaidInSpeedealing' => 'Invoice %s changed to paid in Speedealing',
		'InvoiceCanceledInSpeedealing' => 'Invoice %s canceled in Speedealing',
		'PaymentDoneInSpeedealing' => 'Payment %s done in Speedealing',
		'CustomerPaymentDoneInSpeedealing' => 'Customer payment %s done in Speedealing',
		'SupplierPaymentDoneInSpeedealing' => 'Supplier payment %s done in Speedealing',
		'MemberValidatedInSpeedealing' => 'Member %s validated in Speedealing',
		'MemberResiliatedInSpeedealing' => 'Member %s resiliated in Speedealing',
		'MemberDeletedInSpeedealing' => 'Member %s deleted from Speedealing',
		'MemberSubscriptionAddedInSpeedealing' => 'Subscription for member %s added in Speedealing',
		'ShipmentValidatedInSpeedealing' => 'Shipment %s validated in Speedealing',
		////////// Export //////////
		'Export' => 'تصدير',
		'ExportsArea' => 'صادرات المنطقة',
		'AvailableFormats' => 'الأشكال المتاحة',
		'LibraryUsed' => 'وتستخدم Librairy',
		'LibraryVersion' => 'النسخة',
		'ExportableDatas' => 'تصدير datas',
		'NoExportableData' => 'ليس للتصدير البيانات (أي وحدات للتصدير مع تحميل البيانات ، ومفقود أذونات)',
		'ToExport' => 'الصادرات',
		'NewExport' => 'تصديرية جديدة',
		////////// External sites //////////
		'ExternalSites' => 'المواقع الخارجية'
);
?>