<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'بطاقة مخزن',
		'Warehouse' => 'مخزن',
		'NewWarehouse' => 'المستودع الجديد / بورصة المنطقة',
		'MenuNewWarehouse' => 'مستودع جديد',
		'WarehouseOpened' => 'فتح مخزن',
		'WarehouseClosed' => 'مخزن مغلق',
		'WarehouseSource' => 'مصدر مخزن',
		'WarehouseTarget' => 'الهدف مخزن',
		'ValidateSending' => 'حذف ارسال',
		'CancelSending' => 'الغاء ارسال',
		'DeleteSending' => 'حذف ارسال',
		'Stock' => 'الأسهم',
		'Stocks' => 'الاسهم',
		'Movement' => 'الحركة',
		'Movements' => 'حركات',
		'ErrorWarehouseRefRequired' => 'مستودع الاشارة اسم مطلوب',
		'ErrorWarehouseLabelRequired' => 'مستودع العلامة مطلوبة',
		'CorrectStock' => 'تصحيح الأوراق المالية',
		'ListOfWarehouses' => 'لائحة المخازن',
		'ListOfStockMovements' => 'قائمة الحركات الأسهم',
		'StocksArea' => 'مخزون المنطقة',
		'Location' => 'عوضا عن',
		'LocationSummary' => 'باختصار اسم الموقع',
		'NumberOfProducts' => 'العدد الإجمالي للمنتجات',
		'LastMovement' => 'الماضي حركة',
		'LastMovements' => 'التحركات الأخيرة',
		'Units' => 'الوحدات',
		'Unit' => 'وحدة',
		'StockCorrection' => 'تصحيح الأوراق المالية',
		'StockMovement' => 'نقل',
		'StockMovements' => 'تحويلات الأوراق المالية',
		'NumberOfUnit' => 'عدد الوحدات',
		'TotalStock' => 'إجمالي المخزون',
		'StockTooLow' => 'الاسهم منخفضة جدا',
		'EnhancedValue' => 'القيمة',
		'PMPValue' => 'المتوسط المرجح لسعر',
		'PMPValueShort' => 'الواب',
		'EnhancedValueOfWarehouses' => 'قيمة المستودعات',
		'UserWarehouseAutoCreate' => 'خلق مخزون تلقائيا عند إنشاء مستخدم',
		'QtyDispatched' => 'ارسال كمية',
		'OrderDispatch' => 'ارسال الأسهم',
		'RuleForStockManagementDecrease' => 'قاعدة لإدارة المخزون النقصان',
		'RuleForStockManagementIncrease' => 'قاعدة لإدارة المخزون وزيادة',
		'StockLimitShort' => 'الحد',
		'StockLimit' => 'الأسهم للحد من التنبيهات',
		'PhysicalStock' => 'المخزون المادي',
		'RealStock' => 'الحقيقية للاسهم',
		'TheoreticalStock' => 'Therocial الأسهم',
		'VirtualStock' => 'الأسهم الافتراضية',
		'MininumStock' => 'الحد الأدنى للرصيد',
		'StockUp' => 'تخزين',
		'MininumStockShort' => 'الأسهم دقيقة',
		'StockUpShort' => 'تخزين',
		'IdWarehouse' => 'معرف مخزن',
		'DescWareHouse' => 'وصف المخزن',
		'LieuWareHouse' => 'المكان مخزن',
		'WarehousesAndProducts' => 'والمستودعات والمنتجات',
		'AverageUnitPricePMPShort' => 'متوسط أسعار المدخلات',
		'AverageUnitPricePMP' => 'متوسط أسعار المدخلات',
		'EstimatedStockValueShort' => 'وتقدر قيمة المخزون',
		'EstimatedStockValue' => 'وتقدر قيمة المخزون',
		'DeStockOnShipment' => 'انخفاض الاسهم الحقيقي على شحنة المصادقة (مستحسن)',
		'StockDiffPhysicTeoric' => 'والسبب في الاختلاف المخزون المادي والنظرية',
		'WarehouseEdit' => 'تعديل مستودع',
		'ReStockOnDispatchOrder' => 'زيادة مخزونات دليل حقيقي على إيفاد في المستودعات ، وبعد تلقي أمر المورد',
		'OrderStatusNotReadyToDispatch' => 'أمر لم يتم بعد أو لا أكثر من ذلك الوضع الذي يسمح بإرسال من المنتجات في مخازن المخزون.',
		'NoPredefinedProductToDispatch' => 'لا توجد منتجات محددة سلفا لهذا الكائن. لذلك لا إرسال في المخزون المطلوب.',
		'DispatchVerb' => 'إيفاد',
		'DeleteAWarehouse' => 'حذف مستودع',
		'ConfirmDeleteWarehouse' => 'هل أنت متأكد أنك تريد حذف <b>%s</b> مستودع؟',
		'PersonalStock' => '%s طبيعة الشخصية',
		'ThisWarehouseIsPersonalStock' => 'هذا يمثل مستودع للطبيعة الشخصية لل%s %s',
		'DeStockOnBill' => 'خفض مخزونات حقيقية على فواتير الزبائن / الائتمان التحقق من صحة الملاحظات',
		'DeStockOnValidateOrder' => 'خفض مخزونات حقيقية على التحقق من صحة أوامر العملاء',
		'ReStockOnBill' => 'زيادة المخزون الحقيقي في فواتير الموردين / الائتمان التحقق من صحة الملاحظات',
		'ReStockOnValidateOrder' => 'زيادة مخزونات حقيقية على استحسان أوامر الموردين',
		'SellPriceMin' => 'بيع سعر الوحدة',
		'EstimatedStockValueSellShort' => 'قيمة لبيع',
		'EstimatedStockValueSell' => 'قيمة لبيع',
		'SelectWarehouseForStockDecrease' => 'اختيار مستودع لاستخدامها لانخفاض الأسهم',
		'SelectWarehouseForStockIncrease' => 'اختيار مستودع لاستخدامها لزيادة المخزون',
);
?>