<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$banks = array(
		'CHARSET' => 'UTF-8',
		'Bank' => 'Banka',
		'Banks' => 'Bankalar',
		'MenuBankCash' => 'Banka/Kasa',
		'MenuSetupBank' => 'Banka/Kasa kurulumu',
		'BankName' => 'Banka adı',
		'FinancialAccount' => 'Hesap',
		'FinancialAccounts' => 'Hesaplar',
		'BankAccount' => 'Banka hesabı',
		'BankAccounts' => 'Banka hesapları',
		'AccountRef' => 'Finansal hesap ref',
		'AccountLabel' => 'Finansal hesap etiket',
		'CashAccount' => 'Kasa hesabı',
		'CashAccounts' => 'Kasa hesapları',
		'MainAccount' => 'Ana hesap',
		'CurrentAccount' => 'Cari hesap',
		'CurrentAccounts' => 'Cari hesaplar',
		'SavingAccount' => 'Tasarruf hesabı',
		'SavingAccounts' => 'Tasarruf hesapları',
		'ErrorBankLabelAlreadyExists' => 'Finansal hesap etiketi zaten var',
		'BankBalance' => 'Bakiye',
		'BalanceMinimalAllowed' => 'İzin verilen enaz bakiye',
		'BalanceMinimalDesired' => 'İstenen enaz bakiye',
		'InitialBankBalance' => 'Açılış bakiyesi',
		'EndBankBalance' => 'Kapanış bakiyesi',
		'CurrentBalance' => 'Güncel bakiye',
		'FutureBalance' => 'Gelecek bakiye',
		'ShowAllTimeBalance' => 'Bakiyeyi başlangıçtan göster',
		'Reconciliation' => 'Uzlaşma',
		'RIB' => 'Banka Hesap Numarası',
		'IBAN' => 'IBAN numarası',
		'BIC' => 'BIC/SWIFT numarası',
		'StandingOrders' => 'Ödeme talimatları',
		'StandingOrder' => 'Ödeme talimatı',
		'Withdrawals' => 'Para çekmeler',
		'Withdrawal' => 'Para çekme',
		'AccountStatement' => 'Hesap özeti',
		'AccountStatementShort' => 'Özet',
		'AccountStatements' => 'Hesap özetleri',
		'LastAccountStatements' => 'Son hesap özetleri',
		'Rapprochement' => 'Uzlaşma',
		'IOMonthlyReporting' => 'Aylık raporlama',
		'BankAccountDomiciliation' => 'Hesap adresi',
		'BankAccountCountry' => 'Hesap ülkesi',
		'BankAccountOwner' => 'Hesap sahibi adı',
		'BankAccountOwnerAddress' => 'Hesap sahibi adresi',
		'RIBControlError' => 'Değerlerin bütünlük denetimi başarısız. Bu demektir ki; bu hesap numarasına ait bilgiler tam değil ya da yanlıştır (ülkeyi, numaraları ve IBAN’ı kontrol edin).',
		'CreateAccount' => 'Hesap oluştur',
		'NewAccount' => 'Yeni hesap',
		'NewBankAccount' => 'Yeni bir banka hesabı',
		'NewFinancialAccount' => 'Yeni finansal hesap',
		'MenuNewFinancialAccount' => 'Yeni finansal hesap',
		'NewCurrentAccount' => 'Yeni cari hesap',
		'NewSavingAccount' => 'Yeni tasarruf hesabı',
		'NewCashAccount' => 'Yeni kasa hesabı',
		'EditFinancialAccount' => 'Hesap düzenle',
		'AccountSetup' => 'Finansal hesaplar kurulumu',
		'SearchBankMovement' => 'Banka hareketi ara',
		'Debts' => 'Borçlar',
		'LabelBankCashAccount' => 'Banka veya kasa etiketi',
		'AccountType' => 'Hesap türü',
		'BankType0' => 'Tasarruf hesabı',
		'BankType1' => 'Cari hesap',
		'BankType2' => 'Kasa hesabı',
		'IfBankAccount' => 'Eğer banka hesabıysa',
		'AccountsArea' => 'Hesaplar alanı',
		'AccountCard' => 'Hesap kartı',
		'DeleteAccount' => 'Hesap sil',
		'ConfirmDeleteAccount' => 'Bu hesabı silmek istediğinizden emin misiniz?',
		'Account' => 'Hesap',
		'ByCategories' => 'Kategorilere göre',
		'ByRubriques' => 'Kategorilere göre',
		'BankTransactionByCategories' => 'Kategorilere göre banka işlemleri',
		'BankTransactionForCategory' => 'Kategori <b>%s</b> için banka işlemleri',
		'RemoveFromRubrique' => 'Kategori bağlantısını kaldır',
		'RemoveFromRubriqueConfirm' => 'İşlem ve kategori arasındaki bağlantıyı kaldırmak istediğinizden emin misiniz?',
		'ListBankTransactions' => 'Banka işlemleri listesi',
		'IdTransaction' => 'İşlem Kimliği',
		'BankTransactions' => 'Banka işlemleri',
		'SearchTransaction' => 'İşlem ara',
		'ListTransactions' => 'İşlemleri listele',
		'ListTransactionsByCategory' => 'İşlem/kategori listele',
		'TransactionsToConciliate' => 'Uzlaştırılacak işlemler',
		'Conciliable' => 'Uzlaştırılabilir',
		'Conciliate' => 'Uzlaştır',
		'Conciliation' => 'Uzlaşma',
		'ConciliationForAccount' => 'Bu hesabı uzlaştır',
		'IncludeClosedAccount' => 'Kapalı hesapları içer',
		'OnlyOpenedAccount' => 'Sadece açık hesapları',
		'AccountToCredit' => 'Alacaklandırılan hesap',
		'AccountToDebit' => 'Borçlandırılan hesap',
		'DisableConciliation' => 'Bu hesap için uzlaşma özelliği engelle',
		'ConciliationDisabled' => 'Uzlaşma özelliği engelli',
		'StatusAccountOpened' => 'Açık',
		'StatusAccountClosed' => 'Kapalı',
		'AccountIdShort' => 'Numarası',
		'EditBankRecord' => 'Kayıt düzenle',
		'LineRecord' => 'İşlem',
		'AddBankRecord' => 'İşlem ekle',
		'AddBankRecordLong' => 'Elle işlem ekle',
		'ConciliatedBy' => 'Tarafından uzlaştırılmış',
		'DateConciliating' => 'Uzlaştırma tarihi',
		'BankLineConciliated' => 'İşlem uzlaştırılmış',
		'CustomerInvoicePayment' => 'Müşteri ödemesi',
		'SupplierInvoicePayment' => 'Tedarikçi ödemesi',
		'WithdrawalPayment' => 'Para çekme ödemesi',
		'SocialContributionPayment' => 'Sosyal güvenlik primi ödemesi',
		'FinancialAccountJournal' => 'Finansal hesap günlüğü',
		'BankTransfer' => 'Banka havalesi',
		'BankTransfers' => 'Banka havaleleri',
		'TransferDesc' => 'Bir hesaptan başka bir hesaba transfer sırasında Speedealing iki kayıt yazacaktır (aynı tutarda olmak üzere kaynak hesaba borç ve hedef hesaba alacak. Bu işlem için aynı etiket ve tarih kullanılacaktır).',
		'TransferFrom' => 'Kimden',
		'TransferTo' => 'Kime',
		'TransferFromToDone' => '<b>%s</b> den <b>%s</b> nin <b>%s</b> %s ne bir transfer kaydedildi.',
		'CheckTransmitter' => 'Veren',
		'ValidateCheckReceipt' => 'Bu çek makbuzunı doğruluyor musunuz?',
		'ConfirmValidateCheckReceipt' => 'Bu çek makbuzunu doğrulamak istediğinizden emin misiniz, bu işlem yapıldıktan sonra değiştirme olanağı yoktur?',
		'DeleteCheckReceipt' => 'Bu çek makbuzu silinsin mi?',
		'ConfirmDeleteCheckReceipt' => 'Bu çek makbuzunu silmek istediğinizden emin misiniz?',
		'BankChecks' => 'Banka çekleri',
		'BankChecksToReceipt' => 'Ödeme için bekleyen çekler',
		'ShowCheckReceipt' => 'Çek tahsilat makbuzunu göster',
		'NumberOfCheques' => 'Çek sayısı',
		'DeleteTransaction' => 'İşlem sil',
		'ConfirmDeleteTransaction' => 'Bu işlemi silmek istediğinizden emin misiniz?',
		'ThisWillAlsoDeleteBankRecord' => 'Bu oluşturulan banka işlemlerini de silecektir.',
		'BankMovements' => 'Hareketler',
		'CashBudget' => 'Nakit bütçesi',
		'PlannedTransactions' => 'Planlanan işlemler',
		'Graph' => 'Grafik',
		'ExportDataset_banque_1' => 'Banka işlemleri ve hesap özeti',
		'TransactionOnTheOtherAccount' => 'Diğer hesaptaki işlemler',
		'TransactionWithOtherAccount' => 'Hesap transferi',
		'PaymentNumberUpdateSucceeded' => 'Ödeme numarası başarıyla güncellendi',
		'PaymentNumberUpdateFailed' => 'Ödeme numarası güncellenemedi',
		'PaymentDateUpdateSucceeded' => 'Ödeme tarihi başarıyla güncellendi',
		'PaymentDateUpdateFailed' => 'Ödeme tarihi güncellenemedi',
		'Transactions' => 'Transactions',
		'BankTransactionLine' => 'Banka işlemi',
		'AllAccounts' => 'Tüm banka/kasa hesapları',
		'BackToAccount' => 'Hesaba geri dön',
		'ShowAllAccounts' => 'Tüm hesaplar için göster',
		'FutureTransaction' => 'Gelecekteki işlem. Hiçbir şekilde uzlaştırılamaz.',
		'SelectChequeTransactionAndGenerate' => 'Çek tahsilat makbuzunun içereceği çekleri seç/süz ve “Oluştur” a tıkla.',
		'InputReceiptNumber' => 'Choose the bank statement related with the conciliation. Use a sortable numeric value (such as, YYYYMM)',
		'EventualyAddCategory' => 'Eventually, specify a category in which to classify the records',
		'ToConciliate' => 'To conciliate?',
		'ThenCheckLinesAndConciliate' => 'Then, check the lines present in the bank statement and click'
);
?>