<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Kategori',
		'Categories' => 'Kategoriler',
		'Rubrique' => 'Kategori',
		'Rubriques' => 'Kategoriler',
		'categories' => 'kategoriler',
		'TheCategorie' => 'Kategori',
		'NoCategoryYet' => 'Bu türde oluşturulan Kategori yok',
		'In' => 'İçinde',
		'AddIn' => 'Ekle',
		'modify' => 'değiştir',
		'Classify' => 'Sınıflandır',
		'CategoriesArea' => 'Kategoriler alanı',
		'ProductsCategoriesArea' => 'Ürün/Hizmet kategorileri alanı',
		'SuppliersCategoriesArea' => 'Tedarikçi kategorileri alanı',
		'CustomersCategoriesArea' => 'Müşteri kategorileri alanı',
		'ThirdPartyCategoriesArea' => 'Üçüncü parti kategorileri alanı',
		'MembersCategoriesArea' => 'Üye kategorileri alanı',
		'MainCats' => 'Ana kategoriler',
		'SubCats' => 'Alt kategoriler',
		'CatStatistics' => 'İstatistikler',
		'CatList' => 'Kategori Listesi',
		'AllCats' => 'Tüm kategoriler',
		'ViewCat' => 'Kategori görüntüle',
		'NewCat' => 'Kategori ekle',
		'NewCategory' => 'Yeni kategori',
		'ModifCat' => 'Kategori değiştir',
		'CatCreated' => 'Kategori oluşturuldu',
		'CreateCat' => 'Kategori oluştur',
		'CreateThisCat' => 'Bu kategoriyi oluştur',
		'ValidateFields' => 'Doğrulama alanları',
		'NoSubCat' => 'Alt kategori yok.',
		'SubCatOf' => 'Alt kategori',
		'FoundCats' => 'Kategoriler bulundu',
		'FoundCatsForName' => 'Bu ad için kategoriler bulundu:',
		'FoundSubCatsIn' => 'Kategori içinde alt kategoriler bulundu',
		'ErrSameCatSelected' => 'Birkaç kez aynı kategoriyi seçtiniz',
		'ErrForgotCat' => 'Kategori seçmeyi unuttunuz',
		'ErrForgotField' => 'Alanlara bilgi girmeyi unuttunuz',
		'ErrCatAlreadyExists' => 'Bu ad zaten kullanılıyor',
		'AddProductToCat' => 'Bu ürünü bir kategoriye mi ekleyeceksiniz?',
		'ImpossibleAddCat' => 'Kategori eklemek olanaksız',
		'ImpossibleAssociateCategory' => 'Kategoriyle ilişkilendirmek olanaksız',
		'WasAddedSuccessfully' => '<b>%s</b> başarıyla eklendi.',
		'ObjectAlreadyLinkedToCategory' => 'Öğe zaten bu kategoriye bağlıdır.',
		'CategorySuccessfullyCreated' => 'Bu kategoriye %s başarı ile eklendi.',
		'ProductIsInCategories' => 'Ürün/hizmet aşağıdaki kategorilere aittir',
		'SupplierIsInCategories' => 'Üçüncü parti aşağıdaki tedarikçi kategorilerine aittir',
		'CompanyIsInCustomersCategories' => 'Bu üçüncü parti aşağıdaki müşteri/aday kategorilerine aittir',
		'CompanyIsInSuppliersCategories' => 'Bu üçüncü parti aşağıdaki tedarikçi kategorilerine aittir',
		'MemberIsInCategories' => 'Bu üye, aşağıdaki üye kategorilerine aittir',
		'ProductHasNoCategory' => 'Bu ürün/hizmet herhangi bir kategoride yoktur',
		'SupplierHasNoCategory' => 'Bu tedarikçi herhangi bir kategoride yoktur',
		'CompanyHasNoCategory' => 'Bu firma herhangi bir kategoride yoktur',
		'MemberHasNoCategory' => 'Bu üye herhangi bir kategoride yoktur',
		'ClassifyInCategory' => 'Kategoride Sınıflandır',
		'NoneCategory' => 'Hiçbiri',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Bu kategori zaten bu ilgi ile var',
		'ReturnInProduct' => 'Ürün/hizmet kartına geri dön',
		'ReturnInSupplier' => 'Tedarikçi kartına geri dön',
		'ReturnInCompany' => 'Müşteri/aday kartına geri dön',
		'ContentsVisibleByAll' => 'İçerik herkes tarafından görülebilir',
		'ContentsVisibleByAllShort' => 'Içerik herkes tarafından görülebilir',
		'ContentsNotVisibleByAllShort' => 'İçerik herkes tarafından görülemez',
		'CategoriesTree' => 'Kategori ağacı',
		'DeleteCategory' => 'Kategori sil',
		'ConfirmDeleteCategory' => 'Bu kategoriyi silmek istediğinizden emin misiniz?',
		'RemoveFromCategory' => 'Kategori bağlantısını kaldır',
		'RemoveFromCategoryConfirm' => 'İşlem ile kategori arasındaki bağlantıyı kaldırmak istediğinizden emin misiniz?',
		'NoCategoriesDefined' => 'Tanımlı kategori yok',
		'SuppliersCategoryShort' => 'Tedarikçi kategorisi',
		'CustomersCategoryShort' => 'Müşteri kategorisi',
		'ProductsCategoryShort' => 'Ürün kategorisi',
		'MembersCategoryShort' => 'Üye kategorisi',
		'SuppliersCategoriesShort' => 'Tedarikçi kategorileri',
		'CustomersCategoriesShort' => 'Müşteri kategorileri',
		'CustomersProspectsCategoriesShort' => 'Müşt./aday kategorileri',
		'ProductsCategoriesShort' => 'Ürün kategorileri',
		'MembersCategoriesShort' => 'Üye kategorileri',
		'ThisCategoryHasNoProduct' => 'Bu kategori herhangi bir ürün içermiyor.',
		'ThisCategoryHasNoSupplier' => 'Bu kategori herhangi bir tedarikçi içermiyor.',
		'ThisCategoryHasNoCustomer' => 'Bu kategori herhangi bir müşteri içermiyor.',
		'ThisCategoryHasNoMember' => 'Bu kategori herhangi bir üye içermiyor.',
		'AssignedToCustomer' => 'Bir müşteriye atanmış',
		'AssignedToTheCustomer' => 'Müşteriye atanmış',
		'InternalCategory' => 'İç kategori',
		'CategoryContents' => 'Kategori içeriği',
		'CategId' => 'Kategori kimliği',
		'CatSupList' => 'Tedarikçi kategorileri listesi',
		'CatCusList' => 'Müşteri/aday kategorileri listesi',
		'CatProdList' => 'Ürün kategorileri Listesi',
		'CatMemberList' => 'Üye kategorileri Listesi',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>