<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Ticari',
		'CommercialArea' => 'Ticari alan',
		'CommercialCard' => 'Ticari kart',
		'CustomerArea' => 'Müşteriler alanı',
		'Customer' => 'Müşteri',
		'Customers' => 'Müşteriler',
		'Prospect' => 'Aday',
		'Prospects' => 'Adaylar',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Bir eylem/görev sil',
		'NewAction' => 'Yeni eylem/görev',
		'AddAction' => 'Eylem/görev ekle',
		'AddAnAction' => 'Bir eylem/görev ekle',
		'AddActionRendezVous' => 'Bir randevu eylemi ekle',
		'Rendez-Vous' => 'Rendevu',
		'ConfirmDeleteAction' => 'Bu eylemi/görevi silmek istediğinizden emin misiniz?',
		'CardAction' => 'Eylem kartı',
		'PercentDone' => 'Tamamlanma oranı',
		'ActionOnCompany' => 'Firma için görev',
		'ActionOnContact' => 'Kişi için görev',
		'TaskRDV' => 'Toplantılar',
		'TaskRDVWith' => '%s ile toplantı',
		'ShowTask' => 'Görev göster',
		'ShowAction' => 'Eylem göster',
		'ActionsReport' => 'Eylem raporu',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Satış temsilcisi',
		'SalesRepresentatives' => 'Satış temsilcileri',
		'SalesRepresentativeFollowUp' => 'Satış temsilcisi (takipçi)',
		'SalesRepresentativeSignature' => 'Satış temsilcisi (imza yetkilisi)',
		'CommercialInterlocutor' => 'Ticari muhatap',
		'ErrorWrongCode' => 'Yanlış kod',
		'NoSalesRepresentativeAffected' => 'Etkilenen özel bir satış temsilcisi yok',
		'ShowCustomer' => 'Müşteri göster',
		'ShowProspect' => 'Aday göster',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Adaylar listesi',
		'ListOfCustomers' => 'Müşteri listesi',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'Tamamlanan son %s görev',
		'LastRecordedTasks' => 'Son kaydedilen görevler',
		'LastActionsToDo' => 'Tamamlanan son %s en eski işlem',
		'DoneAndToDoActionsFor' => '%s için tamamlanan ve yapılacak eylemler',
		'DoneAndToDoActions' => 'Tamamlanan ve yapılacak görevler',
		'DoneActions' => 'Tamamlanan eylemler',
		'DoneActionsFor' => '%s için tamamlanan eylemler',
		'ToDoActions' => 'Tamamlanmamış eylemler',
		'ToDoActionsFor' => '%s için tamalanmamış eylemler',
		'SendPropalRef' => '%s ticari teklifini gönder',
		'SendOrderRef' => '% siparişini gönder',
		'StatusNotApplicable' => 'Uygulanamaz',
		'StatusActionToDo' => 'Yapılacaklar',
		'StatusActionDone' => 'Tamamla',
		'StatusActionInProcess' => 'İşlemde',
		'MyActionsAsked' => 'Kayıt ettiğim eylemler',
		'MyActionsToDo' => 'Yapacağım eylemler',
		'MyActionsDone' => 'Beni etkileyen eylemler',
		'TasksHistoryForThisContact' => 'Bu kişi için eylemler',
		'LastProspectDoNotContact' => 'Görüşülmeyecek',
		'LastProspectNeverContacted' => 'Hiç görüşülmedi',
		'LastProspectToContact' => 'İletişime geçilecek',
		'LastProspectContactInProcess' => 'Kişi işlemde',
		'LastProspectContactDone' => 'Görüşme yapıldı',
		'DateActionPlanned' => 'Planlanan eylem tarihi',
		'DateActionDone' => 'Eylemin yapıldığı tarih',
		'ActionAskedBy' => 'Eylemi sunan',
		'ActionAffectedTo' => 'Eylemdenn etkilenen',
		'ActionDoneBy' => 'Eylemi yapan',
		'ActionUserAsk' => 'Raporlayan',
		'ErrorStatusCantBeZeroIfStarted' => 'Eğer <b>Yapıldığı tarih</b> alanı doluysa, eylem başlamıştır (veya bitmiştir),  bu durumda \'<b>Durum</b>\' alanı 0%% olamaz.',
		'ActionAC_TEL' => 'Telefon',
		'ActionAC_FAX' => 'Faks gönder',
		'ActionAC_PROP' => 'Teklifi postayla gönder',
		'ActionAC_EMAIL' => 'Eposta gönder',
		'ActionAC_RDV' => 'Toplantılar',
		'ActionAC_FAC' => 'Müşteri faturasını postayla gönder gönder',
		'ActionAC_REL' => 'Müşteri faturasını postayla gönder (hatırlatma)',
		'ActionAC_CLO' => 'Kapat',
		'ActionAC_EMAILING' => 'Toplu e-posta gönder',
		'ActionAC_COM' => 'Müşteri siparişini postayla gönder',
		'ActionAC_SHIP' => 'Sevkiyatı postayla gönder',
		'ActionAC_SUP_ORD' => 'Tedarikçi siparişini postayla gönder',
		'ActionAC_SUP_INV' => 'Tedarikçi faturasını postayla gönder',
		'ActionAC_OTH' => 'Diğer',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Aday durumu',
		'DraftPropals' => 'Taslak ticari teklifler',
		'SearchPropal' => 'Bir ticari teklif ara'
);
?>