<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$compta = array(
		'CHARSET' => 'UTF-8',
		'Accountancy' => 'Muhasebe',
		'AccountancyCard' => 'Muhasebe kartı',
		'Treasury' => 'Maliye',
		'MenuFinancial' => 'Finansal',
		'TaxModuleSetupToModifyRules' => 'Hesaplama kurallarını değiştirmek için <a href="%s">modül kurulumu</a> na git',
		'OptionMode' => 'Muhasebe seçeneği',
		'OptionModeTrue' => 'Gelir-Gider seçeneği',
		'OptionModeVirtual' => 'Alacak-Borç seçeneği',
		'OptionModeTrueDesc' => 'Bu bağlamda, ciro ödemeler üzerinden (ödeme tarihi) hesaplanır. \nRakamların geçerliliği, yalnızca; eğer kayıtların ilgili hesapların faturaları üzerinden girişleri/çıkışları irdelenmişse sağlanır.',
		'OptionModeVirtualDesc' => 'Bu bağlamda, ciro faturalar üzerinden (doğrulama tarihi) hesaplanır.  Bu faturalar işlendiğinde, ödenmiş ya da ödenmemiş olmasına bakılmadan, ciro listesinde görüntülenir.',
		'FeatureIsSupportedInInOutModeOnly' => 'Özellik yalnızca ALACAKLAR-BORÇLAR muhasebe modunda geçerlidir (Muhasebe modülü yapılandırmasına bak)',
		'VATReportBuildWithOptionDefinedInModule' => 'Burada gösterilen tutarlar vergi modülü kurulumu tarafından tanımlanan kurallar kullanılarak hesaplanır.',
		'Param' => 'Kurulum',
		'RemainingAmountPayment' => 'Kalan ödeme tutarı:',
		'AmountToBeCharged' => 'Ödenecek toplam tutar:',
		'AccountsGeneral' => 'Hesaplar',
		'Account' => 'Hesap',
		'Accounts' => 'Hesaplar',
		'Accountparent' => 'Account parent',
		'Accountsparent' => 'Accounts parent',
		'BillsForSuppliers' => 'Tedarikçi faturaları',
		'Income' => 'Gelir',
		'Outcome' => 'Gider',
		'ReportInOut' => 'Gelir/Gider',
		'ReportTurnover' => 'Ciro',
		'PaymentsNotLinkedToInvoice' => 'Herhangi bir faturaya bağlı olmayan ödemeler, herhangi bir üçüncü partiye de bağlı değildir',
		'PaymentsNotLinkedToUser' => 'Herhangi bir kullanıcıya bağlı olmayan ödemeler',
		'Profit' => 'Kar',
		'Balance' => 'Bakiye',
		'Debit' => 'Borç',
		'Credit' => 'Alacak',
		'Withdrawal' => 'Para çekme',
		'Withdrawals' => 'Para çekmeler',
		'AmountHTVATRealReceived' => 'Net alınan',
		'AmountHTVATRealPaid' => 'Net ödenen',
		'VATToPay' => 'KDV satışlar',
		'VATReceived' => 'KDV alınan',
		'VATToCollect' => 'KDV satınalımlar',
		'VATSummary' => 'KDV bakiyesi',
		'LT2SummaryES' => 'IRPF bakiyesi',
		'VATPaid' => 'KDV ödenmiş',
		'LT2PaidES' => 'IRPF ödenmiş',
		'LT2CustomerES' => 'IRPF satışlar',
		'LT2SupplierES' => 'IRPF satınalımlar',
		'VATCollected' => 'KDV alınan',
		'ToPay' => 'Ödenecek',
		'ToGet' => 'Geri alınacak',
		'TaxAndDividendsArea' => 'Vergi, sosyal güvenlik primleri ve kar payları alanı',
		'SocialContribution' => 'Sosyal güvenlik primi',
		'SocialContributions' => 'Sosyal güvenlik primleri',
		'MenuTaxAndDividends' => 'Vergiler ve kar payları',
		'MenuSocialContributions' => 'Sosyal güvenlik primleri',
		'MenuNewSocialContribution' => 'Yeni katkı payı',
		'NewSocialContribution' => 'Yeni sosyal güvenlik primleri',
		'ContributionsToPay' => 'Ödenecek primler',
		'AccountancyTreasuryArea' => 'Muhasebe/Maliye alanı',
		'AccountancySetup' => 'Muhasebe kurulumu',
		'NewPayment' => 'Yeni ödeme',
		'Payments' => 'Ödemeler',
		'PaymentCustomerInvoice' => 'Müşteri fatura ödemesi',
		'PaymentSupplierInvoice' => 'Tedarikçi fatura ödemesi',
		'PaymentSocialContribution' => 'Sosyal güvenlik primi ödeme',
		'PaymentVat' => 'KDV ödeme',
		'ListPayment' => 'Ödemeler listesi',
		'ListOfPayments' => 'Ödemeler listesi',
		'ListOfCustomerPayments' => 'Müşteri ödemeleri listesi',
		'ListOfSupplierPayments' => 'Tedarikçi ödemeleri listesi',
		'DatePayment' => 'Ödeme tarihi',
		'NewVATPayment' => 'Yeni KDV ödemesi',
		'newLT2PaymentES' => 'Yeni IRPF ödemesi',
		'LT2PaymentES' => 'IRPF Ödemesi',
		'LT2PaymentsES' => 'IRPF Ödemeleri',
		'VATPayment' => 'KDV Ödemesi',
		'VATPayments' => 'KDV Ödemeleri',
		'SocialContributionsPayments' => 'Sosyal güvenlik primi ödemeleri',
		'ShowVatPayment' => 'KDV ödemesi göster',
		'TotalToPay' => 'Ödenecek toplam',
		'TotalVATReceived' => 'Alınan toplam KDV',
		'CustomerAccountancyCode' => 'Müşteri muhasebe kodu',
		'SupplierAccountancyCode' => 'Tedarikçi muhasebe kodu',
		'AlreadyPaid' => 'Zaten ödenmiş',
		'AccountNumberShort' => 'Hesap numarası',
		'AccountNumber' => 'Hesap numarası',
		'NewAccount' => 'Yeni hesap',
		'SalesTurnover' => 'Satış cirosu',
		'ByThirdParties' => 'Üçüncü partiye göre',
		'ByUserAuthorOfInvoice' => 'Faturayı yazana göre',
		'AccountancyExport' => 'Muhasebe dışaaktarımı',
		'ErrorWrongAccountancyCodeForCompany' => '%s için hatalı müşteri muhasebe kodu',
		'SuppliersProductsSellSalesTurnover' => 'Tedarikçi ürünlerinin satışından oluşan ciro.',
		'CheckReceipt' => 'Çek hesabı',
		'CheckReceiptShort' => 'Çek hesabı',
		'NewCheckReceipt' => 'Yeni indirim',
		'NewCheckDeposit' => 'Yeni bir çek hesabı',
		'NewCheckDepositOn' => 'Bu hesap için makbuz oluştur: %s',
		'NoWaitingChecks' => 'Hesaba işlenmeyi bekleyen çek yok.',
		'DateChequeReceived' => 'Çek giriş tarihi',
		'NbOfCheques' => 'Çek sayısı',
		'PaySocialContribution' => 'Bir sosyal güvenlik primi öde',
		'ConfirmPaySocialContribution' => 'Bu sosyal güvenlik primini ödendi olarak sınıflandırmak istediğinizden emin misiniz?',
		'DeleteSocialContribution' => 'Sosyal güvenlik primi sil',
		'ConfirmDeleteSocialContribution' => 'Bu sosyal güvenlik primini silmek istediğinizden emin misiniz?',
		'ExportDataset_tax_1' => 'Sosyal güvenlik primleri ve ödemeleri',
		'AnnualSummaryDueDebtMode' => 'Gelir ve gider bilançosu, yıllık özet, <b>%sAlacaklar-Borçlar%s</b> söz konusu <b>Taahhüt hesabı</b> modu.',
		'AnnualSummaryInputOutputMode' => 'Gelir ve gider bilançosu, yıllık özet, <b>%sGelirler-Giderler%s</b> söz konusu <b>kasa hesabı</b> modu.',
		'AnnualByCompaniesDueDebtMode' => 'Gelir ve gider bilançosu, üçüncü şahıslara göre ayrıntılı, <b>%sAlacaklar-Borçlar%s</b> söz konusu <b>Taahhüt hesabı</b> modu.',
		'AnnualByCompaniesInputOutputMode' => 'Gelir ve gider bilançosu, üçüncü şahıslara göre ayrıntılı, <b>%sGelirler-Giderler%s</b> söz konusu <b>kasa hesabı</b> modu.',
		'SeeReportInInputOutputMode' => 'Yapılan gerçek ödemelerin hesaplanması için <b>%sGelirler-Giderler%s</b> söz konusu <b>kasa hesabı</b> raporuna bakın',
		'SeeReportInDueDebtMode' => 'Verilen faturaların hesaplamaları için <b>%sAlacaklar-Borölar%s</b> söz konusu <b>taahhüt hesabı</b> raporuna bak',
		'RulesResultDue' => '- Gösterilen tutarlara tüm vergiler dahildir<br>- Ödenmemiş faturaları, giderleri ve KDV (ödenmiş ya da ödenmemiş) ni içerir.<br>- Faturaların ve KDV nin doğrulanma tarihleri ve giderlerin ödenme tarihleri baz alınır.',
		'RulesResultInOut' => '- Gösterilen tutarlar tüm vergileri içerir<br>- Faturalara, giderler ve KDV ne yapılan gerçek ödemeleri içerir.<br>- Faturaların, giderlerin ve KDV nin ödenme tarihleri baz alınır.',
		'RulesCADue' => '- Ödenmiş ya da ödenmemiş müşteri faturalarını içerir.<br> - Faturaların doğrulanma tarihleri tarihleri baz alınır. <br>',
		'RulesCAIn' => '- Müşterilerden alınan tüm geçerli fatura ödemelerini içerir.<br>- Bu faturaların ödenme tarihleri baz alınır<br>',
		'DepositsAreNotIncluded' => '- Teminat faturalarını içermez',
		'DepositsAreIncluded' => '- Teminat faturalarını içerir',
		'LT2ReportByCustomersInInputOutputModeES' => 'Üçüncü parti IRPF Raporu',
		'VATReportByCustomersInInputOutputMode' => 'Alınan ve ödenen müşteri KDV raporu (KDV makbuzu)',
		'VATReportByCustomersInDueDebtMode' => 'Alınan ve ödenen müşteri KDV raporu (KDV oranı)',
		'VATReportByQuartersInInputOutputMode' => 'Alınan ve ödenen müşteri KDV oranı raporu (KDV makbuzu)',
		'VATReportByQuartersInDueDebtMode' => 'Alınan ve ödenen müşteri KDV oranı raporu (KDV oranı)',
		'SeeVATReportInInputOutputMode' => 'Standart bir hesaplama için <b>%sKDV kapsamı%s</b> raporuna bak',
		'SeeVATReportInDueDebtMode' => 'Akış seçenekli bir hesaplama için <b>%sKDV akışı%s</b> raporuna bak',
		'RulesVATInServices' => '- For services, the report includes the VAT regulations actually received or issued on the basis of the date of payment.<br>- For material assets, it includes the VAT invoices on the basis of the invoice date.',
		'RulesVATInProducts' => '- Maddi varlıklar için, fatura tarihi baz alınarak fatura KDV lerini içerir.',
		'RulesVATDueServices' => '- Hizmetler için, ödenmiş ya da ödenmemiş fatura tarihini baz alan rapor fatura KDV lerini içerir.',
		'RulesVATDueProducts' => '- Maddi varlıklar için, fatura tarihi baz alınarak fatura KDV lerini içerir.',
		'OptionVatInfoModuleComptabilite' => 'Not: maddi varlıklar için, daha adil olması açısından teslim tarihi kullanılmalı.',
		'PercentOfInvoice' => '%%/fatura',
		'NotUsedForGoods' => 'Ürünler için kullanılmaz',
		'ProposalStats' => 'Teklif istatistikleri',
		'OrderStats' => 'Sipariş istatistikleri',
		'InvoiceStats' => 'Fatura İstatistikleri',
		'Dispatch' => 'Sevketme',
		'Dispatched' => 'Sevkedilmiş',
		'ToDispatch' => 'Sevkedilecek',
		'ThirdPartyMustBeEditAsCustomer' => 'Üçüncü parti bir müşteri olarak tanımlanmalıdır',
		'SellsJournal' => 'Satış Günlüğü',
		'PurchasesJournal' => 'Satınalma Günlüğü',
		'DescSellsJournal' => 'Satış Günlüğü',
		'DescPurchasesJournal' => 'Satınalma Günlüğü',
		'InvoiceRef' => 'Fatura ref.',
		'CodeNotDef' => 'Tanımlanmamış',
		'AddRemind' => 'Sevkedilebilir miktar',
		'RemainToDivide' => 'Gönderilmek üzere kalır:',
		'WarningDepositsNotIncluded' => 'Teminat faturaları bu muhasebe modülü ile bu sürümde içerilmez.',
		'DatePaymentTermCantBeLowerThanObjectDate' => 'Payment term date can\'t be lower than object date.',
		'Pcg_version' => 'Pcg version',
		'Pcg_type' => 'Pcg type',
		'Pcg_subtype' => 'Pcg subtype',
		'Withdrawl' => 'Prélèvement',
		'Withdrawls' => 'Prélèvements',
		'ToGetBack' => 'A récupérer',
		'Journaux' => 'Journaux',
		'Piece' => 'Piece compta',
		'JournalNum' => 'Journal',
		'COMPTA_JOURNAL_SELL' => 'Numéro comptable du Journal des Achats',
		'COMPTA_JOURNAL_BUY' => 'Numéro comptable du Journal des Ventes',
		'COMPTA_PRODUCT_BUY_ACCOUNT' => 'Compte comptable par défaut pour produits achetés (si non défini sur fiche produit)',
		'COMPTA_PRODUCT_SOLD_ACCOUNT' => 'Compte comptable par défaut pour produits vendus (si non défini sur fiche produit)',
		'COMPTA_SERVICE_BUY_ACCOUNT' => 'Compte comptable par défaut pour services achetés (si non défini sur fiche service)',
		'COMPTA_SERVICE_SOLD_ACCOUNT' => 'Compte comptable par défaut pour services vendus (si non défini sur fiche service)',
		'COMPTA_VAT_ACCOUNT' => 'Compte comptable par défaut pour TVA (si non défini dans dictionnaire "Taux de TVA")',
		'COMPTA_ACCOUNT_CUSTOMER' => 'Compte comptable client par défaut (si non défini sur fiche tiers)',
		'COMPTA_ACCOUNT_SUPPLIER' => 'Compte comptable fournisseur par défaut (si non défini sur fiche tiers)',
);
?>