<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$contracts = array(
		'CHARSET' => 'UTF-8',
		'ContractsArea' => 'Sözleşmeler alanı',
		'ListOfContracts' => 'Sözleşme Listesi',
		'LastContracts' => 'Değiştirilen son %s sözleşme',
		'AllContracts' => 'Bütün sözleşmeler',
		'ContractCard' => 'Sözleşme kartı',
		'ContractStatus' => 'Sözleşme durumu',
		'ContractStatusNotRunning' => 'Yürürlükte değil',
		'ContractStatusRunning' => 'Yürülükte',
		'ContractStatusDraft' => 'Taslak',
		'ContractStatusValidated' => 'Doğrulanmış',
		'ContractStatusClosed' => 'Kapalı',
		'ServiceStatusInitial' => 'Yürürlükte değil',
		'ServiceStatusRunning' => 'Yürürlükte',
		'ServiceStatusNotLate' => 'Yürürlükte değil, süresi dolmuş',
		'ServiceStatusNotLateShort' => 'Süresi dolmamış',
		'ServiceStatusLate' => 'Yürülükte, süresi dolmuş',
		'ServiceStatusLateShort' => 'Süresi dolmuş',
		'ServiceStatusClosed' => 'Kapalı',
		'ServicesLegend' => 'Hizmetler göstergesi',
		'Contracts' => 'Sözleşmeler',
		'Contract' => 'Sözleşme',
		'NoContracts' => 'Sözleşme yok',
		'MenuServices' => 'Hizmetler',
		'MenuInactiveServices' => 'Etkin olmayan hizmetler',
		'MenuRunningServices' => 'Yürürlükte olan hizmetler',
		'MenuExpiredServices' => 'Süresi dolmuş hizmetler',
		'MenuClosedServices' => 'Kapalı hizmetler',
		'NewContract' => 'Yeni sözleşme',
		'AddContract' => 'Sözleşme ekle',
		'SearchAContract' => 'Bir sözleşme ara',
		'DeleteAContract' => 'Bir sözleşme sil',
		'CloseAContract' => 'Bir sözleşme kapat',
		'ConfirmDeleteAContract' => 'Bu sözleşme ve bütün hizmetlerinin silmek istediğinizden emin misiniz?',
		'ConfirmValidateContract' => 'Bunu sözleşmeyi doğrulamak istediğinizden emin misiniz?',
		'ConfirmCloseContract' => 'Bu tüm hizmetleri kapatacaktır (etkin ya da değil). Bu sözleşmeyi kapatmak istediğinizden emin misiniz?',
		'ConfirmCloseService' => '<b>%s</b> Tarihli bu hizmeti kapatmak istediğiniz emin?',
		'ValidateAContract' => 'Bir sözleşme doğrula',
		'ActivateService' => 'Hizmet etkinleştir',
		'ConfirmActivateService' => '<b>%s</b> Tarihli bu hizmeti etkinleştirmek istediğiniz eminmisiniz?',
		'DateContract' => 'Sözleşme tarihi',
		'DateServiceActivate' => 'Hizmet etkinleştirme tarihi',
		'DateServiceUnactivate' => 'Hizmet devre dışı bırakma tarihi',
		'DateServiceStart' => 'Hizmet başlagıç tarihi',
		'DateServiceEnd' => 'Hizmet bitiş tarih',
		'ShowContract' => 'Sözleşme göster',
		'ListOfServices' => 'Hizmet listesi',
		'ListOfInactiveServices' => 'Etkin olmayan hizmetler listesi',
		'ListOfExpiredServices' => 'Süresi dolmuş etkin hizmetler listesi',
		'ListOfClosedServices' => 'Kapalı hizmetler listesi',
		'ListOfRunningContractsLines' => 'Yürülükte olan hizmet satırları',
		'ListOfRunningServices' => 'Yürülükteki hizmetler listesi',
		'NotActivatedServices' => 'Etkin olmayan hizmetler (doğrulanmış sözleşmeler arasından)',
		'BoardNotActivatedServices' => 'Doğrulanmış sözleşmeler arasındaki etkinleştirilecek hizmetler',
		'LastContracts' => 'Son %s sözleşme',
		'LastActivatedServices' => 'Etkinleştirilen son %s hizmet',
		'LastModifiedServices' => 'Değiştirilen son %s hizmet',
		'EditServiceLine' => 'Hizmet satırı düzenle',
		'ContractStartDate' => 'Başlangıç tarihi',
		'ContractEndDate' => 'Bitiş tarihi',
		'DateStartPlanned' => 'Planlanan başlangıç tarihi',
		'DateStartPlannedShort' => 'Planlanan başlangıç tarihi',
		'DateEndPlanned' => 'Planlanan bitiş tarihi',
		'DateEndPlannedShort' => 'Planlanan bitiş tarihi',
		'DateStartReal' => 'Gerçek başlangıç tarihi',
		'DateStartRealShort' => 'Gerçek başlangıç tarihi',
		'DateEndReal' => 'Gerçek bitiş tarihi',
		'DateEndRealShort' => 'Gerçek bitiş tarihi',
		'NbOfServices' => 'Hizmet sayısı',
		'CloseService' => 'Hizmet kapat',
		'ServicesNomberShort' => '%s hizmet',
		'RunningServices' => 'Yürürlükteki hizmetler',
		'BoardRunningServices' => 'Süresi dolmuş yürürlükteki hizmetler',
		'ServiceStatus' => 'Hizmetin Durumu',
		'DraftContracts' => 'Taslak sözleşmeler',
		'CloseRefusedBecauseOneServiceActive' => 'En az bir açık hizmeti olduğundan dolayı sözleşme kapatılamıyor',
		'CloseAllContracts' => 'Bütün sözleşme satırlarını kapat',
		'DeleteContractLine' => 'Bir sözleşme satırı sil',
		'ConfirmDeleteContractLine' => 'Bu sözleşme satırını silmek istediğinizden emin misiniz?',
		'MoveToAnotherContract' => 'Hizmeti başka bir sözleşmeye taşıyın.',
		'ConfirmMoveToAnotherContract' => 'Yeni hedefi seçtim ve bu hizmeti bu sözleşmeye taşımayı onaylıyorum.',
		'ConfirmMoveToAnotherContractQuestion' => 'Bu hizmeti taşımak istediğiniz varolan sözleşmeyi seçin (aynı üçüncü partinin)?',
		'PaymentRenewContractId' => 'Sözleşme satırını yenile (sayı %s)',
		'ExpiredSince' => 'Süre doluş tarihi',
		'RelatedContracts' => 'İlgili sözleşmeler',
		'NoExpiredServices' => 'Süresi dolmamış etkin hizmetler',
		////////// Kişi türleri //////////
		'TypeContact_contrat_internal_SALESREPSIGN' => 'Sözleşme imzalalayacak satış temsilcisi',
		'TypeContact_contrat_internal_SALESREPFOLL' => 'Sözleşmeyi izleyecek satış temsilcisi',
		'TypeContact_contrat_external_BILLING' => 'Müşteri fatura ilgilisi',
		'TypeContact_contrat_external_CUSTOMER' => 'Müşteri izleme ilgilisi',
		'TypeContact_contrat_external_SALESREPSIGN' => 'Sözleşme imzalayacak müşteri ilgilisi',
		'Error_CONTRACT_ADDON_NotDefined' => 'CONTRACT_ADDON değişmezi tanımlanmamış',
);
?>