<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Depo kartı',
		'Warehouse' => 'Depo',
		'NewWarehouse' => 'Yeni depo / Stok alanı',
		'MenuNewWarehouse' => 'Yeni depo',
		'WarehouseOpened' => 'Depo açık',
		'WarehouseClosed' => 'Depo kapalı',
		'WarehouseSource' => 'Kaynak depo',
		'WarehouseTarget' => 'Hedef depo',
		'ValidateSending' => 'Gönderim sil',
		'CancelSending' => 'Gönderim iptal et',
		'DeleteSending' => 'Gönderim sil',
		'Stock' => 'Stok',
		'Stocks' => 'Stoklar',
		'Movement' => 'Hareket',
		'Movements' => 'Hareketler',
		'ErrorWarehouseRefRequired' => 'Depo referans adı gereklidir',
		'ErrorWarehouseLabelRequired' => 'Depo etiketi gereklidir',
		'CorrectStock' => 'Doğru stok',
		'ListOfWarehouses' => 'Depo listesi',
		'ListOfStockMovements' => 'Stok hareketleri listesi',
		'StocksArea' => 'Stok alanı',
		'Location' => 'Konum',
		'LocationSummary' => 'Kısa konum adı',
		'NumberOfProducts' => 'Toplam ürün sayısı',
		'LastMovement' => 'Son hareket',
		'LastMovements' => 'Son hareketler',
		'Units' => 'Birimler',
		'Unit' => 'Birim',
		'StockCorrection' => 'Doğru stok',
		'StockMovement' => 'Aktarma',
		'StockMovements' => 'Stok aktarımı',
		'NumberOfUnit' => 'Birim sayısı',
		'TotalStock' => 'Stok toplamı',
		'StockTooLow' => 'Stok çok düşük',
		'EnhancedValue' => 'Değer',
		'PMPValue' => 'Ağırlıklı ortalama fiyat',
		'PMPValueShort' => 'AOF',
		'EnhancedValueOfWarehouses' => 'Depolar değeri',
		'UserWarehouseAutoCreate' => 'Bir kullanıcı oluştururken otomatik olarak bir stok oluşturma',
		'QtyDispatched' => 'Sevkedilen miktar',
		'OrderDispatch' => 'Stok sevkiyatı',
		'RuleForStockManagementDecrease' => 'Azaltma için stok yönetimi kuralı',
		'RuleForStockManagementIncrease' => 'Arttırma için stok yönetimi kuralı',
		'DeStockOnBill' => 'Müşteri faturaların/senetlerinin doğrulanması üzerine gerçek stokları azalt',
		'DeStockOnValidateOrder' => 'Müşteri siparişlerinin doğrulanması üzerine gerçek stokları azalt',
		'DeStockOnShipment' => 'Sevkiyat doğrulaması üzerine gerçek stokları azalt',
		'ReStockOnBill' => 'Faturaların gerçek hisse arttır / kredi notları doğrulama',
		'ReStockOnValidateOrder' => 'Tedarikçi siparişlerinin onanması üzerine gerçek stokları arttır',
		'StockDiffPhysicTeoric' => 'Fiziksel ve teorik stok arasındaki stok farkı',
		'StockLimitShort' => 'Sınır',
		'StockLimit' => 'Uyarılacak stok sınırı',
		'PhysicalStock' => 'Mevcut stok',
		'RealStock' => 'Gerçek Stok',
		'TheoreticalStock' => 'Teorik stok',
		'VirtualStock' => 'Sanal stok',
		'MininumStock' => 'Enaz stok',
		'StockUp' => 'Stok arttır',
		'MininumStockShort' => 'Stok azalt',
		'StockUpShort' => 'Stok arttır',
		'IdWarehouse' => 'Depo No',
		'DescWareHouse' => 'Depo açıklaması',
		'LieuWareHouse' => 'Depo konumlandırma',
		'WarehousesAndProducts' => 'Depolar ve ürünler',
		'AverageUnitPricePMPShort' => 'Ağırlıklı ortalama giriş fiyatı',
		'AverageUnitPricePMP' => 'Ağırlıklı ortalama giriş fiyatı',
		'EstimatedStockValueShort' => 'Stok giriş değeri',
		'EstimatedStockValue' => 'Stok giriş değeri',
		'WarehouseEdit' => 'Depo düzenle',
		'ReStockOnDispatchOrder' => 'Tedarikçi siparişi aldıktan sonra, elle yapılan sevk üzerine gerçek stokları artırın',
		'OrderStatusNotReadyToDispatch' => 'Sipariş henüz yoksa veya stok deposundan gönderime izin veren bir durum varsa.',
		'NoPredefinedProductToDispatch' => 'Bu nesne için önceden tanımlanmış ürünlenyok. Yani stoktan sevk gerekli değildir.',
		'DispatchVerb' => 'Dağıtım',
		'SellPriceMin' => 'Satış Birim Fiyatı',
		'EstimatedStockValueSellShort' => 'Satış değeri',
		'EstimatedStockValueSell' => 'Satış değeri',
		'DeleteAWarehouse' => 'Bir depo sil',
		'ConfirmDeleteWarehouse' => '<b>%s</b> Deposunu silmek istediğiniz emin misiniz ?',
		'PersonalStock' => 'Kişisel stok %s',
		'ThisWarehouseIsPersonalStock' => 'Bu depo %s %s kişisel stoğu temsil eder',
		'SelectWarehouseForStockDecrease' => 'Stok azaltılması için kullanmak üzere depo seçin',
		'SelectWarehouseForStockIncrease' => 'Stok artışı için kullanılacak depo seçin',
);
?>