<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$other = array(
		'CHARSET' => 'UTF-8',
		'Calendar' => 'Календарь',
		'AddTrip' => 'Добавить поездку',
		'Tools' => 'Инструменты',
		'ToolsDesc' => 'Эта область посвящена группе разные инструменты не доступны в другие пункты меню. <br><br> Эти инструменты могут быть достигнуты из меню на стороне.',
		'Birthday' => 'День рождения',
		'BirthdayDate' => 'День рождения',
		'DateToBirth' => 'Дата до рождения',
		'BirthdayAlertOn' => 'День рождения оповещения активных',
		'BirthdayAlertOff' => 'День рождения оповещения неактивные',
		'Notify_FICHINTER_VALIDATE' => 'Вмешательство проверку',
		'Notify_WITHDRAW_TRANSMIT' => 'Передача вывода',
		'Notify_WITHDRAW_CREDIT' => 'Кредитный выход',
		'Notify_WITHDRAW_EMIT' => 'Isue вывода',
		'Notify_ORDER_SENTBYMAIL' => 'Покупатель делает заказ по почте',
		'Notify_COMPANY_CREATE' => 'Третья партия, созданная',
		'Notify_PROPAL_SENTBYMAIL' => 'Коммерческое предложение по почте',
		'Notify_ORDER_SENTBYMAIL' => 'Envío pedido пор электронной почте',
		'Notify_BILL_PAYED' => 'Клиенту счет-фактура оплачен',
		'Notify_BILL_CANCEL' => 'Клиенту счет-фактура отменен',
		'Notify_BILL_SENTBYMAIL' => 'Клиенту счет-фактура высылается по почте',
		'Notify_FICHEINTER_VALIDATE' => 'Вмешательство проверку',
		'Notify_SHIPPING_VALIDATE' => 'Доставка проверку',
		'Notify_SHIPPING_SENTBYMAIL' => 'Доставка по почте',
		'Notify_MEMBER_VALIDATE' => 'Член проверку',
		'Notify_MEMBER_SUBSCRIPTION' => 'Член подписался',
		'Notify_MEMBER_RESILIATE' => 'Член resiliated',
		'Notify_MEMBER_DELETE' => 'Член удален',
		'NbOfAttachedFiles' => 'Количество прикрепленных файлов / документов',
		'TotalSizeOfAttachedFiles' => 'Общий размер присоединенных файлов / документов',
		'MaxSize' => 'Максимальный размер',
		'PredefinedMailTest' => 'Это тест почте. \ NВ две строки, разделенные возвратом каретки.',
		'PredefinedMailTestHtml' => 'Это <b>тест</b> почте (слово тест должен быть жирным шрифтом). <br> Две строки, разделенные возвратом каретки.',
		'PredefinedMailContentSendInvoice' => 'Только здесь вы найдете счета __FACREF__ \n\n__PERSONALIZED__Sincerely \n\n__SIGNATURE__',
		'PredefinedMailContentSendInvoiceReminder' => 'Мы бы хотели предупредить Вас, что счет-фактура __FACREF__, кажется, не оплачиваются. Так что это счета-фактуры в привязанности снова, как напоминание. \n\n__PERSONALIZED__Sincerely \n\n__SIGNATURE__',
		'PredefinedMailContentSendProposal' => 'Только здесь вы найдете коммерческие propoal __PROPREF__ \n\n__PERSONALIZED__Sincerely \n\n__SIGNATURE__',
		'PredefinedMailContentSendOrder' => 'Вы найдете здесь порядок __ORDERREF__ \n\n__PERSONALIZED__Sincerely \n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierOrder' => 'Здесь Вы найдете наш заказ __ORDERREF__ \n\n__PERSONALIZED__Sincerely \n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierInvoice' => 'Только здесь вы найдете счета __FACREF__ \n\n__PERSONALIZED__Sincerely \n\n__SIGNATURE__',
		'PredefinedMailContentSendShipping' => 'Здесь вы найдете доставку __SHIPPINGREF__ \n\n__PERSONALIZED__Sincerely\n\n__SIGNATURE__',
		'PredefinedMailContentSendFichInter' => 'Вы найдете здесь вмешательство __FICHINTERREF__ \n\n__PERSONALIZED__Sincerely \n\n__SIGNATURE__',
		'DemoCompanyProductAndStocks' => 'Управление малого и среднего продуктов компании, продающей',
		'DemoCompanyAll' => 'Управление малых и средних компаний с несколькими деятельности (все основные модули)',
		'GoToDemo' => 'Перейти в демо-',
		'CreatedBy' => 'Создано %s',
		'ModifiedBy' => 'Изменен %s',
		'ValidatedBy' => 'Получившее одобрение %s',
		'CanceledBy' => 'Отменен по %s',
		'ClosedBy' => 'Закрыто %s',
		'FileWasRemoved' => 'Файл был удален %s',
		'DirWasRemoved' => 'Каталог %s был удален',
		'Width' => 'Ширина',
		'Height' => 'Высота',
		'Depth' => 'Глубина',
		'Top' => 'Топ',
		'Bottom' => 'Дно',
		'Left' => 'Левый',
		'Right' => 'Право',
		'CalculatedWeight' => 'Расчетный вес',
		'CalculatedVolume' => 'Расчетный объем',
		'Weight' => 'Вес',
		'Length' => 'Длина',
		'LengthUnitm' => 'метр',
		'LengthUnitdm' => 'дм',
		'LengthUnitcm' => 'см',
		'LengthUnitmm' => 'мм',
		'Surface' => 'Площадь',
		'SurfaceUnitm2' => 'м2',
		'SurfaceUnitdm2' => 'дм2',
		'SurfaceUnitcm2' => 'см2',
		'SurfaceUnitmm2' => 'мм2',
		'VolumeUnitounce' => 'унция',
		'VolumeUnitlitre' => 'литр',
		'VolumeUnitgallon' => 'галлон',
		'Size' => 'размер',
		'SizeUnitm' => 'метр',
		'SizeUnitdm' => 'дм',
		'SizeUnitcm' => 'см',
		'SizeUnitmm' => 'мм',
		'SizeUnitinch' => 'дюйм',
		'SizeUnitfoot' => 'фут',
		'ProfIdShortDesc' => '<b>Профессор Id %s</b> является информация в зависимости от третьей стране партией. <br> Например, для страны <b>%s,</b> это код <b>%s.</b>',
		'SpeedealingDemo' => 'Speedealing ERP / CRM-демо-',
		'StatsByNumberOfUnits' => 'Статистика количества товаров / услуг, единиц',
		'StatsByNumberOfEntities' => 'Статистика в число ссылкой лиц',
		'NumberOfProposals' => 'Количество предложений на последних 12 месяцев',
		'NumberOfCustomerOrders' => 'Количество заказов на последние 12 месяца',
		'NumberOfCustomerInvoices' => 'Количество клиентов на счета последних 12 месяцев',
		'NumberOfSupplierInvoices' => 'Количество поставщиков счетов на последние 12 месяца',
		'NumberOfUnitsProposals' => 'Количество единиц по предложениям в отношении последних 12 месяцев',
		'NumberOfUnitsCustomerOrders' => 'Количество единиц на заказы клиентов на последние 12 месяца',
		'EMailTextOrderApproved' => 'Порядок %s была одобрена.',
		'EMailTextOrderApprovedBy' => 'Порядок %s был одобрен %s.',
		'EMailTextOrderRefused' => 'Порядок %s было отказано.',
		'EMailTextOrderRefusedBy' => 'Порядок %s было отказано %s.',
		'ImportedWithSet' => 'Импорт набора данных',
		'SpeedealingNotification' => 'Автоматическое уведомление',
		'ResizeDesc' => 'Введите новое значение ширины <b>или</b> новые высоты. Отношение будет находиться во время изменения размера ...',
		'NewLength' => 'Новые ширина',
		'NewHeight' => 'Новая высота',
		'NewSizeAfterCropping' => 'Новый размер после обрезки',
		'ClickHere' => 'Нажмите здесь',
		'UseAdvancedPerms' => 'Используйте дополнительные разрешения некоторых модулей',
		'FileFormat' => 'Формат файлов',
		'SelectAColor' => 'Выберите цвет',
		'AddFiles' => 'Добавить файлы',
		'StartUpload' => 'Начать загрузку',
		'CancelUpload' => 'Отмена загрузки',
		'FileIsTooBig' => 'Файлы слишком велик',
		'PropalClosedSignedInSpeedealing' => 'Предложение %s подписан в Speedealing',
		'PropalClosedRefusedInSpeedealing' => 'Предложение %s отказано в Speedealing',
		'PropalValidatedInSpeedealing' => 'Предложение %s подтверждены в Speedealing',
		'InvoiceValidatedInSpeedealing' => 'Счет %s подтверждены в Speedealing',
		'InvoicePaidInSpeedealing' => 'Счет %s изменено на выплачиваются в Speedealing',
		'InvoiceCanceledInSpeedealing' => 'Счет %s отменен в Speedealing',
		'PaymentDoneInSpeedealing' => 'Оплата %s сделано в Speedealing',
		'CustomerPaymentDoneInSpeedealing' => '%s клиентов оплаты сделано в Speedealing',
		'SupplierPaymentDoneInSpeedealing' => '%s Поставщик оплаты сделано в Speedealing',
		'MemberValidatedInSpeedealing' => 'Член %s подтверждены в Speedealing',
		'LibraryUsed' => 'Librairy использоваться',
		'LibraryVersion' => 'Версия',
		'ExportableDatas' => 'Экспортные данные',
		'NoExportableData' => 'Нет экспорта данных (без модулей с экспортируемыми данными загружен, или отсутствуют разрешения)',
		'ToExport' => 'Экспорт',
		'NewExport' => 'Новый экспорт',
		'ExternalSites' => 'Внешние сайты',
);
?>