<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'الفئة',
		'Categories' => 'الفئات',
		'Rubrique' => 'الفئة',
		'Rubriques' => 'الفئات',
		'categories' => 'الفئات',
		'TheCategorie' => 'فئة',
		'NoCategoryYet' => 'أي فئة من هذا النوع التي أنشئت',
		'In' => 'في',
		'AddIn' => 'أضيف في',
		'modify' => 'تعديل',
		'Classify' => 'تصنيف',
		'CategoriesArea' => 'منطقة الفئات',
		'ProductsCategoriesArea' => 'منتجات / خدمات الفئات المنطقة',
		'SuppliersCategoriesArea' => 'الموردين منطقة الفئات',
		'CustomersCategoriesArea' => 'العملاء منطقة الفئات',
		'ThirdPartyCategoriesArea' => 'أطراف ثالثة \'منطقة الفئات',
		'MembersCategoriesArea' => 'أعضاء فئات المناطق',
		'MainCats' => 'الفئات الرئيسية',
		'SubCats' => 'فرعية',
		'CatStatistics' => 'احصاءات',
		'CatList' => 'قائمة الفئات',
		'AllCats' => 'جميع الفئات',
		'ViewCat' => 'وترى هذه الفئة',
		'NewCat' => 'إضافة فئة',
		'NewCategory' => 'فئة جديدة',
		'ModifCat' => 'تعديل الفئة',
		'CatCreated' => 'فئة خلق',
		'CreateCat' => 'خلق فئة',
		'CreateThisCat' => 'تهيئة هذه الفئة',
		'ValidateFields' => 'صحة المجالات',
		'NoSubCat' => 'لا فرعية.',
		'SubCatOf' => 'فرعية',
		'FoundCats' => 'العثور على الفئات',
		'FoundCatsForName' => 'فئات إيجاد اسم :',
		'FoundSubCatsIn' => 'فرعية موجودة في الفئة',
		'ErrSameCatSelected' => 'كنت قد اخترت نفس الفئة عدة مرات',
		'ErrForgotCat' => 'نسيت اختيار الفئة',
		'ErrForgotField' => 'نسيت أن أبلغ المجالات',
		'ErrCatAlreadyExists' => 'هذا الاسم مستخدم بالفعل',
		'AddProductToCat' => 'إضافة هذا المنتج إلى الفئة؟',
		'ImpossibleAddCat' => 'من المستحيل أن تضيف فئة',
		'ImpossibleAssociateCategory' => 'من المستحيل المنتسبين لهذه الفئة',
		'WasAddedSuccessfully' => '<b>ق ٪</b> أضيفت بنجاح.',
		'ObjectAlreadyLinkedToCategory' => 'العنصر المرتبط بالفعل في هذه الفئة.',
		'CategorySuccessfullyCreated' => 'ق ٪ من هذه الفئة تم اضافة بالنجاح.',
		'ProductIsInCategories' => 'المنتجات / الخدمات وتملك على الفئات التالية',
		'SupplierIsInCategories' => 'لطرف ثالث يملك الموردين الفئات التالية',
		'CompanyIsInCustomersCategories' => 'هذا الطرف الثالث وتملك ليلي العملاء / آفاق الفئات',
		'CompanyIsInSuppliersCategories' => 'ويملك هذا الطرف الثالث على الفئات التالية الموردين',
		'MemberIsInCategories' => 'يملك هذا العضو إلى الفئات التالية الأعضاء',
		'ProductHasNoCategory' => 'هذا المنتج / الخدمة وليس في أي فئات',
		'SupplierHasNoCategory' => 'هذا المورد ليست في أي فئات',
		'CompanyHasNoCategory' => 'هذه الشركة ليست في أي فئات',
		'MemberHasNoCategory' => 'هذا العضو غير موجود في أي فئات',
		'ClassifyInCategory' => 'تصنف في الفئة',
		'NoneCategory' => 'بلا',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'هذه الفئة موجودة بالفعل في نفس المكان',
		'ReturnInProduct' => 'عودة إلى المنتجات / الخدمات بطاقة',
		'ReturnInSupplier' => 'عودة الى مورد بطاقة',
		'ReturnInCompany' => 'عودة الى الزبون / احتمال بطاقة',
		'ContentsVisibleByAll' => 'محتويات سوف تكون واضحة من جانب جميع',
		'ContentsVisibleByAllShort' => 'محتويات مرئية من قبل جميع',
		'ContentsNotVisibleByAllShort' => 'محتويات غير مرئي من قبل جميع',
		'CategoriesTree' => 'شجرة التصنيفات',
		'DeleteCategory' => 'حذف فئة',
		'ConfirmDeleteCategory' => 'هل أنت متأكد من أنك تريد حذف هذه الفئة؟',
		'RemoveFromCategory' => 'إزالة الارتباط مع catégorie',
		'RemoveFromCategoryConfirm' => 'هل أنت متأكد من أنك تريد إزالة الربط بين الصفقة والفئة؟',
		'NoCategoriesDefined' => 'أي فئة محددة',
		'SuppliersCategoryShort' => 'فئة الموردين',
		'CustomersCategoryShort' => 'فئة الزبائن',
		'ProductsCategoryShort' => 'فئة المنتجات',
		'MembersCategoryShort' => 'أعضاء الفئة',
		'SuppliersCategoriesShort' => 'فئات الموردين',
		'CustomersCategoriesShort' => 'فئات العملاء',
		'CustomersProspectsCategoriesShort' => 'Custo. / Prosp. الفئات',
		'ProductsCategoriesShort' => 'فئات المنتجات',
		'MembersCategoriesShort' => 'أعضاء الفئات',
		'ThisCategoryHasNoProduct' => 'هذه الفئة لا تحتوي على أي منتج.',
		'ThisCategoryHasNoSupplier' => 'هذه الفئة لا تحتوي على أي مورد.',
		'ThisCategoryHasNoCustomer' => 'هذه الفئة لا تحتوي على أي عميل.',
		'ThisCategoryHasNoMember' => 'هذا التصنيف لا يحتوي على أي عضو.',
		'AssignedToCustomer' => 'المخصصة للعميل',
		'AssignedToTheCustomer' => 'يكلف العميل',
		'InternalCategory' => 'فئة Inernal',
		'CategoryContents' => 'محتويات هذه الفئة',
		'CategId' => 'معرف الفئة',
		'CatSupList' => 'قائمة الموردين الفئات',
		'CatCusList' => 'قائمة العملاء / احتمال الفئات',
		'CatProdList' => 'قائمة المنتجات فئات',
		'CatMemberList' => 'قائمة بأسماء أعضاء الفئات',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>