<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'التجارية',
		'CommercialArea' => 'منطقة تجارية',
		'CommercialCard' => 'بطاقة تجارية',
		'CustomerArea' => 'منطقة العملاء',
		'Customer' => 'العميل',
		'Customers' => 'العملاء',
		'Prospect' => 'احتمال',
		'Prospects' => 'آفاق',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'حذف عمل / المهمة',
		'NewAction' => 'عمل جديدة / المهمة',
		'AddAction' => 'أضف العمل / المهمة',
		'AddAnAction' => 'إضافة عمل / المهمة',
		'AddActionRendezVous' => 'إضافة مهمة رانديفو',
		'Rendez-Vous' => 'الموعد',
		'ConfirmDeleteAction' => 'هل أنت متأكد من أنك تريد حذف هذه المهمة؟',
		'CardAction' => 'بطاقة العمل',
		'PercentDone' => 'النسبة المئوية لعمله',
		'ActionOnCompany' => 'مهمة عن الشركة',
		'ActionOnContact' => 'مهمة حول الاتصال',
		'TaskRDV' => 'اجتماعات',
		'TaskRDVWith' => 'لقاء مع ق ٪',
		'ShowTask' => 'وتظهر هذه المهمة',
		'ShowAction' => 'وتظهر العمل',
		'ActionsReport' => 'تقرير الأعمال',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'ممثل مبيعات',
		'SalesRepresentatives' => 'مندوبي المبيعات',
		'SalesRepresentativeFollowUp' => 'ممثل مبيعات (متابعة)',
		'SalesRepresentativeSignature' => 'ممثل مبيعات (التوقيع)',
		'CommercialInterlocutor' => 'المحاور التجارية',
		'ErrorWrongCode' => 'رمز الخطأ',
		'NoSalesRepresentativeAffected' => 'أي ممثل مبيعات المتضررة',
		'ShowCustomer' => 'وتبين للعملاء',
		'ShowProspect' => 'وتظهر احتمال',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'قائمة التوقعات',
		'ListOfCustomers' => 'قائمة العملاء',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => '٪ ق الماضي مهام عمله',
		'LastRecordedTasks' => 'وسجلت آخر المهام',
		'LastActionsToDo' => 'الماضي ٪ اقدم الإجراءات لم تكتمل',
		'DoneAndToDoActionsFor' => 'وعمله من أجل القيام بالمهام ق ٪',
		'DoneAndToDoActions' => 'ويتم القيام بمهام',
		'DoneActions' => 'إجراءات عمله',
		'DoneActionsFor' => 'إجراءات لعمله ق ٪',
		'ToDoActions' => 'عدم اكتمال الإجراءات',
		'ToDoActionsFor' => 'لعدم اكتمال الإجراءات ق ٪',
		'SendPropalRef' => 'اقتراح ارسال التجارية ق ٪',
		'SendOrderRef' => 'من أجل إرسال المستندات ٪',
		'StatusNotApplicable' => 'Not applicable',
		'StatusActionToDo' => 'القيام',
		'StatusActionDone' => 'فعل',
		'StatusActionInProcess' => 'في العملية',
		'MyActionsAsked' => 'لقد سجلت الأعمال',
		'MyActionsToDo' => 'الإجراءات التي يتعين علي القيام به',
		'MyActionsDone' => 'الإجراءات التي أثرت لي',
		'TasksHistoryForThisContact' => 'إجراءات لهذا الاتصال',
		'LastProspectDoNotContact' => 'لا اتصال',
		'LastProspectNeverContacted' => 'اتصل أبدا',
		'LastProspectToContact' => 'للاتصال',
		'LastProspectContactInProcess' => 'في عملية الاتصال',
		'LastProspectContactDone' => 'الاتصال به',
		'DateActionPlanned' => 'تاريخ العمل المزمع',
		'DateActionDone' => 'تاريخ العمل به',
		'ActionAskedBy' => 'طلبت العمل',
		'ActionAffectedTo' => 'العمل على المتضررين',
		'ActionDoneBy' => 'العمل الذي قام به',
		'ActionUserAsk' => 'التي سجلتها',
		'ErrorStatusCantBeZeroIfStarted' => 'إذا كان المجال <b>\'تاريخ عمله</b> هو شغلها ، وبدأ العمل (أو انتهت) ، وذلك الميدان\' <b>الحالة</b> \'لا يمكن أن يكون 0 ٪ ٪.',
		'ActionAC_TEL' => 'اتصال هاتفي',
		'ActionAC_FAX' => 'إرسال فاكس',
		'ActionAC_PROP' => 'إرسال اقتراح',
		'ActionAC_EMAIL' => 'ارسال بريد الكتروني',
		'ActionAC_RDV' => 'اجتماعات',
		'ActionAC_FAC' => 'ارسال الفواتير',
		'ActionAC_REL' => 'ارسال الفواتير (للتذكير)',
		'ActionAC_CLO' => 'إغلاق',
		'ActionAC_EMAILING' => 'إرسال البريد الإلكتروني الجماعي',
		'ActionAC_COM' => 'لكي ترسل عن طريق البريد',
		'ActionAC_SHIP' => 'Send shipping by mail',
		'ActionAC_SUP_ORD' => 'أرسل النظام المورد عن طريق البريد',
		'ActionAC_SUP_INV' => 'إرسال فاتورة المورد عن طريق البريد',
		'ActionAC_OTH' => 'Other',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Prospect status',
		'DraftPropals' => 'Draft commercial proposals',
		'SearchPropal' => 'Search a commercial proposal'
);
?>