<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'التجارية',
		'CommercialArea' => 'منطقة تجارية',
		'CommercialCard' => 'بطاقة تجارية',
		'CustomerArea' => 'منطقة العملاء',
		'Customer' => 'العميل',
		'Customers' => 'العملاء',
		'Prospect' => 'احتمال',
		'Prospects' => 'آفاق',
		'DeleteAction' => 'حذف عمل / المهمة',
		'NewAction' => 'عمل جديدة / المهمة',
		'AddAction' => 'أضف العمل / المهمة',
		'AddAnAction' => 'إضافة عمل / المهمة',
		'ConfirmDeleteAction' => 'هل أنت متأكد من أنك تريد حذف هذه المهمة؟',
		'CardAction' => 'بطاقة العمل',
		'PercentDone' => 'النسبة المئوية لعمله',
		'ActionOnCompany' => 'مهمة عن الشركة',
		'ActionOnContact' => 'مهمة حول الاتصال',
		'TaskRDV' => 'اجتماعات',
		'TaskRDVWith' => 'لقاء مع ق ٪',
		'ShowTask' => 'وتظهر هذه المهمة',
		'ShowAction' => 'وتظهر العمل',
		'ActionsReport' => 'تقرير الأعمال',
		'SalesRepresentative' => 'ممثل مبيعات',
		'SalesRepresentatives' => 'مندوبي المبيعات',
		'SalesRepresentativeFollowUp' => 'ممثل مبيعات (متابعة)',
		'SalesRepresentativeSignature' => 'ممثل مبيعات (التوقيع)',
		'CommercialInterlocutor' => 'المحاور التجارية',
		'ErrorWrongCode' => 'رمز الخطأ',
		'NoSalesRepresentativeAffected' => 'أي ممثل مبيعات المتضررة',
		'ShowCustomer' => 'وتبين للعملاء',
		'ShowProspect' => 'وتظهر احتمال',
		'ListOfProspects' => 'قائمة التوقعات',
		'ListOfCustomers' => 'قائمة العملاء',
		'LastDoneTasks' => '٪ ق الماضي مهام عمله',
		'LastRecordedTasks' => 'وسجلت آخر المهام',
		'LastActionsToDo' => 'الماضي ٪ اقدم الإجراءات لم تكتمل',
		'DoneAndToDoActionsFor' => 'وعمله من أجل القيام بالمهام ق ٪',
		'DoneAndToDoActions' => 'ويتم القيام بمهام',
		'DoneActions' => 'إجراءات عمله',
		'DoneActionsFor' => 'إجراءات لعمله ق ٪',
		'SendPropalRef' => 'اقتراح ارسال التجارية ق ٪',
		'SendOrderRef' => 'من أجل إرسال المستندات ٪',
		'StatusActionToDo' => 'القيام',
		'StatusActionDone' => 'فعل',
		'MyActionsAsked' => 'لقد سجلت الأعمال',
		'MyActionsToDo' => 'الإجراءات التي يتعين علي القيام به',
		'MyActionsDone' => 'الإجراءات التي أثرت لي',
		'StatusActionInProcess' => 'في العملية',
		'TasksHistoryForThisContact' => 'إجراءات لهذا الاتصال',
		'LastProspectDoNotContact' => 'لا اتصال',
		'LastProspectNeverContacted' => 'اتصل أبدا',
		'LastProspectToContact' => 'للاتصال',
		'LastProspectContactInProcess' => 'في عملية الاتصال',
		'LastProspectContactDone' => 'الاتصال به',
		'DateActionPlanned' => 'تاريخ العمل المزمع',
		'DateActionDone' => 'تاريخ العمل به',
		'ActionAskedBy' => 'طلبت العمل',
		'ActionAffectedTo' => 'العمل على المتضررين',
		'ActionDoneBy' => 'العمل الذي قام به',
		'ActionUserAsk' => 'التي سجلتها',
		'ErrorStatusCantBeZeroIfStarted' => 'إذا كان المجال <b>\'تاريخ عمله</b> هو شغلها ، وبدأ العمل (أو انتهت) ، وذلك الميدان\' <b>الحالة</b> \'لا يمكن أن يكون 0 ٪ ٪.',
		'ActionAC_TEL' => 'اتصال هاتفي',
		'ActionAC_FAX' => 'إرسال فاكس',
		'ActionAC_PROP' => 'إرسال اقتراح',
		'ActionAC_EMAIL' => 'ارسال بريد الكتروني',
		'ActionAC_RDV' => 'اجتماعات',
		'ActionAC_FAC' => 'ارسال الفواتير',
		'ActionAC_REL' => 'ارسال الفواتير (للتذكير)',
		'ActionAC_CLO' => 'إغلاق',
		'ActionAC_EMAILING' => 'إرسال البريد الإلكتروني الجماعي',
		'ActionAC_COM' => 'لكي ترسل عن طريق البريد',
		'AddActionRendezVous' => 'إضافة مهمة رانديفو',
		'Rendez-Vous' => 'الموعد',
		'ToDoActions' => 'عدم اكتمال الإجراءات',
		'ToDoActionsFor' => 'لعدم اكتمال الإجراءات ق ٪',
		'ActionAC_SUP_ORD' => 'أرسل النظام المورد عن طريق البريد',
		'ActionAC_SUP_INV' => 'إرسال فاتورة المورد عن طريق البريد',
);
?>