<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'بطاقة مخزن',
		'Warehouse' => 'مخزن',
		'Warehouses' => 'Warehouses',
		'NewWarehouse' => 'المستودع الجديد / بورصة المنطقة',
		'WarehouseEdit' => 'تعديل مستودع',
		'MenuNewWarehouse' => 'مستودع جديد',
		'WarehouseOpened' => 'فتح مخزن',
		'WarehouseClosed' => 'مخزن مغلق',
		'WarehouseSource' => 'مصدر مخزن',
		'WarehouseSourceNotDefined' => 'No warehouse defined,',
		'AddOne' => 'Add one',
		'WarehouseTarget' => 'الهدف مخزن',
		'ValidateSending' => 'حذف ارسال',
		'CancelSending' => 'الغاء ارسال',
		'DeleteSending' => 'حذف ارسال',
		'Stock' => 'الأسهم',
		'Stocks' => 'الاسهم',
		'Movement' => 'الحركة',
		'Movements' => 'حركات',
		'ErrorWarehouseRefRequired' => 'مستودع الاشارة اسم مطلوب',
		'ErrorWarehouseLabelRequired' => 'مستودع العلامة مطلوبة',
		'CorrectStock' => 'تصحيح الأوراق المالية',
		'ListOfWarehouses' => 'لائحة المخازن',
		'ListOfStockMovements' => 'قائمة الحركات الأسهم',
		'StocksArea' => 'مخزون المنطقة',
		'Location' => 'عوضا عن',
		'LocationSummary' => 'باختصار اسم الموقع',
		'NumberOfProducts' => 'العدد الإجمالي للمنتجات',
		'LastMovement' => 'الماضي حركة',
		'LastMovements' => 'التحركات الأخيرة',
		'Units' => 'الوحدات',
		'Unit' => 'وحدة',
		'StockCorrection' => 'تصحيح الأوراق المالية',
		'StockMovement' => 'نقل',
		'StockMovements' => 'تحويلات الأوراق المالية',
		'NumberOfUnit' => 'عدد الوحدات',
		'UnitPurchaseValue' => 'Unit purchase price',
		'TotalStock' => 'إجمالي المخزون',
		'StockTooLow' => 'الاسهم منخفضة جدا',
		'StockLowerThanLimit' => 'Stock lower than alert limit',
		'EnhancedValue' => 'القيمة',
		'PMPValue' => 'المتوسط المرجح لسعر',
		'PMPValueShort' => 'الواب',
		'EnhancedValueOfWarehouses' => 'قيمة المستودعات',
		'UserWarehouseAutoCreate' => 'خلق مخزون تلقائيا عند إنشاء مستخدم',
		'QtyDispatched' => 'ارسال كمية',
		'OrderDispatch' => 'ارسال الأسهم',
		'RuleForStockManagementDecrease' => 'قاعدة لإدارة المخزون النقصان',
		'RuleForStockManagementIncrease' => 'قاعدة لإدارة المخزون وزيادة',
		'DeStockOnBill' => 'Decrease real stocks on customers invoices/credit notes validation',
		'DeStockOnValidateOrder' => 'Decrease real stocks on customers orders validation',
		'DeStockOnShipment' => 'انخفاض الاسهم الحقيقي على شحنة المصادقة (مستحسن)',
		'ReStockOnBill' => 'Increase real stocks on suppliers invoices/credit notes validation',
		'ReStockOnValidateOrder' => 'Increase real stocks on suppliers orders approbation',
		'ReStockOnDispatchOrder' => 'زيادة مخزونات دليل حقيقي على إيفاد في المستودعات ، وبعد تلقي أمر المورد',
		'OrderStatusNotReadyToDispatch' => 'أمر لم يتم بعد أو لا أكثر من ذلك الوضع الذي يسمح بإرسال من المنتجات في مخازن المخزون.',
		'StockDiffPhysicTeoric' => 'والسبب في الاختلاف المخزون المادي والنظرية',
		'NoPredefinedProductToDispatch' => 'لا توجد منتجات محددة سلفا لهذا الكائن. لذلك لا إرسال في المخزون المطلوب.',
		'DispatchVerb' => 'إيفاد',
		'StockLimitShort' => 'الحد',
		'StockLimit' => 'الأسهم للحد من التنبيهات',
		'PhysicalStock' => 'المخزون المادي',
		'RealStock' => 'الحقيقية للاسهم',
		'TheoreticalStock' => 'Therocial الأسهم',
		'VirtualStock' => 'الأسهم الافتراضية',
		'MininumStock' => 'الحد الأدنى للرصيد',
		'StockUp' => 'تخزين',
		'MininumStockShort' => 'الأسهم دقيقة',
		'StockUpShort' => 'تخزين',
		'IdWarehouse' => 'معرف مخزن',
		'DescWareHouse' => 'وصف المخزن',
		'LieuWareHouse' => 'المكان مخزن',
		'WarehousesAndProducts' => 'والمستودعات والمنتجات',
		'AverageUnitPricePMPShort' => 'متوسط أسعار المدخلات',
		'AverageUnitPricePMP' => 'متوسط أسعار المدخلات',
		'SellPriceMin' => 'Selling Unit Price',
		'EstimatedStockValueSellShort' => 'Value to sell',
		'EstimatedStockValueSell' => 'Value to Sell',
		'EstimatedStockValueShort' => 'وتقدر قيمة المخزون',
		'EstimatedStockValue' => 'وتقدر قيمة المخزون',
		'DeleteAWarehouse' => 'حذف مستودع',
		'ConfirmDeleteWarehouse' => 'هل أنت متأكد أنك تريد حذف <b>%s</b> مستودع؟',
		'PersonalStock' => '%s طبيعة الشخصية',
		'ThisWarehouseIsPersonalStock' => 'هذا يمثل مستودع للطبيعة الشخصية لل%s %s',
		'SelectWarehouseForStockDecrease' => 'Choose warehouse to use for stock decrease',
		'SelectWarehouseForStockIncrease' => 'Choose warehouse to use for stock increase',
		'LastWaitingSupplierOrders' => 'Orders waiting for receptions'
);
?>