<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Kategori',
		'Categories' => 'Kategorier',
		'Rubrique' => 'Kategori',
		'Rubriques' => 'Kategorier',
		'categories' => 'kategorier',
		'TheCategorie' => 'Kategorien',
		'In' => 'I',
		'AddIn' => 'Legg til i',
		'modify' => 'endre',
		'Classify' => 'Klassifiser',
		'CategoriesArea' => 'Kategoriområde',
		'ProductsCategoriesArea' => 'Område for kategorier : produkter/tjenester',
		'SuppliersCategoriesArea' => 'Område for kategorier : Leverandører',
		'CustomersCategoriesArea' => 'Område for kategorier : Kunder',
		'ThirdPartyCategoriesArea' => 'Område for kategorier : Tredjeparter',
		'MainCats' => 'Hovedkategorier',
		'SubCats' => 'Underkategorier',
		'CatStatistics' => 'Statistikk',
		'CatList' => 'Oversikt over kategorier',
		'AllCats' => 'Alle kategorier',
		'ViewCat' => 'Vis kategori',
		'NewCat' => 'Legg til kategori',
		'NewCategory' => 'Ny kategori',
		'ModifCat' => 'Endre kategori',
		'CatCreated' => 'Kategori opprettet',
		'CreateCat' => 'Opprett kategori',
		'CreateThisCat' => 'Opprett denne kategorien',
		'ValidateFields' => 'Godkjenn feltene',
		'NoSubCat' => 'Ingen underkategori.',
		'SubCatOf' => 'Undekategori',
		'FoundCats' => 'Kategorier funnet',
		'FoundCatsForName' => 'Fant kategorier med navnet :',
		'FoundSubCatsIn' => 'Undekategorier funnet i kategorien',
		'ErrSameCatSelected' => 'Du har valgt samme kategori flere ganger',
		'ErrForgotCat' => 'Du glemte å velge kategorien',
		'ErrForgotField' => 'Du glemte feltene',
		'ErrCatAlreadyExists' => 'Dette navnet er allerede i bruk',
		'AddProductToCat' => 'Legg dette produktet til en kategori?',
		'ImpossibleAddCat' => 'Umulig å legge til kategorien',
		'ImpossibleAssociateCategory' => 'Umulig å knytte kategorien til',
		'WasAddedSuccessfully' => '<b>%s</b> ble lagt til.',
		'ObjectAlreadyLinkedToCategory' => 'Elementet er allerede lenket til denne kategorien.',
		'CategorySuccessfullyCreated' => 'Kategorien %s er opprettet.',
		'ProductIsInCategories' => 'Dette produktet/tjenesten hører til følgende kategorier',
		'SupplierIsInCategories' => 'Denne tredjeparten hører til følgende leverandørkategorier',
		'CompanyIsInCustomersCategories' => 'Denne tredjeparten hører til følgende kunder/prospektkategorier',
		'CompanyIsInSuppliersCategories' => 'Denne tredjeparten hører til følgende leverandørkategorier',
		'ProductHasNoCategory' => 'Dette produktet/tjenesten er ikke i noen kategorier',
		'SupplierHasNoCategory' => 'Denne leverandøren er ikke i noen kategorier',
		'CompanyHasNoCategory' => 'Dette firmaet er ikke i noen kategorier',
		'ClassifyInCategory' => 'Klassifiser i kategori',
		'NoneCategory' => 'Ingen',
		'CategoryExistsAtSameLevel' => 'Denne kategorien eksisterer allerede på samme sted',
		'ReturnInProduct' => 'Tilbake til produkt/tjeneste-kort',
		'ReturnInSupplier' => 'Tilbake til leverandørkort',
		'ReturnInCompany' => 'Tilbake til kunde/prospekt-kort',
		'ContentsVisibleByAll' => 'Inneholdet vil være synlig for alle',
		'ContentsVisibleByAllShort' => 'Innhold synlig for alle',
		'ContentsNotVisibleByAllShort' => 'Innhold ikke synlig for alle',
		'CategoriesTree' => 'Kategoristruktur',
		'DeleteCategory' => 'Slett kategori',
		'ConfirmDeleteCategory' => 'Er du sikker på at du vil slette denne kategorien?',
		'RemoveFromCategory' => 'Fjern lenke med kategori',
		'RemoveFromCategoryConfirm' => 'Er di sikker på at du vil fjerne lenken mellom transaksjonen og kategorien?',
		'NoCategoriesDefined' => 'Ingen kategori definert',
		'SuppliersCategoryShort' => 'Leverandøkategori',
		'CustomersCategoryShort' => 'Kundekategori',
		'ProductsCategoryShort' => 'Produktkategori',
		'SuppliersCategoriesShort' => 'Leverandøkategorier',
		'CustomersCategoriesShort' => 'Kundekategorier',
		'CustomersProspectsCategoriesShort' => 'Kunde/prospektkategorier',
		'ProductsCategoriesShort' => 'Produktkategorier',
		'ThisCategoryHasNoProduct' => 'Denne kategorien inneholder ingen produkter.',
		'ThisCategoryHasNoSupplier' => 'Denne kategorien inneholder ingen leverandører.',
		'ThisCategoryHasNoCustomer' => 'Denne kategorien inneholder ingen kunder.',
		'AssignedToCustomer' => 'Knyttet til en kunde',
		'AssignedToTheCustomer' => 'Knyttet til kunden',
		'InternalCategory' => 'Intern kategori',
		'CategoryContents' => 'Innhold i kategori',
		'CategId' => 'Kategori-ID',
		'NoCategoryYet' => 'Ingen kategori av denne typen er opprettet',
		'MembersCategoriesArea' => 'Medlemmer kategorier området',
		'MemberIsInCategories' => 'Dette medlemmet eier til følgende medlemmer kategorier',
		'MemberHasNoCategory' => 'Dette medlem er ikke i noen kategorier',
		'MembersCategoryShort' => 'Medlemmer kategori',
		'MembersCategoriesShort' => 'Medlemmer kategorier',
		'ThisCategoryHasNoMember' => 'Denne kategorien inneholder ingen medlem.',
		'CatSupList' => 'Liste av leverandør kategorier',
		'CatCusList' => 'Liste over kunde / prospektet kategorier',
		'CatProdList' => 'Liste over produkter kategorier',
		'CatMemberList' => 'Liste over medlemmer kategorier',
);
?>