<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Handel',
		'CommercialArea' => 'Handelsområde',
		'CommercialCard' => 'Handelskort',
		'CustomerArea' => 'Kundeområde',
		'Customer' => 'Kunde',
		'Customers' => 'Kunder',
		'Prospect' => 'Prospekt',
		'Prospects' => 'Prospekter',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Slett handling/oppgave',
		'NewAction' => 'Ny handling/oppgave',
		'AddAction' => 'Legg til handling/oppgave',
		'AddAnAction' => 'Legg til en handling/oppgave',
		'AddActionRendezVous' => 'Legg til møte',
		'Rendez-Vous' => 'Rendezvous',
		'ConfirmDeleteAction' => 'Er du sikker på at du vil slette denne oppgaven?',
		'CardAction' => 'Handlingskort',
		'PercentDone' => 'Prosent ferdig',
		'ActionOnCompany' => 'Oppgave ifm. firma',
		'ActionOnContact' => 'Oppgave ifg. kontaktperson',
		'TaskRDV' => 'Møter',
		'TaskRDVWith' => 'Møte med %s',
		'ShowTask' => 'Vis oppgave',
		'ShowAction' => 'Vis handling',
		'ActionsReport' => 'Handlingsrapport',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Salgsreprsentant',
		'SalesRepresentatives' => 'Salgsrepresentanter',
		'SalesRepresentativeFollowUp' => 'Salgsrepresentant (oppfølging)',
		'SalesRepresentativeSignature' => 'Salgsrepresentant (signatur)',
		'CommercialInterlocutor' => 'Commercial interlocutor',
		'ErrorWrongCode' => 'Feil kode',
		'NoSalesRepresentativeAffected' => 'Ingen spesiell salgsrepresentant tilknyttet',
		'ShowCustomer' => 'Vis kunde',
		'ShowProspect' => 'Vis prospekt',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Oversikt over prospekter',
		'ListOfCustomers' => 'Oversikt over kunder',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'Siste %s utførte oppgaver',
		'LastRecordedTasks' => 'Siste registrerte oppgaver',
		'LastActionsToDo' => 'Siste %s eldste handlinger som ikke er fullført',
		'DoneAndToDoActionsFor' => 'Utførte og åpne oppgaver for %s',
		'DoneAndToDoActions' => 'Utførte og åpne oppgaver',
		'DoneActions' => 'Utførte handlinger',
		'DoneActionsFor' => 'Utførte handlinger for %s',
		'ToDoActions' => 'Ikke fullførte handlinger',
		'ToDoActionsFor' => 'Ikke fullførte handlinger for %s',
		'SendPropalRef' => 'Send tilbud %s',
		'SendOrderRef' => 'Send ordre %s',
		'StatusNotApplicable' => 'Ikke aktuelt',
		'StatusActionToDo' => 'To Do',
		'StatusActionDone' => 'Utført',
		'StatusActionInProcess' => 'I arbeid',
		'MyActionsAsked' => 'Handlinger jeg har registrert',
		'MyActionsToDo' => 'Handlinger jeg må gjøre',
		'MyActionsDone' => 'Handlinger knyttet til meg',
		'TasksHistoryForThisContact' => 'Handlinger for denne kontaktpersonen',
		'LastProspectDoNotContact' => 'Kontaktes ikke',
		'LastProspectNeverContacted' => 'Aldri kontaktet',
		'LastProspectToContact' => 'Bør kontaktes',
		'LastProspectContactInProcess' => 'Kontakt pågår',
		'LastProspectContactDone' => 'Kontakt utført',
		'DateActionPlanned' => 'Dato for planlagt handling',
		'DateActionDone' => 'Dato for utført handling',
		'ActionAskedBy' => 'Handling ønsket av',
		'ActionAffectedTo' => 'Handling knyttet til',
		'ActionDoneBy' => 'Handling utført av',
		'ActionUserAsk' => 'Registrert av',
		'ErrorStatusCantBeZeroIfStarted' => 'Hvis feltet \'<b>Dato utført</b>\' er fylt ut er handlingen startet (eller utført), defor kan ikke feltet \'<b>Status</b>\' være 0%%.',
		'ActionAC_TEL' => 'Telefonsamtale',
		'ActionAC_FAX' => 'Send fax',
		'ActionAC_PROP' => 'Send tilbud',
		'ActionAC_EMAIL' => 'Send e-post',
		'ActionAC_RDV' => 'Møter',
		'ActionAC_FAC' => 'Send faktura',
		'ActionAC_REL' => 'Send purring',
		'ActionAC_CLO' => 'Lukk',
		'ActionAC_EMAILING' => 'Send e-postutsendelse (massemailing)',
		'ActionAC_COM' => 'Send ordre i posten',
		'ActionAC_SHIP' => 'Send levering post',
		'ActionAC_SUP_ORD' => 'Send leverandør bestill ved mail',
		'ActionAC_SUP_INV' => 'Send leverandør faktura i posten',
		'ActionAC_OTH' => 'Andre',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Prospect status',
		'DraftPropals' => 'Utkast kommersielle forslag',
		'SearchPropal' => 'Søk en kommersiell forslag'
);
?>