<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$install = array(
		'CHARSET' => 'UTF-8',
		'InstallEasy' => 'Bare følg instruksjonene trinn for trinn.',
		'MiscellanousChecks' => 'Forutsetninger sjekk',
		'SpeedealingWelcome' => 'Welcome to Speedealing',
		'ConfFileExists' => 'Konfigurasjonsfil <b>%s</b> eksisterer.',
		'ConfFileDoesNotExists' => 'Konfigurasjonsfil <b>%s</b> finnes ikke!',
		'ConfFileDoesNotExistsAndCouldNotBeCreated' => 'Konfigurasjonsfil <b>%s</b> eksisterer ikke og kunne ikke opprettes!',
		'ConfFileCouldBeCreated' => 'Konfigurasjonsfil <b>%s</b> kunne bli skapt.',
		'ConfFileIsNotWritable' => 'Konfigurasjonsfil <b>%s</b> er ikke skrivbar. Sjekk tillatelser. For første installere, må webserveren få innvilget å kunne skrive inn i denne filen under konfigureringen ("chmod 666" for eksempel på en Unix som OS).',
		'ConfFileIsWritable' => 'Konfigurasjonsfil <b>%s</b> er skrivbar.',
		'ConfFileReload' => 'Reload all informasjon fra konfigurasjonsfilen.',
		'PHPSupportSessions' => 'Dette PHP støtter sesjoner.',
		'PHPSupportPOSTGETOk' => 'Dette PHP støtter variabler POST og GET.',
		'PHPSupportPOSTGETKo' => 'Det er mulig at din PHP-oppsettet støtter ikke variabler POST og / eller GET. Sjekk din parameter <b>variables_order</b> i php.ini.',
		'PHPSupportGD' => 'Denne PHP-støtte GD grafiske funksjoner.',
		'PHPSupportUTF8' => 'Denne PHP-støtte UTF8 funksjoner.',
		'PHPMemoryOK' => 'Din PHP max økten minnet er satt til <b>%s.</b> Dette bør være nok.',
		'PHPMemoryTooLow' => 'Din PHP max økten minnet er satt til <b>%s</b> bytes. Dette bør være for lav. Endre <b>php.ini</b> å sette <b>memory_limit</b> parameter til minst <b>%s</b> byte.',
		'Recheck' => 'Klikk her for en mer significative test',
		'ErrorPHPDoesNotSupportSessions' => 'Din PHP installasjon har ikke støtte for sesjoner. Denne funksjonen er nødvendig for å gjøre Speedealing jobbe. Sjekk din PHP oppsett.',
		'ErrorPHPDoesNotSupportGD' => 'Din PHP installasjon har ikke støtte for grafiske funksjonen GD. Ingen grafen vil være tilgjengelig.',
		'ErrorPHPDoesNotSupportUTF8' => 'Din PHP installasjon har ikke støtte for UTF8 funksjoner. Speedealing kan ikke fungere riktig. Løs dette før du installerer Speedealing.',
		'ErrorDirDoesNotExists' => 'Directory %s finnes ikke.',
		'ErrorGoBackAndCorrectParameters' => 'Gå bakover og korrigere feil parametre.',
		'ErrorWrongValueForParameter' => 'Du har kanskje skrevet feil verdi for parameteren \'%s\'.',
		'ErrorFailedToCreateDatabase' => 'Kunne ikke opprette database \'%s\'.',
		'ErrorFailedToConnectToDatabase' => 'Kunne ikke koble til database \'%s\'.',
		'ErrorDatabaseVersionTooLow' => 'Database version (%s) too old. Version %s or higher is required.',
		'ErrorPHPVersionTooLow' => 'PHP-versjonen for gammel. Versjon %s er nødvendig.',
		'WarningPHPVersionTooLow' => 'PHP-versjonen for gammel. Versjon %s eller mer er ventet. Denne versjonen bør tillate installere, men er ikke støttet.',
		'ErrorConnectedButDatabaseNotFound' => 'Tilkobling til server vellykket, men database \'%s\' ikke funnet.',
		'ErrorDatabaseAlreadyExists' => 'Database \'%s\' finnes allerede.',
		'IfDatabaseNotExistsGoBackAndUncheckCreate' => 'Hvis databasen ikke finnes, gå tilbake og sjekke alternativet "Opprett database".',
		'IfDatabaseExistsGoBackAndCheckCreate' => 'Hvis databasen allerede eksisterer, gå tilbake og fjern "Opprett database" alternativet.',
		'WarningBrowserTooOld' => 'Too old version of browser. Upgrading your browser to a recent version of Firefox, Chrome or Opera is highly recommanded.',
		'PHPVersion' => 'PHP versjon',
		'YouCanContinue' => 'Du kan fortsette ...',
		'PleaseBePatient' => 'Vær tålmodig ...',
		'License' => 'Bruke lisens',
		'ConfigurationFile' => 'Konfigurasjonsfil',
		'WebPagesDirectory' => 'Katalog der hvor web sider er lagret',
		'DocumentsDirectory' => 'Katalog for å lagre lastet opp og genererte dokumenter',
		'URLRoot' => 'URL Root',
		'ForceHttps' => 'Force sikre tilkoblinger (https)',
		'CheckToForceHttps' => 'Sjekk dette alternativet for å tvinge sikre tilkoblinger (https). <br> Dette krever at web-serveren er satt opp med en SSL-sertifikat.',
		'SpeedealingDatabase' => 'Speedealing Database',
		'DatabaseChoice' => 'Database valg',
		'DatabaseType' => 'Database type',
		'DriverType' => 'Driver type',
		'Server' => 'Server',
		'ServerAddressDescription' => 'Navn eller IP-adressen til database-serveren, som regel "localhost" når database server ligger på samme server enn webserveren',
		'ServerPortDescription' => 'Database server port. Hold tomt hvis ukjent.',
		'DatabaseServer' => 'Databaseserveren',
		'DatabaseName' => 'Databasenavn',
		'DatabasePrefix' => 'Database prefiks bord',
		'Login' => 'Innlogging',
		'AdminLogin' => 'Logg inn for Speedealing database eier.',
		'Password' => 'Passord',
		'PasswordAgain' => 'Skriv inn passordet en gang',
		'AdminPassword' => 'Passord for Speedealing database eier.',
		'CreateDatabase' => 'Opprett database',
		'CreateUser' => 'Lag eier',
		'DatabaseSuperUserAccess' => 'Databaseserveren - Superbruker tilgang',
		'CheckToCreateDatabase' => 'Boksen hvis databasen finnes ikke og må lages. <br> I dette tilfellet må du fylle login / passord for superuser kontoen nederst på denne siden.',
		'CheckToCreateUser' => 'Boksen hvis databasen eieren ikke eksisterer og må opprettes. <br> I dette tilfellet må du velge sin login og passord, og også fylle brukernavn / passord for superuser kontoen nederst på denne siden. Hvis denne boksen ikke er avkrysset, eier database og passord må finnes.',
		'Experimental' => '(Eksperimentell)',
		'DatabaseRootLoginDescription' => 'Logg inn av brukeren lov til å opprette nye databaser eller nye brukere, ubrukelig hvis databasen og databasen din logikk allerede eksisterer (som når du er vert for en web hosting leverandør).',
		'KeepEmptyIfNoPassword' => 'La det være tomt hvis bruker har ingen passord (unngå denne)',
		'SaveConfigurationFile' => 'Lagre verdier',
		'ConfigurationSaving' => 'Lagrer konfigurasjonsfil',
		'ServerConnection' => 'Server-tilkobling',
		'DatabaseConnection' => 'Databasetilkobling',
		'DatabaseCreation' => 'Database opprettelse',
		'UserCreation' => 'Bruker opprettelse',
		'CreateDatabaseObjects' => 'Databaseobjekter opprettelse',
		'ReferenceDataLoading' => 'Referanse data lasting',
		'TablesAndPrimaryKeysCreation' => 'Tabeller og primærnøkler opprettelse',
		'CreateTableAndPrimaryKey' => 'Lag tabell %s',
		'CreateOtherKeysForTable' => 'Lag utenlandske nøkler og indekser for bord %s',
		'OtherKeysCreation' => 'Utenlandske nøkler og indekser opprettelse',
		'FunctionsCreation' => 'Funksjoner opprettelse',
		'AdminAccountCreation' => 'Administrator login opprettelse',
		'PleaseTypePassword' => 'Vennligst skriv inn et passord, er tomt passord ikke tillatt!',
		'PleaseTypeALogin' => 'Vennligst skriv inn en logikk!',
		'PasswordsMismatch' => 'Passord skiller, vennligst prøv igjen!',
		'SetupEnd' => 'Slutt på oppsett',
		'SystemIsInstalled' => 'Denne installasjonen er fullført.',
		'SystemIsUpgraded' => 'Speedealing har blitt oppgradert med hell.',
		'YouNeedToPersonalizeSetup' => 'Du må konfigurere Speedealing som passer dine behov (utseende, funksjoner, ...). For å gjøre dette, vennligst følg lenken nedenfor:',
		'AdminLoginCreatedSuccessfuly' => 'Speedealing administrator login <b>\'%s\'</b> opprettet heldig.',
		'GoToSpeedealing' => 'Go to Speedealing',
		'GoToSetupArea' => 'Gå til Speedealing (setup-området)',
		'MigrationNotFinished' => 'Versjon av dtabase din ikke er helt oppdatert, så du må kjøre upgrade prosessen igjen.',
		'GoToUpgradePage' => 'Gå til side oppgradere igjen',
		'Examples' => 'Eksempler',
		'WithNoSlashAtTheEnd' => 'Uten skråstrek "/" på slutten',
		'DirectoryRecommendation' => 'Det er recommanded å bruke en ut av ditt katalogen av websidene dine.',
		'LoginAlreadyExists' => 'Det finnes allerede',
		'SpeedealingAdminLogin' => 'Speedealing admin login',
		'AdminLoginAlreadyExists' => 'Speedealing administratorkonto <b>\'%s\'</b> finnes allerede.',
		'WarningRemoveInstallDir' => 'Advarsel, av sikkerhetshensyn, når installere eller oppgraderingen er fullført, bør du fjerne <b>installerer katalogen eller endre navnet til install.lock for å unngå den skadelige bruk.</b>',
		'ThisPHPDoesNotSupportTypeBase' => 'Dette PHP Systemet støtter ikke noen grensesnitt for å få tilgang til databasen type %s',
		'FunctionNotAvailableInThisPHP' => 'Ikke tilgjengelig på denne PHP',
		'MigrateScript' => 'Migrasjon script',
		'ChoosedMigrateScript' => 'Velg migrasjon script',
		'DataMigration' => 'Datamigrering',
		'DatabaseMigration' => 'Struktur databasen migrasjon',
		'ProcessMigrateScript' => 'Script behandling',
		'ChooseYourSetupMode' => 'Velg ditt oppsett modus og klikk på "Start" ...',
		'FreshInstall' => 'Frisk installere',
		'FreshInstallDesc' => 'Bruk denne modusen hvis dette er den første installere. Hvis ikke, kan denne modusen reparere en ufullstendig tidligere installere, men hvis du ønsker å oppgradere din versjon, velg "Oppgrader" modus.',
		'Upgrade' => 'Oppgrader',
		'UpgradeDesc' => 'Bruk denne modusen hvis du har erstattet gamle Speedealing filene med filer fra en nyere versjon. Dette vil oppgradere din database og data.',
		'Start' => 'Start',
		'InstallNotAllowed' => 'Installasjonsprogrammet ikke tillates av <b>conf.php</b> tillatelser',
		'NotAvailable' => 'Ikke tilgjengelig',
		'YouMustCreateWithPermission' => 'Du må lage filen %s og sette skriverettigheter på den for web-serveren under installasjonsprosessen.',
		'CorrectProblemAndReloadPage' => 'Rett problemet og trykk F5 for å laste siden.',
		'AlreadyDone' => 'Allerede migrert',
		'DatabaseVersion' => 'Database versjon',
		'ServerVersion' => 'Databaseserveren versjon',
		'YouMustCreateItAndAllowServerToWrite' => 'Du må lage denne katalogen og la for web-serveren til å skrive inn i den.',
		'CharsetChoice' => 'Tegnsett valg',
		'CharacterSetClient' => 'Tegnsett brukes for genererte HTML-nettsider',
		'CharacterSetClientComment' => 'Velg tegnsettet for web visning. <br/> Standard foreslåtte tegnsett er en av databasen.',
		'CollationConnection' => 'Tegn sorteringsrekkefølgen',
		'CollationConnectionComment' => 'Velg side kode som definerer figuren sorteringsrekkefølgen brukes av databasen. Denne parameteren blir også kalt "sortering" av noen databaser. <br/> Denne parameteren kan ikke defineres dersom databasen allerede eksisterer.',
		'CharacterSetDatabase' => 'Tegnsettet for databasen',
		'CharacterSetDatabaseComment' => 'Velg tegnsettet ettersøkt for database skaperverk. <br/> Denne parameteren kan ikke defineres dersom databasen allerede eksisterer.',
		'YouAskDatabaseCreationSoSpeedealingNeedToConnect' => 'You ask to create database <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'YouAskLoginCreationSoSpeedealingNeedToConnect' => 'You ask to create database login <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'BecauseConnectionFailedParametersMayBeWrong' => 'Som tilkobling mislyktes, må vert eller super bruker parametere være feil.',
		'OrphelinsPaymentsDetectedByMethod' => 'Orphans innbetaling oppdaget av metoden %s',
		'RemoveItManuallyAndPressF5ToContinue' => 'Fjerne det manuelt, og trykk F5 for å fortsette.',
		'KeepDefaultValuesWamp' => 'Du bruker Speedealing konfigureringsveiviseren fra DoliWamp, verdiene slik foreslått her, er allerede optimalisert. Endre dem bare hvis du vet hva du gjør.',
		'KeepDefaultValuesDeb' => 'Du bruker Speedealing konfigurasjonsveiviseren fra en Ubuntu eller Debian-pakke, så verdiene foreslått her allerede er optimalisert. Bare passordet til databasen eieren til å opprette må fullføres. Endre andre parametere bare hvis du vet hva du gjør.',
		'KeepDefaultValuesMamp' => 'Du bruker Speedealing konfigureringsveiviseren fra DoliMamp, verdiene slik foreslått her, er allerede optimalisert. Endre dem bare hvis du vet hva du gjør.',
		'KeepDefaultValuesProxmox' => 'Du bruker Speedealing setup wizard fra en Proxmox Virtual Appliance, så verdiene foreslått her, er allerede optimalisert. Bytt dem bare hvis du vet hva du gjør.',
		'FieldRenamed' => 'Field omdøpt',
		'IfLoginDoesNotExistsCheckCreateUser' => 'Hvis logikk ikke eksisterer ennå, må du sjekke alternativet "Opprett bruker"',
		'ErrorConnection' => 'Server <b>"%s",</b> databasenavn <b>"%s",</b> logg inn <b>"%s",</b> eller database passordet er feil eller PHP-klient-versjon kan være for gammel i forhold til database versjon.',
		'InstallChoiceRecommanded' => 'Anbefalt valget å installere versjon <b>%s</b> fra din nåværende versjonen <b>%s</b>',
		'InstallChoiceSuggested' => '<b>Installer valg foreslått av installatør.</b>',
		'MigrateIsDoneStepByStep' => 'Den målrettede versjonen (%s) har et gap på flere versjoner, så installasjonsveiviseren vil komme tilbake til å foreslå neste migrasjon når denne vil bli ferdig.',
		'CheckThatDatabasenameIsCorrect' => 'Sjekk at database navn <b>"%s"</b> er korrekt.',
		'IfAlreadyExistsCheckOption' => 'Hvis dette navnet er riktig, og at databasen ikke eksisterer ennå, du må sjekke alternativet "Opprett database".',
		'OpenBaseDir' => 'PHP openbasedir parameter',
		'YouAskToCreateDatabaseSoRootRequired' => 'Du merket "Opprett database". For dette, må du oppgi brukernavn / passord av superbruker (nederst på skjemaet).',
		'YouAskToCreateDatabaseUserSoRootRequired' => 'Du merket "Opprett database eier". For dette, må du oppgi brukernavn / passord av superbruker (nederst på skjemaet).',
		'NextStepMightLastALongTime' => 'Gjeldende trinn kan vare i flere minutter. Vennligst vent til neste skjermbildet vises helt før du fortsetter.',
		'LastStepDesc' => '<strong>Siste trinn:</strong> Definer her login og passord du har tenkt å bruke til å koble til programvare. Ikke mist dette som det er kontoen for å administrere alle andre.',
		'ActivateModule' => 'Aktiver modulen %s',
		'ShowEditTechnicalParameters' => 'Click here to show/edit advanced parameters (expert mode)',
		'ServerPortCouchdbDescription' => 'Port du serveur. Défaut 5984.',
		'ServerAddressCouchdbDescription' => 'Nom FQDN du serveur de base de données, \'localhost.localdomain\' quand le serveur est installé sur la même machine que le serveur web',
		'DatabaseCouchdbUserDescription' => 'Login du super administrateur ayant tous les droits sur le serveur CouchDB ou l\'administrateur propriétaire de la base si la base et son compte d\'accès existent déjà (comme lorsque vous êtes chez un hébergeur).<br><br><div class="alert-box info">Cet utilisateur/mot de passe sera l\'administrateur pour se connecter à Speedealing.</div>',
		'CheckToCreateCouchdbDatabase' => 'Cochez cette option si la base de données n\'existe pas et doit être créée.',
		'CreateAdminUser' => 'Créer le super administrateur (Première installation de couchDB)',
		'MemcachedDescription' => 'Activer Memcached necessite l\'installation d\'un serveur Memcached et des lib php-memcached ou php-memcache. Il peut être activer après l\'installation.',
		'ServerAddressMemcachedDesc' => 'Nom ou adresse ip du serveur memcached, généralement \'localhost\' quand le serveur est installé sur la même machine que le serveur web',
		'ServerPortMemcachedDesc' => 'Port du serveur memcached. Défaut : 11211',
		'EnabledMemcached' => 'Activer Memcached',
		'DatabaseNoSQL' => 'Base de données CouchDB',
		'FailedToCreateAdminLogin' => 'Echec de la création du compte administrateur Speedealing.',
		'LinkedElementsInvalidDeleted' => '<b>%s</b> liaisons invalides ont été supprimées',
		'NothingToDelete' => 'Aucune liaison invalide trouvée',
		'SourceType' => 'Source',
		'TargetType' => 'Cible',
                // Upgrade
                'UpgradeOk' => 'Upgrade is ok !',
                'NewInstalledVersion' => 'Your new version is %s',
                'NeedUpgrade' => 'New Speedealing version !',
                'WarningUpgrade' => 'Installed version is %s, you must upgrade to %s. <br>Please contact your administrator.'
);
?>