<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$mails = array(
		'CHARSET' => 'UTF-8',
		'Mailing' => 'E-postutsendelser',
		'EMailing' => 'E-postutsendelser',
		'Mailings' => 'E-postutsendelser',
		'EMailings' => 'E-postutsendelser',
		'AllEMailings' => 'Alle eMailings',
		'MailCard' => 'E-postkort',
		'MailTargets' => 'Målgruppe',
		'MailRecipients' => 'Mottagere',
		'MailRecipient' => 'Mottager',
		'MailTitle' => 'Kampanjetittel',
		'MailFrom' => 'Avsender',
		'MailErrorsTo' => 'Feilmeldinger til',
		'MailReply' => 'Svar til',
		'MailTo' => 'Mottaker(e)',
		'MailCC' => 'Kopi til',
		'MailCCC' => 'Cached kopi til',
		'MailTopic' => 'E-postemne',
		'MailText' => 'Meldingstekst',
		'MailFile' => 'Filvedlegg',
		'MailMessage' => 'Meldingstekst',
		'ShowEMailing' => 'Vis utsendelse',
		'ListOfEMailings' => 'Oversikt over utsendelser',
		'NewMailing' => 'Ny utsendelse',
		'EditMailing' => 'Rediger utsendelse',
		'ResetMailing' => 'Send e-post',
		'DeleteMailing' => 'Slett utsendelse',
		'DeleteAMailing' => 'Slett en utsendelse',
		'PreviewMailing' => 'Forhåndsvis utsendelse',
		'PrepareMailing' => 'Klargjør utsendelse',
		'CreateMailing' => 'Opprett utsendelse',
		'MailingDesc' => 'Her kan du sende e-postutesendelser til grupper av mottagere.',
		'MailingResult' => 'Sendingsresultat',
		'TestMailing' => 'Test utsendelse',
		'ValidMailing' => 'Godkjenn utsendelse',
		'ApproveMailing' => 'Aksepter utsendelse',
		'MailingStatusDraft' => 'Kladd',
		'MailingStatusValidated' => 'Godkjent',
		'MailingStatusApproved' => 'Akseptert',
		'MailingStatusSent' => 'Sendt',
		'MailingStatusSentPartialy' => 'Delvis sendt',
		'MailingStatusSentCompletely' => 'Sendt fullt ut',
		'MailingStatusError' => 'Feil',
		'MailingStatusNotSent' => 'Ikke sendt',
		'MailSuccessfulySent' => 'E-post ble sendt (fra %s til %s)',
		'MailingSuccessfullyValidated' => 'EMailing successfully validated',
		'MailUnsubcribe' => 'Unsubscribe',
		'Unsuscribe' => 'Unsubscribe',
		'MailingStatusNotContact' => 'Don\'t contact anymore',
		'ErrorMailRecipientIsEmpty' => 'E-postmottager er ikke oppgitt',
		'WarningNoEMailsAdded' => 'Ingen ny e-post å legge til mottagerlisten.',
		'ConfirmValidMailing' => 'Er du sikker på at du vil godkjenne utsendelsen?',
		'ConfirmResetMailing' => 'Advarsel ved reinitializing emailing <b>%s,</b> kan du gjøre en masse sending av denne e-en annen gang. Er du sikker på at du dette er hva du vil gjøre?',
		'ConfirmDeleteMailing' => 'Er du sikker på at du vil slette utsendelsen?',
		'NbOfRecipients' => 'Antall mottagere',
		'NbOfUniqueEMails' => 'Ant. unike e-poster',
		'NbOfEMails' => 'Ant. e-poster',
		'TotalNbOfDistinctRecipients' => 'Antall bestemte mottagere',
		'NoTargetYet' => 'Ingen mottagere angitt (Gå til fanen \'Mottakere\')',
		'AddRecipients' => 'Legg til mottakere',
		'RemoveRecipient' => 'Fjern mottaker',
		'CommonSubstitutions' => 'Vanlige flettefelt',
		'YouCanAddYourOwnPredefindedListHere' => 'Les mer om hvordan du lager din egen utvalgsliste her: htdocs/core/modules/mailings/README.',
		'EMailTestSubstitutionReplacedByGenericValues' => 'Når du er i testmodus blir flettefelt erstattet med generiske verdier',
		'MailingAddFile' => 'Legg ved denne filen',
		'NoAttachedFiles' => 'Ingen vedlagte filer',
		'BadEMail' => 'Ugyldig verdi for Email',
		'CloneEMailing' => 'Clone Emailing',
		'ConfirmCloneEMailing' => 'Er du sikker på at du vil klone denne e-post?',
		'CloneContent' => 'Clone melding',
		'CloneReceivers' => 'Cloner mottakere',
		'DateLastSend' => 'Dato for siste sending',
		'DateSending' => 'Dato sending',
		'SentTo' => 'Sendt til <b>%s</b>',
		'MailingStatusRead' => 'Les',
		'CheckRead' => 'Read Receipt',
		'YourMailUnsubcribeOK' => 'The email <b>%s</b>  is correctly unsubcribe from mailing list',
		'MailtoEMail' => 'Hyper link to email',
		'ActivateCheckRead' => 'Allow to use the Read receipt tracker and the unsubcribe link',
		'ActivateCheckReadKey' => 'Key use to encrypt URL use for Read Receipt and unsubcribe function',
		// Libelle des modules de liste de destinataires mailing
		'MailingModuleDescContactCompanies' => 'Alle tredjeparters kontaktpersoner (kunder, prospekter, leverandører, ...)',
		'MailingModuleDescSpeedealingUsers' => 'Speedealing users',
		'MailingModuleDescFundationMembers' => 'Medlemmer med e-postadresser',
		'MailingModuleDescEmailsFromFile' => 'E-poster lest inn fra teksttil (e-post;fornavn;etternavn)',
		'MailingModuleDescEmailsFromUser' => 'EMails from user input (email;lastname;firstname;other)',
		'MailingModuleDescContactsCategories' => 'Alle tredjeparters kontakter (etter kategori)',
		'MailingModuleDescSpeedealingContractsLinesExpired' => 'Third parties with expired contract\'s lines',
		'MailingModuleDescContactsByCompanyCategory' => 'Kontakter til tredjeparter (av tredjeparter kategori)',
		'MailingModuleDescMembersCategories' => 'Foundation medlemmer etter kategorier)',
		'MailingModuleDescContactsByFunction' => 'Kontakter til tredjeparter (av stilling / funksjon)',
		'LineInFile' => 'Antall linjer i filen: %s',
		'RecipientSelectionModules' => 'Foresøprsel om lesebekreftelse',
		'MailSelectedRecipients' => 'Valgte mottagere',
		'MailingArea' => 'Område for e-postutsendelser',
		'LastMailings' => 'Siste %s utsendelser',
		'TargetsStatistics' => 'Statistikk over målgruppe',
		'NbOfCompaniesContacts' => 'Unike kontaktpersoner for firmaer',
		'MailNoChangePossible' => 'Du kan ikke endre mottagere når utsendelsen er godkjent',
		'SearchAMailing' => 'Finn utsendelse',
		'SendMailing' => 'Send utesendelse',
		'SendMail' => 'Send e-post',
		'SentBy' => 'Sendt av',
		'MailingNeedCommand' => 'Av sikkerhetsgrunner kan utsendelser bare foretas fra kommandolinja. Be administrator om å kjøre følgedne kommando for å starte utsendelsen:',
		'MailingNeedCommand2' => 'Du kan imidlertid sende dem online ver å sette parameteret MAILING_LIMIT_SENDBYWEB til en verdi tilsvarende den maksimale antalle e-poster du ønsker å sende i en økt.',
		'ConfirmSendingEmailing' => 'Er du sikker på at du vil starte utsendelsen?<br>Av sikkerhetsgrunner er antall maksimalt antall e-poster som kan sendes i en økt <b>%s</b>.',
		'LimitSendingEmailing' => 'Ny sending av emailings er begrenset for sikkerhet og tidsavbrudd grunner til å <b>%s</b> mottakere ved å sende økt.',
		'TargetsReset' => 'Tøm liste',
		'ToClearAllRecipientsClickHere' => 'Trykk på knappen for å tømme mottagerlisten',
		'ToAddRecipientsChooseHere' => 'Velg i listene for å legge til mottagere',
		'NbOfEMailingsReceived' => 'E-postutsendelser mottatt',
		'IdRecord' => 'Post ID',
		'DeliveryReceipt' => 'Mottaksbekreftelse',
		'YouCanUseCommaSeparatorForSeveralRecipients' => 'Du kan bruke <b>komma</b> skilletegn for å angi flere mottakere.',
		'TagCheckMail' => 'Track mail opening',
		'TagUnsubscribe' => 'Unsubscribe link',
		'TagSignature' => 'Signature sending user',
		'TagMailtoEmail' => 'Recipient EMail',
		// Module Notifications
		'Notifications' => 'Varsler',
		'NoNotificationsWillBeSent' => 'Ingen e-postvarsler er planlagt for denne hendelsen/firmaet',
		'ANotificationsWillBeSent' => '1 e-postvarsel vil bli sendt med e-post',
		'SomeNotificationsWillBeSent' => '%s e-postvarsler vil bli sendt med e-post',
		'AddNewNotification' => 'Slå på en ny varslingsforespørsel',
		'ListOfActiveNotifications' => 'Vis alle altive varslingsforespørsler',
		'ListOfNotificationsDone' => 'List alle e-postmeldinger sendt'
);
?>