<?php
/* Copyright (C) 2012-2013	Regis Houssin	<regis.houssin@capnetworks.com>
 * Copyright (C) 2012-2013	Herve Prot		<herve.prot@symeos.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$orders = array(
		'CHARSET' => 'UTF-8',
		'OrdersArea' => 'Område for kundeordre',
		'SuppliersOrdersArea' => 'Område for leverandørordre',
		'OrderCard' => 'Ordrekort',
		'OrderId' => 'Order Id',
		'Order' => 'Ordre',
		'Orders' => 'Ordre',
		'OrderLine' => 'Bestill linje',
		'OrderLines' => 'Order lines',
		'OrderFollow' => 'Oppfølging',
		'OrderDate' => 'Ordredato',
		'OrderToProcess' => 'For å kunne behandle',
		'NewOrder' => 'Ny ordre',
		'ToOrder' => 'Lag ordre',
		'MakeOrder' => 'Lag ordre',
		'SupplierOrder' => 'Leverandørordre',
		'SuppliersOrders' => 'Leverandørordre',
		'SuppliersOrdersRunning' => 'Aktuelle leverandørordre',
		'CustomerOrder' => 'Kundeordre',
		'CustomersOrders' => 'Kundeordre',
		'CustomersOrdersRunning' => 'Aktuelle kundeordre',
		'CustomersOrdersAndOrdersLines' => 'Kundeordre og ordrelinjer',
		'OrdersToValid' => 'Ordre til godkjenning',
		'OrdersToBill' => 'Ordre til fakturering',
		'OrdersInProcess' => 'Ordre under behandling',
		'OrdersToProcess' => 'Ordre til behandling',
		'SuppliersOrdersToProcess' => 'Leverandørens ordre om å behandle',
		'StatusOrderCanceledShort' => 'Kansellert',
		'StatusOrderDraftShort' => 'Kladd',
		'StatusOrderValidatedShort' => 'Godkjent',
		'StatusOrderSentShort' => 'I prosessen',
		'StatusOrderSent' => 'Shipment in process',
		'StatusOrderOnProcessShort' => 'Under behandling',
		'StatusOrderProcessedShort' => 'Behandlet',
		'StatusOrderToBillShort' => 'Til fakturering',
		'StatusOrderToBill2Short' => 'To bill',
		'StatusOrderApprovedShort' => 'Godkjent',
		'StatusOrderRefusedShort' => 'Avvist',
		'StatusOrderToProcessShort' => 'Til behandling',
		'StatusOrderReceivedPartiallyShort' => 'Dellevert',
		'StatusOrderReceivedAllShort' => 'Fullt levert',
		'StatusOrderCanceled' => 'Kansellert',
		'StatusOrderDraft' => 'Kladd (trenger godkjenning)',
		'StatusOrderNeedQuotes' => 'Draft (needs manual quotes)',
		'StatusOrderNew' => 'New order (needs to be validated)',
		'StatusOrderProcessing' => 'Processing',
		'StatusOrderValidated' => 'Godkjent',
		'StatusOrderOnProcess' => 'Under behandling',
		'StatusOrderSending' => 'Sending',
		'StatusOrderClosed' => 'Closed (Shipped)',
		'StatusOrderToBill' => 'Til fakturering',
		'StatusOrderToBill2' => 'To bill',
		'StatusOrderApproved' => 'Godkjent',
		'StatusOrderRefused' => 'Avvist',
		'StatusOrderError' => 'Error',
		'StatusOrderReceivedPartially' => 'Dellevert',
		'StatusOrderReceivedAll' => 'Fullt levert',
		'ShippingExist' => 'En forsendelse eksisterer',
		'DraftOrWaitingApproved' => 'Kladd eller ikke bestilt ennå',
		'DraftOrWaitingShipped' => 'Kladd eller godkjent ikke sendt ennå',
		'MenuOrdersToBill' => 'Ordre til fakturering',
		'MenuOrdersToBill2' => 'Orders to bill',
		'SearchOrder' => 'Søk i ordre',
		'Sending' => 'Levering',
		'Sendings' => 'Leveringer',
		'ShipProduct' => 'Lever produkt',
		'Discount' => 'Rabatt',
		'CreateOrder' => 'Lag ordre',
		'RefuseOrder' => 'Avvis ordre',
		'ApproveOrder' => 'Aksepter ordre',
		'ValidateOrder' => 'Godkjenn ordre',
		'UnvalidateOrder' => 'Unvalidate ordre',
		'DeleteOrder' => 'Slett ordre',
		'CancelOrder' => 'Avbryt ordre',
		'AddOrder' => 'Legg til ordre',
		'AddToMyOrders' => 'Legg til mine ordre',
		'AddToOtherOrders' => 'Lagg til andre ordre',
		'ShowOrder' => 'Vis ordre',
		'NoOpenedOrders' => 'Ingen åpne ordre',
		'NoOtherOpenedOrders' => 'Ingen andre åpne ordre',
		'OtherOrders' => 'Andre ordre',
		'LastOrders' => 'Siste %s ordre',
		'LastModifiedOrders' => 'Siste %s endrede ordre',
		'LastClosedOrders' => 'Siste %s lukkede ordre',
		'AllOrders' => 'Alle ordre',
		'NbOfOrders' => 'Antal ordre',
		'OrdersStatistics' => 'Ordrestatistikk',
		'OrdersStatisticsSuppliers' => 'Statistikk leverandørordre',
		'NumberOfOrdersByMonth' => 'Antall ordre pr måned',
		'AmountOfOrdersByMonthHT' => 'ordrebeløp pr måned (eksl. MVA)',
		'ListOfOrders' => 'Ordreoverikt',
		'CloseOrder' => 'Lukk ordre',
		'ConfirmCloseOrder' => 'Er du sikker på at du vil lukke denne ordren? Når en ordre er lukket kan den kun faktureres.',
		'ConfirmCloseOrderIfSending' => 'Er du sikker på at du vil lukke denne ordren? Du må bare lukke ordren når alle leveringer er utført.',
		'ConfirmDeleteOrder' => 'Er du sikker på at du vil slette denne ordren?',
		'ConfirmValidateOrder' => 'Er du sikker på at du vil godkjenne denne ordren under navnet <b>%s</b> ?',
		'ConfirmUnvalidateOrder' => 'Er du sikker på at du vil gjenopprette orden <b>%s</b> til utkastet status?',
		'ConfirmCancelOrder' => 'Er du sikker på at du vil avbryte denne ordren?',
		'ConfirmMakeOrder' => 'Vil du bekrefte at du lagde denne ordren den <b>%s</b> ?',
		'GenerateBill' => 'Oppret faktura',
		'ClassifyShipped' => 'Classify delivered',
		'ClassifyBilled' => 'Klassifiser "Fakturert"',
		'ComptaCard' => 'Regnskapskort',
		'DraftOrders' => 'Ordrekladder',
		'RelatedOrders' => 'Relaterte ordre',
		'OnProcessOrders' => 'Ordre i behandling',
		'RefOrder' => 'Ref. ordre',
		'RefCustomerOrder' => 'Ref. kundeordre',
		'CustomerOrder' => 'Kundeordre',
		'RefCustomerOrderShort' => 'Ref. ordre',
		'SendOrderByMail' => 'Send ordre i post',
		'ActionsOnOrder' => 'Handlinger ifm. ordre',
		'NoArticleOfTypeProduct' => 'Der er ingen varer av typen \'product\' på ordren så det er ingen varer å sende',
		'OrderMode' => 'Ordremodus',
		'AuthorRequest' => 'Request author',
		'UseCustomerContactAsOrderRecipientIfExist' => 'Bruk kontaktpersons adresse i stedet for tredjepartens adresse',
		'RunningOrders' => 'Ordre i behandling',
		'UserWithApproveOrderGrant' => 'Brukere med rettigheter til å "godkjenne ordre".',
		'PaymentOrderRef' => 'Betaling av ordre %s',
		'CloneOrder' => 'Clone bestilling',
		'ConfirmCloneOrder' => 'Er du sikker på at du vil klone denne bestillingen <b>%s?</b>',
		'DispatchSupplierOrder' => 'Motta leverandør bestill %s',
		'DateDeliveryPlanned' => 'Date de livraison prévue',
		'SetDemandReason' => 'Définir l\'origine de la commande',
		////////// Types de contacts //////////
		'TypeContact_commande_internal_SALESREPFOLL' => 'Representant oppfølging kundeordre',
		'TypeContact_commande_internal_SHIPPING' => 'Representant oppfølging shipping',
		'TypeContact_commande_external_BILLING' => 'Kunden faktura kontakt',
		'TypeContact_commande_external_SHIPPING' => 'Kunden shipping kontakt',
		'TypeContact_commande_external_CUSTOMER' => 'Kundekontakt oppfølging rekkefølge',
		'TypeContact_order_supplier_internal_SALESREPFOLL' => 'Representant oppfølging leverandør bestilling',
		'TypeContact_order_supplier_internal_SHIPPING' => 'Representant oppfølging shipping',
		'TypeContact_order_supplier_external_BILLING' => 'Leverandørfaktura kontakt',
		'TypeContact_order_supplier_external_SHIPPING' => 'Leverandør shipping kontakt',
		'TypeContact_order_supplier_external_CUSTOMER' => 'Leverandør kontakt oppfølging rekkefølge',
		'Error_COMMANDE_SUPPLIER_ADDON_NotDefined' => 'Konstant COMMANDE_SUPPLIER_ADDON er ikke definert',
		'Error_COMMANDE_ADDON_NotDefined' => 'Konstant COMMANDE_ADDON er ikke definert',
		'Error_FailedToLoad_COMMANDE_SUPPLIER_ADDON_File' => 'Kunne ikke laste modulfilen \'%s\'',
		'Error_FailedToLoad_COMMANDE_ADDON_File' => 'Kunne ikke laste modulfilen \'%s\'',
		'Error_OrderNotChecked' => 'No orders to invoice selected',
		// Sources
		'OrderSource0' => 'Tilbud',
		'OrderSource1' => 'Internet',
		'OrderSource2' => 'DM',
		'OrderSource3' => 'Telefonkampanje',
		'OrderSource4' => 'Faxkampanje',
		'OrderSource5' => 'Egenbestilling',
		'OrderSource6' => 'Butikk',
		'QtyOrdered' => 'Ant bestilt',
		'AddDeliveryCostLine' => 'Legg til leveringskostnader og angi forsendelsens vekt',
		// Documents models
		'PDFEinsteinDescription' => 'En komplett ordremodell (logo...)',
		'PDFEdisonDescription' => 'En enkel bestilling modell',
		// Orders modes
		'OrderByMail' => 'Mail',
		'OrderByFax' => 'Faks',
		'OrderByEMail' => '-E-post',
		'OrderByWWW' => 'Online',
		'OrderByPhone' => 'Telefon',
		'CreateInvoiceForThisCustomer' => 'Bill orders',
		'NoOrdersToInvoice' => 'No orders billable',
		'CloseProcessedOrdersAutomatically' => 'Classify "Processed" all selected orders.',
		'MenuOrdersToBill2' => 'Orders to bill',
		'LinkedInvoices' => 'Linked invoices',
		'LinkedProposals' => 'Linked proposals',
		'ShippingHT' => 'Shipping cost'
);
?>