<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Lagerkort',
		'Warehouse' => 'Lager',
		'NewWarehouse' => 'Nytt lager',
		'MenuNewWarehouse' => 'Nytt lager',
		'WarehouseOpened' => 'Lager åpnet',
		'WarehouseClosed' => 'Lager lukket',
		'WarehouseSource' => 'Kildelager',
		'WarehouseTarget' => 'Mållager',
		'ValidateSending' => 'Godkjenn levering',
		'CancelSending' => 'Avbryt levering',
		'DeleteSending' => 'Slett levering',
		'Stock' => 'Lagerbeholdning',
		'Stocks' => 'Lagerbeholdning',
		'Movement' => 'Bevegelse',
		'Movements' => 'Bevegelser',
		'ErrorWarehouseRefRequired' => 'Du må angi et navn på lageret',
		'ErrorWarehouseLabelRequired' => 'du må angi en merkelapp for lageret',
		'CorrectStock' => 'Riktig beholdning',
		'ListOfWarehouses' => 'Oversikt over lagere',
		'ListOfStockMovements' => 'Oversikt over bevegelser',
		'StocksArea' => 'Beholdningsområde',
		'Location' => 'Lokasjon',
		'LocationSummary' => 'Kort navn på lokasjon',
		'NumberOfProducts' => 'Totalt antall produkter',
		'LastMovement' => 'Siste bevegelse',
		'LastMovements' => 'Siste bevegelser',
		'Units' => 'Enheter',
		'Unit' => 'Enhet',
		'StockCorrection' => 'Korriger lagerbeholdning',
		'StockMovement' => 'Overføring',
		'StockMovements' => 'Lageroverføring',
		'NumberOfUnit' => 'Atntall enheter',
		'TotalStock' => 'Tottal beholdning',
		'StockTooLow' => 'For lav beholdning',
		'EnhancedValue' => 'Verdi',
		'EnhancedValueOfWarehouses' => 'Lagerverdi',
		'UserWarehouseAutoCreate' => 'Opprett lager automatisk når en bruker opprettes',
		'QtyDispatched' => 'Antall sendt',
		'OrderDispatch' => 'Ordre sendt',
		'RuleForStockManagementDecrease' => 'Regel for lagerreduksjon',
		'RuleForStockManagementIncrease' => 'Regel for lagerøkning',
		'DeStockOnBill' => 'Reduser virkelig beholdning ut fra faktura/kreditnota',
		'DeStockOnValidateOrder' => 'Reduser virkelig beholdning ut fra ordre',
		'DeStockOnShipment' => 'reduser virkelig beholdning ved forsendelse (anbefalt)',
		'ReStockOnBill' => 'Øk virkelig beholdning ut fra faktura/kreditnota',
		'ReStockOnValidateOrder' => 'Øk virkelig beholdning ut fra ordre',
		'StockDiffPhysicTeoric' => 'Årsak til forskjell mellom fysisk og teoretisk beholdning',
		'StockLimitShort' => 'Grense',
		'StockLimit' => 'Minimumsbeholdning for varselmeldinger',
		'PhysicalStock' => 'Fysisk beholdning',
		'RealStock' => 'Virkelig beholdning',
		'TheoreticalStock' => 'Teoretisk beholdning',
		'VirtualStock' => 'Virtuell beholdning',
		'MininumStock' => 'Minimumsbeholdning',
		'StockUp' => 'Bør bestilles',
		'MininumStockShort' => 'Minimumsbeholdning',
		'StockUpShort' => 'Bør bestilles',
		'IdWarehouse' => 'Id lager',
		'DescWareHouse' => 'Beskrivelse av lager',
		'LieuWareHouse' => 'Lagerlokasjon',
		'WarehousesAndProducts' => 'Lager og varer',
		'WarehouseEdit' => 'Endre lager',
		'PMPValue' => 'Veid gjennomsnittlig pris',
		'PMPValueShort' => 'WAP',
		'ReStockOnDispatchOrder' => 'Øk virkelige aksjer på manuelle sende ut i lagerbygninger, etter leverandør bestill mottak',
		'OrderStatusNotReadyToDispatch' => 'Bestill har ikke ennå, eller ikke mer en status som gjør at ekspedering av produkter på lager lager.',
		'NoPredefinedProductToDispatch' => 'Ingen forhåndsdefinerte produkter for dette objektet. Så nei utsending på lager er nødvendig.',
		'DispatchVerb' => 'Dispatch',
		'AverageUnitPricePMPShort' => 'Veid gjennomsnittlig inngang pris',
		'AverageUnitPricePMP' => 'Veid gjennomsnittlig inngang pris',
		'EstimatedStockValueShort' => 'Estimert verdi av lager',
		'EstimatedStockValue' => 'Estimert verdi av lager',
		'DeleteAWarehouse' => 'Slette et lager',
		'ConfirmDeleteWarehouse' => 'Er du sikker på at du vil slette lageret <b>%s?</b>',
		'PersonalStock' => 'Personlig lager %s',
		'ThisWarehouseIsPersonalStock' => 'Dette lageret representerer personlige lager av %s %s',
		'SellPriceMin' => 'Selge Enhetspris',
		'EstimatedStockValueSellShort' => 'Verdi å selge',
		'EstimatedStockValueSell' => 'Verdi å selge',
		'SelectWarehouseForStockDecrease' => 'Velg lageret til bruk for lager nedgang',
		'SelectWarehouseForStockIncrease' => 'Velg lageret til bruk for lager økning',
);
?>