<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'Brukerkort',
		'ContactCard' => 'Kontaktperson-kort',
		'GroupCard' => 'Guppekort',
		'NoContactCard' => 'Ingen kort blant kontaktpersonene',
		'Permission' => 'Rettighet',
		'Permissions' => 'Rettigheter',
		'EditPassword' => 'Endre passord',
		'SendNewPassword' => 'Send nytt passord',
		'ReinitPassword' => 'Generer nytt passord',
		'PasswordChangedTo' => 'Passordet er endret til : %s',
		'SubjectNewPassword' => 'Ditt nye passord til Speedealing',
		'AvailableRights' => 'Tilgjengelige rettigheter',
		'OwnedRights' => 'Egne rettigheter',
		'GroupRights' => 'Grupperettigheter',
		'UserRights' => 'Brukerrettigheter',
		'UserGUISetup' => 'Brukerens visningsoppsett',
		'DisableUser' => 'Deaktiver',
		'DisableAUser' => 'Deaktiver en bruker',
		'DeleteUser' => 'Slett',
		'DeleteAUser' => 'Slette en bruker',
		'DisableGroup' => 'Slå av',
		'DisableAGroup' => 'Slå av en grupper',
		'EnableAUser' => 'Slå på en bruker',
		'EnableAGroup' => 'Slå på en gruppe',
		'DeleteGroup' => 'Slett',
		'DeleteAGroup' => 'Slett en gruppe',
		'ConfirmDisableUser' => 'Er du sikker på at du vil deaktivere brukeren <b>%s</b> ?',
		'ConfirmDisableGroup' => 'Er du sikker på at du vil deaktivere gruppen <b>%s</b> ?',
		'ConfirmDeleteUser' => 'Er du sikker på at du vil slette brukeren <b>%s</b> ?',
		'ConfirmDeleteGroup' => 'Er du sikker på at du vil slette gruppen <b>%s</b> ?',
		'ConfirmEnableUser' => 'Er du sikker på at du vil aktivere brukeren <b>%s</b> ?',
		'ConfirmEnableGroup' => 'Er du sikker på at du vil aktivere gruppen <b>%s</b> ?',
		'ConfirmReinitPassword' => 'Er du sikker på at du vil generere ett nytt passord for brukeren <b>%s</b> ?',
		'ConfirmSendNewPassword' => 'Er du sikker på at du vil generere og sende ett nytt passord for brukeren <b>%s</b> ?',
		'NewUser' => 'Ny bruker',
		'CreateUser' => 'Lag bruker',
		'SearchAGroup' => 'Søk etter gruppe',
		'SearchAUser' => 'Søk ette bruker',
		'LoginNotDefined' => 'Brukernavn ikke oppgitt.',
		'NameNotDefined' => 'Navn ikke oppgitt.',
		'ListOfUsers' => 'Brukeroversikt',
		'Administrator' => 'Administrator',
		'SuperAdministrator' => 'Super Administrator',
		'SuperAdministratorDesc' => 'Administrator med alle rettigheter',
		'AdministratorDesc' => 'Administrator er enhet',
		'DefaultRights' => 'Forvalgte rettigheter',
		'DefaultRightsDesc' => 'Her kan du angi hvilke rettigheter som automatisk skal gis til nye brukere.',
		'SpeedealingUsers' => 'Speedealing users',
		'LastName' => 'Navn',
		'FirstName' => 'Fornavn',
		'ListOfGroups' => 'Gruppeoversikt',
		'NewGroup' => 'Ny gruppe',
		'CreateGroup' => 'Lag gruppe',
		'RemoveFromGroup' => 'Fjern fra gruppe',
		'PasswordChangedAndSentTo' => 'Passordet er endret og sendt til <b>%s</b>.',
		'PasswordChangeRequestSent' => 'Anmodning om å endre passordet for <b>%s</b> er sendt til <b>%s</b>.',
		'MenuUsersAndGroups' => 'Brukere og grupper',
		'LastGroupsCreated' => 'Siste %s opprettede grupper',
		'LastUsersCreated' => 'Siste %s opprettede brukere',
		'ShowGroup' => 'Vis gruppe',
		'ShowUser' => 'Vis bruker',
		'NonAffectedUsers' => 'Ikke berørte brukere',
		'UserModified' => 'Brukeren er endret',
		'GroupModified' => 'Gruppen er endret',
		'PhotoFile' => 'Bildefil',
		'UserWithSpeedealingAccess' => 'User with Speedealing access',
		'ListOfUsersInGroup' => 'Oversikt over brukere i denne gruppen',
		'ListOfGroupsForUser' => 'Oversikt over grupper for denne brukeren',
		'UsersToAdd' => 'Brukere å legge til i denne gruppen',
		'GroupsToAdd' => 'Grupper å legge til denne brukeren',
		'NoLogin' => 'Ingen innlogging',
		'LinkToCompanyContact' => 'Lenke til tredjepart / kontakt',
		'LinkedToSpeedealingMember' => 'Link to member',
		'LinkedToSpeedealingUser' => 'Link to Speedealing user',
		'LinkedToSpeedealingThirdParty' => 'Link to Speedealing third party',
		'CreateSpeedealingLogin' => 'Create a user',
		'CreateSpeedealingThirdParty' => 'Create a third party',
		'LoginAccountDisable' => 'Kontoen er deaktivert, put a new login to activate it.',
		'LoginAccountDisableInSpeedealing' => 'Account disabled in Speedealing.',
		'LoginAccountDisableInLdap' => 'Kontoen er deaktivert i domenet.',
		'UsePersonalValue' => 'Bruk personlig verdie',
		'GuiLanguage' => 'Språk',
		'InternalUser' => 'Intern bruker',
		'MyInformations' => 'Mine data',
		'ExportDataset_user_1' => 'Speedealing brukere og egenskaper',
		'DomainUser' => 'Domenebruker %s',
		'Reactivate' => 'Reaktiver',
		'CreateInternalUserDesc' => 'Her kan du opprette interne brukere (ansatte). For å lage en ekstern bruker (kunde, leverandør, ...) bruker du knappen \'Lag Speedealing bruker\' fra tredjepartens kontaktkort.',
		'InternalExternalDesc' => 'En <b>intern</b> bruker er er en som er en del av firmaet/organisasjonen.<br>En <b>ekstern</b> bruker er en kunde, leverandør eller annen tredjeperson.<br><br>I begge tilfelle styres brukeren av Speedealing-rettigheter. Dessuten kan eksterne brukere ha en annen menybehandler enn interne brukere (Se Hjem - Instillinger - Visning)',
		'PermissionInheritedFromAGroup' => 'Rettigheter innvilget fordi de er arvet av en brukegruppe.',
		'Inherited' => 'Arvet',
		'UserWillBeInternalUser' => 'Opprettet bruker vil være en intern bruker (fordi ikke knyttet til en bestemt tredjepart)',
		'UserWillBeExternalUser' => 'Opprettet bruker vil være en ekstern bruker (fordi knyttes til et bestemt tredjepart)',
		'IdPhoneCaller' => 'ID phone caller',
		'UserLogged' => 'Brukeren %s er logget inn',
		'UserLogoff' => 'Bruker %s utlogging',
		'NewUserCreated' => 'Brukeren %s er opprettet',
		'NewUserPassword' => 'Passord er endret for %s',
		'EventUserModified' => 'Brukeren %s er endret',
		'UserDisabled' => 'Brukeren %s er deaktivert',
		'UserEnabled' => 'Brukeren %s er aktivert',
		'UserDeleted' => 'Brukeren %s er fjernet',
		'NewGroupCreated' => 'Gruppen %s er oprettet',
		'GroupModified' => 'Gruppen er endret',
		'GroupDeleted' => 'Gruppen %s er fjernet',
		'ConfirmCreateContact' => 'Er du sikker på at du vil lage en Speedealing-konto til denne kontaktpersonen?',
		'ConfirmCreateLogin' => 'Er du sikker på at du vil opprette en Speedealing konto for medlemmet?',
		'ConfirmCreateThirdParty' => 'Er du sikker på at du vil opprette en tredje part for medlemmet?',
		'LoginToCreate' => 'Brukernavn å opprette',
		'NameToCreate' => 'Navn på tredjepart til å lage',
		'YourRole' => 'Din roller',
		'YourQuotaOfUsersIsReached' => 'Din kvote på aktive brukere er nådd!',
		'NbOfUsers' => 'Nb av brukere',
		'DontDowngradeSuperAdmin' => 'Bare en superadmin kan nedgradere en superadmin',
		'NewDatabase' => 'Nouvelle base de données',
		'CreateDatabase' => 'Créer la base de données',
		'ListOfDatabases' => 'Liste des bases de données',
		'ListOfUsersInDatabase' => 'Liste des utilisateurs liés à la base de données',
		'ListOfRolesInDatabase' => 'Liste des groupes liés à la base de données',
		'DeleteADatabase' => 'Suppression d\'une database',
		'ConfirmDatabase' => 'Êtes-vous sûr de vouloir supprimer la base de données <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Groupes non affectés à la base de données',
		'NonAffectedUsersDatabase' => 'Utilisateurs non affectés à la base de données',
		'Collaborators' => 'Collaborateurs',
		'Profiles' => 'Profils collaborateurs'
);
?>