<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Categoría',
		'Categories' => 'Categorías',
		'Rubrique' => 'Directorio',
		'Rubriques' => 'Directorios',
		'categories' => 'categoría(s)',
		'TheCategorie' => 'La categoría',
		'NoCategoryYet' => 'Ninguna categoría de este tipo creada',
		'In' => 'En',
		'AddIn' => 'Añadir en',
		'modify' => 'Modificar',
		'Classify' => 'Clasificar',
		'CategoriesArea' => 'Área categorías',
		'ProductsCategoriesArea' => 'Área categorías de productos y servicios',
		'SuppliersCategoriesArea' => 'Área categorías de proveedores',
		'CustomersCategoriesArea' => 'Área categorías de clientes',
		'ThirdPartyCategoriesArea' => 'Área categorías de terceros',
		'MembersCategoriesArea' => 'Área categorías de miembros',
		'MainCats' => 'Categorías principales',
		'SubCats' => 'Subcategorías',
		'CatStatistics' => 'Estadísticas',
		'CatList' => 'Listado de categorías',
		'AllCats' => 'Todas las categorías',
		'ViewCat' => 'Ver la categoría',
		'NewCat' => 'Nueva categoría',
		'NewCategory' => 'Nueva categoría',
		'ModifCat' => 'Modificar una categoría',
		'CatCreated' => 'Categoría creada',
		'CreateCat' => 'Añadir una categoría',
		'CreateThisCat' => 'Añadir esta categoría',
		'ValidateFields' => 'Validar los campos',
		'NoSubCat' => 'Esta categoría no contiene ninguna subcategoría.',
		'SubCatOf' => 'Subcategoría',
		'FoundCats' => 'Categorías encontradas',
		'FoundCatsForName' => 'Categorías encontradas con el nombre:',
		'FoundSubCatsIn' => 'Subcategorías encontradas en la categoría',
		'ErrSameCatSelected' => 'Ha seleccionado la misma categoría varias veces',
		'ErrForgotCat' => 'Ha olvidado escoger la categoría',
		'ErrForgotField' => 'Ha olvidado reasignar un campo',
		'ErrCatAlreadyExists' => 'Este nombre esta siendo utilizado',
		'AddProductToCat' => '¿Añadir este producto a una categoría?',
		'ImpossibleAddCat' => 'Imposible añadir la categoría',
		'ImpossibleAssociateCategory' => 'Imposible asociar la categoría',
		'WasAddedSuccessfully' => 'se ha añadido con éxito.',
		'ObjectAlreadyLinkedToCategory' => 'El elemento ya está enlazado a esta categoría',
		'CategorySuccessfullyCreated' => 'La categoría %s se insertado correctamente.',
		'ProductIsInCategories' => 'Este producto/servicio se encuentra en las siguientes categorías',
		'SupplierIsInCategories' => 'Este proveedor se encuentra en las siguientes categorías',
		'CompanyIsInCustomersCategories' => 'Esta empresa se encuentra en las siguientes categorías',
		'CompanyIsInSuppliersCategories' => 'Esta empresa se encuentra en las siguientes categorías de proveedores',
		'MemberIsInCategories' => 'Este miembro se encuentra en las siguientes categorías de miembros',
		'ProductHasNoCategory' => 'Este producto/servicio no se encuentra en ninguna categoría en particular',
		'SupplierHasNoCategory' => 'Este proveedor no se encuentra en ninguna categoría en particular',
		'CompanyHasNoCategory' => 'Esta empresa no se encuentra en ninguna categoría en particular',
		'MemberHasNoCategory' => 'Este miembro no se encuentra en ninguna categoría en particular',
		'ClassifyInCategory' => 'Clasificar en la categoría',
		'NoneCategory' => 'Ninguna',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'Esta categoría ya existe para esta referencia',
		'ReturnInProduct' => 'Volver a la ficha producto/servicio',
		'ReturnInSupplier' => 'Volver a la ficha proveedor',
		'ReturnInCompany' => 'Volver a la ficha cliente/cliente potencial',
		'ContentsVisibleByAll' => 'El contenido será visible por todos',
		'ContentsVisibleByAllShort' => 'Contenido visible por todos',
		'ContentsNotVisibleByAllShort' => 'Contenido no visible por todos',
		'CategoriesTree' => 'Árbol de categorías',
		'DeleteCategory' => 'Eliminar categoría',
		'ConfirmDeleteCategory' => '¿Está seguro de querer eliminar esta categoría?',
		'RemoveFromCategory' => 'Eliminar vínculo con categoría',
		'RemoveFromCategoryConfirm' => '¿Está seguro de querer eliminar el vínculo entre la transacción y la categoría?',
		'NoCategoriesDefined' => 'Ninguna categoría definida',
		'SuppliersCategoryShort' => 'Categoría proveedores',
		'CustomersCategoryShort' => 'Categoría clientes',
		'ProductsCategoryShort' => 'Categoría productos',
		'MembersCategoryShort' => 'Categoría miembro',
		'SuppliersCategoriesShort' => 'Categorías proveedores',
		'CustomersCategoriesShort' => 'Categorías clientes',
		'CustomersProspectsCategoriesShort' => 'Categorías clientes/potenciales',
		'ProductsCategoriesShort' => 'Categorías productos',
		'MembersCategoriesShort' => 'Categorías miembros',
		'ThisCategoryHasNoProduct' => 'Esta categoría no contiene ningún producto.',
		'ThisCategoryHasNoSupplier' => 'Esta categoría no contiene ningún proveedor.',
		'ThisCategoryHasNoCustomer' => 'Esta categoría no contiene ningún cliente.',
		'ThisCategoryHasNoMember' => 'Esta categoría no contiene ningún miembro.',
		'AssignedToCustomer' => 'Asignar a un cliente',
		'AssignedToTheCustomer' => 'Asigado a un cliente',
		'InternalCategory' => 'Categoría interna',
		'CategoryContents' => 'Contenido de la categoría',
		'CategId' => 'Id categoría',
		'CatSupList' => 'Listado categorías de proveedores',
		'CatCusList' => 'Listado categorías de clientes/potenciales',
		'CatProdList' => 'Listado categorías de productos',
		'CatMemberList' => 'Listado categorías de miembros',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>