<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$install = array(
		'CHARSET' => 'UTF-8',
		'InstallEasy' => 'Hemos procurado que la instalación sea lo más simple posible, usted sólo tiene que seguir los pasos uno a uno.',
		'MiscellanousChecks' => 'Comprobación de los prerrequisitos',
		'SpeedealingWelcome' => 'Welcome to Speedealing',
		'ConfFileExists' => 'El archivo de configuración <b>%s</b> existe.',
		'ConfFileDoesNotExists' => '¡El archivo de configuración <b>%s</b> no existe!',
		'ConfFileDoesNotExistsAndCouldNotBeCreated' => '¡El archivo de configuración <b>%s</b> no existe y no se ha creado!',
		'ConfFileCouldBeCreated' => 'El archivo de configuración <b>%s</b> se ha creado.',
		'ConfFileIsNotWritable' => 'El archivo <b>%s</b> no es modificable. Para una primera instalación, modifique sus permisos. El servidor Web debe tener el derecho a escribir en este archivo durante la configuración ("chmod 666" por ejemplo sobre un SO compatible UNIX).',
		'ConfFileIsWritable' => 'El archivo <b>%s</b> es modificable.',
		'ConfFileReload' => 'Recargar toda la información del archivo de configuración.',
		'PHPSupportSessions' => 'Este PHP soporta sesiones',
		'PHPSupportPOSTGETOk' => 'Este PHP soporta bien las variables POST y GET.',
		'PHPSupportPOSTGETKo' => 'Es posible que este PHP no soporte las variables POST y/o GET. Compruebe el parámetro <b>variables_order</b> del php.ini.',
		'PHPSupportGD' => 'Este PHP soporta las funciones gráficas GD.',
		'PHPSupportUTF8' => 'Este PHP soporta las funciones UTFB.',
		'PHPMemoryOK' => 'Su memoria máxima de sesión PHP esta definida a <b>%s</b>. Esto debería ser suficiente.',
		'PHPMemoryTooLow' => 'Su memoria máxima de sesión PHP está definida en <b>%s</b> bytes. Esto es muy poco. Se recomienda modificar el parámetro <b>memory_limit</b> de su archivo <b>php.ini</b> a por lo menos <b>%s</b> bytes.',
		'Recheck' => 'Haga click aquí para realizar un test más exhaustivo',
		'ErrorPHPDoesNotSupportSessions' => 'Su instalación PHP no soporta las sesiones. Esta funcionalidad es necesaria para hacer funcionar a Speedealing. Compruebe su configuración de PHP.',
		'ErrorPHPDoesNotSupportGD' => 'Este PHP no soporta las funciones gráficas GD. Ningún gráfico estará disponible.',
		'ErrorPHPDoesNotSupportUTF8' => 'Este PHP no soporta las funciones UTF8. Resuelva el problema antes de instalar Speedealing ya que no podrá funcionar correctamente.',
		'ErrorDirDoesNotExists' => 'El directorio <b>%s</b> no existe o no es accesible.',
		'ErrorGoBackAndCorrectParameters' => 'Vuelva atrás y corrija los parámetros inválidos...',
		'ErrorWrongValueForParameter' => 'Indicó quizá un valor incorrecto para el parámetro \'%s\'.',
		'ErrorFailedToCreateDatabase' => 'Error al crear la base de datos \'%s\'.',
		'ErrorFailedToConnectToDatabase' => 'Error de conexión a la base de datos \'%s\'.',
		'ErrorDatabaseVersionTooLow' => 'Versión de la base de datos (%s) demasiado antigua. Se requiere versión %s o superior.',
		'ErrorPHPVersionTooLow' => 'Versión de PHP demasiado antigua. Se requiere versión %s o superior.',
		'WarningPHPVersionTooLow' => 'Versión de PHP demasiado antigua. Se recomienda version %s o superior. Puede usar esta versión, pero no es compatible.',
		'ErrorConnectedButDatabaseNotFound' => 'La conexión al servidor es correcta pero no se encuentra la base de datos \'%s\'',
		'ErrorDatabaseAlreadyExists' => 'La base de datos \'%s\' ya existe.',
		'IfDatabaseNotExistsGoBackAndUncheckCreate' => 'Si la base de datos no existe, vuelva atrás y active la opción "Crear base de datos"',
		'IfDatabaseExistsGoBackAndCheckCreate' => 'Si la base de datos ya existe, vuelva atrás y desactive la opción "crear la base de datos".',
		'WarningBrowserTooOld' => 'Su navegador es muy antiguo. Le recomendamos que actualice a una versión reciente de Firefox, Chrome u Opera.',
		'PHPVersion' => 'Versión PHP',
		'YouCanContinue' => 'Puede continuar...',
		'PleaseBePatient' => 'Espere, por favor...',
		'License' => 'Licencia de uso',
		'ConfigurationFile' => 'Archivo de configuración',
		'WebPagesDirectory' => 'Directorio que contiene las páginas web',
		'DocumentsDirectory' => 'Directorio que debe contener los documentos generados (PDF, etc.)',
		'URLRoot' => 'URL Raíz',
		'ForceHttps' => 'Forzar conexiones seguras (https)',
		'CheckToForceHttps' => 'Marque esta opción para forzar conexiones seguras (https).<br>Para ello es necesario que el servidor web está configurado con un certificado SSL.',
		'SpeedealingDatabase' => 'Speedealing Database',
		'DatabaseChoice' => 'Elección de la base de datos',
		'DatabaseType' => 'Tipo de la base de datos',
		'DriverType' => 'Tipo del driver',
		'Server' => 'Servidor',
		'ServerAddressDescription' => 'Nombre o dirección IP del servidor de base de datos, generalmente \'localhost\' cuando el servidor se encuentra en la misma máquina que el servidor web',
		'ServerPortDescription' => 'Puerto del servidor de la base de datos. Dejar en blanco si lo desconoce.',
		'DatabaseServer' => 'Servidor de la base de datos',
		'DatabaseName' => 'Nombre de la base de datos',
		'DatabasePrefix' => 'Prefijo para las tablas',
		'Login' => 'Usuario',
		'AdminLogin' => 'Usuario del administrador de la base de datos Speedealing. Deje vacío si se conecta en anonymous',
		'Password' => 'Contraseña',
		'PasswordAgain' => 'Verificación de la contraseña',
		'AdminPassword' => 'Contraseña del administrador de la base de datos Speedealing. Deje vacío si se conecta en anonymous',
		'CreateDatabase' => 'Crear la base de datos',
		'CreateUser' => 'Crear el propietario',
		'DatabaseSuperUserAccess' => 'Base de datos - Acceso super usuario',
		'CheckToCreateDatabase' => 'Seleccione esta opción si la base de datos no existe y debe crearse. En este caso, es necesario indicar usuario/contraseña del superusuario más adelante en esta página.',
		'CheckToCreateUser' => 'Seleccione esta opción si el usuario no existe y debe crearse.<br>En este caso, es necesario indicar usuario/contraseña del superusuario más adelante en esta página.',
		'Experimental' => '(experimental)',
		'DatabaseRootLoginDescription' => 'Usuario de la base que tiene los derechos de creación de bases de datos o cuenta para la base de datos, inútil si la base de datos y su usuario ya existen (como cuando están en un anfitrión).',
		'KeepEmptyIfNoPassword' => 'Deje vacío si el usuario no tiene contraseña',
		'SaveConfigurationFile' => 'Grabación del archivo de configuración',
		'ConfigurationSaving' => 'Grabación del archivo de configuración',
		'ServerConnection' => 'Conexión al servidor',
		'DatabaseConnection' => 'Conexión a la base de datos',
		'DatabaseCreation' => 'Creación de la base de datos',
		'UserCreation' => 'Creación del usuario',
		'CreateDatabaseObjects' => 'Creación de los objetos de la base de datos',
		'ReferenceDataLoading' => 'Carga de los datos de referencia',
		'TablesAndPrimaryKeysCreation' => 'Creación de las tablas y los índices',
		'CreateTableAndPrimaryKey' => 'Creación de la tabla %s y su clave primaria',
		'CreateOtherKeysForTable' => 'Creación de las claves e índices de la tabla %s',
		'OtherKeysCreation' => 'Creación de las claves e índices',
		'FunctionsCreation' => 'Creación de funciones',
		'AdminAccountCreation' => 'Creación de la cuenta administrador',
		'PleaseTypePassword' => '¡Indique una contraseña, no se aceptan las contraseñas vacías!',
		'PleaseTypeALogin' => '¡Indique un usuario!',
		'PasswordsMismatch' => '¡Las contraseñas no coinciden, vuelva a intentarlo !',
		'SetupEnd' => 'Fin de la instalación',
		'SystemIsInstalled' => 'Se está instalando su sistema.',
		'SystemIsUpgraded' => 'Se actualizó Speedealing correctamente.',
		'YouNeedToPersonalizeSetup' => 'Ahora debe configurar Speedealing según sus necesidades (elección de la apariencia, de las funcionalidades, etc). Para eso, haga click en el siguiente link:',
		'AdminLoginCreatedSuccessfuly' => 'Creación de la cuenta administrador Speedealing \'<b>%s</b>\' realizada.',
		'GoToSpeedealing' => 'Go to Speedealing',
		'GoToSetupArea' => 'Acceso a Speedealing (área de configuración)',
		'MigrationNotFinished' => 'La versión de su base de datos aún no está completamente a nivel, por lo que tendrá que reiniciar una migración.',
		'GoToUpgradePage' => 'Acceder a la página de migración de nuevo',
		'Examples' => 'Ejemplos',
		'WithNoSlashAtTheEnd' => 'Sin el signo "/" al final',
		'DirectoryRecommendation' => 'Se recomienda poner este directorio fuera del directorio de las páginas web.',
		'LoginAlreadyExists' => 'Ya existe',
		'SpeedealingAdminLogin' => 'Speedealing admin login',
		'AdminLoginAlreadyExists' => 'La cuenta de administrador Speedealing \'<b>%s</b>\' ya existe. Vuelva atrás si desea crear otra.',
		'WarningRemoveInstallDir' => 'Atención, por razones de seguridad, con el fin de bloquear un nuevo uso de las herramientas de instalación/actualización, es aconsejable crear en el directorio raíz de Speedealing un archivo llamado <b>install.lock</b> en solo lectura.',
		'ThisPHPDoesNotSupportTypeBase' => 'El sistema PHP no soporta los interfaces de acceso para las bases de datos %s',
		'FunctionNotAvailableInThisPHP' => 'No disponible en este PHP',
		'MigrateScript' => 'Script de migración',
		'ChoosedMigrateScript' => 'Elección del script de migración',
		'DataMigration' => 'Migración de los datos',
		'DatabaseMigration' => 'Migración del formato de la base de datos',
		'ProcessMigrateScript' => 'Ejecución del script',
		'ChooseYourSetupMode' => 'Elija su método de instalación y haga clic en "Empezar"...',
		'FreshInstall' => 'Primera instalación',
		'FreshInstallDesc' => 'Utilizar este método si es su primera instalación. Si no es el caso, este método puede reparar una instalación anterior incompleta, pero si quiere actualizar una versión anterior, escoja el método "Actualización".',
		'Upgrade' => 'Actualización',
		'UpgradeDesc' => 'Utilice este método después de haber actualizado los archivos de una instalación Speedealing antigua por los de una versión más reciente. Esta elección permite poner al día la base de datos los y sus datos para esta nueva versión.',
		'Start' => 'Empezar',
		'InstallNotAllowed' => 'Instalación no autorizada por los permisos del archivo <b>conf.php</b>',
		'NotAvailable' => 'No disponible',
		'YouMustCreateWithPermission' => 'Debe crear un archivo %s y darle los derechos de escritura al servidor web durante el proceso de instalación.',
		'CorrectProblemAndReloadPage' => 'Corrija el problema y <a href="%s">recargue la página</a> (Tecla F5).',
		'AlreadyDone' => 'Ya migrada',
		'DatabaseVersion' => 'Versión de la base de datos',
		'ServerVersion' => 'Versión del servidor de la base de datos',
		'YouMustCreateItAndAllowServerToWrite' => 'Debe crear este directorio y permitir al servidor web escribir en él.',
		'CharsetChoice' => 'Elección del juego de caracteres',
		'CharacterSetClient' => 'Codificación utilizada para la visualización de las páginas',
		'CharacterSetClientComment' => 'Puede elegir la codificación que desea para la visualización de las páginas.<br/>La codificación propuesta por defecto es la de su base de datos.',
		'CollationConnection' => 'Orden de selección utilizado para la base de datos',
		'CollationConnectionComment' => 'Puede elegir la página de código por la que se define el orden de selección de los caracteres utilizado por la base de datos. Este parámetro también es llamado \'cotejo\' por algunas bases de datos.<br/> Este parámetro no es seleccionable si la base de datos ya está creada',
		'CharacterSetDatabase' => 'Codificación utilizada por la base de datos',
		'CharacterSetDatabaseComment' => 'Puede elegir la codificación que desea en la creación de la base de datos.<br/> Este parámetro no es seleccionable si la base de datos ya está creada',
		'YouAskDatabaseCreationSoSpeedealingNeedToConnect' => 'You ask to create database <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'YouAskLoginCreationSoSpeedealingNeedToConnect' => 'You ask to create database login <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'BecauseConnectionFailedParametersMayBeWrong' => 'La conexión falla, los parámetros del servidor o el superusuario pueden ser incorrectos.',
		'OrphelinsPaymentsDetectedByMethod' => 'Pagos huérfanos detectados por el método %s',
		'RemoveItManuallyAndPressF5ToContinue' => 'Suprimalo manualmente y pulse F5 para continuar.',
		'KeepDefaultValuesWamp' => 'Está utilizando el asistente de instalación DoliWamp, los valores propuestos aquí están optimizados. Cambielos solamente si está seguro de ello.',
		'KeepDefaultValuesDeb' => 'Está utilizando el asistente de instalación Speedealing de un paquete Linux o BSD (Ubuntu, Debian, Fedora...), los valores propuestos aquí están optimizados. Sólo será necesaria la contraseña del propietario de la base de datos a crear. Cambie la otra información sólamente si está seguro de ello.',
		'KeepDefaultValuesMamp' => 'Está utilizando el asistente de instalación DoliMamp, los valores propuestos aquí están optimizados. Cambielos solamente si está seguro de ello.',
		'KeepDefaultValuesProxmox' => 'Está utilizando el asistente de instalación Speedealing desde una máquina virtual Proxmox, los valores propuestos aquí están optimizados. Cambielos solamente si está seguro de ello.',
		'FieldRenamed' => 'Campo renombrado',
		'IfLoginDoesNotExistsCheckCreateUser' => 'Si el login aún no existe, debe seleccionar la opción "Creación del usuario"',
		'ErrorConnection' => 'El servidor "<b>%s</b>", base de datos "<b>%s</b>", login "<b>%s</b>", o la contraseña de la base de datos pueden ser incorrectos o la versión de PHP muy vieja en comparación con la versión de la base de datos.',
		'InstallChoiceRecommanded' => 'Opción recomendada para instalar la versión <b>%s</b> sobre su actual versión <b>%s</b>',
		'InstallChoiceSuggested' => '<b>Opción sugerida por el instalador</b>.',
		'MigrateIsDoneStepByStep' => 'La versión de destino (%s) tiene una diferencia de varias versiones, una vez concluida esta migración, el instalador volverá a proponer la siguiente.',
		'CheckThatDatabasenameIsCorrect' => 'Compruebe que el nombre de la base de datos "<b>%s</b>" es correcto.',
		'IfAlreadyExistsCheckOption' => 'Si el nombre es correcto y la base de datos no existe, debe seleccionar la opción "Crear la base de datos"',
		'OpenBaseDir' => 'Parámetro php openbasedir',
		'YouAskToCreateDatabaseSoRootRequired' => 'Ha marcado la casilla "Crear la base de datos". Para ello, el usuario/contraseña del superusuario (al final del formulario) son obligatorios.',
		'YouAskToCreateDatabaseUserSoRootRequired' => 'Ha marcado la casilla "Crear el usuario propietario" de la base de datos. Para ello, el usuario/contraseña del superusuario (al final del formulario) son obligatorios.',
		'NextStepMightLastALongTime' => 'El siguiente paso puede tardar varios minutos. Después de haber validado, le agradecemos espere a la completa visualización de la página siguiente para continuar.',
		'LastStepDesc' => '<strong>Último paso</strong>: Indique aquí la cuenta y la contraseña del primer usuario que usted utilizará para conectarse a la aplicación. No pierda estos identificadores, es la cuenta que permite administrar el resto.',
		'ActivateModule' => 'Activación del módulo %s',
		'ShowEditTechnicalParameters' => 'Click here to show/edit advanced parameters (expert mode)',
		'ServerPortCouchdbDescription' => 'Port du serveur. Défaut 5984.',
		'ServerAddressCouchdbDescription' => 'Nom FQDN du serveur de base de données, \'localhost.localdomain\' quand le serveur est installé sur la même machine que le serveur web',
		'DatabaseCouchdbUserDescription' => 'Login du super administrateur ayant tous les droits sur le serveur CouchDB ou l\'administrateur propriétaire de la base si la base et son compte d\'accès existent déjà (comme lorsque vous êtes chez un hébergeur).<br><br><div class="alert-box info">Cet utilisateur/mot de passe sera l\'administrateur pour se connecter à Speedealing.</div>',
		'CheckToCreateCouchdbDatabase' => 'Cochez cette option si la base de données n\'existe pas et doit être créée.',
		'CreateAdminUser' => 'Créer le super administrateur (Première installation de couchDB)',
		'MemcachedDescription' => 'Activer Memcached necessite l\'installation d\'un serveur Memcached et des lib php-memcached ou php-memcache. Il peut être activer après l\'installation.',
		'ServerAddressMemcachedDesc' => 'Nom ou adresse ip du serveur memcached, généralement \'localhost\' quand le serveur est installé sur la même machine que le serveur web',
		'ServerPortMemcachedDesc' => 'Port du serveur memcached. Défaut : 11211',
		'EnabledMemcached' => 'Activer Memcached',
		'DatabaseNoSQL' => 'Base de données CouchDB',
		'FailedToCreateAdminLogin' => 'Echec de la création du compte administrateur Speedealing.',
		'LinkedElementsInvalidDeleted' => '<b>%s</b> liaisons invalides ont été supprimées',
		'NothingToDelete' => 'Aucune liaison invalide trouvée',
		'SourceType' => 'Source',
		'TargetType' => 'Cible'
);
?>