<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$propal = array(
		'CHARSET' => 'UTF-8',
		'Proposals' => 'Presupuestos',
		'Proposal' => 'Presupuesto',
		'ProposalShort' => 'Presupuesto',
		'ProposalsDraft' => 'Presupuestos borrador',
		'ProposalDraft' => 'Presupuesto borrador',
		'Prop' => 'Presupuestos',
		'CommercialProposal' => 'Presupuesto',
		'CommercialProposals' => 'Presupuestos',
		'ProposalsOpened' => 'Presupuestos abiertos',
		'ProposalCard' => 'Ficha presupuesto',
		'NewProp' => 'Nuevo presupuesto',
		'NewProp' => 'Nuevo presupuesto',
		'NewProposal' => 'Nuevo presupuesto',
		'NewPropal' => 'Nuevo presupuesto',
		'Prospect' => 'Cliente potencial',
		'ProspectList' => 'Listado de clientes potenciales',
		'DeleteProp' => 'Eliminar presupuesto',
		'ValidateProp' => 'Validar presupuesto',
		'AddProp' => 'Crear presupuesto',
		'ConfirmDeleteProp' => '¿Está seguro de querer eliminar este presupuesto?',
		'ConfirmValidateProp' => '¿Está seguro de querer validar este presupuesto?',
		'LastPropals' => 'Los %s últimos presupuestos',
		'LastClosedProposals' => 'Los %s últimos presupuestos cerrados',
		'LastModifiedProposals' => 'Los %s últimos presupuestos modificados',
		'AllPropals' => 'Todos los presupuestos',
		'LastProposals' => 'Ultimos presupuestos',
		'SearchAProposal' => 'Buscar un presupuesto',
		'ProposalsStatistics' => 'Estadísticas de presupuestos',
		'NumberOfProposalsByMonth' => 'Número por mes',
		'AmountOfProposalsByMonthHT' => 'Importe por mes (sin IVA)',
		'NbOfProposals' => 'Número presupuestos',
		'ShowPropal' => 'Ver presupuesto',
		'PropalsDraft' => 'Borrador',
		'PropalsOpened' => 'Abiertos',
		'PropalsNotBilled' => 'No facturados',
		'PropalStatusDraft' => 'Borrador (a validar)',
		'PropalStatusValidated' => 'Validado (presupuesto abierto)',
		'PropalStatusOpened' => 'Validado (presupuesto abierto)',
		'PropalStatusClosed' => 'Cerrado',
		'PropalStatusSigned' => 'Firmado (a facturar)',
		'PropalStatusNotSigned' => 'No firmado (cerrado)',
		'PropalStatusBilled' => 'Facturado',
		'PropalStatusDraftShort' => 'Borrador',
		'PropalStatusValidatedShort' => 'Validado',
		'PropalStatusOpenedShort' => 'Abierto',
		'PropalStatusClosedShort' => 'Cerrado',
		'PropalStatusSignedShort' => 'Firmado',
		'PropalStatusNotSignedShort' => 'No firmado',
		'PropalStatusBilledShort' => 'Facturado',
		'PropalsToClose' => 'Presupuestos a cerrar',
		'PropalsToBill' => 'Presupuestos firmados a facturar',
		'ListOfProposals' => 'Listado de presupuestos',
		'ActionsOnPropal' => 'Eventos sobre el presupuesto',
		'NoOpenedPropals' => 'Sin presupuestos abiertos',
		'NoOtherOpenedPropals' => 'Ningún otro presupuesto abierto',
		'RefProposal' => 'Ref. presupuesto',
		'SendPropalByMail' => 'Enviar presupuesto por e-mail',
		'FileNotUploaded' => 'No se ha subido el archivo',
		'FileUploaded' => 'El archivo se ha subido correctamente',
		'AssociatedDocuments' => 'Documentos asociados al presupuesto :',
		'ErrorCantOpenDir' => 'Imposible abrir el directorio',
		'DatePropal' => 'Fecha presupuesto',
		'DateEndPropal' => 'Fecha fin de validez',
		'DateEndPropalShort' => 'Fecha fin',
		'ValidityDuration' => 'Duración de validez',
		'CloseAs' => 'Cerrar con el estado',
		'ClassifyBilled' => 'Clasificar facturado',
		'BuildBill' => 'Crear factura',
		'ErrorPropalNotFound' => 'Presupuesto %s inexistente',
		'Estimate' => 'Presupuesto:',
		'EstimateShort' => 'Presupuesto',
		'OtherPropals' => 'Otros presupuestos',
		'CopyPropalFrom' => 'Crear presupuesto por copia de uno existente',
		'CreateEmptyPropal' => 'Crear presupuesto vacío',
		'DefaultProposalDurationValidity' => 'Plazo de validez por defecto (en días)',
		'UseCustomerContactAsPropalRecipientIfExist' => 'Utilizar dirección contacto de seguimiento de cliente definido en vez de la dirección del tercero como destinatario de los presupuestos',
		'ClonePropal' => 'Clonar presupuesto',
		'ConfirmClonePropal' => '¿Está seguro de querer clonar el presupuesto <b>%s</b>?',
		'ConfirmReOpenProp' => '¿Está seguro de querer reabrir el presupuesto <b>%s</b> ?',
		'ProposalsAndProposalsLines' => 'Presupuestos a clientes y líneas de presupuestos',
		'ProposalLine' => 'Línea de presupuesto',
		'AvailabilityPeriod' => 'Tiempo de entrega',
		'SetAvailability' => 'Definir el tiempo de entrega',
		'AfterOrder' => 'despues del pedido',
		////////// Availability //////////
		'AvailabilityTypeAV_NOW' => 'Inmediata',
		'AvailabilityTypeAV_1W' => '1 semana',
		'AvailabilityTypeAV_2W' => '2 semanas',
		'AvailabilityTypeAV_3W' => '3 semanas',
		'AvailabilityTypeAV_1M' => '1 mes',
		////////// Types de contacts //////////
		'TypeContact_propal_internal_SALESREPFOLL' => 'Comercial seguimiento presupuesto',
		'TypeContact_propal_external_BILLING' => 'Contacto cliente de facturación presupuesto',
		'TypeContact_propal_external_CUSTOMER' => 'Contacto cliente seguimiento presupuesto',
		// Documents models
		'DocModelAzurDescription' => 'Modelo de presupuesto completo (logo...)',
		'DocModelJauneDescription' => 'Modelo de presupuesto Jaune',
		'Numbershort' => 'N°',
);
?>