<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Ficha almacén',
		'Warehouse' => 'Almacén',
		'Warehouses' => 'Almacenes',
		'NewWarehouse' => 'Nuevo almacén o zona de almacenaje',
		'WarehouseEdit' => 'Edición almacén',
		'MenuNewWarehouse' => 'Nuevo almacén',
		'WarehouseOpened' => 'Almacén abierto',
		'WarehouseClosed' => 'Almacén cerrado',
		'WarehouseSource' => 'Almacén origen',
		'WarehouseSourceNotDefined' => 'Sin almacenes definidos,',
		'AddOne' => 'Añadir uno',
		'WarehouseTarget' => 'Almacén destino',
		'ValidateSending' => 'Validar envío',
		'CancelSending' => 'Anular envío',
		'DeleteSending' => 'Eliminar envío',
		'Stock' => 'Stock',
		'Stocks' => 'Stocks',
		'Movement' => 'Movimiento',
		'Movements' => 'Movimientos',
		'ErrorWarehouseRefRequired' => 'El nombre de referencia del almacén es obligatorio',
		'ErrorWarehouseLabelRequired' => 'La etiqueta del almacén es obligatoria',
		'CorrectStock' => 'Corregir stock',
		'ListOfWarehouses' => 'Listado de almacenes',
		'ListOfStockMovements' => 'Listado de movimientos de stock',
		'StocksArea' => 'Área stocks',
		'Location' => 'Lugar',
		'LocationSummary' => 'Nombre corto del lugar',
		'NumberOfProducts' => 'Numero total de productos',
		'LastMovement' => 'Último movimiento',
		'LastMovements' => 'Últimos movimientos',
		'Units' => 'Unidades',
		'Unit' => 'Unidad',
		'StockCorrection' => 'Corrección stock',
		'StockMovement' => 'Transferencia',
		'StockMovements' => 'Movimientos de stock',
		'NumberOfUnit' => 'Número de piezas',
		'UnitPurchaseValue' => 'Precio de compra unitario',
		'TotalStock' => 'Total en stock',
		'StockTooLow' => 'Stock insuficiente',
		'StockLowerThanLimit' => 'Stock lower than alert limit',
		'EnhancedValue' => 'Valor',
		'PMPValue' => 'Valor (PMP)',
		'PMPValueShort' => 'PMP',
		'EnhancedValueOfWarehouses' => 'Valor de stocks',
		'UserWarehouseAutoCreate' => 'Crear automáticamente existencias/almacén propio del usuario en la creación del usuario',
		'QtyDispatched' => 'Cantidad desglosada',
		'OrderDispatch' => 'Recepción de stocks',
		'RuleForStockManagementDecrease' => 'Regla de gestión de decrementos de stock',
		'RuleForStockManagementIncrease' => 'Regla de gestión de incrementos de stock',
		'DeStockOnBill' => 'Decrementar los stocks físicos sobre las facturas/abonos a clientes',
		'DeStockOnValidateOrder' => 'Decrementar los stocks físicos sobre los pedidos de clientes',
		'DeStockOnShipment' => 'Decrementar los stocks físicos sobre los envíos',
		'ReStockOnBill' => 'Incrementar los stocks físicos sobre las facturas/abonos de proveedores',
		'ReStockOnValidateOrder' => 'Incrementar los stocks físicos sobre los pedidos a proveedores',
		'ReStockOnDispatchOrder' => 'Incrementa los stocks físicos en el desglose manual de la recepción de los pedidos a proveedores en los almacenes',
		'OrderStatusNotReadyToDispatch' => 'El pedido aún no está o no tiene un estado que permita un desglose de stock.',
		'StockDiffPhysicTeoric' => 'Motivo de la diferencia entre valores físicos y teóricos',
		'NoPredefinedProductToDispatch' => 'No hay productos predefinidos en este objeto. Por lo tanto no se puede realizar un desglose de stock.',
		'DispatchVerb' => 'Desglosar',
		'StockLimitShort' => 'Límite',
		'StockLimit' => 'Stock límite para alertas',
		'PhysicalStock' => 'Stock físico',
		'RealStock' => 'Stock real',
		'TheoreticalStock' => 'Stock teórico',
		'VirtualStock' => 'Stock virtual',
		'MininumStock' => 'Stock mínimo',
		'StockUp' => 'Stock máximo',
		'MininumStockShort' => 'Stock mín.',
		'StockUpShort' => 'Stock máx.',
		'IdWarehouse' => 'Id. almacén',
		'DescWareHouse' => 'Descripción almacén',
		'LieuWareHouse' => 'Localización almacén',
		'WarehousesAndProducts' => 'Almacenes y productos',
		'AverageUnitPricePMPShort' => 'Precio medio ponderado (PMP)',
		'AverageUnitPricePMP' => 'Precio Medio Ponderado (PMP) de adquisición',
		'SellPriceMin' => 'Precio de venta unitario',
		'EstimatedStockValueSellShort' => 'Valor venta',
		'EstimatedStockValueSell' => 'Valor de venta',
		'EstimatedStockValueShort' => 'Valor compra (PMP)',
		'EstimatedStockValue' => 'Valor de compra (PMP)',
		'DeleteAWarehouse' => 'Eliminar un almacén',
		'ConfirmDeleteWarehouse' => '¿Está seguro de querer eliminar el almacén <b>%s</b>?',
		'PersonalStock' => 'Stock personal %s',
		'ThisWarehouseIsPersonalStock' => 'Este almacén representa el stock personal de %s %s',
		'SelectWarehouseForStockDecrease' => 'Seleccione el almacén a usar en el decremento de stock',
		'SelectWarehouseForStockIncrease' => 'Seleccione el almacén a usar en el incremento de stock',
		'LastWaitingSupplierOrders' => 'Pedidos en espera de recepción'
);
?>