<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Κατηγορία',
		'Categories' => 'Κατηγορίες',
		'Rubrique' => 'Κατηγορία',
		'Rubriques' => 'Κατηγορίες',
		'categories' => 'κατηγορίες',
		'TheCategorie' => 'Η Κατηγορία',
		'NoCategoryYet' => 'Δεν υπάρχει κατηγορία',
		'In' => 'Μέσα',
		'AddIn' => 'Προσθήκη σε',
		'modify' => 'αλλαγή',
		'Classify' => 'Classify',
		'CategoriesArea' => 'Περιοχή κατηγοριών',
		'ProductsCategoriesArea' => 'Περιοχή κατηγοριών Προϊόντων/Υπηρεσιών',
		'SuppliersCategoriesArea' => 'Περιοχή κατηγοριών Προμηθευτών',
		'CustomersCategoriesArea' => 'Περιοχή κατηγοριών Πελατών',
		'ThirdPartyCategoriesArea' => 'Περιοχή κατηγοριών Άλλων Στοιχείων',
		'MembersCategoriesArea' => 'Περιοχή κατηγοριών Χρηστών/Μελών',
		'MainCats' => 'Βασικές Κατηγορίες',
		'SubCats' => 'Υποκατηγορίες',
		'CatStatistics' => 'Στατιστικά',
		'CatList' => 'Λίστα κατηγοριών',
		'AllCats' => 'Όλες οι Κατηγορίες',
		'ViewCat' => 'Εμφάνιση Κατηγορίας',
		'NewCat' => 'Προσθήκη Κατηγορίας',
		'NewCategory' => 'Νέα Κατηγορία',
		'ModifCat' => 'Τροποποίηση Κατηγορίας',
		'CatCreated' => 'Η Κατηγορία Δημιουργήθηκε',
		'CreateCat' => 'Δημιουργία Κατηγορίας',
		'CreateThisCat' => 'Create this category',
		'ValidateFields' => 'Validate the fields',
		'NoSubCat' => 'No subcategory.',
		'SubCatOf' => 'Υποκατηγορία',
		'FoundCats' => 'Found categories',
		'FoundCatsForName' => 'Categories found for the name :',
		'FoundSubCatsIn' => 'Subcategories found in the category',
		'ErrSameCatSelected' => 'You selected the same category several times',
		'ErrForgotCat' => 'You forgot to choose the category',
		'ErrForgotField' => 'You forgot to inform the fields',
		'ErrCatAlreadyExists' => 'This name is already used',
		'AddProductToCat' => 'Add this product to a category?',
		'ImpossibleAddCat' => 'Impossible to add the category',
		'ImpossibleAssociateCategory' => 'Impossible to associate the category to',
		'WasAddedSuccessfully' => '<b>%s</b> was added successfully.',
		'ObjectAlreadyLinkedToCategory' => 'Element is already linked to this category.',
		'CategorySuccessfullyCreated' => 'This category %s has been added with success.',
		'ProductIsInCategories' => 'Product/service owns to following categories',
		'SupplierIsInCategories' => 'Third party owns to following suppliers categories',
		'CompanyIsInCustomersCategories' => 'This third party owns to following customers/prospects categories',
		'CompanyIsInSuppliersCategories' => 'This third party owns to following suppliers categories',
		'MemberIsInCategories' => 'This member owns to following members categories',
		'ProductHasNoCategory' => 'This product/service is not in any categories',
		'SupplierHasNoCategory' => 'This supplier is not in any categories',
		'CompanyHasNoCategory' => 'This company is not in any categories',
		'MemberHasNoCategory' => 'This member is not in any categories',
		'ClassifyInCategory' => 'Classify in category',
		'NoneCategory' => 'Καμία',
		'NotCategorized' => 'Without category',
		'CategoryExistsAtSameLevel' => 'This category already exists with this ref',
		'ReturnInProduct' => 'Back to product/service card',
		'ReturnInSupplier' => 'Back to supplier card',
		'ReturnInCompany' => 'Back to customer/prospect card',
		'ContentsVisibleByAll' => 'The contents will be visible by all',
		'ContentsVisibleByAllShort' => 'Contents visible by all',
		'ContentsNotVisibleByAllShort' => 'Contents not visible by all',
		'CategoriesTree' => 'Categories tree',
		'DeleteCategory' => 'Διαγραφή Κατηγορίας',
		'ConfirmDeleteCategory' => 'Are you sure you want to delete this category ?',
		'RemoveFromCategory' => 'Remove link with categorie',
		'RemoveFromCategoryConfirm' => 'Are you sure you want to remove link between the transaction and the category ?',
		'NoCategoriesDefined' => 'Δεν έχει οριστεί κατηγορία',
		'SuppliersCategoryShort' => 'Κατηγορία Προμηθευτών',
		'CustomersCategoryShort' => 'Κατηγορία Πελατών',
		'ProductsCategoryShort' => 'Κατηγορία Προϊόντων',
		'MembersCategoryShort' => 'Κατηγορία Μελών',
		'SuppliersCategoriesShort' => 'Κατηγορίες Προμηθευτών',
		'CustomersCategoriesShort' => 'Κατηγορίες Πελατών',
		'CustomersProspectsCategoriesShort' => 'Κατηγορίες Πελατών/Προοπτ',
		'ProductsCategoriesShort' => 'Κατηγορίες Προϊόντων',
		'MembersCategoriesShort' => 'Κατηγορίες Μελών',
		'ThisCategoryHasNoProduct' => 'This category does not contain any product.',
		'ThisCategoryHasNoSupplier' => 'This category does not contain any supplier.',
		'ThisCategoryHasNoCustomer' => 'This category does not contain any customer.',
		'ThisCategoryHasNoMember' => 'This category does not contain any member.',
		'AssignedToCustomer' => 'Assigned to a customer',
		'AssignedToTheCustomer' => 'Assigned to the customer',
		'InternalCategory' => 'Εσωτερική Κατηγορία',
		'CategoryContents' => 'Περιεχόμενα Κατηγορίας',
		'CategId' => 'Κωδικός Κατηγορίας',
		'CatSupList' => 'List of supplier categories',
		'CatCusList' => 'List of customer/prospect categories',
		'CatProdList' => 'List of products categories',
		'CatMemberList' => 'List of members categories',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ContactsCategoryShort' => 'Catégorie contact',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)'
);
?>