<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Εμπορικό',
		'CommercialArea' => 'Περιοχή Εμπορικού',
		'CommercialCard' => 'Καρτέλα Εμπορικού',
		'CustomerArea' => 'Περιοχή Πελατών',
		'Customer' => 'Πελάτης',
		'Customers' => 'Πελάτες',
		'Prospect' => 'Προοπτική',
		'Prospects' => 'Προοπτικές',
		'Suspects' => 'Suspects',
		'DeleteAction' => 'Διαγραφή Ενέργειας/Εργασίας',
		'NewAction' => 'Νέα Ενέργεια/Εργασία',
		'AddAction' => 'Προσθήκη Ενέργειας/Εργασίας',
		'AddAnAction' => 'Προσθήκη Ενέργειας/Εργασίας',
		'AddActionRendezVous' => 'Προσθήκη Συνάντησης',
		'Rendez-Vous' => 'Συναντήσεις',
		'ConfirmDeleteAction' => 'Είστε σίγουροι ότι θέλετε να διαγράψετε την ενέργεια;',
		'CardAction' => 'Καρτέλα Ενέργειας',
		'PercentDone' => 'Ποσοστό Ολοκλήρωσης',
		'ActionOnCompany' => 'Εργασία για την εταιρία',
		'ActionOnContact' => 'Εργασία για το πρόσωπο επικοινωνίας',
		'TaskRDV' => 'Συναντήσεις',
		'TaskRDVWith' => 'Συνάντηση με %s',
		'ShowTask' => 'Εμφάνιση Εργασίας',
		'ShowAction' => 'Εμφάνιση Ενέργειας',
		'ActionsReport' => 'Αναφορά Ενεργειών',
		'ThirdPartiesOfSaleRepresentative' => 'Thirdparties with sales representative',
		'SalesRepresentative' => 'Αντιπρόσωπος πωλήσεων',
		'SalesRepresentatives' => 'Αντιπρόσωποι πωλήσεων',
		'SalesRepresentativeFollowUp' => 'Sales representative (follow-up)',
		'SalesRepresentativeSignature' => 'Sales representative (signature)',
		'CommercialInterlocutor' => 'Commercial interlocutor',
		'ErrorWrongCode' => 'Εσφαλμένος Κώδικας',
		'NoSalesRepresentativeAffected' => 'No particular sales representative affected',
		'ShowCustomer' => 'Εμφάνιση Πελάτη',
		'ShowProspect' => 'Εμφάνιση Προοπτικής',
		'ShowSuspect' => 'Show suspect',
		'ListOfProspects' => 'Λίστα Προοπτικών',
		'ListOfCustomers' => 'Λίστα Πελατών',
		'ListOfSuspects' => 'Liste des suspects',
		'ListOfAll' => 'Liste de tous les comptes',
		'ListSuspectsShort' => 'Liste suspects',
		'ListAllShort' => 'Liste tous les comptes',
		'LastDoneTasks' => 'Οι %s τελευταίες ολοκληρωμένες εργασίες',
		'LastRecordedTasks' => 'Οι πιο πρόσφατες καταχωρημένες υποχρεώσεις',
		'LastActionsToDo' => 'Οι τελευταίες %s παλαιότερες ενέργειες που δεν ολοκληρώθηκαν',
		'DoneAndToDoActionsFor' => 'Ολοκληρωμένες και τρέχουσες υποχρεώσεις για %s',
		'DoneAndToDoActions' => 'Ολοκληρωμένες και τρέχουσες ενέργειες',
		'DoneActions' => 'Ολοκληρωμένες Ενέργειες',
		'DoneActionsFor' => 'Ολοκληρωμένες Ενέργειες γιά %s',
		'ToDoActions' => 'Ημιτελείς Ενέργειες',
		'ToDoActionsFor' => 'Ημιτελείς Ενέργειες για %s',
		'SendPropalRef' => 'Αποστολή εμπορικής πρότασης %s',
		'SendOrderRef' => 'Αποστολή παραγγελίας %s',
		'StatusNotApplicable' => 'Δεν ισχύει',
		'StatusActionToDo' => 'Να γίνουν',
		'StatusActionDone' => 'Ολοκληρωμένη',
		'StatusActionInProcess' => 'Σε εξέλιξη',
		'MyActionsAsked' => 'Ενέργειες που καταχώρησα',
		'MyActionsToDo' => 'Ενέργειες που πρέπει να κάνω',
		'MyActionsDone' => 'Ενέργειες που με αφορούν',
		'TasksHistoryForThisContact' => 'Ενέργειες για το πρόσωπο επικοινωνίας',
		'LastProspectDoNotContact' => 'Να μην γίνει επικοινωνία',
		'LastProspectNeverContacted' => 'Δεν έχει γίνει επικοινωνία',
		'LastProspectToContact' => 'Να γίναι επικοινωνία',
		'LastProspectContactInProcess' => 'Επικοινωνία σε εξέλιξη',
		'LastProspectContactDone' => 'Η επικοινωνία έγινε',
		'DateActionPlanned' => 'Ημερ. προγραμματισμού',
		'DateActionDone' => 'Ημερ. ολοκλήρωσης',
		'ActionAskedBy' => 'Η ενέργεια ζητήθηκε από',
		'ActionAffectedTo' => 'Η ενέργεια αφορά τον/την',
		'ActionDoneBy' => 'Η ενέργεια έγινε από τον/την',
		'ActionUserAsk' => 'Καταγράφηκε από τον/την',
		'ErrorStatusCantBeZeroIfStarted' => 'If field \'<b>Date done</b>\' is filled, action is started (or finished), so field \'<b>Status</b>\' can\'t be 0%%.',
		'ActionAC_TEL' => 'Τηλεφώνημα',
		'ActionAC_FAX' => 'Αποστολή FAX',
		'ActionAC_PROP' => 'Αποστολή πρότασης με email',
		'ActionAC_EMAIL' => 'Αποστολή email',
		'ActionAC_RDV' => 'Συναντήσεις',
		'ActionAC_FAC' => 'Αποστολή Τιμολογίου στον πελάτη με email',
		'ActionAC_REL' => 'Αποστολή Τιμολογίου στον πελάτη με	email (υπενθύμιση)',
		'ActionAC_CLO' => 'Κλείσιμο',
		'ActionAC_EMAILING' => 'Αποστολή μαζικών email',
		'ActionAC_COM' => 'Αποστολή παραγγελίας πελάτη με email',
		'ActionAC_SHIP' => 'Αποστολή ναυτιλία με e-mail',
		'ActionAC_SUP_ORD' => 'Αποστολή παραγγελίας προμηθευτή με email',
		'ActionAC_SUP_INV' => 'Αποστολή τιμολογίου προμηθευτή με email',
		'ActionAC_OTH' => 'Άλλο',
		'Stats' => 'Sales statistics',
		'CAOrder' => 'Sales volume (validated orders)',
		'FromTo' => 'from %s to %s',
		'MargeOrder' => 'Margins (validated orders)',
		'RecapAnnee' => 'Summary of the year',
		'NoData' => 'There is no data',
		'StatusProsp' => 'Κατάσταση Prospect',
		'DraftPropals' => 'Σχέδιο εμπορικές προτάσεις',
		'SearchPropal' => 'Αναζητήστε μία εμπορική πρόταση'
);
?>