<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$other = array(
		'CHARSET' => 'UTF-8',
		'SecurityCode' => 'Κωδικός ασφαλείας',
		'Calendar' => 'Ημερολόγιο',
		'AddTrip' => 'Προσθήκη ταξιδιού',
		'Tools' => 'Εργαλεία',
		'ToolsDesc' => 'Αυτή η περιοχή είναι αφιερωμένη στην ομάδα διάφορα εργαλεία που είναι διαθέσιμα δεν σε άλλες καταχωρήσεις μενού. <br><br> Αυτά τα εργαλεία είναι προσβάσιμα από το μενού στο πλάι.',
		'Birthday' => 'Γενέθλια',
		'BirthdayDate' => 'Γενέθλια',
		'DateToBirth' => 'Ημερομ. γέννησης',
		'BirthdayAlertOn' => 'Ειδοποίηση γενεθλίων ενεργή',
		'BirthdayAlertOff' => 'Ειδοποίηση γενεθλίων ανενεργή',
		'Notify_FICHINTER_VALIDATE' => 'Intervention validated',
		'Notify_BILL_VALIDATE' => 'Το τιμολόγιο πελάτη επικυρώθηκε',
		'Notify_ORDER_SUPPLIER_APPROVE' => 'Η παραγγελία προμηθευτή εγγρίθηκε',
		'Notify_ORDER_SUPPLIER_REFUSE' => 'Η παραγγελία προμηθευτή απορρίφθηκε',
		'Notify_ORDER_VALIDATE' => 'Η παραγγελία πελάτη επικυρώθηκε',
		'Notify_PROPAL_VALIDATE' => 'Η εμπ. πρόταση πελάτη επικυρώθηκε',
		'Notify_WITHDRAW_TRANSMIT' => 'Μετάδοση απόσυρση',
		'Notify_WITHDRAW_CREDIT' => 'Πιστωτικές απόσυρση',
		'Notify_WITHDRAW_EMIT' => 'Εκτελέστε την απόσυρση',
		'Notify_ORDER_SENTBYMAIL' => 'Για πελατών αποστέλλονται με το ταχυδρομείο',
		'Notify_COMPANY_CREATE' => 'Τρίτο κόμμα δημιουργήθηκε',
		'Notify_PROPAL_SENTBYMAIL' => 'Εμπορικές προτάσεις που αποστέλλονται ταχυδρομικώς',
		'Notify_ORDER_SENTBYMAIL' => 'Για πελατών αποστέλλονται με το ταχυδρομείο',
		'Notify_BILL_PAYED' => 'Τιμολογίου Πελατών payed',
		'Notify_BILL_CANCEL' => 'Τιμολογίου Πελατών ακυρώσεις',
		'Notify_BILL_SENTBYMAIL' => 'Τιμολογίου Πελατών σταλούν ταχυδρομικώς',
		'Notify_ORDER_SUPPLIER_VALIDATE' => 'Για επικυρωθεί Προμηθευτής',
		'Notify_ORDER_SUPPLIER_SENTBYMAIL' => 'Για Προμηθευτής σταλούν ταχυδρομικώς',
		'Notify_BILL_SUPPLIER_VALIDATE' => 'Τιμολόγιο Προμηθευτή επικυρωθεί',
		'Notify_BILL_SUPPLIER_PAYED' => 'Τιμολόγιο Προμηθευτή payed',
		'Notify_BILL_SUPPLIER_SENTBYMAIL' => 'Τιμολόγιο Προμηθευτή σταλούν ταχυδρομικώς',
		'Notify_CONTRACT_VALIDATE' => 'Επικυρωμένη σύμβαση',
		'Notify_FICHEINTER_VALIDATE' => 'Επικυρωθεί Παρέμβαση',
		'Notify_SHIPPING_VALIDATE' => 'Αποστολή επικυρωθεί',
		'Notify_SHIPPING_SENTBYMAIL' => 'Αποστολές αποστέλλονται με το ταχυδρομείο',
		'Notify_MEMBER_VALIDATE' => 'Επικυρωθεί μέλη',
		'Notify_MEMBER_SUBSCRIPTION' => 'Εγγραφεί μέλος',
		'Notify_MEMBER_RESILIATE' => 'Resiliated μέλη',
		'Notify_MEMBER_DELETE' => 'Διαγράφεται μέλη',
		'NbOfAttachedFiles' => 'Πλήθος επισυναπτώμενων αρχείων/εγγράφων',
		'TotalSizeOfAttachedFiles' => 'Συνολικό μέγεθος επισυναπτώμενων αρχείων/εγγράφων',
		'MaxSize' => 'Μέγιστο μέγεθος',
		'AttachANewFile' => 'Επισύναψη νέου αρχείου/εγγράφου',
		'LinkedObject' => 'Συνδεδεμένα αντικείμενα',
		'Miscellanous' => 'Διάφορα',
		'NbOfActiveNotifications' => 'Πλήθος ειδοποιήσεων',
		'PredefinedMailTest' => 'Δοκιμαστικο mail.\nΟι δύο γραμμές είναι χωρισμένες με carriage return.',
		'PredefinedMailTestHtml' => 'Αυτό είναι ένα μήνυμα <b>δοκιμής</b> (η δοκιμή λέξη πρέπει να είναι με έντονα γράμματα). <br> Οι δύο γραμμές που χωρίζονται με ένα χαρακτήρα επαναφοράς.',
		'PredefinedMailContentSendInvoice' => 'Εδώ θα βρείτε το τιμολόγιο __ FACREF__ \n\n __PERSONALIZED__Ειλικρινά \n\n__SIGNATURE__',
		'PredefinedMailContentSendInvoiceReminder' => 'Θα θέλαμε να σας προειδοποιήσω ότι το τιμολόγιο FACREF__ __ φαίνεται να μη πληρώνονται. Έτσι, αυτό είναι το τιμολόγιο στο συνημμένο και πάλι, ως υπενθύμιση. Ειλικρινά \n\n__PERSONALIZED__ \n\n__SIGNATURE__',
		'PredefinedMailContentSendProposal' => 'Εδώ θα βρείτε την εμπορική propoal __ PROPREF__ \n\n__PERSONALIZED__ Ειλικρινά \n\n__SIGNATURE__',
		'PredefinedMailContentSendOrder' => 'Εδώ θα βρείτε τη σειρά __ ORDERREF__ \n\n__PERSONALIZED__ Ειλικρινά \n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierOrder' => 'Εδώ θα βρείτε για μας __ ORDERREF__ \n\n__PERSONALIZED__ Ειλικρινά \n\n__SIGNATURE__',
		'PredefinedMailContentSendSupplierInvoice' => 'Εδώ θα βρείτε το τιμολόγιο __ FACREF__ \n\n__PERSONALIZED__ Ειλικρινά \n\n__SIGNATURE__',
		'PredefinedMailContentSendShipping' => 'Θα βρείτε εδώ τη ναυτιλία __SHIPPINGREF__ \n\n__PERSONALIZED__Sincerely \n\n__SIGNATURE__',
		'PredefinedMailContentSendFichInter' => 'Θα βρείτε εδώ την παρέμβαση __ FICHINTERREF__ \n\n__PERSONALIZED__ Ειλικρινά \n\n__SIGNATURE__',
		'DemoDesc' => 'Speedealing είναι ένα συμπαγές ERP / CRM αποτελείται από διάφορες λειτουργικές ενότητες. Ένα demo που περιλαμβάνει όλες τις ενότητες δεν σημαίνει τίποτα, όπως ποτέ δεν συμβαίνει αυτό. Έτσι, πολλά προφίλ επίδειξη είναι διαθέσιμα.',
		'ChooseYourDemoProfil' => 'Επιλέξτε το προφίλ που ταιριάζει με επίδειξη δραστηριότητά σας ...',
		'DemoFundation' => 'Διαχειριστείτε τα μέλη του ιδρύματος',
		'DemoFundation2' => 'Διαχειριστείτε τα μέλη και τον τραπεζικό λογαριασμό του ιδρύματος',
		'DemoCompanyServiceOnly' => 'Διαχειριστείτε μια δραστηριότητα παροχής υπηρεσιών ελεύθερος πώλησης μόνο',
		'DemoCompanyShopWithCashDesk' => 'Διαχειριστείτε το κατάστημα με ένα ταμείο',
		'DemoCompanyProductAndStocks' => 'Διαχειριστείτε μια μικρή ή μεσαία επιχείρηση πώλησης προϊόντων',
		'DemoCompanyAll' => 'Διαχειριστείτε μια μικρή ή μεσαία εταιρεία με πολλαπλές δραστηριότητες (όλες οι κύριες ενότητες)',
		'GoToDemo' => 'Μετάβαση στο demo',
		'CreatedBy' => 'Δημιουργήθηκε από %s',
		'ModifiedBy' => 'Τροποποίηθηκε από %s',
		'ValidatedBy' => 'Επικυρώθηκε από  %s',
		'CanceledBy' => 'Ακυρώθηκε από %s',
		'ClosedBy' => 'Έκλεισε από  %s',
		'FileWasRemoved' => 'File %s was removed',
		'DirWasRemoved' => 'Directory %s was removed',
		'FeatureNotYetAvailableShort' => 'Διαθέσιμο σε μία επόμενη έκδοση',
		'FeatureNotYetAvailable' => 'Διαθέσιμο σε μία επόμενη έκδοση',
		'FeatureExperimental' => 'Πειραματική χαρακτηριστικό. Δεν είναι σταθερή σε αυτή την έκδοση',
		'FeatureDevelopment' => 'Χαρακτηριστικό Ανάπτυξης. Δεν είναι σταθερή σε αυτή την έκδοση',
		'FeaturesSupported' => 'Δυνατότητες που υποστηρίζονται',
		'Width' => 'Πλάτος',
		'Height' => 'Ύψος',
		'Depth' => 'Βάθος',
		'Top' => 'Κορυφή',
		'Bottom' => 'Κάτω μέρος',
		'Left' => 'Αριστερά',
		'Right' => 'Δικαίωμα',
		'CalculatedWeight' => 'Υπολογισμένο βάρος',
		'CalculatedVolume' => 'Υπολογισμένος όγκος',
		'Weight' => 'Βάρος',
		'TotalWeight' => 'Συνολικό βάρος',
		'WeightUnitton' => 'τόνοι',
		'WeightUnitkg' => 'kg',
		'WeightUnitg' => 'g',
		'WeightUnitmg' => 'mg',
		'WeightUnitpound' => 'pound',
		'Length' => 'Μήκος',
		'LengthUnitm' => 'm',
		'LengthUnitdm' => 'dm',
		'LengthUnitcm' => 'cm',
		'LengthUnitmm' => 'mm',
		'Surface' => 'Εμβαδό',
		'SurfaceUnitm2' => 'm2',
		'SurfaceUnitdm2' => 'dm2',
		'SurfaceUnitcm2' => 'cm2',
		'SurfaceUnitmm2' => 'mm2',
		'SurfaceUnitfoot2' => 'ft2',
		'SurfaceUnitinch2' => 'in2',
		'Volume' => 'Όγκος',
		'TotalVolume' => 'Συνολικός όγκος',
		'VolumeUnitm3' => 'm3',
		'VolumeUnitdm3' => 'dm3',
		'VolumeUnitcm3' => 'cm3',
		'VolumeUnitmm3' => 'mm3',
		'VolumeUnitfoot3' => 'ft3',
		'VolumeUnitinch3' => 'in3',
		'VolumeUnitounce' => 'ουγκιά',
		'VolumeUnitlitre' => 'λίτρο',
		'VolumeUnitgallon' => 'gallon',
		'Size' => 'μέγεθος',
		'SizeUnitm' => 'm',
		'SizeUnitdm' => 'dm',
		'SizeUnitcm' => 'cm',
		'SizeUnitmm' => 'mm',
		'SizeUnitinch' => 'ίντσα',
		'SizeUnitfoot' => 'πόδι',
		'SizeUnitpoint' => 'point',
		'BugTracker' => 'Tracker Bug',
		'SendNewPasswordDesc' => 'Αυτή η μορφή σας επιτρέπει να ζητήσετε ένα νέο κωδικό πρόσβασης. Θα πρέπει να στείλετε στο e-mail σας. <br> Η αλλαγή θα είναι αποτελεσματική μόνο μετά κάνετε κλικ στο σύνδεσμο επιβεβαίωσης μέσα σε αυτό το email. <br> Ελέγξτε το email πρόγραμμα ανάγνωσης.',
		'BackToLoginPage' => 'Επιστροφή στην σελίδα εισόδου',
		'AuthenticationDoesNotAllowSendNewPassword' => 'Λειτουργία ελέγχου ταυτότητας είναι <b>%s.</b> <br> Σε αυτή τη λειτουργία, Speedealing δεν μπορεί να γνωρίζει ούτε αλλαγή του κωδικού πρόσβασής σας. <br> Επικοινωνήστε με το διαχειριστή του συστήματός σας, εάν θέλετε να αλλάξετε τον κωδικό πρόσβασής σας.',
		'EnableGDLibraryDesc' => 'Εγκατάσταση ή ενεργοποίηση GD βιβλιοθήκη με την PHP σας για χρήση αυτής της επιλογής.',
		'EnablePhpAVModuleDesc' => 'Θα πρέπει να εγκαταστήσετε μια μονάδα συμβατή με anti-virus σας. (ClamAV: php4-clamavlib ou php5-clamavlib)',
		'ProfIdShortDesc' => '<b>Καθ %s ταυτότητα</b> είναι μια ενημερωτική ανάλογα με τρίτη χώρα μέρος. <br> Για παράδειγμα, για <b>%s</b> χώρα, είναι <b>%s</b> κώδικα.',
		'SpeedealingDemo' => 'Speedealing ERP/CRM demo',
		'StatsByNumberOfUnits' => 'Στατιστικά στοιχεία τον αριθμό των προϊόντων / υπηρεσιών μονάδες',
		'StatsByNumberOfEntities' => 'Στατιστικά στοιχεία τον αριθμό των φορέων που αναφέρονται',
		'NumberOfProposals' => 'Ο αριθμός των προτάσεων για την τελευταία 12 μήνες',
		'NumberOfCustomerOrders' => 'Αριθμός των παραγγελιών των πελατών κατά την τελευταία 12 μήνες',
		'NumberOfCustomerInvoices' => 'Αριθμός των τιμολογίων των πελατών για την τελευταία 12 μήνες',
		'NumberOfSupplierInvoices' => 'Αριθμός των τιμολογίων προμηθευτή σε τελευταία 12 μήνες',
		'NumberOfUnitsProposals' => 'Αριθμός μονάδων σχετικά με τις προτάσεις για την τελευταία 12 μήνες',
		'NumberOfUnitsCustomerOrders' => 'Αριθμός μονάδων σχετικά με τις παραγγελίες των πελατών για την τελευταία 12 μήνες',
		'NumberOfUnitsCustomerInvoices' => 'Αριθμός μονάδων στα τιμολόγια των πελατών για την τελευταία 12 μήνες',
		'NumberOfUnitsSupplierInvoices' => 'Αριθμός μονάδων στα τιμολόγια προμηθευτή για την τελευταία 12 μήνες',
		'EMailTextInterventionValidated' => 'Η %s παρέμβαση έχει επικυρωθεί.',
		'EMailTextInvoiceValidated' => 'Το τιμολόγιο %s έχει επικυρωθεί.',
		'EMailTextProposalValidated' => 'Η %s πρόταση έχει επικυρωθεί.',
		'EMailTextOrderValidated' => 'Η σειρά %s έχει επικυρωθεί.',
		'EMailTextOrderApproved' => 'Η %s παραγγελία έχει εγκριθεί.',
		'EMailTextOrderApprovedBy' => 'Η σειρά %s έχει εγκριθεί από %s.',
		'EMailTextOrderRefused' => 'Η σειρά %s έχει απορριφθεί.',
		'EMailTextOrderRefusedBy' => 'Η σειρά %s έχει απορριφθεί από %s.',
		'ImportedWithSet' => 'Η εισαγωγή των δεδομένων που',
		'SpeedealingNotification' => 'Automatic notification',
		'ResizeDesc' => 'Εισάγετε το νέο πλάτος <b>ή το</b> νέο ύψος. Λόγος θα διατηρηθούν κατά τη διάρκεια της αλλαγής μεγέθους ...',
		'NewLength' => 'Νέο βάρος',
		'NewHeight' => 'Νέο ύψος',
		'NewSizeAfterCropping' => 'Νέο μέγεθος μετά το ψαλίδισμα',
		'DefineNewAreaToPick' => 'Ορίστε νέα περιοχή στην εικόνα για να πάρει (αριστερό κλικ στην εικόνα στη συνέχεια σύρετε μέχρι να φτάσετε στην απέναντι γωνία)',
		'CurrentInformationOnImage' => 'Το εργαλείο αυτό σχεδιάστηκε για να σας βοηθήσει να αλλάξετε το μέγεθος ή την καλλιέργεια μιας εικόνας. Πρόκειται για πληροφορίες σχετικά με τις τρέχουσες επεξεργασμένη εικόνα',
		'ImageEditor' => 'Επεξεργαστής εικόνας',
		'YouReceiveMailBecauseOfNotification' => 'Αυτό το μήνυμα επειδή το email σας έχει προστεθεί στη λίστα των στόχων που πρέπει να ενημερώνεται για συγκεκριμένα γεγονότα σε %s λογισμικό της %s.',
		'YouReceiveMailBecauseOfNotification2' => 'Το γεγονός είναι το ακόλουθο:',
		'ThisIsListOfModules' => 'Αυτή είναι μια λίστα των modules που έχουν επιλέξει αυτό το προφίλ demo (μόνο οι περισσότερες κοινές ενότητες είναι ορατά σε αυτό το demo). Επεξεργασία αυτό να έχει μια πιο εξατομικευμένη επίδειξη και κάντε κλικ στο &quot;Start&quot;.',
		'ClickHere' => 'Πατήστε εδώ',
		'UseAdvancedPerms' => 'Χρησιμοποιήστε την προηγμένη δικαιώματα κάποιων ενοτήτων',
		'FileFormat' => 'Μορφή αρχείου',
		'SelectAColor' => 'Επιλέξτε ένα χρώμα',
		'AddFiles' => 'Προσθήκη αρχείων',
		'StartUpload' => 'Έναρξη μεταφόρτωσης',
		'CancelUpload' => 'Ακύρωση ανεβάσετε',
		'FileIsTooBig' => 'Τα αρχεία είναι πολύ μεγάλο',
		'PleaseBePatient' => 'Please be patient...',
		////////// Calendar common //////////
		'AddCalendarEntry' => 'Προσθήκη εγγραφής στο ημερολόγιο %s',
		'NewCompanyToSpeedealing' => 'Company %s added into Speedealing',
		'ContractValidatedInSpeedealing' => 'Contract %s validated in Speedealing',
		'ContractCanceledInSpeedealing' => 'Contract %s canceled in Speedealing',
		'ContractClosedInSpeedealing' => 'Contract %s closed in Speedealing',
		'PropalClosedSignedInSpeedealing' => 'Proposal %s signed in Speedealing',
		'PropalClosedRefusedInSpeedealing' => 'Proposal %s refused in Speedealing',
		'PropalValidatedInSpeedealing' => 'Proposal %s validated in Speedealing',
		'InvoiceValidatedInSpeedealing' => 'Invoice %s validated in Speedealing',
		'InvoicePaidInSpeedealing' => 'Invoice %s changed to paid in Speedealing',
		'InvoiceCanceledInSpeedealing' => 'Invoice %s canceled in Speedealing',
		'PaymentDoneInSpeedealing' => 'Payment %s done in Speedealing',
		'CustomerPaymentDoneInSpeedealing' => 'Customer payment %s done in Speedealing',
		'SupplierPaymentDoneInSpeedealing' => 'Supplier payment %s done in Speedealing',
		'MemberValidatedInSpeedealing' => 'Member %s validated in Speedealing',
		'MemberResiliatedInSpeedealing' => 'Member %s resiliated in Speedealing',
		'MemberDeletedInSpeedealing' => 'Member %s deleted from Speedealing',
		'MemberSubscriptionAddedInSpeedealing' => 'Subscription for member %s added in Speedealing',
		'ShipmentValidatedInSpeedealing' => 'Shipment %s validated in Speedealing',
		////////// Export //////////
		'Export' => 'Εξαγωγή',
		'ExportsArea' => 'Exports area',
		'AvailableFormats' => 'Available formats',
		'LibraryUsed' => 'Librairy used',
		'LibraryVersion' => 'Version',
		'ExportableDatas' => 'Exportable data',
		'NoExportableData' => 'No exportable data (no modules with exportable data loaded, or missing permissions)',
		'ToExport' => 'Export',
		'NewExport' => 'New export',
		////////// External sites //////////
		'ExternalSites' => 'External sites'
);
?>