<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$propal = array(
		'CHARSET' => 'UTF-8',
		'Proposals' => 'Εμπορικές προτάσεις',
		'Proposal' => 'Εμπορική πρόταση',
		'ProposalShort' => 'Πρόταση',
		'ProposalsDraft' => 'Draft commercial proposals',
		'ProposalDraft' => 'Draft commercial proposal',
		'ProposalsOpened' => 'Opened commercial proposals',
		'Prop' => 'Εμπορικές προτάσεις',
		'CommercialProposal' => 'Εμπορική πρόταση',
		'CommercialProposals' => 'Εμπορικές προτάσεις',
		'ProposalCard' => 'Καρτέλα πρότασης',
		'NewProp' => 'Νέα εμπορική πρόταση',
		'NewProposal' => 'Νέα εμπορική πρόταση',
		'NewPropal' => 'Νέα πρόταση',
		'Prospect' => 'Προοπτική',
		'ProspectList' => 'Λίστα προοπτικών',
		'DeleteProp' => 'Διαγραφή εμπορικής πρότασης',
		'ValidateProp' => 'Επικύρωση εμπορικής πρότασης',
		'AddProp' => 'Προσθήκη πρότασης',
		'ConfirmDeleteProp' => 'Are you sure you want to delete this commercial proposal ?',
		'ConfirmValidateProp' => 'Are you sure you want to validate this commercial proposal ?',
		'LastPropals' => 'Last %s proposals',
		'LastClosedProposals' => 'Last %s closed proposals',
		'LastModifiedProposals' => '%s τελευταίες εμπορικές προτάσεις',
		'AllPropals' => 'Όλες οι προτάσεις',
		'LastProposals' => 'Τελευταίες προτάσεις',
		'SearchAProposal' => 'Εύρεση πρότασης',
		'ProposalsStatistics' => 'Commercial proposal\'s statistics',
		'NumberOfProposalsByMonth' => 'Number by month',
		'AmountOfProposalsByMonthHT' => 'Amount by month (net of tax)',
		'NbOfProposals' => 'Number of commercial proposals',
		'ShowPropal' => 'Show proposal',
		'PropalsDraft' => 'Drafts',
		'PropalsOpened' => 'Opened',
		'PropalsNotBilled' => 'Closed not billed',
		'PropalStatusDraft' => 'Draft (needs validation)',
		'PropalStatusValidated' => 'Validated (proposal is open)',
		'PropalStatusOpened' => 'Validated (proposal is open)',
		'PropalStatusClosed' => 'Closed',
		'PropalStatusSigned' => 'Signed (needs billing)',
		'PropalStatusNotSigned' => 'Not signed (closed)',
		'PropalStatusBilled' => 'Billed',
		'PropalStatusDraftShort' => 'Draft',
		'PropalStatusValidatedShort' => 'Validated',
		'PropalStatusOpenedShort' => 'Opened',
		'PropalStatusClosedShort' => 'Closed',
		'PropalStatusSignedShort' => 'Signed',
		'PropalStatusNotSignedShort' => 'Not signed',
		'PropalStatusBilledShort' => 'Χρεωμένη',
		'PropalsToClose' => 'Εμπορικές προτάσεις προς κλείσιμο',
		'PropalsToBill' => 'Υπογεγραμμένες εμπορικές προτάσεις προς χρέωση',
		'ListOfProposals' => 'List of commercial proposals',
		'ActionsOnPropal' => 'Actions on proposal',
		'NoOpenedPropals' => 'No opened commercial proposals',
		'NoOtherOpenedPropals' => 'No other opened commercial proposals',
		'RefProposal' => 'Commercial proposal ref',
		'SendPropalByMail' => 'Send commercial proposal by mail',
		'FileNotUploaded' => 'The file was not uploaded',
		'FileUploaded' => 'The file was successfully uploaded',
		'AssociatedDocuments' => 'Documents associated with the proposal:',
		'ErrorCantOpenDir' => 'Can\'t open directory',
		'DatePropal' => 'Date of proposal',
		'DateEndPropal' => 'Date end validity',
		'DateEndPropalShort' => 'Date end',
		'ValidityDuration' => 'Validity duration',
		'CloseAs' => 'Close with status',
		'ClassifyBilled' => 'Classify billed',
		'BuildBill' => 'Build invoice',
		'ErrorPropalNotFound' => 'Propal %s not found',
		'Estimate' => 'Estimate :',
		'EstimateShort' => 'Estimate',
		'OtherPropals' => 'Άλλες προτάσεις',
		'CopyPropalFrom' => 'Δημιουργία εμπορική πρόταση με την αντιγραφή υφιστάμενη πρόταση',
		'CreateEmptyPropal' => 'Δημιουργία κενών εμπορικών vierge προτάσεις ή από την λίστα των προϊόντων / υπηρεσιών',
		'DefaultProposalDurationValidity' => 'Προεπιλογή εμπορική διάρκεια ισχύος πρόταση (σε ημέρες)',
		'UseCustomerContactAsPropalRecipientIfExist' => 'Χρησιμοποιήστε διεύθυνση επικοινωνίας του πελάτη, εάν αυτή ορίζεται αντί του τρίτου μέρους διεύθυνση ως διεύθυνση παραλήπτη πρόταση',
		'ClonePropal' => 'Κλώνος εμπορική πρόταση',
		'ConfirmClonePropal' => 'Είστε βέβαιοι ότι θέλετε να κλωνοποιήσουν τα εμπορικά <b>%s</b> πρόταση;',
		'ConfirmReOpenProp' => 'Είστε βέβαιοι ότι θέλετε να ανοίξετε ξανά τις εμπορικές <b>%s</b> πρόταση;',
		'ProposalsAndProposalsLines' => 'Εμπορικές προτάσεις και γραμμές',
		'ProposalLine' => 'Πρόταση γραμμή',
		'ProposalLines' => 'Proposal lines',
		'AvailabilityPeriod' => 'Καθυστέρηση Διαθεσιμότητα',
		'SetAvailability' => 'Ορισμός καθυστέρηση διαθεσιμότητα',
		'AfterOrder' => 'μετά την παραγγελία',
		////////// Availability //////////
		'AvailabilityTypeAV_NOW' => 'Άμεση',
		'AvailabilityTypeAV_1W' => '1 εβδομάδα',
		'AvailabilityTypeAV_2W' => '2 εβδομάδες',
		'AvailabilityTypeAV_3W' => '3 εβδομάδες',
		'AvailabilityTypeAV_1M' => '1 μήνα',
		////////// Types de contacts //////////
		'TypeContact_propal_internal_SALESREPFOLL' => 'Εκπρόσωπος παρακολουθώντας πρόταση',
		'TypeContact_propal_external_BILLING' => 'Πελάτης επαφή τιμολόγιο',
		'TypeContact_propal_external_CUSTOMER' => 'Πελάτης επαφή την παρακολούθηση πρόταση',
		// Document models
		'DocModelAzurDescription' => 'Ένα πλήρες μοντέλο πρόταση (logo. ..)',
		'DocModelJauneDescription' => 'Jaune μοντέλο πρόταση',
		'Numbershort' => 'N°',
		'LinkdedOrders' => 'Linked orders'
);
?>