<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Αποθήκη κάρτα',
		'Warehouse' => 'Αποθήκη',
		'NewWarehouse' => 'Νέα αποθήκη / Χρηματιστήριο περιοχή',
		'WarehouseEdit' => 'Τροποποίηση αποθήκη',
		'MenuNewWarehouse' => 'Νέα αποθήκη',
		'WarehouseOpened' => 'Αποθήκη άνοιξε',
		'WarehouseClosed' => 'Αποθήκη κλειστό',
		'WarehouseSource' => 'Αποθήκη Πηγή',
		'WarehouseTarget' => 'Στόχος αποθήκη',
		'ValidateSending' => 'Διαγραφή αποστολή',
		'CancelSending' => 'Ακύρωση αποστολής',
		'DeleteSending' => 'Διαγραφή αποστολή',
		'Stock' => 'Χρηματιστήριο',
		'Stocks' => 'Αποθέματα',
		'Movement' => 'Κίνηση',
		'Movements' => 'Κινήματα',
		'ErrorWarehouseRefRequired' => 'Αποθήκη όνομα αναφοράς απαιτείται',
		'ErrorWarehouseLabelRequired' => 'Ετικέτα Αποθήκη απαιτείται',
		'CorrectStock' => 'Σωστή απόθεμα',
		'ListOfWarehouses' => 'Κατάλογος των αποθηκών',
		'ListOfStockMovements' => 'Κατάλογος των κινήσεων των αποθεμάτων',
		'StocksArea' => 'Αποθέματα περιοχή',
		'Location' => 'Τοποθεσία',
		'LocationSummary' => 'Σύντομη τοποθεσία όνομα',
		'NumberOfProducts' => 'Συνολικός αριθμός προϊόντων',
		'LastMovement' => 'Τελευταία κίνηση',
		'LastMovements' => 'Τελευταία κινήσεις',
		'Units' => 'Μονάδες',
		'Unit' => 'Μονάδα',
		'StockCorrection' => 'Σωστή απόθεμα',
		'StockMovement' => 'Μεταφορά',
		'StockMovements' => 'Μεταφορές Χρηματιστήριο',
		'NumberOfUnit' => 'Αριθμός μονάδων',
		'TotalStock' => 'Σύνολο σε απόθεμα',
		'StockTooLow' => 'Χρηματιστήριο πολύ χαμηλή',
		'EnhancedValue' => 'Αξία',
		'PMPValue' => 'Μέση σταθμική τιμή',
		'PMPValueShort' => 'WAP',
		'EnhancedValueOfWarehouses' => 'Αποθήκες αξία',
		'UserWarehouseAutoCreate' => 'Δημιουργήστε μια αποθήκη αυτόματα κατά τη δημιουργία ενός χρήστη',
		'QtyDispatched' => 'Ποσότητα αποστέλλονται',
		'OrderDispatch' => 'Χρηματιστήριο αποστολή',
		'RuleForStockManagementDecrease' => 'Κανόνας για μείωση της διαχείρισης των αποθεμάτων',
		'RuleForStockManagementIncrease' => 'Κανόνας για την αύξηση της διαχείρισης των αποθεμάτων',
		'DeStockOnBill' => 'Μείωση πραγματικών αποθεμάτων για τους πελάτες τιμολόγια / πιστωτικά επικύρωση σημειώσεις',
		'DeStockOnValidateOrder' => 'Μείωση πραγματικών αποθεμάτων σχετικά με τις παραγγελίες των πελατών επικύρωσης',
		'DeStockOnShipment' => 'Μείωση πραγματικών αποθεμάτων για την επικύρωση αποστολή',
		'ReStockOnBill' => 'Αύξηση πραγματικού αποθέματα για τους προμηθευτές τιμολόγια / πιστωτικά επικύρωση σημειώσεις',
		'ReStockOnValidateOrder' => 'Αύξηση πραγματικού αποθεμάτων σχετικά με τις παραγγελίες τους προμηθευτές επιδοκιμασίας',
		'ReStockOnDispatchOrder' => 'Αύξηση των αποθεμάτων σε πραγματικό εγχειρίδιο αποστολή σε αποθήκες, μετά από σειρά προμηθευτής που λαμβάνει',
		'OrderStatusNotReadyToDispatch' => 'Παραγγελία δεν έχει ακόμη ή όχι περισσότερο μια κατάσταση που επιτρέπει την αποστολή των προϊόντων σε αποθήκες αποθεμάτων.',
		'StockDiffPhysicTeoric' => 'Λόγος αποθεμάτων διαφορά φυσική και θεωρητική',
		'NoPredefinedProductToDispatch' => 'Δεν προκαθορισμένα προϊόντα για αυτό το αντικείμενο. Έτσι, δεν έχει αποστολή σε απόθεμα είναι απαραίτητη.',
		'DispatchVerb' => 'Αποστολή',
		'StockLimitShort' => 'Όριο',
		'StockLimit' => 'Χρηματιστήριο όριο για ειδοποιήσεις',
		'PhysicalStock' => 'Φυσικό απόθεμα',
		'RealStock' => 'Real Χρηματιστήριο',
		'TheoreticalStock' => 'Therocial απόθεμα',
		'VirtualStock' => 'Εικονική απόθεμα',
		'MininumStock' => 'Ελάχιστο απόθεμα',
		'StockUp' => 'Απόθεμα επάνω',
		'MininumStockShort' => 'Χρηματιστήριο min',
		'StockUpShort' => 'Απόθεμα επάνω',
		'IdWarehouse' => 'Id αποθήκη',
		'DescWareHouse' => 'Αποθήκη Περιγραφή',
		'LieuWareHouse' => 'Αποθήκη Localisation',
		'WarehousesAndProducts' => 'Αποθήκες και τα προϊόντα',
		'AverageUnitPricePMPShort' => 'Μέση σταθμική τιμή εισόδου',
		'AverageUnitPricePMP' => 'Μέση σταθμική τιμή εισόδου',
		'SellPriceMin' => 'Πώληση Τιμή μονάδας',
		'EstimatedStockValueSellShort' => 'Αξία για την πώληση',
		'EstimatedStockValueSell' => 'Αξία για Πώληση',
		'EstimatedStockValueShort' => 'Είσοδος αξία μετοχών',
		'EstimatedStockValue' => 'Είσοδος αξία μετοχών',
		'DeleteAWarehouse' => 'Διαγραφή μιας αποθήκης',
		'ConfirmDeleteWarehouse' => 'Είστε σίγουροι ότι θέλετε να διαγράψετε το <b>%s</b> αποθήκη;',
		'PersonalStock' => 'Προσωπικά %s απόθεμα',
		'ThisWarehouseIsPersonalStock' => 'Αυτή η αποθήκη αποτελεί προσωπική απόθεμα %s %s',
		'SelectWarehouseForStockDecrease' => 'Επιλέξτε αποθήκη που θα χρησιμοποιηθεί για μείωση αποθεμάτων',
		'SelectWarehouseForStockIncrease' => 'Επιλέξτε αποθήκη που θα χρησιμοποιηθεί για αύξηση των αποθεμάτων',
);
?>