<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'Καρτέλα Χρήστη',
		'ContactCard' => 'Καρτέλα αντιπροσώπου',
		'GroupCard' => 'Καρτέλα Ομάδας',
		'NoContactCard' => 'Δεν υπάρχουν καρτέλες αντιπροσώπων',
		'Permission' => 'Άδεια',
		'Permissions' => 'Άδειες',
		'EditPassword' => 'Επεξεργασία κωδικού',
		'SendNewPassword' => 'Επαναδημιουργία και αποστολή κωδικού',
		'ReinitPassword' => 'Επαναδημιουργία κωδικού',
		'PasswordChangedTo' => 'Ο κωδικός άλλαξε σε: %s',
		'SubjectNewPassword' => 'Ο νέος σας κωδικός για το Speedealing',
		'AvailableRights' => 'Διαθέσιμες άδειες',
		'OwnedRights' => 'Αποκτηθήσες άδειες',
		'GroupRights' => 'Άδειες ομάδας',
		'UserRights' => 'Άδειες χρήστη',
		'UserGUISetup' => 'Ρυθμίσεις εμφάνισης χρήστη',
		'DisableUser' => 'Απενεργοποίηση',
		'DisableAUser' => 'Απενεργοποίηση ενός χρήστη',
		'DeleteUser' => 'Διαγραφή',
		'DeleteAUser' => 'Διαγραφή ενός χρήστη',
		'DisableGroup' => 'Απενεργοποίηση',
		'DisableAGroup' => 'Απενεργοποίηση μίας ομάδας',
		'EnableAUser' => 'Ενεργοποίηση ενός χρήστη',
		'EnableAGroup' => 'Ενεργοποίηση μιας ομάδας',
		'DeleteGroup' => 'Διαγραφή',
		'DeleteAGroup' => 'Διαγραφή μιας ομάδας',
		'ConfirmDisableUser' => 'Are you sure you want to disable user <b>%s</b> ?',
		'ConfirmDisableGroup' => 'Are you sure you want to disable group <b>%s</b> ?',
		'ConfirmDeleteUser' => 'Are you sure you want to delete user <b>%s</b> ?',
		'ConfirmDeleteGroup' => 'Are you sure you want to delete group <b>%s</b> ?',
		'ConfirmEnableUser' => 'Are you sure you want to enable user <b>%s</b> ?',
		'ConfirmEnableGroup' => 'Are you sure you want to enable group <b>%s</b> ?',
		'ConfirmReinitPassword' => 'Are you sure you want to generate a new password for user <b>%s</b> ?',
		'ConfirmSendNewPassword' => 'Are you sure you want to generate and send new password for user <b>%s</b> ?',
		'NewUser' => 'Νέος χρήστης',
		'CreateUser' => 'Δημιουργία χρήστη',
		'SearchAGroup' => 'Εύρεση ομάδας',
		'SearchAUser' => 'Εύρεση χρήστη',
		'LoginNotDefined' => 'Το όνομα χρήστη δεν είναι καθορισμένο',
		'NameNotDefined' => 'Το όνομα δεν είναι καθορισμένο',
		'ListOfUsers' => 'Λίστα χρηστών',
		'Administrator' => 'Διαχειριστής',
		'SuperAdministrator' => 'Υπερδιαχειριστής',
		'SuperAdministratorDesc' => 'Διαχειριστής με όλα τα δικαιώματα',
		'AdministratorDesc' => 'Οντότητα Διαχειριστή',
		'DefaultRights' => 'Προκαθορισμένες άδειες',
		'DefaultRightsDesc' => 'Define here <u>default</u> permissions that are automatically granted to a <u>new created</u> user (Go on user card to change permission of an existing user).',
		'SpeedealingUsers' => 'Speedealing users',
		'LastName' => 'Επίθετο',
		'FirstName' => 'Όνομα',
		'ListOfGroups' => 'Λίστα ομάδων',
		'NewGroup' => 'Νέα ομάδα',
		'CreateGroup' => 'Δημιουργία ομάδας',
		'RemoveFromGroup' => 'Αφαίρεση από την ομάδα',
		'PasswordChangedAndSentTo' => 'Password changed and sent to <b>%s</b>.',
		'PasswordChangeRequestSent' => 'Request to change password for <b>%s</b> sent to <b>%s</b>.',
		'MenuUsersAndGroups' => 'Χρήστες και Ομάδες',
		'LastGroupsCreated' => 'Last %s created groups',
		'LastUsersCreated' => 'Last %s users created',
		'ShowGroup' => 'Εμφάνιση ομάδας',
		'ShowUser' => 'Εμφάνιση χρήστη',
		'NonAffectedUsers' => 'Non affected users',
		'UserModified' => 'User modified successfully',
		'GroupModified' => 'Group modified successfully',
		'PhotoFile' => 'Photo file',
		'UserWithSpeedealingAccess' => 'User with Speedealing access',
		'ListOfUsersInGroup' => 'List of users in this group',
		'ListOfGroupsForUser' => 'List of groups for this user',
		'UsersToAdd' => 'Users to add to this group',
		'GroupsToAdd' => 'Groups to add to this user',
		'NoLogin' => 'No login',
		'LinkToCompanyContact' => 'Link to third party / contact',
		'LinkedToSpeedealingMember' => 'Link to member',
		'LinkedToSpeedealingUser' => 'Link to Speedealing user',
		'LinkedToSpeedealingThirdParty' => 'Link to Speedealing third party',
		'CreateSpeedealingLogin' => 'Create a user',
		'CreateSpeedealingThirdParty' => 'Create a third party',
		'LoginAccountDisable' => 'Account disabled, put a new login to activate it.',
		'LoginAccountDisableInSpeedealing' => 'Account disabled in Speedealing.',
		'LoginAccountDisableInLdap' => 'Account disabled in the domain.',
		'UsePersonalValue' => 'Use personal value',
		'GuiLanguage' => 'Interface language',
		'InternalUser' => 'Internal user',
		'MyInformations' => 'My data',
		'ExportDataset_user_1' => 'Speedealing\'s users and properties',
		'DomainUser' => 'Domain user %s',
		'Reactivate' => 'Reactivate',
		'CreateInternalUserDesc' => 'This form allows you to creat an user internal to your company/foundation. To creat an external user (customer, supplier, ...), use button \'Create Speedealing user\' from third party\'s contact card.',
		'InternalExternalDesc' => 'An <b>internal</b> user is a user that is part of your company/foundation.<br>An <b>external</b> user is a customer, supplier or other.<br><br>In both cases, permissions defines rights on Speedealing, also external user can have a different menu manager than internal user (See Home - Setup - Display)',
		'PermissionInheritedFromAGroup' => 'Permission granted because inherited from one of a user\'s group.',
		'Inherited' => 'Inherited',
		'UserWillBeInternalUser' => 'Δημιουργήθηκε χρήστη θα είναι ένας εσωτερικός χρήστης (επειδή δεν συνδέεται με ένα συγκεκριμένο τρίτο μέρος)',
		'UserWillBeExternalUser' => 'Δημιουργήθηκε χρήστης θα είναι μια εξωτερική χρήστη (επειδή συνδέονται με μια συγκεκριμένη τρίτο μέρος)',
		'IdPhoneCaller' => 'Id phone caller',
		'UserLogged' => 'User %s connected',
		'UserLogoff' => '%s χρήστη logout',
		'NewUserCreated' => 'User %s created',
		'NewUserPassword' => 'Password change for %s',
		'EventUserModified' => 'User %s modified',
		'UserDisabled' => 'User %s disabled',
		'UserEnabled' => 'User %s activated',
		'UserDeleted' => 'User %s removed',
		'NewGroupCreated' => 'Group %s created',
		'GroupModified' => 'Group modified successfully',
		'GroupDeleted' => 'Group %s removed',
		'ConfirmCreateContact' => 'Are you sure you want to create a Speedealing account for this contact ?',
		'ConfirmCreateLogin' => 'Are you sure you want to create a Speedealing account for this member ?',
		'ConfirmCreateThirdParty' => 'Are you sure you want to create a third party for this member ?',
		'LoginToCreate' => 'Login to create',
		'NameToCreate' => 'Name of third party to create',
		'YourRole' => 'Your roles',
		'YourQuotaOfUsersIsReached' => 'Your quota of active users is reached !',
		'NbOfUsers' => 'Nb των χρηστών',
		'DontDowngradeSuperAdmin' => 'Μόνο μια superadmin μπορεί να προβεί στην ανακατάταξη ενός superadmin',
		'NewDatabase' => 'Nouvelle base de données',
		'CreateDatabase' => 'Créer la base de données',
		'ListOfDatabases' => 'Liste des bases de données',
		'ListOfUsersInDatabase' => 'Liste des utilisateurs liés à la base de données',
		'ListOfRolesInDatabase' => 'Liste des groupes liés à la base de données',
		'DeleteADatabase' => 'Suppression d\'une database',
		'ConfirmDatabase' => 'Êtes-vous sûr de vouloir supprimer la base de données <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Groupes non affectés à la base de données',
		'NonAffectedUsersDatabase' => 'Utilisateurs non affectés à la base de données',
		'Collaborators' => 'Collaborateurs',
		'Profiles' => 'Profils collaborateurs'
);
?>