<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$commercial = array(
		'CHARSET' => 'UTF-8',
		'Commercial' => 'Kommerciel',
		'CommercialArea' => 'Kommercielle område',
		'CommercialCard' => 'Kommerciel kortet',
		'CustomerArea' => 'Kunder område',
		'Customer' => 'Kunde',
		'Customers' => 'Kunder',
		'Prospect' => 'Prospect',
		'Prospects' => 'Perspektiver',
		'DeleteAction' => 'Slet en foranstaltning / opgave',
		'NewAction' => 'Ny action / opgave',
		'AddAction' => 'Tilføj action / opgave',
		'AddAnAction' => 'Tilføj en foranstaltning / opgave',
		'ConfirmDeleteAction' => 'Er du sikker på du vil slette denne opgave?',
		'CardAction' => 'Action-kortet',
		'PercentDone' => 'Procentdel gjort',
		'ActionOnCompany' => 'Opgave om virksomheden',
		'ActionOnContact' => 'Task om kontakt',
		'TaskRDV' => 'Møder',
		'TaskRDVWith' => 'Møde med %s',
		'ShowTask' => 'Vis opgave',
		'ShowAction' => 'Vis aktion',
		'ActionsReport' => 'Aktioner rapport',
		'SalesRepresentative' => 'Salg repræsentant',
		'SalesRepresentatives' => 'Salgsrepræsentanter',
		'SalesRepresentativeFollowUp' => 'Salg repræsentant (opfølgning)',
		'SalesRepresentativeSignature' => 'Salg repræsentant (underskrift)',
		'CommercialInterlocutor' => 'Kommerciel samtalepartner',
		'ErrorWrongCode' => 'Forkert kode',
		'NoSalesRepresentativeAffected' => 'Ingen særlige salg repræsentant påvirket',
		'ShowCustomer' => 'Vis kunde',
		'ShowProspect' => 'Vis udsigt',
		'ListOfProspects' => 'Liste over udsigterne',
		'ListOfCustomers' => 'Listen over kunder',
		'LastDoneTasks' => 'Seneste %s udført opgaver',
		'LastRecordedTasks' => 'Seneste registreres opgaver',
		'LastActionsToDo' => 'Seneste %s ældste aktioner ikke er afsluttet',
		'DoneAndToDoActionsFor' => 'Udfærdiget og gøre opgaver for %s',
		'DoneAndToDoActions' => 'Udfærdiget og gøre opgaver',
		'DoneActions' => 'Udfærdiget aktioner',
		'DoneActionsFor' => 'Gøres tiltag for %s',
		'SendPropalRef' => 'Send kommercielle forslag %s',
		'SendOrderRef' => 'Send for %s',
		'NoRecordedProspects' => 'Ingen udsigt registreres',
		'StatusActionToDo' => 'At gøre',
		'StatusActionDone' => 'Gjort',
		'MyActionsAsked' => 'Aktioner jeg har indspillet',
		'MyActionsToDo' => 'Initiativer, jeg har at gøre',
		'MyActionsDone' => 'Aktioner påvirket mig',
		'StatusActionInProcess' => 'I proces',
		'TasksHistoryForThisContact' => 'Handlinger for denne kontakt',
		'LastProspectDoNotContact' => 'Må ikke komme i kontakt med',
		'LastProspectNeverContacted' => 'Aldrig kontaktet',
		'LastProspectToContact' => 'Til at kontakte',
		'LastProspectContactInProcess' => 'Kontakt i processen',
		'LastProspectContactDone' => 'Kontakt gjort',
		'DateActionPlanned' => 'Dato aktion er planlagt til',
		'DateActionDone' => 'Dato indsats gøres',
		'ActionAskedBy' => 'Aktion spurgt af',
		'ActionAffectedTo' => 'Aktion påvirkes i',
		'ActionDoneBy' => 'Aktion gøres ved',
		'ActionUserAsk' => 'Registreres af',
		'ErrorStatusCantBeZeroIfStarted' => 'Hvis feltet <b>\'Dato gjort</b> «er fyldt handling er startet (eller afsluttet), så felt\' <b>Status\'</b> kan ikke være 0%%.',
		'ActionAC_TEL' => 'Telefonopkald',
		'ActionAC_FAX' => 'Send fax',
		'ActionAC_PROP' => 'Send forslag',
		'ActionAC_EMAIL' => 'Send Email',
		'ActionAC_RDV' => 'Møder',
		'ActionAC_FAC' => 'Send fakturering',
		'ActionAC_REL' => 'Send faktureringsstatus (påmindelse)',
		'ActionAC_CLO' => 'Luk',
		'ActionAC_EMAILING' => 'Send masse emailing',
		'ActionAC_COM' => 'Send ordre ved mail',
		'AddActionRendezVous' => 'Tilføj en Rendezvous opgave',
		'Rendez-Vous' => 'Rendezvous',
		'ToDoActions' => 'Ufuldstændig aktioner',
		'ToDoActionsFor' => 'Ufuldstændig aktioner for %s',
		'ActionAC_SUP_ORD' => 'Send leverandør opstil efter mail',
		'ActionAC_SUP_INV' => 'Send leverandør faktura med posten',
		'StatusNotApplicable' => 'Ikke relevant',
		'ActionAC_SHIP' => 'Send en forsendelse med posten',
		'ActionAC_OTH' => 'Andet',
		'StatusProsp' => 'Prospect status',
		'DraftPropals' => 'Forslaget til handelslov forslag',
		'SearchPropal' => 'Søg en kommerciel forslag',
);
?>