<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$contracts = array(
		'CHARSET' => 'UTF-8',
		'ContractsArea' => 'Kontrakter område',
		'ListOfContracts' => 'Liste over kontrakter',
		'LastContracts' => 'Seneste %s modificerede kontrakter',
		'AllContracts' => 'Alle kontrakter',
		'ContractCard' => 'Kontrakt-kortet',
		'ContractStatus' => 'Kontrakt status',
		'ContractStatusNotRunning' => 'Ikke kører',
		'ContractStatusRunning' => 'Kørsel',
		'ContractStatusDraft' => 'Udkast',
		'ContractStatusValidated' => 'Valideret',
		'ContractStatusClosed' => 'Lukket',
		'ServiceStatusInitial' => 'Ikke kører',
		'ServiceStatusRunning' => 'Kørsel',
		'ServiceStatusLate' => 'Kører, er udløbet',
		'ServiceStatusClosed' => 'Lukket',
		'ServicesLegend' => 'Services legend',
		'Contracts' => 'Kontrakter',
		'Contract' => 'Kontrakt',
		'NoContracts' => 'Nr. kontrakter',
		'MenuServices' => 'Services',
		'MenuInactiveServices' => 'Tjenester, der ikke er aktive',
		'MenuRunningServices' => 'Kørsel tjenester',
		'MenuExpiredServices' => 'Udløbet tjenester',
		'MenuClosedServices' => 'Lukket tjenester',
		'NewContract' => 'Ny kontrakt',
		'AddContract' => 'Tilføj kontrakt',
		'SearchAContract' => 'Søg en kontrakt',
		'DeleteAContract' => 'Slet en kontrakt',
		'CloseAContract' => 'Luk en kontrakt',
		'ConfirmDeleteAContract' => 'Er du sikker på du vil slette denne kontrakt og alle dets tjenester?',
		'ConfirmValidateContract' => 'Er du sikker på at du ønsker at validere denne kontrakt?',
		'ConfirmCloseContract' => 'Dette vil lukke alle tjenester (aktiv eller ej). Er du sikker på du ønsker at lukke denne kontrakt?',
		'ConfirmCloseService' => 'Er du sikker på du ønsker at lukke denne service med <b>dato %s?</b>',
		'ValidateAContract' => 'Validere en kontrakt',
		'ActivateService' => 'Aktivér service',
		'ConfirmActivateService' => 'Er du sikker på du vil aktivere denne tjeneste med datoen <b>for %s?</b>',
		'DateContract' => 'Kontrakt dato',
		'DateServiceActivate' => 'Forkyndelsesdato aktivering',
		'DateServiceUnactivate' => 'Forkyndelsesdato unactivation',
		'DateServiceStart' => 'Dato for starten af service',
		'DateServiceEnd' => 'Datoen for afslutningen af tjenesten',
		'ShowContract' => 'Vis kontrakt',
		'ListOfServices' => 'Liste over tjenesteydelser',
		'ListOfRunningContractsLines' => 'Liste over kører kontrakt linjer',
		'ListOfRunningServices' => 'Liste over kører tjenester',
		'NotActivatedServices' => 'Ikke aktiverede tjenester (blandt valideret kontrakter)',
		'BoardNotActivatedServices' => 'Tjenester for at aktivere blandt valideret kontrakter',
		'LastContracts' => 'Seneste% kontrakter',
		'LastActivatedServices' => 'Seneste %s aktiveret tjenester',
		'LastModifiedServices' => 'Seneste %s modificerede tjenester',
		'EditServiceLine' => 'Rediger service line',
		'ContractStartDate' => 'Startdato',
		'ContractEndDate' => 'Slutdato',
		'DateStartPlanned' => 'Planlagt startdato',
		'DateStartPlannedShort' => 'Planlagt startdato',
		'DateEndPlanned' => 'Planlagte slutdato',
		'DateEndPlannedShort' => 'Planlagte slutdato',
		'DateStartReal' => 'Real startdato',
		'DateStartRealShort' => 'Real startdato',
		'DateEndReal' => 'Real slutdato',
		'DateEndRealShort' => 'Real slutdato',
		'NbOfServices' => 'Nb af tjenesteydelser',
		'CloseService' => 'Luk service',
		'ServicesNomberShort' => '%s tjeneste (r)',
		'RunningServices' => 'Kørsel tjenester',
		'BoardRunningServices' => 'Udløbet kører tjenester',
		'ServiceStatus' => 'Status for service',
		'DraftContracts' => 'Drafts kontrakter',
		'CloseRefusedBecauseOneServiceActive' => 'Kontrakten ikke kan lukkes, da der er mindst en åben tjeneste på det',
		'CloseAllContracts' => 'Luk alle kontrakter',
		'MoveToAnotherContract' => 'Flyt tjeneste i en anden kontrakt.',
		'ConfirmMoveToAnotherContract' => 'Jeg choosed nyt mål kontrakt og bekræfte, jeg ønsker at flytte denne tjeneste i denne kontrakt.',
		'ConfirmMoveToAnotherContractQuestion' => 'Vælg, hvor eksisterende kontrakt (af samme tredjemand), du ønsker at flytte denne service?',
		'TypeContact_contrat_internal_SALESREPSIGN' => 'Salg repræsentant, der underskriver kontrakt',
		'TypeContact_contrat_internal_SALESREPFOLL' => 'Salg repræsentant opfølgning kontrakt',
		'TypeContact_contrat_external_BILLING' => 'Faktureringsindstillinger kunde kontakt',
		'TypeContact_contrat_external_CUSTOMER' => 'Opfølgning kunde kontakt',
		'TypeContact_contrat_external_SALESREPSIGN' => 'Undertegnelse kontrakt kunde kontakt',
		'ServiceStatusNotLate' => 'Kører, ikke er udløbet',
		'ServiceStatusNotLateShort' => 'Ikke er udløbet',
		'ServiceStatusLateShort' => 'Udløbet',
		'ListOfInactiveServices' => 'Liste over ikke aktive tjenester',
		'ListOfExpiredServices' => 'Liste over udløb aktive tjenester',
		'ListOfClosedServices' => 'Liste over lukkede tjenester',
		'DeleteContractLine' => 'Slet en kontrakt linje',
		'ConfirmDeleteContractLine' => 'Er du sikker på du vil slette denne kontrakt linje?',
		'PaymentRenewContractId' => 'Forny kontrakten linje (antal %s)',
		'ExpiredSince' => 'Udløbsdatoen',
		'RelatedContracts' => 'Relaterede kontrakter',
		'Error_CONTRACT_ADDON_NotDefined' => 'Konstant CONTRACT_ADDON ikke defineret',
		'NoExpiredServices' => 'Ingen udløbne aktive tjenester',
);
?>