<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$install = array(
		'CHARSET' => 'UTF-8',
		'InstallEasy' => 'Vi forsøgte at gøre Speedealing setup så let som muligt. Følg anvisningerne trin for trin.',
		'MiscellanousChecks' => 'Forudsætninger check',
		'SpeedealingWelcome' => 'Welcome to Speedealing',
		'ConfFileExists' => '<b>Konfigurationsfil %s</b> eksisterer.',
		'ConfFileDoesNotExists' => '<b>Konfigurationsfil %s</b> eksisterer ikke!',
		'ConfFileDoesNotExistsAndCouldNotBeCreated' => '<b>Konfigurationsfil %s</b> eksisterer ikke og kunne ikke oprettes!',
		'ConfFileCouldBeCreated' => '<b>Konfigurationsfil %s</b> kunne oprettes.',
		'ConfFileIsNotWritable' => '<b>Konfigurationsfil %s</b> er ikke skrivbar. Check permissions. For første installation, webserveren skal ydes for at kunne skrive i denne fil under konfigurationen ( "chmod 666" for eksempel på Unix-lignende OS).',
		'ConfFileIsWritable' => '<b>Konfigurationsfil %s</b> er skrivbar.',
		'ConfFileReload' => 'Genindlæs alle oplysninger fra konfigurationsfilen.',
		'PHPSupportSessions' => 'Denne PHP understøtter sessioner.',
		'PHPSupportPOSTGETOk' => 'Denne PHP understøtter variabler POST og GET.',
		'PHPSupportPOSTGETKo' => 'Det er muligt din PHP setup ikke understøtter variabler POST og / eller GET. Tjek din parameter <b>variables_order</b> i php.ini.',
		'PHPSupportGD' => 'Denne PHP støtte GD grafiske funktioner.',
		'PHPSupportUTF8' => 'Denne PHP støtte UTF8 funktioner.',
		'PHPMemoryOK' => 'Din PHP max session hukommelse er sat <b>til %s.</b> Dette skulle være nok.',
		'PHPMemoryTooLow' => 'Din PHP max session hukommelse er sat <b>til %s</b> bytes. Dette skulle være for lav. Skift din <b>php.ini</b> at indstille <b>memory_limit</b> parameter til <b>mindst %s</b> bytes.',
		'Recheck' => 'Klik her for en mere significative test',
		'ErrorPHPDoesNotSupportSessions' => 'Din PHP installation ikke støtte sessioner. Denne funktion er forpligtet til at gøre Speedealing fungerer. Tjek din PHP setup.',
		'ErrorPHPDoesNotSupportGD' => 'Din PHP installation ikke understøtter grafiske funktion GD. Nr. grafen vil være til rådighed.',
		'ErrorPHPDoesNotSupportUTF8' => 'Din PHP installation ikke støtte UTF8 funktioner. Speedealing kan ikke fungere korrekt. Løse dette, før du installerer Speedealing.',
		'ErrorDirDoesNotExists' => 'Directory %s ikke eksisterer.',
		'ErrorGoBackAndCorrectParameters' => 'Gå tilbage og rette forkerte parametre.',
		'ErrorWrongValueForParameter' => 'Du kan have indtastet en forkert værdi for parameter \' %s\'.',
		'ErrorFailedToCreateDatabase' => 'Kunne ikke oprette databasen \' %s\'.',
		'ErrorFailedToConnectToDatabase' => 'Det lykkedes ikke at oprette forbindelse til databasen \' %s\'.',
		'ErrorDatabaseVersionTooLow' => 'Database version (%s) too old. Version %s or higher is required.',
		'ErrorPHPVersionTooLow' => 'PHP version for gammel. Version %s er påkrævet.',
		'WarningPHPVersionTooLow' => 'PHP version for gammel. Version %s eller mere er forventet. Denne version skulle gøre det muligt installere, men er ikke understøttet.',
		'ErrorConnectedButDatabaseNotFound' => 'Forbindelsen til serveren vellykket men database \' %s\' blev ikke fundet.',
		'ErrorDatabaseAlreadyExists' => 'Database \' %s\' eksisterer allerede.',
		'IfDatabaseNotExistsGoBackAndUncheckCreate' => 'Hvis databasen ikke findes, gå tilbage og tjekke valgmulighed "Opret database".',
		'IfDatabaseExistsGoBackAndCheckCreate' => 'Hvis database findes allerede, gå tilbage og fjerne markeringen "Opret database" valgmulighed.',
		'WarningBrowserTooOld' => 'Too old version of browser. Upgrading your browser to a recent version of Firefox, Chrome or Opera is highly recommanded.',
		'PHPVersion' => 'PHP Version',
		'YouCanContinue' => 'Du kan fortsætte ...',
		'PleaseBePatient' => 'Vær tålmodig ...',
		'License' => 'Bruger licens',
		'ConfigurationFile' => 'Opsætningsfil',
		'WebPagesDirectory' => 'Mappe, hvor websider er gemt',
		'DocumentsDirectory' => 'Vejviser til at gemme uploadet og genererede dokumenter',
		'URLRoot' => 'URL Root',
		'ForceHttps' => 'Force sikre forbindelser (https)',
		'CheckToForceHttps' => 'Markér dette for at tvinge sikre forbindelser (https). <br> Dette kræver, at web-serveren er konfigureret med en SSL-certifikat.',
		'SpeedealingDatabase' => 'Speedealing Database',
		'DatabaseChoice' => 'Database valg',
		'DatabaseType' => 'Database type',
		'DriverType' => 'Driver type',
		'Server' => 'Server',
		'ServerAddressDescription' => 'Navn eller IP-adresse til database-serveren, som normalt \'localhost\', når database-serveren er hostet på samme server end webserver',
		'ServerPortDescription' => 'Database serverport. Opbevar tomme hvis ukendt.',
		'DatabaseServer' => 'Database server',
		'DatabaseName' => 'Database navn',
		'DatabasePrefix' => 'Database prefix table',
		'Login' => 'Login',
		'AdminLogin' => 'Log ind for Speedealing database administrator. Hold tomme, hvis du slutter i anonym',
		'Password' => 'Password',
		'PasswordAgain' => 'Gentag adgangskode en anden gang',
		'AdminPassword' => 'Adgangskode til Speedealing database administrator. Hold tomme, hvis du slutter i anonym',
		'CreateDatabase' => 'Opret database',
		'CreateUser' => 'Opret bruger',
		'DatabaseSuperUserAccess' => 'Database - SuperUser adgang',
		'CheckToCreateDatabase' => 'Afkrydsningsfelt, hvis databasen ikke eksisterer og skal være oprettet. <br> I dette tilfælde skal du udfylde login / password for SuperUser konto nederst på denne side.',
		'CheckToCreateUser' => 'Afkrydsningsfelt, hvis login ikke eksisterer og skal være oprettet. <br> I dette tilfælde skal du udfylde login / password for SuperUser konto nederst på denne side.',
		'Experimental' => '(eksperimentel, ikke operationelle)',
		'DatabaseRootLoginDescription' => 'Log ind på den bruger lov til at oprette nye databaser eller nye brugere, ubrugelige, hvis din database og din database login findes allerede (ligesom når du er vært ved en web hosting provider).',
		'KeepEmptyIfNoPassword' => 'Efterlad tom, hvis brugeren ikke har nogen adgangskode (undgå dette)',
		'SaveConfigurationFile' => 'Gem værdier',
		'ConfigurationSaving' => 'Lagring opsætningsfil',
		'ServerConnection' => 'Serverforbindelse',
		'DatabaseConnection' => 'Database forbindelse',
		'DatabaseCreation' => 'Database skabelse',
		'UserCreation' => 'Bruger oprettelse',
		'CreateDatabaseObjects' => 'Database-objekter skabelse',
		'ReferenceDataLoading' => 'Referencedata lastning',
		'TablesAndPrimaryKeysCreation' => 'Tabeller og primære nøgler skabelse',
		'CreateTableAndPrimaryKey' => 'Opret tabel %s',
		'CreateOtherKeysForTable' => 'Opret udenlandske nøgler og indekser for tabel %s',
		'OtherKeysCreation' => 'Udenlandske nøgler og indekserer skabelse',
		'FunctionsCreation' => 'Funktioner skabelse',
		'AdminAccountCreation' => 'Administrator login skabelse',
		'PleaseTypePassword' => 'Indtast en adgangskode, tomme adgangskoder er ikke tilladt!',
		'PleaseTypeALogin' => 'Indtast et login!',
		'PasswordsMismatch' => 'Passwords er forskellig, prøv igen!',
		'SetupEnd' => 'Slutningen af setup',
		'SystemIsInstalled' => 'Denne installationen er færdig.',
		'SystemIsUpgraded' => 'Speedealing er blevet opgraderet med succes.',
		'YouNeedToPersonalizeSetup' => 'Du er nødt til at konfigurere Speedealing at matche dine behov (udseende, funktioner, ...). For at gøre dette, skal du følge nedenstående link:',
		'AdminLoginCreatedSuccessfuly' => 'Speedealing administrator login <b>\' %s\'</b> skabt successfuly.',
		'GoToSpeedealing' => 'Go to Speedealing',
		'GoToSetupArea' => 'Gå til Speedealing (setup-området)',
		'MigrationNotFinished' => 'Version af din database er ikke helt up to date, så du bliver nødt til at køre opgraderingen igen.',
		'GoToUpgradePage' => 'Gå til opgradere siden igen',
		'Examples' => 'Eksempler',
		'WithNoSlashAtTheEnd' => 'Uden skråstreg "/" i slutningen',
		'DirectoryRecommendation' => 'Det er opfordres der til at bruge en mappe uden for din mappe på dine websider.',
		'LoginAlreadyExists' => 'Allerede findes',
		'SpeedealingAdminLogin' => 'Speedealing admin login',
		'AdminLoginAlreadyExists' => 'Speedealing administratorkonto <b>\' %s\'</b> eksisterer allerede.',
		'WarningRemoveInstallDir' => 'Advarsel, af sikkerhedshensyn, når de installerer eller opgraderer er færdig, bør du fjerne <b>installationen mappe eller omdøbe den til install.lock for at undgå sin ondsindet brug.</b>',
		'ThisPHPDoesNotSupportTypeBase' => 'Denne PHP system understøtter ikke nogen grænseflade for at få adgang til databasen type %s',
		'FunctionNotAvailableInThisPHP' => 'Ikke til rådighed på dette PHP',
		'MigrateScript' => 'Overflyt script',
		'ChoosedMigrateScript' => 'Valgt migrere script',
		'DataMigration' => 'Data migration',
		'DatabaseMigration' => 'Struktur database migration',
		'ProcessMigrateScript' => 'Script forarbejdning',
		'ChooseYourSetupMode' => 'Vælg din opsætning mode, og klik på "Start" ...',
		'FreshInstall' => 'Friske installere',
		'FreshInstallDesc' => 'Brug denne tilstand, hvis dette er din første installation. Hvis ikke, denne tilstand kan reparere en tidligere ufuldstændige installere, men hvis du ønsker at opgradere din version, kan du vælge "Opdater"-tilstand.',
		'Upgrade' => 'Upgrade',
		'UpgradeDesc' => 'Brug denne tilstand, hvis du har erstattet gamle Speedealing filer med filerne fra en nyere version. Dette vil opgradere din database og data.',
		'Start' => 'Start',
		'InstallNotAllowed' => 'Setup ikke tilladt ved <b>conf.php</b> tilladelser',
		'NotAvailable' => 'Ikke til rådighed',
		'YouMustCreateWithPermission' => 'Du skal oprette fil %s og sæt skrive tilladelser på det for web server under installere proces.',
		'CorrectProblemAndReloadPage' => 'Ret problemet og tryk F5 for at genindlæse siden.',
		'AlreadyDone' => 'Allerede migreret',
		'DatabaseVersion' => 'Database version',
		'ServerVersion' => 'Database server version',
		'YouMustCreateItAndAllowServerToWrite' => 'Du skal oprette denne mappe og giver mulighed for at web-serveren til at skrive i den.',
		'CharsetChoice' => 'Tegnsæt valg',
		'CharacterSetClient' => 'Tegnsæt anvendes til genererede HTML-websider',
		'CharacterSetClientComment' => 'Vælg tegnsættet for web displayet. <br/> Default foreslåede tegnsæt er den ene af din database.',
		'CollationConnection' => 'Tegn sortering orden',
		'CollationConnectionComment' => 'Vælg side kode, der definerer karakter\'s sortering rækkefølge anvendes af databasen. Denne parameter kaldes også »samling« af nogle databaser. <br/> Denne parameter kan ikke defineres, hvis database findes allerede.',
		'CharacterSetDatabase' => 'Tegnsæt for database',
		'CharacterSetDatabaseComment' => 'Vælg tegnsættet ønskede for database oprettelse. <br/> Denne parameter kan ikke defineres, hvis database findes allerede.',
		'YouAskDatabaseCreationSoSpeedealingNeedToConnect' => 'You ask to create database <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'YouAskLoginCreationSoSpeedealingNeedToConnect' => 'You ask to create database login <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'BecauseConnectionFailedParametersMayBeWrong' => 'Som forbindelse mislykkedes, vært eller superbruger parametre skal være forkerte.',
		'OrphelinsPaymentsDetectedByMethod' => 'Orphelins betaling opdaget ved metoden %s',
		'RemoveItManuallyAndPressF5ToContinue' => 'Fjern det manuelt, og tryk på F5 for at fortsætte.',
		'KeepDefaultValuesWamp' => 'Du bruger DoliWamp opsætningsguiden, så værdier foreslås her allerede er optimeret. Ændre dem kun, hvis du ved hvad du gør.',
		'KeepDefaultValuesDeb' => 'Du bruger Speedealing opsætningsguiden fra en Ubuntu eller Debian-pakke, så værdier, der foreslås her, er allerede optimeret. Kun den password i databasen ejeren for at oprette skal udfyldes. Ændre andre parametre kun hvis du ved hvad du gør.',
		'KeepDefaultValuesMamp' => 'Du bruger DoliMamp opsætningsguiden, så værdier foreslås her allerede er optimeret. Ændre dem kun, hvis du ved hvad du gør.',
		'KeepDefaultValuesProxmox' => 'Du bruger Speedealing opsætningsguiden fra en Proxmox virtual appliance, så værdier, der foreslås her, allerede er optimeret. Skift dem kun hvis du ved hvad du gør.',
		'FieldRenamed' => 'Felt omdøbt',
		'IfLoginDoesNotExistsCheckCreateUser' => 'Hvis login ikke findes endnu, skal du kontrollere option "Opret bruger"',
		'ErrorConnection' => 'Server <b>" %s",</b> databasenavn <b>" %s"</b> login <b>" %s",</b> eller database password kan være forkerte eller PHP klientversionen kan være for gammel i forhold til database version.',
		'InstallChoiceRecommanded' => 'Anbefalet valg til at installere version <b>%s</b> fra din nuværende version <b>%s</b>',
		'InstallChoiceSuggested' => '<b>Installer valg foreslået af installationsprogrammet.</b>',
		'MigrateIsDoneStepByStep' => 'De målrettede version (%s) har et efterslæb på flere versioner, så installere guiden vil komme tilbage, der tyder på næste migration, når denne ene vil være færdig.',
		'CheckThatDatabasenameIsCorrect' => 'Kontroller, at databasen navnet <b>"%s"</b> er korrekt.',
		'IfAlreadyExistsCheckOption' => 'Hvis dette navn er korrekte, og at databasen ikke findes endnu, skal du kontrollere indstillingen "Opret database".',
		'OpenBaseDir' => 'PHP openbasedir parameter',
		'YouAskToCreateDatabaseSoRootRequired' => 'Du har markeret afkrydsningsfeltet "Opret database". Til dette skal du give login / password på superbruger (i bunden af skemaet).',
		'YouAskToCreateDatabaseUserSoRootRequired' => 'Du har markeret afkrydsningsfeltet "Opret database ejer". Til dette skal du give login / password på superbruger (i bunden af skemaet).',
		'NextStepMightLastALongTime' => 'Nuværende trin kan vare flere minutter. Vent venligst indtil det næste skærmbillede vises helt, før du fortsætter.',
		'LastStepDesc' => '<strong>Sidste trin:</strong> Definer her login og adgangskode, du planlægger at bruge til at oprette forbindelse til software. Må ikke løse dette, da det er den konto, at administrere alle andre.',
		'ActivateModule' => 'Aktiver modul %s',
		'ShowEditTechnicalParameters' => 'Click here to show/edit advanced parameters (expert mode)',
		'ServerPortCouchdbDescription' => 'Port du serveur. Défaut 5984.',
		'ServerAddressCouchdbDescription' => 'Nom FQDN du serveur de base de données, \'localhost.localdomain\' quand le serveur est installé sur la même machine que le serveur web',
		'DatabaseCouchdbUserDescription' => 'Login du super administrateur ayant tous les droits sur le serveur CouchDB ou l\'administrateur propriétaire de la base si la base et son compte d\'accès existent déjà (comme lorsque vous êtes chez un hébergeur).<br><br><div class="alert-box info">Cet utilisateur/mot de passe sera l\'administrateur pour se connecter à Speedealing.</div>',
		'CheckToCreateCouchdbDatabase' => 'Cochez cette option si la base de données n\'existe pas et doit être créée.',
		'CreateAdminUser' => 'Créer le super administrateur (Première installation de couchDB)',
		'MemcachedDescription' => 'Activer Memcached necessite l\'installation d\'un serveur Memcached et des lib php-memcached ou php-memcache. Il peut être activer après l\'installation.',
		'ServerAddressMemcachedDesc' => 'Nom ou adresse ip du serveur memcached, généralement \'localhost\' quand le serveur est installé sur la même machine que le serveur web',
		'ServerPortMemcachedDesc' => 'Port du serveur memcached. Défaut : 11211',
		'EnabledMemcached' => 'Activer Memcached',
		'DatabaseNoSQL' => 'Base de données CouchDB',
		'FailedToCreateAdminLogin' => 'Echec de la création du compte administrateur Speedealing.',
		'LinkedElementsInvalidDeleted' => '<b>%s</b> liaisons invalides ont été supprimées',
		'NothingToDelete' => 'Aucune liaison invalide trouvée',
		'SourceType' => 'Source',
		'TargetType' => 'Cible'
);
?>