<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Warehouse kortet',
		'Warehouse' => 'Warehouse',
		'NewWarehouse' => 'Nyt oplag / Stock område',
		'MenuNewWarehouse' => 'Ny lagerhal',
		'WarehouseOpened' => 'Warehouse åbnet',
		'WarehouseClosed' => 'Warehouse lukket',
		'WarehouseSource' => 'Kilde lagerhal',
		'WarehouseTarget' => 'Målret lager',
		'ValidateSending' => 'Slet afsendelse',
		'CancelSending' => 'Annuller afsendelse',
		'DeleteSending' => 'Slet afsendelse',
		'Stock' => 'Stock',
		'Stocks' => 'Lagre',
		'Movement' => 'Bevægelighed',
		'Movements' => 'Bevægelser',
		'ErrorWarehouseRefRequired' => 'Warehouse reference navn er påkrævet',
		'ErrorWarehouseLabelRequired' => 'Warehouse fareseddel kræves',
		'CorrectStock' => 'Korrekt lager',
		'ListOfWarehouses' => 'Liste over pakhuse',
		'ListOfStockMovements' => 'Liste over lagerbevægelserne',
		'StocksArea' => 'Lagre område',
		'Location' => 'Lieu',
		'LocationSummary' => 'Kortnavn placering',
		'NumberOfProducts' => 'Samlet antal produkter',
		'LastMovement' => 'Seneste bevægelighed',
		'LastMovements' => 'Seneste bevægelser',
		'Units' => 'Enheder',
		'Unit' => 'Enhed',
		'StockCorrection' => 'Korrekt lager',
		'StockMovement' => 'Transfer',
		'StockMovements' => 'Stock overførsler',
		'NumberOfUnit' => 'Antal enheder',
		'TotalStock' => 'I alt på lager',
		'StockTooLow' => 'Stock for lavt',
		'EnhancedValue' => 'Værdi',
		'PMPValue' => 'Værdi',
		'EnhancedValueOfWarehouses' => 'Lager værdi',
		'UserWarehouseAutoCreate' => 'Opret en bestand automatisk, når du opretter en bruger',
		'QtyDispatched' => 'Afsendte mængde',
		'OrderDispatch' => 'Bestil lastfordelingen',
		'RuleForStockManagementDecrease' => 'Reglen for lagerstyring fald',
		'RuleForStockManagementIncrease' => 'Reglen for lagerstyring stigning',
		'DeStockOnBill' => 'Fraførsel reelle bestande på fakturaer / kreditnotaer',
		'DeStockOnValidateOrder' => 'Fraførsel reelle bestande om ordrer noter',
		'ReStockOnBill' => 'Forhøjelse reelle bestande på fakturaer / kreditnotaer',
		'ReStockOnValidateOrder' => 'Forhøjelse reelle bestande om ordrer noter',
		'StockLimitShort' => 'Limit',
		'StockLimit' => 'Stock grænse for indberetninger',
		'PhysicalStock' => 'Fysiske lager',
		'RealStock' => 'Real Stock',
		'TheoreticalStock' => 'Therocial lager',
		'VirtualStock' => 'Virtual lager',
		'MininumStock' => 'Minimumslager',
		'StockUp' => 'Stock op',
		'MininumStockShort' => 'Stock min',
		'StockUpShort' => 'Stock op',
		'IdWarehouse' => 'Id lager',
		'DescWareHouse' => 'Beskrivelse lager',
		'LieuWareHouse' => 'Lokalisering lager',
		'WarehousesAndProducts' => 'Lager og produkter',
		'PMPValueShort' => 'WAP',
		'AverageUnitPricePMPShort' => 'Gennemsnitlig input pris',
		'AverageUnitPricePMP' => 'Gennemsnitlig input pris',
		'EstimatedStockValueShort' => 'Anslåede værdi af materiel',
		'EstimatedStockValue' => 'Anslåede værdi af materiel',
		'WarehouseEdit' => 'Rediger lager',
		'DeStockOnShipment' => 'Formindsk reelle bestande om overførsel validering',
		'ReStockOnDispatchOrder' => 'Øge den reelle bestande på manuel ekspedition i pakhuse, efter at leverandøren ordremodtagelse',
		'OrderStatusNotReadyToDispatch' => 'Ordren er endnu ikke eller ikke mere en status, der tillader forsendelse af varer på lager lagre.',
		'StockDiffPhysicTeoric' => 'Årsag til forskel bestand fysisk og teoretisk',
		'NoPredefinedProductToDispatch' => 'Ingen foruddefinerede produkter for dette objekt. Så ingen ekspedition på lager er påkrævet.',
		'DispatchVerb' => 'Forsendelse',
		'DeleteAWarehouse' => 'Slet et lager',
		'ConfirmDeleteWarehouse' => 'Er du sikker på du vil slette lageret <b>%s?</b>',
		'PersonalStock' => 'Personligt lager %s',
		'ThisWarehouseIsPersonalStock' => 'Denne lagerhal er personlig status over %s %s',
		'SellPriceMin' => 'Salgsenhed Pris',
		'EstimatedStockValueSellShort' => 'Value at sælge',
		'EstimatedStockValueSell' => 'Værdi til Sælg',
		'SelectWarehouseForStockDecrease' => 'Vælg lageret skal bruges til lager fald',
		'SelectWarehouseForStockIncrease' => 'Vælg lageret skal bruges til lager stigning',
);
?>