<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$withdrawals = array(
		'CHARSET' => 'UTF-8',
		'StandingOrdersArea' => 'Stående ordrer område',
		'CustomersStandingOrdersArea' => 'Kunder stående ordrer område',
		'StandingOrders' => 'Stående ordrer',
		'StandingOrder' => 'Stående ordrer',
		'NewStandingOrder' => 'Nye stående ordre',
		'StandingOrderToProcess' => 'For at kunne behandle',
		'StandingOrderProcessed' => 'Forarbejdet',
		'Withdrawals' => 'Tilbagekøb',
		'Withdrawal' => 'Tilbagetrækning',
		'WithdrawalsReceipts' => 'Tilbagekøb kvitteringer',
		'WithdrawalReceipt' => 'Tilbagetrækning modtagelse',
		'WithdrawalReceiptShort' => 'Modtagelse',
		'LastWithdrawalReceipts' => 'Seneste %s tilbagetrækning kvitteringer',
		'WithdrawedBills' => 'Withdrawed fakturaer',
		'WithdrawalsLines' => 'Tilbagekøb linjer',
		'RequestStandingOrderToTreat' => 'Anmodning om stående ordrer til behandling',
		'RequestStandingOrderTreated' => 'Anmodning om stående ordrer behandles',
		'CustomersStandingOrders' => 'Kunden stående ordrer',
		'CustomerStandingOrder' => 'Kunden stående ordre',
		'NbOfInvoiceToWithdraw' => 'Nb af faktura med trække anmodning',
		'NbOfInvoiceToWithdrawWithInfo' => 'Nb af faktura med trække anmodningen om kunder, der har defineret bankkontooplysninger',
		'InvoiceWaitingWithdraw' => 'Faktura afvente trække',
		'AmountToWithdraw' => 'Beløb til at trække',
		'WithdrawsRefused' => 'Tilbagekalder nægtet',
		'NoInvoiceToWithdraw' => 'Nr. kundens faktura i betalingssystemer mode "trække" venter. Gå på \'Træk\' fane på faktura-kort til at fremsætte en anmodning.',
		'ResponsibleUser' => 'Ansvarlig bruger',
		'WithdrawalsSetup' => 'Tilbagetrækning setup',
		'WithdrawStatistics' => 'Tilbagekalder »statistik',
		'WithdrawRejectStatistics' => 'Trække afviser \'statistikker',
		'LastWithdrawalReceipt' => 'Seneste %s tilbagetrækning kvitteringer',
		'MakeWithdrawRequest' => 'Foretag en trække anmodning',
		'ThirdPartyBankCode' => 'Tredjepart bankkode',
		'ThirdPartyDeskCode' => 'Tredjepart desk-kode',
		'NoInvoiceCouldBeWithdrawed' => 'Nr. faktura withdrawed med succes. Kontroller, at fakturaen er for selskaber med en gyldig forbud.',
		'ClassCredited' => 'Klassificere krediteres',
		'ClassCreditedConfirm' => 'Er du sikker på at du vil klassificere denne tilbagetrækning modtagelse som krediteres på din bankkonto?',
		'TransData' => 'Dato Transmission',
		'TransMetod' => 'Metode Transmission',
		'Send' => 'Send',
		'Lines' => 'Lines',
		'StandingOrderReject' => 'Udstedelse en forkaste',
		'InvoiceRefused' => 'Oplad afslag til kunden',
		'WithdrawalRefused' => 'Udbetalinger Refuseds',
		'WithdrawalRefusedConfirm' => 'Er du sikker på du vil indtaste en tilbagetrækning afvisning for samfundet',
		'RefusedData' => 'Dato for afvisning',
		'RefusedReason' => 'Årsag til afvisning',
		'RefusedInvoicing' => 'Fakturering afvisningen',
		'NoInvoiceRefused' => 'Oplad ikke afvisning',
		'InvoiceRefused' => 'Oplad afslag til kunden',
		'Status' => 'Status',
		'StatusUnknown' => 'Ukendt',
		'StatusWaiting' => 'Venter',
		'StatusTrans' => 'Transmitteret',
		'StatusCredited' => 'Krediteres',
		'StatusRefused' => 'Afviste',
		'StatusMotif0' => 'Uspecificeret',
		'StatusMotif1' => 'Levering insuffisante',
		'StatusMotif2' => 'Tirage conteste',
		'StatusMotif3' => 'Ingen Tilbagetrækning for',
		'StatusMotif4' => 'Kunde Bestil',
		'StatusMotif5' => 'RIB inexploitable',
		'StatusMotif6' => 'Konto uden balance',
		'StatusMotif7' => 'Retslig afgørelse',
		'StatusMotif8' => 'Andre grunde',
		'CreateAll' => 'Tilbagekalde alle',
		'CreateGuichet' => 'Kun kontor',
		'CreateBanque' => 'Kun bank',
		'OrderWaiting' => 'Venter på behandling',
		'NotifyTransmision' => 'Tilbagetrækning Transmission',
		'NotifyEmision' => 'Tilbagetrækning Emission',
		'NotifyCredit' => 'Tilbagetrækning Credit',
		'NumeroNationalEmetter' => 'National Transmitter Antal',
		'PleaseSelectCustomerBankBANToWithdraw' => 'Vælg oplysninger om kundens bankkonto til at trække',
		'WithBankUsingRIB' => 'For bankkonti ved hjælp af RIB',
		'WithBankUsingBANBIC' => 'For bankkonti ved hjælp af IBAN / BIC / SWIFT',
		'BankToReceiveWithdraw' => 'Bankkonto til at modtage trækker sig',
		'CreditDate' => 'Kredit på',
		'WithdrawalFileNotCapable' => 'Kan ikke generere tilbagetrækning kvittering fil til dit land',
		'ShowWithdraw' => 'Vis Træk',
		'IfInvoiceNeedOnWithdrawPaymentWontBeClosed' => 'Hvis faktura mindst en tilbagetrækning betaling endnu ikke behandlet, vil den ikke blive angivet som betales for at tillade at styre tilbagetrækning før.',
		'DoStandingOrdersBeforePayments' => 'Denne faner giver dig mulighed for at anmode om en stående ordre. Når den bliver færdig, kan du skrive betalingen for at lukke fakturaen.',
		////// Notifications
		'InfoCreditSubject' => 'Betaling af stående ordre %s af banken',
		'InfoCreditMessage' => 'Den stående ordre %s er betalt af banken <br> Data for betaling: %s',
		'InfoTransSubject' => 'Transmission af stående ordre %s til bank',
		'InfoTransMessage' => 'Den stående ordre %s er transmited til bank ved %s %s. <br><br>',
		'InfoTransData' => 'Beløb: %s <br> Methodology: %s <br> Dato: %s',
		'InfoFoot' => 'Dette er en automatisk sendes af Speedealing',
		'InfoRejectSubject' => 'Stående For nægtede',
		'InfoRejectMessage' => 'Hej, <br><br> den standig rækkefølgen af ​​faktura %s relateret til selskabets %s, med et beløb på %s er blevet afvist af banken. <br><br> - <br> % $',
		'ModeWarning' => 'Mulighed for real mode ikke var indstillet, vi stopper efter denne simulation'
);
?>