<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$banks = array(
		'CHARSET' => 'UTF-8',
		'Bank' => 'Banco',
		'Banks' => 'Bancos',
		'MenuBankCash' => 'Banco/Efectivo',
		'MenuSetupBank' => 'Configuración de Banco/Efectivo',
		'BankName' => 'Nombre del banco',
		'FinancialAccount' => 'Cuenta',
		'FinancialAccounts' => 'Cuentas',
		'BankAccount' => 'Cuenta de banco',
		'BankAccounts' => 'Cuentas de banco',
		'AccountRef' => 'Ref. de cuenta financiera',
		'AccountLabel' => 'Etiqueta de la cuenta financiera',
		'CashAccount' => 'Cuenta de efectivo',
		'CashAccounts' => 'Cuentas de efectivo',
		'MainAccount' => 'Cuenta principal',
		'CurrentAccount' => 'Cuenta actual',
		'CurrentAccounts' => 'Cuentas actuales',
		'SavingAccount' => 'Cuenta de ahorro',
		'SavingAccounts' => 'Cuentas de ahorros',
		'ErrorBankLabelAlreadyExists' => 'La etiqueta para la cuenta financiera ya existe',
		'BankBalance' => 'Saldo',
		'BalanceMinimalAllowed' => 'Saldo mínimo permitido',
		'BalanceMinimalDesired' => 'Saldo mínimo deseado',
		'InitialBankBalance' => 'Saldo inicial',
		'EndBankBalance' => 'Saldo final',
		'CurrentBalance' => 'Saldo actual',
		'FutureBalance' => 'Saldo futuro',
		'ShowAllTimeBalance' => 'Mostrar saldo desde el inicio',
		'Reconciliation' => 'Reconciliación',
		'RIB' => 'Número de cuenta bancaria',
		'IBAN' => 'Número IBAN',
		'BIC' => 'Número BIC/SWIFT',
		'StandingOrders' => 'Órdenes permanentes',
		'StandingOrder' => 'Orden permanente',
		'Withdrawals' => 'Retiros',
		'Withdrawal' => 'Retiro',
		'AccountStatement' => 'Declaración de cuenta',
		'AccountStatementShort' => 'Declaración',
		'AccountStatements' => 'Declaraciones de cuenta',
		'LastAccountStatements' => 'Últimas declaraciones de cuenta',
		'Rapprochement' => 'Reconciliar',
		'IOMonthlyReporting' => 'Reporte mensual',
		'BankAccountDomiciliation' => 'Dirección de la cuenta',
		'BankAccountCountry' => 'País de la cuenta',
		'BankAccountOwner' => 'Dueño de la cuenta',
		'BankAccountOwnerAddress' => 'Dirección del dueño de la cuenta',
		'RIBControlError' => 'Fallo en la comprobación de integridad de los valores. Esto significa que la información para este número de cuenta no está completa o es errónea (verifique el país, números e IBAN).',
		'CreateAccount' => 'Crear cuenta',
		'NewAccount' => 'Nueva cuenta',
		'NewBankAccount' => 'Nueva cuenta bancaria',
		'NewFinancialAccount' => 'Nueva cuenta financiera',
		'MenuNewFinancialAccount' => 'Nueva cuenta financiera',
		'NewCurrentAccount' => 'Nueva cuenta actual',
		'NewSavingAccount' => 'Nueva cuenta de ahorros',
		'NewCashAccount' => 'Nueva cuenta de efectivo',
		'EditFinancialAccount' => 'Editar cuenta',
		'AccountSetup' => 'Configurar cuentas financieras',
		'SearchBankMovement' => 'Buscar movimiento bancario',
		'Debts' => 'Deudas',
		'LabelBankCashAccount' => 'Etiqueta para el banco o efectivo',
		'AccountType' => 'Tipo de cuenta',
		'BankType0' => 'Cuenta de ahorros',
		'BankType1' => 'Cuenta actual o tarjeta de crédito',
		'BankType2' => 'Cuenta de efectivo',
		'IfBankAccount' => 'Si cuenta bancaria',
		'AccountsArea' => 'Área de cuentas',
		'AccountCard' => 'Cuenta de tarjeta',
		'DeleteAccount' => 'Eliminar cuenta',
		'ConfirmDeleteAccount' => '¿Está seguro de querer eliminar esta cuenta?',
		'Account' => 'Cuenta',
		'ByCategories' => 'Por categorías',
		'ByRubriques' => 'Por categorías',
		'BankTransactionByCategories' => 'Transacciones bancarias por categorías',
		'BankTransactionForCategory' => 'Transacciones bancarias para la categorías <b>%s</b>',
		'RemoveFromRubrique' => 'Eliminar enlace con categoría',
		'RemoveFromRubriqueConfirm' => '¿Está seguro de querer eliminar el enlace entre la transacción y la categoría?',
		'ListBankTransactions' => 'Lista de transacciones bancarias',
		'IdTransaction' => 'ID de transacción',
		'BankTransactions' => 'Transacciones bancarias',
		'SearchTransaction' => 'Buscar transacción',
		'ListTransactions' => 'Listar transacciones',
		'ListTransactionsByCategory' => 'Listar transacciones por categoría',
		'TransactionsToConciliate' => 'Transacciones para conciliar',
		'Conciliable' => 'Puede ser conciliada',
		'Conciliate' => 'Conciliar',
		'Conciliation' => 'Conciliación',
		'ConciliationForAccount' => 'Conciliar esta cuenta',
		'IncludeClosedAccount' => 'Incluir cuentas cerradas',
		'OnlyOpenedAccount' => 'Sólo cuentas abiertas',
		'AccountToCredit' => 'Cuenta a creditar',
		'AccountToDebit' => 'Cuenta a debitar',
		'DisableConciliation' => 'Deshabilitar la característica de conciliación para esta cuenta',
		'ConciliationDisabled' => 'Característica de conciliación deshabilitada',
		'StatusAccountOpened' => 'Abierta',
		'StatusAccountClosed' => 'Cerrada',
		'AccountIdShort' => 'Número',
		'EditBankRecord' => 'Editar registro',
		'LineRecord' => 'Transacción',
		'AddBankRecord' => 'Agregar transacción',
		'AddBankRecordLong' => 'Agregar transacción manualmente',
		'ConciliatedBy' => 'Conciliada por',
		'DateConciliating' => 'Fecha de conciliación',
		'BankLineConciliated' => 'Transacción conciliada',
		'CustomerInvoicePayment' => 'Pago del cliente',
		'SupplierInvoicePayment' => 'Pago del proveedor',
		'WithdrawalPayment' => 'Retiro de pago',
		'SocialContributionPayment' => 'Pago de contribución social',
		'FinancialAccountJournal' => 'Diario de cuenta financiera',
		'BankTransfer' => 'Transferencia bancaria',
		'BankTransfers' => 'Transferencias bancarias',
		'TransferDesc' => 'Al transferir desde una cuenta a otra, Speedealing escribirá dos registros (una deuda en la cuenta de origen y un saldo en la cuenta destino, de la misma cantidad. Las mismas etiqueta y fecha serán utilizadas para esta transacción)',
		'TransferFrom' => 'De',
		'TransferTo' => 'Para',
		'TransferFromToDone' => 'Una transferencia desde <b>%s</b> para <b>%s</b> de <b>%s</b> %s ha sido registrada',
		'CheckTransmitter' => 'Emisor',
		'ValidateCheckReceipt' => '¿Validar este recibo de cheque?',
		'ConfirmValidateCheckReceipt' => '¿Está seguro de querer validar este recibo de cheque? No se podrán realizar cambios una vez hecho.',
		'DeleteCheckReceipt' => '¿Eliminar este recibo de cheque?',
		'ConfirmDeleteCheckReceipt' => '¿Está seguro de querer eliminar este recibo de cheque?',
		'BankChecks' => 'Cheques bancarios',
		'BankChecksToReceipt' => 'Cheques esperando a ser depositados',
		'ShowCheckReceipt' => 'Mostrar recibo de cheque depositado',
		'NumberOfCheques' => 'Nro de cheque',
		'DeleteTransaction' => 'Eliminar transacción',
		'ConfirmDeleteTransaction' => '¿Está seguro de querer eliminar esta transacción?',
		'ThisWillAlsoDeleteBankRecord' => 'Esto también eliminará las transacciones bancarias generadas',
		'BankMovements' => 'Movimientos',
		'CashBudget' => 'Presupuesto',
		'PlannedTransactions' => 'Transacciones planeadas',
		'Graph' => 'Gráficos',
		'ExportDataset_banque_1' => 'Transacciones bancarias y estados de cuentas',
		'TransactionOnTheOtherAccount' => 'Transacciones en la otra cuenta',
		'TransactionWithOtherAccount' => 'Transferir a otra cuenta',
		'PaymentNumberUpdateSucceeded' => 'Número de pago actualizado correctamente',
		'PaymentNumberUpdateFailed' => 'El número de pago no se pudo actualizar',
		'PaymentDateUpdateSucceeded' => 'Fecha de pago actualizada correctamente',
		'PaymentDateUpdateFailed' => 'La fecha de pago no pudo ser actualizada',
		'Transactions' => 'Transacciones',
		'BankTransactionLine' => 'Transacción bancaria',
		'AllAccounts' => 'Todas las cuentas bancarias/efectivo',
		'BackToAccount' => 'De banco a cuenta',
		'ShowAllAccounts' => 'Mostrar para todas las cuentas',
		'FutureTransaction' => 'Transacción futura. No se puede conciliar.',
		'SelectChequeTransactionAndGenerate' => 'Seleccionar/Filtrar cheques para incluirlos en los recibos de cheques depositados y presione "Crear".',
		'InputReceiptNumber' => 'Escoja el extracto de cuenta relacionado con la conciliación. Utilice un valor numérico ordenable (como YYYYMM)',
		'EventualyAddCategory' => 'Eventualmente, especifique una categoria para clasificar los registros',
		'ToConciliate' => '¿Para conciliar?',
		'ThenCheckLinesAndConciliate' => 'Luego, seleccione las líneas presentes en los extractos de cuentas y presione'
);
?>