<?php
/* Copyright (C) 2012	Regis Houssin	<regis@dolibarr.fr>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$categories = array(
		'CHARSET' => 'UTF-8',
		'Category' => 'Catégorie',
		'Categories' => 'Catégories',
		'Rubrique' => 'Rubrique',
		'Rubriques' => 'Rubriques',
		'categories' => 'catégorie(s)',
		'TheCategorie' => 'La catégorie',
		'NoCategoryYet' => 'Aucune catégorie de ce type créée',
		'In' => 'Dans',
		'AddIn' => 'Ajouter dans',
		'modify' => 'modifier',
		'Classify' => 'Classer',
		'CategoriesArea' => 'Espace catégories',
		'ProductsCategoriesArea' => 'Espace des catégories de produits et services',
		'SuppliersCategoriesArea' => 'Espace des catégories de tiers fournisseurs',
		'CustomersCategoriesArea' => 'Espace des catégories de tiers clients ou prospects',
		'ThirdPartyCategoriesArea' => 'Espace des catégories de tiers',
		'MembersCategoriesArea' => 'Espace des catégories d\'adhérents',
		'MainCats' => 'Catégories principales',
		'SubCats' => 'Sous-catégories',
		'CatStatistics' => 'Statistiques',
		'CatList' => 'Liste des catégories',
		'AllCats' => 'Toutes les catégories',
		'ViewCat' => 'Visualisation de la catégorie',
		'NewCat' => 'Nouvelle catégorie',
		'NewCategory' => 'Nouvelle catégorie',
		'ModifCat' => 'Modifier une catégorie',
		'CatCreated' => 'Catégorie créée',
		'CreateCat' => 'Ajouter une catégorie',
		'CreateThisCat' => 'Ajouter cette catégorie',
		'ValidateFields' => 'Valider les champs',
		'NoSubCat' => 'Cette catégorie ne contient aucune sous-catégorie.',
		'SubCatOf' => 'Sous-catégorie',
		'FoundCats' => 'Catégories trouvées',
		'FoundCatsForName' => 'Catégories trouvées pour le nom :',
		'FoundSubCatsIn' => 'Sous-catégories trouvées dans la catégorie',
		'ErrSameCatSelected' => 'Vous avez sélectionné la même catégorie plusieurs fois',
		'ErrForgotCat' => 'Vous avez oublié de choisir la catégorie',
		'ErrForgotField' => 'Vous avez oublié de renseigner un champ',
		'ErrCatAlreadyExists' => 'Ce nom est déjà utilisé',
		'AddProductToCat' => 'Ajouter ce produit à une catégorie ?',
		'ImpossibleAddCat' => 'Impossible d\'ajouter la catégorie',
		'ImpossibleAssociateCategory' => 'Impossible d\'associer la catégorie',
		'WasAddedSuccessfully' => '<b>%s</b> a été ajouté avec succès.',
		'ObjectAlreadyLinkedToCategory' => 'L\'élément est déjà lié à cette catégorie.',
		'CategorySuccessfullyCreated' => 'La catégorie %s a été ajouté avec succès.',
		'ProductIsInCategories' => 'Ce produit/service est dans les catégories suivantes',
		'SupplierIsInCategories' => 'Ce fournisseur est dans les catégories suivantes',
		'CompanyIsInCustomersCategories' => 'Cette société est dans les catégories clients/prospects suivantes',
		'CompanyIsInSuppliersCategories' => 'Cette société est dans les catégories fournisseurs suivantes',
		'MemberIsInCategories' => 'Cet adhérent est dans les catégories adhérent suivantes',
		'ContactIsInCategories' => 'Ce contact est dans les catégories suivantes',
		'ProductHasNoCategory' => 'Ce produit/service n\'est dans aucune catégorie en particulier',
		'SupplierHasNoCategory' => 'Ce fournisseur n\'est dans aucune catégorie en particulier',
		'CompanyHasNoCategory' => 'Cette société n\'est dans aucune catégorie en particulier',
		'MemberHasNoCategory' => 'Cet adhérent n\'est dans aucune catégorie en particulier',
		'ContactHasNoCategory' => 'Ce contact n\'est dans aucune catégorie en particulier',
		'ClassifyInCategory' => 'Classer dans la catégorie',
		'NoneCategory' => 'Aucune',
		'NotCategorized' => 'Sans catégorie',
		'CategoryExistsAtSameLevel' => 'Cette catégorie existe déjà pour cette référence',
		'ReturnInProduct' => 'Retour sur la fiche produit/service',
		'ReturnInSupplier' => 'Retour sur la fiche fournisseur',
		'ReturnInCompany' => 'Retour sur la fiche client/prospect',
		'ContentsVisibleByAll' => 'Le contenu sera visible par tous',
		'ContentsVisibleByAllShort' => 'Contenu visible par tous',
		'ContentsNotVisibleByAllShort' => 'Contenu non visible par tous',
		'CategoriesTree' => 'Arbre des catégories',
		'DeleteCategory' => 'Supprimer catégorie',
		'ConfirmDeleteCategory' => 'Êtes-vous sûr de vouloir supprimer cette catégorie ?',
		'RemoveFromCategory' => 'Supprimer lien avec catégorie',
		'RemoveFromCategoryConfirm' => 'Êtes-vous sûr de vouloir supprimer le lien entre la transaction et la catégorie ?',
		'NoCategoriesDefined' => 'Aucune catégorie définie',
		'SuppliersCategoryShort' => 'Catégorie fournisseurs',
		'CustomersCategoryShort' => 'Catégorie clients',
		'ProductsCategoryShort' => 'Catégorie produits',
		'MembersCategoryShort' => 'Catégorie adhérent',
		'ContactsCategoryShort' => 'Catégorie contact',
		'SuppliersCategoriesShort' => 'Catégories fournisseurs',
		'CustomersCategoriesShort' => 'Catégories clients',
		'CustomersProspectsCategoriesShort' => 'Catégories clients/prospects',
		'ProductsCategoriesShort' => 'Catégories produits',
		'MembersCategoriesShort' => 'Catégories adhérents',
		'ContactsCategoriesShort' => 'Catégories contacts',
		'ThisCategoryHasNoProduct' => 'Cette catégorie ne contient aucun produit.',
		'ThisCategoryHasNoSupplier' => 'Cette catégorie ne contient aucun fournisseur.',
		'ThisCategoryHasNoCustomer' => 'Cette catégorie ne contient aucun client.',
		'ThisCategoryHasNoMember' => 'Cette catégorie ne contient aucun adhérent.',
		'ThisCategoryHasNoContact' => 'Cette catégorie ne contient aucun contact.',
		'AssignedToCustomer' => 'Attribuer à un client',
		'AssignedToTheCustomer' => 'Attribué au client',
		'InternalCategory' => 'Catégorie interne',
		'CategoryContents' => 'Contenu de la catégorie',
		'CategId' => 'Id catégorie',
		'CatSupList' => 'Liste des catégories fournisseurs',
		'CatCusList' => 'Liste des catégories clients/prospects (infos comptes incluses)',
		'CatConList' => 'Liste des catégories contacts (infos contacts incluses)',
		'CatProdList' => 'Liste des catégories produits',
		'CatMemberList' => 'Liste des catégories adhérents',
);
?>