<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$install = array(
		'CHARSET' => 'UTF-8',
		'InstallEasy' => 'Veuillez suivre les étapes une à une.',
		'MiscellanousChecks' => 'Vérification de prérequis',
		'SpeedealingWelcome' => 'Bienvenue dans Speedealing',
		'ConfFileExists' => 'Le fichier de configuration <b>%s</b> existe.',
		'ConfFileDoesNotExists' => 'Le fichier de configuration <b>%s</b> n\'existe pas !',
		'ConfFileDoesNotExistsAndCouldNotBeCreated' => 'Le fichier de configuration <b>%s</b> n\'existe pas et n\'a pu être créé !',
		'ConfFileCouldBeCreated' => 'Le fichier de configuration <b>%s</b> a pu être créé.',
		'ConfFileIsNotWritable' => 'Le fichier <b>%s</b> n\'est pas modifiable. Pour une première installation, modifiez ses permissions. Le serveur Web doit avoir le droit d\'écrire dans ce fichier le temps de la configuration ("chmod 666" par exemple sur un OS compatible Unix).',
		'ConfFileIsWritable' => 'Le fichier <b>%s</b> est modifiable.',
		'ConfFileReload' => 'Rechargement des informations depuis le fichier de configuration.',
		'PHPSupportSessions' => 'Ce PHP supporte les sessions.',
		'PHPSupportPOSTGETOk' => 'Ce PHP supporte bien les variables POST et GET.',
		'PHPSupportPOSTGETKo' => 'Il est possible que ce PHP ne supporte pas les variables POST et/ou GET. Vérifier le paramètre <b>variables_order</b> du php.ini.',
		'PHPSupportGD' => 'Ce PHP supporte les fonctions graphiques GD.',
		'PHPSupportUTF8' => 'Ce PHP supporte les fonctions UTF8.',
		'PHPMemoryOK' => 'Votre mémoire maximum de session PHP est définie à <b>%s</b>. Ceci devrait être suffisant.',
		'PHPMemoryTooLow' => 'Votre mémoire maximum de session PHP est définie à <b>%s</b> octets. Ceci est trop faible. Il est recommandé de modifier le paramètre <b>memory_limit</b> de votre fichier <b>php.ini</b> à au moins <b>%s</b> octets.',
		'Recheck' => 'Cliquez ici pour un test plus probant',
		'ErrorPHPDoesNotSupportSessions' => 'Votre installation PHP ne supporte pas les sessions. Cette fonctionnalité est requise pour faire fonctionner Speedealing. Vérifiez votre configuration de PHP.',
		'ErrorPHPDoesNotSupportGD' => 'Ce PHP ne supporte pas les fonctions graphiques GD. Aucun graphique ne sera disponible.',
		'ErrorPHPDoesNotSupportUTF8' => 'Ce PHP ne supporte pas les fonctions UTF8. Résolvez le problème avant d\'installer Speedealing car il ne pourra pas fonctionner correctement.',
		'ErrorDirDoesNotExists' => 'Le répertoire <b>%s</b> n\'existe pas ou n\'est pas accessible.',
		'ErrorGoBackAndCorrectParameters' => 'Revenez en arrière et corrigez les paramètres invalides.',
		'ErrorWrongValueForParameter' => 'Vous avez peut-être saisi une mauvaise valeur pour le paramètre \'%s\'.',
		'ErrorFailedToCreateDatabase' => 'Echec de création de la base \'%s\'.',
		'ErrorFailedToConnectToDatabase' => 'Echec de connexion à la base \'%s\'.',
		'ErrorDatabaseVersionTooLow' => 'Version de base de donnée (%s) trop ancienne. La version %s ou supérieure est requise.',
		'ErrorPHPVersionTooLow' => 'Version de PHP trop ancienne. La version %s est requise.',
		'WarningPHPVersionTooLow' => 'Version de PHP trop ancienne. La version %s ou plus est recommandée. Cette version reste utilisable mais n\'est pas supportée.',
		'ErrorConnectedButDatabaseNotFound' => 'Connexion au serveur réussi mais base \'%s\' introuvable.',
		'ErrorDatabaseAlreadyExists' => 'La base de données \'%s\' existe déjà.',
		'IfDatabaseNotExistsGoBackAndUncheckCreate' => 'Si la base n\'existe pas, revenez en arrière et cochez l\'option "Créer la base de données".',
		'IfDatabaseExistsGoBackAndCheckCreate' => 'Si la base existe déjà, revenez en arrière et désactiver l\'option "Créer la base de données".',
		'WarningBrowserTooOld' => 'Version de navigateur trop ancienne. Nous vous recommandons de mettre à jour vers un version récente de Firefox, Chrome ou Opera.',
		'PHPVersion' => 'Version PHP',
		'YouCanContinue' => 'Vous pouvez continuer...',
		'PleaseBePatient' => 'Merci de patienter...',
		'License' => 'Licence d\'utilisation',
		'ConfigurationFile' => 'Fichier de configuration',
		'WebPagesDirectory' => 'Répertoire pages web',
		'DocumentsDirectory' => 'Répertoire documents',
		'URLRoot' => 'URL Racine',
		'ForceHttps' => 'Forcer les connexions sécurisées (https)',
		'CheckToForceHttps' => 'Cochez cette option pour forcer les connexions sécurisées (https).<br>Ceci nécessite que le serveur web soit configuré avec un certificat SSL.',
		'SpeedealingDatabase' => 'Speedealing Database',
		'DatabaseChoice' => 'Choix de la base de données',
		'DatabaseType' => 'Type de la base de données',
		'DriverType' => 'Type du driver',
		'Server' => 'Serveur',
		'ServerAddressDescription' => 'Nom ou adresse ip du serveur de base de données, généralement \'localhost\' quand le serveur est installé sur la même machine que le serveur web',
		'ServerPortDescription' => 'Port du serveur. Ne rien mettre si inconnu.',
		'DatabaseServer' => 'Serveur de la base de données',
		'DatabaseName' => 'Nom de la base',
		'DatabasePrefix' => 'Préfixe des tables',
		'Login' => 'Login',
		'AdminLogin' => 'Login du propriétaire de la base de données Speedealing.',
		'Password' => 'Mot de passe',
		'PasswordAgain' => 'Vérification du mot de passe',
		'AdminPassword' => 'Mot de passe du propriétaire de la base de données Speedealing.',
		'CreateDatabase' => 'Créer la base de données',
		'CreateUser' => 'Créer le propriétaire',
		'DatabaseSuperUserAccess' => 'Serveur de base de données - Accès super utilisateur',
		'CheckToCreateDatabase' => 'Cochez cette option si la base de données n\'existe pas et doit être créée.<br>Dans ce cas, il faut renseigner le login/mot de passe du super-utilisateur au bas de cette page.',
		'CheckToCreateUser' => 'Cochez cette option si l\'utilisateur propriétaire n\'existe pas et doit être créé.<br>Dans ce cas, il faut renseigner le nom et mot de passe du propriétaire à créer ainsi que le login/mot de passe du superutilisateur au bas de cette page. Si la case n\'est pas cochée, le nom et mot de passe du propriétaire doivent exister.',
		'Experimental' => '(expérimental)',
		'DatabaseRootLoginDescription' => 'Login de l\'utilisateur de la base ayant les droits de création de bases de données ou de comptes pour la base, inutile si la base et son compte d\'accès existent déjà (comme lorsque vous êtes chez un hébergeur).',
		'KeepEmptyIfNoPassword' => 'Laissez vide si l\'administrateur n\'a pas de mot de passe',
		'SaveConfigurationFile' => 'Enregistrement du fichier de configuration',
		'ConfigurationSaving' => 'Enregistrement du fichier de configuration',
		'ServerConnection' => 'Connexion au serveur',
		'DatabaseConnection' => 'Connexion à la base',
		'DatabaseCreation' => 'Création de la base',
		'UserCreation' => 'Création de l\'utilisateur',
		'CreateDatabaseObjects' => 'Création des objets de la base',
		'ReferenceDataLoading' => 'Chargement des données de référence',
		'TablesAndPrimaryKeysCreation' => 'Création des tables et des clés primaires',
		'CreateTableAndPrimaryKey' => 'Création de la table %s et de sa clé primaire',
		'CreateOtherKeysForTable' => 'Création des clés étrangères et des index pour la table %s',
		'OtherKeysCreation' => 'Création des clés étrangères et des index',
		'FunctionsCreation' => 'Création des fonctions',
		'AdminAccountCreation' => 'Création du compte administrateur',
		'PleaseTypePassword' => 'Veuillez saisir un mot de passe, les mots de passe vides ne sont pas acceptés !',
		'PleaseTypeALogin' => 'Veuillez saisir un login !',
		'PasswordsMismatch' => 'Les mots de passe ne correspondent pas, veuillez réessayer !',
		'SetupEnd' => 'Fin de l\'installation',
		'SystemIsInstalled' => 'Votre système est maintenant installé.',
		'SystemIsUpgraded' => 'Speedealing a été mis à jour avec succès.',
		'YouNeedToPersonalizeSetup' => 'Vous devez maintenant configurer Speedealing selon vos besoins (Choix de l\'apparence, des fonctionnalités, etc.). Pour cela, cliquez sur le lien ci-dessous:',
		'AdminLoginCreatedSuccessfuly' => 'Création du compte administrateur Speedealing \'<b>%s</b>\' réussie.',
		'GoToSpeedealing' => 'Go to Speedealing',
		'GoToSetupArea' => 'Accéder à Speedealing (espace configuration)',
		'MigrationNotFinished' => 'La version de votre base n\'est pas encore complètement à niveau, aussi il vous faudra relancer à nouveau une migration.',
		'GoToUpgradePage' => 'Accéder à la page de migration à nouveau',
		'Examples' => 'Exemples',
		'WithNoSlashAtTheEnd' => 'Sans le slash "/" à la fin',
		'DirectoryRecommendation' => 'Il est recommandé de mettre ce répertoire en dehors du répertoire des pages web.',
		'LoginAlreadyExists' => 'Existe déjà',
		'SpeedealingAdminLogin' => 'Speedealing admin login',
		'AdminLoginAlreadyExists' => 'Compte administrateur Speedealing \'<b>%s</b>\' déjà existant. Revenez en arrière si vous voulez en créer un autre.',
		'WarningRemoveInstallDir' => 'Attention, pour des raisons de sécurité, afin de bloquer une nouvelle utilisation des outils d\'installation/migration, une fois l\'installation terminée, il est conseillé de placer dans le répertoire document de Speedealing un fichier nommé <b>install.lock</b> en lecture seule.',
		'ThisPHPDoesNotSupportTypeBase' => 'Le système PHP ne supporte pas les interfaces d\'accès pour les bases %s',
		'FunctionNotAvailableInThisPHP' => 'Non disponible sur ce PHP',
		'MigrateScript' => 'Script de migration',
		'ChoosedMigrateScript' => 'Choix du script de migration',
		'DataMigration' => 'Migration des données',
		'DatabaseMigration' => 'Migration du format de la base de données',
		'ProcessMigrateScript' => 'Exécution du script',
		'ChooseYourSetupMode' => 'Choisissez votre mode d\'installation et cliquez sur "Démarrer"...',
		'FreshInstall' => 'Première installation',
		'FreshInstallDesc' => 'Utilisez ce mode si c\'est votre première installation. Si ce n\'est pas le cas, ce mode peut réparer une installation précédente incomplète, mais si vous voulez juste mettre à jour, choisissez le mode "Mise à jour".',
		'Upgrade' => 'Mise à jour',
		'UpgradeDesc' => 'Utilisez ce mode après avoir écrasé les fichiers d\'une ancienne installation Speedealing par ceux d\'une version plus récente. Ce choix permet de mettre à jour votre base et vos données pour cette nouvelle version.',
		'Start' => 'Démarrer',
		'InstallNotAllowed' => 'Installation non autorisée par les permissions du fichier <b>conf.php</b>',
		'NotAvailable' => 'Non disponible',
		'YouMustCreateWithPermission' => 'Vous devez créer un fichier %s et donner les droits d\'écriture dans celui-ci au serveur web durant le processus d\'installation.',
		'CorrectProblemAndReloadPage' => 'Corrigez le problème et pressez F5 pour recharger la page.',
		'AlreadyDone' => 'Déjà migré',
		'DatabaseVersion' => 'Version de la base',
		'ServerVersion' => 'Version du serveur de base de données',
		'YouMustCreateItAndAllowServerToWrite' => 'Vous devez créer ce dossier et permettre au serveur web d\'écrire dans celui-ci.',
		'CharsetChoice' => 'Choix du codage des caractères',
		'CharacterSetClient' => 'Codage utilisé pour l\'affichage des pages',
		'CharacterSetClientComment' => 'Veuillez choisir le codage que vous souhaitez pour l\'affichage des pages.<br/> Le codage proposé par défaut est celui de votre base de données par défaut.',
		'CollationConnection' => 'Ordre de tri utilisé pour la base de données',
		'CollationConnectionComment' => 'Veuillez choisir la page de code définissant l\'ordre de tri des caractères utilisés par la base de données. Ce paramètre est aussi appelé \'collation\' par certaines bases de données.<br/> Ce paramètre n\'est pas sélectionnable si votre base est déjà créée.',
		'CharacterSetDatabase' => 'Codage utilisé pour la base de données',
		'CharacterSetDatabaseComment' => 'Veuillez choisir le codage que vous désirez choisir pour la création de la base de données.<br/> Ce paramètre n\'est pas sélectionnable si votre base est déjà créée.',
		'YouAskDatabaseCreationSoSpeedealingNeedToConnect' => 'You ask to create database <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'YouAskLoginCreationSoSpeedealingNeedToConnect' => 'You ask to create database login <b>%s</b>, but for this, Speedealing need to connect to server <b>%s</b> with super user <b>%s</b> permissions.',
		'BecauseConnectionFailedParametersMayBeWrong' => 'La connexion ayant échoué, les paramètres du serveur ou du super utilisateur sont peut-être incorrects.',
		'OrphelinsPaymentsDetectedByMethod' => 'Paiement orphelins détectés par la méthode %s',
		'RemoveItManuallyAndPressF5ToContinue' => 'Supprimez le manuellement et appuyez sur F5 pour continuer.',
		'KeepDefaultValuesWamp' => 'Comme vous utilisez l\'assistant d\'installation Speedealing depuis DoliWamp, les valeurs proposées aux paramètres sont déjà optimisées. Ne les modifier qu\'en connaissance de cause.',
		'KeepDefaultValuesDeb' => 'Comme vous utilisez l\'assistant d\'installation Speedealing depuis un package Linux ou BSD (Ubuntu, Debian, Fedora, ...), les valeurs proposées aux paramètres sont déjà optimisées. Seul le mot de passe du propriétaire de la base de données à créer est à renseigner. Ne modifiez les autres informations qu\'en connaissance de cause.',
		'KeepDefaultValuesMamp' => 'Comme vous utilisez l\'assistant d\'installation Speedealing depuis DoliMamp, les valeurs proposées aux paramètres sont déjà optimisées. Ne les modifiez qu\'en connaissance de cause.',
		'KeepDefaultValuesProxmox' => 'Comme vous utilisez l\'assistant d\'installation Speedealing depuis une machine virtuelle Proxmox, les valeurs proposées aux paramètres sont déjà optimisées. Ne les modifiez qu\'en connaissance de cause.',
		'FieldRenamed' => 'Champ renommé',
		'IfLoginDoesNotExistsCheckCreateUser' => 'Si le login n\'existe pas encore, vous devez cocher l\'option "Créer l\'utilisateur"',
		'ErrorConnection' => 'Le serveur "<b>%s</b>", nom de base "<b>%s</b>", login "<b>%s</b>", ou mot de passe de la base de données est peut-être incorrect ou la version du client PHP trop ancienne par rapport à la version de la base de données.',
		'InstallChoiceRecommanded' => 'Choix recommandé pour installer la version <b>%s</b> depuis votre version actuelle <b>%s</b>',
		'InstallChoiceSuggested' => '<b>Choix suggéré par l\'installeur</b>.',
		'MigrateIsDoneStepByStep' => 'La version cible (%s) ayant un écart de plusieurs versions, l\'installeur reviendra proposer la migration suivante une fois celle-ci exécutée.',
		'CheckThatDatabasenameIsCorrect' => 'Vérifiez que le nom de base "<b>%s</b>" est correct.',
		'IfAlreadyExistsCheckOption' => 'Si ce nom est correct et que cette base n\'existe pas déjà, vous devez cocher l\'option "Créer la base de données".',
		'OpenBaseDir' => 'Paramètre php openbasedir',
		'YouAskToCreateDatabaseSoRootRequired' => 'Vous avez coché la case "Créer la base de données". Pour cela, le login/mot de passe du super utilisateur (en bas de formulaire) sont obligatoire.',
		'YouAskToCreateDatabaseUserSoRootRequired' => 'Vous avez coché la case "Créer l\'utilisateur propriétaire" de la base. Pour cela, le login/mot de passe du super utilisateur (en bas de formulaire) sont obligatoire.',
		'NextStepMightLastALongTime' => 'L\'étape en cours peut durer quelques minutes. Merci d\'attendre l\'affichage complet de la page suivante pour poursuivre.',
		'LastStepDesc' => '<strong>Dernière étape</strong>: Définissez ici le compte et mot de passe du premier utilisateur que vous allez utiliser pour vous connecter à l\'application. Ne perdez pas ces identifiants, il s\'agit du compte permettant d\'administrer les autres.',
		'ActivateModule' => 'Activation du module %s',
		'ShowEditTechnicalParameters' => 'Cliquer ici pour afficher/éditer les paramètres techniques (mode expert)',
		'ServerPortCouchdbDescription' => 'Port du serveur. Défaut 5984.',
		'ServerAddressCouchdbDescription' => 'Nom FQDN du serveur de base de données, \'localhost.localdomain\' quand le serveur est installé sur la même machine que le serveur web',
		'DatabaseCouchdbUserDescription' => 'Login du super administrateur ayant tous les droits sur le serveur CouchDB ou l\'administrateur propriétaire de la base si la base et son compte d\'accès existent déjà (comme lorsque vous êtes chez un hébergeur).<br><br><div class="alert-box info">Cet utilisateur/mot de passe sera l\'administrateur pour se connecter à Speedealing.</div>',
		'CheckToCreateCouchdbDatabase' => 'Cochez cette option si la base de données n\'existe pas et doit être créée.',
		'CreateAdminUser' => 'Créer le super administrateur (Première installation de couchDB)',
		'MemcachedDescription' => 'Activer Memcached necessite l\'installation d\'un serveur Memcached et des lib php-memcached ou php-memcache. Il peut être activer après l\'installation.',
		'ServerAddressMemcachedDesc' => 'Nom ou adresse ip du serveur memcached, généralement \'localhost\' quand le serveur est installé sur la même machine que le serveur web',
		'ServerPortMemcachedDesc' => 'Port du serveur memcached. Défaut : 11211',
		'EnabledMemcached' => 'Activer Memcached',
		'DatabaseNoSQL' => 'Base de données CouchDB',
		'FailedToCreateAdminLogin' => 'Echec de la création du compte administrateur Speedealing.',
		'LinkedElementsInvalidDeleted' => '<b>%s</b> liaisons invalides ont été supprimées',
		'NothingToDelete' => 'Aucune liaison invalide trouvée',
		'SourceType' => 'Source',
		'TargetType' => 'Cible'
);
?>