<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$users = array(
		'CHARSET' => 'UTF-8',
		'UserCard' => 'Fiche utilisateur',
		'ContactCard' => 'Fiche contact',
		'GroupCard' => 'Fiche groupe',
		'NoContactCard' => 'Pas de fiche parmi les contacts',
		'Permission' => 'Droit',
		'Permissions' => 'Droits',
		'EditPassword' => 'Modifier mot de passe',
		'SendNewPassword' => 'Régénérer et envoyer mot de passe',
		'ReinitPassword' => 'Régénérer mot de passe',
		'PasswordChangedTo' => 'Mot de passe modifié en: %s',
		'SubjectNewPassword' => 'Votre mot de passe pour Speedealing',
		'AvailableRights' => 'Permissions disponibles',
		'OwnedRights' => 'Permissions détenues',
		'GroupRights' => 'Permissions groupe',
		'UserRights' => 'Permissions utilisateur',
		'UserGUISetup' => 'Interface utilisateur',
		'DisableUser' => 'Désactiver',
		'DisableAUser' => 'Désactiver un utilisateur',
		'DeleteUser' => 'Supprimer',
		'DeleteAUser' => 'Supprimer un utilisateur',
		'DisableGroup' => 'Désactiver',
		'DisableAGroup' => 'Désactiver un groupe',
		'EnableAUser' => 'Réactiver un utilisateur',
		'EnableAGroup' => 'Réactiver un groupe',
		'DeleteGroup' => 'Supprimer',
		'DeleteAGroup' => 'Supprimer un groupe',
		'ConfirmDisableUser' => 'Êtes-vous sûr de vouloir désactiver l\'utilisateur <b>%s</b> ?',
		'ConfirmDisableGroup' => 'Êtes-vous sûr de vouloir désactiver le groupe <b>%s</b> ?',
		'ConfirmDeleteUser' => 'Êtes-vous sûr de vouloir supprimer l\'utilisateur <b>%s</b> ?',
		'ConfirmDeleteGroup' => 'Êtes-vous sûr de vouloir supprimer le groupe <b>%s</b> ?',
		'ConfirmEnableUser' => 'Êtes-vous sûr de vouloir réactiver l\'utilisateur <b>%s</b> ?',
		'ConfirmEnableGroup' => 'Êtes-vous sûr de vouloir réactiver le groupe <b>%s</b> ?',
		'ConfirmReinitPassword' => 'Êtes-vous sûr de vouloir générer un nouveau mot de passe pour l\'utilisateur <b>%s</b> ?',
		'ConfirmSendNewPassword' => 'Êtes-vous sûr de vouloir générer et envoyer un nouveau mot de passe pour l\'utilisateur <b>%s</b> ?',
		'NewUser' => 'Nouvel utilisateur',
		'CreateUser' => 'Créer l\'utilisateur',
		'SearchAGroup' => 'Rechercher un groupe',
		'SearchAUser' => 'Rechercher un utilisateur',
		'LoginNotDefined' => 'Le login n\'est pas défini.',
		'NameNotDefined' => 'Le nom n\'est pas défini.',
		'ListOfUsers' => 'Liste des utilisateurs',
		'Administrator' => 'Administrateur',
		'SuperAdministrator' => 'Super Administrateur',
		'SuperAdministratorDesc' => 'Administrateur global',
		'AdministratorDesc' => 'Administrateur de l\'entité',
		'DefaultRights' => 'Permissions par défaut',
		'DefaultRightsDesc' => 'Définissez ici les permissions <u>par défaut</u>, c\'est-à-dire les permissions qui seront attribuées automatiquement à un <u>nouvel</u> utilisateur lors de sa création (Voir la fiche utilisateur pour changer les permissions d\'un utilisateur existant).',
		'SpeedealingUsers' => 'Speedealing users',
		'LastName' => 'Nom',
		'FirstName' => 'Prénom',
		'ListOfGroups' => 'Liste des groupes',
		'NewGroup' => 'Nouveau groupe',
		'CreateGroup' => 'Créer le groupe',
		'RemoveFromGroup' => 'Supprimer du groupe',
		'PasswordChangedAndSentTo' => 'Mot de passe changé et envoyé à <b>%s</b>.',
		'PasswordChangeRequestSent' => 'Demande de changement de mot de passe pour <b>%s</b> envoyée à <b>%s</b>.',
		'MenuUsersAndGroups' => 'Utilisateurs & Groupes',
		'LastGroupsCreated' => 'Les %s derniers groupes créés',
		'LastUsersCreated' => 'Les %s derniers utilisateurs créés',
		'ShowGroup' => 'Afficher groupe',
		'ShowUser' => 'Afficher utilisateur',
		'NonAffectedUsers' => 'Utilisateurs non affectés au groupe',
		'UserModified' => 'Utilisateur correctement modifié',
		'GroupModified' => 'Groupe correctement modifié',
		'PhotoFile' => 'Fichier photo',
		'UserWithSpeedealingAccess' => 'User with Speedealing access',
		'ListOfUsersInGroup' => 'Liste des utilisateurs dans ce groupe',
		'ListOfGroupsForUser' => 'Liste des groupes pour cet utilisateur',
		'UsersToAdd' => 'Utilisateur à ajouter à ce groupe',
		'GroupsToAdd' => 'Groupes à ajouter pour cet utilisateur',
		'NoLogin' => 'Pas de login',
		'LinkToCompanyContact' => 'Lien tiers / contact',
		'LinkedToSpeedealingMember' => 'Link to member',
		'LinkedToSpeedealingUser' => 'Link to Speedealing user',
		'LinkedToSpeedealingThirdParty' => 'Link to Speedealing third party',
		'CreateSpeedealingLogin' => 'Create a user',
		'CreateSpeedealingThirdParty' => 'Create a third party',
		'LoginAccountDisable' => 'Le compte est désactivé, mettre un nouveau login pour l\'activer.',
		'LoginAccountDisableInSpeedealing' => 'Account disabled in Speedealing.',
		'LoginAccountDisableInLdap' => 'Le compte est désactivé sur le domaine.',
		'UsePersonalValue' => 'Utiliser valeur personnalisée',
		'GuiLanguage' => 'Langage de l\'interface',
		'InternalUser' => 'Utilisateur interne',
		'MyInformations' => 'Mes informations',
		'ExportDataset_user_1' => 'Utilisateurs Speedealing et attributs',
		'DomainUser' => 'Utilisateur du domaine %s',
		'Reactivate' => 'Réactiver',
		'CreateInternalUserDesc' => 'Cet écran permet de créer un utilisateur interne à votre société/institution. Pour créer un utilisateur externe (client, fournisseur, ...), utiliser le bouton \'Créer utilisateur Speedealing\' qui se trouve sur la fiche contact du tiers en question.',
		'InternalExternalDesc' => 'Un utilisateur <b>interne</b> est un utilisateur appartenant à votre société/institution.<br>Un utilisateur <b>externe</b> est un utilisateur client, fournisseur ou autre.<br><br>Dans les 2 cas, les permissions utilisateurs définissent les droits d\'accès mais l\'utilisateur externe peut en plus avoir un gestionnaire de menu différent de l\'utilisateur interne (Voir Accueil - Configuration - Affichage)',
		'PermissionInheritedFromAGroup' => 'La permission est accordée car héritée d\'un groupe auquel appartient l\'utilisateur.',
		'Inherited' => 'Hérité',
		'UserWillBeInternalUser' => 'L\'utilisateur créé sera un utilisateur interne (car non lié à un tiers en particulier)',
		'UserWillBeExternalUser' => 'L\'utilisateur créé sera un utilisateur externe (car lié à un tiers en particulier)',
		'IdPhoneCaller' => 'Id appelant (téléphone)',
		'UserLogged' => 'Connexion utilisateur %s',
		'UserLogoff' => 'Déconnexion utilisateur %s',
		'NewUserCreated' => 'Création utilisateur %s',
		'NewUserPassword' => 'Changement mot de passe de %s',
		'EventUserModified' => 'Modification utilisateur %s',
		'UserDisabled' => 'Désactivation utilisateur %s',
		'UserEnabled' => 'Activation utilisateur %s',
		'UserDeleted' => 'Suppression utilisateur %s',
		'NewGroupCreated' => 'Création groupe %s',
		'GroupModified' => 'Groupe correctement modifié',
		'GroupDeleted' => 'Suppression groupe %s',
		'ConfirmCreateContact' => 'Êtes-vous sûr de vouloir créer un compte Speedealing pour ce contact ?',
		'ConfirmCreateLogin' => 'Êtes-vous sûr de vouloir créer un compte Speedealing pour cet adhérent ?',
		'ConfirmCreateThirdParty' => 'Êtes-vous sûr de vouloir créer un tiers pour cet adhérent ?',
		'LoginToCreate' => 'Login à créer',
		'NameToCreate' => 'Nom du tiers à créer',
		'YourRole' => 'Vos rôles',
		'YourQuotaOfUsersIsReached' => 'Votre quota d\'utilisateurs actifs est atteint !',
		'NbOfUsers' => 'Nb d\'utilisateurs',
		'DontDowngradeSuperAdmin' => 'Seul un superadmin peut rétrograder un superadmin',
		'NewDatabase' => 'Nouvelle base de données',
		'CreateDatabase' => 'Créer la base de données',
		'ListOfDatabases' => 'Liste des bases de données',
		'ListOfUsersInDatabase' => 'Liste des utilisateurs liés à la base de données',
		'ListOfRolesInDatabase' => 'Liste des groupes liés à la base de données',
		'DeleteADatabase' => 'Suppression d\'une database',
		'ConfirmDatabase' => 'Êtes-vous sûr de vouloir supprimer la base de données <b>%s</b> ?',
		'NonAffectedGroupsDatabase' => 'Groupes non affectés à la base de données',
		'NonAffectedUsersDatabase' => 'Utilisateurs non affectés à la base de données',
		'Collaborators' => 'Collaborateurs',
		'Profiles' => 'Profils collaborateurs'
);
?>