<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$compta = array(
		'CHARSET' => 'UTF-8',
		'Accountancy' => 'Raamatupidamine',
		'AccountancyCard' => 'Raamatupidamine kaart',
		'Treasury' => 'Riigikassa',
		'MenuFinancial' => 'Finants-',
		'TaxModuleSetupToModifyRules' => 'Mine <a href="%s">mooduli seadistuse</a> muutmiseks arvutamise eeskirjad',
		'OptionMode' => 'Võimalus raamatupidamine',
		'OptionModeTrue' => 'Võimalus Sissetulekud-kulud',
		'OptionModeVirtual' => 'Võimalus Nõuded, võlad',
		'OptionModeTrueDesc' => 'Selles kontekstis käive arvutatakse maksed (kuupäev maksed). \ NThe kehtivuse arvud on tagatud ainult siis, kui raamatupidamine on uurinud läbi sisend / väljund kontodel kaudu arveid.',
		'OptionModeVirtualDesc' => 'Selles kontekstis käive arvutatakse arvete (kinnitamise kuupäev). Kui need arved on tingitud, kas need on makstud või mitte, need on loetletud käibe toodangut.',
		'FeatureIsSupportedInInOutModeOnly' => 'Funktsioon saadaval ainult CREDITS-võlad raamatupidamise režiimis (vt Raamatupidamise mooduli konfiguratsiooni)',
		'VATReportBuildWithOptionDefinedInModule' => 'Summad on näidatud siin arvutatakse eeskirjade määratletud Maksu moodul setup.',
		'Param' => 'Setup',
		'RemainingAmountPayment' => 'Summa makse jäänud:',
		'AmountToBeCharged' => 'Kogusumma maksma:',
		'AccountsGeneral' => 'Raamatupidamise',
		'Account' => 'Konto',
		'Accounts' => 'Raamatupidamise',
		'Accountparent' => 'Account parent',
		'Accountsparent' => 'Accounts parent',
		'BillsForSuppliers' => 'Arveid, mille alusel tarnijad',
		'Income' => 'Tulu',
		'Outcome' => 'Kulu',
		'ReportInOut' => 'Tulu / Kulu',
		'ReportTurnover' => 'Käive',
		'PaymentsNotLinkedToInvoice' => 'Maksed ei ole seotud ühegi arve, nii et ei ole seotud kolmanda osapoole',
		'PaymentsNotLinkedToUser' => 'Maksed ei ole seotud ühegi kasutaja',
		'Profit' => 'Kasum',
		'Balance' => 'Saldo',
		'Debit' => 'Deebet',
		'Credit' => 'Krediit',
		'Withdrawal' => 'Tagasivõtmine',
		'Withdrawals' => 'Väljamakseid',
		'AmountHTVATRealReceived' => 'Net kogutud',
		'AmountHTVATRealPaid' => 'Net makstud',
		'VATToPay' => 'VAT müüb',
		'VATReceived' => 'Laekuv käibemaks',
		'VATToCollect' => 'VAT ostud',
		'VATSummary' => 'VAT Balance',
		'LT2SummaryES' => 'IRPF Balance',
		'VATPaid' => 'Makstud käibemaksu',
		'LT2PaidES' => 'IRPF Paide',
		'LT2CustomerES' => 'IRPF müük',
		'LT2SupplierES' => 'IRPF ostud',
		'VATCollected' => 'Kogutud käibemaks',
		'ToPay' => 'Maksma',
		'ToGet' => 'Tagasi saada',
		'TaxAndDividendsArea' => 'Maksu-, sotsiaalmaksu ja dividendid ala',
		'SocialContribution' => 'Sotsiaalmaksu',
		'SocialContributions' => 'Sotsiaalmakse',
		'MenuTaxAndDividends' => 'Maksud ja dividendid',
		'MenuSocialContributions' => 'Sotsiaalmakse',
		'MenuNewSocialContribution' => 'New panus',
		'NewSocialContribution' => 'Uus sotsiaalmaksu',
		'ContributionsToPay' => 'Toetused maksma',
		'AccountancyTreasuryArea' => 'Raamatupidamine / Treasury ala',
		'AccountancySetup' => 'Raamatupidamine setup',
		'NewPayment' => 'New makse',
		'Payments' => 'Maksed',
		'PaymentCustomerInvoice' => 'Tellija arve tasumise',
		'PaymentSupplierInvoice' => 'Tarnija arve maksmist',
		'PaymentSocialContribution' => 'Sotsiaalmaksu maksmise',
		'PaymentVat' => 'Käibemaksu tasumist',
		'ListPayment' => 'List maksete',
		'ListOfPayments' => 'List maksete',
		'ListOfCustomerPayments' => 'List of klient maksed',
		'ListOfSupplierPayments' => 'Loetelu pakkuja maksete',
		'DatePayment' => 'Maksekuupäev',
		'NewVATPayment' => 'New käibemaksu tasumist',
		'newLT2PaymentES' => 'New IRPF makse',
		'LT2PaymentES' => 'IRPF tasumine',
		'LT2PaymentsES' => 'IRPF Maksed',
		'VATPayment' => 'Käibemaksu tasumine',
		'VATPayments' => 'VAT Maksed',
		'SocialContributionsPayments' => 'Sotsiaalmaksu maksed',
		'ShowVatPayment' => 'Näita käibemaksu tasumist',
		'TotalToPay' => 'Kokku maksta',
		'TotalVATReceived' => 'Kokku laekuv käibemaks',
		'CustomerAccountancyCode' => 'Klientide raamatupidamise kood',
		'SupplierAccountancyCode' => 'Tarnija raamatupidamise kood',
		'AlreadyPaid' => 'Juba makstud',
		'AccountNumberShort' => 'Konto number',
		'AccountNumber' => 'Konto number',
		'NewAccount' => 'Uus konto',
		'SalesTurnover' => 'Müügikäive',
		'ByThirdParties' => 'Bu kolmandatele osapooltele',
		'ByUserAuthorOfInvoice' => 'Arve author',
		'AccountancyExport' => 'Raamatupidamine eksport',
		'ErrorWrongAccountancyCodeForCompany' => 'Bad kliendi raamatupidamise koodi %s',
		'SuppliersProductsSellSalesTurnover' => 'Käive poolt müüki tarnija tooteid.',
		'CheckReceipt' => 'Vaata tagatisraha',
		'CheckReceiptShort' => 'Vaata tagatisraha',
		'NewCheckReceipt' => 'New allahindlust',
		'NewCheckDeposit' => 'New kontrolli tagatisraha',
		'NewCheckDepositOn' => 'Loo kviitungi tagatisraha arvel: %s',
		'NoWaitingChecks' => 'Ei kontrolli ootab tagatisraha.',
		'DateChequeReceived' => 'Vaata vastuvõtmise kuupäeva',
		'NbOfCheques' => 'Nb kontrolli',
		'PaySocialContribution' => 'Maksma sotsiaalmaksu',
		'ConfirmPaySocialContribution' => 'Oled sa kindel, et tahad liigitada see sotsiaalmaksu makstud?',
		'DeleteSocialContribution' => 'Kustuta sotsiaalmaksu',
		'ConfirmDeleteSocialContribution' => 'Oled sa kindel, et soovite kustutada selle sotsiaalmaksu?',
		'ExportDataset_tax_1' => 'Sotsiaalmaksu ja makseid',
		'AnnualSummaryDueDebtMode' => 'Tasakaal tulude ja kulude, iga-aastane kokkuvõte, mode <b>%sClaims-Debt%sS</b> ütles <b>Kohustus raamatupidamist.</b>',
		'AnnualSummaryInputOutputMode' => 'Tasakaal tulude ja kulude, iga-aastane kokkuvõte, mode <b>%sIncomes-Expense%sS</b> ütles <b>kassapõhist raamatupidamisarvestust.</b>',
		'AnnualByCompaniesDueDebtMode' => 'Tasakaal tulude ja kulude, detail kolmandate isikute poolt, mode <b>%sClaims-Debt%sS</b> ütles <b>Kohustus raamatupidamist.</b>',
		'AnnualByCompaniesInputOutputMode' => 'Tasakaal tulude ja kulude, detail kolmandate isikute poolt, mode <b>%sIncomes-Expense%sS</b> ütles <b>kassapõhist raamatupidamisarvestust.</b>',
		'SeeReportInInputOutputMode' => 'Vaata aruanne <b>%sIncomes-Expense%sS</b> ütles <b>kassapõhise raamatupidamisarvestuse</b> jaoks arvutus tegelike maksete',
		'SeeReportInDueDebtMode' => 'Vaata aruanne <b>%sClaims-Debt%sS</b> ütles <b>pühendumust moodustas</b> arvutuste väljastatud arved',
		'RulesResultDue' => '- Summad on näidatud on koos kõigi maksudega <br> - See sisaldab tasumata arved, kulud ja käibemaks, kas need on tasutud või mitte. <br> - See põhineb kinnitamise päevast arved ja käibemaksu ning tähtpäev kulud.',
		'RulesResultInOut' => '- Summad on näidatud on koos kõigi maksudega <br> - See sisaldab päris tehtavaid väljamakseid arveid, kulud ja käibemaks. <br> - See põhineb maksmise kuupäevad arved, kulud ANF käibemaksuga. <br>',
		'RulesCADue' => '- See sisaldab kliendi tõttu arved, kas need on tasutud või mitte. <br> - See põhineb kinnitamise kuupäev need arved. <br>',
		'RulesCAIn' => '- See sisaldab kõiki tõhus arvete maksmine saadud kliendid. <br> - See põhineb maksepäeva nende arvete <br>',
		'DepositsAreNotIncluded' => '- Hoiuste arveid ega kuulu',
		'DepositsAreIncluded' => '- Hoiuste arved kuuluvad',
		'LT2ReportByCustomersInInputOutputModeES' => 'Aruanne kolmandate isikute IRPF',
		'VATReportByCustomersInInputOutputMode' => 'Raport kliendi poolt kogutud käibemaks ja makstud (käibemaks kätte)',
		'VATReportByCustomersInDueDebtMode' => 'Raport kliendi poolt kogutud käibemaks ja makstud (käibemaksumäär)',
		'VATReportByQuartersInInputOutputMode' => 'Aruande käibemaksupõhiste kogunud ja maksnud (käibemaks kätte)',
		'VATReportByQuartersInDueDebtMode' => 'Aruande käibemaksupõhiste kogunud ja maksnud (käibemaksumäär)',
		'SeeVATReportInInputOutputMode' => 'Vaata aru <b>%sVAT encasement%s</b> standardse arvutamine',
		'SeeVATReportInDueDebtMode' => 'Vaata aruanne <b>%sVAT on flow%s</b> jaoks arvutus valik voog',
		'RulesVATInServices' => '- Teenuste puhul Aruanne sisaldab käibemaksu määruste tegelikult laekunud või välja põhjal maksmise kuupäeva. <br> - Sest ainelist vara, et see sisaldab käibemaksu arvete alusel arve kuupäeva.',
		'RulesVATInProducts' => '- Sest ainelist vara, et see sisaldab käibemaksu arvete alusel arve kuupäeva.',
		'RulesVATDueServices' => '- Teenuste puhul Aruanne sisaldab käibemaksu arvete tõttu makstud või mitte, lähtudes arve kuupäevast.',
		'RulesVATDueProducts' => '- Sest ainelist vara, et see sisaldab käibemaksu arvetel, mis põhineb arve esitamise kuupäevast.',
		'OptionVatInfoModuleComptabilite' => 'Märkus: materiaalsed väärtused, siis tuleks kasutada tarnimise kuupäevast olla aus.',
		'PercentOfInvoice' => '%% / Arve',
		'NotUsedForGoods' => 'Ei kasutata kaupade',
		'ProposalStats' => 'Statistika ettepanekute',
		'OrderStats' => 'Statistika tellimusi',
		'InvoiceStats' => 'Statistika arveid',
		'Dispatch' => 'Saatmine',
		'Dispatched' => 'Lähetatud',
		'ToDispatch' => 'Saata',
		'ThirdPartyMustBeEditAsCustomer' => 'Kolmandale isikule peab olema defineeritud klient',
		'SellsJournal' => 'Müük Teataja',
		'PurchasesJournal' => 'Ostud Teataja',
		'DescSellsJournal' => 'Müük Teataja',
		'DescPurchasesJournal' => 'Ostud Teataja',
		'InvoiceRef' => 'Arve ref.',
		'CodeNotDef' => 'Määratlemata',
		'AddRemind' => 'Lähetamiseks kättesaadavaks summa',
		'RemainToDivide' => 'Veel saata:',
		'WarningDepositsNotIncluded' => 'Hoiuste arved ei kuulu selles versioonis seda raamatupidamise moodul.',
		'DatePaymentTermCantBeLowerThanObjectDate' => 'Payment term date can\'t be lower than object date.',
		'Pcg_version' => 'Pcg version',
		'Pcg_type' => 'Pcg type',
		'Pcg_subtype' => 'Pcg subtype',
		'Withdrawl' => 'Prélèvement',
		'Withdrawls' => 'Prélèvements',
		'ToGetBack' => 'A récupérer',
		'Journaux' => 'Journaux',
		'Piece' => 'Piece compta',
		'JournalNum' => 'Journal',
		'COMPTA_JOURNAL_SELL' => 'Numéro comptable du Journal des Achats',
		'COMPTA_JOURNAL_BUY' => 'Numéro comptable du Journal des Ventes',
		'COMPTA_PRODUCT_BUY_ACCOUNT' => 'Compte comptable par défaut pour produits achetés (si non défini sur fiche produit)',
		'COMPTA_PRODUCT_SOLD_ACCOUNT' => 'Compte comptable par défaut pour produits vendus (si non défini sur fiche produit)',
		'COMPTA_SERVICE_BUY_ACCOUNT' => 'Compte comptable par défaut pour services achetés (si non défini sur fiche service)',
		'COMPTA_SERVICE_SOLD_ACCOUNT' => 'Compte comptable par défaut pour services vendus (si non défini sur fiche service)',
		'COMPTA_VAT_ACCOUNT' => 'Compte comptable par défaut pour TVA (si non défini dans dictionnaire "Taux de TVA")',
		'COMPTA_ACCOUNT_CUSTOMER' => 'Compte comptable client par défaut (si non défini sur fiche tiers)',
		'COMPTA_ACCOUNT_SUPPLIER' => 'Compte comptable fournisseur par défaut (si non défini sur fiche tiers)',
);
?>