<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$contracts = array(
		'CHARSET' => 'UTF-8',
		'ContractsArea' => 'Lepingud ala',
		'ListOfContracts' => 'Lepingute loetelu',
		'LastContracts' => 'Last %s muutmine lepingud',
		'AllContracts' => 'Kõik lepingud',
		'ContractCard' => 'Leping kaart',
		'ContractStatus' => 'Lepingu staatus',
		'ContractStatusNotRunning' => 'Ei tööta',
		'ContractStatusRunning' => 'Töötab',
		'ContractStatusDraft' => 'Eelnõu',
		'ContractStatusValidated' => 'Valideeritud',
		'ContractStatusClosed' => 'Suletud',
		'ServiceStatusInitial' => 'Ei tööta',
		'ServiceStatusRunning' => 'Töötab',
		'ServiceStatusNotLate' => 'Töötab, ei ole lõppenud',
		'ServiceStatusNotLateShort' => 'Ole lõppenud',
		'ServiceStatusLate' => 'Jooksmine, aegunud',
		'ServiceStatusLateShort' => 'Lõppenud',
		'ServiceStatusClosed' => 'Suletud',
		'ServicesLegend' => 'Teenused legend',
		'Contracts' => 'Lepingud',
		'Contract' => 'Leping',
		'NoContracts' => 'Lepinguid',
		'MenuServices' => 'Teenused',
		'MenuInactiveServices' => 'Teenused ole aktiivne',
		'MenuRunningServices' => 'Running teenused',
		'MenuExpiredServices' => 'Aegunud teenused',
		'MenuClosedServices' => 'Suletud teenused',
		'NewContract' => 'Uus leping',
		'AddContract' => 'Lisa leping',
		'SearchAContract' => 'Otsi leping',
		'DeleteAContract' => 'Kustuta leping',
		'CloseAContract' => 'Sulge leping',
		'ConfirmDeleteAContract' => 'Oled sa kindel, et soovite kustutada selle lepingu ja kõigi selle teenuseid?',
		'ConfirmValidateContract' => 'Oled sa kindel, et soovid, et kinnitada käesoleva lepingu?',
		'ConfirmCloseContract' => 'Sulgeb kõik teenused (aktiivne või mitte). Oled sa kindel, et soovid lõpetada käesoleva lepingu?',
		'ConfirmCloseService' => 'Oled sa kindel, et tahad sulgeda selle teenuse koos kuupäeva <b>%s?</b>',
		'ValidateAContract' => 'Kinnitada leping',
		'ActivateService' => 'Aktiveeri teenus',
		'ConfirmActivateService' => 'Oled kindel, et soovite aktiveerida seda teenust koos kuupäeva <b>%s?</b>',
		'RefContract' => 'Contract reference',
		'DateContract' => 'Lepingu kuupäev',
		'DateServiceActivate' => 'Teenuse aktiveerimine kuupäev',
		'DateServiceUnactivate' => 'Teenuse deaktiveerimine kuupäev',
		'DateServiceStart' => 'Kuupäeva alguseks teenus',
		'DateServiceEnd' => 'Kuupäeva lõppu teenus',
		'ShowContract' => 'Näita leping',
		'ListOfServices' => 'Teenuste loetelu',
		'ListOfInactiveServices' => 'Loetelu ei ole aktiivne teenused',
		'ListOfExpiredServices' => 'List of lõppenud aktiivne teenused',
		'ListOfClosedServices' => 'Nimekiri suletud teenused',
		'ListOfRunningContractsLines' => 'List töötab lepingu read',
		'ListOfRunningServices' => 'List töötab teenused',
		'NotActivatedServices' => 'Passiivne teenused (sh kinnitatud lepingud)',
		'BoardNotActivatedServices' => 'Teenuste aktiveerimiseks seas kinnitatud lepingud',
		'LastContracts' => 'Last %s muutmine lepingud',
		'LastActivatedServices' => 'Last %s aktiveeritud teenused',
		'LastModifiedServices' => 'Last %s muutmine teenused',
		'EditServiceLine' => 'Edit teenuse rida',
		'ContractStartDate' => 'Alguskuupäev',
		'ContractEndDate' => 'Lõppkuupäev',
		'DateStartPlanned' => 'Kavandatav alguskuupäev',
		'DateStartPlannedShort' => 'Kavandatav alguskuupäev',
		'DateEndPlanned' => 'Planeeritud lõppkuupäev',
		'DateEndPlannedShort' => 'Planeeritud lõppkuupäev',
		'DateStartReal' => 'Real alguskuupäev',
		'DateStartRealShort' => 'Real alguskuupäev',
		'DateEndReal' => 'Real lõppkuupäev',
		'DateEndRealShort' => 'Real lõppkuupäev',
		'NbOfServices' => 'Nb teenuste',
		'CloseService' => 'Sulge teenus',
		'ServicesNomberShort' => '%s teenus (t)',
		'RunningServices' => 'Running teenused',
		'BoardRunningServices' => 'Aegunud töötab teenused',
		'ServiceStatus' => 'Status teenuse',
		'DraftContracts' => 'Mustandid lepingud',
		'CloseRefusedBecauseOneServiceActive' => 'Leping ei saa sulgeda kui seal on vähemalt üks teenuse peal',
		'CloseAllContracts' => 'Sulge kõik lepingu read',
		'DeleteContractLine' => 'Kustuta lepingu rida',
		'ConfirmDeleteContractLine' => 'Oled sa kindel, et soovite kustutada selle lepingu piiri?',
		'MoveToAnotherContract' => 'Liiguta teenust teise lepingu.',
		'ConfirmMoveToAnotherContract' => 'Ma valis uue eesmärgi leping ja kinnitage ma tahan minna seda teenust sellesse leping.',
		'ConfirmMoveToAnotherContractQuestion' => 'Vali, kus senise lepingu (kokku samale kolmandale isikule), mida soovite teisaldada seda teenust?',
		'PaymentRenewContractId' => 'Pikendada lepingu (number %s)',
		'ExpiredSince' => 'Aegumistähtaeg',
		'RelatedContracts' => 'Seotud lepingud',
		'NoExpiredServices' => 'Ei möödunud aktiivne teenused',
		////////// Types de contacts //////////
		'TypeContact_contrat_internal_SALESREPSIGN' => 'Müügiesindaja allkirjastades lepingu',
		'TypeContact_contrat_internal_SALESREPFOLL' => 'Müügiesindaja järelmeetmeid leping',
		'TypeContact_contrat_external_BILLING' => 'Arved kliendi kontaktandmed',
		'TypeContact_contrat_external_CUSTOMER' => 'Järelmeetmete kliendikontakti',
		'TypeContact_contrat_external_SALESREPSIGN' => 'Allkirjastades lepingu kliendikontakti',
		'Error_CONTRACT_ADDON_NotDefined' => 'Pidev CONTRACT_ADDON ole määratletud'
);
?>