<?php
/* Copyright (C) 2012	Regis Houssin	<regis.houssin@capnetworks.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$stocks = array(
		'CHARSET' => 'UTF-8',
		'WarehouseCard' => 'Warehouse kaart',
		'Warehouse' => 'Ladu',
		'Warehouses' => 'Warehouses',
		'NewWarehouse' => 'Uus ladu / laopinda',
		'WarehouseEdit' => 'Muuda ladu',
		'MenuNewWarehouse' => 'Uus ladu',
		'WarehouseOpened' => 'Ladu avatud',
		'WarehouseClosed' => 'Ladu suletud',
		'WarehouseSource' => 'Allikas ladu',
		'WarehouseSourceNotDefined' => 'No warehouse defined,',
		'AddOne' => 'Add one',
		'WarehouseTarget' => 'Target ladu',
		'ValidateSending' => 'Kustuta saatmine',
		'CancelSending' => 'Tühista saatmine',
		'DeleteSending' => 'Kustuta saatmine',
		'Stock' => 'Varu',
		'Stocks' => 'Varud',
		'Movement' => 'Liikumine',
		'Movements' => 'Liikumised',
		'ErrorWarehouseRefRequired' => 'Warehouse viite nimi on nõutav',
		'ErrorWarehouseLabelRequired' => 'Warehouse etikett nõutav',
		'CorrectStock' => 'Õige varude',
		'ListOfWarehouses' => 'Ladude nimistu',
		'ListOfStockMovements' => 'List of veeremiliikumiste',
		'StocksArea' => 'Varud ala',
		'Location' => 'Asukoht',
		'LocationSummary' => 'Lühinimi asukoht',
		'NumberOfProducts' => 'Koguarv tooted',
		'LastMovement' => 'Viimati liikumine',
		'LastMovements' => 'Last liikumised',
		'Units' => 'Units',
		'Unit' => 'Üksus',
		'StockCorrection' => 'Õige varude',
		'StockMovement' => 'Üle',
		'StockMovements' => 'Stock ülekandeid',
		'NumberOfUnit' => 'Ühikute arv',
		'UnitPurchaseValue' => 'Unit purchase price',
		'TotalStock' => 'Kokku varude',
		'StockTooLow' => 'Stock liiga madal',
		'StockLowerThanLimit' => 'Stock lower than alert limit',
		'EnhancedValue' => 'Väärtus',
		'PMPValue' => 'Kaalutud keskmine hind',
		'PMPValueShort' => 'WAP',
		'EnhancedValueOfWarehouses' => 'Laod väärtus',
		'UserWarehouseAutoCreate' => 'Loo lattu automaatselt luua kasutaja',
		'QtyDispatched' => 'Lähetatud kogused',
		'OrderDispatch' => 'Stock ekspedeerimine',
		'RuleForStockManagementDecrease' => 'Reeglina varude juhtimise vähenemine',
		'RuleForStockManagementIncrease' => 'Reegel varude haldamist tõusu',
		'DeStockOnBill' => 'Väheneb reaalne varud klientidele arveid / kreeditarvete kinnitamine',
		'DeStockOnValidateOrder' => 'Väheneb reaalne varud klientidele tellimuste kinnitamine',
		'DeStockOnShipment' => 'Väheneb reaalne varude vedu kinnitamine',
		'ReStockOnBill' => 'Suurendada tõeline varud tarnijate arved / kreeditarvete kinnitamine',
		'ReStockOnValidateOrder' => 'Suurendada tõeline varude tarnijatele tellimusi aprobatsioon',
		'ReStockOnDispatchOrder' => 'Suurendada tõeline varude käsitsi ekspedeerimine arvesse ladude, pärast tarnija et saavad',
		'OrderStatusNotReadyToDispatch' => 'Selleks ei ole veel või enam staatust, mis võimaldab lähetamine toodete varude laod.',
		'StockDiffPhysicTeoric' => 'Põhjus erinevus varude füüsilise ja teoreetiline',
		'NoPredefinedProductToDispatch' => 'Ei eelnevalt tooted Selle objekti. Nii ei ekspedeerimine varude vaja.',
		'DispatchVerb' => 'Lähtekoha',
		'StockLimitShort' => 'Piirama',
		'StockLimit' => 'Stock tähtaeg teateid',
		'PhysicalStock' => 'Inventuuride',
		'RealStock' => 'Real Stock',
		'TheoreticalStock' => 'Therocial varu',
		'VirtualStock' => 'Virtual varu',
		'MininumStock' => 'Miinimumvaru',
		'StockUp' => 'Varuma',
		'MininumStockShort' => 'Stock min',
		'StockUpShort' => 'Varuma',
		'IdWarehouse' => 'Id ladu',
		'DescWareHouse' => 'Kirjeldus ladu',
		'LieuWareHouse' => 'Lokaliseerimine ladu',
		'WarehousesAndProducts' => 'Laod ja tooted',
		'AverageUnitPricePMPShort' => 'Kaalutud keskmine sisendi hind',
		'AverageUnitPricePMP' => 'Kaalutud keskmine sisendi hind',
		'SellPriceMin' => 'Müük Ühiku Hind',
		'EstimatedStockValueSellShort' => 'Väärtust müüa',
		'EstimatedStockValueSell' => 'Väärtus müüa',
		'EstimatedStockValueShort' => 'Sisend aktsia väärtus',
		'EstimatedStockValue' => 'Sisend aktsia väärtus',
		'DeleteAWarehouse' => 'Kustuta ladu',
		'ConfirmDeleteWarehouse' => 'Oled sa kindel, et soovite kustutada lattu <b>%s?</b>',
		'PersonalStock' => 'Isiklik varu %s',
		'ThisWarehouseIsPersonalStock' => 'See ladu esindab isiklikku varu %s %s',
		'SelectWarehouseForStockDecrease' => 'Vali lattu kasutada varude vähenemine',
		'SelectWarehouseForStockIncrease' => 'Vali lattu kasutada varude kasv',
		'LastWaitingSupplierOrders' => 'Orders waiting for receptions'
);
?>